lib/puppet/provider/mailalias/aliases.rb
lib/puppet/type/mailalias.rb
spec/fixtures/integration/provider/mailalias/aliases/test1
spec/unit/type/mailalias_spec.rb

The mailalias type does not allow the specification of included files,
which contain an alias's elements. Such alias entries are commonly
specified in the an MTA's aliases file through the following syntax.
aliasname: :include: /path/to/file
Specifying the rest of an ":include:" line as a recipient does not
work, because the existing mailalias type will quote the entry.
This change adds a new parameter named "file" to the mailalias type,
which allows the indirect specification of a file containing the
recipients.  The parameter parses and generates ":include:" alias entries.
Also, as recommended by @joshcooper, remove legacy unneeded "should" from
recipient property implementation.  This fixes a gratuitous difference
between the new file property implementation and the recipient property …

(PUP-3750) Support :include: in mailalias type

---

spec/unit/type/mailalias_spec.rb

Used Linux-style paths while requiring that they be absolute paths. Fixed
so that Windows testing uses Windows-style paths that are correctly
interpreted as absolute paths.

(PUP-3750) Fix specs on Windows

---

lib/puppet/pops/evaluator/collector_transformer.rb
spec/integration/parser/collector_spec.rb

The support for double quoted (interpolated) strings were
missing in the new implementation of collectors introduced in
PUP-2906.This was not detected since there is a parser optimization
that treats double quoted strings that does not require
interpolation as literal strings and there were no tests
that included double quited strings with interpolation of an expression.
This commit adds support for concatenated string (i.e. interpolation).

(PUP-3806) Add missing support for interpolation in collection

---

.travis.yml
spec/unit/reports/store_spec.rb

Prior to this change, this spec test failed on ruby 2.2.0-rc1 with:
Failure/Error: Time.stubs(:now).returns(Time.parse("2011-01-06 12:00:00 UTC"))
NoMethodError:
undefined method `utc_offset' for nil:NilClass
I didn't track down the root cause of this failure, but just
normalized this stub to use Time.utc, which (along with Time.local)
is the more common way of stubbing Time objects in the codebase.

(maint) Change spec test to pass on ruby 2.2

---

lib/puppet/type/scheduled_task.rb

When this is merged, please resolve DOC-1509.

(docs) Clarify meaning of `schedule` key in scheduled_task trigger hashes

---

acceptance/tests/resource/service/ticket_1343_should_add_and_remove_symlinks.rb

This fixes the acceptance test failures happening for all the
platforms this test wasn't intended for.

Confine test ticket_1343 to el-5

---

lib/puppet/provider/file/windows.rb
spec/unit/provider/file/windows_spec.rb

This change is a followup to commit 54f6159102, which added leading '0's
to ensure four-digit octal notation on file modes in the POSIX file
provider. This commit does the same for the Windows file provider.

(PUP-3787) Add leading '0' to ensure four-digit octal notation of file modes in Windows

---

ext/project_data.yaml
spec/integration/agent/logging_spec.rb
spec/unit/util/log/destinations_spec.rb

- Previously win32-eventlog 0.6.1 was referenced for the sake of
source development on Windows.  However, as part of the MSI
distribution, 0.6.1 + a critical patch for Windows 2003 is shipped.
This commit ensures that test execution is restored on Windows 2003
and that 0.6.2, which incorporates the critical fix, is used for
development from source on Windows.
The original test changes were introduced as part of PUP-2889 and
merged in as 6fdea01544f6025abf84d68d1ba9a222c87ea488

(PUP-3601) - Upgrade win32-eventlog to 0.6.2

---

lib/puppet/defaults.rb
lib/puppet/util/autoload.rb
spec/unit/util/autoload_spec.rb

Previously, it was possible to set `Puppet[:libdir]` to a list of
directories, so that the autoloader's search path could be expanded.
That behavior was added in f9e05a806.
That said, it only worked when using puppet as a library, most commonly
when executing tests for modules that depend on each other. If you ever
tried to actually run puppet with `:libdir` containing multiple
directories, puppet would try to manage/create the directory,
interpreting it as a single directory, and would fail with:
$ puppet apply -e "notice 'hi'" --libdir /tmp/a:/tmp/b
Cannot create /tmp/a:/tmp/b; parent directory /tmp/a:/tmp does not exist
This commit modifies the autoloader so that it no longer splits the
`:libdir` setting, consistent with other parts of puppet that assume
it's a single directory, e.g. …

(PUP-3336) Be consistent about a single libdir

---

lib/puppet/error.rb
lib/puppet/provider/command.rb
lib/puppet/provider/network_device.rb
lib/puppet/transaction.rb

Currently prefetch rescue all StandardError, and this results in puppet
creating resources unecessarily when prefetch fails. This patch limits
the exception handling to only rescue LoadError for rubygems, and
Puppet::MissingCommand when software packages have not been installed
yet.

(PUP-3656) Prefetch only rescue LoadError or MissingCommand

---

lib/puppet/indirector/catalog/compiler.rb
spec/unit/indirector/catalog/compiler_spec.rb

This commit undoes a change made in commit fb5f859cf4 that
causes the master to alter the agent's facts timestamp when
they are received by the catalog compiler.
With this change, the facts timestamp is always based on the
agent's time.

(PUP-3488) Stop overwriting agent's facts timestamp

---

ext/project_data.yaml

Update ffi requirement to use at least 1.9.6 because Ruby 2.1.5
requires it.

(PUP-3724) Use ffi 1.9.6

---

lib/puppet/indirector/indirection.rb
lib/puppet/indirector/request.rb
spec/unit/indirector/request_spec.rb

The `to_s` method on Puppet::Indirector::Request was removed in
fd7c4f912d3f26977863faaec91e010c9bc48abb, without realizing that it was used
to make two error messages more useful. This adds back this functionality,
renamed to `description`.

(maint) Add Puppet::Indirector::Request#description for better errors

---

spec/unit/provider/user/hpux_spec.rb

Ruby 2.1.5 on Windows does not contain Etc::Password.passwd due to not
having HAVE_STRUCT_PASSWD_PW_PASSWD defined when it was compiled -
https://github.com/ruby/ruby/blob/v2_1_5/ext/etc/etc.c#L691-L693.
Ruby 2.0.0 did not have this and passwd was not guarded by an ifdef -
https://github.com/ruby/ruby/blob/v2_0_0_598/ext/etc/etc.c#L682
This goes for both x86 and x64 versions of Ruby. Since Etc is not used
on Windows, it is safe to confine this spec to only run on POSIX
systems.

(PUP-3779) confine hpux password spec

---

lib/puppet/module_tool/skeleton/templates/generator/Gemfile

Without this change, bundler breaks if PUPPET_VERSION is specified with a curvy arrow syntax for example export PUPPET_VERSION="~> 3.6.0".
Without this change the puppet gem declaration after processing would look like 'gem "puppet", "= ~> 3.6.0"' that isn't valid syntax.

(PUP-3082) When PUPPET_VERSION="~> x.x.x" bundler breaks

---

acceptance/tests/resource/service/ticket_1343_should_add_and_remove_symlinks.rb
lib/puppet/provider/service/redhat.rb
spec/unit/provider/service/redhat_spec.rb

On RHEL/CentOS 5 systems, the use of chkconfig on to enable a service
does not create the K-symlinks in /etc/rc.d to shut down the service.
Running chkconfig --add before chkconfig on fixes this issue, and
should be harmless on the unaffected OS versions.
The rspec unit test has been updated, and a new acceptance test
included to validate the bugfix.

(PUP-1343) Use chkconfig --add to ensure K-symlinks get installed

---

lib/puppet/parser/resource.rb
lib/puppet/pops/evaluator/collector_transformer.rb
lib/puppet/util/tagging.rb
spec/unit/util/tagging_spec.rb

(PUP-3665) Make tagging arguments case insensitive
Tags are stored internally as downcased strings. All objects passed
as tags to the tagged? method where converted to strings prior to
comparison but they were not downcased. As a result, a query for
tags containing uppercase letters would always fail.
This commit adds the needed downcasing of the tags parameter. It
also introduces a new raw_tagged? method that assumes that whatever
tags that are passed to it already have been converted to strings
and downcased. This to allow the CollectorTransformer to do this
conversion once and then ask multiple resources if they are tagged.

Issue/pup 3665/make tagged case insensitive

---

lib/puppet/pops/binder/lookup.rb
lib/puppet/pops/evaluator/closure.rb

Now when the 3x AST implementation has been removed the marker
method :puppet_lambda is no longer needed. This commit replaces
the check if an argument is callable by using the type calculator
instead of checking the marker method.
The marker method was only used by the lookup function. All other such
calls have already been cleaned up.

(PUP-3313) Remove marker method puppet_lambda

---

acceptance/tests/allow_arbitrary_node_name_fact_for_agent.rb
acceptance/tests/allow_arbitrary_node_name_for_agent.rb
acceptance/tests/concurrency/ticket_2659_concurrent_catalog_requests.rb
acceptance/tests/environment/can_enumerate_environments.rb
acceptance/tests/external_ca_support/fixtures/auth.conf
acceptance/tests/node/check_woy_cache_works.rb
acceptance/tests/security/cve-2013-1652_improper_query_params.rb
acceptance/tests/security/cve-2013-2275_report_acl.rb
conf/auth.conf
lib/puppet/defaults.rb
lib/puppet/network/authconfig.rb
lib/puppet/network/http/api.rb
lib/puppet/network/http/api/v2.rb
lib/puppet/network/http/api/v3/indirected_routes.rb
lib/puppet/network/http/rack/rest.rb
lib/puppet/network/http/webrick/rest.rb
spec/unit/indirector/rest_spec.rb
spec/unit/network/authconfig_spec.rb
spec/unit/network/http/api/v2_spec.rb
spec/unit/network/http/api/v3/indirected_routes_spec.rb
spec/unit/network/http/api/v3_spec.rb
spec/unit/network/http/api_spec.rb
spec/unit/type/file/content_spec.rb

This commit support for a configurable setting `master_url_prefix`, which
defaults to `/puppet`, that the master's http endpoints are mounted at. All
requests generated by the agent honor this prefix. This will allow us to mount
the Puppet HTTP endpoints in a namespaced URL space alongside other apps
running on the same webserver.

(PUP-3645) Add support for configurable url prefix

---

acceptance/Gemfile
acceptance/bin/ci-pe-puppet.sh
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/setup/git/pre-suite/000_EnvSetup.rb
acceptance/setup/packages/pre-suite/010_Install.rb

The testing infrastucture should be resilient to network issues. For
acceptance tests that exercise the Gem provider and setup that installs
Gems, there hasn't been a clean way to specify that the internal mirror
should be used. This follows the Gemfile pattern and selects the
internal mirror if it's available.

(PUP-3839) Use PL Gem mirror in acceptance tests

---

acceptance/config/git/options.rb
acceptance/config/packages/options.rb
acceptance/lib/puppet/acceptance/rpm_util.rb
acceptance/setup/common/pre-suite/001_PkgBuildSetup.rb
acceptance/tests/resource/package/common_package_name_in_different_providers.rb
lib/puppet/resource.rb
lib/puppet/resource/catalog.rb
lib/puppet/type/package.rb
spec/integration/type/package_spec.rb

Makes package uniqueness key a composite of namevar and provider, so
packages with the same name from different providers don't collide.
Making the uniqueness_key more complex than name for packages means that
testing whether name matches title is an insufficient test for whether
to check if the resource is defined and add an alias. Now if the
resource is isomorphic and the uniqueness key is not the resource's
title, add an alias.
Adds an integration spec test for packages with a name collision, but
different providers. Having two packages with matching names but
different name-provider pairs is now allowed. Titles must still be
different.

(PUP-1073) Make package use a composite namevar

---

acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/setup/git/pre-suite/000_EnvSetup.rb

Fixes calling the gem command on Windows, which requires that Ruby is
installed first and that it be called via cmd /c.

(PUP-3839) Fix calling gem on Windows

---

lib/puppet/pops/types/type_calculator.rb
spec/unit/pops/types/type_calculator_spec.rb

This commit changes the assignable?(t1, t2) so that A Variant t2 is
assignable to t1 if all types contained in t2 are assignable to t1. A
test is also added to verify this behavior.
The commit also adds the method instance_of_PIntegerType(t, o) as
a performance improvement. There were several places where an integer
instance was checked against an existing PIntegerType. Creating an
interim type for that instance just to perform the check is expensive
and puts an unecessary load on the garbage collector.

(PUP-3461) Make Variant assignable when contained types are assignable

---

ext/vim/syntax/puppet.vim

This makes the digit in 'include apache2' use the same color.
i.e.: digits are colored only when starting a word.

Don't color numbers in class names

---

lib/puppet/pops/parser/egrammar.ra
lib/puppet/pops/parser/eparser.rb
spec/unit/pops/parser/parse_basic_expressions_spec.rb

The length of the source text associated with model elements is
important for error reporting and for the Puppet Strings documentation
tool. The grammar did not correctly produce the length of empty array
and hash expresses (they were always recorded with a length of 1).
This was caused by rules either referencing a non existant token, or by
only including the starting token in the calculation (which always leads
to a length of 1).
This commit changes the grammar's calls to associate length for the
erronous cases. Tests are also added.

(PUP-3786) Correct text length calculation of [] and {}

---

lib/puppet/resource.rb
spec/integration/parser/compiler_spec.rb
spec/integration/parser/resource_expressions_spec.rb
spec/unit/parser/compiler_spec.rb

The error message emitted when an attribute operation used
an attribute name that was invalid did not read well and caused
confusion since it did not clearly indicate that part of the message was
the name of the parameter - e.g. "invalid parameter hash" which can be
read as an invalid "parameter hash" (confusing when actually setting all
parameters from a hash and having a parameter named 'hash' in the hash).
The message is now changed to say "Invalid parameter: '<name>'". As a
consequence spec tests are updated to match this message.

(PUP-3002) Improve error message for invalid parameter name

---

lib/puppet/parser/compiler.rb
spec/integration/parser/compiler_spec.rb
spec/unit/parser/compiler_spec.rb

Without this fix, the final step of compiling a catalog for a node will
transform the produced catalog to resource form in a context that is not
configured for the environment used to compule the catalog. This can
lead to a wide variety of problems since there is a high chans that
unrelated code gets loaded and this code may have errors, may cause side
effects and cause the catalog to silently contain a result different
from the intended.
The fix is simple - the compile method now accepts a block that it
yields the produced catalog to if the block is given in a call to
compile. This is then used instead of simply calling to_resource on the
produced result.
As a conseuence of the change mocking tests were failing. As it was
found that these tests were meaningless and testing nothing they …

(PUP-3755) Make compile for a node use compiler's context for transform

---

spec/unit/util/execution_spec.rb

Execute was trying to call 'echo hello', which is invalid on Windows. Stub
execution subcalls so no process is called, making it platform independent.

(maint) Stub execute when testing debug logging

---

lib/puppet/functions.rb
lib/puppet/pops.rb
lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/evaluator/runtime3_converter.rb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/functions/function.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/callee.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/callee_ws.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/metadata.json
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/user/lib/puppet/functions/user/caller.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/user/lib/puppet/functions/user/caller_ws.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/user/metadata.json
spec/unit/pops/loaders/loaders_spec.rb

The call_function() method of the Puppet::Pops::Functions::Function
class did not make any attempt to find functions that had been
declared using the 3x function API. This commit adds the following:
Proper 3x load and execute:
The call_function() method will now consult the 3x Functions class
to find (and optionally load) the function from there when it fails
to find it using the 4x loader. The load is always performed using
the closure scope of the caller. The 3x load will fail unless the
closure_scope is of type Puppet::Parser::Scope. The scope of the
caller (which might be different from closure_scope) will be the
instance that holds the method that corresponds to the 3x function.
Propagation of caller scope:
The call_function() will pass the closure_scope as that scope of the
caller. …

(PUP-3548) Allow 4x function to call 3x function

---

.travis.yml
lib/puppet/application/epp.rb
lib/puppet/face/epp.rb
lib/puppet/pops/parser/evaluating_parser.rb
spec/unit/face/epp_face_spec.rb

This adds a new command called puppet-epp that can validate
one or several epp templates, render them to text with
various options for specifying facts and variables in scope,
giving variables to the template etc.
The command also has a dump action that is useful for debugging
epp parsing. This command is similar to the puppet parser dump
action.
For more details run 'puppet man epp' on this branch.

(PUP-2531) add epp validate and render face

---

ext/build_defaults.yaml

This PR adds updates to what is pulled in and defined for building the puppet MSI. We're changing the name of the installer, adding in mcollective, and using new automation to deal with these changes. These are all targeted at Puppet 4.

(PUP-3842,PUP-3844,PUP-3842) Updates for building the puppet windows installer

---

spec/integration/provider/ssh_authorized_key_spec.rb

Previously, the test created an instance variable named `example`, for
which rspec created a method that memoized the instance variable. The
method shadowed the `example` method on RSpec::Core::ExampleGroup, which
can lead to surprising results. For example if you add an rspec before
hook:
RSpec.configure do |config|
config.before :each do |test|
...
end
end
Then `test` will be derived from `RSpec::Core::ExampleGroup`:
(rdb:1) test.is_a? RSpec::Core::ExampleGroup
true
But if you call `test.example` it will return the memoized variable,
instead of the RSpec::Core::Example:
(rdb:2) test.example.class
Puppet::Type::Ssh_authorized_key
This commit simply renames the instance variable/method.

(maint) Rename let `example` instance variable

---

acceptance/tests/environment/broken_unassigned_environment_handled_gracefully.rb

in PUP-3755 there are two scenarios that lead to a newly classified
agent not picking up its new environment.  This test will catch the case
in which a broken but non-assigned environment is parsed and causes
errors or warnings.

(PUP-3897) Add acceptance: ensure new environment picked up by agent

---

lib/puppet/face/module/generate.rb

Before this commit, the "examples" string in the generate face still
read "Apache 2.0". After this commit, it reads "Apache-2.0" to be in
line with the behavior of puppet module generate.

(PUP-3894) Update license in PMT generate example to match SPDX string

---

lib/puppet/module_tool/tar/gnu.rb
spec/unit/module_tool/tar/gnu_spec.rb

Before this commit, file permissions on installing a module only removed
the setuid and sticky bit permissions. After this commit, file
permissions are added for read and write for the executor of the puppet
module install and read for group in addition.

(PUP-3168) Fix file permissions on puppet module install

---

.gitignore
acceptance/Gemfile
acceptance/Rakefile
acceptance/config/aio/options.rb
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/setup/aio/pre-suite/010_Install.rb
acceptance/setup/aio/pre-suite/015_PackageHostsPresets.rb
acceptance/setup/aio/pre-suite/045_EnsureMasterStartedOnPassenger.rb

This implements a new pre-suite that installs the puppet-agent (all in
one) package and add a new Rake task "ci:test:aio" to utilize the new
pre-suite.
note: there are currently failures in the pre-suite for AIO because of
issues between the AIO package and the puppet server. These are expected
to be ironed out with the dev release of puppet-server 2.0
You can see the current CI pipeline against this commit [here](https://jenkins.puppetlabs.com/view/z-temp-view-for-aio/view/puppet/job/experimental-Puppet-Package-Acceptance-master/3/)*
You can see the current AIO pipeline failing (with legit failures, but still accurately running the tests) [here](http://10.32.77.180/view/job%20development/view/All%20in%20One%20Agent/view/Integrated%20Acceptance/job/platform_puppet-agent_intn-sys_master/13/ …

(maint) Update CI Setup for AIO Testing

---

acceptance/lib/puppet/acceptance/module_utils.rb

The existing tests asserted that regular files could not be writable,
but cc51668 restored the ability for files to have more relax
permisions. This commit refactors the module permissions tests to be
more granular and handle the relaxed permissions.

(maint) Allow module files to have u=rw permissions

---

lib/puppet/application/face_base.rb
spec/unit/application/face_base_spec.rb

This makes puppet <face> --help into an alias for puppet help <face>.
And puppet <face> <action> --help into an alias for puppet help <face>
<action>.

(PUP-1103) Faces should respond to --help

---

lib/puppet/type/tidy.rb
spec/unit/type/tidy_spec.rb

Previously, a tidy resource could create a duplicate file resource due to a
mismatch between back and forward slashes on Windows.
This commit munges the tidy path parameter using File.expand_path, so on
Windows, `C:\dir` becomes `C:/dir`. When that is File.join'ed with a file
needing to be tidy'ed, the resulting path contains only forward slashes,
which is consistent with the path parameter for the file type.

(PUP-1276) Normalize tidy paths

---

acceptance/lib/puppet/acceptance/module_utils.rb
lib/puppet/module_tool/tar/mini.rb

Changes minitar file permissions to 0644 to match new gnu tar
permissions. Fixes acceptance failures in PMT install.

(PUP-3168) Change minitar permissions to match

---

lib/puppet/pops/parser/lexer2.rb
spec/unit/pops/parser/lexer2_spec.rb

The lexer treated a div after a variable or bare word as a potential
literal regular expression.
e.g.
$foo / 2 / 2 
abc-def / 2 / 2
This was caused by two entries (:VARIABLE, and :WORD) missing from the
list of tokens that do not allow a following literal regexp.

(PUP-3923) Fix lexer problem seeing regexp for div after var or word

---

lib/puppet/functions.rb
lib/puppet/pops.rb
lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/evaluator/runtime3_converter.rb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/functions/function.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/callee.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/callee_ws.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/metadata.json
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/user/lib/puppet/functions/user/caller.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/user/lib/puppet/functions/user/caller_ws.rb
spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/user/metadata.json
spec/unit/pops/loaders/loaders_spec.rb

The call_function() method of the Puppet::Pops::Functions::Function
class did not make any attempt to find functions that had been
declared using the 3x function API. This commit adds the following:
Proper 3x load and execute:
The call_function() method will now consult the 3x Functions class
to find (and optionally load) the function from there when it fails
to find it using the 4x loader. The load is always performed using
the closure scope of the caller. The 3x load will fail unless the
closure_scope is of type Puppet::Parser::Scope. The scope of the
caller (which might be different from closure_scope) will be the
instance that holds the method that corresponds to the 3x function.
Propagation of caller scope:
The call_function() will pass the closure_scope as that scope of the
caller. …

Issue/pup 3548/enable 3xcall from 4xfunction

---

lib/puppet/metatype/manager.rb
lib/puppet/util/autoload.rb

Backports [PR-2963](https://github.com/puppetlabs/puppet/pull/2963) to stable. This is just a cherry-picked
commit that caused no conflicts.

(PUP-1515) Autoload types and providers from same environment

---

lib/puppet/file_serving/content.rb
lib/puppet/file_serving/terminus_helper.rb
lib/puppet/indirector/direct_file_server.rb
lib/puppet/indirector/file_metadata/file.rb
lib/puppet/indirector/file_server.rb
spec/integration/indirector/direct_file_server_spec.rb
spec/integration/indirector/file_metadata/file_server_spec.rb
spec/shared_contexts/checksum.rb
spec/shared_contexts/digests.rb
spec/unit/file_serving/content_spec.rb
spec/unit/file_serving/metadata_spec.rb
spec/unit/file_serving/terminus_helper_spec.rb
spec/unit/indirector/direct_file_server_spec.rb
spec/unit/indirector/file_metadata/file_spec.rb
spec/unit/indirector/file_server_spec.rb

The file_server uses the requested checksum_type to calculate a
file checksum, rather than always defaulting to md5.

(PUP-3887) Fix checksum and source_permissions option in file servers

---

lib/puppet/network/http/api/indirected_routes.rb
spec/unit/network/http/api/indirected_routes_spec.rb

The PR for PUP-3644 moved the `check_authorization` call for
indirected routes to a spot before the environment for a request is
translated into a `Puppet::Node::Environment` instance in the request
params.  This caused any restrictions on environment made in an
auth.conf file to inappropriately reject all requests matching the
rule path, even ones that should have been allowed.
This PR moves the `check_authorization` call back to a spot in the
code after the translation to an `Puppet::Node:::Environment` instance
occurs.  This change restores the ability for an environment value in
the auth.conf to appropriately allow/deny access for requests.

(PUP-3855) Restore ability for auth.conf to restrict on environment

---

lib/puppet/type/file/source.rb
lib/puppet/util/checksums.rb
spec/integration/type/file_spec.rb
spec/shared_contexts/checksum.rb
spec/unit/type/file/source_spec.rb
spec/unit/util/checksums_spec.rb

When checking whether the local file must be modified, ensure the metadata
includes the requested checksum, rather than defaulting to md5.
Streaming checksums are compared to file checksums, so they must behave
the same way on a stream that is being written to a file.

(PUP-3889) Fix checksums writing files

---

lib/puppet/functions.rb
spec/unit/functions4_spec.rb

Previously, a block parameter was not added to the weaving array
which resulted in it being omitted by the weaving logic. This
commit ensures two things.
1. No parameters can be added after a block parameter.
2. The index of the block parameter (size of the names array)
is added to the weaving array.
A test is also added that tests combining injection with a required block
parameter.

(PUP-3936) Ensure that weaving logic is aware of block

---

api/docs/http_file_content.md
lib/puppet/file_bucket/file.rb
lib/puppet/file_serving/content.rb
lib/puppet/network/formats.rb
lib/puppet/type/file/content.rb
spec/lib/puppet/indirector_testing.rb
spec/unit/file_bucket/file_spec.rb
spec/unit/file_serving/content_spec.rb
spec/unit/network/formats_spec.rb
spec/unit/network/http/api/indirected_routes_spec.rb

Previously the MIME type that the filebucket endpoints used to transfer
data was `text/plain`. This leads to potential problems transfering
binary data. This commit adds a new format called `:binary` which uses
`application/octet-stream` as the MIME type, which is the correct type
to specify arbitrary binary data.

(PUP-3812) Change file_bucket content type to application/octet-stream

---

acceptance/tests/pluginsync/3935_pluginsync_should_follow_symlinks.rb
lib/puppet/configurer/downloader.rb
spec/unit/configurer/downloader_spec.rb

Currently, Puppet produces one of two pluginsync errors during an
agent run if the root of a modulepath directory is a symlink
and no modules contain a facts.d or lib directory.
In the normal case, when the base module path is a directory
and none if its modules include facts.d or lib directories,
pluginsync returns the path to the module path directory itself,
at which point the file type disables recursion in its
`recurse_remote` method and stops the agent from attempting to
download plugins.
However, if the base module path is not a directory (in this case
a link), `recurse_remote` returns early, causing the agent-side
facts.d or lib directory to not have its 'source' metadata set,
leading to a failing query back to the master.
This commit forces pluginsync to follow symlinks rather …

(PUP-3935) Fix pluginsync errors when dealing with symlinks

---

ext/redhat/puppet.spec.erb

This commit updates the RPM packaging specfile for pathing
changes brought in by the all-in-one agent switchover.

(PUP-3632) Update RPM packaging spec for AIO changes

---

lib/puppet/type/file.rb
spec/shared_contexts/checksum.rb
spec/unit/type/file/content_spec.rb

Fixes writing a file from content for a non-default checksum type when
the content is initialized as part of creating a file resource.
Fix applies to both puppet apply and puppet agent runs.

(PUP-3898) Fix writing content with checksum

---

lib/puppet/module.rb
lib/puppet/module_tool.rb
spec/unit/module_spec.rb
spec/unit/module_tool_spec.rb

Prior to this commit, we had undocumented support for
'versionRequirement' instead of 'version_requirement' for a dependency
in the metadata.json. This support was created because an old version
of Gepetto inadvertently gave this as the field key. With this commit,
we remove the support for that undocumented field.

(PUP-777) Remove 'versionRequirement' for dependencies

---

lib/puppet/module.rb
spec/unit/module_spec.rb

Previously, if a module had a dependency named "puppetlabs-stdlib", it
would call `Environment.module_by_forge_name` with that name, but that
method expects names to be of the form `author/name`.
This commit translates the name prior to making the call.

(PUP-3121) Lookup dependencies by forge name

---

acceptance/setup/git/pre-suite/000_EnvSetup.rb

- Update the pointers to the puppet-win32-ruby to the appropriate
SHAs so that Windows acceptance tests can run against Ruby 2.1.5

(PUP-3818) Windows acceptance on Ruby 2.1.5

---

acceptance/tests/modules/build/build_basic.rb

PMT is no longer using the Modulefile and the acceptance test needed to be
updated to use a "metadata.json" file instead. Also, the test has been
updated with current Beaker syntax in increase readability.

(CODEMGMT-69) Update Acceptance Test

---

Gemfile
ext/project_data.yaml

Bump Facter up to at least 2.0 but less than 4 to allow for Facter
3, which is expected to be out during Puppet 4.x series. Bump Hiera
to allow it to take a dependency from 1.0 but less than 3. Without
this change Facter 3.x and Hiera 2.x will not be able to be
resolved as dependencies.

(PUP-3848) Bump Facter/Hiera dependencies

---

lib/puppet/type/file.rb
spec/integration/type/file_spec.rb
spec/unit/type/file_spec.rb

When copying a directory from a source with recurse enabled, any files
copied this way would be forced to the configured default. That meant
they're copied every time you initialize the resource, even if already
present.
This fix lets the files be managed by the checksum property on the
resource. It also updates a prior spec test that confirmed the previous
hack that was required to work around checksums failing to be copied
across the indirector.

(PUP-3945) Fix checksum recursing directories

---

docs/quickstart.md
spec/spec_helper.rb

When tests are failing, it is often useful to capture Puppet's logs of the
test run. This change makes it possible to send the log to a file, and to
adjust Puppet's log level.
Thanks to Josh Cooper for pointing out how to do this

(maint) Make it possible to capture logs of test runs

---

lib/puppet/network/http.rb
lib/puppet/network/http/api.rb
lib/puppet/network/http/rack/rest.rb
lib/puppet/network/http/webrick/rest.rb
spec/unit/network/http/api_spec.rb

Add a 404 error that is triggered when requests are made to
routes without the /puppet or /puppet-ca prefixes to indicate
to the user that they may need to upgrade Puppet on their
agents.
This is a new PR addressing the same ticket as https://github.com/puppetlabs/puppet/pull/3532, which I am closing in favor of this one.

(PUP-3921) Add 404 error suggesting an upgrade

---

lib/puppet/util/windows/api_types.rb
lib/puppet/util/windows/registry.rb
spec/unit/util/windows/api_types_spec.rb

- Previously, only Windows API calls that were Registry related had
the Encoding set to UTF_8 at their individual callsites.  Change the
default from Encoding.default_external (which matched previous
Puppet 3.7 and below behavior) to now favor UTF_8 instead.  Though
this commit doesn't see those changes, the calls that will
automatically pick up this new string encoding are:
Puppet::Util::Windows::ADSI.computer_name
Puppet::Util::Windows::ADSI::User.current_user_name
Puppet::Util::Windows::Error.format_error_code
Puppet::Util::Windows::File.resolve_symlink

(PUP-3951) Default Windows API strings to UTF_8

---

lib/puppet/graph/simple_graph.rb

Use the `ref` attribute of a resource instead of `to_s`.
Internally, Puppet uses the `ref` attribute to identify and locate resources
within a catalog. This patch makes use of `ref` to identify nodes in graphviz
output as some Types, notably Whit, override `to_s` and either destroy or
obscure the identity of resource nodes.

Backport: (PUP-914) Use resource ref when writing dot files

---

lib/puppet/module.rb
lib/puppet/node/environment.rb
spec/unit/module_spec.rb
spec/unit/node/environment_spec.rb

Before this commit, we were checking the validity of a module name in
multiple places. We were also only excluding . and .. from the list
of modules to create. This permitted directories in the modulepath like
.git, .svn, and .DS_store to cause errors and warnings. This commit
consolidates the module name checking and excludes those types of
directories. It also enforces a name validity check more in line with the Forge validator.

(PUP-3678) Correct and unify module name validation

---

benchmarks/type_inference/benchmarker.rb
benchmarks/type_inference/description
benchmarks/type_inference/puppet.conf.erb
benchmarks/type_inference/site.pp.erb
lib/puppet/pops/types/types.rb

This PR adds two commits. One with a type_inference performance test and another with a performance
optimization that makes the test run almost twice as fast. The optimization replaces the ```copy``` method of
the ```PAnyType::ClassModule``` so that it performs a regular recursive deep copy instead of the more
expensive ```Marshal dump/load```.
Before optimization:
user     system      total        real
Run 1        1.750000   0.020000   1.770000 (  1.785820)
Run 2        1.200000   0.000000   1.200000 (  1.200219)
Run 3        1.140000   0.010000   1.150000 (  1.149083)
Run 4        1.150000   0.000000   1.150000 (  1.147719)
Run 5        1.140000   0.000000   1.140000 (  1.148519)
Run 6        1.150000   0.000000   1.150000 (  1.149797)
Run 7        1.110000   0.010000   1.120000 ( …

Issue/pup 909/type inference benchmark

---

lib/puppet/resource.rb
lib/puppet/resource/catalog.rb

Prior to this commit, if a Resource was created as 'Bar[instance]',
it would fail an attemt to fetch the resource type from its
environment. The environment would not be set and thus fallback
to whatever the :current_environment referred to. This made
the test spec/integration/parser/ruby_manifest_spec.rb fail.
Here, the environment is passed from the catalog to the Resource
initialize methdo in the attributes hash and properly assigned
before used.

(PUP-3934) Propagate environment to Resource initializer

---

ext/build_defaults.yaml

This commit will allow us to include a specific cfacter build in the
puppet-agent msi package. This update is dependent on updates to the
automation in puppet_for_the_win to be able to encorporate this
addition.

(PUP-3853) Add cfacter to the msi build

---

spec/unit/module_spec.rb
spec/unit/node/environment_spec.rb

Before this test, the spec tests don't include negative tests for module
directories starting with '.'. After this commit, we test for those
types of directories also. This tests the original intention of
PUP-3678.

(PUP-3962) Test for '.' module directories

---

lib/puppet/type/file/content.rb
spec/integration/type/file_spec.rb
spec/shared_contexts/checksum.rb
spec/unit/type/file/content_spec.rb

Makes file contents that use mtime or ctime for checksum_type
compare to ensure the target mtime/ctime is newer than the source.

(PUP-3890) Fix mtime/ctime checksum type

---

acceptance/tests/environment/broken_unassigned_environment_handled_gracefully.rb
acceptance/tests/environment/can_enumerate_environments.rb
acceptance/tests/environment/directory_environment_production_created_master.rb
acceptance/tests/environment/use_environment_from_environmentpath.rb
acceptance/tests/modules/install/with_environment.rb

Beaker uses these for user/group on test-runner.  Ensure the tests use
the output of puppet agent/master --configprint so manifests get created
and run correctly using the puppet user/group.
This is required for the AIO pipelines.

(maint) fix tests that incorrectly use host['user']

---

acceptance/lib/puppet/acceptance/environment_utils.rb
acceptance/lib/puppet/acceptance/temp_file_utils.rb
acceptance/tests/environment/broken_unassigned_environment_handled_gracefully.rb
acceptance/tests/environment/can_enumerate_environments.rb
acceptance/tests/environment/directory_environment_production_created_master.rb
acceptance/tests/environment/use_environment_from_environmentpath.rb
acceptance/tests/modules/install/with_environment.rb
acceptance/tests/resource/file/symbolic_modes.rb
acceptance/tests/resource/user/should_not_create_existing.rb
acceptance/tests/ticket_4110_puppet_apply_should_not_create_a_user_that_already_exists.rb

This commit updates puppet acceptance tests and their helper methods to use
the Beaker `host.puppet['user']` and `host.puppet['group']` method in order to
introspect the proper puppet user and group.
Previously, these tests and helpers were relying on the `host` hash as defined
by Beaker to determine these values. This method is no longer proper procedure
for determining these values and was resulting in test failures in the
acceptance testing of puppet against the All In One agent as well as
failures in the acceptance testing of Beaker.

(PUP-3969) Use Beaker puppet method for host 'user' and 'group'

---

lib/puppet/provider/service/base.rb

Facter 3 is planning to drop the 'ps' fact (which is only used here
as far as anyone can tell), so this commit simply moves that logic
for different ps versions into the one provider that relies on it.

(PUP-3679) Drop use of facter's 'ps' fact.

---

lib/puppet/util/windows/process.rb
lib/puppet/util/windows/user.rb
spec/integration/util/windows/user_spec.rb

- The previous method for checking whether a user is an admin? on
Windows can cause issues loading Puppet when the --cfacter switch is
applied.  The error message is:
Error: Could not initialize global default settings: facter has
already evaluated facts.
Detect that the Windows major version is at least 6 (Vista+) as a
shortcut to whether or not TokenElevation is available on the current
operating system.
An alternative approach would rewrite supports_elevated_security to
execute similarly to elevated_security?, but watch only for
ERROR_NO_SUCH_PRIVILEGE.  This would be less code, but several
additional API calls to clone the current process token and
call GetTokenInformation against it.

(PUP-3821) Don't check Windows admin? with Facter

---

acceptance/tests/resource/file/content_attribute.rb
acceptance/tests/resource/file/source_attribute.rb
spec/integration/network/http/api/indirected_routes_spec.rb
spec/integration/type/file_spec.rb
spec/lib/puppet/indirector_proxy.rb
spec/lib/puppet_spec/network.rb
spec/shared_contexts/checksum.rb
spec/unit/network/http/api/indirected_routes_spec.rb

Add integration and acceptance tests for specifying the checksum on a file. Covers puppet apply, querying the server via the HTTP API, and puppet agent runs.

(PUP-3899) Testing for checksum type on file resource

---

acceptance/tests/resource/file/source_attribute.rb

Fix mistype in removing directories. For some reason that only failed on
Solaris, but it impacts the environment of every platform.

(PUP-3899) Fix source_attribute acceptance on Solaris

---

ext/build_defaults.yaml

Update MSI dependencies for PUP 4.0.0
This may or may not cover the following (depending on whether we need to split this to multiple PRs as those other components are released):
Followup to address the rest at https://github.com/puppetlabs/puppet/pull/3583

(PUP-3848) MSI Dependencies for Ruby 2.1.5 / Puppet 4.0.0

---

acceptance/tests/modules/build/build_ignore_module_file.rb

Create a new acceptance test for the PMT tool. Verify that the user will
receive an appropriate warning message if a "Modulefile" is present when
building a module. (The "Modulefile" support has been removed from PMT.)

(PUP-3981) Add Acceptance Test for Modulefile

---

lib/puppet/functions/each.rb
lib/puppet/functions/filter.rb
lib/puppet/functions/map.rb
lib/puppet/functions/reduce.rb
lib/puppet/functions/scanf.rb
lib/puppet/functions/slice.rb
lib/puppet/functions/with.rb
lib/puppet/pops/binder/lookup.rb
lib/puppet/pops/binder/producers.rb
lib/puppet/pops/evaluator/closure.rb
spec/unit/functions4_spec.rb
spec/unit/pops/binder/injector_spec.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

This commit was merged to master 3 months ago. It is also needed on stable since it changes the way blocks are called from puppet functions written in Ruby.

(PUP-3274) Change Closure.call to not take scope as parameter

---

lib/puppet/resource/type.rb
spec/integration/parser/node_spec.rb
spec/unit/resource/type_spec.rb

Prior to this commit, it was possible for a node resource to have
a name that collided with another resource. This is due to the fact
that when a resource is created for a node, if the node has a regex
name the regular expression will be munged and altered into a regular
string.
If the munged node name matched the name of another resource, the
two would collide and the collision would go undetected but potentially
case small errors.
In order to prevent this from happening, prepend "__node_regexp__"
to front of resource names that represent nodes which are specified
by a regex in order to prevent a possible collision.

(PUP-3167) Prevent regex node names from colliding

---

lib/puppet/functions.rb
lib/puppet/functions/assert_type.rb
lib/puppet/functions/each.rb
lib/puppet/functions/filter.rb
lib/puppet/functions/map.rb
lib/puppet/functions/reduce.rb
lib/puppet/functions/scanf.rb
lib/puppet/functions/slice.rb
lib/puppet/functions/with.rb
lib/puppet/pops.rb
lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/evaluator/puppet_proc.rb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/functions/dispatch.rb
lib/puppet/pops/functions/dispatcher.rb
lib/puppet/pops/functions/function.rb
lib/puppet/pops/types/type_calculator.rb
spec/integration/parser/future_compiler_spec.rb
spec/unit/functions/assert_type_spec.rb
spec/unit/functions/with_spec.rb
spec/unit/functions4_spec.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

Passing a block as a normal parameter messed up the notion of
optional parameters since the last parameter could be a required
block. It also made the calling convention somewhat unorthodox
from a ruby developers point of view.
This commit introduces a new class 'PuppetProc' derived from the Ruby
'Proc'. It wrapps the normal closure that would otherwise be passed in
a parameter and enables it to instead be passed as a block, thus
making it possible to use standard calls like 'block_given?' and
'yield' to execute a Puppet lambda from Ruby.
The 'TypeCalculator' will infer a 'PuppetProc' to the type of its
closure. It is also capable of inferring a normal ruby 'Proc' using the
information returned by its 'parameters' method so that all parameters
are of type 'Any' and the min/max is …

(PUP-3978) Pass block using Ruby semantics, not as normal parameter

---

lib/puppet/pops/model/model_label_provider.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

When interpolating a short form numeric variable name (e.g. ${0}) and
continuing with an access operation (to take a substring e.g.
${0[2,4]}) this failed because the validation of a Variable expected the
name of the variable to always be a NAME, not an integer).
This fixes the validation logic, and adds tests.
Also fixed is the label provider which now provides the label "Undef
Value" instead of "Nil Object".

(PUP-3998) Fix interpolation of "${0[...]}"

---

lib/puppet/pops/types/type_calculator.rb
spec/unit/pops/types/type_calculator_spec.rb

This commit changes the TypeCalculator so that a Struct with optional
values becomes assignable from a Struct where the keys corresponding
to those values are missing. It also changes the instance_of logic so
that a Hash missing such keys is considered an instance of the struct.

(PUP-4000) Make optional Struct value imply optional key

---

lib/puppet/reference/configuration.rb

This should make the error more googleable and less baffling.

(docs) Add example error message for boolean CLI options to configuration reference

---

acceptance/tests/resource/service/ticket_3927_redhat_systemd_vs_service_provider.rb
lib/puppet/provider/service/systemd.rb
spec/unit/provider/service/systemd_spec.rb

Recent changes to the redhat (chkconfig) service provider requires
features that the chkconfig shim doesn't support (specifically, --add).
Besides, the systemd provider should be the default for Fedora anyway.

(PUP-3927) Ensure Fedora uses the systemd service provider

---

spec/unit/provider/service/systemd_spec.rb

In Ruby 1.8.7, the order of hash elements differs from 1.9+ and
caused short-circuiting of the logic used by default.all? in the
provider. Thanks to Peter Huene for diagnosing this issue and
proposing the fix.

(PUP-4011) systemd spec test fix for Ruby 1.8.7

---

lib/puppet/pops/types/type_calculator.rb
lib/puppet/pops/types/types.rb
spec/unit/pops/types/type_calculator_spec.rb

This commit adds the method 'is_the_empty_hash?' to the PHashType.
It responds true when both the key and value types are PNilType and
the size_type is 0,0. This method is then called by the
TypeCalculator.assignable_PHashType when the first parameter accepts
a hash type of size zero.

(PUP-4008) Consider empty hash assignable to any Hash with size 0

---

acceptance/config/nodes/win2012r2-rubyx64.yaml
acceptance/config/nodes/win2012r2-rubyx86.yaml
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/setup/aio/pre-suite/010_Install.rb

Previously it was not possible to run Windows acceptance against FOSS
MSI packages. This commit adds a step to the aio rake tasks that can
install the puppet-agent MSI.
It depends on https://github.com/puppetlabs/beaker/pull/674
With this commit you can do:
$ bundle exec rake ci:test:aio \
CONFIG=config/nodes/win2012r2-rubyx64.yaml \
SHA=<SHA> VERSION=1.0.0-o-ga354e25 \
MSI_BASE_URL=http://int-resources.corp.puppetlabs.net/aio
Note the VERSION string must match the filename of the MSI which
includes the output from `git describe`. The host definition file needs
to specify which `ruby_arch` it wants to install, either x86 or x64.
Given one off builds may wish to be tested that are not products
of the build pipeline, the MSI url and filename may be overridden
completely with two environment …

(QENG-1800) Install MSI for AIO package acceptance

---

lib/puppet/type/file/mode.rb

* Modes MUST be strings, not should
* Add more info about setuid/setgid/sticky
* Break up description of numeric modes to make it more scannable
* Remove reference to "four-digit," since that's a style issue and not technically required
* Docs standards: uppercase text in `<PLACEHOLDER>` tokens

(docs) Revise description of file type's mode attribute

---

acceptance/setup/git/pre-suite/000_EnvSetup.rb
acceptance/setup/packages/pre-suite/010_Install.rb

Puppet 4.0 requires the deep_merge gem. It needs to be available
when running the acceptance suite on git or packages (it is included
in aio).
This adds a 'gem install deep_merge' on all hosts (for the sake of
simplicity) except windows hosts (where it is not needed).

(maint) Add deep_merge gem install to git and packages pre-suite

---

acceptance/setup/aio/pre-suite/010_Install.rb

- Previously, the ability to find MSIs for an acceptance run required
3 pieces of information:
- Long SHA of puppet-agent repository
- ARCH as either x86 or x64
- The `git describe` of the puppet-agent repository, typically in the
x.y.z.XX.g<SHA> format
Unfortunately, the `git describe` was not made available anywhere to
the job, and thus acceptance runs would need to have a change made to
make it easier to find the correct MSI.  On platforms other than
Windows, the `git describe` is actually not necessary as the SHA is
enough to find a repo config, which then contains the information
necessary to resolve packages with the specific version.  So Windows
needs a solution (as will other platforms not using repo configs like
Solaris and AIX).
Options discussed:
- Pass the `git describe` …

(QENG-1800) Use symlink convention to find MSIs

---

ext/debian/puppet.init

Previously, condrestart was supported only on redhat. This brings the
support to Debian. Condrestart is useful for packaging scripts that
want to bounce the service if it's running, but not start it if a user
chose to keep it off.

(PUP-3982) Enable condrestart for puppet agent init script

---

.gemspec

PuppetDB uses the gem version of Puppet to test its terminus. Recently a new
hard dependency was added for Puppet::Pops::MergeStrategy to work, this patch
ensures the gem 'deep_merge' is included in the gem dependencies.

(maint) Include deep_merge in .gemspec

---

lib/puppet/type/package.rb

Updates the package type docs to account for changes in PUP-1073
allowing multiple package resources that share the same name if they
come from different providers.

(PUP-4027) Fix package docs for PUP-1073

---

acceptance/lib/puppet/acceptance/install_utils.rb

Previously, when puppet is installed on windows, it creates and executes
a service that runs in the background. This can interfere with tests
that try to execute the agent, resulting in:
Notice: Run of Puppet configuration client already in progress;
skipping (C:/ProgramData/PuppetLabs/puppet/var/state/agent_catalog_run.lock
exists)
This commit stop the service after installing the MSI.
Another approach would have been to specify
PUPPET_AGENT_STARTUP_MODE=Manual, but cygwin keeps quoting the argument
and msiexec hangs because it thinks it's a single argument as opposed to
a key=value.
```
$ cmd.exe /c start /w msiexec /qn /i http://builds.puppetlabs.lan/puppet-agent/7f9eb57786e5862ead966f71415ebc0ed21c1ee4/artifacts/windows/puppet-agent-x64.msi /L*V C:\\Windows\\Temp\\Puppet-Install.log …
```

(maint) Stop the windows service

---

ext/build_defaults.yaml

This commit updates the refs for vendored Windows Ruby to
the latest SHAs in the 2.1.x-x86 and 2.1.x-x64 branches.

(RE-3997) Update vendored Windows Ruby to latest.

---

lib/puppet/application/doc.rb

This removes the now useless options, examples, and updates the
helptext with a reference to puppet-strings which should be used instead
of the deprecated puppet doc command.

(PUP-3638) Update the help text for puppet doc

---

lib/puppet/util/fileparsing.rb
spec/fixtures/unit/provider/parsedfile/simple.txt

If the fileparsing parses a file that includes a line that starts with
an uppercase Q, this line is merged with the previous line, so
foo
Quest
bar
becomes
foouest
bar
this can have some serious and unexpected sideeffects. The problem lies
in the way how trailing line seperators are removed. The current regex
"\n\Q" (given the fact that line seperator is \n is most cases) looks
like some perlish regex. But in fact `\Q` does not have a special
meaning here and is translated to a literal `Q` instead. As a result the
newline and the `Q` from the following line are just removed.
However the split method does ignore trailing delimiter by default
irb(main):003:0> "foo\nbar\n\n".split("\n")
=> ["foo", "bar"]
so I am not sure of the original intention. The fact that this caused no
issue so far is …

(PUP-4012) Dont merge lines with uppercase Q

---

lib/puppet/provider/package/pacman.rb
spec/unit/provider/package/pacman_spec.rb

These commits fix the pacman package provider's handling of groups.
Previously, the pacman provider would return a version of '1' for package groups if a single package of the group was installed. This meant that groups that were partially installed were considered to be installed.  Additionally, if a package in a group was updated, the group was still considered to be the latest and no action would be taken to update the group.
This fixes the above issue by considering a package group to be installed only if all the packages in the group are installed.  Additionally, package group versions are now a concatenation of all the versions of the packages comprising the groups.  This allows the group to install packages in the group that have been updated.
Also fixed:
* Pass the `--needed` …

(PUP-1085) Fix handling of package groups in pacman provider.

---

lib/puppet/provider/service/debian.rb
spec/unit/provider/service/debian_spec.rb

Check for enabled debian service manually on 101 status. 101 is action
not allowed, meaning we have to manually check the service status
similar to when we get a status 105 (unknown).

(PUP-3166) Debian provider handles 101 status

---

lib/puppet/daemon.rb
spec/unit/daemon_spec.rb

Ruby 2.x changes the way signals work to mean you can't do certain things from the 'trap context'. This means that SIGUSR1 and the like no longer work.
This change makes it so that we, instead of processing methods in the 'trap context', just store them on a list and pop them out the other side in another job called signal_loop.
This is modelled on the way other Ruby Daemon-like projects have fixed this issue.

(PUP-1635) Make daemon.rb signals Ruby 2.x safe

---

spec/unit/provider/package/pacman_spec.rb

Previously, the pacman unit test "should raise a Puppet::Error when
trying to install a group and allow_virtual is false" assumed
`allow_virtual` was false, and tried to install a package, assuming the
provider would raise a Puppet::Error.
However, in Puppet 4, `allow_virtual` is true, so the test was not
failing early as expected, and instead would actually try to execute:
/usr/bin/pacman --noconfirm --needed --noprogressbar -Sy package'
Puppet raises Puppet::ExecutionFailure on systems without the `pacman`
executable. However, this went unnoticed on *nix, because the test was
only expecting Puppet::Error, which is the superclass for
Puppet::ExecutionFailure. This did not go unnoticed on Windows, because
puppet raises a different exception:
Errno::ENOENT: No such file or directory - …

(PUP-1085) Be more specific about expected exception

---

lib/puppet/pops/types/class_loader.rb
lib/puppet/pops/types/type_calculator.rb
lib/puppet/pops/types/type_factory.rb
lib/puppet/pops/types/types.rb
lib/puppet/pops/types/types_meta.rb
spec/unit/pops/types/type_calculator_spec.rb
spec/unit/pops/types/type_factory_spec.rb

Before this commit, the type PNilType was used to represent the
Puppet 'undef' value. This was an unessesary mismatch. It is now renamed
to PUndefType.
The PNilType is not exposed to users of the Puppet Language or its APIs
so this is completely an internal refactoring/rename.

(maint) Rename PNilType to PUndefType

---

lib/puppet/util/run_mode.rb
spec/unit/util/run_mode_spec.rb

This commit moves `codedir` out of the `confdir` directory, so it
changes from `C:\ProgramData\PuppetLabs\puppet\etc\code` to
`C:\ProgramData\PuppetLabs\code`.
It also renames `vardir` from `C:\ProgramData\PuppetLabs\puppet\var` to
`C:\ProgramData\PuppetLabs\puppet\cache` to match *nix.
This commit also adds tests for `rundir` and `logdir`, similar to what
is done for *nix. Note we have to undefine `HOMEDRIVE` and `USERPROFILE`
as Ruby will fall back to those when trying to expand `~`.

(PUP-4037) Update Windows paths for AIO

---

lib/puppet.rb
lib/puppet/environments.rb
lib/puppet/node/environment.rb
lib/puppet/parser/ast/arithmetic_operator.rb
lib/puppet/parser/ast/collexpr.rb
lib/puppet/parser/compiler.rb
lib/puppet/parser/functions/defined.rb
lib/puppet/parser/functions/lookup.rb
lib/puppet/parser/functions/realize.rb
lib/puppet/parser/parser_factory.rb
lib/puppet/parser/relationship.rb
lib/puppet/parser/scope.rb
lib/puppet/pops/binder/lookup.rb
lib/puppet/resource.rb
lib/puppet/resource/type.rb
lib/puppet/settings/environment_conf.rb
lib/puppetx.rb
spec/integration/parser/environment_spec.rb
spec/unit/environments_spec.rb
spec/unit/settings/environment_conf_spec.rb

Prior to this pull request, the 'parser' setting was not environment
specific. In order to make it easier for users to migrate to using
the future parser, make 'parser' environment specific.
The environment parameter is optional, and if missing will use
what is configured for all environments.
This mechanism can only be used with directory environments.

(PUP-4017) Make parser an environment specific setting

---

lib/hiera/puppet_function.rb
lib/puppet/functions.rb
lib/puppet/functions/each.rb
lib/puppet/functions/epp.rb
lib/puppet/functions/filter.rb
lib/puppet/functions/inline_epp.rb
lib/puppet/functions/map.rb
lib/puppet/functions/reduce.rb
lib/puppet/functions/with.rb
spec/unit/functions4_spec.rb

This commit adds additional methods to the 4x Function disptach to
allow declarations of required, optional, or repeated parameters. The
new methods replaces the current way of defining this using arg_count()
and last_captures_rest() and those methods are therefore removed. 
NOTE: Care must be taken when merging this to master since new 4x
functions have been added there that makes use of the arg_count method.

(PUP-1806) Add varargs support to 4x function API

---

lib/puppet/parameter/value.rb
lib/puppet/parameter/value_collection.rb
lib/puppet/property.rb
spec/unit/parameter/value_collection_spec.rb
spec/unit/parameter/value_spec.rb
spec/unit/property_spec.rb

This commit effectively removes the `:call` option from the
`Puppet::Resource::Value` since it becomes meaningless when the only
valid settings are `:none`and `:instead`. The option is still
recognized and validated for backwards compatibility but will trigger
a deprecation warning.
The value of the `:call` option is no longer used. Instead, a check is
made if either a method or block has been given. If so, it is called.
If not, the providers setter is called.
This commit also removes a couple of @TODO's related to the `:method`
option and ensures that a given method always exists. If a block is
given, then a method is defined using that block and the name given
by the `:method` option. If not, then the name becomes an alias for
a call to the providers setter method.

(PUP-3296) Remove :before and :after for parameters

---

acceptance/config/nodes/win2012r2-rubyx64.yaml
acceptance/config/nodes/win2012r2-rubyx86.yaml
install.rb

- In previous commits, Windows was aligned to other platform
file system layout for both
- codedir, which changed from PuppetLabs/puppet/code to
Puppetlabs/code
- vardir, which changed from PuppetLabs/puppet/var to
PuppetLabs/puppet/cache
These changes were made to run_mode:
codedir introduced in 423f9b3aa8a987b7e4e25a8131eaad9754c4131a
codedir was moved in c3757f734e9b5ec6979c43c07c671c482590ae66
vardir was moved in c3757f734e9b5ec6979c43c07c671c482590ae66
- Unfortunately, there were some additional changes that should
have been made that affect install.rb, where those
default values are duplicated.  This commit addresses those
omissions.
- Further, since the defaults changed, acceptance node definitions
were also invalidated for the AIO platform we're currently
supporting - namely …

(PUP-4050) Windows changes to codedir / vardir

---

acceptance/config/nodes/rhel7.yaml
acceptance/config/nodes/trusty.yaml
acceptance/config/nodes/wheezy.yaml
acceptance/config/nodes/win2012r2-rubyx64.yaml
acceptance/config/nodes/win2012r2-rubyx86.yaml
acceptance/setup/aio/pre-suite/020_AIO_Workarounds.rb

Previously, we had to override the puppetserver conf.d to refer to the
old location and override ruby-load-path to point to where the
puppet-agent installed puppet, facter, etc ruby code.
A recent build of puppetserver fixes the ruby-load-path issue, so that
workaround step is no longer required. Also puppetserver moved the
location of conf.d from /etc/puppetserver/conf.d to the correct location
/etc/puppetlabs/puppetserver/conf.d, so this commit updates the node
definitions to refer to the new locations.

(maint) Change puppetserver conf.d

---

acceptance/lib/puppet/acceptance/rpm_util.rb

This commit changes the validation of an rpm package install to
use yum to perform the query.
Prior to this commit, the helper assumed that the package installed
a binary of the same name.

(PUP-3960) Fix installed rpm package helper

---

acceptance/lib/puppet/acceptance/temp_file_utils.rb
acceptance/tests/ensure_puppet-agent_paths.rb

Tests that the results of `puppet agent --genconfig` and `puppet agent
--configprint` match puppet-specifications, and that files that are
expected to exist from the installer and agent runs are in the locations
specified in said specification.

(PUP-4033) Test for correct puppet configuration

---

acceptance/tests/ssl/certificate_extensions.rb

This reverts commit df7306b39da0d53cd657161ce5368ea5a43addcd
and un-skips the certificate_extensions test which was previously
failing in the AIO pipeline due to a needed update to puppet-server.

(maint) Revert "(maint) Skip certificate_extensions test for AIO"

---

acceptance/config/nodes/rhel7.yaml
acceptance/config/nodes/trusty.yaml
acceptance/config/nodes/wheezy.yaml
acceptance/config/nodes/win2012r2-rubyx64.yaml
acceptance/config/nodes/win2012r2-rubyx86.yaml
acceptance/lib/puppet/acceptance/environment_utils.rb
acceptance/setup/git/pre-suite/010_TestSetup.rb
acceptance/tests/environment/environment_scenario-bad.rb
acceptance/tests/environment/environment_scenario-default.rb
acceptance/tests/environment/environment_scenario-existing.rb
acceptance/tests/environment/environment_scenario-master_environmentpath.rb
acceptance/tests/environment/environment_scenario-non_existent.rb
acceptance/tests/environment/environment_scenario-with_explicit_environment_conf.rb
acceptance/tests/modules/install/with_modulepath.rb
acceptance/tests/modules/list/with_modulepath.rb
acceptance/tests/modules/uninstall/with_modulepath.rb

Previously, several acceptance tests relied on the `puppetpath` beaker
setting, which beaker currently defaults to `/etc/puppetlabs/agent` and
will be deprecated.
This commit updates the acceptance tests to use either `codedir` or
`confdir` as appropriate, and to query the host for the method, rather
than relying on beaker.

(PUP-4057) Don't rely on puppetpath beaker option

---

lib/puppet/pops/binder/lookup.rb
spec/unit/parser/functions/lookup_spec.rb

Type parameter validator, when encountering a name that was not a
string, passed the value instead of the value type to the
TypeCalculator.string method responsible for producing a string
representation of the type to include in the validation error message.
This resulted in an internal error.
This commit fixes so that the type of the value is used instead.

(PUP-4064) Fix bogus error from 3x lookup function parameter validator

---

lib/puppet/network/format_support.rb
lib/puppet/network/formats.rb
spec/unit/application/face_base_spec.rb
spec/unit/network/formats_spec.rb

This is a rebase and trivial rspec update to @dalen's [PR-3348](https://github.com/puppetlabs/puppet/pull/3348):
This makes the console format actually pretty print nested structures.
It already said it would, but didn't in fact.

(PUP-3706) console format should pretty print nested structures

---

acceptance/setup/aio/pre-suite/020_AIO_Workarounds.rb

This commit removes an acceptance workaround for AIO that
created the puppet-server cache and related directories.
With the resolution of SERVER-357, we can remove this workaround.

(PUP-4004) Remove puppet-server cachedir acceptance workaround for AIO

---

lib/puppet/pops/types/type_asserter.rb
spec/unit/functions/lookup_spec.rb

The TypeAsserter.assert_instance_of incorrectly used infer() to
determine the type of the given instance. This commit changes it
to use infer_set().
A couple of tests for the new lookup function are also added since
it was impacted by this bug.

(PUP-4070) Fix TypeAsserter to use infer_set instead of infer

---

lib/puppet/parser/functions/create_resources.rb
spec/unit/parser/functions/create_resources_spec.rb

Before this fix, if Puppet::ParseError was raised with a causing
(original) error associated with it, the original error was unwrapped
and passed on. This led to valuable information being lost as the
original error would typically be a lower level ArgumentError that has
no information about file and line.
This in turn means that the error is reported against the call to
create_resources as opposed to the actual location in puppet source that
invoked the logic that in turn triggered the ArgumentError.
This can be observed by having create_resource create a defined resource
that attempts to add two strings.
The fix is simply to remove the unwrapping and not catching the error at
all. With this implementation the error is as detailed as it can get,
albeit slightly oddly formatted in some …

(PUP-4054) Remove unhelpful unwrapping of errors in create_resources

---

lib/puppet/plugins/data_providers.rb

The default data provider that is used when no environment has been
setup or when no module provider is found returned nil on lookup.
This commit changes this so that they instead throw :no_such_key to
indicate that no value was found (as opposed to finding nil).

(maint) Ensure that default data providers throws :no_such_key

---

conf/puppet.conf

While for agents caching features would not be good as they can have new
features delivered during the course of a run, for masters this poses no
problems and decreases overhead during catalog compilation. Without
this, masters will reset and reinterrogate features during the course of
operation which is expensive.

(PUP-3090) Set always_cache_features to true for masters

---

lib/puppet/network/formats.rb
spec/unit/application/face_base_spec.rb
spec/unit/network/formats_spec.rb

Previously, rendering console output would fail if `datum` was true,
false, nil, or Object. This regressed in commit ac56d115ac9, which
switched from `json.render(datum)` to `JSON.pretty_generate(datum)`. It
turns out that the latter will render values that are not valid JSON,
e.g. `json.render(true) => 'true'`, while the latter raises an
exception.
This commit modifies the console formatter to use
`PSON.pretty_generate(datum)`. This preserves the old behavior of
accepting non-JSON values, while adding the pretty printing we need for
nested datum values.
We will be switching everything from PSON to JSON in PUP-3524

(PUP-3706) Render console output using PSON

---

acceptance/Gemfile

This commit pins beaker to the last known SHA prior to
https://github.com/puppetlabs/beaker/commit/c6a15c8f6df09a, which
changes the semantics around `puppetbindir`.
This is a temporary measure until PUP-4056 is implemented.

(PUP-4056) Pin beaker

---

lib/puppet/parser/scope.rb
spec/unit/parser/scope_spec.rb

Before this commit, it was problematic to use the built in variables
$caller_module_name, and $module_name when testing a module since
and using the --strict_variables option since these built in variables
are not set by the test harness.
This commit makes the two built in variables always exist. They have
undef value unless set by the runtime.

(PUP-4066) Make built in variables exist at all times

---

lib/puppet/provider/service/systemd.rb
lib/puppet/type/service.rb
spec/unit/provider/service/systemd_spec.rb
spec/unit/type/service_spec.rb

This updated the systemd service type to add support for masking. If a
service is masked, it is deemed to also be disabled. If a service is
masked and changed to enabled, it will first be unmasked since the
standard 'systemctl enable' command does not properly unmask the command
first.

PUP-1253 Add systemd service masking support

---

conf/environment.conf

The file is all comments, so we can include it in a default production
environment. It includes a link to docs, a brief explanation, and a list of
allowed settings with default values.

(PUP-4083) Add sample environment.conf to conf/

---

conf/puppet.conf

This PR removes the master section from puppet.conf, as it will be
specified by puppetserver or puppetmaster as needed. It is replaced with
comments so that users can easily find the documentation on which
settings are available and how to use them.

(PUP-4074) Remove master section from puppet.conf

---

lib/puppet/parser/scope.rb
spec/unit/parser/functions/defined_spec.rb

This fixes the problem of checking if an absolute variable is defined or not.
The fix is a back port of the fix on master with extra support added for a corner case that occurs only
when running tests (the class "" is not mapped to a scope in partially set up tests).

(PUP-4072) Make defined function work for variables with initial ::

---

lib/puppet/pops/evaluator/evaluator_impl.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

Before this commit, an unfold of undef would be treated like unfold of
any other value - i.e. wrapping it in an array, and then depending on
context unfold the result into that context.
It is more natural that an unfold of undef leads to nothing - i.e that
undef is turned into an empty array, that when unfolded in context adds
nothing.
Thus *undef and [] has the same result.
In options for case and selector expressions, if a *undef is used as an
option, that option will not match any value, not even undef or an empty
array.

(PUP-4082) Make unfold of undef produce nothing

---

lib/puppet/type/package.rb
spec/unit/type/package_spec.rb

In Puppet 4, the package type's allow_virtual setting will be true by
default. In commit 3f6d7cad, this change was made and the deprecation
warning for allow_virtual was removed in master. However, many have
found the deprecation warning to be disruptive in the 3.x series, so
this commit removes it. We will deprecate in docs instead.

(PUP-4076) Remove 'allow_virtual' deprecation warning in the 3.x series

---

acceptance/setup/git/pre-suite/010_TestSetup.rb

Without this change, acceptance tests will fail if puppetconfdir
contains a space. This wasn't a problem previously because Beaker uses
cygpath to generate DOS-style paths, such as
`C:/PROGRA~3/PuppetLabs/puppet/etc`. It has become a problem during
testing of new AIO agent paths, that contain spaces in Windows Server
2003.
Fix handling of paths with spaces by quoting them when they're used.

(maint) Fix paths with spaces in Windows acceptance setup

---

ext/rack/config.ru

With PUP-4074, the master section was removed from the puppet.conf being
laid down by puppet during installation. Those settings are still
required by a master running under passenger, so this commit adds these
settings to the example config.ru in ext/rack. always_cache_features is
also included as a performance improvement for the master.

(PUP-3090) Update puppetmaster rack config for new paths

---

acceptance/tests/ensure_puppet-agent_paths.rb

Without this change, the new ensure_puppet-agent_paths acceptance test
fails on Windows Server 2003, and when testing 32-bit puppet-agent
installs on 64-bit Windows.
Update the test to use the correct paths for both cases.

(DO NOT MERGE)(PUP-4088) Fix new path acceptance for some Windows

---

acceptance/tests/ensure_puppet-agent_paths.rb

- Prior to MSI packaging changes that went into
https://github.com/puppetlabs/puppet_for_the_win/commit/f8bfe7f
the Windows MSI did not contain mco.bat
- With the MSI changes made, the test can be updated accordingly

(PUP-4112) AIO path checks should verify mco.bat

---

lib/puppet/functions/hiera_include.rb
lib/puppet/pops/loader/module_loaders.rb
spec/unit/pops/loaders/module_loaders_spec.rb

Before this commit it was not possible to call hiera_include
because of two problems:
* a missing requirement on the helper hiera/puppet_function
* the puppet system loader had no private loader and could not call
to other puppet functions (i.e. the include() function).
This went undetected because of poor test covarage of hiera
related functionality.
The fix for this adds the requirement and ensures that the "puppet
system loader" (loading from puppet itself) has self as private loader.
(This because the concept of having functions that can only be called
from other functons in puppet does not exist; i.e. "puppet private".
This is not needed since puppet itself can always invoke common private
logic via other means).

(PUP-4046) Fix missing requirement and system private loaders

---

lib/puppet/error.rb
lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/util/errors.rb

Before this commit, ParseErrors that occured in a call from the
evaluator was passed on verbatim to the higher powers. The intent is
that ParseError is used when the file and line in a .pp file is known.
The use of raised ParseErrors without such information does however
permeate throughput the puppet code base and in modules.
This was bad because many errors would then not be associated with
a location in a manifest.
Further complications were that a) some errors were already preformatted
with location information being baked into the message text when
reaching the evaluator (these should pass verbatim), and b) the way
safeevaluate of AST objects work meant that all errors would end up with
a wrapped 'original' exception which leads to duplicated output of the
message and the text …

(PUP-4086) Patch ParseErrors with location if missing

---

acceptance/Gemfile
acceptance/config/aio/options.rb
acceptance/config/nodes/rhel7.yaml
acceptance/config/nodes/trusty.yaml
acceptance/config/nodes/wheezy.yaml
acceptance/config/nodes/win2012r2-rubyx64.yaml
acceptance/config/nodes/win2012r2-rubyx86.yaml
acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/lib/puppet/acceptance/module_utils.rb
acceptance/lib/puppet/acceptance/windows_utils.rb
acceptance/tests/environment/agent_runs_pluginsync_with_proper_environment.rb
acceptance/tests/environment/enc_nonexistent_directory_environment.rb
acceptance/tests/environment/use_agent_environment_when_enc_doesnt_specify.rb
acceptance/tests/environment/use_enc_environment.rb
acceptance/tests/environment/use_enc_environment_for_files.rb
acceptance/tests/environment/use_enc_environment_for_pluginsync.rb
acceptance/tests/reports/submission.rb
acceptance/tests/resource/file/ticket_8740_should_not_enumerate_root_directory.rb
acceptance/tests/security/cve-2013-1654_sslv2_downgrade_agent.rb
acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb
acceptance/tests/windows/eventlog.rb

* Prepends privatebindir to the PATH environment used to execute `ruby` and `gem` on all hosts.
* For ruby-based ENC scripts executing on the master, resolve `ruby` relative to `privatebindir`.
* Moves the beaker pin to the version that contains the AIO pathing changes
* Removes the AIO path overrides from node config files

(PUP-4056) Use privatebindir to resolve ruby

---

lib/puppet/indirector/hiera.rb
lib/puppet/pops/lookup.rb
lib/puppet/pops/merge_strategy.rb
spec/unit/functions/lookup_spec.rb

(PUP-4132) Pass merge strategy to Hiera
Hiera version 2.x will recognize a resolution_type parameter value
that is a Hash to mean a `:hash` _resolution_type_ with configured deep
merge options. This commit ensures that the lookup _merge_ parameter
is correctly converted into such a Hash when needed. The conversion
also translates the `'unique'` merge type into the Hiera `:array`
equivalence.

(PUP-4132) Pass merge strategy to Hiera

---

CONTRIBUTING.md

Remove an old link to the mostly-dead wiki, add links to puppet-dev email list
archive, #puppet-dev IRC archive, and community triage notes. Clean up some
white space errors.

(maint) Update links in CONTRIBUTING.md

---

acceptance/tests/modules/install/with_version.rb
acceptance/tests/resource/file/symbolic_modes.rb

- changes in beaker 2.x broke a few tests, update tests to function
correctly with new beaker while maintaining backwards compatability

(MAINT) updates tests to work with beaker 2.x

---

spec/integration/provider/yumrepo_spec.rb

Add spec integration tests to test the yumrepo provider.
Test include adding, changing, deleting of yumrepo resources on the
filesystem. This change also tests a handful of properties. The full
list of properties and acceptable values are covered by spec unit tests.
This PR should supersede the previous acceptance PR #3035.
We should still go back and add an acceptance test which ensures round
trip through yum.conf for reposdir setting and puppet resource and
setting repos in the right place in the real-world.

(PUP-3886) add yumrepo spec integration tests

---

acceptance/tests/resource/file/source_attribute.rb

Prior to this change the source_attributes test did not cover the puppet
apply cases for all checksums.  This change adds these tests.
This change also removes the sleep(1) in favor of a loop which checks to
ensure we're ready to move on, saving up to a second.

(PUP-3974) test source attribute, all checksums

---

lib/puppet/util/windows/registry.rb
spec/unit/util/windows/registry_spec.rb

Changes were introduced in b46ede7
to work around string encoding issues discovered internal to
Ruby 2.1.5 Registry handling.  Additional tests were added to
demonstrate the behavior around round-tripping Unicode characters
properly.  Interestingly, this test caused a test failure only
in Windows 2003.
- On Windows 2003, the following behavior was observed:
- Calls to create generated registry keys under
HKLM\SOFTWARE\Wow6432Node\
This is equivalent to passing KEY_WOW64_32KEY to RegCreateKeyEx
- Calls to open try to open registry keys under
HKLM\SOFTWARE\
This is equivalent to passing KEY_WOW64_64KEY to RegOpenKeyEx
This generates a test failure because the key created is not the same
one that the code later attempts to open, and hence the handle is
invalid, and the key cannot be deleted. …

(maint) Windows 2003 registry test fails

---

acceptance/setup/aio/pre-suite/010_Install.rb

Without this change the pre-suite installs puppet-server from
nightlies/puppetserver-latest which can sometimes be an older version.
this fix allows one to specify SERVER_VERSION environment variable to
pull a specific build.
This change also adds puppetserver-confdir to the aio options file.

(maint) allow puppet server installs from version

---

lib/puppet/defaults.rb

The defaults.rb file didn't have any advice on how to use this setting, so this
commit adds our current best practices.

(PUP-4094) Update description of environment_timeout in defaults.rb

---

conf/environment.conf

There's a companion pull request, #3727, that edits the description of the setting in defaults.rb. The hope is that there'll be a merge-up from stable to master relatively soon, so we won't have to cherry-pick. This PR has to stay separate, because the example file doesn't exist in stable.

(PUP-4094) Update environment_timeout default in example environment.conf

---

lib/puppet/pops/parser/heredoc_support.rb
spec/unit/pops/parser/parse_heredoc_spec.rb

Missing a '@' when referencing lexing_context. This prevented multiple
heredocs on the same line from being parsed correctly.

(PUP-4205) Fix syntax error in heredoc support.

---

ext/rack/config.ru

While our config.ru was mostly modified to work with the AIO and Puppet
4, we missed adding the codedir option. This commit adds that with the
default of /etc/puppetlabs/code as the value.

(PUP-4199) Add codedir to ARGV in config.ru example

---

ext/systemd/puppet.service

Currently, the entire control group is sent a kill; if a puppet agent run under the control group is running an upgrade of the puppet package, both the running agent process and the yum process doing the upgrade are killed as well as the daemon agent process, leaving the puppet installation in a bad state.  This brings the behavior in line with the behavior under the SysV init script.

(PUP-3931) Change systemd KillMode to process for agent

---

lib/puppet/data_providers.rb
lib/puppet/data_providers/data_adapter.rb
lib/puppet/data_providers/data_function_support.rb
lib/puppet/data_providers/function_env_data_provider.rb
lib/puppet/data_providers/function_module_data_provider.rb
spec/fixtures/unit/functions/lookup/environments/production/lib/puppet/functions/environment/data.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/abc/lib/puppet/functions/abc/data.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/bad_data/lib/puppet/bindings/bad_data/default.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/bad_data/lib/puppet/functions/bad_data/data.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/bad_data/manifests/init.pp
spec/fixtures/unit/functions/lookup/environments/production/modules/bca/lib/puppet/bindings/bca/default.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/bca/lib/puppet/functions/bca/data.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/bca/manifests/init.pp
spec/fixtures/unit/functions/lookup/environments/production/modules/no_provider/manifests/init.pp
spec/unit/functions/lookup_spec.rb

This commit changes the data provider logic so that when a qualified
name is used in the lookup and no value is found globally or in the
environment, then the first segment of the qualified name will be used
to determine what module the lookup should be perfomed in.
No attempt will be made to do a module lookup unless the name is
qualified. This applies even if the lookup is made from within a
module.
This commit also adds a validator for the function provided module
data hash that checks that all keys are qualified with the name of
the module.

(PUP-4081) lookup in module when looking up qualified names

---

lib/puppet/application/device.rb
spec/unit/application/device_spec.rb

Puppet device does one catalog run per device in device.conf, however it
was then throwing away the return codes of the catalog compile and
apply. The man page says that puppet device supports
--detailed-exitcodes, so this fixes it.
Since there are multiple catalog runs in one command, exitcode masking
is unavoidable, so I selected to take the path of returning the single
most important exit code, in decending order with the exception of exit
1 taking precedence.

(PUP-4032) Fix exitcodes on puppet device

---

lib/puppet/application/device.rb
lib/puppet/util/network_device/config.rb
spec/unit/application/device_spec.rb
spec/unit/util/network_device/config_spec.rb

The url contains the credentials for a device. Don't print them in plaintext.

(PUP-4190) Don't display credentials in output

---

spec/unit/application/device_spec.rb

The PR for PUP-4032 added exits to the code, and the PR for PUP-4190
added tests that didn't catch the exits. This should dovetail the two
and make specs pass again.

(PUP-4190) Catch exit in device spec

---

acceptance/tests/parser_functions/lookup.rb

This change adds acceptance tests for the agnostic data lookup()
function provided for puppet 4x.
The tests include baseline functionality for testing round-tripping of
data from environments, modules, and hiera through implied class
parameter lookups and calling lookup() directly.
This change does not test the various data types that are enabled in
lookup(), hiera, etc.  These are well covered in the unit tests.

(PUP-4232) add acceptance: lookup function

---

lib/puppet/error.rb
lib/puppet/node/environment.rb
lib/puppet/parser/compiler.rb
lib/puppet/pops/issue_reporter.rb
lib/puppet/util/log.rb
lib/puppet/util/log/destinations.rb
lib/puppet/util/logging.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/issues_spec.rb

The main objective for this commit is to retain backward compatility
with the 3.x stream. It only touches the logged messages that stems
from the Puppet::Pops::IssueReporter.
The commit removes the responsibility for formatting the log messages
from the IssueReporter. Instead it passes all details to the Log
instance that is created, either by direct logging och by raising an
error. A new class named ParseErrorWithIssue (a subclass of ParseError)
that keeps track of the basic message and the issue_code was needed to
accomplish this. This class is also has the attributes 'environment'
and 'node' that will be assigned in rescue blocks before the exception
is re-thrown. Prior to this change, the rescue block would create a
new error instance with additional information in the actual message …

(PUP-4201) Add support for structured logging

---

ext/build_defaults.yaml

Fixes for March 2015 CVE's: https://www.openssl.org/news/secadv_20150319.txt

(re-4183)(packaging) Update Windows builds to openssl 1.0.0r

---

lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
spec/unit/provider/scheduled_task/win32_taskscheduler_spec.rb

Populate 'day_of_week' instead of 'on' when loading existing triggers. This
should prevent constant changes from being registered.

(PUP-3429) task_scheduler should use 'day_of_week' instead of 'on'

---

lib/puppet/provider/group/windows_adsi.rb
lib/puppet/type/group.rb
lib/puppet/util/windows/adsi.rb
spec/unit/provider/group/windows_adsi_spec.rb

Previously, if you wanted to use the group resource you needed to specify the
entire list of members as the windows provider ignored the auth_membership
setting and was always the authoritative list. This ensures that the windows
provider respects the auth_membership setting.

(PUP-2628) Add members to groups instead of full list for Windows

---

ext/build_defaults.yaml

Updates SHA to puppet_for_the_win to incorporate fix to start service
directly with ruby.exe instead of using a wrapper. This avoids warnings
in the service control manager; see PUP-1802 for details.

(PUP-1802) Update SHA to puppet_for_the_win

---

lib/puppet/pops/parser/egrammar.ra
lib/puppet/pops/parser/eparser.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

There was a problem in the grammar that caused an expression like:
unless true {} else {1}
to result in nil because neither the then-, nor the else- part were
added to the generated UnlessExpression.
This corrects the call to generate the UnlessExpression.

(PUP-4278) Fix grammar error when unless then-part was empty

---

acceptance/tests/ensure_puppet-agent_paths.rb
ext/redhat/client.sysconfig
install.rb
lib/puppet/util/run_mode.rb
spec/unit/util/run_mode_spec.rb

Previously, puppet would set its `logdir` permissions to `root:root:750`
if run on a host without the `puppet` service user and group. If the
`puppetserver` package was installed later, it would create the `puppet`
user and group accounts, try to start, but fail to write to its log
directory `/var/log/puppetlabs/puppetserver`, because of the parent
directory permissions.
This commit moves puppet's logdir to `/var/log/puppetlabs/puppet`,
isolated from both `puppetserver` and `puppetmaster` packages, the latter
being the passenger-based compatibility packages.
This commit affects both the `puppetdlog` setting, which is pretty much
dead, and the puppet master webrick `masterhttplog` setting, which is
soon to be deprecated.

(PUP-4194) Move `logdir` default to /var/log/puppetlabs/puppet

---

lib/puppet/functions/hiera_include.rb
lib/puppet/pops/loader/module_loaders.rb
spec/unit/pops/loaders/module_loaders_spec.rb

The cherry picked commit in Puppet 4.0.0 is
706cec5a34e209c37431314839ed96bb360587d8
with the following comment:
(PUP-4046) Fix missing requirement and system private loaders
Before this commit it was not possible to call hiera_include
because of two problems:
* a missing requirement on the helper hiera/puppet_function
* the puppet system loader had no private loader and could not call
to other puppet functions (i.e. the include() function).
This went undetected because of poor test covarage of hiera
related functionality.
The fix for this adds the requirement and ensures that the "puppet
system loader" (loading from puppet itself) has self as private loader.
(This because the concept of having functions that can only be called
from other functons in puppet does not exist; i.e. "puppet …

(PUP-4334) Cherry pick fix for PUP-4046 to fix broken hiera_include

---

lib/puppet/pops/issues.rb
lib/puppet/pops/parser/epp_support.rb
lib/puppet/pops/parser/evaluating_parser.rb
lib/puppet/pops/parser/heredoc_support.rb
lib/puppet/pops/parser/lexer2.rb
lib/puppet/pops/parser/lexer_support.rb
lib/puppet/pops/parser/parser_support.rb
lib/puppet/pops/parser/slurp_support.rb
lib/puppet/util/log.rb
lib/puppet/util/log/destinations.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/parser/lexer2_spec.rb
spec/unit/util/log_spec.rb

This commit ensures that trace is output correctly for errors
that origins from the future parser. It also adds four new issues
related to the lexer and ensures that the errors and warnings related
to them are generated using the improved structured logging.

(PUP-4336) Fix issues with trace and structured logging

---

lib/hiera/puppet_function.rb
spec/unit/functions/hiera_spec.rb

The Puppet function hiera() was not able to diffrentiate between the
lack of a default argument and a default argument passed as undef.
Instead, it would always treat undef as "no default" and consequently
raise an error when no value was found for a given key.
This commit changes this so that the hieara function (and it's
specializations) have different dispatchers for the cases when a
default parameter is provided or not. For the case when the default
is provied it will pass a special default value down to Hiera in its
place. On return of this special default means that the original
default should be used.

(PUP-3863) Ensure correct handling when undef is hiera default value

---

acceptance/tests/resource/file/source_attribute.rb

The source_attribute test was modified to wait for time to pass
sufficient that touching source files on the master would cause puppet
agent runs to resync the files. However, the test only checked
mtime/ctime on the master - which is unrelated to ctime/mtime of the
target files on the agents - and the agent target files are what will be
compared to the ctime/mtime of the source file to see if they need to be
resynced.
We could fix this by iterating over the agents - or assuming they'll
always be done in order and only querying the last agent - to check the
ctime/mtime stats of the target files using `puppet resource file
<filename>`, but that's more complicated and unlikely to be
significantly less than the 1 second sleep we used to have.
Revert to the previous behavior of waiting 1 …

(PUP-4340) Fix intermittent failure in test case

---

lib/puppet/provider/package/pip.rb
spec/unit/provider/package/pip_spec.rb

Add support for passing in additional options to pip install. The
current provider has no way to send additional options to pip.
For example, there are cases where you may want to connect to a
different package index, or add an extra index url to look for packages.
In my use case, we maintained our own pre-built wheels and wanted to
connect only to our pypi index and not to the general index at all, so
--find-links and --no-index achieve this.

(PUP-4198) Add install_options feature to pip provider

---

lib/puppet/type/tidy.rb

This patch reduces the amount of notifications tidy generates when working
with a large number of files.  Tidy now reports the number of changed files
using 'notify,' and reports the list of files (the old behavior) with 'debug.'

(PUP-3908) Make tidy type messages less verbose

---

lib/puppet/resource/catalog.rb
spec/integration/transaction_spec.rb

Under some circumstances (eg. dependency cycle) when catalog could not be
applied, Puppet didn't report failure (status unchanged, return code 0).
Raise Puppet::Error so the failure gets logged and reported (status is
"failed", return value is 1).

(PUP-735) Fail when cannot apply complete catalog

---

lib/puppet/provider/package/zypper.rb
spec/unit/provider/package/zypper_spec.rb

Prior to this commit, our zypper provider didn't work. When installing a
package with zypper, we pass in the `--name` flag, which is not
available in earlier versions of zypper that we account for. It also
breaks when you use `install_options`. It previously dropped in the
extra install options between `--name` and the package name to be
installed. This cuased it to fail.
This pull request reorders the options that we pass to the zypper
command. If the user has passed in the global option `--no-gpg-check`,
we pull that flag out, and pass it in where zypper expects it (after
`zypper` and before `install`).

(PUP-4090) Zypper provider improvements

---

lib/puppet/type/file/ensure.rb

When `ensure => present` and file content is provided via `content` or
`source`, the message logged was that the file was created. This is in
contrast to when `ensure => file` with content provided via `content` or
`source`, in which scenario the message logged contains the file's hash.
This makes both values log the file's hash.

(PUP-4231) Log file content hash when using ensure=>present

---

lib/puppet/provider/package/gem.rb
lib/puppet/provider/package/puppet_gem.rb
spec/unit/provider/package/gem_spec.rb
spec/unit/provider/package/puppet_gem_spec.rb

This is a rebase of #3728 against the stable branch so it can be included in Puppet 4.0
It includes cherry-picks of PUP-4191 and PUP-4203 (from #3708), since this code was originally written assuming they would be merged into 4.0 but they ended up in 4.1

(PUP-4237) Add puppet-agent gem provider

---

lib/puppet/settings.rb
spec/unit/util/run_mode_spec.rb

Commit 4ae5aca changed the per-user directories from ~/.puppet to ~/.puppetlabs
but did not update the windows specs that only run on Windows.
This commit fixes the tests and fixes an old reference to ~/.puppet.

(PUP-4355) Update windows tests for ~/.puppetlabs

---

lib/puppet/provider/mount/parsed.rb
lib/puppet/type/mount.rb
spec/fixtures/unit/provider/mount/parsed/aix.filesystems
spec/fixtures/unit/provider/mount/parsed/aix.mount
spec/unit/provider/mount/parsed_spec.rb

The way that AIX tracks its mounted filesystems is different than other
unix or linux operatingsystems. AIX uses /etc/filesystems and has
entirely different filesystem options.
This commit takes advantage of two parsedfile hooks, post_parse and
to_line, to read & generate /etc/filesystem entries. Parsedfile was
not created with arbitrary-ordering in mind, and any /etc/filesystem
entries will have their attributes reordered by to_line
Options in AIX without related properties in Puppet's mount type are
placed under the "options" property.

(PUP-1628) Fix mount provider for AIX

---

acceptance/tests/resource/zpool/basic_tests.rb
lib/puppet/provider/zpool/zpool.rb
spec/unit/provider/zpool/zpool_spec.rb

This commit backports 9464fe08 from master, which fixed a longstanding regression in the Zpool resource. Also backported are the corresponding spec and acceptance tests from commits 91243475 and a907ddd8 respectively.

(PUP-4345) Backport Zpool mirror fix for Puppet 3.8

---

lib/puppet/provider/package/gem.rb
lib/puppet/provider/package/puppet_gem.rb
spec/unit/provider/package/gem_spec.rb
spec/unit/provider/package/puppet_gem_spec.rb

The previous version of this had an issue where the `provider` resource parameter would be set to `:gem` in the `instances` method of `puppet_gem`. This fixes the provider to be set properly.

(PUP-4237) Add puppet_gem provider (take 2)

---

lib/puppet/provider/package/portage.rb

In commit 9e7bf07580d79e5b68d28cc594162959cf2a8d7d, portage.rb was
refactored, but from this on, puppet resource package only lists
packages installed by puppet, but no packages installed by hand.
The other providers apt/dpkg and yum/rpm list _all_ installed packages.
The format string in portage.rb:L123 misses a tailing \n.

(PUP-4362) fix portage to list all installed packages

---

lib/puppet/provider/package/pkgng.rb
lib/puppet/provider/package/ports.rb
spec/fixtures/unit/provider/package/pkgng/pkg.info
spec/fixtures/unit/provider/package/pkgng/pkg.query
spec/fixtures/unit/provider/package/pkgng/pkg.query_absent
spec/fixtures/unit/provider/package/pkgng/pkg.version
spec/unit/provider/package/pkgng_spec.rb

To improve the default state of Puppet on FreeBSD systems, this work
moves the pkgng provider into core.  Previously, users of the provider
would need to install from the forge module zleslie/pkgng.

(PUP-3618) Include pkgng provider for FreeBSD

---

spec/integration/type/file_spec.rb

This commit adds spec tests to cover 'ensure => present' for
the file type.
Note: This PR is rebased on top of https://github.com/puppetlabs/puppet/pull/3752, and should be merged afterwards.

(PUP-4231) Cover logs generated by ensure => present in file type

---

spec/unit/provider/package/pkgng_spec.rb

One of the tests were found to be broken. It's now commented out and
the logged as issue PUP-4382.

(maint) Change old rspec 'should' to 'expect().to' syntax

---

lib/puppet/provider/package/pkgng.rb
spec/unit/provider/package/pkgng_spec.rb

There were two issues with this test:
* It was using a resource for which the fixture data didn't actually
exist for this query
* It failed to call `prefetch`, so the `property_hash` was never
populated anyway
This fixes up the test to use a different resource and appropriately
prefetches the data.

(PUP-4382) Fix test for retrieval of 'latest' property

---

acceptance/Gemfile

Previously we were tracking on the master branch of beaker, which makes
it hard to know which version of beaker was compatible with puppet 4
when it was released. For example, as we continue to support puppet
4.0.z releases while beaker development moves forward.
This commit pins us to beaker ~> 2.8, which includes 2.8.1 and 2.9.z
releases, but not 3.0.

(maint) Pin to a released beaker version

---

lib/puppet/pops/parser/interpolation_support.rb
spec/unit/pops/parser/lexer2_spec.rb

Before this, it was not possible to use the short form interpolation
of a variable starting with _ if continued with '[' or '.'. This is
caused by the fact that names cannot start with '_' and the
transformation of interpolated expressions did instead receive the
bare word '_x' as a LiteralString (which cannot be transformed to
a variable).
The fix modifies the lexer so that the first token is always
transformed if it is a NAME or a WORD, and if it is followed by
'[' or '.'.(Logic already in place handles the case where there is
only one expression being interpolated.

(PUP-4379) Fix interpolation of shortform var with _ continued with [

---

acceptance/tests/ticket_2455_on_solaris_init_provider_should_start_service_in_own_smf_contract.rb
lib/puppet/provider/service/init.rb
spec/unit/provider/service/freebsd_spec.rb
spec/unit/provider/service/gentoo_spec.rb
spec/unit/provider/service/init_spec.rb
spec/unit/provider/service/openbsd_spec.rb
spec/unit/provider/service/redhat_spec.rb

Prior to this commit, non-SMF Puppet-managed services on Solaris
are not started in their own SMF contracts. If started
by Puppet running as a daemon, the services end up in Puppet's
SMF contract.
There are several negative implications from this scenario:
(1) If Puppet is stopped or restarted, the non-SMF Puppet-managed
services in Puppet's SMF contract are killed (by SMF).
(2) If Puppet-managed services are in Puppet's SMF contract, certain
events impacting any one of the managed services can lead to SMF killing
killing Puppet's contract, also killing all Puppet-managed services
that have ended up in Puppet's SMF contract.
In both scenarios, SMF also places Puppet in the SMF "maintenance"
state.
This commit updates the Puppet service provider to use the Solaris
'ctrun' facility to start …

(PUP-2455) Update service provider to use 'ctrun' on Solaris

---

acceptance/tests/ticket_2455_on_solaris_init_provider_should_start_service_in_own_smf_contract.rb

Prior to this commit, the ticket_2455 acceptance test
fails if there are no Solaris agents.
With no valid agents, the interaction of 'skip_test'
after the setup of 'with_puppet_running_on' causes
the whole test to fail.
This commit updates the acceptance test to skip the setup
if there are no Solaris agents.

(PUP-2455) Fix logic in ticket_2455 acceptance test

---

ext/build_defaults.yaml

Fedora 19 went EOL on 2015-01-06. We should not longer be providing
packages for this platform.

(maint) Remove Fedora 19 from build defaults

---

acceptance/tests/cycle_detection.rb

Prior to commit 3ca9e74b, if an error occurred during catalog
application, e.g. cycle detected, the `Puppet::Resource::Catalog#apply`
method would log the exception, eventually exiting puppet with code 0.
Commit 3ca9e74b modified the `apply` method to not rescue exceptions, so
failures propagate to the higher level `Puppet::Configurer`, and
eventually cause puppet to exit with code 1.
This commit modifies the acceptance test to expect exit code 1.

(PUP-735) Expect exit code 1 when cycles detected

---

ext/build_defaults.yaml

With the switch to puppet 4, we are no longer building and shipping
individual package. Instead, we're shipping puppet as a part of the
puppet-agent package. This means we can reduce the number of cow and
mock build targets to only LTS releases (for community members who are
using the automation in the packaging repo to build puppet). We can also
stop building the dmg and the msi, as puppet will be delivered to those
platforms also with puppet-agent.

(PUP-4410) decrease build targets

---

acceptance/tests/apply/puppet_apply_trace.rb

This change adds a test for --trace using puppet apply.
Other tests use --trace with apply but don't check the output.
Create a dedicated test to protect against possible regressions.

(PUP-4336) add test for puppet apply trace

---

spec/integration/type/file_spec.rb

When getting PUP-4343 ready to commit, I failed to remove all of the `File.mumble?` predicates after replacing them with the equivalent and less Windows-befuddling `Puppet::FileSystem.mumble?` predicates. This commit fixes that commit.

(maint) (PUP-4343) Remove errant File.mumble calls

---

acceptance/tests/ticket_2455_on_solaris_init_provider_should_start_service_in_own_smf_contract.rb

Prior to this commit, PE Puppet acceptance testing for
ticket 2455 fails with an "undefined local variable or
method 'agent_service'" error.
This commit updates the acceptance test to fix this issue.
We also update the acceptance test fixture to more reliably
stop the fixture service.

(maint) Fix Solaris ticket 2455 PE acceptance test.

---

appveyor.yml
spec/integration/type/file_spec.rb
spec/integration/util/windows/security_spec.rb
spec/unit/util/windows/sid_spec.rb

Windows spec tests cover behavior that's platform-specific and not
exposed by running spec tests on other CI platforms. This sometimes
leads to missing spec failures on pull requests that primarily affect
Windows.
Add AppVeyor configuration to run spec tests on Windows.
(PUP-4404) Use current user for SID spec test
(PUP-4404) Use current user for security specs

(PUP-585, PUP-4404) Add AppVeyor, fix specs expecting Administrator user

---

lib/puppet/reference/indirection.rb

These comments get generated and posted onto the docs site. This commit
updates them for the Puppet 4 url changes.

(DOC-1887) Fix indirection reference comments for Puppet 4 url changes

---

acceptance/tests/apply/puppet_apply_trace.rb

The first commit of this test had an overly specific stack trace matcher
which did not work on certain ruby stacks.  This change uses a different
match that should only match stack traces but be forgiving to changes in
the code and across ruby versions.

(maint) fix stacktrace matcher in apply trace test

---

ext/build_defaults.yaml

- As part of PUP-1283, the win32-service gem was upgraded to 0.8.5 from
0.7.2 on 7/3/2014.  Unfortunately, this picked up a bug introduced
to the win32-service gem that broke service enumeration under
Windows 2003 in commit:
https://github.com/djberg96/win32-service/commit/f65181283bd8f1f51d6f4dca3f38cbbebcaf0b60
Support for SERVICE_DELAYED_AUTO_START_INFO was added as part of this
change to support configuring and retrieving delayed start service
status, but this startup type is not supported on 2003.  Simply
executing the code yields the error:
Error: Could not run: The system call level is not correct. -
QueryServiceConfig2: The system call level is not correct.
- A PR is outstanding against the gem, but until then, our vendored
gem modifications will remain in effect until 0.8.7 ships …

(PUP-4390) Patch win32-service gem 0.8.6 for 2003

---

spec/unit/util/windows/sid_spec.rb

When running as the SYSTEM account, doing lookup of the current user via
the WIN32OLE interface fails, because SYSTEM isn't recognized as a user.
We'd like to test looking up an Administrator's SID, so query WIN32OLE for
the members of the Administrators group and get the SID of the first
member.

(PUP-4404) Fix SID lookup when running as SYSTEM

---

acceptance/lib/puppet/acceptance/install_utils.rb

Download directly to SUT in install_utils
This commit modifies the helpers in
lib/puppet/acceptance/install_utils.rb to download files directly
onto the target test host rather than downloading them locally and
scp'ing them to the host.
This reduces the test execution time by removing the duplication of
downloading the target files twice (once from the origin point to
the test runner, and then again from the test runner to the SUT).
This change eliminates the curls of the rpm files prior to installing them by
giving the URL directly to rpm. This should save a small amount of time.

(PUP-4044) curl directly to host in  install_repos_on

---

lib/puppet/pops/evaluator/evaluator_impl.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

Before this, if a splat or arguments was placed in parentheses in
a context where an unfold/splat has special meaning it would not be
recognized as a splat.
e.g.
```
(*[1,2,3]).with |$x, $y, $z| { notice $x, $y, $z }
```
would give the array to $x, and then fail because $y and $z was not
given.
This was caused by not unwinding parenthesized expressions in positions
where an UnfoldExpression is recognized - i.e. arguments in calls, case
and selector options.
The problem was reported against method call, since there, if splatting
is wanted, it must be in parentheses because of precedence.
This fixes all three places where splatting is recognized as special.

(PUP-4398) Fix problem with splatted args in parentheses

---

lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/issues.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

Before this it was not possible to directly assign multiple variables
from values in an array.:
This commit adds this ability so that:
```
[$a, $b, $c] = [1,2,3]
```
assigns the values 1,2,3 to $a, $b, $c respectively.
Nested arrays are supported:
```
[$a, [$b, $c]] = [1,[2,3]]
```
And if RHS is not an array, it is treated as an array of 1 value.
The numbers of variables and values must be the same.

(PUP-2894) Add multi assignment of variables in array

---

lib/puppet/pops/evaluator/epp_evaluator.rb

Before this, if the epp tool was asked to process a file it would
automatically append ".epp" to any file that did not end with ".epp". It
would also, depending on code path end up not checking if the file
exists or not before processing.
The fix is to:
* Allow a file that does not end with .epp to be processed, but only
if it exists
* Treat a missing file the same way for the different code paths.
While not explicitly supported to use other extensions than .epp when
templates are in modules and a search is made for them, it is of value
to be able to take a sample file and process it as if it was epp to
assert that the text itself does not need escapes etc. as this could be
the first step in converting a sample file into an epp template.

(PUP-3895) Make epp command error correctly

---

lib/puppet/pops/evaluator/collectors/catalog_collector.rb
lib/puppet/pops/evaluator/collectors/exported_collector.rb
lib/puppet/pops/model/model_label_provider.rb

Under certain circumstances, a Collector object may be assigned to
a variable or placed in an Array or Hash. When transormed to a string
for human output, the output showed the full classname and id.
This changes the output to be a label "Catalog-Collector[type]", or
"Exported-Collector[type]", where type is the type being collected
e.g. "CatalogColloector[Notify]".

(PUP-4378) Improve output of label for collector objects

---

lib/puppet/environments.rb

Argument 'setting_values' is a dead code, does not do anything,
nor is it set at any create_environment() call.
Reference to this can be found in #3386 pull request.
b.

Remove unused argument from Puppet::Environments::Directories::create_environment

---

lib/puppet/application/master.rb
spec/unit/application/master_spec.rb

The puppet-agent package does not create the puppet user or group
by default, meaning that attempting to run the webrick server without
manually creating the user results in Puppet failing hard.
This commit updates Puppet's webrick code to first check it the
puppet user exists, and only attempt to switch to it if it does.
Otherwise, we emit an error and exit. Previously, Puppet would
actually try to switch to the non-existent user and throw several
errors. We now only throw one.

(PUP-4394) Improve erroring for WEBrick server when Puppet user doesn't exist

---

lib/puppet/functions.rb
spec/unit/functions4_spec.rb

Adds the ability to declare a repeated parameter as being required
using the method `required_repeated_parameter` with the meaning that
at least one argument must be passed to it.
For consistency, this commit also adds an `optional_repeated_parameter`
alias for the already existing `repeated_parameter` method.

(PUP-4438) Add required_repeated_param to 4.x function API

---

lib/puppet/functions.rb
spec/unit/functions4_spec.rb

Before this commit it was possible to declare a required repeated
parameter after optional parameters. This cannot be allowed since
it introduces ambiguities when dispatching the parameter values.

(PUP-4438) Ensure that required_repeated_param cannot follow optionals

---

acceptance/tests/environment/environment_scenario-bad.rb
acceptance/tests/environment/environment_scenario-default.rb
acceptance/tests/environment/environment_scenario-existing.rb
acceptance/tests/environment/environment_scenario-master_environmentpath.rb
acceptance/tests/environment/environment_scenario-non_existent.rb
acceptance/tests/environment/environment_scenario-with_explicit_environment_conf.rb

This change ensures all the environment tests assert on the proper
outputs to finalize the tests that gather results into one step.
Prior to this change, some tests could result in false passes.
This change also fixes the "bad" scenario test, which tests for a bad
environmentpath.

(PUP-4111) environment scenario tests should assert success

---

lib/puppet/type/yumrepo.rb

Unshorten 'repository' in the yumrepo type descriptions and be consistent with using the full word.

(docs) Unshorten the word 'repository' in the yumrepo type descriptions

---

lib/puppet/functions.rb
lib/puppet/functions/defined.rb
lib/puppet/parser/functions/defined.rb
lib/puppet/pops/functions/dispatch.rb
spec/unit/functions/defined_spec.rb
spec/unit/functions4_spec.rb

Before this, the 3x defined() function beahaves in a strange way when
giving undef and empty string as input. A user may want to check if a
variable is defined and calls:
```
defined($not_defined)
```
and becomes surprised when true is returned even if the variable is not
defined. The user should have asked for:
```
defined('$not_defined')
```
This anomaly is caused by the 3.x functions inability to distinquish
between undef and an empty string, and the strange naming of the
Class[main] which is called '' (the empty string) internally, and 'main'
externally.
This commit fixes this problem by adding a 4.x implementation of the
defined() function. This version:
* does not accept undef input (protects users from the mistake of
defined($foo)).
* the empty string produces false
* the string …

(PUP-4178) Move defined function to 4.x to correct behavior

---

lib/puppet/pops/validation/checker4_0.rb

Before this, the validator had the ability to pass a single-feature
name when checking hostnames. This was used to check the parent of a
node. This is no longer needed since having a parent is now illegal.
This removes this feature. Tests that checked validation of parent
host name matches were removed a long time ago.

(PUP-3988) Remove unused hostname checking feature

---

lib/puppet/pops/issues.rb
lib/puppet/pops/validation/checker4_0.rb

Before this it was possible to perform assignment of variables in
a parameter default expression. This is bad because the variable is
set in the calling context!
```
define bad_boy($a = ($b = 10)) { }
```
This commit adds validation and an error for such assignments.

(PUP-2862) Make assignment in parameter default expr invalid

---

lib/puppet/parser/scope.rb
lib/puppet/pops/issues.rb
lib/puppet/pops/validation/checker4_0.rb
spec/integration/parser/scope_spec.rb
spec/unit/parser/scope_spec.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/evaluator/variables_spec.rb

Before this, an attempt to assign to $name o $title, when not in a
lambda where $name or $title is a parameter would result in an error
saying "Cannot reassign variable ...".
This was bad because users does not understand that $name and $title are
always assigned in the body of a class or a define, and that top-scope
is really in the body of Class['main'].
This commit improves the error in this situation to read:
"Cannot reassign built in (or already assigned) variable '$...'"
The vagueness "built in (or already assigned)" is used since when the
error occurs it is difficult to compute if the evaluated logic is in the
body of a class or define or not. Instead, it gives this alternative
output when the name of the variable is "name" or "title". The only
downside is the potential confusion …

(PUP-4447) Give better error message for assignment to name and title

---

spec/unit/provider/package/apt_spec.rb
spec/unit/provider/service/debian_spec.rb

We've recently updated Cumulus Linux to default to the apt package
provider and debian service type. This commit adds in spec tests for
those changes to verify that those defaults are assigned correctly.

(PUP-4351) Cumulus Linux should set defaults

---

lib/puppet/indirector/facts/facter.rb
spec/integration/indirector/facts/facter_spec.rb
spec/unit/indirector/facts/facter_spec.rb

cfacter - and in the future, Facter 3 - don't define the puppetversion
fact. This is done to avoid having the current cyclical dependency in
Facter.
Puppet already adds several facts to the node's facts. Add puppetversion
prior to loading custom facts, so the custom facts can access it.

(PUP-4359) Add the puppetversion fact for cfacter

---

lib/puppet/pops/issues.rb
lib/puppet/pops/parser/slurp_support.rb
spec/unit/pops/parser/lexer2_spec.rb

Before this it was not possible to enter \u escapes unless the
char was expressed with exactly 4 hex digits.
1
This commit makes it possible to use 1-6 (max 10ffff value) hex
digits by enclosing them in braces. Thus "\u{1f452}" results in
an emoji hat icon.

(PUP-4385) Add support for 1-6 hex digits in \u escape

---

ext/debian/puppet.default
ext/debian/puppet.init

In the new puppet-agent AIO package, services no longer
start on package installation, as there are a few required
configuration steps which must be addressed before the
service can be started.
This means we can remove the agent service START option from
/etc/default/puppet, a relic of old packages where debhelper
started services upon package installation.

(PUP-4388) Remove START option from /etc/default/puppet on Debian

---

lib/puppet/application/master.rb
spec/unit/application/master_spec.rb

This commit adds a deprecation warning to Puppet's
webrick code so that just before the server is started,
the warning will be emitted. We plan to eventually drop
WEBrick.

(PUP-4435) Deprecate WEBrick and Rack master servers

---

lib/puppet/provider/service/systemd.rb
lib/puppet/type/service.rb
spec/unit/provider/service/systemd_spec.rb
spec/unit/type/service_spec.rb

This updates the systemd service type to add support for masking. If a
service is masked, it is deemed to also be disabled. If a service is
masked and changed to enabled, it will first be unmasked since the
standard 'systemctl enable' command does not properly unmask the command
first.

(PUP-1253) Add systemd service masking support

---

lib/puppet/pops/loaders.rb

Before this, the configured system loader (loading functions supplied in
puppet core) would cache all loaded functions for the lifetime of the
process. This was done to reduce loading time since hot-loading of the
function code is not required (requires a restart of the process, just
like loading any other puppet runtime code).
Since functions are not only loaded code-wise, but are also tied to a
closure scope, and this scope is associated with a compiler, all loaded
types, a catalog etc. this lead to binding a more or less complete
environment in memory. Worst case, if each request called a unique
function there would be as many environment copies in memory as there
are functions.
In addition to the memory leak, functions such as hiera_include would
get the old information when …

(PUP-4461) Turn off caching of loaded system functions

---

lib/puppet/pops/evaluator/collector_transformer.rb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/model/model_meta.rb
lib/puppet/pops/validation/checker4_0.rb
spec/integration/parser/collector_spec.rb
spec/integration/parser/resource_expressions_spec.rb

There were parts missing in the implementation supporting * => $hash to set resource parameters; in overrides, and in collectors. There is no reason to forbid those using * => $hash. 
This corrects the implementation and adds test cases.

(PUP-4374) Splat in all resource expressions

---

lib/puppet/functions/regsubst.rb
lib/puppet/functions/split.rb
lib/puppet/pops/types/types.rb
spec/unit/functions/regsubst_spec.rb
spec/unit/functions/split_spec.rb

Before this, if a Regexp without a pattern was used as a regular
expression, it would present a nil pattern - which for the split
function means use a default split on whitespace (other methods on
string may give it different meaning).
This makes a Regexp without a pattern behave as if the pattern was
// when asking for the regexp's compiled regular expression.
This also updates the functions split, and regsubst to either use the
type's compiled regexp, or the same rule (pattern || '').
As a type, the Regexp still represents all possible patterns.

(PUP-4463) Make Regexp Type without pattern use '' when used as pattern

---

lib/puppet/pops/parser/lexer2.rb
lib/puppet/pops/parser/slurp_support.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/parser/parse_heredoc_spec.rb

Before this, heredoc with interpolation would also turn on escapes. This
means input like \$name would not interpolate, and \\ would be required
to get a single \. It should be required to be explici about allowing
escapes by using /$ (to be allowed to escape interpolation).
The prolem was caused by the pattern used to find the start of an
interpolation. This pattern included the escapes that would make the
pattern skip the interpolation start - it would simply scan past the
interpolation start if escaped.
The solution was to create a new pattern for finding interpolation
starts when a $ is not one of the wanted escapes.

(PUP-4462) Fix problem with heredoc interpolation turning on escapes

---

acceptance/tests/environment/3x_forbidden_environment_names_allowed.rb

This change adds an acceptance test to ensure that the 3x forbidden
environment names now work, and continue to work in 4x.
There are 4 previously forbidden names, which means this test has to run
puppet 5 times, unfortunately.

(PUP-4413) Add acceptance test that 3x forbidden env names work in 4x

---

acceptance/tests/resource/service/ticket_14297_handle_upstart.rb

The handle_upstart acceptance test fails on ubuntu systems when using
passenger, because the master is ubuntu, but the agent is not. So the
confine would pass, but `agent` was nil, causing the test to fail later
with:
undefined method `[]' for nil:NilClass
This commit skips the test if there are no ubuntu agents.

(maint) skip upstart test if there are no ubuntu agents

---

acceptance/setup/passenger/pre-suite/030_ConfigurePassenger.rb

The apache `version` module must be loaded to use the <IfVersion>
syntax. On debian 7 and ubuntu 14.04, the module is static, and it is
an error to try to enable it. On ubuntu 12.04, the module is not static,
and must be explicitly enabled, see RE-4465.
This commit enables the `version` module only if it is not already
loaded.

(maint) Enable version module if it's not already loaded

---

lib/puppet/pops/types/type_calculator.rb
spec/unit/pops/types/type_calculator_spec.rb

This PR fixes two problems with the `TypeCalculator.common_type` when used to compute the common type for two `PStringType` instances. I chose to put them in the same PR since they touches on the exact same lines of code which inevitably would cause merge conflicts.

(PUP-4499) and (PUP-4500) Issues with TypeCalculator.common_type and String

---

lib/puppet/pops/types/type_calculator.rb
spec/unit/pops/types/type_calculator_spec.rb

The current instance_of? method does not consider the `values`
of the string type. This commit adds that check.

(PUP-4501) Fix TypeCalculator.instance_of? for PStringType

---

lib/puppet/pops/types/type_calculator.rb
spec/unit/pops/types/type_calculator_spec.rb

The `Array`, `Hash`, and `Optional` all have contained types that may
be `nil`. The `TypeCalculator.assignable?` method didn't handle this
well (it passed `nil` in a recursive call to `assignable?`, an
operation that is permitted but will yield a `false` result).
This commit adds checks to ensure that if the contained type is `nil`,
then it will be considered to be of type `Any`.
Some tests were changed to accommodate the fact that `Optional[?]` now
considers everything to be assignable whereas nothing was assignable
before.

(PUP-4511) Ensure that unspecified contained types default to Any

---

lib/puppet.rb
spec/unit/puppet_spec.rb

Add type name to Puppet.newtype deprecation warning so it is easier to find and fix those occurrences.

(PUP-4517) Add type name to Puppet.newtype deprecation warning

---

ext/osx/puppet.plist

This commit adds a launchd plist for use with OSX AIO packaging.

(PUP-4532) Add launchd plist for use with OSX AIO

---

lib/puppet/forge/repository.rb
lib/puppet/network/http/factory.rb
lib/puppet/provider/package/pkgdmg.rb
lib/puppet/util/http_proxy.rb
spec/unit/network/http/factory_spec.rb
spec/unit/provider/package/pkgdmg_spec.rb
spec/unit/util/http_proxy_spec.rb

Implement support for the no_proxy variable in various places where http_proxy was taken into consideration such as accessing the forge.

(PUP-4030) Support no_proxy env variable

---

spec/unit/provider/service/base_spec.rb

Rather than rely on executing ruby to manipulate a file to "emulate" a
service start/status/stop command, stub command execution itself to
ensure the base service provider is executing the commands as expected.

(PUP-4524) Stub command execution in base service provider spec.

---

lib/puppet/network/http/factory.rb

A require for `puppet/util/http_proxy` was missing for
`puppet/network/http/factory` after code that uses
`Puppet::Util::HttpProxy` was added.
This originally passed specs because the spec required the file before
using the HTTP factory.

(PUP-4030) Add missing require for Puppet::Util::HttpProxy.

---

.gitignore
spec/integration/type/file_spec.rb

This commit adds 5 tests for the `ignore` attribute of the File resource.

(PUP-4347) Add test for the File resource ignore attribute

---

lib/puppet/provider/mount/parsed.rb
lib/puppet/type/mount.rb
spec/integration/provider/mount_spec.rb
spec/unit/type/mount_spec.rb

Previously, when not specifying options to a mount resource, puppet
would fail with an opaque resource. It would create a bogus fstab entry
without an options field.
This commit adds in the `default` option to ensure that the options
field is created and valid for all mount resources.
Contribution originally from Mark Bainter <mbainter+github@gmail.com>

(PUP-1931) Fix mount provider failure w/o options

---

lib/puppet/resource/status.rb
lib/puppet/transaction.rb
spec/integration/transaction_spec.rb

I profiled `puppet agent --test` on one of my servers using stackprof
[1] on Ruby 2.1.
Something like 30% or more of the time was spent in
`Puppet::Graph::SimpleGraph#upstream_from_vertex`, called from
`Puppet::Transaction#failed_dependencies?`
It turns out that, while evaluating the resource graph, when considering
a resource, we look at *the complete set of transitive dependencies* to
evaluate whether any of them have failed. This is hugely expensive, and
moreover, is wasted work in the success case where no resources fail.
Instead of all that work, this patch pushes the work to the *failed*
nodes; When a node fails, we transitively walk the dependents of that
node, and mark them as having failed dependencies, and then check that
flag directly when considering whether to skip a node …

(PUP-3930) Optimize `failed_dependencies?`

---

acceptance/tests/ensure_puppet-agent_paths.rb

In FACT-956, the ruby facter component was removed from
puppet-agent#master, and cfacter was renamed to facter. As a result,
there are no longer files named cfacter.
This commit updates the acceptance test to no longer check for cfacter.

(maint) CFacter is no longer in puppet-agent master

---

appveyor.yml

The appveyor script gives the appearance of setting to Ruby 2.1.5,
but that particular folder doesn't actually exist, so it is actually running with Ruby 
1.9.3. When the build runs it should share the environment variables, the 
Gemfile.lock file and the Ruby version it is set on. ~~Additionally it should test both 
x86 and x64 architectures.~~
Additionally we should test against the x64 architecture, which should catch a 
reasonable amount of failures related to Windows. Adding a second architecture 
slows the build down quite a bit (to more than double the amount of time),
so we won't go the route of adding a matrix for now.

(maint) Fix/update AppVeyor settings

---

lib/puppet/pops/evaluator/access_operator.rb
lib/puppet/pops/issues.rb
lib/puppet/pops/types/type_calculator.rb
lib/puppet/pops/types/type_factory.rb
lib/puppet/pops/types/type_parser.rb
lib/puppet/pops/types/types.rb
lib/puppet/pops/types/types_meta.rb
spec/unit/pops/evaluator/access_ops_spec.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/types/type_calculator_spec.rb

This PR adds a new `NotUndef` type. The purpose of this type is to constrain its contained type so that it is not assignable from the `Undef` type. The contained type is optional and defaults to `Any`.
The PR also changes the behavior of the `Struct` type by allowing its members to be types. This change enables declaration of required members who's values may be optional.

(PUP-4483) Add NotUndef type to the Puppet type system

---

lib/puppet/pops/evaluator/evaluator_impl.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/migration_spec.rb

Before this, and after 3.7.5, a case option being a literal default
was selected when encountered instead of being selected last if no other
option was selected.
This was introduced when adding either support for deep merge, or for
migration checking. There was no test finding this regression.
(A similar problem was found earlier with selector).
The fix was to remove the call to is_match? for the default option and
instead return false (to continue with other case option values in the
same option.
As a consequence, one migration test needed to be changed as it reported
a "type diff" for default vs. Resource type (which was actually wrong,
since a comparisson against default is not considered a type match diff)

(PUP-4520) Fix regression with case default option not being done last

---

lib/puppet/pops/migration/migration_checker.rb

Befoe this, reflection had to be used to see what a version of a
MigrationChecker implements.
This is now changed so all versions of puppet after 3.8.0 has a method
that returns the migration checks that are implemented. This makes it
possible to have newer versions of the migration checker support older
versions of puppet (>= 3.8.0).

(PUP-4527) Add MigrationChecker method to provide available migrations

---

lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/migration/migration_checker.rb

This merges the implementation of PUP 4527 into stable (from 3x) and provides fix up of earlier merges that added back calls to the migration checker (from PUP 4127).
A safety mechanism is added (raising errors) if any of the methods that should not be called in the migration checker is called by mistake.

(PUP-4527) merge 4527 from 3.x and fix up earlier merge mistakes

---

lib/puppet/defaults.rb
lib/puppet/indirector/catalog/compiler.rb
lib/puppet/node.rb
lib/puppet/parser/compiler.rb
lib/puppet/parser/scope.rb
lib/puppet/pops/evaluator/runtime3_support.rb
spec/integration/parser/compiler_spec.rb
spec/unit/node_spec.rb

Prior to this change, there was no way for module authors to ensure
that they were getting trusted server facts due to the fact that
server side global variables can be overwritten by client side
facts.
Add the $server_facts global variable which will contain a hash
of server side facts which cannot be overwritten. Add the
corresponding trusted_server_facts setting. The setting is false
by default, but if set to true by the user then the $server_facts
variable will be populated.
Additionally, if merge attempted to set a node parameter
that already existed, it would quietly fail to update the value.
This meant that if a client fact value was being used for one of
the server side facts, it would not be overwritten with the correct
value and the user would never know.
Since we cannot change …

(PUP-2630) Ensure it is possible to get trusted server facts that cannot be overwritten

---

acceptance/tests/reports/finalized_on_cycle.rb
lib/puppet/configurer.rb

After the initial work on PUP-735, we were left with a situation where
certain catalog apply errors (including resource cycles) could casue a
report to not be finalized. An easy symptom of this to see is that the
metrics section of the report is empty.
This fixes the configurer to always finalize the report, and adds a
test.

(PUP-735) Ensure reports are finalized when catalog.apply fails

---

spec/integration/application/apply_spec.rb
spec/lib/puppet_spec/files.rb
spec/unit/parser/functions/generate_spec.rb

The ENC integration tests using the exec terminus were originally only
implemented with shell scripts. Extend the testing to create Windows batch
scripts and run on Windows.
Also create a new spec_helper script_containing to generate a script on
the appropriate platform. Since script languages also differ, usage
requires that you provide both Windows and shell versions of the script.

(PUP-4473) Extend ENC tests to Windows

---

acceptance/tests/reports/finalized_on_cycle.rb

With our Windows MSI package, Puppet isn't installed into normal Ruby
library locations. For puppet/facter/etc we provide wrappers that setup
RUBYLIB, but the same isn't done for ruby/irb. Disable the test on
Windows until PUP-4547 can be fixed.

(PUP-735) Disable finalized_on_cycle on Windows

---

lib/puppet/provider/user/openbsd.rb

Note that an openbsd-specific user provider was added in
https://github.com/puppetlabs/puppet/commit/986281e1d. However,
that commit neglected to include a confine, so the provider
became suitable for all platforms (although it isn't actually
suitable). Since puppet resolves suitability ties alphabetically,
this meant that providers alphabetically after 'openbsd' would
lose out to this provider.

(PUP-4491) Add a proper confine for the openbsd user provider

---

lib/puppet/pops/types/type_calculator.rb
spec/unit/pops/types/type_calculator_spec.rb

This commit ensures that String types that represents keys in a
Struct type are excluded from generalization. The reason for this
is that such generalization would remove the value that the String
represents and thus, the name of the member.

(PUP-4551) Do not generalize struck key types

---

lib/puppet/agent.rb
lib/puppet/application/apply.rb
lib/puppet/util/splayer.rb
spec/unit/agent_spec.rb
spec/unit/application/apply_spec.rb
spec/unit/util/splayer_spec.rb

For masterless deploys it would be good if puppet apply supported splay just like agent does to avoid thundering herd issues (without the need of wrapping it in a shell script with a sleep).
The `--test` option should imply `--no-splay` just like it does in the agent.

(PUP-4363) Support splay in apply as well

---

acceptance/tests/parser_functions/calling_all_functions.rb

This change adds a test for all parser functions.
This test calls all the parser functions that ship with puppet.  It
ensures sane output in most cases.  The remainder of the coverage for
functions lies in the spec tests.

(PUP-4342) test calling all parser functions

---

lib/puppet/defaults.rb

Commit e1c8724df80190946ebde0559eb15fb4902797cc resolved a conflict
in defaults.rb that re-introduced the stringify_facts,
trusted_node_data, and immutable_node_data settings that were removed in
4.0.
This commit removes them again.

(maint) Fix bad merge from 3.x branch.

---

.gemspec

This will prevent gem upgrade on environments with ruby 1.8.7

(PUP-4601) Add ruby version requirement to .gemspec.

---

acceptance/tests/windows/eventlog.rb

Prior to commit 88ae8a9, it was an error to specify a `confdir` whose
parent directory didn't exist. After the change, puppet would create the
ancestor directories `C:/does/not`, enabling puppet's settings catalog
to create the `confdir` named `C:/does/not/exist`.
This commit changes the test to no longer rely on setting an invalid
confdir.  Instead it just runs `puppet agent` trying to connect to a
non-existent master, as it did before, and it changes the expectation to
match the error we generate.
The commit also changes from the deprecated `puppet_agent` beaker
method to `puppet('agent', ...)`.
It would have been nice to test this behavior using:
puppet apply -e "err('some message')"
However, `apply` uses the console as the default log destination. It is
possible to specify `puppet …

(PUP-4436) Generate error message in eventlog differently

---

acceptance/tests/language/PUP-2630-server_set_facts.rb

This change adds an acceptance test that ensures the proper function of
trusted_server_facts setting and $server_facts puppet variable.
It has to restart the master twice, along with several agent runs, unfortunately.

(PUP-4419) create acceptance to ensure no overwrite of server-set variables

---

acceptance/tests/windows/eventlog.rb

The acceptance test fails on 2003, because the messages in the event log
contains a trailing carriage return "\r" as can be seen from the
message:
U5OCQ1AVU5DNJ72,Could not retrieve catalog; skipping run
,Error
The same test doesn't fail on 2012, because the message does not contain
a carriage return:
REQSRXS29NWN1ZY,Could not retrieve catalog; skipping run,Error
I verified that puppet is not calling Win32 ReportEvent with a
carriage return. Instead, it seems 2003 always adds a carriage return to
events as can be seen when copying the message to the clipboard:
Description:
Could not retrieve catalog; skipping run
This commit adds back the extra .* in the regexp to account for 2003 vs
later differences.

(PUP-4436) Relax regexp to handle carriage return on 2003

---

lib/puppet/provider/package/pkgin.rb
spec/unit/provider/package/pkgin_spec.rb

The output for 'pkgin list' has been changed to separate fields with ';'
for non-interactive terminals, so adjust the regex accordingly. To ensure
we'll always get this output pass '-p' to the list command (this is what pkgin
does internally for non-interactive terminals).

(PUP-4546) Fix retrieving package version in #instances

---

lib/puppet/indirector/facts/facter.rb
spec/integration/indirector/facts/facter_spec.rb

In Facter 2.x, upon the first Facter.add, the directory loaders
are created and cannot be changed.
PUP-4359 added the puppetversion fact before setting the external
fact directories, meaning that no other external facts were being
found by Puppet in puppet specific external fact directories.
This commit causes Puppet to first set its external fact directories,
and then add the puppetversion fact.

(PUP-4607) Fix loading external facts

---

acceptance/tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb
lib/puppet/file_serving/metadata.rb
lib/puppet/file_serving/terminus_helper.rb
lib/puppet/type/file.rb
spec/unit/file_serving/metadata_spec.rb
spec/unit/file_serving/terminus_helper_spec.rb

Prior to this commit, the :source_permissions attribute was
not being properly propagated into the Posix MetaStat class,
and so source permissions were ignored for all resources.
External facts are required to use source permissions so
that the facts are executable when they are downloaded onto
the agent. This means that due to this regression, external
facts were being pluginsync'd to the client without execution
permissions.
This commit re-enables using source permissions for fact
pluginsync, while continuing to ignore them otherwise.
See commit 21edcd6 for the first fix for of a similar, earlier
regression.

(PUP-4420) Ensure pluginfacts don't ignore source permissions

---

lib/puppet/resource.rb
spec/integration/parser/future_compiler_spec.rb

The type validation for resource parameters currently uses
TypeCalculator.infer when reporting errors. This commit changes
this so that infer_set is used instead.

(PUP-4552) Use TypeCalculator.infer_set for type validation errors

---

acceptance/tests/resource/file/source_attribute.rb

The mtime/ctime verification that a file update causes resyncing has
been flaky, occasionally failing in CI. A ticket to address that has
been filed at PUP-4115. Until that ticket can be addressed, disable the
flaky portion of the test.

(maint) Disable flaky section of acceptance test

---

lib/puppet/pops/evaluator/access_operator.rb
lib/puppet/pops/types/type_parser.rb
lib/puppet/resource.rb
spec/integration/parser/compiler_spec.rb
spec/lib/matchers/resource.rb

This commit contains the merge of PUT-4552 from 3.x to stable.
In addition to what's covered in that issue, it also copies a lot
of tests from the future_compiler_spec (which doesn't exist in
stable) to compiler_spec.

(PUP-4552) Merge from 3.x

---

lib/puppet/provider/group/windows_adsi.rb
lib/puppet/provider/user/windows_adsi.rb
lib/puppet/type/user.rb
lib/puppet/util/windows/adsi.rb
spec/unit/provider/group/windows_adsi_spec.rb
spec/unit/provider/user/windows_adsi_spec.rb
spec/unit/util/windows/adsi_spec.rb

Supercedes #3876, which superceded #3788 
Previously, when specifying a user's groups, the names were compared
as strings and needed to be an exact match. The group resource uses
SIDs when comparing the users, so the user resource should mimic that
behavior.
Without this change casing and names must match exactly and can 
produce erroneous results.
With this change, the comparison will be by SIDs so it will allow for
the following when a user is a member of Administrators and Users
groups:
```puppet
user { 'tim':
groups => ['BUILTIN\Administrators','users'],
}
```
Groups members can also be set to an empty list and the user's groups will
report that it does but will not make the changes. Allow that the user groups to
be set to an empty list so that group's members and …

(PUP-4373) Windows ADSI User groups property should behave similarly to Groups members property

---

lib/puppet/application/apply.rb
spec/integration/application/apply_spec.rb

Prior to this commit, $server_facts would only be populated during
an agent run. This it made it difficult for users to use
`$server_facts[environment]` in their puppet code since they could
not test it via a puppet apply.
Now that variable will be populated during an apply if
trusted_server_facts is true. It will only contain the environment
portion of the hash.

(PUP-2630) Populate $server_facts during puppet apply

---

lib/puppet/provider/package/pip.rb
spec/unit/provider/package/pip_spec.rb

This backports commit 6ee0339675e7460073483ebc74d4136b27687ae9 to 3.x.
See [PUP-4604](https://tickets.puppetlabs.com/browse/PUP-4604) for the task ticket to backport this fix for PUP-3829.

(PUP-3829) : call 'pip' instead of 'pip-python' on RedHat > 6 in the pip package provider

---

lib/puppet/property/ensure.rb
lib/puppet/provider/package.rb
lib/puppet/provider/package/openbsd.rb
lib/puppet/provider/package/rpm.rb
lib/puppet/provider/package/yum.rb
lib/puppet/type/package.rb
spec/integration/type/package_spec.rb
spec/unit/provider/package/aptrpm_spec.rb
spec/unit/provider/package/base_spec.rb

For package providers, the base package provider was defaulting to a
property hash with a status of :absent when the package was missing.
When the resource is `ensure => purged`, an :absent status causes it to
be purged.  This is because an absent package could represent a
"partially installed" package that is not truly installed and can
therefore be purged (see the dpkg provider).  If the base provider
always returns a status of :absent for missing packages then purgeable
providers will always attempt to purge a missing resource.
The fix is to have the base provider default to a :purged status when
the resource is missing and the provider supports purging.  Otherwise,
it defaults to :absent like before.

(PUP-1295) Fix always purging package resources that are not installed.

---

acceptance/Rakefile

Previously we were depending on the "use-el-extras" feature of Beaker
but we were not taking full advantage of its ability to point at an EPEL
mirror.  We have sporadically seen failures based on the availability of
the mirrors at kernel.org.
This commit infers if we are running within the internal network by
looking for a well known environment variable and, if so, adds the
appropriate beaker configuration to use our internal epel mirror.

(QENG-1453) Make use of Beaker's epel_url option

---

appveyor.yml

Previously, tests executed in a platform-specific order in appveyor, and
if an order dependent failure happened, we didn't know what the order
was.
This commit sets the `LOG_SPEC_ORDER` environment variable which causes
puppet's spec helper to write each spec to `spec_order.txt` in the
project root.
It also adds an `on_failure` handler to archive the file, which can then
be downloaded from the job's Artifacts tab.

(maint) Archive spec_order.txt on appveyor failures

---

appveyor.yml

- When running specs in our local Jenkins environment, the
'extra' gems, which include 'msgpack' are not installed.  We do
this because:
- 'msgpack' requires building native code, which unnecessarily
adds to the feedback loop
- we intentionally try to maintain a clean environment without
the Ruby DevKit installed
This has previously worked on AppVeyor because they have the
Ruby DevKit installed.

(maint) remove extra gems from appveyor

---

lib/puppet.rb
lib/puppet/parser/compiler.rb
lib/puppet/pops.rb

Before this, when the compiler was instantiated from an environment that
was configured to use parser=current, the initialization of the context
for compilation would do this for parser=current. This led to not having
loaded the ruby code for Puppet::Pops::Loaders, and because of this, the
first function call made in a puppet manifest would fail.
This fixes the problem by making the compiler check if the environment
it is going to *set* as the current environment has parser=future set
(instead of checking in the current environment).
This also moves the requirement to load the ruby logic to the loading of
'puppet/pops' since the loaders since quite some time back are lazilily
initialized.

(PUP-4636) Fix problem with environment.conf parser=future

---

lib/puppet/type/exec.rb

Could probably clearer that the `unless` and `only` parameters have all the same parameters as the main exec, not just the path.

(DOCUMENT-319) Clarification on unless and only

---

lib/puppet/provider/service/debian.rb
spec/unit/provider/service/debian_spec.rb

This fix is also needed for 3.x puppet-agents, because most system don't and will not puppet-agent 4.x for a more or less long time. Commit 1e096fd5537cbfcd66a21833bdd538e279aa2e95 has been cherry-picked for this PR.

(PUP-3166) Backport Debian provider handles 101 status

---

ext/build_defaults.yaml

This commit bumps the version of facter included in the puppet msi to
the latest release available, which is facter 2.4.4

(maint) Bump facter version included in the MSI

---

acceptance/tests/resource/mount/defined.rb
acceptance/tests/resource/mount/destroy.rb
acceptance/tests/resource/mount/modify.rb
acceptance/tests/resource/mount/mounted.rb
acceptance/tests/resource/mount/query.rb

Add basic acceptance tests for mount type. This adds acceptance
tests for defined, mounted, query, modify, and destroy.

(PUP-2400) Add mount acceptance tests

---

acceptance/tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb
lib/puppet/configurer/plugin_handler.rb
lib/puppet/face/plugin.rb
spec/unit/configurer/plugin_handler_spec.rb
spec/unit/face/plugin_spec.rb

Puppet has a `plugin` face application whose `download` action will perform a pluginsync. However, it did not `use` source permissions when downloading external facts. As a result, executable external facts could not be executed on the agent. This is similar to PUP-4420, but is a different code path that triggers the same bad behavior.
This commit modifies the `download` action to use the same code paths that the configurer uses to perform pluginsyncing of external facts and modules. It also adds spec and acceptance tests.

(PUP-4538) Use source permissions when using plugin application

---

acceptance/tests/modules/build/build_ignore_module_file.rb

This commit changes the 'build_ignore_module_file' acceptance test to
create its own unique tmpdir for use while the test is running.  In the
previous commit, the test would try to populate the tmpdir at a
hard-coded location, '/tmp/test', which would fail if that directory were
pre-existing.

(PUP-4666) Create unique tmpdir for 'build_ignore_module_file' test

---

lib/puppet/provider.rb
lib/puppet/provider/package/gem.rb
spec/unit/provider/package/gem_spec.rb

The gem package provider was previously not implementing insync? but
supported a provider-specific version string for gem version specifiers
(e.g. '~> 2.0').  This resulted in the resource always being out-of-sync
when a gem version specifier was used.
This adds an implementation of insync? that uses the rubygems API to
verify the version specifier matches.

(PUP-4131) Implement insync? for gem package provider.

---

lib/puppet/provider/service/freebsd.rb
spec/unit/provider/service/freebsd_spec.rb

Take just the leading string of non-whitespace characters from the
first line of the rcvar output as the service name

(PUP-4530) Fix FreeBSD service provider to parse service names correctly

---

lib/puppet/parser/scope.rb
spec/unit/parser/scope_spec.rb

Add an inspect function to the Puppet::Parser::Scope class that
aliases to the to_s method so that calling inspect on a scope no
longer generates a massive, unused string.

(PUP-4665) Add inspect function to scope class

---

.gemspec

Removing `rubygems_version` from gemspec as it breaks under the most
recently released version of bundler.
From the documentation this should not be set and is instead generated
by rubygems at packaging.

(maint) Remove rubygems_version from gemspec.

---

acceptance/config/nodes/osx-1010-x86_64.yaml
acceptance/config/nodes/osx-109-x86_64.yaml

Note: We currently aren't building packages for Vivid yet so I don't have an artifact to test these configs with. Having said that, I copied existing configs and updated them, this should be a very low risk change.
I used a "code name" approach to the platform as is done with Debian. I don't know if this is how you folks prefer the OSX testing or if you'd want to refer to their platform as numeric.

(maint) Add acceptance configs for OSX

---

lib/puppet/pops/evaluator/runtime3_converter.rb
spec/unit/pops/evaluator/runtime3_converter_spec.rb

Before this the use of references such as Classroom, Classroom[x] would
when converted to a 3.x parameter value i.e. used this way:
notify { bad: require => Classroom[nbr3] }
would misinterpret the leading 'Class' (or 'class') as if it was a
reference to the class nbr3 not the resource Classroom[nbr3].
This was caused by a non end-anchored regular expression.

(PUP-4668) Fix leading 'class...' 3.x resource type conversion

---

lib/puppet/parser/scope.rb
spec/unit/pops/evaluator/variables_spec.rb

Before this, it was not possible to access top scope variables (e.g.
$::x) from a local scope with top scope as parent if a local scope
shadowed the variable.
The problem is primarily caused by the strange Scope implementation
where Scope represents both itself and all local/ephemeral scopes where
it is ultimately the parent. This has lead to complicated logic inside
scope when looking up variables.
The test that was supposed to test this case was flawed and in realtiy
tested that it did not work!
The fix is unfortunately to add yet another special case.

(PUP-4662) Fix :: access to top scope from within top scope

---

lib/puppet/pops/parser/epp_support.rb
spec/unit/pops/parser/lexer2_spec.rb

Before this, a right trim would replace the whitespace on each following
line up to the next tag instead of just trimming the space on the same
line as the ending tag.
A similar problem occured for a left trim, as it removed the line ending
of the previous line.
Fixing these issues means more strictness wrt which whitespace is
trimmed by each rule.
* A right trim rule trims at most to (including) a line break, stopping
on the first non whitespace.
* A left trim rule troms at most to the beginning of the same line as
the opening (left trimming tag).
This has consequences for comment tags (as they cannot start with a left
trim). Instead, they are now always made left trimming. This is the most
reasonable thing to do since they otherwise needs to be placed
immediately adjacent to a tag or …

(PUP-4648) Fix EPP trimming/indentation problems

---

lib/puppet/module.rb
spec/unit/module_spec.rb

Before this commit, there was an undocumented field, puppetversion, which was tracked by the Puppet::Module class.  An error would be thrown if the metadata value was present and was not an exact string match to Puppet.version.  This commit removes the recognition and checking of that metadata key:value pair.
Note: Accessors and validation for puppetversion still exist in order to not cause a breaking change, but they return nil.

(PUP-4356) Remove puppetversion from PMT metadata

---

lib/puppet/provider/service/systemd.rb

- All supported releases of Fedora have systemd and the latest release
with upstart has been EOLed three years ago. So we could drop the
version restriction now.
Signed-off-by: Gael Chamoulaud <gchamoul@redhat.com>

(PUP-4663) Ensure Fedora uses the systemd service provider

---

acceptance/Rakefile
acceptance/config/git/options.rb

Previously, git based acceptance (rake ci:test:git) defaulted to
facter#stable, but that branch was recently promoted to native facter,
so acceptance would fail trying to install facter `ruby install.rb`
This commit changes the default facter branch to 2.x, containing the
legacy ruby facter implementation. It also relaxes the regex to match
digits and a literal dot, when translating short branch names,
facter#2.x, to git URLs.

(maint) Default to facter#2.x for git based acceptance

---

acceptance/tests/language/functions_in_puppet_language.rb

(PUP-4466) Add acceptance tests for functions in the puppet language
Puppet 4.0 adds support for functions written in the Puppet DSL (.pp files). This commit adds basic acceptance tests for this feature. Other surfaces of the Puppet 4.x function API are tested elsewhere; this extends that testing.

(PUP-4466) Add acceptance tests for functions in the puppet language

---

acceptance/tests/language/functions_in_puppet_language.rb

The original commit for PUP-4466 did not clean up after itself, causing
tests that follow it, particularly modules tests, to fail. This commit
fixes that.

(maint) Add teardown block to remove test fixtures created by the test

---

spec/integration/type/package_spec.rb
spec/unit/type/package_spec.rb

This commit stubs the Process.euid to always return zero for tests
that potentially use the yum provider. This makes the provider think
that the user is root and prevents it from bailing out with the
message: "The yum provider can only be used as root".

(PUP-4701) Fix so that yum provider thinks that user is root

---

acceptance/tests/apply/puppet_apply_graph.rb
lib/puppet/application/apply.rb
lib/puppet/configurer.rb
lib/puppet/settings.rb
spec/unit/application/apply_spec.rb

Previously, if you installed puppet, and never executed `puppet agent`,
but immediately executed `puppet apply` (such as with vagrant
workflows), and `graph` was true (as is the default in PE), then
puppet would fail to write the graph. This occurred because `puppet
apply` tries to write the graph (during `Catalog#to_ral`) before
creating the necessary settings related directories (as a side-effect
of calling `Puppet::Configurer.new`).
The `agent` and `device` applications also use the Configurer to apply
the catalog, but they explicitly use the `main`, `ssl`, and `agent`
sections during application setup, and before calling `Catalog#to_ral`.
This commit modifies `apply` to match the other two. Alternatively, the
setup logic could be added to the base `Puppet::Application#setup`, but
it's …

(PUP-2638) Use settings during puppet apply setup

---

lib/puppet/configurer.rb
lib/puppet/indirector/catalog/compiler.rb
spec/unit/configurer_spec.rb
spec/unit/indirector/catalog/compiler_spec.rb

Prior to this commit, there was no way to write an external node
classifier that allows some agents - based on Facts - to override the
node classifier with its own requested environment.
The first request from the agent for the environment will not use the
correct Facts (that might need to include custom facts), which may end
up classifying it in the incorrect environment. Subsequent requests
will send that environment instead of the configured environment.
Fix by passing the configured environment to the Node::Facts find
request as a new option.

(PUP-4521) Add configured_environment to Node Facts find

---

lib/puppet/indirector/facts/facter.rb
lib/puppet/settings.rb
spec/integration/indirector/facts/facter_spec.rb
spec/unit/indirector/facts/facter_spec.rb

Creates an `agent_specified_environment` fact with the value being the
environment name if the environment was set on the agent by the user.

(PUP-4522) Set agent_specified_environment

---

ext/suse/client.init

This was an oversite when the init script was initially updated for AIO
pathing. This commit just adds in a (hopefully) final update

(packaging)(RE-4770) Update puppet init script to handle AIO pathing

---

acceptance/tests/environment/environment_scenario-bad.rb
acceptance/tests/environment/environment_scenario-default.rb
acceptance/tests/environment/environment_scenario-master_environmentpath.rb
acceptance/tests/environment/use_enc_environment_for_files.rb
acceptance/tests/environment/use_enc_environment_for_pluginsync.rb
acceptance/tests/environment/use_environment_from_environmentpath.rb

Previously, the tests failed when the master had the agent role. This
wasn't noticed originally due to PUP-4111. We also stopped testing the
agent role on the master in the lead up to Puppet 4, so once PUP-4111
was fixed, we didn't see the problem in platform CI. But puppetserver CI
does test that combination and was failing.
These commits update some of the environment related tests to
match the current and expected behavior.

(PUP-4659) Update environment tests

---

lib/puppet/provider/package/gem.rb

Prior to rubygems 2.0.0, creating a Gem::Dependency with an invalid
version, would raise an ArgumentError. During the rubygems 2.0.0 rc,
it was changed to raise IllformedRequirementError[1], but was renamed to
BadRequirementError prior to the 2.0.0 release[2].
As a result, if you ran puppet from source or a gem install, and tried
to manage a `gem` package using rubygems < 2.0 (so really ruby < 2.0),
then puppet would raise an exception due to the undefined constant
Gem::Requirement::BadRequirementError.
This commit rescues ArgumentError, which is the parent of
BadRequirementError, and so will work for all supported rubygems
versions.
[1] https://github.com/rubygems/rubygems/commit/c53ac0f5a
[2] https://github.com/rubygems/rubygems/commit/ccfbb4feb

(PUP-4131) Rescue generic ArgumentError

---

acceptance/config/nodes/centos-4-i386.yaml
acceptance/config/nodes/centos-4-x86_64.yaml
acceptance/config/nodes/centos-7-x86_64.yaml
acceptance/config/nodes/oracle-5-i386.yaml
acceptance/config/nodes/oracle-5-x86_64.yaml
acceptance/config/nodes/oracle-6-i386.yaml
acceptance/config/nodes/oracle-6-x86_64.yaml
acceptance/config/nodes/oracle-7-x86_64.yaml
acceptance/config/nodes/redhat-4-i386.yaml
acceptance/config/nodes/redhat-4-x86_64.yaml
acceptance/config/nodes/scientific-5-i386.yaml
acceptance/config/nodes/scientific-5-x86_64.yaml
acceptance/config/nodes/scientific-6-i386.yaml
acceptance/config/nodes/scientific-6-x86_64.yaml
acceptance/config/nodes/scientific-7-x86_64.yaml
acceptance/config/nodes/sles-10-i386.yaml
acceptance/config/nodes/sles-10-x86_64.yaml
acceptance/config/nodes/sles-11-i386.yaml
acceptance/config/nodes/sles-11-x86_64.yaml
acceptance/config/nodes/sles-12-x86_64.yaml
acceptance/config/nodes/ubuntu-1004-i386.yaml
acceptance/config/nodes/ubuntu-1004-x86_64.yaml

Prior to this there were no acceptance test host config files for PE
only platforms. The distinction between PE and FOSS is largely going
away (save for where the failures are reported).
This commit adds the necessary host configs to test Puppet against all
the platforms we will distribute puppet-agent on in the Shallow Gravy
timeframe.

(maint) add PE platform configs

---

ext/redhat/client.init
ext/redhat/client.sysconfig
ext/suse/client.init

…onfig values
Currently, the EL and SLES init scripts will read variables from /etc/sysconfig/puppet
and override variables set in puppet.conf or the init sctipt. This can lead to
undesired behavior, like an old sysconfig file setting variables incorrectly, causing
startup failures, etc.
This updates the sysconfig files to be more conistent with the defaults file we
ship for Debian, and updates the EL and SUSE init scripts to only use the
PUPPET_EXTRA_OPTS variable if it exists, and to ignore other settings that
are better set in puppet.conf or that should not need to be overridden at
all (like pidfile for example).

(packaging) (re-4770) Update init script to ignore old/incorrect sysconfig values

---

lib/puppet/provider/group/pw.rb
lib/puppet/provider/user/pw.rb

These providers were designed to function on systems similar to FreeBSD. If a
`pw` binary shows up on Linux, the providers will be activated and Puppet's
ability to manage users and groups will break.

(PUP-4693) Confine the pw user and group providers to BSD (Puppet 3.x)

---

lib/puppet/provider/group/windows_adsi.rb
lib/puppet/type/group.rb
spec/unit/provider/group/windows_adsi_spec.rb

Assume that `puppet resource group guests` yields the following:
```puppet
group { 'guests':
ensure  => 'present',
gid     => 'S-1-5-32-546',
members => ['Guest', 'Administrator'],
}
```
Previously, trying to apply the following manifest with a bad user,
would trigger a bug in Puppet:
```puppet
group { 'guests':
members => ['Guest', 'Administrator', ''],
}
```
An error would be raised in resource_harness#sync_if_needed method, and
would lose important details about expected resource changes:
```
Notice: Compiled catalog for vagrant-2008r2.corp.puppetlabs.net in environment production in 0.22 seconds Error: Could not resolve username:
Error: /Group[Guests]: Could not evaluate: Puppet::Util::Log requires a message
Notice: Finished catalog run in 0.05 seconds
```
This …

(PUP-4386) Windows group invalid user error msgs

---

api/docs/http_catalog.md
api/docs/http_file_metadata.md
api/docs/http_node.md

This commit is mostly about bad Markdown formatting that can limp along in some
renderers but will break others.

(docs) Fix formatting in some API docs

---

lib/puppet/resource.rb

Before this, there would be one call to Puppet.future_parser? for every
attribute of a resource. This call is expensive esp. when it is not
given an environment as an argument. Users report 20-30% of catalog
compilation time spent on this alone!
Now, the check is only performed once per resource, and then with the
environment of the resource. This is safe because all attributes of a
resource are natually also in the same environment, and the parser
setting cannot change (at least in a sane way) between attributes being
copied.

(PUP-4703) Optimize copy_as_resource checks for future parser

---

lib/puppet/parser/functions/fqdn_rand.rb
lib/puppet/util.rb
spec/unit/parser/functions/fqdn_rand_spec.rb

Before this, fqdn_rand always returned a String. That is not the best
choice for a numeric value now that the evaluator is aware of different
data types as comparissons will typically be wrong (since '2' > '19'
when compared leicographically).
This fix adds a utility method that returns an integer version while the
old utility method producing a string is retained for those that use
Puppet as an API. The function now uses the integer version of this
utility method.
A test is added that asserts that an Integer is produced.
At some point it would be beneficial to reimplement the function using
the 4.x function API as it will simply raise a generic error if given
input of the wrong type. It will also magically change a floating point
input value to integer.

(PUP-4698) Change fqdn_rand's return type to Integer

---

lib/puppet/parser/ast/pops_bridge.rb
lib/puppet/resource/type.rb

In the Puppet 3 parser, default parameter values on a serialized
resource_type object would appear to be puppet source code. This makes the
Puppet 4 parser behave roughly the same way, by retrieving the original source
code representing an argument.

(PUP-4747) Format resource_type arguments as source code

---

ext/build_defaults.yaml

This commit updates the pinned SHAs for the
embedded Ruby in the Windows Puppet agent
to update to OpenSSL 1.0.0.s.
The update for x64, which uses Ruby 2.0, also
remediates the embedded RubyGems for CVE-2015-4020.
(The embedded RubyGems in Ruby 1.9.3 is not affected
by CVE-2015-4020.)

(RE-4831) Update RubyGems and to OpenSSL 1.0.0.s

---

lib/puppet/parser/scope.rb
lib/puppet/pops/evaluator/runtime3_support.rb
spec/integration/parser/scope_spec.rb

Before this it was close to impossible to correctly call a function in
an agnostic way from a 3.x function or ERB template.
This commit adds the ablity to call a function by given name, with
arguments given using 4.x semantics. It will load and call either a 4.x
function or a 3.x function. For a 3.x function it will perform argument
transformation as needed (just as if the call came from 4.x puppet
code).
Since there is no (easily obtained) information abailable about which
module the call originates from a 4.x call is done from the perpective
of the environment (thus, later when there are module private functions,
those will not be callable; but for now, this distinction does not
exist).

(PUP-4753) Add ability to call 3.x and 4.x function from scope

---

spec/lib/matchers/include_in_order.rb

The rspec-expectations gem removed `RSpec::Matchers::Pretty` in version
3.3.0.  This resulted in spec failures in CI when 3.3.0 was used.
See related commit:
https://github.com/rspec/rspec-expectations/commit/be1d897d48b8a41ef2869fefe8404e3d26b1f5fc
This fix removes the include of this module.  This may make failure
messages "not pretty" for anyone using rspec-expectations older than
3.3.0.

(maint) Remove RSpec::Matchers::Pretty usage.

---

lib/puppet/util/log.rb
spec/unit/provider/zone/solaris_spec.rb
spec/unit/util/log_spec.rb

The provider should directly call `Puppet.debug` and `Puppet.err`
because of the issue described in the PUP ticket.

(PUP-3088) Fix zone provider debug call

---

acceptance/tests/parser_functions/calling_all_functions.rb

The previous version of this test incorrectly handled the testdir
variable, as it could have been set from multiple agents, when they
exist (puppet server).  This is a simple change to only have a single
agents loop, rather than having to store an array or hash of testdirs.

(PUP-4749) testdir incorrectly used in calling all functions test

---

spec/integration/util/rdoc/parser_spec.rb

Appveyor has transient failures running rdoc parser tests on windows
only. Puppet uses rdoc as part of its `puppet doc` command. The
puppet-strings project has mostly, but not yet completely, replaced the
`puppet doc` command. At a future date `puppet doc` will be deprecated
and removed. This commit skips the tests on windows.

(PUP-4537) Skip rdoc tests on windows

---

.gemspec
Gemfile
ext/project_data.yaml

Previously, installing puppet from source or a gem would refuse to use
hiera 3, even though that is the combination that will be included in
puppet-agent 1.2.0.
This commit allows puppet to use hiera 3 as a dependency. Bundler uses
the Gemfile to resolve dependencies when running puppet from source. Our
gem packaging tasks use ext/project_data.yaml when building puppet as a
gem. This way if you gem install puppet, its runtime dependencies will
also be installed. The .gemspec is special, because it only used when
other code, e.g. module, has a dependency on puppet and is running
against a source checkout of puppet (as opposed to a puppet gem).

(PUP-4777) Allow hiera 3 as a puppet dependency

---

spec/unit/pops/evaluator/evaluating_parser_spec.rb

The evaluator spec tests started failing when Hiera 3.0.1 was brought
in. This was unexpected as the tests does not rely on data binding being
in effect. Instead it is running with string variables to ensure that no
unknown variables are used in the tests. At the same time, tests had not
made the now required variables $environment and $trusted available.
The fix is to run these tests without databinding.

(maint) Fix failing test caused by databinding being in effect

---

lib/puppet/node.rb
spec/unit/node_spec.rb

Before this, a Puppet::Node would serialize to YAML in such a way
that all of its instance variables were serialized. This caused
everything in a compelte Environment to be serialized (everything
loaded and evaluated), which in turn can cause OOM, or OOStack errors.
The cause of the problem is that Puppet::Node did not correctly
include Puppet::Util::PsyckSupport which handles the Yaml serialization
API and turns them into calls: to_data_hash, and initialize_from_hash.
The older way of using 'to_yaml' (one such implementation is found in
Environment itself) never gets called when it is not at the root of the
serialization.
This commit adds the missing include and refactors the initialization
from a hash to use the correct API. It also keeps the older way of a
class method from_data_hash, …

(PUP-4775) Make Puppet::Node serialize env as a string in YAML

---

lib/puppet/provider/zone/solaris.rb
spec/unit/provider/zone/solaris_spec.rb

This reverts commit 1764674bea168a9e6619ddcbc4e698eb236742f8.
Originally, this commit changed the Solaris Zone provider's debug
and error messages to use the global utilities, which means that
they aren't prefixed with the provider context. This was done to
circumvent PUP-3088, which is now fixed.

(PUP-4770) Revert "(maint) Fix debug and error output"

---

lib/hiera/puppet_function.rb
lib/puppet/functions/hiera_include.rb
spec/unit/functions/hiera_spec.rb

Before this, the hiera_include function would call the include function
with its closure scope instead of the calling scope. This caused the
include function to not understand in which class the include was made,
and variable scoping would be wrong - not seeing variables in node
scope.
The hiera 4.x functions already received the calling scope, but did not
pass it on to the post processing method, that in hiera_include's case
performs the call to the include function.

(PUP-4789) Make hiera_include function call include in calling scope

---

lib/puppet/node.rb
spec/unit/node_spec.rb

Before this, (introduced in PUP-4775 where the serialization
was changed to use Psych support for asymetric serialization), two of
Puppet::Node's instance varaibles (@classes, and @parameters) where
initialized to nil on deserialization. When again serializing a check
was made if these where empty? (which fails).
This was caught by a roundtripping acceptance test where a
yaml-serialized node was turned into json via serialization.
The fix was to initialize to [] and {} respectively in the
initialize_from_hash method.
This also adds a unit test for a roundtrip serialization where classes
and parameters are not included in the serialized data.

(PUP-4787) Initialize @vars of Puppet:Node with expected defaults

---

lib/puppet/agent.rb
lib/puppet/agent/locker.rb
lib/puppet/daemon.rb
lib/puppet/error.rb
spec/unit/agent/locker_spec.rb
spec/unit/agent_spec.rb
spec/unit/daemon_spec.rb

This fixes a possible raise condition in the puppet agent where it first
checked if the lock was taken and then later on aquired it, possibly
having some other agent taking the lock in between with no handling of
that situation.
Also it updates the description of the lock method to actually match
what it does, namely return the value of the block itself. Not
true/false based on if lock was acquired. That was in fact impossible to
find out previously.

(PUP-2573) Make agent locker raise LockError if we fail to aquire lock

---

lib/puppet/file_bucket/dipper.rb
lib/puppet/indirector/request.rb
spec/integration/file_bucket/file_spec.rb
spec/unit/indirector/request_spec.rb

Network communication with filebuckets used to be implemented by
1. building a REST URL using logic that duplicated that from
Puppet::Network::HTTP::API::IndirectedRoutes
2. deconstructing the URL when handling this special case
of Puppet::Indirector::Request
This is a relic from API v1 (release 0.25.5) and has not been
necessary for a while, apparently.
We can just stop doing both of those things and the filebucket
Just Works.

(PUP-4653) stop using hardcoded REST URLs around the filebucket

---

lib/puppet/provider/service/smf.rb
spec/unit/provider/service/smf_spec.rb

This change adds the -H flag to /usr/bin/svcs to strip out the column headers.

Add -H flag to svcs to strip column headers

---

lib/puppet/module_tool/skeleton/templates/generator/.gitignore
lib/puppet/module_tool/skeleton/templates/generator/.yardopts
lib/puppet/module_tool/skeleton/templates/generator/manifests/init.pp.erb

* Add .yardopts file. This tells yard to use markdown, not rdoc because we
anticipate that this is what most people will actually want.
* Add generated .yardoc to .gitignore. Yard generates this file and you don't
care about it.
* Convert init.pp comments to use markdown.

(PDOC-16) Improve compatibility of skeleton module with puppet strings

---

lib/puppet/module_tool/metadata.rb
spec/unit/module_tool/metadata_spec.rb

Adds a 'data_provider' entry to metadata.json. The entry must
be an object with a 'name' and an optional 'attributes' array.

(PUP-4489) Add data_provider to module metadata

---

lib/puppet/type/user.rb
spec/unit/type/user_spec.rb

I submit this PR as a trivial fix for PUP-4633.
More details are available in the debian bug report :
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782494
PS: I did not sign the CLA but it looks like it complies with the Trivial Patch Exemption Policy.

(PUP-4633) fix non-ASCII user comment with ruby >= 2.1

---

lib/puppet/application/agent.rb
spec/unit/application/agent_spec.rb

Currently, 'puppet agent' only analyses options beginning with '--', such as '--test' and
'--disable'.  Any other words after agent are ignored.  That is different from the way that
commands like 'puppet resource' and 'puppet apply' work, mainly because those require
an argument, while 'puppet agent' does not.  This has led to, for instance, one of our new
sysadmins typing 'puppet agent disable' instead of 'puppet agent --disable' and being
terribly surprised when about 5 minutes later the server died.
This patch raises an error if someone on the CLI tries to invoke 'puppet agent' with what
has to be an invalid argument.

(PUP-4776) Make 'puppet agent arg' error instead of silently running the catalog

---

lib/puppet/module_tool/metadata.rb
spec/unit/module_tool/metadata_spec.rb

Reverting this change. having binding arguments declared in metadata.json is too complex. A symbolic name will suffice.

Revert "(PUP-4489) Add data_provider to module metadata"

---

lib/puppet/environments.rb
spec/integration/parser/compiler_spec.rb
spec/unit/environments_spec.rb

This adds a better cache eviction algorithm to the environment cache. See commit comments for details.

(PUP-4810) Do not cache 0 ttl entries and evict aggressively

---

lib/puppet/provider/augeas/augeas.rb
lib/puppet/type/augeas.rb
spec/unit/provider/augeas/augeas_spec.rb

This fixes PUP-4629 by using aug.get to return the values of the paths returned by the aug.match operation.

(PUP-4629) Return values instead of augeas paths during the match operation

---

acceptance/Gemfile
acceptance/lib/puppet/acceptance/temp_file_utils.rb
acceptance/setup/aio/pre-suite/010_Install.rb
acceptance/tests/concurrency/ticket_2659_concurrent_catalog_requests.rb
acceptance/tests/config/apply_file_metadata_specified_in_config.rb
acceptance/tests/environment/can_enumerate_environments.rb
acceptance/tests/modules/install/basic_install.rb
acceptance/tests/modules/install/with_version.rb
acceptance/tests/resource/exec/should_run_command.rb
acceptance/tests/resource/file/symbolic_modes.rb
acceptance/tests/resource/group/should_create.rb
acceptance/tests/resource/group/should_modify_gid.rb
acceptance/tests/resource/mount/defined.rb
acceptance/tests/resource/mount/destroy.rb
acceptance/tests/resource/mount/modify.rb
acceptance/tests/resource/mount/mounted.rb
acceptance/tests/resource/service/should_not_change_the_system.rb
acceptance/tests/resource/user/should_create.rb
acceptance/tests/resource/user/should_create_with_gid.rb
acceptance/tests/resource/user/should_modify_gid.rb
acceptance/tests/resource/user/should_modify_when_not_managing_home.rb
acceptance/tests/resource/user/should_modify_while_managing_home.rb
acceptance/tests/security/cve-2013-1652_improper_query_params.rb
acceptance/tests/security/cve-2013-4761_resource_type.rb
acceptance/tests/ticket_9862_puppet_runs_without_service_user_or_group_present.rb

```
...
Total Suite Time: 5297.40 seconds
Average Test Time: 18.99 seconds
Attempted: 279
Passed: 221
Failed: 0
Errored: 0
Skipped: 58
Pending: 0
Total: 279
```
```
...
- Test Case Summary for suite 'tests' -
Total Suite Time: 5486.13 seconds
Average Test Time: 19.66 seconds
Attempted: 279
Passed: 221
Failed: 0
Errored: 0
Skipped: 58
Pending: 0
Total: 279
```
This updates our beaker dependency to require at least 2.16, which is necessary for beaker's helpers to install dmgs, but has the potential to break non-OSX platforms.
The last CI run used beaker 2.15.1 and puppet#stable per-commit passed:
https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/view/Stable/view/Puppet/job/platform_aio-puppet_intn-sys_stable/146/SLAVE_LABEL=beaker,TEST_TARGET=redhat-7-x86_64/consoleFull

(PUP-4688) Update acceptance tests for OSX

---

lib/puppet/environments.rb
spec/integration/parser/compiler_spec.rb
spec/integration/parser/future_compiler_spec.rb
spec/unit/environments_spec.rb

This back ports the fix for PUP-4810 on stable (4.x) to 3.x.
When merging this up to stable there will be conflicts due to:
* logging functions cannot take a lambda in 3.x
* spec tests moved around
* future_compiler_spec is removed in 4.x
When merging to stable - favor the stable version over everything in this PR, and make sure the deleted spec tests stay deleted.

(PUP-4810) 3x do not cache 0ttl evict aggressively

---

lib/puppet/pops/issues.rb
lib/puppet/pops/patterns.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/pops/validator/validator_spec.rb

Before this, a badly formed parameter name would go unnoticed. This
causes a problem when not running with --strict_parameters beause
references to a non existing parameter does not cause a failure.
A user may have defined a parameter with 'define foo($Ateam) {}' and
tries to reference it with '$ateam' or '$Ateam' (the former would not
find the value, and the latter would fail with illegal parameter name).
This commit adds validation of the parameter name. It may start with a
lower case letter or underscore, and then any number of word characters.
A new issue code is added, and a new pattern since all existing patterns
(and error messages) are for fully qualified names.
This also correct typos on existing issues where \w did not output correctly.

(PUP-4752) Improve validation of parameter names

---

lib/puppet/pops/types/type_parser.rb
spec/unit/pops/types/type_parser_spec.rb

The Puppet evaluator will consider this statement to be true:
Integer[0] == Integer[0,default]
The TypeParser (used in Ruby function API) will instead use the single
argument in both positions and thus consider this to be true:
Integer[0] == Integer[0,0]
This commit changes the TypeParser to behave like the evaluator. The
change affects both Integer and Float.

(PUP-4826) Make Integer and Float with one argument unbounded

---

acceptance/tests/pluginsync/4847_pluginfacts_should_be_resolvable_from_applications.rb

Test config caused failures on Windows where the tmpdir name is
invalid. Fix by creating the tmpdir name with the agent.
[skip ci]

(PUP-4847) Fix using master to create tmpdir name

---

lib/puppet/util.rb
spec/unit/util_spec.rb

Before this, on POSIX systems, each time we execute a command, it forks a new process and this one will close inherited file descriptors by looping between 3 and 256 although there is more than 256 possible file descriptors. It's not safe and it's really slow.
Now, we try to list open file descriptors by reading "/proc/self/fd" and close the ones we don't want. This will fallback to the original method if it can't find "/proc/self/fd".

(PUP-4751) Optimize & Secure safe_posix_fork

---

ext/suse/client.init

On suse/sles 10, when executed by puppet, the init script will not start the puppet
service because startproc checks and finds a puppet process running.
This updates the init script to force start the process unless there is
a running process matching the pid in the pidfile. It also updates the status
command to only return true if the pidfile matches a running puppet pid.
This is a direct port of a fix for SLES 10 from previous PE releases.

(RE-5087) Fix init script behavior on sles/suse when run by puppet

---

lib/puppet/functions/epp.rb
lib/puppet/functions/inline_epp.rb
lib/puppet/parser/functions/epp.rb
lib/puppet/parser/functions/inline_epp.rb

Now that we have core docs pages about using and writing EPP templates, we can
shorten the function docs and reduce their scope.
Committing on behalf of Garrett Guillotte, who did the revisions.

(docs) Improve and shorten descriptions of epp and inline_epp functions

---

acceptance/tests/face/4654_facts_face.rb

This commit adds a new acceptance test to ensure that custom and
external facts are resolved correctly and present in the output
of the puppet facts face.

(PUP-4654) Add acceptance test for custom facts in puppet facts face

---

lib/puppet/parser/ast/collexpr.rb

When the feature enabling environment.conf to specify parser was added,
all checks for 'is future parser in effect' should be made via the
method `Puppet.future_parser?` instead of just checking
`Puppet[:parser]´ as the latter just checks what that setting is in
the MAIN section.
As a result, the collection expression would try to bring in 4.x code
that had not been required. This would happen if the runtime had never
executed a request where parser == 'future'. The 4.x code would not be
used, but it would instantiate a structure to support 4.x evaluation.
This fix is simply to use the correct way of checking if future parser
is in effect.

(PUP-4848) Change CollExpr to check for future parser the correct way

---

lib/puppet/application/lookup.rb

Add the skeleton for the `puppet lookup` application. Right now all
the arguments are accepted and parsed, but running `puppet lookup`
will only result in printing "Hello World" and the hash of options.

(PUP-4476) Add bare bones lookup application

---

acceptance/setup/git/pre-suite/000_EnvSetup.rb

- Previously, Git based acceptance was still configured to use FOSS
default paths for distmoduledir and sitemoduledir, which are
incorrect given AIO pathing changes.  This would cause a number of
acceptance test failures.  This commit effectively changes paths:
```
Windows
distmoduledir: "`cygpath -smF 35`/PuppetLabs/puppet/etc/modules"
sitemoduledir: C:/usr/share/puppet/modules
Other platforms
distmoduledir: '/etc/puppet/modules'
sitemoduledir: '/usr/share/puppet/modules'
```
To those specified in Beaker's AIO_DEFAULTS hash.
```
Windows
distmoduledir: '`cygpath -smF 35`/PuppetLabs/code/modules'
sitemoduledir:
Other platforms
distmoduledir: '/etc/puppetlabs/code/modules'
sitemoduledir: '/opt/puppetlabs/puppet/modules'
```
- Note that Windows sitemoduledir is now removed from the host …

(PUP-4050) Git acceptance requires AIO module dirs

---

lib/puppet/defaults.rb
lib/puppet/module_tool/applications/unpacker.rb

- For modules that install on Windows and use a long hierarchical
directory structure, the default TEMP path where PMT extracts the
modules tarball can be problematic. Windows has a default maximum
path length of 260 characters that must be carefully navigated.
By default, the extracted temp location looks like:
C:\ProgramData\PuppetLabs\puppet\cache\puppet-module\cache\tmp-unpackerYYYYMMDD-XXXX-xxxxxxx
The default install location of a puppet 4.0+ module is:
C:\ProgramData\PuppetLabs\code\environments\production\modules
This is based on the module_working_dir setting originally added in
eb617e5d9093834588732e78f42e865c814b982b
By initially extracting to such a long path, 30 valuable characters
are wasted (92 char current temp path vs 62 char install path).
On Windows, the TEMP directory …

(PUP-4854) Shorten PMT TEMP location on Windows

---

lib/puppet/defaults.rb
lib/puppet/module_tool/applications/unpacker.rb

- For modules that install on Windows and use a long hierarchical
directory structure, the default TEMP path where PMT extracts the
modules tarball can be problematic. Windows has a default maximum
path length of 260 characters that must be carefully navigated.
By default, the extracted temp location looks like:
C:\ProgramData\PuppetLabs\puppet\cache\puppet-module\cache\tmp-unpackerYYYYMMDD-XXXX-xxxxxxx
The default install location of a puppet 4.0+ module is:
C:\ProgramData\PuppetLabs\code\environments\production\modules
By initially extracting to such a long path, 30 valuable characters
are wasted (92 char current temp path vs 62 char install path).
On Windows, the TEMP directory can be used as a location to extract
to, and this is the default for Dir.mkdir.  Depending on the user,
this …

(PUP-4854) Shorten default PMT TEMP location on Windows

---

lib/puppet/application/filebucket.rb
lib/puppet/file_bucket/dipper.rb
lib/puppet/indirector/file_bucket_file/file.rb
spec/unit/application/filebucket_spec.rb
spec/unit/file_bucket/dipper_spec.rb
spec/unit/indirector/file_bucket_file/file_spec.rb

This patch adds a diff subcommand to the filebucket command.
It implements a way to diff filebucket files. Either between
them or between a filebucket file and the local one.

(PUP-4622) Add a diff command in Puppet filebucket

---

lib/puppet/util/windows/taskscheduler.rb
spec/unit/provider/scheduled_task/win32_taskscheduler_spec.rb

This might be a rare case, but fixing it could improve the code actually.
If a Windows Server 2003 system is upgraded from Windows Server 2000 or NT, the default `%SYSTEMROOT%` or `%WINDIR%` is `C:\WINNT` rather than `C:\Windows`. This will cause failure of `scheduled_task` resource, because [`taskscheduler.rb`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/windows/taskscheduler.rb#L812) hardcoded the path of scheduled tasks as `C:\Windows\Tasks` when testing if a job exists.
```
Error: /Stage[main]/test/Scheduled_task[foo]: Could not evaluate: No such file or directory @ dir_initialize - C:/Windows/Tasks
```
I don't think it's a good way :
- The windows directory doesn't have to be `C:\Windows`
- The system drive doesn't have to be `C:`
It's better to use …

(PUP-4814) Use ENV variables in the path of scheduled tasks folder.

---

lib/puppet/functions/versioncmp.rb
spec/unit/functions/versioncmp_spec.rb

The conversion is needed to work around improper string -> float conversion
that appears to be happening when calling 3x functions.

(PUP-4780) convert versioncmp() function to 4x API

---

.travis.yml
Rakefile

This PR adds a travis check for non-conforming commit messages.
The initial commit should demonstrate what a failure will look like. I'll amend the commit to conform if/when the failure is nicely reported.

Hi, I aim to be the last non-conforming commit summary in this project.

---

lib/puppet/indirector/catalog/static_compiler.rb

We've been using this fix in production to fix an issue we encountered with directory environments and the static_compiler catalog terminus. I didn't add tests because the store_content method appears to just be mocked and can't say I'm familiar enough with rspec or puppet code to test it properly.

(PUP-4771) static_compiler should get content from request environment

---

ext/osx/puppet.plist

This commit fully qualifies the label in the osx puppet plist using the
identifier plus service name.  Some formatting was also cleaned up.

(maint) fully qualify the label in the osx puppet plist

---

lib/puppet/defaults.rb

Ruby 2.2 complains with:
```
/usr/local/lib/ruby/site_ruby/2.2/puppet/defaults.rb:488: warning: duplicated key at line 489 ignored: :queue_type
```
The `:queue_type` is obviously duplicated so it's safe to remove one of them.

(MAINT) Fix duplicate key which ruby 2.2 complains about

---

ext/build_defaults.yaml

- We recently had to recall the Windows 3.7.5 builds due to an errant
commit 8c73637a1e2e001008b674c8c5b63736aa7ab0a7 which accidentally
switched the vendored Ruby from 1.9.3 on x86 and 2.0.0 on x64 to
2.1.x on both architectures.
Fortunately, this was later unknowingly corrected in
b9c6b9b5f471ab709858178d82c8af59d545714f when the vendored Ruby was
switched back to what it should have been.
Given SHAs are not human readable, attempt to limit the possibility
for another human error by using git tags as much as possible.
Note: This only affects the 3.x line of Puppet builds.  Since 4.x AIO
builds use the puppet-agent repo, these defaults are no longer set
in this repository.  That repository is already following the model
of using tags rather than SHAs for maintainability.

(maint) Use tags for Windows MSI dependencies

---

lib/puppet/provider/service/bsd.rb
lib/puppet/provider/service/rcng.rb
spec/unit/provider/service/rcng_spec.rb

Here's a new provider for service functionality through rcng, while it shares some traits with the `bsd` provider it differs enough to warrant a new one due to the different paths and content of files that need to be enabled.

(PUP-4602) Add rcng service provider

---

lib/puppet/pops/evaluator/relationship_operator.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

Before this, passing a resource reference as an attribute value resulted in that value not being useful as an operand in a resource expression.
This also corrects a faulty choice of issue leading to an error message with less information.

(PUP-4926) Make it possible to form relationship with 3x resource

---

acceptance/tests/resource/host/pup_2289_should_not_destroy_data_when_malformed.rb

This commit adds an acceptance test to validate that puppet does
not delete existing host file entries when the hosts file contains
malformed content.

(PUP-2289) Add test when hosts file is malformed

---

lib/puppet/data_providers/data_adapter.rb
lib/puppet/pops/binder/bindings_loader.rb
lib/puppet/pops/binder/config/binder_config.rb
lib/puppet/pops/binder/scheme_handler/module_scheme.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/meta/lib/puppet/functions/meta/data.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/meta/manifests/init.pp
spec/fixtures/unit/functions/lookup/environments/production/modules/meta/metadata.json
spec/fixtures/unit/functions/lookup/environments/production/modules/metawcp/lib/puppet/bindings/metawcp/default.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/metawcp/lib/puppet_x/thallgren/sample_module_data.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/metawcp/manifests/init.pp
spec/fixtures/unit/functions/lookup/environments/production/modules/metawcp/metadata.json
spec/unit/functions/lookup_spec.rb
spec/unit/pops/binder/config/binder_config_spec.rb

This PR adds a 'module:/*::metadata' pattern to the includes
for the binding layer 'modules'. The ModuleScheme will recognize
the matching entries and assume that contributed bindings are
specified in the module's metadata.json file using the key
'data_provider'.
Unit tests are provided to verify that a data_provider that appoints
a Puppet provided binding (such as 'function') works OK and that
a user provided binding (such as 'sample') also works.

(PUP-4490) Pick up bindings from module's metadata.json

---

ext/systemd/puppet.service
ext/systemd/puppetmaster.service

The "{}" prevent systemd from interpreting values correctly and causes
services to fail to start. {} indicates that the variable is a single
argument[1].
This is largely a cherry-pick of the fix for PUP-3228.
[1] - http://www.freedesktop.org/software/systemd/man/systemd.service.html

(PUP-4196) Remove "{}" from variables in systemd files

---

acceptance/tests/ticket_4622_filebucket_diff_test.rb

In the Jenkins environment, the master options being passed cause the
test to fail when attempting to kill the master. Use default options to
setup the master for the test.
The test would still setup a master, even if no agents were identified
to test (i.e. Windows). Skip the test if no agents are available after
the confine.
Also cleanup some magic and formatting.
[skip ci]

(PUP-4622) Fix acceptance test in Jenkins CI

---

Rakefile

Previously the check for the trailing paren was only made
for PUP-<digits> (but not for maint or doc or packaging). This fixes
that regex.

(maint) Fix commits checker regex

---

lib/puppet/defaults.rb
lib/puppet/pops/parser/lexer2.rb
spec/unit/pops/parser/lexer2_spec.rb

Adds the ability to feature-switch tokens related to app_management. A setting is added, and used to configure to lexer. The work in the PR is just an enabler for future features. See ticket for more information.

(PUP-4905) Add app managment feature switch

---

acceptance/tests/resource/package/common_package_name_in_different_providers.rb
acceptance/tests/resource/package/yum.rb
lib/puppet/provider/package/yum.rb
spec/unit/provider/package/yum_spec.rb

In older yum versions, attempting to install a package that doesn't
exist doesn't result in an error. Parse the yum output to identify
failure to install a package and throw an error.
The resulting error message is different on older vs newer ELs:
```
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install not_a_package' returned 1: Error: Nothing to do
Error: /Stage[main]/Main/Package[not_a_package]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install not_a_package' returned 1: Error: Nothing to do`
```
```
Error: Could not find package not_a_package
Error: /Stage[main]/Main/Package[not_a_package]/ensure: change from purged to present failed: Could not find package not_a_package
```

(PUP-4865) Ensure error on yum install failure

---

lib/puppet/ssl/certificate_authority/interface.rb
spec/unit/ssl/certificate_authority/interface_spec.rb

Enforce a non-zero return code for errors in the puppet cert print|fingerprint functions.

(PUP-3694) puppet cert fingerprint invalidhost returns zero instead of non-zero [#puppethack]

---

ext/solaris/smf/puppet
ext/solaris/smf/puppet.xml

There were previously no smf files for puppet that weren't geared toward
opencsw. This commit adds the smf files from the PE service, and updates
them for current pathing.

(PUP-4936) Add files needed for smf puppet service

---

Rakefile

Historically we've used (docs) more than (doc). Allow both (docs) and
(doc) in commit messages.

(maint) Allow (docs) tag in commit messages

---

acceptance/tests/resource/group/should_modify_gid.rb
acceptance/tests/resource/user/should_create.rb
acceptance/tests/resource/user/should_create_with_gid.rb
acceptance/tests/resource/user/should_modify_gid.rb

Previously, several user and group acceptance tests dependeded
on `getent` to create and query users and groups on the system.
This did not work in OSX, and caused several test failures.
We now have cross-platform beaker methods specifically meant for
user and group management which we can use to replace the bare
`getent` calls.

(PUP-4824) Fixup acceptance group / user tests for OSX

---

acceptance/lib/puppet/acceptance/temp_file_utils.rb

This is coming from a CI failure for `puppet-server`, which uses `puppet`
4.2.1, see SERVER-832 for details.
The stat function references an `agent` variable, which will coincidentally
be set correctly to the same value as `host` if the beaker config only has
one host with an agent role. But if there is more than one agent, the
'agent' variable will be a list of hosts, and the stat function will throw an
exception.
The bug was introduced in 8d2a872

(maint) Fix bug in stat function

---

acceptance/tests/modules/install/basic_install.rb
acceptance/tests/modules/install/with_version.rb
acceptance/tests/resource/group/should_modify_gid.rb
acceptance/tests/resource/user/should_create.rb
acceptance/tests/resource/user/should_create_with_gid.rb
acceptance/tests/resource/user/should_modify_gid.rb

The first of these commits re-enables PMT-related tests for OSX.
We now bundle the GeoTrust Global CA with our vendored openssl,
so we can re-enable tests which require a connection to the
forge on OSX. See PUP-4688 for additional context.
The second commit cherry-picks PUP-4824 from master, which further
fixes OSX acceptance by removing bare calls to `getent`.

(PUP-4822) Fixup acceptance in OSX

---

README.md

Currently, the 'JIRA tracker' link points to http://tickets.puppetlabs.com/
which redirects itself to https://tickets.puppetlabs.com/ with a 301 redirection.
I just changed this to point directly to the correct https page.

(doc) 'JIRA tracker' link fix in the README

---

acceptance/tests/resource/service/ticket_14297_handle_upstart.rb

This commit sets the handle upstart test to skip the 'vivid'
version of ubuntu since it uses systemd rather than upstart to
manage services.

(PUP-5010) Skip upstart test on vivid

---

.travis.yml

When .travis.yml was updated for the latest 2.2 z release,
the exclusions matrix wasn't updated, which meant the commits
and rubocop jobs were being run on multiple rubies (no point
in that, never the intent).
So this commit just fixes up the excludes to prune those out
as intended.

(maint) Remove redundant travis jobs

---

lib/puppet/indirector/catalog/static_compiler.rb

The static_compiler catalog terminus always sets ensure to 'file' on
file resources as long as the resource has a source parameter declared.
It does this even if the ensure parameter is explicitly declared.
This is inconsistent with the behavior of the normal compiler, where a
file's ensure parameter gets enforced regardless of the value of the
source parameter.
This commit skips file resources with ensure set to 'absent' in the static
compiler.

(PUP-4919) static compiler always sets ensure parameter to 'file' if a

---

lib/puppet/indirector/json.rb
lib/puppet/indirector/msgpack.rb

log_exception() wrong.
In Puppet::Indirector::JSON, Puppet.log_exception() is called without
the required exception as the first argument value, instead the message
is passed.
This breaks further along in format_exception() as it attempts to get
the exception message attribute but finds a string:

(PUP-5014) Base class for JSON indirection terminus calls

---

lib/puppet/provider/service/systemd.rb
spec/unit/provider/service/systemd_spec.rb

Prior to this commit, if a service was masked, and a user tried to start
the service, it would throw an error because it was masked. Even if the
user enabled the service (which calls unmask), an error would be thrown
because 'start' would be run before 'enable'. This commit ensures that
the start command has the ability to unmask a service before trying to
start it.

(PUP-4605) Unmask before attemping to start

---

acceptance/tests/resource/user/should_create_with_gid.rb
acceptance/tests/resource/user/should_modify_gid.rb

No idea why this didn't fail in our pipeline or locally, but this should fix the acceptance failures on the puppet-server board.

(PUP-4824) Fix typo on resource acceptance tests

---

acceptance/tests/concurrency/ticket_2659_concurrent_catalog_requests.rb

Previously, the concurrent catalog request test was failing in
SLES 10 due to an old version of cURL on the system. This commit
updates the test to use our vendored cURL when it is present, or
fall back to the system cURL if it is not.

(PUP-4952) Use vendored curl in concurrency acceptance test

---

lib/puppet/file_system/windows.rb
spec/unit/file_system_spec.rb

- When a symlink is created to point at a directory, then that target
directory is removed, Windows was previously generating
`Errno::EACCES: Permission denied @ unlink_internal` because the
underlying Ruby File.unlink was being called, which fails on Windows.
When the target no longer exists, Ruby's File.unlink only works
properly on symlinks pointed at files and not symlinks pointed at
directories
Given the lstat only specifies 'link' and does not describe the
target, there is no way of knowing whether the former target was a
file or directory.  Thefore, when the target stat does not exist,
first attempt to File.unlink, and if that fails call Dir.rmdir.
Ruby's Dir.rmdir only works on links that were targeted at
directories, and not links that were targeted at files.

(PUP-5018) Cannot unlink dangling Windows symlinks

---

lib/puppet/provider/exec.rb
lib/puppet/util/execution.rb
spec/unit/type/exec_spec.rb

This patch sends a TERM signal to POSIX subprocesses spawned by Exec resources
when the `timeout` paramenter triggers an exception. Any process that does not
respond to TERM before Puppet exits will be orphaned and left for init to clean
up --- this is the default behavior for all timeout events prior to this patch.

(PUP-3045) kill timed out execs

---

spec/unit/type/exec_spec.rb

This patch splits the spec test for exec timeouts into separate Windows and
POSIX cases.

(PUP-3045) Re-factor timeout spec test for windows

---

appveyor.yml
spec/integration/type/file_spec.rb
spec/integration/util/windows/security_spec.rb
spec/unit/util/windows/sid_spec.rb

We've been bitten by a couple 3.x PRs that failed on windows specs,
so run AppVeyor here as well. This is identical to the config on the
stable/master branches, except that it specifies a 2.0 ruby and has
a build identifier with a "3.x" prefix.

(maint) Add appveyor builds for 3.x as well

---

lib/puppet/reference/configuration.rb

The configuration reference was showing blank defaults for codedir, rundir, and
logdir, and it was showing root Unix paths only for confdir and vardir. Since
we're overriding these with simple strings when we generate the config reference
anyway, we can just make those strings more useful.

(docs) Show more useful defaults for special directories in configuration reference

---

acceptance/tests/parser_functions/lookup.rb

(PUP-5002) acceptance: add metadata.json data binding to lookup.rb test
The existing test creates manifests including the bindings directory in the module's lib/puppet/ directory.  The additional test code creates new manifests which remove the bindings directories and install a metadata.json file for each of the two modules.  The new manifest is applied and the asserts are checked
again to verify the same data is returned as was before when the data bindings were made in the module's lib/puppet/bindings.

(PUP-5002) acceptance: add metadata.json data binding to lookup.rb test

---

ext/redhat/server.init

Details here: https://tickets.puppetlabs.com/browse/PUP-5037

(PUP-5037) Fixed `service puppetmaster status` incorrectly returning "puppet dead but subsys locked" on RHEL and derivatives

---

acceptance/lib/puppet/acceptance/environment_utils.rb
acceptance/tests/environment/environment_scenario-bad.rb
acceptance/tests/environment/environment_scenario-non_existent.rb

This change ensures we run the apply, module, config tests on the master
even if the master does not have an agent role.  We removed the agent
role from the master in the puppet tests to decrease testing time at low
risk.
This change also fixes the environment_scenario-bad test which never
would have passed against current puppet nor server due to matching on
output that was fixed.
[skip ci]

(PUP-5041) "environment non existent" acceptance tests failing on puppetserver

---

install.rb

This PR includes 2 commits. The first removes ftools usage from install.rb, as ftools has not been available in ruby since 1.8.7. The second adds a new option to allow for skipping prerequisite library checks, which is useful in situations where the ruby/platform being built on won't be the ruby/platform at runtime.

(PUP-5051) install.rb improvements

---

Rakefile
ext/osx/puppet.plist

This reverts commit 13b54ace034f231e1744c9267bbb728b7d0edc5f, excepting
the white-space changes.
We realized that changing this name actually changes the service name, which impacts anyone trying to manage the service - such as PE. This seems high-impact for a patch release.
cc @heathseals @joshcooper

(PUP-5053) revert "(maint) fully qualify the label in the osx puppet plist"

---

lib/puppet/provider/service/launchd.rb
spec/unit/provider/service/launchd_spec.rb

This is the right branch, closing #4170 although this should go to master as well.
Always adds `-w` when starting a job, as the status is cached and you can end up getting `unload -w` and then just `load`.
Adding the `-w` is a noop when it isn't needed.

(PUP-4639) always add -w when starting launchd

---

lib/puppet/network/authconfig.rb
spec/unit/network/authconfig_spec.rb
spec/unit/network/authorization_spec.rb

This commit introduces an object seam in Puppet::Network::AuthConfig
that will allow Puppet Server to provide a no-op implementation and
effectively disable authorization so it can be handled externally.
---
The approach I took with this was to wholesale rename the existing `Puppet::Network::AuthConfig` class to `Puppet::Network::DefaultAuthProvider`.
Then, create a new AuthConfig class that simply forwards the `check_authorization` call to an instance of authprovider class, which it will instantiate during initialization. The class can be set, but defaults to `DefaultAuthProvider`.
Happy to change class/module names and structuring.

(PUP-5012) Introduce authorization delegate

---

lib/puppet/reports.rb
spec/unit/reports_spec.rb

Previously, if a report handler failed during initialization, it wasn't
cleaned up. So the second time a report was submitted, Puppet would try
to instantiate a new class, and then fail because it had already been
instantiated. This instructs the class loader to overwrite if needed.
(PUP-1189) add spec test
(PUP-1189) Corrected spec test for accuracy
Thanks for the help, @MikaelSmith

(PUP-1189) declare report handlers with overwrite

---

lib/puppet/indirector/catalog/static_compiler.rb

When a file resource is declared without an explicit mode, the mode
retrieved from the metadata by the static_compiler catalog terminus is
not stringified, resulting in file resources with integer file modes in
the resultant catalog and a depreciation warning such as:
Warning: Non-string values for the file mode property are deprecated. It
must be a string, either a symbolic mode like 'o+w,a+r' or an octal
representation like '0644' or '755'.
(at /usr/lib/ruby/vendor_ruby/puppet/type/file/mode.rb:69:in `block (2
levels) in <module:Puppet>')

(PUP-4781) filemode retrieved by static_compiler should be stringified

---

spec/unit/provider/service/launchd_spec.rb

Adds specs covering changes to launchd overrides that occured in Mac OS
X 10.10.
Extends specs coverage for changes in https://github.com/puppetlabs/puppet/pull/4167.

(PUP-5044) Add specs for Mac OS X 10.10

---

ext/debian/puppet.logrotate
ext/redhat/client.init
ext/redhat/logrotate
ext/redhat/puppet.spec.erb
ext/systemd/puppet.service

This patch updates logrotate script and aligns it what is defined in
defaults.rb, specifically:
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/defaults.rb#L1036-L1046
and
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/defaults.rb#L1258-L1274
Because of logrotate and puppet during restart were both "fighting" for correct
file permissions, this was causing issues with SELinux. Also fixed paths which
has been incorrect for Fedora/RHEL systems (`/var/log/puppetlabs` vs
`/var/log/puppet`). It contains both now which seems to work just fine.
I am not adding logrotate scriplet for master tho as I don't know if it
supports signals. When running master under webrick one should not expect fully
working log rotation tho. Open for discussion.
As part of this patch, I am also …

PUP-4918 - Updated logrotate and init scripts

---

ext/suse/client.init
ext/suse/server.init

In the puppet-agent RPM spec we call the 'condrestart' action from
the %postun on package upgrade. This is currently missing from the
sles/suse init scripts.
This adds 'condrestart' as a synonym for the try-restart action.

(packaging) Add condrestart to suse init scripts

---

acceptance/.gitignore

Acceptance runs create a `tmp` directory in `acceptance/tmp`. Add it to
gitignore so I no longer accidentally add it to my PRs.

(maint) Ignore acceptance/tmp directory

---

lib/puppet/parser/ast/pops_bridge.rb
lib/puppet/parser/compiler.rb
lib/puppet/resource/type.rb
lib/puppet/resource/type_collection.rb
spec/unit/capability_spec.rb

This commit adds a test that verifies that a resource type that
consumes/produces capabilities may have a qualified name.
This PR sits on top of https://github.com/puppetlabs/puppet/pull/4183. The PUP-5075 commit is the only one to consider here.

(PUP-5075) Check that types that produces caps can use qualified names

---

lib/puppet/parser/ast/pops_bridge.rb
lib/puppet/parser/compiler.rb
lib/puppet/resource/type.rb
lib/puppet/resource/type_collection.rb
spec/unit/capability_spec.rb

This commit ensures that the resolution of declared capability
mappings is deferred until all files for a particular environment
has been parsed.
The commit introduces a new Resource::Type named 'capability_mapping'
that acts as intermediate object created by the parser and added to a
hash in the known_resource_types TypeCollection which is later made
available to the compiler. The compiler uses these objects when it's
time to evaluate to perform the actual mapping between capabilities
and resources. Once the mapping is complete, the 'capability_mapping'
hash is no longer needed and is cleared out to conserve memory.

(PUP-5074) Support consume/produces annotations site-wide

---

lib/puppet/configurer.rb

When the puppet agent is instructed to change environments by
classification, it issues a warning. That change is expected, so a
warning is not.
Change the warning to a notice. Later environment changes caused by
reclassification based on new facts are still warnings, as changing
environments multiple times isn't generally desirable.

(PUP-3318) Change environment change warning to notice

---

lib/puppet/indirector/catalog/static_compiler.rb

In the static compiler we are setting the mode, owner and group
attributes on the parent too early. This is causing child
resources to inherit the same values.
Child resources should only inherit attribute values if they are
explicitly set on the parent resource. In other cases overriding
the child group, mode and owner attributes should depend on the
value of source_permissions.
This commit attempts to fix this by postponing the call to set the
parent's attributes until after all children have inherited.
It also prevents mode, owner and group from being set if
source_permissions is not set to 'use'.

(PUP-5055) parent attributes are set from metadata too early in static_compiler

---

lib/puppet/parser/compiler.rb
lib/puppet/parser/resource.rb

When surfacing Puppet metrics in Puppet Server, w/o this change, a huge percentage of the metrics related to resource evaluation are never registered / tracked, because there are multiple code paths that can lead to resource evaluation during compilation, and only one of them has a profiling block around it.
e.g. whether or not a resource gets metrics tracked may depend on whether it was introduced via NC vs site.pp, etc.
In local tests where I've been experimenting with improvements for surfacing metrics data from Puppet Server, this change is a huge improvement and gives us much more interesting and complete data to look at.

(PUP-5013) move profiling block for resource eval

---

lib/puppet/context/trusted_information.rb
spec/unit/context/trusted_information_spec.rb

Before this there is no way to get the hostname/domain fact from a trustworthy source.
With this `hostname` and `domainname` are now part of the trusted facts. Both of them are derived
from the validated certificate name.
It can be used in Hiera as follows :
```yaml
:hierarchy:
- "%{::trusted.domainname}/%{::trusted.hostname}"
- "%{::trusted.domainname}"
- common
```

(PUP-5097) Adding hostname and domainname in trusted facts

---

acceptance/tests/resource/service/launchd_provider.rb

Launchd had a few bugs in managing services on newer platforms that were
not exposed by testing. Add acceptance tests to ensure managing services
with the launchd provider are tested.

(PUP-5056) launchd service provider tests

---

acceptance/tests/ssl/certificate_extensions.rb

The certificate_extensions test verifies trusted facts. Since PUP-5097
modifies trusted facts, the test is updated to include the new facts.

(PUP-5097) Fix certificate acceptance test

---

acceptance/tests/resource/service/service_enable_linux.rb

This change fixes many platforms this test was not setup to handle. It
skips ubuntu15 and debian8 for now as it seems to uncover legit
failures.

(maint) fix service_enable_acceptance test on deb8 ubuntu15 sles12

---

lib/puppet/pops/model/model_label_provider.rb
lib/puppet/pops/model/model_meta.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/capability_spec.rb

This commit relaxes that constraint that a CapabilityMapping
only can contain an AttributeOperation so that it instead can
contain an AbstractAttributeOperation. This was done to prevent
a cryptic error message when an AttributesOperation (note the
plural) was assigned due to use of *=> operator. The relaxed
constraint lets this pass so that it instead can be trapped
in the validator where a correct check was already in place.

(PUP-5088) Ensure only => can be used in capability mappings

---

lib/puppet/application/lookup.rb
spec/unit/application/lookup_spec.rb

This pull request adds basically functionality to the `puppet lookup` command.
Right now the command basically serves as a conduit to the Puppet::Pops::Lookup.lookup
function and allows you to pass in parameters to that function. It does not yet support
the --explain or the --facts options.

(PUP-4476) Add basic `puppet lookup` command

---

lib/puppet/provider/service/redhat.rb
lib/puppet/provider/service/systemd.rb
spec/unit/provider/service/redhat_spec.rb
spec/unit/provider/service/systemd_spec.rb

Previously, the default service provider for suse was 'redhat' with
an override of 'systemd' for suse 12 and 13. However this doesn't work for the rolling
release of suse (tumbleweed) or the next (leap), which are both systemd
based.
This reverses the logic so the default service provider is 'systemd'
with overrides for suse 10 and suse 11.
I also updated some unrelated spec tests in provider/service/systemd_spec.rb
to use 'stubs' rather than 'expects' - the latter made the tests unnecessarily
brittle and was testing implementation rather than behavior.

(PUP-4697) Make systemd the default service provider for all suse's *except* 10 and 11

---

acceptance/config/nodes/solaris-10-sparc.yaml
acceptance/config/nodes/solaris-11-sparc.yaml
acceptance/config/nodes/solaris-11-x86_64.yaml

This commit adds node definitions for solaris sparc 10 and 11
agents using the SPARC architecture.

(PUP-5133) Add Solaris 10/11 SPARC node defs

---

lib/puppet/pops/parser/lexer2.rb
spec/unit/pops/parser/lexer2_spec.rb
spec/unit/pops/parser/parse_application_spec.rb
spec/unit/pops/parser/parse_capabilities_spec.rb
spec/unit/pops/parser/parser_rspec_helper.rb
spec/unit/pops/validator/validator_spec.rb

The app_management feature flag governs which of two variants of lexer
tables we use for appmgmt specific language constructs. Previously, the
decision was made when code was loaded, which is too early for how
puppet-server loads the Ruby code.
We now defer the decision until we actually get ready to lex text, and make
the decision in the initvars method, rather than in the setup of constants
during loading of the Ruby code.
As an (untested) side-effect, it should now be possible to turn
app_management on or off per environment rather than just globally.
This change also required changing before(:all) to before(:each) as
Puppet[:app_management] is reset before each test automatically. On the
upside, we can now also get rid of the horrible hacks in
ParserRspecHelper::with_app_management

(PUP-5197) Defer appmgmt-specific setup of lexer tables

---

lib/puppet/parser/resource.rb
lib/puppet/resource/type.rb
spec/unit/capability_spec.rb

This commit adds validation of values assigned to the export/consume
metaparameters. The validation ensures that the value is a capability
resource. It also asserts that the value is a resource before attempts
are made to use methods such as resource.type. This to avoid cryptical
"undefined method" errors in case user enters non resource RHS values.

(PUP-5078) Validate export/consume metaparameters

---

acceptance/tests/resource/service/service_enable_linux.rb

This change fixes a service enablement test for various platforms which
use sysV in our testing setups and sles which uses different runlevels
by default.
[skip ci]

(maint) fix service enable test sles,ubuntu15

---

acceptance/tests/allow_symlinks_as_config_directories.rb
acceptance/tests/concurrency/ticket_2659_concurrent_catalog_requests.rb
acceptance/tests/config/apply_file_metadata_specified_in_config.rb
acceptance/tests/resource/file/symbolic_modes.rb
acceptance/tests/resource/mount/defined.rb
acceptance/tests/resource/mount/destroy.rb
acceptance/tests/resource/mount/modify.rb
acceptance/tests/resource/mount/mounted.rb
acceptance/tests/resource/mount/query.rb
acceptance/tests/ticket_2455_on_solaris_init_provider_should_start_service_in_own_smf_contract.rb
acceptance/tests/ticket_9862_puppet_runs_without_service_user_or_group_present.rb

Fixes or disables tests to get CI running. Disabled tests that we want to re-enable are ticketed in [PUP-5200](https://tickets.puppetlabs.com/browse/PUP-5200) and [PUP-5201](https://tickets.puppetlabs.com/browse/PUP-5201).
[skip ci]

(PUP-5191) Fix acceptance tests for Solaris

---

lib/puppet/network/http/api/master/v3/environment.rb
lib/puppet/parser/compiler.rb
spec/unit/appmgmt_spec.rb

This commit adds validation of the 'nodes' parameter in application
instances such that it must be a Hash where each key is a Node and
each value is a resource or an array of resources.
The code also checks that no resource is mapped to more than one
node.
A change was made to remove the prior more relaxed scheme where the
node could be on either side of the association in the hash. Now
it must be the key. This is natural since the node must be unique
and since the resources that it is associated with can be an array.

(PUP-5079) Check that 'nodes' parameter for applications is sound

---

acceptance/lib/puppet/acceptance/service_utils.rb

On Windows, ruby.exe doesn't know where to `require 'puppet'`, as Puppet
is not put in Ruby's vendor or site dir in the MSI. Requiring puppet
fails in the systemd acceptance test.
Explicitly state Windows does not support systemd.

(PUP-5024) Fix test on Windows

---

ext/build_defaults.yaml

This commit updates the ruby build we are including in the puppet-agent
package. This new build is against an updated build of OpenSSL 1.0.0s

(PUP-5215) Update Ruby to include an updated openssl

---

lib/puppet/application/lookup.rb
spec/unit/application/lookup_spec.rb

Prior to this commit, the lookup application was calling the internal
lookup function in a way that was compatible with the old version
of the function (eight parameters) rather than the current version
of the function (six parameters). This meant that attempts to use
the lookup application would fail due to the function being called
improperly.
Fix this issue and also remove a test that had too much stubbing
and was not longer useful.

(PUP-4476) Call lookup with the correct parameters

---

lib/puppet/reference/report.rb

Reporting has been enabled by default since 2.7.0.

(docs) Remove outdated info from reports reference

---

acceptance/tests/face/loadable_from_modules.rb
acceptance/tests/resource/package/common_package_name_in_different_providers.rb
acceptance/tests/resource/package/yum.rb
acceptance/tests/resource/ssh_authorized_key/destroy.rb

Several tests fail on EL/Centos 4 and have been filed as separate tasks.
This commit skips those tests until we resolve those issues. See
PUP-5225, PUP-5226, PUP-5227, and PUP-5228.

(maint) Skip failing tests on EL/Centos 4

---

lib/puppet/data_providers/hiera_interpolate.rb
spec/fixtures/unit/data_providers/environments/hiera_misc/data/common.yaml
spec/unit/data_providers/hiera_data_provider_spec.rb

This commit fixes a typo in the hiera data provider and adds a test
to verify that interpolation expressions using qualified names such
as `%{os.name}` works as expected.
A test was also added to ensure that the hiera data provider does
not suffer from the problem described in HI-469.

(PUP-5328) Fix crash when using qualified lookups in interpolation

---

lib/puppet/functions/hiera.rb
lib/puppet/functions/hiera_array.rb
lib/puppet/functions/hiera_hash.rb
lib/puppet/functions/hiera_include.rb
lib/puppet/parser/functions/hiera.rb
lib/puppet/parser/functions/hiera_array.rb
lib/puppet/parser/functions/hiera_hash.rb
lib/puppet/parser/functions/hiera_include.rb

Revising ~~lookup~~, `hiera`, `hiera_array`, `hiera_hash`, and `hiera_include`.
Squashed; per @nfagerlund, there's more discussion needed about 
terms we use in `lookup`.

(docs) Hiera function revisions

---

lib/puppet/application/lookup.rb
lib/puppet/data_binding.rb
lib/puppet/data_providers.rb
lib/puppet/data_providers/hiera_config.rb
lib/puppet/data_providers/hiera_interpolate.rb
lib/puppet/data_providers/hiera_support.rb
lib/puppet/functions/lookup.rb
lib/puppet/plugins/data_providers/data_provider.rb
lib/puppet/pops.rb
lib/puppet/pops/lookup.rb
lib/puppet/pops/lookup/explainer.rb
lib/puppet/pops/lookup/invocation.rb
lib/puppet/pops/merge_strategy.rb
lib/puppet/resource.rb
spec/fixtures/unit/application/environments/production/data/common.yaml
spec/fixtures/unit/application/environments/production/environment.conf
spec/unit/application/lookup_spec.rb
spec/unit/data_providers/hiera_data_provider_spec.rb
spec/unit/functions/lookup_spec.rb

This commit adds report callbacks to the Lookup::Invocation object
which is passed down to all instances involved in the lookup. These
callbacks will either do nothing at all (no Explainer attached to
the Invocation) or tell the explainer to accept data for that
particular report.
A new 'with' method was also added. It is used when a lookup changes
its context. This happens when the lookup is branching due to things
like several paths, global/environment/module scopes, or when
evaluating interpolations in a string. The with method is used as
a wrapper (yields to a block where the lookup continues) and will
push and pop contextual objects in the Explainer and thereby build
a full DAG of all branches that the lookup invocation took part in.
The LookupInvocation that resided in …

(PUP-4475) Add explain-ability to the lookup and data provider APIs

---

acceptance/tests/parser_functions/hiera_in_templates.rb

Until now we had no acceptance tests for verifying behavior of hiera
function calls (hiera(), hiera_array(), hiera_hash(), and hiera_include()) f
within a template (erb or epp).
This test calls hiera functions from with in an erb template and from within
an epp template.  The master is configured with a manifest.  The client
applies the manifest using the puppet agent -t call.  The file created by
templates are examined to determine whether the hiera function calls returne
the expected values.
hiera_include() is called from the epp template.  The included sub-modules
each create a file that is then checked for correctness.

(PUP-4695) New acceptance test for hiera function calls in templates

---

acceptance/tests/resource/file/should_create_symlink.rb
acceptance/tests/resource/file/ticket_7680-follow-symlinks.rb

Previously, we were using beaker's confine_block method to skip symlink
tests on 2003. Prior to beaker 2.24, the test would be skipped on all
platforms due to BKR-505. Beaker 2.24 fixed the issue, which causes the
test to execute correctly on non-2003 platforms, but fails on 2003. That
issue is filed as BKR-535.
This commit changes the acceptance tests to not use `confine_block` to
avoid any beaker incompatibilities.

(maint) Don't use confine_block to skip tests

---

ext/suse/client.init

Prior to this commit, the Puppet service fails to start
on SLES11 with the error "Could not prepare for execution:
The puppet agent command does not take parameters".
This appears to be caused by an empty '' at the end of
Puppet's SUSE init script startproc call.
Here we update the SUSE init script to remove the
double quotes from "${PUPPET_EXTRA_OPTS}".

(PUP-5258) Unquote PUPPET_EXTRA_OPTS in SUSE init script

---

lib/puppet/pops/parser/parser_support.rb
spec/unit/pops/parser/parser_spec.rb

This commit fixes the error method in the ParserSupport class so that
it correctly reports the position of TokenValue instances such as
COMMA when such tokens are misplaced.

(PUP-5026) Ensure that parser tokens are reported with position

---

acceptance/lib/puppet/acceptance/service_utils.rb
acceptance/tests/resource/service/AIX_service_provider.rb
acceptance/tests/resource/service/puppet_mcollective_service_management.rb

This commit adds a new acceptance test to ensure that the Puppet
and Mcollective services can be started, stopped and refreshed
in a number of scenarios.

(PUP-5057) Add test for managing puppet and mcollective services

---

api/docs/http_catalog.md
api/schemas/catalog.json
lib/puppet/indirector/catalog/compiler.rb
lib/puppet/resource/catalog.rb
spec/unit/indirector/catalog/compiler_spec.rb
spec/unit/resource/catalog_spec.rb

Adds a code_id accessor to the catalog, updates the api docs, schema, and tests.
Updates the compiler terminus' find method to add the code_id from the request to the catalog it returns.

(PUP-4890) Add code_id to the catalog

---

ext/redhat/client.init

Prior to this commit, managing the AIO
puppet-agent's puppet service using
`puppet resource` fails on EL4.
Because EL4's /etc/init.d/functions do not
take pid as an argument, we're not able to
use the built-in 'status' or 'killproc'
functions, as these will check the status of
and/or kill the `puppet resource` process
itself.
This commit updates the EL init script to
allow use of `puppet resource` to manage the
puppet service on EL4, while continuing to
use the built-in 'status' and 'killproc'
functions on EL5 and EL6.

(PUP-5257) Update client init script for EL4

---

lib/puppet/parser/resource.rb
lib/puppet/pops.rb
lib/puppet/pops/types/type_asserter.rb
lib/puppet/pops/types/type_calculator.rb
lib/puppet/pops/types/type_factory.rb
lib/puppet/resource.rb
lib/puppet/resource/type.rb
spec/integration/parser/compiler_spec.rb
spec/integration/parser/undef_param_spec.rb
spec/unit/appmgmt_spec.rb
spec/unit/parser/compiler_spec.rb
spec/unit/parser/functions/create_resources_spec.rb
spec/unit/parser/resource_spec.rb

This commit unifies how parameters are validated so that instantiations
of nodes, classes, and definitions use a validatio logic that has more
in common with the validation of lambda invocations and function calls.

(PUP-4458) Refactor validation of parameter signatures

---

lib/puppet/application/lookup.rb
spec/unit/application/lookup_spec.rb

Prior to this commit, logging was not being registered for the
lookup application which meant that errors would not appear on
standard out. Add a setup method which will register logging so
errors appear accordingly.

(maint) Set up logging for lookup application

---

ext/build_defaults.yaml

Fedora 20 is now EOL, so we should no longer be building packages for
it.

(maint) Remove F20 from build targets

---

acceptance/Rakefile
acceptance/config/gem/options.rb
acceptance/config/nodes/gem.yaml
acceptance/setup/gem/pre-suite/010_GemInstall.rb

Creates a rake task `ci:test:gem` and an acceptance test for installing
puppet as a gem and smoke testing the install against a predefined set
of hosts windows (ruby x86 and x64), osx and redhat. The osx case is
needed because we have a darwin-specific facter gem that has a
dependency on CFPropertyList.
The `ci:test:gem` task relies on the existing git setup step that
installs `git` and `ruby` on each host, even though we really only need
`ruby`.
Also on Windows, we're using the our vendored ruby, which already
includes some gems, e.g. win32-service, ffi. So the test setup step
wipes the current set of installed gems. Alternatively, it would be nice
to only install our vendored ruby, but we do not current publish that as
a build artifact.

(PUP-3742) Smoke test gems

---

lib/puppet/provider/sshkey/parsed.rb
spec/unit/provider/sshkey/parsed_spec.rb

Beginning with El Capitan (OSX 10.11), the new location for SSH
configuration files is `/etc/ssh`, rather than at the top level
in `/etc`. This commit updates the sshkey provider to store
our generated `ssh_known_hosts` file in the new location for
OSX 10.11 and above.

(PUP-5058) Update ssh_known_hosts file path for OSX 10.11

---

lib/puppet/defaults.rb
lib/puppet/feature/cfacter.rb

This commit deprecates the --cfacter setting, as it is no longer
needed with native Facter being shipped in AIO by default.

(PUP-4932) Deprecate --cfacter option

---

acceptance/tests/resource/ssh_authorized_key/destroy.rb
acceptance/tests/resource/ssh_authorized_key/modify.rb
acceptance/tests/resource/ssh_authorized_key/query.rb

Previously, the ssh_authorized_key tests would append a new
key to authorized_keys with `echo.` On CentOS 4. simply appending
did not create a newline, and so the key was appended to the end
of the last key, meaning Puppet couldn't find or remove it.
This commit updates the test to add a newline to the file before
appending the new key.
In addition, there was an issue with the modifcation test in which the
key was appended improperly, and we then mistook Puppet's newly generated
key for a modified version of the old key, when in reality
'ensure=present' was just adding a brand new key.

(PUP-5228) Fixup ssh_authorized_key tests

---

acceptance/tests/parser_functions/hiera_in_templates.rb

Until now we had no acceptance tests for verifying hiera function calls
(hiera(), hiera_array(), hiera_hash(), and hiera_include()) from within
a template (erb or epp).
This test calls hiera functions from with in an erb template and from within
an epp template.  The master is configured with a manifest.  The client
applies the manifest using the puppet agent -t call.  The file created by
templates are examined to determine whether the hiera function calls returned
the expected values.
hiera_include() is called from the epp template.  The included sub-modules
each create a file that is then checked for correctness.
9/24/15

(PUP-4695) New hiera_in_templates acceptance test

---

lib/puppet/indirector/catalog/compiler.rb
lib/puppet/parser/compiler.rb
lib/puppet/resource/catalog.rb
spec/integration/resource/catalog_spec.rb
spec/unit/indirector/catalog/compiler_spec.rb
spec/unit/parser/compiler_spec.rb
spec/unit/resource/catalog_spec.rb

Commit e14f2bc modified the catalog's compiler terminus to copy the
code_id from the request to the catalog that it returned. However, this
isn't sufficient as the code_id needs to be set on the catalog and
available during compilation.
This commit modifies the catalog's compiler terminus to pass the code_id
from the request to the compiler (Puppet::Parser::Compiler), which sets
it on the catalog it creates and returns.
Note the compiler terminus calls `catalog.filter` to remove exported
resources, making a copy of the catalog in the process, and is why the
catalog's `convert` method needs to copy the code_id.

(PUP-4890) Thread code_id into compiler

---

lib/puppet/transaction.rb
lib/puppet/util/tagging.rb
spec/unit/transaction_spec.rb

Prior to this commit a change made to the way tags are split when
filtering was causing the agent to create more resources than
nessecary.
Update the way a tag is recoreded when filtering to fix this issue.

(PUP-4495) Fix tag filtering regression

---

lib/puppet/application/lookup.rb

Prior to this commit running `puppet lookup --help` would do nothing.
Now a help messages is displayed.

(PUP-5202) Add help for puppet lookup CLI command

---

lib/puppet/pops/types/type_calculator.rb
lib/puppet/pops/types/types.rb
spec/unit/pops/types/type_calculator_spec.rb

This commit changes code in the `TypeCalculator` and the `PRuntimeType`
so that they test for ruby Module instead of ruby Class. It also
changes so that an inferred Module (or Class) becomes the PType for
the PRubyType that corresponds to the Module/Class instead of just the
default PType.

(PUP-4960) Fix so that ruby modules are considered PRuntimeType

---

lib/puppet/provider/package/gem.rb
spec/unit/provider/package/gem_spec.rb

Attempting to install a gem from a local source on windows fails because of the way
that the provider code detects using URI.  This patch preserves the current behaviour
but allows the a puppet util method to detect a fully qualified path to pass to the gem
command, which allows install

(PUP-5282) Use absolute_path to detect local installation of gem on windows

---

lib/puppet/resource/type.rb
spec/unit/capability_spec.rb

This commit adds the validation necessary to raise an error when more
than one consumed capability mapping tries to map the same parameter.

(PUP-5080) Check parameters consumed from capabilities are unique

---

lib/puppet/parser/environment_compiler.rb
spec/unit/appmgmt_spec.rb

Before this there was a problem if an environment compiler compiled a
manifest that did not have a site expression. The final pruning step
would then end up with a nil reference instead of an array of elements
to keep from the site expression.

(PUP-5293) Fix ref to nil in environment_compiler

---

lib/puppet/pops/parser/code_merger.rb
spec/unit/resource/type_spec.rb

Before this, if a site used thousands of manifests the code merger would
create a tree that was thousands of levels deep. When evaluating that,
the ruby stack will (most likely) hit its limit.
After this change the structure is flattened - rather than recursing
the merged instructions are simply concatenated (after unwrapping them
as much as possible).
As a consequnce, one test was changed since it depended on the internal
structure being build having a particular shape.

(PUP-5299) Flatten the code structure produced by the 4x code merger

---

lib/puppet/parser/resource.rb

This improves the readability of the error message issued when more than
one capability resource attribute is mapped to the same attribute in a
consuming resource.

(PUP-5080) Improve error message on mapping conflict to same attr

---

lib/puppet/resource/capability_finder.rb
spec/unit/resource/capability_finder_spec.rb

This commit ensures that the CapabilityFinder uses the connections
that have been configured for PuppetDB.

(PUP-5084) Make CapabilityFinder use configured PuppetDB

---

acceptance/tests/resource/package/common_package_name_in_different_providers.rb
acceptance/tests/resource/package/yum.rb
acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb

Previously, these tests failed when using a rhel master and windows
agent, because apply_manifest_on will return nil when the agents array
is empty, see BKR-571.
This failure started occurring, because BKR-533 used to overwrite the
array of all hosts, making the test unsuitable for all hosts even if
there was only a single windows agent. That issue was fixed in beaker
2.25.0, and unmasked BKR-571.
However, the tests are not following best practice, which is to just
pass the block to the apply_manifest_on method, and that will yield each
result to the block.

(maint) Don't rely on apply_manifest_on return value

---

acceptance/tests/resource/service/service_enable_linux.rb
acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
lib/puppet/provider/service/debian.rb
lib/puppet/provider/service/init.rb
lib/puppet/provider/service/systemd.rb
spec/unit/provider/service/debian_spec.rb
spec/unit/provider/service/systemd_spec.rb

This series of commits makes some changes to the systemd, debian and init providers to work around the strange behavior of the sysvinit-systemd compatibility layer in Debian. In order:
Previously, Debian 8 and Ubuntu 15.05, which are systemd-managed
platforms, would erroneously fall back to the init provider
when Systemd was unable to manage a SysVInit service without
a unit file. The Debian provider should be used instead, as
it inherits from init and provides the ability to enable and
disable services.
Previously, we checked for lowercased 'debian' when trying
to determine if a platform is Debian-ish in the systemd provider.
Facter returns capitalized 'Debian', so this commit downcases
Facter's return value to ensure we properly detect the Debians.
Previously, services_enable_linux.rb …

(PUP-5016) Fixup systemd / sysvinit issues in Debian and Ubuntu

---

acceptance/tests/config/puppet_manages_own_configuration_in_robust_manner.rb
lib/puppet/application/master.rb
spec/unit/application/master_spec.rb

Commit 144ea123 changed Puppet's behavior when a master is run
with no Puppet user existing. This commit maintains the more
graceful behavior of failing in main rather than down the line,
but restores the behavior of exiting with `74`.
The test `puppet_manages_own_configuration_in_robust_manner` is
also updated to account for the fact that we no longer attempt
to change groups if the user is missing.

(PUP-5317) Exit with 74 when trying to run a master with no puppet user

---

acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/tests/ssl/ticket_5274_private_key_modes.rb
lib/puppet/settings/file_setting.rb
spec/unit/settings/file_setting_spec.rb

Previously, puppet would create settings related files using the process
umask, instead of the mode specified in defaults.rb, or overridden in
puppet.conf, and it would take a second puppet run to converge.
This issue was introduced in 691056e for PUP-2349, merged in 87b0b5d,
and has been present since 3.7.0. There are two issues with the code:
First, the case statement was trying to compare if mode was a string,
nil, or fixnum using ruby's case equality operator, but it was
actually comparing if mode's class was a string or nil, which was
never true, always falling through to the else case.
Second, the assignment statement `mode = case mode` introduced a `mode`
local variable whose value was set to nil, and shadowed the `mode`
accessor. This combined with above issue meant the method …

(PUP-5274) Create settings related files with the correct mode

---

lib/puppet/indirector/indirection.rb
spec/unit/indirector/indirection_spec.rb

Failing to cache requests could lead to silent exits. For example if the
apply application failed to cache to PuppetDB catalog terminus. This
will log the exception and continue.

(PUP-5290) Log exceptions raised by saving to cache

---

CONTRIBUTING.md

guidelines had one too many ls in it.

(maint) Fix typo in CONTRIBUTING.md

---

lib/puppet/functions/regsubst.rb
spec/unit/functions/regsubst_spec.rb

This reverts commit 4d2ad0f167d39624da282ac0b8260256746fe488.
Henrik discovered that this allows [undef, undef, undef,...] to be passed
to regsubst, which is not ideal. We'll instead wait for the underlying type system
bug to be fixed instead.

Revert "(PUP-5292) Allow empty arrays as first parameter to regsubst"

---

lib/puppet/provider/package/rpm.rb
spec/unit/provider/package/rpm_spec.rb

Prior to this commit, the RPM provider did not include non-zero
epoch values in the :ensure field when calling RPM to install or
query packages.
This commit ensures that non-zero epochs are included.

(PUP-5025) RPM Epoch should be included in ensure field

---

acceptance/lib/puppet/acceptance/rpm_util.rb
acceptance/tests/resource/package/common_package_name_in_different_providers.rb
acceptance/tests/resource/package/yum.rb
lib/puppet/provider/package/dnf.rb
lib/puppet/provider/package/yum.rb
spec/unit/provider/package/dnf_spec.rb
spec/unit/provider/package/yum_spec.rb

This series of commits adds a new DNF provider to Puppet, which is necessary due to Fedora's move from Yum to DNF.
A few updates to the Yum provider were required to make way for the new provider, which is its child.

(PUP-4055) Add DNF package provider

---

lib/puppet/network/authorization.rb
spec/unit/network/authorization_spec.rb

This commit provides an accessor for controlling the AuthConfigLoader
class which is used to load an authorization config.  This would be used
by Puppet Server to disable the default AuthConfigLoader when it is
configured to use its own trapperkeeper-based authorization instead.

(PUP-5351) AuthConfigLoader hook for Puppet Server

---

lib/puppet/type/file/source.rb

These docs seemed to imply that you could download remote files with file: URIs,
when they're really just another way to write local file paths.
When this is merged, please resolve https://tickets.puppetlabs.com/browse/DOCUMENT-413.

(docs) Fix ambiguous reference to file: URIs in source attribute

---

ext/suse/client.init

The force-reload and reload init script actions had the exact same bash
code, so this commit moves them into the same block in the case
statement and consolidates the comments.

(maint) Refactor reloading in suse init script

---

lib/puppet/application/apply.rb
spec/unit/application/apply_spec.rb

Previously, the 'puppet agent' command accepted catalog_cache_terminus,
but 'puppet apply' did not. This makes 'apply' match 'agent'.

(PUP-5340) Accept catalog_cache_terminus for apply

---

lib/puppet/functions/filter.rb
spec/unit/functions/filter_spec.rb

This commit ensures that the filter function behaves consistently
with respect to how the block return value affects the filter.
Prior to this commit, filters on Hash would check if the block
returned truthy and filters on Array would check if it returned
`true`. Now both uses the latter.

(PUP-5350) Ensure consistent behavior of filter function

---

lib/puppet/resource.rb
spec/unit/resource_spec.rb

Previously, if you had a single quote in a resources' title,
running puppet resource would generate an invalid manifest.
Now, we escape any single quotes correctly.

(PUP-3953) single quotes in titles are escaped correctly

---

lib/puppet/resource/catalog.rb
lib/puppet/transaction.rb
lib/puppet/transaction/additional_resource_generator.rb
lib/puppet/transaction/resource_harness.rb
spec/lib/matchers/include_in_order.rb
spec/unit/transaction/additional_resource_generator_spec.rb

Previously, generated resources could not have edge metaparams or
participate in autorequire, since they were created AFTER those
transformations had occured on the catalog. This changes resource
generation to occur before those transformations.
Because of this, the containment edges for generated resources now end
up in the final relationship graph. This caused issues with purged
resources, since the purge check now sees that a whit depends on the
purged resource. This was resolved by excluding whits from the purge
safety check. Since whits can only be generated by containment edges,
and generated resources previously could not have containment edges,
this is not a breaking change.
In order to maintain manifest ordering, it is necessary to add the
generated resources into the catalog …

(PUP-1963) allow dependencies on/for generated resources

---

acceptance/tests/aix/aix_package_provider.rb

Puppet sends error notices to stderr instead of stdout. Update
the aix package provider test to reflect this.

(PUP-5311) Check stderr for errors in AIX package test

---

acceptance/tests/resource/user/should_manage_shell.rb

Previously, the should_manage_shell test tried to switch the
user's shell to /bin/bash, which actually won't work on AIX
because it is not specifically allowed in /etc/security/login.cfg
and thus is not considered valid.
Modify the test to use ksh for AIX instead, which is an allowed
shell.

(PUP-5314) Switch to allowed shell on AIX in shell test

---

acceptance/tests/concurrency/ticket_2659_concurrent_catalog_requests.rb

This commit skips AIX agents when conducting the
`concurrency/ticket_2659_concurrent_catalog_requests` acceptance
test.

(PUP-5312) Skip concurrent requests test on AIX

---

acceptance/tests/resource/user/should_create_with_gid.rb

This commit updates the `resource/user/should_create_with_gid`
acceptance test to accommodate finding the gid for the user under
test on AIX.

(PUP-5313) Fix user gid test for AIX

---

lib/puppet/provider/group/directoryservice.rb
spec/unit/provider/group/directoryservice_spec.rb

OSX group membership is currently returned as simple Arrays. Comparing these
is strict, and the order of the resource must exactly match the order given
in the manifest, or a spurious change notice will be generated.
To fix this, add a members_insync? method on the directoryservice group
provider.

(PUP-2575) Sort OSX group membership before comparison

---

acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb

This commit shortens the username used in the
`ticket_6857_password-disclosure-when-changing-a-users-password`
acceptance test to adhere to the default 8 character limit in AIX.

(PUP-5310) Shorten username for AIX acceptance

---

lib/puppet/resource/capability_finder.rb
lib/puppet/resource/catalog.rb
spec/unit/resource/capability_finder_spec.rb

Ensure that code_id is part of the query when asking PuppetDB for
a capability.

(PUP-5081) Lookup capabilities using code_id

---

lib/puppet/parser/environment_compiler.rb
lib/puppet/parser/resource.rb
lib/puppet/pops/types/type_mismatch_describer.rb
lib/puppet/resource/type.rb
spec/unit/appmgmt_spec.rb

When compiled with the environment compiler, consumers of capability
resources that has non-default parameters will fail with a validation
error on parameters that are expected to be consumed from the
capability. At validation time only the type and title of the
capability is known.
This commit relaxes the parameter validation when the environment
compiler is used. The compiler will detect resources that consumes
capabilities (using require or consume meta parameters) and mark such
resources as `unevaluated_consumer`. The validation of such resources
will not consider a missing but required parameter an error.

(PUP-5294) Do not validate parameters of unevaluated consumers

---

spec/unit/provider/package/dnf_spec.rb

The install tests will fail when running on an OS with majrelease
< 5, so stub that value.

(maint) Stub Facter operatingsystemmajrelease value in DNF tests

---

acceptance/tests/aix/aix_package_provider.rb

This commit updates the teardown step in the `aix_package_provider`
test to ensure that the packages involved in the test are removed
when the test is completed.

(PUP-5311) Update teardown for aix pkg acceptance

---

lib/puppet/face/module/changes.rb

With this commit, the help associated with `puppet help module changes`
is updated to reflect the actual behavior of the command.

(PUP-4743) Update puppet help module changes

---

lib/puppet/plugins/data_providers/data_provider.rb
spec/fixtures/unit/functions/lookup/environments/production/modules/hieraprovider/data/first.json
spec/fixtures/unit/functions/lookup/environments/production/modules/hieraprovider/hiera.yaml
spec/fixtures/unit/functions/lookup/environments/production/modules/hieraprovider/manifests/init.pp
spec/fixtures/unit/functions/lookup/environments/production/modules/hieraprovider/metadata.json
spec/unit/functions/lookup_spec.rb

When a merge of hiera paths resulted in a not found, the singleton
object representing 'not found' was printed in the explanation. This
commit removes that printout since merging sources where nothing is
found doesn't yield a merged result.

(PUP-5278) Fix unhelpful reference in lookup explain output

---

lib/puppet/application/lookup.rb
spec/unit/application/lookup_spec.rb

Prior to this commit, the --node flag did not actually work as
intended, it would simply always default to the machine you were
running lookup on due to some settings not being configured properly.
Now you can specify a node with --node and the host name and lookup
will find and compile that node to obtain a scope. If you do not
specify a node then lookup will default to using the scope of the
machine you are running on (which is intended to be the master).

(PUP-5059) Add the --node feature to lookup CLI tool 

---

lib/puppet.rb
lib/puppet/defaults.rb
lib/puppet/environments.rb
lib/puppet/node/environment.rb

Prior to this commit, the Puppet.future_parser? method would load
the environment configuration from disk each time the method was
called. This had a very negative performance impact since it happens
in a lot of places.
This commit ensures that the future_parser flag is cached in the
environment instance.
All caches are cleared when the global configuration is changed.
Individual environment caches are cleared when the environment times
out.

(PUP-5380) Cache future_parser flag in environment

---

lib/puppet/application/filebucket.rb
lib/puppet/file_bucket/dipper.rb
lib/puppet/indirector/file_bucket_file/file.rb
spec/unit/file_bucket/dipper_spec.rb
spec/unit/indirector/file_bucket_file/file_spec.rb

Previously the filebucket list command was implemented using the `find`
method on the `file_bucket_file` endpoint passing along `list_all` as a
query parameter. However, the filebucket is accessible to all users, so
any remote user could list the contents of the filebucket and retrieve
file content backed up by other hosts. And since retrieve and list both
use `find` where the only difference is the `find_all` query parameter,
it wasn't possible to write an ACL that allowed access to the
former, but denied access to the latter.
This commit modifies the dipper client code to raise an error when
trying to list a remote filebucket. It also modifies the
Puppet::FileBucketFile::File#list server-side code to reject remote
requests, for example, if you curl the REST API directly.
Note the list …

(PUP-5151) Don't allow remote file buckets to be listed

---

api/docs/http_api_index.md
api/docs/http_catalog.md
api/docs/http_file_metadata.md
api/docs/http_node.md

Previously the source_permissions parameter was added to file_metadata
without updating the API documentation. Update the API documentation
with examples of its use.
The client includes which environment was configured on the client (if
not using the application default) as the configured_environment in node
and catalog requests. This may be used by a node classifier when
determining the environment the client should use, as added in PUP-4521.
Also adds that the transaction_uuid can be included in the node request.

(PUP-4740) Update HTTP APIs for source_permissions and configured_environment

---

lib/puppet/parser/compiler.rb

This commit ensures that capability mappings are evaluated twice. Once
before evaluate_main since it eventually calls on evaluate_classes
which may require capability mappings, and then again after
evaluate_site since it may introduce new mappings.
I have tested this manually in my own local setup (based on input from
Nick Lewis in the JIRA) but there should be acceptance tests for this
too.

(PUP-5275) Evalutate capability mappings after evaluating site

---

spec/unit/functions/regsubst_spec.rb

Before this, there were no tests checking that regsubst function
behaved correctly given an empty array.

(PUP-5292) Add tests for regsubst given empty array

---

lib/puppet/pops/evaluator/access_operator.rb
spec/unit/pops/evaluator/access_ops_spec.rb

Passing a literal String as T to the Undef[T] or Optional[T] types
was handled badly in the AccessOperator and equally badly in the
unit test that verified the function (for Undef[T], there was no
unit test for Optional[T]).
This commit fixes the problem and the tests.

(PUP-5381) Fix access operator for Undef and Optional types

---

lib/puppet/environments.rb

This commit fixes a regression that causes all manifests to be watched
and hence to be subject to the filetimeout in directory environments.
This causes reparse of the manifests even if the environment_timeout
is set to unlimited.

(PUP-5398) Fix regression causing file watching for dir environments

---

acceptance/tests/aix/nim_package_provider.rb

This commit adds a teardown step to the nim package provider
test which removes the packages it installs once the test is
complete. This prevents failures on subsequent runs on the same
host when the test attempts to install the same package. In addition,
we now check stderr instead of stdout for the expected downgrade
error.

(PUP-5391) Fixup AIX nim provider acceptance test

---

lib/puppet/util/windows/adsi.rb
spec/unit/provider/user/windows_adsi_spec.rb
spec/unit/util/windows/adsi_spec.rb

Currently when the password policy for "Password must meet complexity
requirements" is enabled, attempts to have puppet create Windows users
without passwords fail with result `"OLE error code:800708C5 in Active
Directory. The password does not meet the password policy requirements.
Check the minimum password length, password complexity and password
history requirements."`
This behavior is expected when the password is specified but doesn't meet
the password policy, but not expected when the user has not attempted to
manage the password, e.g. leaving it empty. Correct Puppet not to try to set
the password unless it is specified.
Note that when the password policy "Minimum password length" is greater than
0, the password must always be specified. This is due to how Windows
validates new …

(PUP-5271) ADSI User - Do not manage unspecified password

---

lib/puppet/environments.rb

Due to a merge conflict, a call to the Puppet::Node::Environment
watching= method was restored in stable and master. However, that
method has been removed on these branches and so the chance was
causing test failures.
Remove the unneeded call to watching= to fix failing tests.

(maint) Remove call to watching in Puppet::Environments

---

lib/puppet/application/lookup.rb

Add support for the --facts flag in puppet lookup. This allows the
user to give a .json or .yaml file full of fact names and values
via the --facts flag. The facts the user specified will be merged
with the existing facts for the current node. This means that if
a fact is specified in the file it's value will be overridden, but
if it is not specified, the original fact value for the node will
stay the same.

(PUP-5060) Allow users to override facts

---

lib/puppet/parser/compiler.rb
spec/unit/appmgmt_spec.rb

Per the app spec, providing node mappings on app declarations is
optional. Prior to this commit, an error would be raised if the nodes
key on an app declaration was undefined. This commit prevents `.value`
from being called on an undefined value during application evaluation.

(PUP-5382) Allow undefined nodes key on app declarations

---

lib/puppet/defaults.rb

This can be revisited if the Puppet Forge team ever develops a non-internal use
for module groups.
When this is merged, please resolve https://tickets.puppetlabs.com/browse/DOC-2266.

(docs) Clarify that module_groups is an internal setting

---

lib/puppet/ssl/oids.rb
spec/unit/ssl/oids_spec.rb

Prior to this commit we were lacking cloud and puppet workflow specific
names.
This commit adds the following
"1.3.6.1.4.1.34380.1.1.18" = 'pp_region'
"1.3.6.1.4.1.34380.1.1.19" = 'pp_datacenter'
"1.3.6.1.4.1.34380.1.1.20" = 'pp_zone'
"1.3.6.1.4.1.34380.1.1.21" = 'pp_network'
"1.3.6.1.4.1.34380.1.1.22" = 'pp_securitypolicy'
"1.3.6.1.4.1.34380.1.1.23" = 'pp_cloudplatform'
"1.3.6.1.4.1.34380.1.1.24" = 'pp_apptier'
"1.3.6.1.4.1.34380.1.1.25" = 'pp_hostname'

(PUP-5355) Add more descriptive oid names

---

ext/debian/puppet.init
ext/osx/puppet.plist
ext/redhat/client.init

Prior to this commit, some of puppet's service
scripts were setting PATH. This appears to be
unneccesary. Additionally, the specific PATH that
was being set could lead to unexpected use of the
puppet-agent's "private" utilities, such as gem.
This commit removes PATH where it was set in
puppet's service scripts.

(PUP-5427) Don't set PATH in puppet's service scripts

---

acceptance/lib/puppet/acceptance/mount_utils.rb
acceptance/tests/resource/mount/defined.rb
acceptance/tests/resource/mount/destroy.rb
acceptance/tests/resource/mount/modify.rb
acceptance/tests/resource/mount/mounted.rb
acceptance/tests/resource/mount/query.rb

(PUP-5339) Add mount_utils acceptance helper library
This commit adds new helpers to assist with dealing with mountpoints
and fstab on testing hosts. It is used in the suite of mount resource tests.
(PUP-5339) Update mount tests to work in AIX
This commit updates each of the mount resource tests to work in
AIX. The main difference between AIX and regular Linuxes is that
we need to use crfs to properly create a filesystem. Slight
modifications have been made to deal with the small differences
in setup before running puppet.

(PUP-5339) Update mount tests to work in AIX

---

lib/puppet/daemon.rb
spec/unit/daemon_spec.rb

Starting in ruby 2, signal handlers are not allowed to acquire a
mutex[1], because it could deadlock[2]. For example, the main thread
acquires a mutex, is interrupted by a signal, signal handler runs in a
separate thread, and will deadlock if tries to acquire the already
locked mutex. In ruby 1.8/9, the behavior was allowed, but wasn't safe.
In ruby 2, it's a hard failure.
Commit 6238616 removed thread-safety code because it was incomplete and
puppet primarily runs single threaded -- exceptions being its signal
handler and webrick request processing. PUP-202 was marked as fixed
since we no longer tried to acquire a mutex from a trap context.
However, the signal handler would still call back into puppet code, e.g.
reload, which led to PUP-1635 "current thread not owner".
Commit 245de036f …

(PUP-4516) Exit immediately when sent INT or TERM

---

lib/puppet/daemon.rb
spec/unit/daemon_spec.rb

PUP-4516 and commit c9a7e6d506768cb1c00767f785339bec512d069e introduce
a message before exiting after receiving a TERM or INT signal.
This commit adds the signal name to this error message, clarifying the
fact that we actually exit because we receive a signal and specifying
the signal.

(PUP-4516) Add signal name in exit message

---

acceptance/config/aio/options.rb
acceptance/tests/agent/agent_disable_lockfile.rb
acceptance/tests/security/cve-2013-4761_injection_of_class_names_loading_code.rb

Previously, we were restarting puppetserver twice during each call to
`with_puppet_running_on`, which takes about 30 seconds each time. The
first restart occurs because the test needs to change configuration,
e.g. autosign policy, destructive ssl operations, etc. The second
restart restores the original configuration and brings the server back
up. But that is useless, because we stop the server as soon as we call
`with_puppet_running_on` the next time.
This commit sets the `restart_when_done beaker` option globally in
AIO, which requires Beaker 2.27.0 to work correctly and is already the
minimum beaker version we depend on for acceptance.
Also two tests were calling `with_puppet_running_on` in a loop
unnecessarily, so the call was moved outside the loop.
In practice, acceptance tests on …

(PUP-5383) Don't restart puppetserver twice

---

acceptance/tests/resource/zone/dataset.rb

This commit adds 1 as an acceptable exit code to the teardown steps
in the acceptance test `tests/resource/zone/dataset.rb`.
This prevents the test from failing when the system state was
already in the desired exit state.

(PUP-5433) Set solaris zone teardown to exit cleanly

---

lib/puppet/application/lookup.rb

Prior to this commit, since lookup searched for a node called "default"
to obtain the node the user was running lookup from, it was creating
a ghost node in PuppetDB that did not have a hostname and was unusable.
This meant that lookup would fail in the next run because it would
attempt to obtain the hostname of the ghost node.
In order to prevent this, switch to looking up the current node
using it's certname rather than "default" so that no false node is
created.

(PUP-5425) Lookup creates phantom node in PuppetDB

---

lib/puppet.rb
lib/puppet/context.rb
lib/puppet/parser/compiler.rb
spec/unit/parser/compiler_spec.rb

@hlindberg take another look. Since we chatted:
* I added the ability to ignore or restore a context key, which allowed me to flesh out the spec tests. 
* I also added some explanatory comments because the priority scheme for setting `trusted_data` begged for some explanation.
* Last, note that I moved the `to_h` to the *end* of the block passed to `lookup`. In the location I had it in the previous version of this PR, that would raise if lookup failed because it would try to call that `to_h` before it even got to the block. Fun stuff.

(PUP-5441) Sanitize node's trusted info

---

acceptance/tests/ssl/certificate_extensions.rb
lib/puppet/context/trusted_information.rb
spec/unit/context/trusted_information_spec.rb
spec/unit/settings_spec.rb

Renames the domainname trusted fact to domain, since the latter is what
we use for the Facter fact.

(PUP-5097) Rename domainname trusted fact to domain

---

acceptance/tests/reports/submission.rb

This commit modifies the acceptance test `reports/submission.rb`
to use the `agent.node_name` rather than the beaker
`agent.hostname` value to validate the contents
of the submitted report on the master.
[skip ci]

(PUP-5432) Use node_name to validate report test

---

lib/puppet/data_providers/hiera_support.rb
lib/puppet/data_providers/lookup_adapter.rb
lib/puppet/plugins/data_providers/data_provider.rb
lib/puppet/pops/lookup/invocation.rb
spec/fixtures/unit/data_providers/environments/hiera_misc/data/common.yaml
spec/fixtures/unit/data_providers/environments/hiera_misc/modules/one/data/common.yaml
spec/fixtures/unit/data_providers/environments/hiera_misc/modules/one/manifests/init.pp
spec/unit/data_providers/hiera_data_provider_spec.rb

A check for qualified name in modules prevented lookup of the
'lookup_options' key in a module. This commit adds that check and
a test that verifies that lookup_options declared in environment
and module are merged and used.

(PUP-5395) Fix problem with lookup_options not found in module

---

lib/puppet/data_providers/lookup_adapter.rb
lib/puppet/pops/lookup/explainer.rb
lib/puppet/pops/lookup/invocation.rb
spec/unit/application/lookup_spec.rb
spec/unit/data_providers/hiera_data_provider_spec.rb
spec/unit/functions/lookup_spec.rb

The global data binding was forgotten in the explain support. This
commit adds the needed output and alters all test to accomodate its
presence.

(PUP-5278) Include global data binding in explain output

---

lib/puppet/indirector/catalog/static_compiler.rb
spec/unit/indirector/catalog/static_compiler_spec.rb

Previously, the static compiler would raise a NoMethodError if a file resource had recurse => true, but the source referred to a file. This change ensures we only try to generate child resources if the source has children.

(PUP-5035)  Only add child resources for directory sources

---

lib/puppet/provider/group/windows_adsi.rb
lib/puppet/type/group.rb
spec/unit/provider/group/windows_adsi_spec.rb

Assume that `puppet resource group guests` yields the following:
group { 'guests':
ensure  => 'present',
gid     => 'S-1-5-32-546',
members => ['Guest', 'Administrator'],
}
Previously, trying to apply the following manifest with a bad user,
would trigger a bug in Puppet:
group { 'guests':
members => ['Guest', 'Administrator', ''],
}
An error would be raised in resource_harness#sync_if_needed method, and
would lose important details about expected resource changes:
Notice: Compiled catalog for vagrant-2008r2.corp.puppetlabs.net in environment production in 0.22 seconds Error: Could not resolve username:
Error: /Group[Guests]: Could not evaluate: Puppet::Util::Log requires a message
Notice: Finished catalog run in 0.05 seconds
This change prevents both the loss of error …

(PUP-4426) backport (PUP-4386) Windows group invalid user error msgs 

---

acceptance/tests/resource/service/ticket_14297_handle_upstart.rb

This commit modifies the confine block on the handle_upstart test to
confine out the execution of the ticket_14297_handle_upstart test based
on the platform version numbers, e.g., 15.04 or greater, as opposed to
just the platform code name, e.g., Vivid or Werewolf.  This is needed
because the platform field is populated for code names on some CI
pipelines - core Puppet - but by version number on other pipelines -
e.g., Puppet Server.

(PUP-5470) Update handle_upstart test to case out Ubuntus by version

---

acceptance/config/nodes/gem.yaml
acceptance/config/nodes/osx-1010-x86_64.yaml
acceptance/config/nodes/osx-1011-x86_64.yaml
acceptance/lib/puppet/acceptance/install_utils.rb

Previously, beaker tried to install puppet-agent on OSX 10.11 twice
because the 'el' regex matched the elcapitan platform. When the 'el'
regex was made to be more specific, beaker added PermitUserEnvironment
to the pre 10.11 location, because beaker expects platform to contain
version numbers, not codenames.
This commit changes all OSX host configs to version numbers as
codenames, and makes the 'el' regex more specific, as 'el' could occur
in a future OS name.
It also backports the osx-1011 node definition to stable, as we haven't
merged down yet.
For consistency, this commit also updates the platform identifier for
smoke testing gem installs.

(PUP-5146) Update platform field to use version numbers

---

acceptance/tests/aix/aix_package_provider.rb

This commit updates the teardown step for the
`aix_package_provider` acceptance test to not use puppet
to remove the package.
This test is intended to test the provider. So, even if there
is a bug in the provider, we want to make sure the package is
removed. This commit uses the native AIX package call to ensure
that the package is uninstalled.
[skip ci]

(maint) Update teardown for aix pkg acceptance

---

acceptance/Gemfile
acceptance/tests/modules/install/with_version.rb

We were using an old beaker version that relied on deprecated vmpooler
behavior (see BKR-572), which will be removed real soon now. So bump
beaker to the same version we're using in puppet#stable.
[skip ci]

(PUP-5308) Bump beaker dependency

---

lib/puppet/application/agent.rb
lib/puppet/application/master.rb
lib/puppet/daemon.rb

When running the agent, waiting for certificates can sleep and wait for
a significant period of time. During that time a SIGTERM event can come
in (from Ctrl-C or service shutdown), causing an exception to be thrown
that prevents daemon cleanup.
Setup signal traps before waiting for certs so we ensure daemon cleanup
occurs. Update the master as well so all call paths only call
set_signal_traps once, and do so immediately after possibly daemonizing.

(PUP-5422) Setup signal trap before waiting for certs

---

.gemspec

In PA-25 we are registering puppet, facter, and hiera as gems in the
puppet agent packaging. However, the version of facter registered is in
the 3.x series, so currently any gems installed with a dependency on
puppet would end up trying to pull in facter 2.4, causing conflicts with
the puppet-agent facter. This allows dependency resolution to work
properly for the puppet-agent rubygems installation.

(packaging) (PA-25) The registered facter gem in puppet-agent is v3.x

---

lib/puppet/pops/issues.rb

When a resource title was missing or not properly capitalized,
puppet would provide a confusing error message. Rephrase this
error message so that it is easier to understand and is more
helpful to the user.

(PUP-5090) Improve missing title error message

---

acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/tests/resource/package/common_package_name_in_different_providers.rb
acceptance/tests/resource/service/service_enable_linux.rb

This commit updates two acceptance tests which were failing in Fedora
22: service_enable_linux.rb and
common_package_name_in_different_providers.rb.
The systemd provider is already the default for all versions of Fedora,
so there is no need to bump the provider.
For the common package name test, we need to use puppet-agent's private
gem binary, as rubygems is not installed on our Fedora 22 testing VMs.

(PUP-5478) Fix tests failing in Fedora 22

---

lib/puppet/provider/cron/crontab.rb
spec/unit/provider/cron/parsed_spec.rb

Without this, crontab files containing environment variables that have spaces after the variable name and before the equal sign cannot be parsed properly.

(PUP-5452) Correct parsing of crontab environment variable lines

---

acceptance/tests/resource/service/puppet_mcollective_service_management.rb
lib/puppet/provider/service/smf.rb
spec/unit/provider/service/smf_spec.rb

When stopping, starting, and restarting services, SMF tracks state
transitions through through two states: `state` for the
current state, and `nstate` for the next state. Because of this,
Puppet would occasionally encounter race conditions when attempting
to act on a service that was in the middle of a state transition.
This is due to the asychronous nature of service management in Solaris,
and the fact that state transitions are not atomic.
This commit adds a 60 second timeout when stopping or starting services
to ensure that the state transition has completed before continuing
operatings.

(PUP-5262) Wait for services to finish state transitions in Solaris

---

acceptance/tests/ticket_4622_filebucket_diff_test.rb

In AIX, the output of diff varies from other platforms. This was
causing our filebucket diff test to fail due to a strict regex.
This commit updates the regexes to allow diff formats from AIX
5.3, 6.1 and 7.1.
[skip ci]

(PUP-5483) Update diff regex in filebucket test for AIX

---

acceptance/setup/common/pre-suite/100_SetParser.rb

Previously, the future parser setup step was using Beaker's
`lay_down_new_puppet_conf` method to set the parser=future puppet
setting. When using beaker 2.x, the method calls `puppet master
--configprint config` in order to figure out the location of
puppet.conf, but since the master application isn't supported on
Windows, it was raising an error: "Puppet master is not supported on
Microsoft Windows". This issue was introduced when we bumped our
beaker dependency from ~> 1.17 to ~> 2.23 in 94d93e863 as beaker's
method behaves differently in 2.x than it did in 1.x.
This commit eliminates the call to beaker, instead just calling
`puppet config set --section main` to set the parser setting to the
value of the PARSER environment variable.

(PUP-5308) Use puppet config set for future parser

---

lib/puppet/util/windows/security.rb
spec/integration/util/windows/security_spec.rb

- Previously, as part of b578ed4,
when Puppet would manage a directory where SYSTEM was not explicitly
set, it would re-add SYSTEM to the directory in an effort to ensure
that Windows (and services like Puppet itself) could later access the
directory:
`NT AUTHORITY\SYSTEM:(F)`
However, this approach was flawed, since files could be written to
that directory (by Puppet or otherwise), and they would no longer be
accessible to SYSTEM since inheritance was not set on the directory.
Instead, the permissions should be set as:
`NT AUTHORITY\SYSTEM:(F)(CI)(OI)`
This allows the SYSTEM permission to propagate to any newly created
files or directories within the parent managed directory.
- As it turns out, Puppet itself is affected by this flaw on the first
run that it writes an agents private key, …

(PUP-5480) Windows dirs should inherit SYSTEM

---

appveyor.yml

Previously, appveyor skipped based on the commit message
matching the pattern for a docs commit or having the text
"acceptance test" anywhere in the commit message.
Unfortunately both these have led to some confusion in looking
at PRs and various debugging efforts to figure out what was
wrong with AppVeyor. This behavior is also inconsistent with
Travis.
So this PR removes that skipping behavior.

(maint) Remove skipping based on commit msg

---

.travis.yml

This bumps travis CI to test against:
* 2.1.7 (which is what puppet-agent is now shipping with)
* 2.2.3 (latest of 2.2 series)

(maint) Bump travis to test against latest rubies

---

lib/puppet/application/lookup.rb

Prior to this commit, the --help message for lookup did not make it
clear that lookup needs to be run on a puppet master or a masterless
node. Update the docs to reflect this fact so the workflow is more
clear to users.

(maint) Update lookup help to specify running on master

---

lib/puppet.rb
lib/puppet/indirector/facts/facter.rb

Recently several Puppet-specific facts were added to the facts
end-point. Anyone trying to use Puppet as a library, expecting all facts
to be registered with Facter, will find those facts missing. Create a
helper to initialize them as needed.

(PUP-5508) Create initialize_facts helper for core Puppet facts

---

lib/puppet/pops/evaluator/collectors/exported_collector.rb
lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/validation/checker4_0.rb

(PUP-5487) Remove runtime warning about storeconfig not beeing set and instead only warn on evaluation time.
Also since the evaluation time warning included less information it is changed to also include information about where the collection happened.

(PUP-5487) Remove runtime warning about storeconfig not beeing set and instead only warn on evaluation time

---

lib/puppet/resource/type.rb

The pseudo variable for calling_module was assigned too late when
a resource was evaluated which resulted in that a hiera interpolation
used when finding default values didn't interpolate the value
correctly.
This commit ensures that the value is assigned before the external
values are resolved which means that hiera will find the right
values.
I suggest the addition of an acceptance test to verify this behavior.

(PUP-5525) Fix pseudo variable assignment that happens too late

---

lib/puppet/pops/evaluator/collector_transformer.rb
spec/integration/parser/collection_spec.rb

The support for resource references in collector search expressions is
missing. This is a documented aspect of resource collectors and
previously worked in Puppet 3.
This PR attempts to provide a solution to this issue. Full disclosure though, I'm fairly new to the way the new parser works and it's still mostly a mystery to me. I've spent some time pulling it apart and I think I've found the most reasonable solution. If there is some other materials I should look at it to understand more, that'd be awesome.

(PUP-5465) Add missing support for Resource References in collection

---

lib/puppet/resource.rb

This commit ensures that the environment instance rather than its
name is passed to the DataBinder indirection during lookup. This
prevents that a lot of unnecessary lookups takes place when the
environment_timeout is set to zero.
Please note that there are two PRs for this fix. One for the 3.x branch that places a fix in file `lib/puppet/resource.rb` and another for 4.x that places the same fix in file `lib/puppet/data_providers/lookup_adapter.rb`. When the 3.x branch is merged to stable this PR should be considered a no-op.

(PUP-5547) Prevent unnecessary environment eviction

---

lib/puppet/provider/sshkey/parsed.rb
spec/fixtures/unit/provider/sshkey/parsed/sample_with_blank_lines
spec/unit/provider/sshkey/parsed_spec.rb

Previously, blank lines in the default ssh_known_hosts file would
cause errors in the sshkey type due to a faulty regex. This commit
updates said regex to properly match blank lines with no whitespace
characters.

(PUP-5513) Allow blank lines in ssh known hosts file

---

lib/puppet/application/lookup.rb

Prior to this commit, the facts passed in via the --facts were not
being promoted to topscope because they were not being added to the
node parameters. This meant they would not be found in a lookup.
Now, facts in the given fact file are merged into the node parameters
so that when the node is compiled they will be promoted to topscope.

(PUP-5060) Fix lookup --facts bug

---

lib/puppet/pops/evaluator/closure.rb
spec/unit/functions/epp_spec.rb
spec/unit/functions/inline_epp_spec.rb

The refactor of parameter validation that was made in PUP-4458 left
the EPP template parameters out. That was an oversight. This commit
ensures that EPP templates are validated using the same logic that
is used when validating resource parameters.

(PUP-5552) Validate EPP parameters

---

lib/puppet/pops/issues.rb
lib/puppet/pops/parser/lexer2.rb
spec/unit/pops/parser/lexer2_spec.rb

The lexer did not detect a multiline comment that wasn't closed and
returned the same parse position over and over again causing the
parser to loop forever. This commit remedies that and adds a new
issue UNCLOSED_MLCOMMENT to the set of issues reported by the parser.

(PUP-5127) Fix hung process caused by unclosed multiline comments

---

lib/puppet/type/interface.rb
lib/puppet/util/network_device/cisco/device.rb
lib/puppet/util/network_device/cisco/interface.rb
spec/unit/type/interface_spec.rb
spec/unit/util/network_device/cisco/device_spec.rb

This patch adds full support for interface mode auth, and encapsulation negotiate to the cisco device. It also adds new tests for mode and encapsulation to the interface resource which didn't exist before.

PUP-5289 adding interface mode auto, encapsulation negotiate to puppet device

---

lib/puppet/node.rb
spec/unit/node_spec.rb

This commit adds code to ensure that the Puppet::Node attribute
'environment_name' and its parameter named 'environment' are updated
when the attribute 'environment' is modified.

(PUP-5522) Ensure consistency of node environment attr and param

---

lib/puppet/application/lookup.rb
spec/unit/application/lookup_spec.rb

The lookup command didn't accept the merge strategy 'first'. Probably
because this strategy was the default but could not be explicitly
specified in earlier versions.
To fix this, and also cater for other future additions, this commit
changes the validation of the --merge parameter so that it uses the
MergeStrategies::strategy_keys method instead of a hard-coded set.

(PUP-5511) Make lookup command accept all valid choices for --merge

---

lib/puppet/application/lookup.rb
lib/puppet/data_providers/lookup_adapter.rb
lib/puppet/plugins/data_providers/data_provider.rb
lib/puppet/pops/lookup.rb
lib/puppet/pops/lookup/explainer.rb
lib/puppet/pops/lookup/invocation.rb
spec/fixtures/unit/application/environments/production/data/common.yaml
spec/unit/application/lookup_spec.rb
spec/unit/data_providers/hiera_data_provider_spec.rb
spec/unit/functions/lookup_spec.rb

The explainer will currently only report the actions that lookup
performs during traversal of global data binders and providers in
order to find the data for a given key. This commit adds an option
to include the lookup of the new 'lookup_options' hash to the report.
The '--explain-options' option takes no argument can be used alone or
in combination with the '--explain' option. When used alone, and
when no keys are passed to the lookup command, the result will be
the global lookup_options hash (merge of global data binding and
environment data provider). When keys are passed, the lookup_options
will be the full hash that includes a hash found in the data provider
of the module identified by the key.

(PUP-5437) Add 'lookup_options' to the lookup explainer

---

acceptance/tests/resource/file/symbolic_modes.rb

Previously, we ensured the `symuser` and `symgroup` accounts existed for
every symbolic file mode combination, of which there are over 40. Due to
BKR-628, we were updating the `PrimaryGroupID` of the `symgroup` group
everytime on OSX, leading to an apparent race condition where we would
`chmod` a file to the old gid, and then try to resolve the gid to a
name, but since the gid no longer existed, the test would fail.
This commit modifies the acceptance test to use puppet to ensure the
user and group accounts (avoiding the beaker issue), moves the ensure
check to once per agent, and adds a teardown to ensure the accounts are
removed when the test is finished.
[skip ci]

(PUP-5444) Create user and group accounts once

---

lib/puppet/provider/package/rpm.rb
spec/unit/provider/package/rpm_spec.rb

This reverts commit 1fdaeae9fa4f18c1c96da3d6fd84613dab6024f8, which
introduced a regression when using the yum provider under certain
circumstances.
This change was originally meant to fix a DNF issue when installing RPMs
which included the epoch field in their release strings. However, it
also brought about a new issue in the yum provider when trying to
manage packages which use the epoch field. Upon every run, Puppet throws
a notice to indicate that the package version has been updated to
include the epoch. Adding the epoch into a manifest results in an error
when installing a package which isn't already on the system.
This commit reverts the original change until further investigation and
more comprehensive changes can be made.

(PUP-5549) Revert "(PUP-5025) RPM Epoch should be included in ensure field

---

lib/puppet/provider/service/launchd.rb
spec/unit/provider/service/launchd_spec.rb

Reading text-based plist files with plutil appears to incur a lot of
overhead. Attempt to read all plists as text first, falling back to
plutil if that fails. Failing to read a binary plist appears to incur
very little overhead.
This appears to compare favorably to other approaches using
CFPropertyList, and is a much smaller change. Average times for `puppet
resource service` improved from 30 seconds to 5 seconds on a variety of
tested systems (OS X 10.9 with Ruby 1.9.3, OS X 10.10 with Ruby 2.0.0,
OS X 10.11 with Ruby 2.1.7).

(PUP-5505) Improve performance of reading service plists

---

lib/puppet/data_providers/lookup_adapter.rb
lib/puppet/indirector/hiera.rb
lib/puppet/pops/lookup/invocation.rb
spec/unit/resource_spec.rb

Errors originating from syntax errors in the hiera.yaml were nested
and the error messages were repeated, resulting in a long blob of
unhelpful text where the original stack trace was lost.
This commit ensures that no message is repeated and that the
stack backtrace is retained.

(PUP-5502) Improve error messages for faulty hiera.yaml

---

lib/hiera/scope.rb
spec/unit/hiera/scope_spec.rb

This PR is the suggested fix for PUP-5578

(PUP-5578) use exist? instead of '' to determine if scope key exists.

---

lib/puppet/pops/evaluator/access_operator.rb

No error context (file, line, position) was provided for the case
when a non numeric access operator was used on a string. It was
however provided when the same operator was used on an array. This
was caused by an incorrect passing of the semantic parameter.
This commit fixes that.

(PUP-5509) Ensure error context for non-numeric index error

---

lib/puppet/type/group.rb

Auth_membership plays a role in how a provider can set a group to
empty based on whether it is considered authoritative or not. The
documentation should provide an indication that setting a group
empty is possible.

(doc) Clarify auth_membership

---

lib/puppet/pops/model/factory.rb
lib/puppet/pops/model/model.rb
lib/puppet/pops/parser/lexer2.rb
lib/puppet/pops/parser/slurp_support.rb

This PR contains two commits. One that optimizes the lexer and one that optimizes the parser
factory. The measurements that I've done indicates that when this PR is applied, parsing will spend:
55% less CPU time with JRuby (tested using JRuby 9.0.4)
13% less CPU time with MRI (tested on 1.9.3, 2.1.1, and 2.2.1).
The parser is 11% faster with MRI than with JRuby.
This PR is for the stable branch and supersedes #4470 which was for master.

(PUP-5554) Improve parser performance

---

lib/puppet/parser/compiler.rb
spec/unit/parser/compiler_spec.rb

The current resurrection of the 'trusted' hash changes the
authentication to `false`. This commit removes that behavior so that
the hash is left untouched.

(PUP-5061) Alter resurrection of trusted retain 'authenticated'

---

lib/puppet/provider/package/zypper.rb
spec/unit/provider/package/zypper_spec.rb

Added zypper purge to be able to remove packages using zypper instead of rpm, which in some cases could break systems due to lack of dependencies check.

(PUP-3149) Add uninstall method to zypper provider

---

lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/functions/function.rb

This commit ensures that calls to 4x functions are profiled. The
description of the profiling data is simply the method name since
I wanted to avoid unnecessary string formatting. The entry is
easy enough to understand anyway given that the metric_id is
:function.

(PUP-5063) Ensure that 4x-functions are profiled

---

lib/puppet/resource/type.rb
spec/unit/resource_spec.rb

A class parameter that is explicitly specified with an `undef` value
should not prevent that a data lookup is made for the parameter but
it did. This commit fixes that problem.

(PUP-5592) Ensure that undef parameter does not prevent data lookup

---

lib/puppet/provider/service/debian.rb
spec/unit/provider/service/debian_spec.rb

In the Debian family, the `service` command provides an
abstraction around available init systems, allowing it to be used
to properly determine service state regardless of which init system
is active on the system.
This commit updates the Debian provider's `statuscmd` method to use
`service` at all times, allowing the provider to properly query
services regardless of OS version or init system in place.

(PUP-5548) Use `service` in debian provider to interact with all init systems

---

lib/puppet/data_providers/lookup_adapter.rb
lib/puppet/pops/lookup/explainer.rb
spec/unit/functions/lookup_spec.rb

The `lookup_options`special key should not be found using a normal
lookup and neither should any of its subkeys when a dotted key is
used. This commit ensures that this holds true and also adds a new
explanation of 'Invalid key' to be used when such lookup attempts are
made.

(PUP-5598) Ensure that keys starting with lookup_options fail lookup

---

lib/puppet/pops/issues.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/pops/parser/parser_rspec_helper.rb
spec/unit/pops/validator/validator_spec.rb

Adds validation logic to detect duplicate parameter names in host
class definitions, defines, and EPP templates.

(PUP-5590) Detect duplicate parameter names

---

acceptance/tests/ticket_5592_hiera_lookup_when_param_undef.rb

This commit adds an acceptance test to ensure that a valid hiera
lookup is applied to a class parameter when the value of that
parameter is set to `undef`.

(PUP-5592) Test hiera lookup of undef class param

---

lib/puppet/indirector/rest.rb

Hello, 
This PR is solving issue https://tickets.puppetlabs.com/browse/PUP-5428.
When the length of the uri is greater that 1024, the GET is converted in POST and all data (environment, facts) are stored in the body request.
Adding a query string when posting allows to loadbalance catalog compilation (for example) to specific puppetserver.
Regards
Olivier

(PUP-5428) Add a query string with the environment when using POST

---

lib/puppet/provider/package/yum.rb
spec/unit/provider/package/yum_spec.rb

* Previous code was using `#warn`
* Would cause error: `private method `warn' called for Puppet::Type::Package::ProviderYum:Class`
* Changed to correct method `warning`
* Updated spec

(PUP-5594) Fixes yum check-updates private method

---

lib/puppet/provider/aixobject.rb

and they should maintain the original casing. 
We where experiencing a strange behavior with some users using Kerberos authentication, this implies setting the "SYSTEM" attribute to a value of KRB5Afiles.
In hiera this was the (redacted) definition of one such users:
```yaml
xxxxx:
ensure: present
comment: XXXXXX
gid: 'xxxxx'
groups:
- ssh_grp
managehome: 'true'
attributes:
- SYSTEM=KRB5Afiles
- registry=KRB5Afiles
- auth_domain=DOMAIN.AD
home: "%{::default_home}/xxxxx"
shell: "%{::default_shell}"
uid: 'xxxxx'
```
And this is the (redacted) output from "lsuser -c xxxxx":
```bash
#name:id:pgrp:groups:home:shell:gecos:login:su:rlogin:daemon:admin:sugroups:tpath:ttys:expires:auth1:auth2:umask:registry:SYSTEM:loginretries:pwdwarntime:account_locked:minage:maxage:maxexpired:minalpha:minother:mi …
```

Some of the user attributes in Aix could be UPPERCASE 

---

lib/puppet/provider/service/systemd.rb

Revert this part of 7fe61647f23650fc4c93cd6b54c654a20ff7c9f9 because
it means systemd is not detected if running puppet within a chroot
environment where this is not yet mounted.

(PUP-5577) Don't require /run/systemd/system for systemd

---

lib/puppet/defaults.rb
lib/puppet/transaction.rb
lib/puppet/util/skip_tags.rb
spec/integration/transaction_spec.rb
spec/unit/transaction_spec.rb

This commit is a first attempt at achieving 'not tags' or tag negation. I've called them 'skip tags' in this PR. This adds the ability to specify a list of tags to be excluded from the catalog.
I'm not entirely sure this is complete, so I'd like some feedback if this is a desirable feature (I think it is), and if this implementation is feasible.

(PUP-1376) Allow tag negation

---

lib/puppet/provider/package/pip.rb
lib/puppet/provider/package/pip3.rb
spec/unit/provider/package/pip3_spec.rb
spec/unit/provider/package/pip_spec.rb

The issue is that the latest and only available python-pip package via EPEL for EL6 "python-pip-7.1.0-1.el6.noarch" doesn't have /usr/bin/pip-python anymore which is defined to be the binary for pip provider in puppet package resource check https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/package/pip.rb#L42-L48
So I've added a backward compatibility, so pip provider will work either the binary is pip or pip-python

(PUP-4997) Fix pip provider for EL6

---

.travis.yml
lib/puppet/provider/package/pip.rb
spec/unit/provider/package/pip_spec.rb

The pip package provider previously did not work behind a http proxy. It
will now honor system proxy settings for querying latest packages from
`pypi.python.org`.

(PUP-5212) Pip package honors HTTP proxy

---

lib/puppet/functions/match.rb
lib/puppet/parser/functions/match.rb

An unclosed code block was messing up the formatting in the function reference.

(docs) Fix markup typo in the match function

---

lib/puppet/type/file/ensure.rb

Puppet allows users to create symlinks without explicitly specifying the
`link` attribute. Note that this behavior is deprecated as of Puppet
4.3.0.
See also puppet-docs [PR 571](https://github.com/puppetlabs/puppet-docs/pull/571).

(docs) Deprecate implicit symlink creation.

---

acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/lib/puppet/acceptance/mount_utils.rb
acceptance/setup/packages/pre-suite/015_PackageHostsPresets.rb
acceptance/tests/resource/service/service_enable_linux.rb

We were using `el` in various redhat related regexs, but `elcapitan`
unfortunately matches. This commit changes the regex to be more
specific to avoid false positives.

(maint) Don't allow elcapitan to match redhat el regex

---

lib/puppet/data_providers/lookup_adapter.rb
spec/fixtures/unit/data_providers/environments/hiera_module_config/data/common.yaml
spec/fixtures/unit/data_providers/environments/hiera_module_config/data/specific.yaml
spec/fixtures/unit/data_providers/environments/hiera_module_config/hiera.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/data/common.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/data/specific.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/environment.conf
spec/fixtures/unit/data_providers/environments/hiera_modules/hiera.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/manifests/site.pp
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/one/data/common.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/one/hiera.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/one/manifests/init.pp
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/one/metadata.json
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/two/data/common.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/two/hiera.yaml
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/two/manifests/init.pp
spec/fixtures/unit/data_providers/environments/hiera_modules/modules/two/metadata.json
spec/unit/data_providers/hiera_data_provider_spec.rb

The module data provider was a singleton that was cached in the scope
of the environment lifecycle. Yet, it was configured on a per module
basis. The first configuration of the first module to be configured
was cached and subsequently used for all other modules.
This commit ensures that each module that provides data has a unique
module data provider instance.

(PUP-5618) Ensure module data provider isolation.

---

lib/puppet/provider/yumrepo/inifile.rb
spec/unit/provider/yumrepo/inifile_spec.rb

* `reposdir` can be split by whitespace - http://yum.baseurl.org/gitweb?p=yum.git;a=blob;f=yum/config.py;h=97e5e3d3b063294a96227a67cce43a9655cd3aa6;hb=30c993c19b8b85f44e7cec436484862ab55a6961#l171
- Puppet previously only split by commas
- Now changed to a regex of [,|\s|\n] which will catch whitespace, commas and newlines (like in the original python code)
- Added new spec for this new regex
Now against stable (Continued from https://github.com/puppetlabs/puppet/pull/4495)

(PUP-4744) Fixes `reposdir` split by whitespace

---

acceptance/tests/ticket_3360_allow_duplicate_csr_with_option_set.rb

This commit addresses a few issues seen when running the
`ticket_3360_allow_duplicate_csr_with_option_set.rb` test in a local
beaker run:
1) Use `refute_equal` instead of `assert_not_equals` for negative
comparisons.
2) Changed the logic a bit around the iteration of certs on the master
to ensure that only the csrs/certs for the agents under test (and not
unrelated files that might be on the CA) will be used.
3) Validate that the master csr can be reissued - for the case that the
master and agent are the same node.
4) Minor changes to the regexs used to pick the list of agent csrs/certs
from the output of the `puppet cert` command.

(PUP-5625) Addressed some issues with the allow_dup_csrs acceptance test

---

lib/puppet/provider/service/init.rb
spec/unit/provider/service/init_spec.rb

Yocto Linux ships a series of init scripts that are not safe to execute.  This creates unintended consequences such as sending shutdown signals to daemons.
This commit excludes the known list of unsafe scripts so that Puppet does not try to execute them via the service init provider.
https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-core/initscripts/initscripts-1.0
Replaces #4479

(PUP-5520) Exclude Yocto init scripts from service init provider

---

.travis.yml

Move Travis testing to the latest Ruby 2.2 bug fix release, 2.2.4.

(maint) Move to latest Ruby 2.2 bug fix release

---

lib/puppet/pops/parser/evaluating_parser.rb
spec/unit/face/epp_face_spec.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb

This commit ensures that the file name of a loaded puppet function is
propagated properly to the lexer so that errors are can be reported
including this information.

(PUP-5628) Include file name in errors from puppet function loader

---

lib/puppet/module.rb
spec/fixtures/unit/pops/loaders/loaders/dependent_modules_with_metadata/usee2/lib/puppet/functions/usee2/callee.rb
spec/fixtures/unit/pops/loaders/loaders/dependent_modules_with_metadata/user/lib/puppet/functions/user/caller2.rb
spec/fixtures/unit/pops/loaders/loaders/dependent_modules_with_metadata/user/metadata.json
spec/unit/pops/loaders/loaders_spec.rb

The module loader would not find a dependent module when a dash was
used instead of a slash to separate the author and module name in a
dependency in the metadata.json file. Both constructs are allowed
in other places in the code (and on the forge). This commit makes
the loader work with both.

(PUP-5209) Fix so that dash can be used in module dependency

---

acceptance/Gemfile
acceptance/Rakefile

The puppet-agent components need the osinfo version 1 of b-hg,
so that centos4 is correctly specified as a platform name, so
that puppet-agent can be installed on centos4.
This commit moves to b-hg 0.3.1, the first version implementing
that, and specifies the osinfo version when invoking b-hg.

(PUP-5583) Bump to beaker-hostgenerator 0.3.1

---

acceptance/tests/parser_functions/calling_all_functions.rb

:exclamation:To merger: this should be merged up to stable and master as well.  There will be conflicts in the current version in stable and master, but the version in this PR should be retained, conflicts ignored.  
This change adds a test for all parser functions.
This test calls all the parser functions that ship with puppet. It
ensures sane output in most cases. The remainder of the coverage for
functions lies in the spec tests.
[skip ci]

(PUP-5378) acceptance: port all-functions test to 3.x

---

acceptance/tests/parser_functions/calling_all_functions.rb

In the calling_all_functions test we were passing a block to with() with
the wrong number of arguments. This passed in ruby 1.9 due to...
reasons. ruby 1.8 caught this when we ported the test to 3.x.
This change fixes the with() usage.
re: PUP-5378
[skip ci]

(maint) acceptance-fix with() function usage

---

lib/puppet/provider/package/pkgng.rb
spec/unit/provider/package/pkgng_spec.rb

This work updates the pkgng package provider to ensure that port names as resource titles are handled correctly, and that fewer calls to 'pkg version' are made.

(maint) Minor fixes to the pkgng package provider

---

lib/puppet/pops/issues.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/pops/validator/validator_spec.rb

A resource declared without title becomes a BlockExpression with
two statments, a QualifiedName and a LiteralHash. This commit adds
validation logic that detects and reports such statements as a new
`RESOURCE_WITHOUT_TITLE` issue. It also ensures that when such a
declaration is found last in a node, define, or host class, it's
reported instead of the `IDEM_NOT_ALLOWED_LAST` since reporting both
would be confusing.

(PUP-5612) Detect and report resource definitions with missing title

---

lib/puppet/indirector/indirection.rb

Prior to this commit, the errors from the method
`Puppet::Indirector::Indirection.find` that occurred when calling
the `terminus.filter(result)` method was never logged. This caused
the puppet apply command to return 1 without any information since
the command assumes that the indirection has logged all
Puppet::Error exceptions.
This commit ensures that these particular errors are logged by
the `Indirector.find` method.

(PUP-5589) Ensure that errors from terminus filter is propagated

---

acceptance/tests/parser_functions/calling_all_functions.rb

Previously, we required `fqdn_rand(100000)` to return a 5 digit number,
but it can return any number greater than or equal to 0 and less than
100000.  So relax the regex to require between 1 and 5 digits.
Also the regsubst function was defining a regex in a single quoted
string which is written to a manifest as:
regsubst("Cersei","Cer(\w)ei","Daenery\1")
But `\w` in a double quoted string is an invalid escape sequence,
causing puppet to output a warning, but somehow successfully apply
the regex:
Warning: Unrecognised escape sequence '\w'
This commit escapes the backslash so that the manifest contains:
regsubst("Cersei","Cer(\\w)ei","Daenery\\1")
This eliminates the warning, while continuing to verify that the
regsubst function returns `Daenerys`.

(maint) Relax fqdn_rand regex

---

lib/puppet/application/lookup.rb

The setup of the puppet lookup application performed a full master
config/setup process. This is not necessary and this commit removes
setup of the write-only node-cache and ssl configuration
that creates CA-cert.

(PUP-5644) Avoid that lookup command configures node cache and ssl

---

lib/puppet/application/lookup.rb
spec/fixtures/unit/application/environments/production/data/common.yaml
spec/fixtures/unit/application/environments/production/manifests/site.pp
spec/fixtures/unit/application/environments/puppet_func_provider/environment.conf
spec/fixtures/unit/application/environments/puppet_func_provider/functions/data.pp
spec/fixtures/unit/application/environments/puppet_func_provider/manifests/site.pp
spec/unit/application/lookup_spec.rb

Prior to this commit, the `lookup` application would compile a full
catalog which gave undesired side effects. This commit ensures that
this compilation does not take place unless the flag `--compile` is
given on the command line. Without this option, the lookup command will
instead compile the string `undef` to produce the scope needed
for the lookup.

(PUP-5461) Prevent that lookup evaluates site manifest

---

api/docs/http_certificate.md
api/docs/http_certificate_request.md
api/docs/http_certificate_revocation_list.md
api/docs/http_certificate_status.md
api/docs/http_status.md

The status endpoint docs stated the environment was ignored, but Puppet
validates it and will fail if it doesn't match a real environment.

(docs) Clarify behavior of environment for /puppet/v3/status and /puppet-ca/v1

---

acceptance/tests/parser_functions/calling_all_functions.rb

Previous versions of this test overrode the expectation for the split()
function when puppet_version was deemed to be 3.x. This failed in the
3.x job with future parser turned on.  The override has been removed as
it was confusing and the single regex now works for both 3.x jobs and
4.x jobs.
[skip ci]

(maint) acceptance: fix calling all functions-split regex

---

lib/puppet/provider/service/upstart.rb
spec/unit/provider/service/upstart_spec.rb

As requested by @baurmatt (I believe), here's a PR to backport the fix for PUP-1293 to `3.x`.

(PUP-1293) Don't ignore status when using upstart provider

---

.travis.yml

In the run up to the 2.3.0 release, .travis.yml was
configured to test against ruby-head. Now that 2.3.0 has
been released, this commit just replaces ruby-head testing
with 2.3.0 testing. (The commits in support of ruby 2.3 went
in earlier.)
Note that we won't continue to test against ruby-head for now.
Instead, next year around this time, we can enable ruby-head
again in the run up to next year's Dec 25 ruby release.

(maint) Bump travis matrix to ruby 2.3.0

---

spec/unit/indirector/indirection_spec.rb

This is followup to PUP-4758, which cleaned up a ton of these.

(maint) Fix an rspec warning re a bare raise_error

---

lib/puppet/pops/issues.rb
lib/puppet/pops/model/model_label_provider.rb
lib/puppet/pops/validation/checker4_0.rb
spec/unit/pops/validator/validator_spec.rb

A function many not be nested in any type of block. This commit
adds the validation necessary to assert that rule.

(PUP-5651) Prevent that functions can be defined in blocks

---

lib/puppet/pops/evaluator/access_operator.rb
lib/puppet/pops/types/type_calculator.rb
lib/puppet/pops/types/type_factory.rb
lib/puppet/pops/types/types.rb
spec/unit/pops/evaluator/access_ops_spec.rb

Numeric types like `Integer[10,0]` was allowed. This commit ensures
that an error is raised if 'to' is less than 'from' in the range.
**Important note when merging to 4.x**
The checks for to < from (here in multiple places) should NOT be
merged. In 4.x there should be only one check and it should reside
in the `PNumericType.initialize`.

(PUP-5658) Disallow numeric types with ranges where to < from

---

ext/build_defaults.yaml

The apt_host variable has been depricated in favor of
apt_signing_server. This should be used instead.

(maint) Change apt_host to apt_signing_server

---

ext/build_defaults.yaml

Ruby builds were linked against an updated version of openssl. Use those
for the windows builds.

(maint) Update ruby build for windows

---

acceptance/tests/aix/nim_package_provider.rb

This commit adds a step to the aix nim_package_provider test to
ensure that all test packages are removed prior to the other steps
in the test.
[skip ci]

(maint) Acceptance - ensure test aix packages absent

---

lib/puppet/util/windows/adsi.rb
spec/unit/provider/group/windows_adsi_spec.rb
spec/unit/provider/user/windows_adsi_spec.rb
spec/unit/util/windows/adsi_spec.rb

- In #2317 / 580a1ce, a change was introduced
to generate WinNT://<SID> style URIs.  This code was wrong.
- The check for exists? should not only verify that the WinNT:// style
moniker parses and resolves to a COM object, but also that the object
is an IADsUser / IADsGroup as appropriate.  To verify this, access the
.Class property of IADs (which IADsUser / IADsGroup inherit from) for
"User" or "Group".  While the WinNT://<SID> will resolve, it attempts
to resolve a domain rather than a user or group, and returns an IADs
with .Class set to "Domain" (even though it is not an IADsDomain).
Also ensure that sid_uri / sid_uri_safe uris are not used where they
are not applicable.
Note that IADsGroup::Add continues to use WinNT://<SID> style URIs for
users per it's documentation …

(PUP-5684) Fix Windows ADSI User / Group exists?

---

ext/build_defaults.yaml

This will update ruby 2.0.0 and 1.9.3 for windows
per CVE at: https://tickets.puppetlabs.com/browse/RE-6141

(RE-6205) updating ruby for CVE-2015-7551

---

acceptance/tests/resource/file/symbolic_modes.rb

This commit confines hosts eligible to be included in the execution
of the `resource/file/symbolic_modes` test.
It removes the master from the hosts list.
It also moves the logic to exclude windows and solaris-10 from
the body of the test and places them as confine statements at
the beginning.

(PUP-1607) Acceptance - no master in symbolic_modes

---

api/docs/http_catalog.md
api/schemas/catalog.json
lib/puppet/resource/catalog.rb
spec/unit/resource/catalog_spec.rb

Currently, every agent run generates a unique transaction_uuid which
is attached to the catalog and report after the run has finished.
This allows the catalog to be linked to a specific report. However,
in the case of running off of cached catalogs, a single catalog can
have multiple reports.
When this happens, the catalog retains its original transaction_uuid
while the new reports contain the newly generated UUID, making it
impossible to link the cached catalog to any reports except for the
very first one.
This commit adds a new `catalog_uuid` identifier to the catalog,
which will allow a single catalog to be linked to multiple reports.

(PUP-5106) Add catalog_uuid identifier to catalog

---

lib/puppet/provider/group/windows_adsi.rb
lib/puppet/provider/user/windows_adsi.rb
lib/puppet/util/windows.rb
lib/puppet/util/windows/adsi.rb
lib/puppet/util/windows/principal.rb
lib/puppet/util/windows/sid.rb
spec/integration/util/windows/principal_spec.rb
spec/integration/util/windows/security_spec.rb
spec/unit/provider/group/windows_adsi_spec.rb
spec/unit/provider/user/windows_adsi_spec.rb
spec/unit/util/windows/adsi_spec.rb
spec/unit/util/windows/sid_spec.rb

* Use Windows API directly rather than consuming win32-security gem
Still left to do:
The constants can be removed later.  I think we can get away without an acceptance test, unless someone wants to write one.  Docs are probably OK for now as well.

(PUP-5538) Rewrite SID conversions

---

benchmarks/function_loading/benchmarker.rb
benchmarks/function_loading/description
benchmarks/function_loading/puppet.conf.erb
benchmarks/function_loading/site.pp.erb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/loader/base_loader.rb

Before this the function_loading benchmark failed with a out of stack
error. This was caused by a combination of the deep recursion set up by
the benchmark, and that the rutime needs additional stack levels per
call.
The benchmark logic also had flaws that had gone undetected in older
puppet versions. Now with stricter module visibility rules the benchmark
generated modules did not have the correct deendencies in meta data.
This changes the recursion to not go as deep and fixes the module
dependency problems. The number of runs/modules/funcions were also
lowered to reduce the running time of the benchmark as he additional
iterations does not provide more information.
One problem remains - each iteration takes about 25% longer than the
previous. There could be a natural explanatoin for …

(PUP-5693) Make function_loading benchmark operational

---

lib/puppet/agent.rb
lib/puppet/application/apply.rb
lib/puppet/util/locker.rb
spec/integration/application/apply_spec.rb
spec/unit/agent/disabler_spec.rb
spec/unit/agent_spec.rb
spec/unit/application/apply_spec.rb
spec/unit/util/locker_spec.rb

Use a filesytem lock when running Puppet apply. This prevents multiple
simultaneous writes to the same state files by multiple apply processes
or a mix of apply and agent processes (the same state files are shared
by apply and agent).

(PUP-5609) Protect shared state with filesystem lock

---

lib/puppet/util/windows/principal.rb
spec/integration/util/windows/principal_spec.rb

- Previously, the Puppet::Util::Windows::SID::Principal initializer
didn't understand that an account may be passed in with a domain
prefix that should be parsed off when building the domain_account
value.
When calling:
Puppet::Util::Windows::SID::Principal.lookup_account_name('NT AUTHORITY\\SYSTEM')
account was previously set to 'NT AUTHORITY\\SYSTEM' and
domain_account to 'NT AUTHORITY\\NT AUTHORITY\\SYSTEM'
This commit changes account to 'SYSTEM' and
domain_account to 'NT AUTHORITY\\SYSTEM' in the above instance

(PUP-5538) Fix SID::Principal domain_account

---

lib/puppet/indirector/json.rb
spec/unit/indirector/json_spec.rb

Previously, puppet would attempt to treat JSON read from a cached
catalog as part of the system encoding. This could cause oddities with
how inlined file content is treated.
With this change, catalogs on disk will be treated as ASCII-8BIT. This
essentially tells Ruby to just treat it as a bunch of bytes,
preserving file content and avoiding any encoding issues.

(PUP-5584) Force ASCII-8BIT encoding for cached catalogs

---

benchmarks/evaluations/benchmarker.rb
lib/puppet/parser/resource.rb
lib/puppet/parser/scope.rb
lib/puppet/pops/evaluator/closure.rb
lib/puppet/pops/evaluator/epp_evaluator.rb
lib/puppet/pops/evaluator/evaluator_impl.rb
lib/puppet/pops/evaluator/runtime3_support.rb
lib/puppet/pops/issues.rb
lib/puppet/pops/validation/checker4_0.rb
lib/puppet/resource/type.rb
spec/integration/parser/parameter_defaults_spec.rb
spec/unit/functions/epp_spec.rb
spec/unit/parser/scope_spec.rb
spec/unit/pops/evaluator/evaluating_parser_spec.rb
spec/unit/pops/evaluator/evaluator_rspec_helper.rb
spec/unit/pops/validator/validator_spec.rb
spec/unit/resource/type_spec.rb

This commit ensures that a correct scope is used when evaluating
parameter default expressions. It impacts the parameter declarations
of functions, EPP templates, classes, and resources.
A new ephemeral scope `ParameterScope` was added to keep track of
which parameters that exists and in which order they are evaluated
and accessed. This scope is only in effect during the evaluation
of the parameter defaults. Since the parameters are evaluated left
to right, and each parameter is added to the scope, a default
expression of a parameter can use the parameters declared to the
left.
Each parameter in turn is evaluated using a private MatchScope to
ensure that the evaluation of one parameter cannot interfere with
another. No LocalScope is pushed though, since it's forbidden
to assign new …

(PUP-1985) Fix correct scope for parameter default evaluation

---

ext/build_defaults.yaml

msi windows builds for puppet need to grab facter from the
github repo, so we need to bump the release tag to the newest
facter before releasing puppet

(PUP-5670) bump facter release tag

---

lib/puppet/defaults.rb
lib/puppet/environments.rb
lib/puppet/indirector/catalog/compiler.rb
lib/puppet/node/environment.rb
lib/puppet/settings/environment_conf.rb
spec/unit/environments_spec.rb
spec/unit/settings/environment_conf_spec.rb

Creates a boolean `static_catalogs` puppet setting defaulting to
false. The setting can be overridden in environment.conf, similar to
how future parser worked.
Currently the `static_catalogs` setting only modifies the compiler's
message when it compiles a catalog, e.g. "Compiled static catalog". In
the future, it will control whether the compiler inlines file metadata
into the catalog.

(PUP-5694) Add per environment static_catalogs setting

---

.travis.yml

Since we're getting a mysterious seg fault when running our spec
tests against Ruby 2.3.0, remove it from the Travis testing matrix
for now until the issue is sorted out.

(maint) Remove Ruby 2.3.0 from Travis C.I. matrix

---

api/docs/http_report.md
api/schemas/report.json
lib/puppet/configurer.rb
lib/puppet/transaction/report.rb
spec/unit/configurer_spec.rb
spec/unit/transaction/report_spec.rb

Currently, the agent run report does not provide any information
about why a cached catalog was used. This can cause issues when
a remote catalog request unexpectedly fails, causing the agent
to fall back to a cached catalog. In such a case, the report will
indicate that the run was successful without pointing out that a
cached catalog had to be used.
There are two ways a cached catalog may be used: by running the agent
with the `--use_cached_catalog` option, or by a catalog failing to
compile on the master, causing the agent to automatically fall back to
a cached catalog as long as the `usecacheonfailing` setting is set.
This commit adds the `cached_catalog_status` field to Puppet::Transaction::Report,
with possible values 'unused', 'use_cached_catalog' and
'use_cache_on_failure'.

(PUP-917) Identify in the report why a cached catalog was use
