puppetlabs/puppet

- lib/puppet/type.rb
Not sure why this require was here?
> (maint) Remove a duplicate require

- lib/puppet/provider/user/hpux.rb
- spec/unit/provider/user/hpux_spec.rb
HP-UX Trusted Computing does not change the password age when doing an
update to the password hash using /usr/sam/lbin/usermod.sam. This change
corrects that behavior and sets the password age back to 0 days old
after it has been modified.
If the HP-UX box is not running Trusted Computing, it only changes the
password.
> (PUP-3801) HP-UX Trusted Computing password age fix

- spec/unit/context/trusted_information_spec.rb
- spec/unit/ssl/certificate_factory_spec.rb
- spec/unit/ssl/certificate_spec.rb
I'm putting this up prematurely to ensure travis passes. If everything looks good, I'm going to update my commit message and add some comments in the code as to why I've done this.
> (MAINT) Fixed some tests for some OpenSSL vers

- lib/puppet/type/package.rb
When this is merged, please resolve DOCUMENT-159.
> (docs) Clarify docs for the package type's source and adminfile attributes

- ext/redhat/puppet.spec.erb
Reverts puppetlabs/puppet#3557 until the AIO pipeline is ready to go.
> Revert "(PUP-3632) Update RPM packaging spec for AIO changes"

- lib/puppet/provider/package/windows/package.rb
- lib/puppet/util/windows/api_types.rb
- lib/puppet/util/windows/registry.rb
- spec/unit/util/windows/registry_spec.rb
> (PUP-3837) FFI Registry calls to work around Ruby 2.1.5 Windows bugs

- lib/puppet/provider/yumrepo/inifile.rb
- spec/unit/provider/yumrepo/inifile_spec.rb
We merged this into master in [PR-3227](https://github.com/puppetlabs/puppet/pull/3227), and since it's a regression we need it in stable as well.
> (PUP-2916) yumrepo fails to honour custom reposdir

- lib/puppet/parser/functions/scanf.rb
- spec/unit/parser/functions/scanf_spec.rb
See https://tickets.puppetlabs.com/browse/PUP-3991
> (PUP-3991) Implement scanf function for classic parser

- acceptance/config/nodes/centos5.yaml
- acceptance/config/nodes/centos6.yaml
- acceptance/config/nodes/rhel5.yaml
- acceptance/config/nodes/rhel6.yaml
- acceptance/config/nodes/rhel6_and_rhel5.yaml
If you folks would kindly review my copy pasta
> update el nodesets for aio workarounds

- acceptance/config/nodes/rhel7.yaml
- acceptance/config/nodes/trusty.yaml
- acceptance/config/nodes/wheezy.yaml
This reverts commit 362b66d1ee312f62d878529b5a59ad8975efe03a,
and returns the agent role on the master.
> (PUP-4019) Revert "(maint) Remove the agent role on the master"

- LICENSE
This should really be automated.
> (maint) Update copyright years in LICENSE

- lib/puppet/pops/adaptable.rb
- lib/puppet/pops/binder/binder.rb
- lib/puppet/pops/binder/bindings_label_provider.rb
- lib/puppet/pops/loader/dependency_loader.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/model/ast_transformer.rb
- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/model/model_label_provider.rb
- lib/puppet/pops/model/tree_dumper.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/types.rb
- lib/puppet/pops/visitor.rb
- lib/puppet/vendor/load_rgen.rb
- lib/puppet/vendor/rgen_patch.rb
- spec/unit/pops/loaders/loaders_spec.rb
This PR contains a series of performance improvements. Each commit covers one specific improvement. The details of each improvement can be found in the commit message.
The 'Use setXXX instead of repeated addXXX ...' commit includes some changes to RGen. A PR with those changes has been submitted here: https://github.com/mthiede/rgen/pull/22
> (PUP-2929) Optimize function loader performance

- lib/puppet/provider/service/systemd.rb
- lib/puppet/type/service.rb
- spec/unit/provider/service/systemd_spec.rb
- spec/unit/type/service_spec.rb
Reverts puppetlabs/puppet#3141
> Revert "PUP-1253 Add systemd service masking support"

- lib/puppet/defaults.rb
This setting didn't have all the info you needed to use the graphing feature.
> (docs) Improve description of "graph" setting

- acceptance/lib/puppet/acceptance/install_utils.rb
Prior to this we were installing repositories for products/devel or main
(for rpms and debs respectively).
Now AIO packages will be in a repository called PC1. This adds checks to
the repository set up steps so that PC1 will be tried first. Once
packaging is fully switched over will need to remove references to older
repositories.
> (maint) Ensure AIO pre-suite uses PC1 repositories

- acceptance/tests/parser_functions/lookup.rb
This change adds merged arrays and hashes to the lookup acceptance test
from across data providers.
This implicitly tests including classes via lookup from arrays and
hashes and is not interesting to test at this layer.
> (PUP-4239) add array and hash types to lookup acceptance

- lib/puppet/pops.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/migration/migration_checker.rb
- lib/puppet/pops/parser/evaluating_parser.rb
- lib/puppet/pops/validation.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/migration_spec.rb
- spec/unit/pops/validation_spec.rb
MERGE AFTER #3738 has been merged to 3.8 to merge those changes and a revert of the functionality that should not be present on master.
> (PUP-4123) MASTER (caution) Add infrastructure for migration support

- spec/integration/type/file_spec.rb
Without this commit, the File type has no tests that verify the logs
generated when the state is changed.
Add tests that verify the logs generated when
- creating a new file
- overwriting an existing file
- removing a file
> (maint) Cover logs generated by ensure file type

- lib/puppet/version.rb
```
0 ~/work/puppet (maint/stable/update-version-4)  $ bundle exec puppet --version
4.0.0
```
> (packaging) Update PUPPETVERSION to 4.0.0

- spec/integration/type/file_spec.rb
The File resource is unevenly tested in acceptance and spec. This adds tests for the links attribute.
> (PUP-4343) Add test(s) for file resource links attribute

- acceptance/lib/puppet/acceptance/install_utils.rb
Reverts puppetlabs/puppet#3835; acceptance setup on Debian and Ubuntu were broken.
> Revert "(PUP-4044) curl directly to host in  install_repos_on"

- acceptance/lib/puppet/acceptance/install_utils.rb
Previously, we copied the puppetlabs-release package from
{yum,apt}.puppetlabs.com, the per-commit repo_config from
builds.puppetlabs.lan or nightlies.puppetlabs.com, and the actual repos
from either PC1, main or devel to the coordinator node, which then
scp'ed the files to each SUT.
This commit modifies the `install_repos_on` method to curl the
repo_config for the specified SHA to the SUT's system location e.g.
/etc/yum.repos.d. Once installed the repo_config specifies the URL from
which to install the package for the specified SHA, e.g
baseurl=http://builds.puppetlabs.lan/puppet-agent/<SHA>/repos/el/7/PC1/x86_64/
This commit also skips installing the puppetlabs-release package.
In puppet 3.x, the package is required, because it provides dependencies
for puppet, e.g. facter, hiera. In …
> (PUP-4044) Curl repo config directly to SUT

- lib/puppet/application/apply.rb
Before this all compilation errors were logged both by the compiler, and
then again by the apply application.
This splits up the error handling so that those errors that are logged
and processed by the compiler are caught and then causing an immediate
exit. Other errors (such as errors after the compiler has finished
compiling, or before being in a state where errors are rescued and
logged) are caught by the general logic at the end of the compile/apply
block.
This fix is not a guarantee there will never be duplicate output since
different compilation logic can be used (and it may not behave the same
way).
> (PUP-3814) Only log compilation errors once

- acceptance/Rakefile
- acceptance/config/nodes/debian-7-passenger.yaml
- acceptance/config/nodes/redhat-6-passenger.yaml
- acceptance/config/nodes/redhat-7-passenger.yaml
- acceptance/config/nodes/ubuntu-1204-passenger.yaml
- acceptance/config/nodes/ubuntu-1404-passenger.yaml
- acceptance/config/passenger/options.rb
- acceptance/setup/aio/pre-suite/010_Install.rb
- acceptance/setup/aio/pre-suite/015_PackageHostsPresets.rb
- acceptance/setup/passenger/pre-suite/015_PackageHostsPresets.rb
- acceptance/setup/passenger/pre-suite/030_ConfigurePassenger.rb
> (PUP-4234) Passenger package support

- lib/puppet/application/apply.rb
- spec/integration/application/apply_spec.rb
Make `puppet apply` use the ENC environment, as discussed on the dev list.
> (PUP-3341) use the proper manifest with puppet apply and ENC

- lib/puppet/provider/package/pip.rb
- lib/puppet/provider/package/pip3.rb
- spec/unit/provider/package/pip3_spec.rb
Based on Python 2 package provider (pip).
> (PUP-3480) Python 3 package provider (pip3).

- acceptance/lib/puppet/acceptance/classifier_utils.rb
Runs of PE Puppet Acceptance for 3.8.x began failing several environment
tests after the new "Production environment" group was added to the
default pe classifications in PE-8444.  This new "Production
environment" group set the production environment for all pe nodes.  The
failing environment tests were making us of the helper method
lib/puppet/acceptance/classifier_utils#create_group_for_nodes to
create test groups in the classifier setting environment for nodes
under test.  But the method was setting the parent to the default root
group, and this was causing the classifier to return a conflict error
due to two separate groups attempting to override environment for the
same nodes.
Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Failed when searching for node …
> (maint) Attach pe classifier groups to Production environment group

- acceptance/tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb
Previously, the test passed when run with a single agent node, but
failed when run with multiple agent nodes, with the error:
TypeError Exception: no implicit conversion of String into Integer
The root cause is that Beaker metaprograms methods for each role,
where the method returns either a single host or an array of hosts
with that role. And in the latter case, we were calling `['platform']`
on an array causing the TypeError.
This commit modifies the test to not assume there is a single agent.
Instead we always create unix and windows external facts on the master,
and for each agent, verify the external fact is resolved.
> (PUP-4652) Don't rely on beaker's `agent` method

- acceptance/config/nodes/ubuntu-1504-i386.yaml
- acceptance/config/nodes/ubuntu-1504-x86_64.yaml
Note: We currently aren't building packages for Vivid yet so I don't have an artifact to test these configs with. Having said that, I copied the Utopic configs and updated them, this should be a very low risk change
> (maint) Add acceptance configs for Ubuntu Vivid

- lib/puppet/provider/package/pacman.rb
- spec/unit/provider/package/pacman_spec.rb
Installing packages with pacman fails when the package is not in a
group.
This is fixed by allowing a non-zero exit code for some of the pacman calls.
> (PUP-4635) Fix pacman provider to handle failure on group queries.

- spec/unit/file_serving/configuration/parser_spec.rb
ENTERPRISE-361 reported on regression in fileserver.conf which did not
allow globbing subdomains.  Allow in
file_serving/configuration/parser.rb sets simple comma separated allows
in mount.allow, which inherits from network/authconf allow, where most
of the testing lives. This change adds tests that ensure we are sending
the correct patterns to mount.allow.
> (PUP-3539) add specs globbing ACL in fileserver.conf

- Gemfile
- spec/fixtures/vcr/cassettes/Puppet_Network_HTTP_Connection/when_methods_that_accept_a_block_are_called_with_a_block/_request_get/should_yield_to_the_block.yml
- spec/fixtures/vcr/cassettes/Puppet_Network_HTTP_Connection/when_methods_that_accept_a_block_are_called_with_a_block/_request_head/should_yield_to_the_block.yml
- spec/fixtures/vcr/cassettes/Puppet_Network_HTTP_Connection/when_methods_that_accept_a_block_are_called_with_a_block/_request_post/should_yield_to_the_block.yml
- spec/spec_helper.rb
- spec/unit/network/http/connection_spec.rb
This adds more lines than it removes, but most of them are in fixtures.
The code itself is currently about +/- 0, but future HTTP tests can be implemented with very little overhead.
> (maint) Introduce VCR to the bundle, have nicer HTTP stubbing

- api/docs/http_api_index.md
- api/docs/http_catalog.md
- api/docs/http_certificate_request.md
- api/docs/http_certificate_status.md
- api/docs/http_environments.md
- api/docs/http_file_metadata.md
- api/docs/http_node.md
- api/docs/http_report.md
- api/docs/http_resource_type.md
- api/docs/http_status.md
- api/docs/pson.md
Hey @dankreek, a note about this showed up in an otherwise unrelated docs ticket. Could you verify that this is true, and Puppet Server CA doesn't support the pluralized version of this? 
When this PR gets merged, please resolve https://tickets.puppetlabs.com/browse/DOC-864!
> (docs) Minor updates to API docs

- lib/puppet/info_service.rb
- lib/puppet/info_service/class_information_service.rb
- lib/puppet/pops/adapters.rb
- lib/puppet/pops/evaluator/literal_evaluator.rb
- spec/unit/info_service_spec.rb
- spec/unit/pops/evaluator/literal_evaluator_spec.rb
This adds a class info service to be used by node classifier. See ticket for details.
> (PUP-4819) Add class info service

- acceptance/tests/ensure_puppet-agent_paths.rb
A prior commit for PUP-4854 changed the module_working_dir setting
default on Windows, causing the acceptance test to fail. Update the
test.
> (PUP-4854) Fix acceptance for module_working_dir

- lib/puppet/type.rb
> (docs) Metaparameters: Update URL to docs about resource references

- acceptance/lib/puppet/acceptance/install_utils.rb
> (PUP-4757) added puppet-agent support for PE-only platforms

- spec/unit/file_bucket/dipper_spec.rb
The list command specs were using the path returned from `tmpfile` in
its expectations, but the filebucket returns the real paths to the file.
For OSX, `tmpfile` is returning paths under `/var/...` which is
symbolically linked to `/private/var/...`.  Thus the expectations would
not match.
The fix is to simply get the real path to the files returned from
`tmpfile` and friends.
> (maint) Fix file bucket dipper spec on OSX.

- spec/unit/indirector/file_bucket_file/file_spec.rb
The file bucket list command feature added a spec that adds three files
to the bucket and compares what is listed with Time.now.  Unfortunately,
this introduces a timing issue where TIme.now is not the same second as
the modification times of the files that were stored in the file bucket.
This results in a sporadic failure.
The fix is to simply verify that the list contents is in the expected
format with respect to the date and time.
> (maint) Fix file bucket spec timing issue.

- acceptance/tests/ticket_4622_filebucket_diff_test.rb
This commit adds an acceptance test to make sure filebucket diff
commands works with both remote and local filebuckets
> (PUP-4622) Adding acceptance test for filebucket diff command

- lib/puppet/resource/catalog.rb
- spec/integration/transaction_spec.rb
> (PUP-735) Fail when cannot apply complete catalog

- lib/puppet/functions/map.rb
- lib/puppet/functions/match.rb
- lib/puppet/parser/functions/map.rb
- lib/puppet/parser/functions/match.rb
Clarify how the `map` function works and provide more context in the
examples.
> (docs) Improve map function description.

- acceptance/tests/resource/user/should_create_with_gid.rb
- acceptance/tests/resource/user/should_modify_gid.rb
@kylog ugh one more... #4136 made me notice this was also wrong.
> (maint) Fix remaining typos in user acceptance tests

- lib/puppet/indirector/catalog/static_compiler.rb
The static compiler never removes child resources that already exist
leading to duplicate file resource declarations.
The problem is in remove_existing_resources()
The intersection between existing_names and children.keys never matches
anything because existing_names are stringified resource objects (e.g.
File['/tmp/statically_compiled/test.txt']) and children.keys are
relative path strings (e.g. 'test.txt.).
This leads to duplicate files resources and catalog subsequently failing
with an error:
`Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Duplicate declaration: File[/tmp/statically_compiled/test.txt]
is already declared in file
/etc/puppet/environments/production/modules/role/manifests/traveler.pp:27;
cannot redeclare`
This commit fixes …
> (PUP-5062) static compiler fails to remove existing resources from children

- lib/puppet/type/package.rb
When this is merged, please resolve [DOC-1170](https://tickets.puppetlabs.com/browse/DOC-1170).
> (docs) Improve description of package type's configfiles attribute

- acceptance/tests/parser_functions/lookup.rb
Modified existing test to include automatic parameter lookup of
parametrized class
> (PUP-4821) acceptance test for automatic parameter lookup

- acceptance/lib/puppet/acceptance/service_utils.rb
- acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
See PUP-4605 for additional context.
> (PUP-5024) Add acceptance test for enabling systemd-masked services

- lib/puppet/functions/filter.rb
- lib/puppet/parser/functions/filter.rb
Update to follow the `map` function revisions.
> (docs) Revise filter function docs.

- acceptance/config/nodes/aix-53-power.yaml
- acceptance/config/nodes/aix-61-power.yaml
- acceptance/config/nodes/aix-71-power.yaml
- acceptance/config/nodes/solaris-10-sparc.yaml
- acceptance/config/nodes/solaris-11-sparc.yaml
[skip-ci]
Merge after release!
> (maint) Add 'hypervisor: none' to non-provisioned node definitions

- lib/puppet/resource/status.rb
- spec/unit/transaction/report_spec.rb
> (PUP-5192) Revert psych support for Puppet::Resource::Status

- acceptance/config/nodes/ubuntu-1404-i386.yaml
- acceptance/config/nodes/ubuntu-1404-passenger.yaml
- acceptance/config/nodes/ubuntu-1404-x86_64.yaml
Reverts puppetlabs/puppet#4293
> Revert "(PUP-5001) Remove Ubuntu 14.04 acceptance node defs"

- acceptance/setup/aio/pre-suite/010_Install.rb
- acceptance/tests/resource/file/source_attribute.rb
Previously, the test required all checksum types to converge in one run.
However, ctime and mtime are sensitive to clock skew, and can require
multiple runs to converge. For example, suppose the source file's mtime
on the master is 11:00, but the agent's clock is behind at 10:00. The
agent downloads and applies a catalog, creating the file at 10:02. The
next time the agent runs it will compare its local time of 10:02 against
11:00, and decide the file is out of sync, and update it again. This
process will repeat until the file's ctime on the agent is greater than
or equal the file's ctime on the master.
This commit modifies the install step to query each host for its local
time, and does a rough calculation to determine the difference between
all hosts. Note the timestamp that beaker …
> (PUP-5272) Allow test to pass if ctime/mtime don't converge

- acceptance/tests/parser_functions/hiera_in_templates.rb
The previous version of hiera_in_templates failed when there was more
than one agent in the test because of the way the temporary directories
were created using the agent.tmpdir method.  This fixes that problem.
9/28/15
> (PUP-4695) Fixed hiera_in_templates acceptance test

- spec/unit/capability_spec.rb
This commit adds a unit test that asserts that a produced resource
depends on its producer and that a consumer depends on its consumed
resource.
> (PUP-5085) Test that produced/consumed depend on the producer/consumer

- lib/puppet/parser/compiler.rb
I was encountering this error and found it hard to understand. I think this
wording is a little closer to the intent.
> (maint) clarify node lookup failure

- acceptance/config/nodes/win10-rubyx64.yaml
- acceptance/config/nodes/win10-rubyx86.yaml
> (PUP-5189) Add beaker node defs for Win10(x86,x64)

- lib/puppet/defaults.rb
Unless I misunderstood and you actually do have to reboot your server after setting app_management = true.
> (docs) Don't refer to restarting the Puppet master as "rebooting"

- acceptance/tests/resource/service/puppet_mcollective_service_management.rb
Currently, there is a race condition when refreshing the puppet
service in Solaris. In the time that the service is restarting,
puppet sees the service as being stopped, but moments later sees
it as running. Skip the pup/mco service test in Solaris until this
can be addressed.
> (PUP-5262) Skip pup/mco service test in Solaris

- acceptance/Gemfile
- acceptance/config/aio/options.rb
- acceptance/config/nodes/cumulus-22-x86_64.yaml
- acceptance/lib/puppet/acceptance/install_utils.rb
- acceptance/setup/aio/pre-suite/020_InstallCumulusModules.rb
This commit adds conditional logic to find cumulus repo file
in order to install on cumulus.
[skip ci]
> (PUP-5448) Add cumulus install support

- lib/puppet/provider/service/src.rb
- spec/unit/provider/service/src_spec.rb
Previously when stopping a service, the AIX SRC provider would hit
the service with the stop signal via `stopsrc` and return immediately
as the service asynchronously shut down. In some cases, this would
cause a race condition if the service took a moment to actually stop.
In such cases, Puppet would became unaware of the actual state of the
service.
This is due to the asychronous nature of service management in AIX,
and the fact that state transitions are not atomic.
This commit adds a 60 second timeout when stopping services to check
that the service is actually stopped before returning. If a service
has not stopped by the end, it fails, since that may affect future
resources depending on the service being stopped.
For consistency, this commit also adds the same timeout for starting …
> (PUP-5387) Wait for services to finish state transitions in AIX

- lib/puppet/functions/scanf.rb
- lib/puppet/parser/functions/scanf.rb
updating scanf description to better align with current style guide.
@nfagerlund
> (docs) updating function descriptions - scanf (DOC-2151)

- lib/puppet/functions/slice.rb
- lib/puppet/parser/functions/slice.rb
making function descriptions more uniform, to align with our style guide.
@nfagerlund
> (docs) updating function descriptions - slice (DOC-2152)

- lib/puppet/module_tool/skeleton/templates/generator/README.md.erb
Cherry picked #4373 on top of stable.
> (PUP-5022) update generator skeleton to new README template

- lib/puppet/transaction/additional_resource_generator.rb
PUP-1963 changed resource generation such that resources were added to
the *catalog*, not just the final relationship graph. This required
the Type instances returned by the `generate` method to be converted
to Resource instances.
Unfortunately, the `to_resource` method calls `retrieve`, presumably
for the sake of the RAL. This would cause resources to be retrieved at
generation time, rather than at application time.
Instead of using `to_resource`, the additional resource generator now
constructs a Resource instance using its own logic, including only the
parameters that were used when the Type instance was created.
> (PUP-5595) Do not retrieve generated resources until they are applied

- lib/puppet/type/package.rb
https://tickets.puppetlabs.com/browse/DOCUMENT-448
> (DOCUMENT-448) Specify format for 'ensure' value when using a version.

- lib/puppet/functions/lookup.rb
- lib/puppet/parser/functions/lookup.rb
When this is merged, please resolve DOC-2225.
> (docs) Rewrite description of the lookup function

- acceptance/tests/security/cve-2013-1654_sslv2_downgrade_agent.rb
See discussion in QENG-3328 for why we went this route.
> (maint) Retry curl on name resolution failures

- acceptance/tests/parser_functions/calling_all_functions.rb
> (maint) acceptance-tighten calling_all_functions regexex for 4x

- lib/puppet/agent.rb
- lib/puppet/agent/locker.rb
- lib/puppet/application/apply.rb
- spec/integration/application/apply_spec.rb
- spec/unit/agent/disabler_spec.rb
- spec/unit/agent/locker_spec.rb
- spec/unit/agent_spec.rb
- spec/unit/application/apply_spec.rb
Reverts puppetlabs/puppet#4501
> Revert "(PUP-5609) Protect shared state with filesystem lock"

- lib/puppet/resource/capability_finder.rb
- spec/unit/resource/capability_finder_spec.rb
Previously, the CapabilityFinder was using the
Puppetdb::Util::Http.action(...) method to query PuppetDB. In PuppetDB 4
however, the action() method has changed to require a new optional
argument, which breaks compatibility. At the same time, a top-level
query_puppetdb() method has been introduced which is intended to be the
public API going forward. We now check for and use the query_puppetdb()
method where it exists, falling back to the old internal action() method
when necessary.
> (PUP-5745) Use PuppetDB 4 API for querying where applicable

- spec/unit/indirector/catalog/compiler_spec.rb
Previously the checksum_value spec tests for modifying a catalog
verified that a catalog was equal to itself. Improve verification to
assert that the checksum_value properties have been set.
> (maint) Improve checksum_value spec test verification

- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- spec/integration/parser/compiler_spec.rb
Reverts puppetlabs/puppet#4620
> (PUP-5850) Revert "(PUP-5659) Validate all relationships"

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
This adds a check around replacing the resource's metadata to verify
the file is versionable (exists within the environment path tied to
the catalog's code id). Doing this at the compiler layer greatly
simplifies the code compared to trying to forward all the needed
parameters to the file server layer. This does mean we occasionally
stat a file we won't inline, but that's worth it (until we see
real-world numbers saying it's expensive) to avoid making this super
complicated.
> (PUP-5119) Only inline metadata if the source is in the environment

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
> (PUP-5897) Add systemd as a default provider on Ubuntu 16.04.

- lib/puppet/functions/type.rb
- lib/puppet/pops/parser/egrammar.ra
- lib/puppet/pops/parser/eparser.rb
- spec/unit/functions/type_spec.rb
- spec/unit/pops/parser/parse_calls_spec.rb
> (PUP-5845) Add the type function

- lib/puppet/face/parser.rb
- spec/unit/face/parser_spec.rb
> (PUP-5895) Fix puppet parser validate breaks on puppet function

- lib/puppet/resource.rb
- lib/puppet/resource/type.rb
- spec/unit/resource_spec.rb
Before this commit, a binding for a host class definition parameter
that was declared as `undef` was treated as "not found" and hence,
would yield an error if the parameter didn't receive a value some
other way.
This commit changes this so that an `undef` value found in a binding
is considered a valid parameter default. An `undef` value will however
never replace a value produced by a parameter default expression.
> (PUP-5925) Treat undef as a valid value from a binding

- acceptance/tests/language/exported_resources.rb
> (maint) acceptance-skip exported resource test on arista

- lib/puppet/util/monkey_patches.rb
I am wiping the tears off my keyboard as I type. Read the ticket for 
backstory.
> (PUP-5962) Restore monkey-patch to Symbol#<=>

- lib/puppet/defaults.rb
> (docs) Add splay example

- acceptance/tests/direct_puppet/cached_catalog_remediate_local_drift.rb
Previously, the static catalog drift remediation test created
the agent test file path using `agent.tmpdir`, which is really
an alias to `agent[0].tmpdir`. This would normally be fine,
except in the case where the agents array contains both
Linux and Windows hosts, as the temporary directories between
the two differ.
Instead, generate a new tmpfile for each agent in the agent array
and update the test file resource on the master accordingly.
> (maint) Use new tmpfile for each agent in direct puppet test

- spec/unit/indirector/catalog/compiler_spec.rb
When inlining file metadata, we sometimes hardcode the default values
for the `links` and `source_permissions` parameters to match
the real file type defaults.
This commit adds a new test case to ensure that the values we've
hardcoded actually match those defaults. Should they ever change,
this test will fail, thus notifying us that our hardcoded values
need to change.
This is being done with a test rather than retrieving the defaults
during compilation due to the fact that determining said defaults
requires instantiated file resources, which depend on knowing which
file provider to use. Creating a new dummy file resource on the
master is clunky and inelegant.
> (PUP-5959) Add test to ensure static catalog file params match defaults

- api/docs/http_catalog.md
Documents the response when requesting a static catalog from a Puppet
Server with static catalog support configured.
> (PUP-5960) Document static catalog response

- lib/puppet/provider/augeas/augeas.rb
> (maint) Fix a typo in comments: verison => version

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
Submitting this pull request to start a discussion. I have not tested this on Debian and have only spot checked this on RHEL 7 (`puppet apply -e "service { 'autofs': ensure => true }'"`).
`systemctl is-enabled` will print the following statuses to stdout:
- enabled / enabled-runtime
- linked / linked-runtime
- masked / masked-runtime
- static
- indirect
see the systemctl(1) man page for description of each
No output is generated if systemctl can't find the unit file.
The networking service is a good example of a service that has an init script but does not have a unit file. I have tested `systemctl is-enabled networking` on Debian 8.0, 8.3, Ubuntu 15.04, and Ubuntu 15.10. The output is the same on all systems.
```
$ systemctl is-enabled networking 2>/dev/null
$ systemctl is-enabled …
```
> (PUP-5825) use systemctl is-enabled to determine service enable state

- lib/puppet/pops/evaluator/closure.rb
- spec/integration/parser/parameter_defaults_spec.rb
A given argument with an undef value didn't make it all the way to
the parameter validation. An error was therefore issued that the
the parameter was missing. This commit ensures that undef values will
be propagated all the way but not override a given default.
> (PUP-6064) Fix problem with given undef and optional parameter in EPP

- lib/puppet/pops/loader/runtime3_type_loader.rb
The Runtime3Loader calls on the known_resource_types of the current
environment to find a type. That call might ultimately result in that
the loader is being updated with the queried entry. When the call
returns, the loader must therefore check if it has the entry before
it tries to store it. This commit adds that check.
> (PUP-6168) Fix problem with Runtime3Loader double updates

- lib/puppet/indirector/resource_type/parser.rb
- spec/unit/indirector/resource_type/parser_spec.rb
Add a deprecation message to the resource_types endpoint.
> (PUP-6122) Deprecate resource_types endpoint

- lib/puppet/type/file.rb
Checksum verification of new files can incorrectly fail on some filesystem
types such as GlusterFS, which causes Puppet runs to fail. This patch calls
file.fsync before performing the checksum verification, which increases
the chance that all file descriptors opened on the file will return
consistent data and allow the checksum verification to succeed.
> (PUP-6059) Perform fsync on temp file before doing checksum verification

- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/loader/base_loader.rb
- lib/puppet/pops/loader/dependency_loader.rb
- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- lib/puppet/pops/visitor.rb
- spec/lib/puppet_spec/compiler.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
This PR contains a series of commits related to internal logic in the Puppet Type system.
> (maint) Misc maint fixes related to Puppet Type system internals

- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
This PR contains some additional related to internal logic in the Puppet Type system.
> Additional maint fixes related to Puppet Type system internals

- lib/puppet/type/mount.rb
- spec/unit/type/mount_spec.rb
With this improvement, file resources will execute before their mount point is mounted and file resources will execute after their parent mount is mounted.
Continues #4824 
After moving all the changes to the mount type, I am unsure how to get Puppet to traverse unknown child paths of a mount point, unless it is working from the file resources themselves and ascending to find mount points. I am sure the mimicked code I put in will not actually work correctly.
Changed up the spec test for everything being in mount, but still expecting the file resources to not be generated correctly.
> (PUP-6099) add additional autorequires for file/mount interactions

- acceptance/Rakefile
> (maint) Restrict quick test to omit trying to test removed tests

- api/docs/http_report.md
- api/schemas/report.json
- lib/puppet/transaction/report.rb
- spec/unit/transaction/report_spec.rb
PE needs an exact info about noop puppet run. The proposed solution seems to be the easiest way to implement it. However, it can have consequences I'm not aware of. Please, provide feedback.
This problem is reported as https://tickets.puppetlabs.com/browse/PUP-6294.
Intention of this PR is to open discussion about this problem and the proper implementation - marking as Blocked.
> (PUP-6294) Indicate noop run mode in puppet report

- lib/puppet/application/apply.rb
- spec/integration/application/apply_spec.rb
[PUP-6269](https://tickets.puppetlabs.com/browse/PUP-6269) backporting fix from [PUP-3341](https://tickets.puppetlabs.com/browse/PUP-3341) to 3.x branch
> (PUP-6269) Backport PUP-3341 to 3.x

- acceptance/tests/resource/scheduled_task/should_modify.rb
- lib/puppet/util/windows/taskscheduler.rb
- spec/unit/provider/scheduled_task/win32_taskscheduler_spec.rb
Supercedes #5012 and #5028, retargets at stable.
> (PUP-3768) Address Win32::TaskScheduler idempotency issues

- acceptance/tests/resource/scheduled_task/should_modify.rb
- lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
- lib/puppet/util/windows/taskscheduler.rb
- spec/unit/provider/scheduled_task/win32_taskscheduler_spec.rb
> (PUP-5269) Fix scheduled_task name comparisons (Unicode + case)

- lib/puppet/provider/service/smf.rb
- spec/unit/provider/service/smf_spec.rb
The restartcmd in smf.rb needs to add the -s flag to make
sure that service restarts are synchronous. Without this
patch smf will return prior to the completion of the restart.
(PUP-6238) Serivce SMF should set has_feature :refreshable
SMF supports the concept of restart instead of calling start/stop
on each service. This patch informs the higher level service
provider of that capability.
> (PUP-6233) Serivce SMF restart should use -s

- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/parser/locator.rb
- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/p_sem_ver_type.rb
- lib/puppet/pops/types/puppet_object.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_formatter_spec.rb
Details in the commit comments.
> (maint) Minor fixes found when working on serialization

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
The ideas from this are working as an extracted T/P: https://github.com/petems/petems-systemd_logs
Error before:
> Error: Could not start Service[foo]: Execution of '/usr/bin/systemctl start foo' returned 6: Failed to start foo.service: Unit foo.service failed to load: Invalid argument. See system logs and 'systemctl status foo.service' for details.
Error after:
> Error: Systemd start for foo failed:journalctl log for foo: -- Logs begin at Mon 2016-06-20 12:07:17 UTC, end at Mon 2016-06-20 12:08:06 UTC. --
Jun 20 12:08:06 centos-7-x64 systemd[1]: foo.service lacks both ExecStart= and ExecStop= setting. Refusing.
Jun 20 12:08:06 centos-7-x64 systemd[1]: foo.service lacks both ExecStart= and ExecStop= setting. Refusing.
> (PUP-5604) Journald on failure in Systemd

- lib/puppet/indirector/catalog/static_compiler.rb
As discussed in [PUP-6415](https://tickets.puppetlabs.com/browse/PUP-6415). My grasp of Ruby is unfortunately not good enough to be able to write a test that covers this - I have tried!
> (PUP-6415) static_compiler: fix symlinks in recursed directories

- acceptance/tests/resource/service/service_enable_linux.rb
This commit removes the pinned run order of the expected symlinks
created for the services in the `service_enable_linux` acceptance
test.
Prior to this commit, SUSE Enterprise Linux instances on s390x were
failing this test when the generated run order did not equal the
statically defined number.
[skip-ci]
> (PUP-6390) Unpin run order for service symlinks

- acceptance/tests/reports/failover_master.rb
Still trying to get a build through Jenkins, but these did all pass with a slightly outdated build (from right before Branan's work got merged).
In the meantime, I'll just put these up for review.
> (PUP-6383) Failover report acceptance

- lib/puppet/transaction/report.rb
This will make it easier to spec test from PuppetDB.
> (maint) change noop_pending in transaction/report.rb to attr_accessor

- lib/puppet/property.rb
- lib/puppet/transaction/resource_harness.rb
- lib/puppet/type.rb
- lib/puppet/type/file.rb
- spec/unit/type/file_spec.rb
- spec/unit/type_spec.rb
Depends on https://github.com/puppetlabs/puppet/pull/5141.
> (PUP-6439) Retain sensitive context from resources to RAL properties

- spec/unit/parser/functions/create_resources_spec.rb
This adds a spec test that asserts that create_resources writes
file/line information to all resources created by the call.
The file/line information is the file/line of the call expression.
The implementation of the behavior was merged in PUP-5948 as it adds the
logic required to compute the location, and a refactoring made all code
that creates resources follow one and the same logical path. The issue
PUP-6530 was fixed as a side effect (but no tests were then added for
this problem).
> (PUP-6530) Add spec test that create_resources write file/line info

- acceptance/tests/reports/corrective_change_new_resource.rb
Thie commit adds new acceptance test for corrective_change flag
[skip ci]
> (PUP-6295) Acceptance test for corrective_change flag

- lib/puppet/parser/scope.rb
- spec/integration/parser/compiler_spec.rb
Fix for camel cased classnames not working.
> (PUP-6574) Handle camel case class names

- lib/puppet/transaction/persistence.rb
- spec/unit/transaction/persistence_spec.rb
This adds better testing for the corruption case, and stops the system from
hard failing if it has to do a rename.
> (PUP-6629) Tighten up corruption handling for transactionstorefile

- lib/puppet/node/environment.rb
- lib/puppet/pops/loaders.rb
- spec/fixtures/unit/pops/loaders/loaders/no_modules/manifests/site.pp
- spec/unit/face/parser_spec.rb
- spec/unit/pops/loaders/loaders_spec.rb
This PR adds environment caching of loaders as this was made possible by earlier work on the same ticket.
> (PUP-6582) cache loaders

- api/docs/http_resource_type.md
Supports [DOC-2646](https://tickets.puppetlabs.com/browse/DOC-2646) and resolves [DOC-2892](https://tickets.puppetlabs.com/browse/DOC-2892).
> (docs) Add deprecation note to resource_types.

- acceptance/tests/environment/variables_refreshed_each_compilation.rb
> (PUP-6604) acceptance: compilation should get new variable values each time

- Rakefile
On PR https://github.com/puppetlabs/puppet/pull/5280 against puppet, the travis
CI commit check is failing because a prior commit unrelated to that PR be753a4
did not adhere to the commit guidelines and the underlying check code lists
commits unreachable from master to HEAD of the PR. This commit adjust this to
be stable, and this PR is intended for the stable branch only. On merge up to
master, the commit should be taken but master's version of this change
accepted (for example by doing git merge --no-commit, checking out master's version, and proceeding)
> (maint) Adjust rake commit check for stable

- lib/puppet/parser/compiler.rb
- lib/puppet/resource/type.rb
- spec/unit/capability_spec.rb
Reverts puppetlabs/puppet#5184
> Revert "(PUP-6087) Error when a capability mapping is redefined."

- acceptance/tests/parser_functions/calling_all_functions.rb
> (PUP-6755) acceptance: strftime function

- lib/puppet/parser/functions/then.rb
- lib/puppet/type/ssh_authorized_key.rb
Two docs issues. 
When this is merged, please resolve [DOCUMENT-581](https://tickets.puppetlabs.com/browse/DOCUMENT-581), as well as the PUP ticket cited in the commit messages below. 
Lemme know if I should be targeting a different branch to accommodate release timing or whatevs.
> Sep2016 doc fixes

- lib/puppet/resource/capability_finder.rb
- spec/unit/resource/capability_finder_spec.rb
Previously the capability finder would only search inside the
environment of the current catalog for capability resources to consume.
Now the capability finder will first search for a matching capability
across all environments and only limit it's search to a single
environment if a conflict is found. This allows users to test new code
on part of an application by moving nodes into a different environment
as long as they use globally unique capability titles.
> (PUP-6789) Allow capabilties to be consumed across environments.

- acceptance/tests/language/binary_data_type.rb
- acceptance/tests/language/sensitive_data_type.rb
> (PUP-6778) acceptance: Binary Type

- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/types_spec.rb
This maint commit fixes some minor issues that was found while browsing
through the code.
> (maint) Fix some minor pcore type related issues

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
The Puppet lookup explanations changed wording slightly as a result of the
changes introduced in PUP-6780. This commit adjusts the acceptance tests
accordingly.
> (PUP-6933) Change acceptance test to accept new explanations

- lib/puppet/ssl/host.rb
- When the agents public key does not match what's in the CSR
generate a message for the user.
> (PUP-6918) Propagate error with CSR mismatch

- spec/unit/file_system_spec.rb
Prior to this commit, a test in file_system_spec.rb would assert an expected
default permission for a newly created file by Puppet::FileSystem, but failed
to take into account that this would vary based on umask (which varies in linux
by root vs non-root user). This commit updates the test to instead calculate
the expected permission based on the current umask.
transaction spec
> (PUP-6188) consider umask for default perms FS test

- benchmarks/catalog_memory/benchmarker.rb
- lib/puppet/interface/face_collection.rb
- lib/puppet/settings.rb
- lib/puppet/util/profiler/aggregate.rb
- spec/unit/graph/rb_tree_map_spec.rb
Eliminate the temporary array created by reverse.each.
> (PUP-6831) Change reverse.each to reverse_each

- acceptance/tests/lookup/lookup_rich_values.rb
* previous commits did not use hiera v5 functionality
> (PUP-6945) acceptance: fix lookup rich data values test

- spec/unit/file_system_spec.rb
- When running specs as SYSTEM, the temp directory used is typically
C:\Windows\Temp, and when creating new files the perms should be
typically written as:
SYSTEM:(F)
Administrators:(F)
When Puppet calculates a POSIX mode, the owner is SYSTEM and the
group is Administrators, yielding a mode of 770
In some circumstances there may be another ACE on the file (as can
be the case when IIS_IUSRS has permissions to C:\Windows\Temp) and
Puppets calculated mode will include the 2 prefix which is a
sentinel value used to indicate extra aces, resulting in a mode of
2000770.
- Previously the tests assumed that tests were being run as another
user that was writing to their own isolated temp directory. Such
files are normally written as:
MACHINE\USER:(I)(F)
SYSTEM:(I)(F)
Administrators:(I)(F)
When …
> (PUP-6188) Fix SYSTEM perms for file_system_spec

- acceptance/lib/puppet/acceptance/module_utils.rb
- acceptance/tests/windows/eventlog.rb
For the full suite to pass, this also requires the fixes from:
* [BKR-1008](https://tickets.puppetlabs.com/browse/BKR-1008) - PR at https://github.com/puppetlabs/beaker/pull/1293
* [BKR-1011](https://tickets.puppetlabs.com/browse/BKR-1011) - PR at https://github.com/puppetlabs/beaker/pull/1294
> (PUP-6993) Fix acceptance tests for Japanese windows

- .gemspec
- Gemfile
- Rakefile
- ext/project_data.yaml
- install.rb
- lib/puppet.rb
- lib/puppet/face/help.rb
- locales/config.yaml
- locales/puppet.pot
This is a continuation of the work @branan started in https://github.com/puppetlabs/puppet/pull/5329. The most recent commit by me contains initial work responding to feedback on that PR.
> (PUP-6474) Incorporate gettext_setup gem in to Puppet

- acceptance/tests/lookup/lookup_rich_values.rb
put this test in with the other test because this is where we first found the issue.
this change also removes the spurious environment, and creates a hiera5 3 level hierarchy
[skip ci]
> (PUP-6997) acceptance: can put pp functions in $environment/functions

- acceptance/tests/language/objects_in_catalog.rb
> (PUP-7081) acceptance: Object types in catalog

- spec/unit/provider/scheduled_task/win32_taskscheduler_spec.rb
- When run concurrently, there may be file sharing issues when using
the task scheduler APIs that prevent a task deletion from
succeeding with an error like:
Failed to call
with HRESULT: -2147024864.:  The process cannot access the file
because it is being used by another process.
- Introduce a task deletion helper that retries up to 3 times with
a 1 second delay in between attempts, in an effort to clean up
tasks under such circumstances
> (PUP-7079) Retry scheduled task deletion in specs

- acceptance/tests/lookup/v3_config_and_data.rb
- acceptance/tests/lookup/v4_hieradata_with_v5_configs.rb
> (PUP-6811) acceptance tests for puppet server hocon vendoring

- acceptance/tests/utf8/utf8-in-file-resource.rb
This PR adds a new accecptance test to verify correct behavior of
file resources when they include utf-8 characters.
> (PUP-7117) New acceptance test: utf-8 characters in file resource

- acceptance/tests/utf8/utf8-in-function-args.rb
This PR adds a new acceptance test to verify correct behavior
when utf-8 characters are in arguments to puppet functions.
> (PUP-7118) New Acceptance test: utf-8 characters in function args

- lib/puppet/version.rb
In anticipation of an upcoming bug-fix release.
> (maint) update version.rb for 4.9.1

- lib/puppet/version.rb
In anticipation of an upcoming feature release.
> (maint) update version.rb for 5.0

- lib/puppet/provider/selmodule/semodule.rb
- Previously SELinux modules were parsed by using the Ruby File.new API
without specifying 'binary' mode, nor using Ruby block form.
- Update the code to use Puppet::FileSystem and to specify its a
binary read.  Further, use the block format of the call to close
the file handle as soon its done being read
> (PUP-7151) Read selinux module version as BINARY

- acceptance/lib/puppet/acceptance/temp_file_utils.rb
- acceptance/tests/lookup/hiera3_custom_backend.rb
* acceptance test of a custom hiera backend in hiera v5
[skip ci]
> (pup-7091) acceptance: hiera v3 custom backends

- lib/puppet/pops/lookup/global_data_provider.rb
- spec/unit/functions/hiera_spec.rb
Hiera 3 would fail if a key containing unquoted dots was used in a call
to `hiera_array`, `hiera_hash` or `hiera_include`. This commit reinstates
that failure to ensure backward compatibility.
> (PUP-7366) Fail when hiera_xxx methods are called with dotted key

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
* a few spelling changes in puppet lookup --explain output needed
updating in this test
> (maint) fix puppet_lookup_cmd acceptance after upstream changes

- lib/puppet/indirector/file_bucket_file/file.rb
- spec/unit/indirector/file_bucket_file/file_spec.rb
If Puppet receives a file to back up in filebucket that has the same checksum
as an existing backed up file, Puppet will detect this, validate that the
files are indeed identical by comparing size and content, and if so use the
existing backup for the new file.
If Puppet detects that the existing backup and the new file are NOT the same,
it will fail with an error "Got passed new contents for sum <shared checksum
value>". Originally, this somewhat opaque error was only expected to only be
raised in the event of an sum collision, which was expected to be very unlikely
and infrequent.
However, in practice, a filebucket contents_file can accidentally vary from its
expected state (and check sum value) a number of ways - for example, if puppet
unexpectedly fails during the backup write but has …
> (PUP-1334) overwrite corrupted contents_file in filebucket

- lib/puppet.rb
- lib/puppet/type/zpool.rb
This commit marks user-facing strings for translation in a couple of
files, chosen more or less at random as a way to test the workflow.
> (PUP-7042) Mark strings in puppet.rb and lib/puppet/type/zpool.rb

- .travis.yml
- Gemfile
This must be merged prior to #5779
> (maint) Update TravisCI / AppVeyor config

- lib/puppet/face/ca.rb
- lib/puppet/face/catalog/select.rb
- lib/puppet/face/certificate.rb
- lib/puppet/face/config.rb
- lib/puppet/face/epp.rb
- lib/puppet/face/facts.rb
- lib/puppet/face/file.rb
- lib/puppet/face/file/download.rb
- lib/puppet/face/file/store.rb
- lib/puppet/face/generate.rb
- lib/puppet/face/help.rb
- lib/puppet/face/key.rb
- lib/puppet/face/man.rb
- lib/puppet/face/module.rb
- lib/puppet/face/module/build.rb
- lib/puppet/face/module/changes.rb
- lib/puppet/face/module/generate.rb
- lib/puppet/face/module/install.rb
- lib/puppet/face/module/list.rb
- lib/puppet/face/module/search.rb
- lib/puppet/face/module/uninstall.rb
- lib/puppet/face/module/upgrade.rb
- lib/puppet/face/node.rb
- lib/puppet/face/node/clean.rb
- lib/puppet/face/parser.rb
- lib/puppet/face/plugin.rb
- lib/puppet/face/report.rb
- lib/puppet/face/resource.rb
- lib/puppet/face/resource_type.rb
- lib/puppet/face/status.rb
`lib/puppet/face.rb` and `lib/puppet/face/*` for translation.
> (PUP-7042) Mark strings in face

- lib/puppet/defaults.rb
When this is merged, please resolve [DOC-2939](https://tickets.puppetlabs.com/browse/DOC-2939).
> (docs) Explain what node_terminus setting does; clarify external_nodes setting

- lib/puppet/parser/compiler.rb
- lib/puppet/parser/scope.rb
- lib/puppet/resource/type.rb
- spec/integration/parser/scope_spec.rb
- spec/unit/parser/resource_spec.rb
- spec/unit/parser/scope_spec.rb
- spec/unit/pops/evaluator/evaluator_rspec_helper.rb
- spec/unit/resource/type_spec.rb
> (PUP-5635) Prevent qualified var access from becoming locally resolved

- lib/puppet/parser/functions/create_resources.rb
- spec/lib/puppet_spec/compiler.rb
- spec/unit/parser/functions/create_resources_spec.rb
> (PUP-6698) Create resources and exported resource not working

- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/issues.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
> (PUP-1795) Warn when numeric auto convert takes place

- lib/puppet/util/log.rb
We've decided to keep this so let's not say it should be removed soon.
> (PUP-7502) clarify Puppet::Log alias comment

- acceptance/tests/resource/cron/should_allow_changing_parameters.rb
- acceptance/tests/resource/package/yum.rb
- lib/puppet/type/cron.rb
This PR fixes some problems that were encountered when running the acceptance tests with the changes introduced by PUP-7616.
> (PUP-7616) Fix problems encountered in acceptance tests

- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- spec/integration/parser/compiler_spec.rb
> (PUP-7660) Virtual resources should not have relationships validated

- lib/puppet/version.rb
Update the puppet reported version to 4.10.3 for agent 1.10.3 release
> (PUP-7666) Update puppet version to 4.10.3

- api/schemas/catalog.json
- Update regex to coincide with code changes made in
2ac4dc0395e08a603e97698de82833d388095c70
> (PUP-7579) Update API documentation for tags

- acceptance/tests/resource/ssh_authorized_key/create.rb
- acceptance/tests/resource/ssh_authorized_key/destroy.rb
- acceptance/tests/resource/ssh_authorized_key/modify.rb
In the past we assumed that this user logged in would be root.
Since this is not always the case, this has been fixed.
> (PUP-7599) Acceptance: Fix authorized keys tests

- lib/puppet/pops/types/p_init_type.rb
- spec/unit/pops/types/p_init_type_spec.rb
This commit fixes several bugs in the implementation of `Init[T]`
and adds tests to ensure 100% code coverage.
> (PUP-7277) Fix bugs in the implementation of Init[T] and add tests

- acceptance/Gemfile
- acceptance/tests/loader/autoload_from_resource_type_decl.rb
- acceptance/tests/loader/resource_triggers_autoload.rb
Resource type statement triggered auto-loading works both with and without generated types
Can auto-load defined types using a Resource statement
> (PUP-7680) add autoloader tests for resource types

- lib/puppet.rb
- spec/unit/puppet_spec.rb
> (PUP-7766) Ensure that --modulepath is propagated to static environment

- spec/unit/file_bucket/dipper_spec.rb
dipper_spec assumes gnu diff AND executes diff via ``s
notably this fails on Solaris but may also fail on other platforms.
On Solaris 11+ dipper_spec now invokes 'gdiff' and on all platforms
uses Puppet::Util::Execution.execute which causes the test to fail
if diff cannot be executed.
> (PUP-6756) Puppet::FileBucket::Dipper specs fail silently

- acceptance/tests/catalog_with_binary_data.rb
This is a follow-on from #6031 to apply the same changes to
- acceptance/tests/catalog_with_binary_data.rb &
- acceptance/tests/direct_puppet/supports_utf8.rb
Otherwise these tests fail with a similar error.
> (PUP-7521) Fix further FQDN Test Errors

- lib/puppet/version.rb
For the upcoming agent 1.10.6 release
> (packaging) Update puppet's version to 4.10.6

- acceptance/Gemfile
- acceptance/tests/loader/autoload_from_resource_type_decl.rb
- lib/puppet/indirector/request.rb
- lib/puppet/pops/types/string_converter.rb
- lib/puppet/util/windows/api_types.rb
- lib/puppet/util/windows/process.rb
- spec/integration/util/windows/process_spec.rb
- spec/unit/indirector/request_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/util/windows/api_types_spec.rb
Merge 5.0.x into master
Parent(s):	fa35667f1e 0e7936de19
Due to merge conflict in locales.pot, raising a PR instead of a normal merge and push.
> (maint) Merge 5.0.x into master

- lib/puppet/functions/epp.rb
- lib/puppet/parser/functions/epp.rb
Add a short note about absolute paths.
> (docs) add a note to epp about loading any file with absolute path

- lib/puppet/pops/types/p_object_type.rb
- spec/unit/pops/types/p_object_type_spec.rb
This commit adds a new member `constants` the `Object` type. The
`constants` member is similar to the `attributes` member in that its
value is a hash of attributes. The specification of each attribute under
`constants` is however only a value. It's type is inferred from this
value and the kind is always 'constant'.
Overrides are automatically allowed if the parent attribute is also a
constant with a type that is assignable from the overriding type.
> (PUP-7852) Add attribute 'constants' to the Object type description

- lib/puppet/feature/bolt.rb
- lib/puppet/functions/run_task.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/types/task.rb
- spec/unit/functions/run_task_spec.rb
Run tasks using the bolt executor
> (PUP-7875) Use bolt to execute tasks in run_task

- spec/unit/type/scheduled_task_spec.rb
Added some tests that had not been implemented around "enable".
> (PUP-7884) Added tests to describe block that had no tests.

- .gemspec
- acceptance/tests/i18n/check_puppet_run_message.rb
- acceptance/tests/i18n/translation_fallback.rb
- acceptance/tests/resource/file/symbolic_modes.rb
- lib/puppet/version.rb
This PR merges 5.3.x to master with the exception of the following commit which results in a parser conflict which needs to be resolved.
https://github.com/puppetlabs/puppet/commit/f770758042505a66ce30a0442da8b9db40545f0f
> Merge up 5.3.x -> master

- lib/puppet/agent/locker.rb
- lib/puppet/face/catalog/select.rb
- lib/puppet/face/help.rb
- lib/puppet/face/man.rb
- lib/puppet/face/node.rb
- lib/puppet/face/plugin.rb
- lib/puppet/face/status.rb
- lib/puppet/forge/errors.rb
- lib/puppet/module_tool/errors/installer.rb
- lib/puppet/ssl/host.rb
This reverts the HEREDOC changes in commit a266796.
> (maint) Restore heredoc i18n

- .gemspec
- acceptance/tests/loader/autoload_from_resource_type_decl.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/pops/loader/puppet_resource_type_impl_instantiator.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/ssl/certificate_revocation_list.rb
- lib/puppet/version.rb
- locales/puppet.pot
@Magisus @MosesMendoza is this how it's done (merging up) in Agent? I think we want to get @adrienthebo 's CI fix into master soon?
> Merge up '5.3.x' to 'master'

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This commit ensures that the Puppet::Pal API adds the lib directory of
the modules on the module path to the Ruby $LOAD_PATH.
> (PUP-8007) Ensure that modules lib dir are on the Ruby load path

- acceptance/tests/i18n/check_puppet_run_message.rb
> (PUP-8009) Fix incorrectly labeled pending_test

- spec/unit/pops/types/task_spec.rb
This commit adds more tests to verify that the task metadata conforms
to specification.
> (PUP-8043) Add test that verifies task metadata.

- lib/puppet/provider/zfs/zfs.rb
- spec/unit/provider/zfs/zfs_spec.rb
This is https://github.com/puppetlabs/puppet/pull/6114, with an extra test commit added. See that PR for original context.
> (PUP-7672) zoned property is called jailed on FreeBSD.

- lib/puppet/util/selinux.rb
- spec/unit/util/selinux_spec.rb
Cherry-pick of https://github.com/puppetlabs/puppet/pull/6278 targeting 4.10.x
> (PUP-2169) Invalidate SELinux matchpathcon cache

- lib/puppet/provider/user/aix.rb
- lib/puppet/provider/user/user_role_add.rb
- lib/puppet/provider/user/useradd.rb
- lib/puppet/type/user.rb
- spec/unit/provider/user/user_role_add_spec.rb
- spec/unit/provider/user/useradd_spec.rb
- spec/unit/type/user_spec.rb
some of the spec tests for useradd are not working for me, all tests I've modified work though
> (PUP-7292) Change to allow set of password_warn_days

- lib/puppet/util/log/destinations.rb
- spec/unit/util/log/destinations_spec.rb
This works, and so do the tests now!
> (PUP-7153) truncate extremely long messages for windows

- lib/puppet/forge.rb
- lib/puppet/forge/repository.rb
- spec/unit/forge/forge_spec.rb
- spec/unit/forge_spec.rb
See discussion on https://github.com/puppetlabs/puppet/pull/6287
> (PUP-8008) Fix bugs with PMT traversing multiple pages of Forge API results

- lib/puppet/indirector/catalog/compiler.rb
Merge 2 messages to make translation better
> (PUP-8029) merge 2 messages for translation

- lib/puppet/util/selinux.rb
- spec/unit/util/selinux_spec.rb
This reverts commit 0b142e7f69fe34ec0e27a339661f4acb8074afa1.
> Revert "(PUP-2169) Invalidate SELinux matchpathcon cache"

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
Before this it was only possible to either give a complete modulepath,
or to use the modulepath configured for an env.
This commit makes it possible to add to the modulepath by prepending
entries from a `pre_modulepath`, and append from a `post_modulepath`.
> (PUP-8086) Make it possible to prepend and append to modulepath in PAL

- .rubocop.yml
- Gemfile
Add the rubocop-i18n cops and turn on checking for interpolation
strings "#{}" inside of decorated strings
> (PUP-7954) add rubocop-i18n and turn on interpolation checking

- lib/puppet/functions/file_upload.rb
- lib/puppet/functions/run_command.rb
- lib/puppet/functions/run_script.rb
- lib/puppet/functions/run_task.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/types/type_factory.rb
- spec/unit/functions/file_upload_spec.rb
- spec/unit/functions/run_command_spec.rb
- spec/unit/functions/run_script_spec.rb
- spec/unit/functions/run_task_spec.rb
This PR contains the addition of a new `Target` data type.
> (PUP-8020) Add Target data type

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This refactors the PAL API while keeping backwards compatibility.
> (PUP-8102) Add call function to pal api (and much more)

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
Before this, when evaluating a string, file, or Program AST, the
evaluation method did not instantiate any definitions (functions, plans,
etc). This was bad because it is useful to be able to both define and
evaluate at the same time.
This is now fixed such that all evaluating methods instantiates the
definitiosn if asked to evaluate a Program. If evaluating arbitrary ast
(not a program) the definitions are not evaluated.
> (PUP-8185) Make the PAL evaluating method instantiate definitions

- README.md
Add badges for appveyor and gem version. Switch to svg over png for the
badge images as Travis' png looks pretty terrible.
> (maint) Add appveyor and gem version badges

- lib/puppet/face/config.rb
- spec/unit/face/config_spec.rb
Sort puppet config output based on the key.
> (PUP-3807) Sort puppet config output

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This commit adds logic to yield a text to provided block in case a
mismatch is detected when calling `TaskSignature#runnable_with?`.
> (PUP-8221) Ensure that TaskSignature#runnable_with? yields on error

- .rubocop.yml
- lib/puppet/provider/selmodule/semodule.rb
- spec/unit/provider/selmodule_spec.rb
list command executed and error message when selinux module load raises an exception
> (PUP-7948) list error message when selinux module load raises an exception

- lib/puppet/application/filebucket.rb
- spec/unit/application/filebucket_spec.rb
Prior to this commit, the filebucket app would ignore server_list if a
user had set it. It would only honor server. This commit updates
filebucket to take the first entry from server_list if set, otherwise
take server.
> (PUP-6823) Filebucket should evaluate server_list

- lib/puppet/type/k5login.rb
- spec/unit/type/k5login_spec.rb
This is an attempt to get PUP-4403 resolved.
Step 1, get the selinux bits (that are really really biting me) fixed.
Step 2, get the owner bits (that are biting me) fixed.
> PUP-4403 - k5login selinux/owner

- acceptance/tests/resource/service/service_enable_linux.rb
- lib/puppet/provider/service/systemd.rb
- lib/puppet/provider/service/upstart.rb
- spec/unit/provider/service/systemd_spec.rb
I've built and tested this on a pre-release of Amazon Linux v2 for basic validation.
> Amazon Linux v2 Support

- lib/puppet/face/help.rb
- lib/puppet/face/man.rb
- lib/puppet/face/node.rb
- lib/puppet/face/status.rb
- lib/puppet/forge/errors.rb
- lib/puppet/graph/simple_graph.rb
- lib/puppet/module_tool/errors/installer.rb
- lib/puppet/module_tool/errors/shared.rb
- lib/puppet/module_tool/errors/uninstaller.rb
- lib/puppet/module_tool/errors/upgrader.rb
- lib/puppet/parameter/value_collection.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- lib/puppet/util/log.rb
- lib/puppet/util/plist.rb
Split some of paragraphs in puppet for messages into sentences.
> (PUP-8254) split paragraphs into sentences for translation

- lib/puppet/daemon.rb
- lib/puppet/error.rb
- lib/puppet/indirector/exec.rb
- lib/puppet/indirector/facts/facter.rb
- lib/puppet/indirector/facts/network_device.rb
- lib/puppet/indirector/indirection.rb
- lib/puppet/indirector/ldap.rb
- lib/puppet/indirector/ssl_file.rb
- lib/puppet/indirector/terminus.rb
- lib/puppet/network/authstore.rb
- lib/puppet/parameter.rb
- lib/puppet/parameter/value_collection.rb
- lib/puppet/parser/ast/leaf.rb
- lib/puppet/parser/ast/node.rb
- lib/puppet/parser/compiler.rb
Decorate strings when we raise a DevError error so that we'll
have translations for the error (Part 1 of 3)
> (PUP-8313) raise DevError decorate strings part 1

- lib/puppet/parser/functions.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/label_provider.rb
- lib/puppet/pops/migration/migration_checker.rb
- lib/puppet/pops/resource/resource_type_impl.rb
- lib/puppet/pops/validation.rb
- lib/puppet/property.rb
- lib/puppet/property/ensure.rb
- lib/puppet/provider.rb
- lib/puppet/provider/ldap.rb
- lib/puppet/provider/naginator.rb
- lib/puppet/provider/nameservice.rb
- lib/puppet/provider/package/aix.rb
- lib/puppet/provider/package/pkg.rb
- lib/puppet/provider/package/yum.rb
- lib/puppet/provider/parsedfile.rb
Decorate strings when we raise a DevError error so that we'll
have translations for the error (Part 2 of 3)
> (PUP-8313) raise DevError decorate strings part 2

- spec/unit/transaction/report_spec.rb
Removed the exact same test, no other impact.
> (maint) Remove duplicate test for transaction_uuid.

- lib/hiera_puppet.rb
- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/functions/yaml_data.rb
- lib/puppet/indirector/rest.rb
- lib/puppet/interface/action_manager.rb
- lib/puppet/interface/face_collection.rb
- lib/puppet/metatype/manager.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/provider/package/pkg.rb
- lib/puppet/provider/service/launchd.rb
- lib/puppet/provider/user/openbsd.rb
- lib/puppet/settings.rb
- lib/puppet/settings/base_setting.rb
- lib/puppet/type.rb
- lib/puppet/util/instance_loader.rb
- lib/puppet/util/windows/process.rb
Added decorations for translation of Puppet.err and Puppet.warning calls
Added decorations for 'raise InterpolationError' strings
> (PUP-8312) add translations for err and warning calls

- lib/puppet/network/format.rb
- lib/puppet/provider/group/aix.rb
- lib/puppet/provider/nameservice/directoryservice.rb
- lib/puppet/provider/user/aix.rb
- lib/puppet/util/at_fork/solaris.rb
- lib/puppet/util/rdoc/generators/puppet_generator.rb
Some of the code used back slashes to continue the code on the next line in
ways that made the code less readable.
Also addressed i18n string decorations while I was there
> (PUP-8345) make back slash continuation lines more readable

- README.md
Filed Ticket indicating 2 outdated links.
Updated the affected links.
Also:
* beautified some of the sentences, adding commas for improved readability.
* shortened a few instances of hyperlinked text.
* fixed casing on a few phrases.
> (docs) Outdated links (2) on README.md

- lib/puppet/resource/catalog.rb
Convert the Catalog.alias() method to use the error_location()
for displaying the where the problem is
> (PUP-8340) convert alias to use error_location

- acceptance/tests/direct_puppet/supports_utf8.rb
Fix the test to use fqdn's for the hostnames so it works with amazon
Better path quoting
Check the config_version
> (PUP-8397) update supports_utf8.rb test

- lib/puppet/face/config.rb
- lib/puppet/settings/ini_file.rb
- spec/unit/face/config_spec.rb
- spec/unit/settings/ini_file_spec.rb
Add ability to delete config settings from the puppet.conf file
> (PUP-3020) add puppet config delete functionality

- lib/puppet/face/help.rb
- spec/unit/face/help_spec.rb
Added better argument handling
Updated a some error messages to be more user friendly
Fixed some I18n messages
> (PUP-8464) update puppet help to process its arguments

- README.md
minor changes improving readability
> (docs) minor changes improving readability

- lib/puppet/face/man.rb
Fixed man.erb and the man system to work correctly when generating
the 'man' manpage. Added comments explaining what has to work
and why
> (PUP-8444) fix man to work correctly for gen_manpages

- lib/puppet/parser/functions/new.rb
There was a conflict in how some headings were styled in a docs update
/cc @gguillotte Please make sure the headings still look right before we merge this.
>  Merge commit '7cce4d48a2c35f5877d8ddb49eab07f64a61266a' into 5.3.x

- lib/puppet/application/device.rb
- spec/unit/application/device_spec.rb
Added the ability to query resources via `puppet device`
> (PUP-8041) puppet device --resource

- lib/puppet/provider/group/windows_adsi.rb
- lib/puppet/provider/user/windows_adsi.rb
- lib/puppet/util/windows/adsi.rb
- lib/puppet/util/windows/principal.rb
- lib/puppet/util/windows/sid.rb
- spec/integration/util/windows/adsi_spec.rb
- spec/integration/util/windows/principal_spec.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
- spec/unit/util/windows/adsi_spec.rb
- spec/unit/util/windows/sid_spec.rb
Reverts puppetlabs/puppet#6647
My keyboard malfunctioned and inadvertently merged an in-progress PR
> Revert "(PUP-7326) Handle Windows unresolvable SIDs"

- lib/puppet/util/windows/adsi.rb
- lib/puppet/util/windows/principal.rb
- Add _() calls for localizable strings, so that it will be easier
after the next merge (which will have a few easily resolved
merge conflicts) to perform automated merge-ups
> (PUP-7326) Add ADSI / Principal localizations

- lib/puppet/type.rb
- lib/puppet/type/user.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/type/augeas_spec.rb
- spec/unit/type/file_spec.rb
- spec/unit/type/group_spec.rb
- spec/unit/type/user_spec.rb
- spec/unit/type_spec.rb
This reverts commit c98bb6787fa2ec04842a92924dd4eb8e41bddd78.
> Revert "(PUP-8442) Params should allow default of `false`"

- lib/puppet/provider/yumrepo/inifile.rb
- spec/unit/provider/yumrepo/inifile_spec.rb
In the case that a yumrepo config file that we will be managing a section in is
created after prefetch has happened, any yumrepo resource that follows will be
operating from a stale cache (virtual_inifile). This will cause any content in
the file for any section that we are managing to be cobbered. This is because
when a yumrepo resource is flushed, a new file is written to disk based on what
is in the virtual_inifile instead of modifying the existing file on disk.  Now
we refresh the virtual_inifile if the target of the yumrepo exists on disk but
does not exist in the virual_inifile.
> (PUP-723) Check to see if a repo config file has already been created when creating a yumrepo resource

- lib/puppet/settings.rb
- spec/unit/settings_spec.rb
If we need to create the production environment directory, set the
permissions, and add the service user and service group if we
have them.
> (PUP-6996) Update how we create the production environment directory

- lib/puppet/application/device.rb
- spec/unit/application/device_spec.rb
Print error messages for puppet device --resource. Previously --debug needed to be set as well
> (PUP-8585) Error mgs displayed for device resource

- lib/puppet/util.rb
Sorry for closing/reopening, I seem to have irreparably bamboozled my local branch before going on PTO so I started a new one.
> (PUP-7407) Add @deprecation in code comments for absolute_path

- lib/puppet/util.rb
(Accidentally targeted and merged into master, cherry-picking to 5.5.x)
> (PUP-7407) Add deprecation code comment for absolute_path

- ext/build_defaults.yaml
Reverts puppetlabs/puppet#6923
> Revert "Revert "(maint) Bump packaging to 1.0.x""

- acceptance/.beaker.yml
Analogous to https://github.com/puppetlabs/puppet-agent/pull/1470
> (maint) Update internal test forge URI

- lib/puppet/functions/warning.rb
> (docs) Fix log level in warning function comment

- acceptance/Gemfile
- acceptance/README.md
- acceptance/config/nodes/aix-53-power.yaml
- acceptance/config/nodes/aix-61-power.yaml
- acceptance/config/nodes/aix-71-power.yaml
- acceptance/config/nodes/gem.yaml
- acceptance/config/nodes/huaweios-6-powerpc.yaml
- acceptance/config/nodes/solaris-10-sparc.yaml
- acceptance/config/nodes/solaris-11-sparc.yaml
- acceptance/lib/helper.rb
Cherry picks of the work that originally appeared in https://github.com/puppetlabs/puppet/pull/6988
> (maint) Retarget of the Beaker 4 work to 5.5.x

- acceptance/tests/pluginsync/feature/pluginsync_should_sync_features.rb
- lib/puppet/pops/loader/module_loaders.rb
This introduces the abolity to give a whilecard as "module name" for
a module loader. This will have the same effect as setting `nil`
(which indicates that it is a kind of global loader), but in contrast
it will accept any namespace and attempt to load from it where a `nil`
module name means *only* accepting unqualified name (top/global
namespace).
> (PUP-9133) Make agent side loader load all modules by using wildcard

- lib/puppet/util/windows/service.rb
- spec/unit/util/windows/service_spec.rb
Since we added waits on pending statuses for windows we uncovored an issue:
if the service does not supply a wait hint puppet will not wait at all for the
service to move out of pending. Since we can't assume everything supplies a
wait hint (puppet, for example, does not) this commit updates the wait
functionality in puppet to include a floor of at least 30 seconds: if the
service provides a wait hint less than 30 seconds or none at all puppet will
wait at least that long.
> (PUP-5475) Add default timeout for waiting on pending windows services

- lib/puppet/util/windows/adsi.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
...for better outcomes in localization
> (maint) Reword ADSI util error message

- lib/puppet/util/windows/service.rb
- spec/unit/util/windows/service_spec.rb
This commit adds the Puppet::Util::Windows::Service.exists? method,
which returns true if a given service exists, false otherwise. It
is not only a useful method to have, but is also required to implement
PUP-6822.
> (PUP-9179) Add Puppet::Util::Windows::Service.exists?

- lib/puppet/provider/user/useradd.rb
- spec/unit/provider/user/useradd_spec.rb
Same as https://github.com/puppetlabs/puppet/pull/7137, but targeting 5.5.x branch
> (PUP-9195) Use usermod to manage user expiry when forcelocal is true

- acceptance/tests/resource/exec/should_set_environment_variables.rb
- lib/puppet/provider/exec.rb
- spec/unit/provider/exec/posix_spec.rb
> (PUP-1209) Allow setting empty environment variables

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
Description:
Originally most people used to create an module based Exec to get a _systemd deamon-reload_, every time that a Systemd unit has been changed.
This could have the same exact command defined in multiple modules to ensure to get it run when required.
Suggested Fix:
This Commit will add a new function to check if an unit is requiring a deamon-reload before to (re)start it.
If the unit is flagged with **NeedDaemonReload=yes**, then a _systemd deamon-reload_ will be run.
If multiple units have been updated, the first one flagged will trigger the _deamon-reload_ for all of them, and the others will then be flagged **NeedDaemonReload=no**
So the command will run only once in a puppet run.
CPU Cost:
- Checking for the NeedDaemonReload=yes flag is costing around 6ms.
Running a single …
> (PUP-3483) Fix systemd provider to scan for changed units

- acceptance/tests/ssl/autosign_command.rb
- acceptance/tests/ssl/certificate_extensions.rb
The puppetserver ca cli tool needs the value of the server set in "main"
or "master" sections of the puppet.conf to function correctly.
Previously we updated the main portions of the autosign and certificate
extension tests to set server in the master section and removed our
passing of --server to the agent.
The agent however will not see the server setting in the master
section. This moves the server setting to the main section. It
additionally wraps the teardown calls to puppetserver ca in a
with_puppet_running to with server set.
> (maint) Set server in main section of conf

- acceptance/lib/puppet/acceptance/common_utils.rb
- acceptance/tests/resource/cron/should_allow_changing_parameters.rb
- acceptance/tests/resource/cron/should_be_idempotent.rb
- acceptance/tests/resource/cron/should_create_cron.rb
- acceptance/tests/resource/cron/should_fail_to_write_a_nonexistent_users_crontab.rb
- acceptance/tests/resource/cron/should_match_existing.rb
- acceptance/tests/resource/cron/should_not_overwrite_crontab_file_on_file_read_error.rb
- acceptance/tests/resource/cron/should_only_fail_associated_resources_on_file_read_error.rb
- acceptance/tests/resource/cron/should_remove_cron.rb
- acceptance/tests/resource/cron/should_remove_leading_and_trailing_whitespace.rb
- acceptance/tests/resource/cron/should_remove_matching.rb
- acceptance/tests/resource/cron/should_update_existing.rb
- acceptance/tests/resource/cron/should_write_new_users_crontab_after_puppet_creates_them.rb
> (maint) run cron tests on fedora using cronie

- lib/puppet/provider/package/pkg.rb
- spec/unit/provider/package/pkg_spec.rb
Implements install_options for the pkg provider on Solaris
> (PUP-5287) Implement install_options for Solaris pkg provider

- lib/puppet/provider/package/portage.rb
- spec/unit/provider/package/portage_spec.rb
Use package versions and releases in queries and emerge commands
> (PUP-9071) Fix portage package provider to support versioning

- lib/puppet/transaction.rb
- spec/unit/transaction_spec.rb
With this change, resource dependencies will only get logged once when the transaction is checking for failed_dependency?.
> (PUP-6562) Restrict notice of failed dependency to once.

- lib/puppet/transaction.rb
- spec/unit/transaction_spec.rb
Always log prefetch exceptions, even if we re-raise the exception.  Also, limit the list of exceptions to rescue instead of rescuing Exception.
> (PUP-8962) Log prefetch exceptions and fix rescue list

- lib/puppet/transaction.rb
- spec/unit/transaction_spec.rb
This change corrects some issues with commit 0494301: Adding some tests and fixing an issue with prefetch_failed_providers.
> (PUP 8962) Log Prefetch Exception and Limit Rescue Take 2

- lib/puppet/provider/package/apt.rb
- lib/puppet/provider/package/dnf.rb
- lib/puppet/provider/package/gem.rb
- lib/puppet/provider/package/openbsd.rb
- lib/puppet/provider/package/pacman.rb
- lib/puppet/provider/package/pip.rb
- lib/puppet/provider/package/pip3.rb
- lib/puppet/provider/package/pkg.rb
- lib/puppet/provider/package/portage.rb
- lib/puppet/provider/package/rpm.rb
- lib/puppet/provider/package/sun.rb
- lib/puppet/provider/package/windows.rb
- lib/puppet/provider/package/yum.rb
- lib/puppet/provider/package/zypper.rb
Correcting information about provider install_options as per DOCUMENT-650.
> (docs) DOCUMENT-650: pkg provider install options correction

- lib/puppet/application/lookup.rb
https://tickets.puppetlabs.com/browse/DOC-3896
> (DOCS)DOC-3896: Changing puppet-lookup to puppet lookup

- lib/puppet/type/exec.rb
- spec/unit/type/exec_spec.rb
When we abort an exec because of a failed check,
log a debug level message with the command since that information is not easily available.
> (PUP-9357) Give debug message with command when exec fails check

- lib/puppet/application/device.rb
- spec/unit/application/device_spec.rb
Supersedes PR https://github.com/puppetlabs/puppet/pull/7450
> (maint) Merge 6.0.x to 6.4.x

- acceptance/README.md
- docs/quickstart.md
Please note, this is still in progress, but could benefit by some initial review at this point
> (PUP-4543) Update acceptance readme details

- acceptance/tests/ssl/autosign_command.rb
The agent now emits which type of private key it created.
> (PUP-2606) Update acceptance test to match new message

- lib/puppet/provider/package/rpm.rb
- spec/unit/provider/package/rpm_spec.rb
Prior to this commit:
The rpm provider used potentially out-of-date cache information when uninstalling.
The uninstall command options were more specific than the resource for version and release.
The if statement for arch always appended arch to the uninstall command options.
With this commit:
The cache is updated before use in the uninstall method.
The install is as specific as the resource for version and release and arch.
The spec test correctly tests both specifying and not specifying arch.
> (PUP-8664) rpm provider uninstall too specific

- lib/puppet/reference/configuration.rb
Clarifying hiera_config default setting, take two. Now with more verified accuracy!
> (docs) (DOCUMENT-982) clarify hiera_config default

- lib/puppet/ssl/state_machine.rb
- spec/unit/ssl/state_machine_spec.rb
This reverts commit 926e0e6436cd7eff7b54af240a47e5fea51f861a, reversing
changes made to b04c464352fa8941f4d276672e079ffd23860e31.
> Revert "Merge pull request #7507 from joshcooper/ssl_race_2958"

- acceptance/tests/provider/package/dpkg_ensure_held_package_is_latest.rb
Replaced grep pipe with sed to retrieve candidate and installed package version.
> (maint)- Fix integration test for dpkg ensure held.

- acceptance/tests/resource/user/should_destroy_with_managehome.rb
- lib/puppet/provider/package/dpkg.rb
- lib/puppet/provider/user/useradd.rb
- spec/unit/provider/package/dpkg_spec.rb
Resolve conflict with upstart provider and JRuby
> (maint) Merge 5.5.x to 6.0.x

- lib/puppet/configurer.rb
- spec/unit/configurer_spec.rb
Backports updates from PUP-8967 to 5.5.x
> (PUP-9698) Backport simple status server check

- acceptance/tests/provider/package/dpkg_ensure_held_package_is_latest.rb
- acceptance/tests/provider/package/dpkg_ensure_held_package_should_preserve_version.rb
- lib/puppet/util/pidlock.rb
- lib/puppet/util/windows/process.rb
- spec/unit/util/pidlock_spec.rb
One conflict on puppet_device_test.rb file that was removed from master in this cherry-pick: https://github.com/puppetlabs/puppet/pull/7572
> (maint) Merge 6.4.x to master

- lib/puppet/configurer.rb
Ran tests locally and they passed, so fingers crossed this is good to go.
> (maint) Small changes to PUP-9698 backport for easier mergeups.

- lib/puppet/transaction.rb
When `evaltrace` is enabled, include progress info in the message. Note
the total number of resources may change in the case of providers that
add resources to the catalog at catalog application, such as recursive
file resources, purging, etc.
> (PUP-6465) Emit resource evaluation progress

- lib/puppet/defaults.rb
Added a link to docs and some minor edits on environment_timeout setting.
> (DOCS) DOCUMENT-1027 provide reference link

- lib/puppet/provider/service/systemd.rb
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/647/
> (PUP-9752) default for for released Debian 10

- acceptance/tests/resource/service/launchd_provider.rb
- lib/puppet/provider/service/launchd.rb
- spec/integration/provider/service/systemd_spec.rb
- spec/unit/provider/service/launchd_spec.rb
The only conflict was for this commit: https://github.com/puppetlabs/puppet/commit/da5a1644583a7451a06449e6468533e2dcc1a64d
> (maint) Merge 5.5.x -> 6.0.x

- lib/puppet/type/group.rb
- lib/puppet/type/user.rb
Support has requested more detail about forcelocal depending on luser... implementation.
> (docs) DOCUMENT-800 add info to forcelocal

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
If there is no IPv4 address, use the IPv6 address if available.
> (PUP-5109) Add :serverip6 fact

- acceptance/tests/provider/package/rpm_ensure_install_multiversion_package.rb
- lib/puppet/provider/package/dnf.rb
- lib/puppet/provider/package/rpm.rb
- lib/puppet/provider/package/yum.rb
- lib/puppet/type/package.rb
- spec/unit/provider/package/aptrpm_spec.rb
- spec/unit/provider/package/dnf_spec.rb
- spec/unit/provider/package/rpm_spec.rb
- spec/unit/provider/package/yum_spec.rb
use/display installed packages versions as a string of versions separated by "; " if more than one version if found
> (PUP-9605) add multiple versions support for rpm

- lib/puppet/forge/repository.rb
- lib/puppet/network/http/connection.rb
- lib/puppet/network/http/factory.rb
- lib/puppet/network/http_pool.rb
- lib/puppet/ssl.rb
- lib/puppet/ssl/base.rb
- lib/puppet/ssl/openssl_loader.rb
- lib/puppet/ssl/validator.rb
- lib/puppet/ssl/validator/default_validator.rb
- lib/puppet/ssl/validator/no_validator.rb
- lib/puppet/util/checksums.rb
- lib/puppet/util/http_proxy.rb
- lib/puppet/util/monkey_patches.rb
- lib/puppet/util/platform.rb
- lib/puppet/util/ssl.rb
- lib/puppet/util/windows/root_certs.rb
- lib/puppet/x509.rb
Just putting this up for discussion, needs a ticket, cleanup, maybe totally different approach even....
> (PUP-9930) Conditionally load openssl when not in JRuby FIPS

- lib/puppet/provider/package/apt.rb
- lib/puppet/provider/package/dpkg.rb
- spec/unit/provider/package/dpkg_spec.rb
This reverts commit f33a531d71a960360c519e38e977b37112fc99b3.
> Revert "(PUP-9824) Allow virtual packages for debian"

- lib/puppet/application/device.rb
- lib/puppet/application/resource.rb
- lib/puppet/resource.rb
- spec/unit/application/device_spec.rb
- spec/unit/resource_spec.rb
Conflicts were related to https://github.com/puppetlabs/puppet/commit/690c4e6fb7043498fe03180cbea71fe4a1247120
> (maint) Merge 5.5.x to 6.4.x

- lib/puppet/provider/exec.rb
- lib/puppet/type/exec.rb
- spec/unit/provider/exec_spec.rb
- spec/unit/type/exec_spec.rb
Redact output for failed commands and exclude arguments from unqualified commands.
> (PUP-10100) Redact sensitive data from arguments and failed commands

- acceptance/tests/provider/package/dpkg_ensure_latest_virtual_packages.rb
- lib/puppet/provider/package/apt.rb
- lib/puppet/provider/package/dpkg.rb
- lib/puppet/type/package.rb
- spec/unit/provider/package/dpkg_spec.rb
- spec/unit/type/package_spec.rb
Added implementation to support virtual packages using dpkg provider
> (PUP-10023) Expand the dpkg provider with virtual packages

- acceptance/Gemfile
> (PUP-10116) add dependency to beaker-gke

- acceptance/tests/provider/package/pip.rb
- lib/puppet/provider/package/pip.rb
- spec/unit/provider/package/pip_spec.rb
This PR is a cherry-pick from https://github.com/puppetlabs/puppet/pull/7803
> (maint) fix pip tests on centos-8 

- spec/unit/provider/service/daemontools_spec.rb
- spec/unit/provider/service/runit_spec.rb
This happened because the changes in testing between 5.5.x and 6.4.x
> (maint) fix runit and deamontools unit tests

- lib/puppet/type/selboolean.rb
- spec/unit/type/selboolean_spec.rb
Allow selboolean value property to accept `true/false` as values besides `on/off`
> (PUP-9963) allow boolean for selboolean value

- lib/puppet/application/device.rb
- spec/unit/application/device_spec.rb
Not sure if I'd need some other tests, will gladly add them if necessary.
> (PUP-10104) Puppet device ssl oids

- acceptance/tests/ssl/certificate_extensions.rb
- acceptance/tests/ssl/trusted_external_facts.rb
- lib/puppet/context/trusted_information.rb
- lib/puppet/defaults.rb
- lib/puppet/test/test_helper.rb
- lib/puppet/trusted_external.rb
- spec/unit/context/trusted_information_spec.rb
Supersedes PR https://github.com/puppetlabs/puppet/pull/7813
> (PUP-9994) Trusted external facts

- Gemfile
Work around https://github.com/voxpupuli/hiera-eyaml/issues/289
> (maint) Pin hiera eyaml in 5.5.x

- Gemfile
Work around voxpupuli/hiera-eyaml#289
> (maint) Pin hiera eyaml in 6.4.x

- lib/puppet/configurer.rb
- lib/puppet/defaults.rb
- spec/integration/configurer_spec.rb
This is PR #7666 targeted at master with a few minor adjustments
> (PUP-5934) Add optional fact refresh after applying catalog

- Gemfile
This reverts commit 77d45a1e0e1f95fcd789db191914a642b201c574.
> Revert "(maint) Pin to hiera-eyaml less than 3.1.0"

- lib/puppet/configurer.rb
- lib/puppet/defaults.rb
- spec/integration/configurer_spec.rb
Backports PR https://github.com/puppetlabs/puppet/pull/7833 to 5.5.x
Supersedes PR https://github.com/puppetlabs/puppet/pull/7666
> (PUP-5934) Backport resubmit facts

- ext/windows/service/daemon.rb
Log if there are any erros when windows services
fails to start to to load_env exceptions
> (PUP-10140) Improve logging on windows service

- lib/puppet/provider/package_targetable.rb
- spec/unit/provider/package_targetable_spec.rb
This is a maintenance commit, resolving a broken debug statement.
> (maint) add spec tests and correct debug output

- tasks/manpages.rake
Cherry-pick commit from https://github.com/puppetlabs/puppet/pull/7870
> (maint) Create man{5,8} before manpage generation

- lib/puppet/provider/user/hpux.rb
- spec/unit/provider/user/hpux_spec.rb
Applied fix from community member [Carla Curtis](https://tickets.puppetlabs.com/browse/PUP-9391?focusedCommentId=616503&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-616503). Thank you for your contribution!
> (PUP-9391) HP-UX usermod/userdel syntax order fix

- lib/puppet/concurrent.rb
- lib/puppet/concurrent/lock.rb
- lib/puppet/concurrent/synchronized.rb
- lib/puppet/concurrent/thread_local_singleton.rb
- lib/puppet/environments.rb
- lib/puppet/node/environment.rb
- lib/puppet/pops/parser/evaluating_parser.rb
- lib/puppet/pops/time/timespan.rb
- lib/puppet/pops/types/type_parser.rb
- spec/unit/concurrent/lock_spec.rb
Lock when initializing properties on environment objects and when
handling the environment cache.
> (PUP-10024) Add locking around environments

- .gemspec
- .travis.yml
backport https://github.com/puppetlabs/puppet/pull/7887 to 5.5.x
> (maint) fix travis for bundler 2.1.0 update

- lib/puppet/http/client.rb
- spec/unit/http/client_spec.rb
This commit adds method to `Puppet::HTTP::Client` to allow us to make
delete, head, and post http calls using the new http client code.
> (PUP-10034) Add DELETE, HEAD, POST

- lib/puppet/pops/lookup/invocation.rb
This PR is to fix a RecursiveLookup error that sometimes occurs when trying to auto-populate class parameters with Hiera data when running in multithreaded mode.
> (PUP-10222) Make Lookup Invocation parent thread local

- lib/puppet/http.rb
- lib/puppet/http/errors.rb
- lib/puppet/http/service.rb
- lib/puppet/http/service/compiler.rb
- lib/puppet/http/service/report.rb
- spec/unit/http/service/compiler_spec.rb
Add serialization error and protected methods for serializing/deserializing.
Add a :puppet service to get nodes/catalogs and put facts.
> (PUP-10145) Add :puppet service

- lib/puppet/http.rb
- lib/puppet/http/client.rb
- lib/puppet/http/service.rb
- lib/puppet/http/service/file_server.rb
- spec/unit/http/client_spec.rb
- spec/unit/http/service/compiler_spec.rb
- spec/unit/http/service/file_server_spec.rb
- spec/unit/http/service/report_spec.rb
This commit adds in a new file service. This service has the ability to
get file metadata, search file metadata, and get file content from a
server.
> (PUP-10146) Add File HTTP Service

- acceptance/tests/provider/package/gem.rb
> (PUP-9966) acceptance tests for package gem provider

- .gemspec
- ext/project_data.yaml
This PR updates the Facter dependency to also include Facter 4.
_A ship in harbor is safe — but that is not what ships are built for._
> (maint) update Facter dependency

- lib/puppet/util/pidlock.rb
- spec/unit/util/pidlock_spec.rb
When Puppet Agent is started as a LightWeight Process(LWP), and is incorrectly terminated (eg. killed by KILL signal), decision for the removal of stale pidfile lock (on POSIX) actually depends on the kernel, operating system and sometimes even version due to the unreliability of ps CLI arguments. The '-p' argument, used initially for all POSIX, is indeed available for all (checked) versions of ps, but in some cases it does not work as expected for LWP (printing nothing and returning error code 1).
Depending on the kernel seemed to be the most clean approach to tackle all the different scenarios of choosing the right ps argument. A fallback was implemented for Linux operating systems where ps is outdated and it does not have the -q (quick mode) parameter (such as Red Hat 5) which seems to …
> (PUP-10218) Puppet incorrectly detecting stale pidfile

- spec/unit/util/pidlock_spec.rb
One of the newly introduced tests in `pidlock_spec.rb` wasn't fully mocked and sadly it was actually having expectations based on real executions of a command. To be noted that this test was failing under different circumstances:
1. When it was run any time after some certain tests from `agent_spec.rb` 
2. When the test's filepath used in rspec run or the bundler's gem installation path did not include the word `puppet`
**The first** one is a more complex case which will be solved under a different ticket (PUP-10302). Basically, a fork mechanism, covered by four tests, ends up making changes to the rspec's process argument instead of creating a child process and do said modification to it (not the parent process). An interesting finding here is that both `comm` and `args` columns of `ps` …
> (PUP-10294) Order dependent test failure with recent changes

- lib/puppet/application/filebucket.rb
- lib/puppet/type/file.rb
This affects versions 5.5 and up.
https://tickets.puppetlabs.com/browse/DOCUMENT-966
> (docs)(DOCUMENT-966) Warning for file backup docs

- lib/puppet/functions/eyaml_lookup_key.rb
- spec/unit/functions/lookup_spec.rb
Fixes https://github.com/voxpupuli/hiera-eyaml-gpg/issues/41
> (PUP-10317) Provide better error when hiera-eyaml decryption fails

- lib/puppet/metatype/manager.rb
- lib/puppet/node/environment.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/parser/functions.rb
- lib/puppet/pops/loaders.rb
- lib/puppet/resource/type_collection.rb
- lib/puppet/type.rb
- lib/puppet/util/autoload.rb
- lib/puppet/util/instance_loader.rb
Some of this is hacky for now, working on cleaning it up but I'm putting this up as a draft so it can be used for testing.
> (PUP-10318) Fix errors when running multithreaded with environment cache on

- acceptance/tests/provider/package/dpkg_ensure_latest_virtual_packages.rb
This commit handles the `dpkg_ensure_latest_virtual_packages` test which
is not present on the 5.5.x tree.
> (maint) Run package resource acceptance in CI - master branch

- lib/puppet/provider/package/pkgng.rb
- spec/unit/provider/package/pkgng_spec.rb
This pr fixes https://tickets.puppetlabs.com/browse/PUP-10380
> (PUP-10380) Add support for install_options to pkgng

- spec/integration/http/client_spec.rb
Prior to ruby 2.3, if puppet tried to reuse a persistent connection, but the
remote side had already closed it, then puppet would receive an EOFError.
Ruby 2.3.0 does a non-blocking read to detect if the connection is closed, and
automatically reconnects if needed. See ruby bug 11671 and commit [1].
Since puppet 6 requires 2.3.0 or greater, there isn't anything for puppet to do.
However, this commit adjusts the persistent http test to POST instead of GET.
This is because ruby 2.1.5 and up will automatically retry idempotent HTTP
requests, like GET, which could mask the issue. Note when running on ruby 2.5
and up, puppet disables the ruby's auto retry, so that the decision to retry
is not being made in multiple places. See PUP-3905 and commit
1e4fd336568afaf989e1e0b782629aa42903b8d5 for …
> (maint) Verify POST requests detect EOF

- lib/puppet/functions/reduce.rb
Targeting this at 5.5.x so it can be merged up to master.
> (docs)(DOCUMENT-1035) Edits from user feedback

- lib/puppet.rb
- lib/puppet/network/http_pool.rb
- lib/puppet/runtime.rb
- spec/unit/network/http_pool_spec.rb
- spec/unit/puppet_spec.rb
Allow puppetserver to register its http implementation
> (PUP-10429) Allow puppetserver to register http implementation

- lib/puppet/agent.rb
Reverting part of the changes (from #8113 which were non essential for fixing the ticket's issue) due to unwanted behaviour changes for puppet run and executions time. These changes will be available in a configurable form (only on 6.x) through `PUP-8051`.
> (PUP-10351) Puppet Agent fails to self-restart

- lib/puppet/agent.rb
- lib/puppet/provider/package/pip.rb
- spec/unit/provider/package/pip_spec.rb
* commit '7c0d2e85829d4a147d06db330ef5b3660abbe40e':
(PUP-10351) Puppet Agent fails to self-restart
(PUP-10485) quote spaces in the path to pip tests
(PUP-10485) quote spaces in the path to pip
Conflicts:
lib/puppet/provider/package/pip.rb
locales/puppet.pot
We kept ours locales/puppet.pot and fixed pip.rb
>  (maint) Merge 5.5.x to master 

- lib/puppet/ssl/state_machine.rb
- spec/unit/ssl/state_machine_spec.rb
Previously, if the state machine failed to acquired the ssl lock it would raise
a Puppet::Error with the message "Another puppet instance is already running;
exiting" causing puppet to exit.
This commit makes it possible for the state machine to retry the ssl lock up to
a maximum deadline. By default, the state machine won't retry.
If we fail to acquire the lock (after retrying or not), we raise Puppet::Error
and state the reason why we're exiting.
> (PUP-10420) Allow state machine to retry ssl lock

- lib/puppet/type/user.rb
- spec/unit/type/user_spec.rb
ssh tests should be added to the sshkeys_core module
> Mergeup 5.5.x to master

- ext/project_data.yaml
ffi 0.13 segfaults on windows, see ffi/ffi#784
> (maint) Pin to ffi < 0.13

- ext/project_data.yaml
This reverts commit 6fdf2d3cbc966dbc83add93f46b3dda80a2cdd06, reversing
changes made to 9b5bd2ad8b180efa4c143798a1a2b362928f1f1c.
> Revert "Merge pull request #8186 from joshcooper/pin_ffi"

- lib/puppet/util/windows/principal.rb
Calling `SID.octet_string_to_principal` with an invalid byte array containing a
single element `2` could cause a segfault on Windows because
`Principal#lookup_account_sid` converts the byte array to a SID pointer (PSID)
and calls `LookupAccountSidW` with it. Apparently, Windows doesn't sanity check
the argument before using it, sometimes resulting in the following:
C:/Users/josh/projects/puppet/lib/puppet/util/windows/principal.rb:115: [BUG] Segmentation fault
ruby 2.5.7p206 (2019-10-01 revision 67816) [x64-mingw32]
-- Control frame information -----------------------------------------------
c:0062 p:---- s:0321 e:000320 CFUNC  :LookupAccountSidW
c:0061 p:0050 s:0310 e:000309 BLOCK  C:/Users/josh/projects/puppet/lib/puppet/util/windows/principal.rb:115 [FINISH]
c:0060 p:---- s:0304 …
> (maint) Fix segfault due to invalid SID in tests

- acceptance/tests/direct_puppet/static_catalog_env_control.rb
The static catalog beaker test failed, because as of commit 039270e298, puppet
will raise if the file it writes doesn't match the desired checksum. For static
catalogs, the desired checksum is specified in the `metadata` section of the
catalog. The test didn't fail previously, because puppet would write the file,
and then read the file back in, and compare those two checksums, ignoring the
desired checksum in catalog.
> (maint) Return code_content that matches checksum

- lib/puppet/provider/package/gem.rb
- lib/puppet/provider/package/puppet_gem.rb
- spec/unit/provider/package/puppet_gem_spec.rb
* pl/5.5.x:
(PUP-10584) use customized PKG_CONFIG_PATH while installing puppet gems
* Conflicts:
lib/puppet/provider/package/puppet_gem.rb
> (maint) Merge up 5.5.x into master

- lib/puppet/type/notify.rb
https://tickets.puppetlabs.com/browse/DOCUMENT-1091
> (DOCS) Add acceptable values for message

- lib/puppet/indirector/hiera.rb
- lib/puppet/test/test_helper.rb
- spec/integration/data_binding_spec.rb
- spec/unit/configurer_spec.rb
Resolves conflicts due to thread local differences in indirector state.
> (maint) Merge up 5.5.x to master

- lib/puppet/defaults.rb
https://tickets.puppetlabs.com/browse/DOCUMENT-1095
> (DOCS) Add a note re. where to add the certname

- lib/puppet/type/file/source.rb
Document explicit `checksum_value` with `source`, `X-Checksum-*` headers,
userinfo component and HTTPS servers with `ssl_trust_store` setting.
> (maint) Update file source docs

- lib/puppet/pops/lookup/hiera_config.rb
- spec/integration/data_binding_spec.rb
- spec/unit/pops/lookup/lookup_spec.rb
This adds a new `plan_hierarchy` key to Hiera's config at the same level
as the `hierarchy` key. This key is used to specify data to use for
lookups in Bolt plans outside of [apply
blocks](https://puppet.com/docs/bolt/latest/applying_manifest_blocks.html).
This solves two related problems with lookups in Bolt plans:
1. Bolt plans don't run in a context that has a node, environment, or
other common interpolations used when configuring and looking up
Hiera data, which causes
2. Users who reuse their existing Hiera configuration with Bolt often
encounter errors because interpolation isn't supported, even if the
data they are trying to look up doesn't require interpolating.
Adding the `plan_hierarchy` key allows users to add to their existing
Hiera config and use existing Hiera data without …
> (PUP-10587) Add plan_hierarchy key to Hiera config

- Gemfile
- lib/puppet/defaults.rb
- spec/unit/defaults_spec.rb
This reverts commit e471d9e86e8aa2b30433bdfff51750fc11698964.
> (PUP-10605) Revert "(PUP-10091) Add FacterNg dependency"

- lib/puppet/parser/functions.rb
- lib/puppet/pops/adaptable.rb
- lib/puppet/pops/adapters.rb
- lib/puppet/pops/validation/checker4_0.rb
- lib/puppet/util/autoload.rb
This primarily cleans up our Adapter.adapt usage where we were effectively calling initialization code on every invocation. I doubt it's a huge performance win, but it was bothering me nonetheless. There's a couple of other small Adapter related clean ups as well.
> (maint) Adapter improvements

- lib/puppet/functions/lstrip.rb
- lib/puppet/functions/rstrip.rb
- lib/puppet/functions/strip.rb
https://tickets.puppetlabs.com/browse/PUP-10054
> (docs) Update examples for strip, rstrip and lstrip functions

- lib/puppet/defaults.rb
- lib/puppet/transaction.rb
- spec/unit/transaction_spec.rb
> (PUP-9426) Remove future_features setting

- spec/integration/application/agent_spec.rb
For tests where the foreground agent tries to acquire the lock and exits with
failure, increase the timeout that the background thread waits for the
foreground agent to start, as it might take awhile in appveyor.
For the test where the background thread acquires the lock and waits for the
foreground agent to fail to acquire the lock once, have the foreground agent
signal the failure using the log destination. As soon as the failure occurs, the
background thread will exit, enabling the foreground agent to acquire the lock
and successfully apply the catalog.
> (maint) Handle slow 2019 appveyor workers

- lib/puppet/defaults.rb
https://tickets.puppetlabs.com/browse/DOC-4673
> (DOCS) Clarify values in server_list

- spec/unit/ssl/ssl_provider_spec.rb
More details in https://tickets.puppetlabs.com/browse/PUP-10689
> (maint) Skip SSL spec when openssl >= 1.1.1h

- api/schemas/report.json
- lib/puppet/configurer.rb
- lib/puppet/transaction/report.rb
- spec/integration/application/agent_spec.rb
- spec/unit/configurer_spec.rb
- spec/unit/transaction/report_spec.rb
it has the same value like `master_used`
> (PUP-10672) add server_used report entry

- lib/puppet/configurer.rb
follow-up of https://github.com/puppetlabs/puppet/pull/8384#pullrequestreview-507824182
> (maint) user serverport instead masterport in merge from 5.5.x

- api/schemas/report.json
- lib/puppet/transaction/report.rb
- spec/integration/application/agent_spec.rb
- spec/unit/configurer_spec.rb
- spec/unit/transaction/report_spec.rb
Remove master_used from report since it was replaced by server_used
>  (PUP-10714) Remove master_used from report 

- lib/puppet/configurer.rb
follow-up from https://github.com/puppetlabs/puppet/pull/8354#discussion_r504258393
> (PUP-10648) simplify code and remove exception usage

- lib/puppet/configurer.rb
* commit '6bf8f61a84e59f1968ce17e935eab15b47cdfebf':
(PUP-10648) simplify code and remove exception usage
Conflicts:
lib/puppet/configurer.rb (masterport -> serverport)
> (maint) Merge 5.5.x to master

- .github/workflows/rspec_tests.yaml
- lib/puppet/configurer.rb
* Commits:
(maint) Remove ignored paths from GitHub Actions
(PUP-10648) simplify code and remove exception usage
* Conflicts:
.github/workflows/rspec_tests.yaml - replaced keyword master with main
lib/puppet/configurer.rb - wrong identation issue
> (maint) Merge up master into main 

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
- acceptance/tests/security/cve-2013-2275_report_acl.rb
- lib/puppet/application/filebucket.rb
Remove leftover references to the `[master]` setting section and replace them with `[server]`.
> (maint) Remove references to `master` section

- lib/puppet/pal/pal_impl.rb
- spec/unit/puppet_pal_catalog_spec.rb
This updates `PAL.with_catalog_compiler` to shadow target and plan
variables that collide with facts of the same name.
Part of https://github.com/puppetlabs/bolt/issues/2111
> (PUP-10723) Shadow fact/variable collisions in PAL catalog compiler

- lib/puppet/network/formats.rb
- spec/unit/http/service/compiler_spec.rb
- spec/unit/http/service_spec.rb
Manually merging this to workaround SLES12 power CI issue.
> (maint) Merge master to main

- CODEOWNERS
Networking team no longer exists.
> (maint) Collapse defaults and remove networking

- lib/puppet/application_support.rb
- spec/unit/application_spec.rb
Master application settings will also be used on server application
> (PUP-10773) Reroute master settings to server

- spec/integration/application/agent_spec.rb
Suppress stdout test output added in commit 50186218c1.
> (maint) Suppress test output

- acceptance/tests/resource/user/should_modify_gid.rb
- acceptance/tests/resource/user/should_modify_gid_forcelocal.rb
- lib/puppet/provider/user/useradd.rb
- spec/unit/provider/user/useradd_spec.rb
"7.4.1"
* tag '7.4.1':
(PUP-10896) Fix gid idempotency on user resource
(packaging) Bump to version '7.4.1' [no-promote]
> (maint) Merge up 7.4.1 to main

- acceptance/tests/resource/user/should_modify_gid.rb
- acceptance/tests/resource/user/should_modify_gid_forcelocal.rb
- lib/puppet/provider/user/useradd.rb
- spec/unit/provider/user/useradd_spec.rb
"6.21.1"
* tag '6.21.1':
(PUP-10896) Fix gid idempotency on user resource
(packaging) Bump to version '6.21.1' [no-promote]
> (maint) Merge up 6.21.1 to 6.x

- spec/unit/application/facts_spec.rb
* pl/6.x:
(PUP-10844) Add puppet facts show on 6.x
Manually merged-up lib/puppet/face/facts.rb.
> (maint) Merge up 6.x  to main

- lib/puppet/face/facts.rb
On facts diff command we run both facter 3 and facter 4 in the same run
When apt module is installed, this leads to errors in output since both
runs are using the same ruby environment/instance
After this commit, facter 4 output is read using a totally separated puppet run
> (PUP-10940) puppet facts diff facter-ng reload

- lib/puppet/functions/partition.rb
- spec/integration/http/client_spec.rb
puppetlabs/6.x:
*  (docs) mark documentation examples as source code
*  (maint) stub Facter request to external services
Conflicts:
*	spec/spec_helper.rb
> (maint) Merge branch 6.x into main

- lib/puppet/http/resolver/server_list.rb
- spec/unit/configurer_spec.rb
When processing server_list and trying to find a functional server,
throw warnings when it cannot connect to servers from server_list and
if there is no functional server in server_list, then throw the initial
error.
> (PUP-10844) Warnings for unavailable servers

- spec/unit/configurer_spec.rb
Update the specs in main to match the new behavior.
> (maint) Update server_list tests for terminology changes in main

- acceptance/tests/resource/service/windows.rb
- lib/puppet/provider/service/windows.rb
- lib/puppet/type/service.rb
- spec/unit/provider/service/windows_spec.rb
- spec/unit/type/service_spec.rb
Before this commit, most checks were done in [munge](https://github.com/puppetlabs/puppet/blob/be708728ed6f6d98784a857b9c31a5e3dd636f50/lib/puppet/type/service.rb#L142) and [validate](https://github.com/puppetlabs/puppet/blob/be708728ed6f6d98784a857b9c31a5e3dd636f50/lib/puppet/type/service.rb#L161) of the `logonaccount` and `logonpassword` parameters. This proved to be too early in case of manifests where the value of these parameters depended on other actions (such as creating the user, changing its password or adding the 'Logon as a service' right in the same manifest where we are setting it as `logonaccount` for a service).
This commit ensures said munging and validation to happen only when checking insyncness (munging) and when changes are required (validation).
Easy issue …
> (PUP-10999) Fix logon account setting for Windows services 

- spec/unit/functions/lookup_spec.rb
Verify interpolation within lookup options works.
> (PUP-7315) Add test for interpolation of lookup options

- lib/puppet/functions/empty.rb
- spec/unit/functions/empty_spec.rb
- accept Datatype `Sensitive` for Function `empty`
> (PUP-11124) Sensitive for Function empty

- lib/puppet/environments.rb
- spec/unit/environments_spec.rb
- spec/unit/functions/logging_spec.rb
This reverts commit 0d8c1d5a1b70674450fd80e919d198ab919bcb46.
> Revert "(PUP-10955) Normalize environment name to symbol before caching"

- lib/puppet/environments.rb
- spec/unit/environments_spec.rb
- spec/unit/functions/logging_spec.rb
This reverts commit 0d8c1d5a1b70674450fd80e919d198ab919bcb46.
> Revert "(PUP-10955) Normalize environment name to symbol before caching" (cherry-pick to main)

- acceptance/tests/resource/package/ips/should_be_updateable_and_unholdable_at_same_time.rb
- lib/puppet/defaults.rb
- lib/puppet/network/http/api/indirected_routes.rb
- lib/puppet/provider/package/pkg.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
- spec/unit/provider/package/pkg_spec.rb
Conflicts:
spec/unit/provider/package/pkg_spec.rb
> (maint) Merge-up 6.x to main

- lib/puppet/defaults.rb
- lib/puppet/network/http/api/indirected_routes.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
This reverts commit 2bf802541d1f2da0cfe505af10e2724d822e8757, reversing
changes made to 1d0df07929c93b740cecd7fcf876471ffe799132.
> (PUP-6802) Revert PR #8681 non existing environment handling

- lib/puppet/environments.rb
- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/node/environment.rb
- spec/unit/environments_spec.rb
- spec/unit/indirector/catalog/compiler_spec.rb
This reverts commit 53aa5b312d1f15063822b8ad2f5c545975ad47a3, reversing
changes made to 32f0d253309e44cf3a2cf189b9f7cf02d6229435.
> Revert "Merge pull request #8714 from joshcooper/guard_environment_11158

- lib/puppet/environments.rb
- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/node/environment.rb
- spec/unit/environments_spec.rb
- spec/unit/indirector/catalog/compiler_spec.rb
This reverts commit 21bf78d0ed9be75a14c2f73bbdf14899bcfafe10, reversing
changes made to 53aa5b312d1f15063822b8ad2f5c545975ad47a3.
> (maint) Rerevert environment guard

- lib/puppet/module_tool/applications/installer.rb
- spec/unit/module_tool/applications/installer_spec.rb
`semantic_puppet` exposed `unsatisfied` as an attribute
for the `SemanticPuppet::Dependency::UnsatisfiableGraph`
error. In the cases where the unsatisfiable dependencies
cannot be determined, this will `e.unsatisfied` returns
`nil` and we need to prin the generic error message.
> (PUP-11172) Handle missing unsatisfied dependencies

- spec/integration/application/agent_spec.rb
* commit '6058bbec65bb3479f823cb71536f6a7eed9817e7':
(maint) Increase wait time
(maint) Refactor creation of lock file
* Conflicts:
spec/integration/application/agent_spec.rb
> (maint) Merge up 6.x to main

- lib/puppet/application/resource.rb
- lib/puppet/pops/serialization/to_stringified_converter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/application/resource_spec.rb
- spec/unit/pops/serialization/to_stringified_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
This is the minimal changes required to fix the PUP-10105 issue. Please see https://github.com/puppetlabs/puppet/pull/8726 for more details
> (PUP-10105) puppet resource --to_yaml emits puppet class tags (minimal)

- lib/puppet/provider/package/pkg.rb
- spec/unit/provider/package/pkg_spec.rb
On Solaris when a pkg install is already running, or it is running in a zone, if
puppet tries to install a package with pkg, it will fail.
Now puppet will try 5 times(waiting 1s, 2s, 4s, 8s, 16s) to install the package.
> (PUP-11208) Retry pkg install on Solaris

- Gemfile
- acceptance/Gemfile
update Gemfile locate_for to accept https git URLs
> (maint) update Gemfile locate_for

- acceptance/tests/environment/use_last_server_specified_environment.rb
In bb1017f9 we changed the agent's behavior to fall back to making a
node request if the lastrunfile does not contain a usable environment.
Update the `use_last_server_specified_environment` test to reflect this
change in behavior. Based on test ordering, this test could have passed
if the `lastrunfile` was present when the first agent run started. To
ensure the new behavior is triggered, always clean up the `lastrunfile`
at the beginning of the test.
> (maint) Fix last server environment test

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
- lib/puppet/application/lookup.rb
- spec/integration/application/lookup_spec.rb
Previously, while puppet lookup was creating the node request, the classifier would collect all facts from a node, and then search for local trusted data with `Puppet.lookup(:trusted_information)`. The problem is that, whether we are using lookup in a local or remote context, the `trusted_information` would always be empty, and so, the classifier would gather trusted_data from the local node where the lookup command is ran.
(https://github.com/puppetlabs/classifier/blob/main/puppet/lib/puppet/indirector/node/classifier.rb#L62-L69)
This commit fixes this issue by using the trusted facts gathered from pdb (#8786), to override the `trusted_information` option, so that the block of code mentioned above doesn't use the local node as a base of collection for trusted data, unless we are using …
> (PUP-8094) Puppet lookup ignores trusted fact rule for classifier

- acceptance/tests/agent/agent_fails_with_unknown_resource.rb
- api/schemas/catalog.json
- benchmarks/serialization/catalog.json
- lib/puppet/defaults.rb
- lib/puppet/http/client.rb
- lib/puppet/http/redirector.rb
- lib/puppet/parser/resource.rb
- lib/puppet/pops/evaluator/runtime3_resource_support.rb
- lib/puppet/resource.rb
- lib/puppet/resource/catalog.rb
- spec/fixtures/integration/application/agent/cached_deferred_catalog.json
- spec/integration/parser/pcore_resource_spec.rb
- spec/unit/configurer_spec.rb
- spec/unit/http/client_spec.rb
- spec/unit/resource/catalog_spec.rb
- spec/unit/resource_spec.rb
This reverts commit 845033b31caa3234801d155727c39dcbb26cbd93, reversing
changes made to 3b2acd0f1cf855706d67cd340d1b3277ba04c88f.
> Revert "Merge pull request #8809 from joshcooper/revert_35121d8b87"

- lib/puppet/application/lookup.rb
This commit updates the documentation for the puppet lookup command to
contain more examples and further clarification.
> (PUP-10151) Update man page for the puppet lookup command

- lib/puppet/resource/type_collection.rb
Puppetserver in MT mode can deadlock if one thread calls into the loaders,
which locks the environment, and then tries to lock the type_collection:
- waiting to lock <3f27e688> (a org.jruby.gen.RubyObject0) owned by "qtp346358872-131" t@131
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/type_collection.rb:188
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/type_collection.rb:152
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/type_collection.rb:152
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/loader/runtime3_type_loader.rb:79
...
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/concurrent/lock.rb:10
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/loader/loader.rb:153
While another thread locks the type_collection and tries to lock …
> (PUP-11373) Always lock the environment before its type collection

- .github/workflows/snyk_monitor.yaml
This changes the Snyk GitHub workflow to use an organizational token and removes the workflow from a schedule.
> (PUP-14153) Updates Snyk GitHub workflow

- docs/environment_convergence.md
- docs/index.md
Describe agent vs server specified environments, strict_environment_mode
and use_last_environment.
> (maint) Add environment convergence docs

- lib/puppet/provider/package/yum.rb
Update yum provider to pass in relevant install options (_disablerepo_, _enablerepo_, _disableexcludes_) while listing available versions when version or range is specified.
Fixes [PUP-11475](https://tickets.puppetlabs.com/browse/PUP-11475)
> (PUP-11475) Add install_options when listing available_versions

- ext/systemd/puppet.service
Wait for network-online.target 
Fix issue where Puppet Agent attempts to contact Puppet Server before having network connectivity.
JIRA: PUP-5402, PA-1119
> (PUP-5402) Update puppet.service

- lib/puppet/pops/functions/dispatcher.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
Using a deferred function for a typed parameter value of a class
results in a compilation error stating that the type defined for
the parameter does not match the “Deferred” type at compilation
time. This error prevents the use of Deferred functions for the
values of any typed class parameters.
This change updates the type check to introspect Deferred
functions for the return_value type of that Deferred function.
> (PUP-11518) Fix type checking with deferred functions

- acceptance/tests/resource/user/should_modify_while_managing_home.rb
This is a follow up to commit f6214639183
> (maint) Mark additional Windows 11 test as pending

- lib/puppet/functions/capitalize.rb
- lib/puppet/type/tidy.rb
Two small changes related to generated docs pages. Please let me know if there is an error with the format of my contribution.
> (maint) trivial docs changes

- lib/puppet/face/module/list.rb
- spec/unit/face/module/list_spec.rb
Supersedes https://github.com/puppetlabs/puppet/pull/8930
> (PUP-11604) List unmet deps in --render-as json 

- lib/puppet/application/lookup.rb
- spec/integration/application/lookup_spec.rb
This commit ensures that `puppet lookup -E <environment> --compile` executes the enc but still uses the environment defined on the command line. Additionally, 2 tests were added to test this behavior and make sure `puppet lookup` behaves as expected.
> (PUP-11527) puppet lookup -E doesn't execute ENC

- lib/puppet/info_service/task_information_service.rb
- spec/unit/info_service_spec.rb
Previously, if a task failed validation in someway, typically with bad metadata, then `Puppet::InfoService.tasks_per_environment` method would error, failing to return any task info.
The desired behavior is to still list valid tasks in an environment, even if one task is invalid.
> (PUP-11683) Ignore invalid tasks when listing

- .gemspec
- Gemfile
- ext/project_data.yaml
- install.rb
- lib/hiera_puppet.rb
- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/hiera_spec.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/hiera_puppet_spec.rb
- spec/unit/indirector/hiera_spec.rb
This PR comprises work to remove Hiera 3 as a hard dependency while retaining compatibility.
> (PUP-11621) Hiera 3 deprecation

- lib/puppet/defaults.rb
- lib/puppet/environments.rb
- lib/puppet/node/environment.rb
- lib/puppet/resource.rb
- spec/unit/environments_spec.rb
- spec/unit/node/environment_spec.rb
- spec/unit/parser/resource_spec.rb
Needs more work and tests, but wanted to put what I have so far up to discuss approach.
> (PUP-11691) Report configured environment dir even when containing resolved symlinks

- spec/integration/application/apply_spec.rb
Using the format handler allows usage of the render function which overrides with `rich_data: true` for rendering a catalog.
> (PUP-11751) Use format handler instead of to_json

- lib/puppet/ssl/state_machine.rb
- spec/unit/ssl/state_machine_spec.rb
Prior to this commit, any time a node attempted to refresh its certificate authority (CA) or certificate revocation list (CRL), regardless of whether it was successful in doing so, Puppet would update the modified timestamp (mtime) on the CA or CRL file.
Puppet uses the mtime to decide when to attempt to update a CA or CRL. As a result, if Puppet attempted but failed to updates either of those file, it would need to wait the full refresh interval before trying again.
This commit changes Puppet to only update the modified timestamp on the CA or CRL files if they have been successfully refreshed. This means that if Puppet fails to update its CA or CRL, it will try again the next run interval instead of waiting for the full CA or CRL refresh interval (which should be greater than the run …
> (PUP-11869) Retry failed CA/CRL refreshes sooner

- spec/integration/application/agent_spec.rb
Running the agent integration test modified the CA and CRL fixtures if the files on disk were last modified more than ca/crl_refresh_interval seconds old. So make a copy of those fixture for each test, even ones where we're not testing refresh behavior.
> (PUP-11871) Copy CA/CRL fixtures

- .rubocop_todo.yml
- lib/puppet/provider/package/yum.rb
- lib/puppet/type/component.rb
- lib/puppet/util/package/version/pip.rb
See https://github.com/puppetlabs/puppet/pull/9177
> (PUP-11931) Backport some Lint rubocops to 7.x

- acceptance/tests/resource/exec/should_run_command_in_cwd.rb
- acceptance/tests/utf8/utf8-in-function-args.rb
Supersedes https://github.com/puppetlabs/puppet/pull/9240
> (PUP-12020) Skip tests on debian-12-amd64

- acceptance/lib/puppet/acceptance/environment_utils.rb
- acceptance/lib/puppet/acceptance/module_utils.rb
- acceptance/lib/puppet/acceptance/service_utils.rb
- acceptance/tests/agent/agent_disable_lockfile.rb
- acceptance/tests/environment/can_enumerate_environments.rb
- acceptance/tests/environment/directory_environment_production_created_master.rb
- acceptance/tests/pluginsync/7316_faces_with_app_stubs_should_be_available_via_pluginsync.rb
- acceptance/tests/resource/service/should_query_all.rb
- acceptance/tests/ticket_13948_lib_dir_hook_should_be_called_on_initialization.rb
This PR is a backport of https://github.com/puppetlabs/puppet/pull/9246
> Backport #9246 to 7.x

- lib/puppet/pops/evaluator/literal_evaluator.rb
- lib/puppet/pops/validation/validator_factory_4_0.rb
- spec/unit/info_service_spec.rb
- spec/unit/pops/evaluator/literal_evaluator_spec.rb
- spec/unit/pops/validator/validator_spec.rb
https://github.com/puppetlabs/puppet/pull/9269
> Backport #9269 to 7.29.1

- Gemfile
- puppet.gemspec
> [Backport 7.x] (FACT-3434) Accept ffi >= 1.16.3, < 1.17.0

- lib/puppet/provider/file/posix.rb
- lib/puppet/type/file/selcontext.rb
- lib/puppet/util/selinux.rb
- spec/unit/transaction_spec.rb
- spec/unit/type/file/selinux_spec.rb
- spec/unit/util/selinux_spec.rb
This reverts commit 889892f24bfa43121e47a582c15d6586be9416c5, reversing changes made to 0c28d4f6f5aec1d6fd8c460528381d4e6e678c20.
> Revert "Merge pull request #9349 from AriaXLi/PUP-7126"

- lib/puppet/daemon.rb
- lib/puppet/scheduler/splay_job.rb
- spec/unit/daemon_spec.rb
This reverts commit 7f0770c25d03324e29b6438db7acc933799e7e29, reversing changes made to c26087122aa9750894ac14667a1540e6c6cf56f5.
> Revert "Merge pull request #9345 from mhashizume/PUP-11728/main/splay"

- acceptance/tests/resource/service/windows.rb
Windows FIPS 2016 requires that the tests in acceptance/tests/resource/service/windows.rb should have passwords with a special character and a numeric character.
> (PUP-12076) Fix windows password compliance issue

- lib/puppet/feature/telnet.rb
This mateches other features such as ssh and zlib to automatically load a library.
> Use Feature's built in library loading to load telnet

- acceptance/tests/ssl/certificate_extensions.rb
This reverts commit d282ec361ca0d73373da35636b76528a3fadad33.
> Revert "(PA-7090) Correct system time on AIX"

- lib/puppet/version.rb
- puppet.gemspec
This reverts commit 603c0d4cea997f3680fb5d51fa3a7e41e4426038.
> Revert "(packaging) Bump to version '99.99.99' [no-promote]"
