puppetlabs/puppet

- lib/puppet/defaults.rb
Soon, the behavior of pluginsyncing will be based on whether or
not a cached catalog is being used. This is to prevent scenarios
where the set of plugins used by the agent is different than the
set that was used when the catalog was originally compiled.
This commit deprecates the setting. Future work will handle the
switchover to the new logic based on cached catalog usage.
> (PUP-5708) Deprecate pluginsync setting

- lib/puppet/util.rb
In commit 292233cea202a4989eaf0fd9a7cf3cb499d66a2c, support was added for ruby
< 1.9.3. Puppet no longer supports ruby versions that old, so this code can be
removed.
> (maint) Remove support for ruby < 1.9.3

- lib/puppet/parser/functions/fqdn_rand.rb
Currently with a default seed of the ::fqdn there is
seemingly a correlation between fqdn_rand(60) and
fqdn_rand(24) reguardless of the fqdn input.
The extra padding ensures the seed is different for the
two intentially independed fqdn calls.
> (PUP-5646) - pad seed fqdn_rand seed with max number

- ext/nagios/check_puppet.rb
replace meth{|my[opt]|} with meth{|o| my[opt] = o}
> (PUP-2909) rubocop - meth{|my[opt]|} is no longer valid syntax in 1.9

- lib/puppet/type/file.rb
- lib/puppet/util/checksums.rb
- spec/unit/type/file_spec.rb
Adds a checksum_value parameter to the file type. Validates that it's
format matches the specified checksum parameter.
> (PUP-5695) Add checksum_value parameter to file type

- lib/puppet/defaults.rb
This commit updates the pluginsync deprecation warning to only present
itself if the setting is actually set via the commandline or by config.
> (PUP-5708) Only emit deprecation warning for pluginsync if explicitly set

- lib/puppet/pops/issues.rb
- spec/unit/pops/evaluator/comparison_ops_spec.rb
Prior to this commit, the method MessageData#label had two functions.
If called with an argument, it presented the String form for that
argument. If called without, it returned a `ModelLabelProvider`. This
made it impossible to produce a message for `nil`.
This commit splits the method in two. One `provider`method that takes
no arguments and just returns the `ModuleLabelProvider` and one that
always returns the String representation of its argument. All calls
are adjusted accordingly.
> (PUP-5741) Fix confusing errors when comparing values

- api/docs/http_report.md
- api/schemas/report.json
- lib/puppet/configurer.rb
- lib/puppet/transaction/report.rb
- spec/unit/configurer_spec.rb
- spec/unit/transaction/report_spec.rb
This commit renames each of the three states of the
'cached_catalog_status' key of the report in order to
better convey their meaning.
The new values are 'not_used', 'explicitly_requested',
and 'on_failure'.
> (PUP-917) Update naming of cached catalog status in report

- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/types/type_parser_spec.rb
Prior to this commit, the TypeParser would not recognize an
UnaryMinusExpression and hence raise an error when one was encountered.
This commit ensures that an unary minus is handled correctly so that
types like `Integer[default, -1]` can be used in a function dispatch.
> (PUP-5712) Fix so that TypeParser can handle negative numbers

- lib/puppet/info_service/class_information_service.rb
- lib/puppet/pops/adapters.rb
- spec/unit/info_service_spec.rb
A parameter default that is not a literal must be represented as
source in the info structure created by the ClassInformationService.
A bug in the SourcePosAdapter where all contained elements were
assumed to have a non-nil offset prevented this function.
This commit fixes the bug and adds a test to verify that the the
source is extracted correctly.
The commit also changes the behavior so that the 'default_source'
entry will always be present in the info structure when a default
expression is present, regardless of if it also contains a
'default_literal' entry.
> (PUP-5713) Let ClassInformationService use source of parameter defaults

- api/docs/http_catalog.md
- lib/puppet/configurer.rb
- lib/puppet/defaults.rb
- spec/unit/configurer_spec.rb
- spec/unit/defaults_spec.rb
- spec/unit/type/file/checksum_spec.rb
Currently, when the agent applies a catalog, it sends a `file_metadata`
request for each file resource along with the `checksum_type` that the
master should use to compute the checksum. The `checksum_type` originates
in either the manifest (and preserved in the catalog), or if none was
specified, the agent's default `Puppet[:digest_algorithm]`.
When static catalogs are enabled, the file metadata inlining process
will need to choose a digest algorithm if none is specified in the
manifest. To ensure the master chooses a checksum suitable for the
agent, the agent needs to send its desired checksum in the catalog
request as a request parameter. Add a checksum_type query param to the
catalog request with an ordered list of algorithms the agent supports,
with the value of …
> (PUP-5120) Send checksum_type and static_catalog in catalog request

- lib/puppet/network/http/pool.rb
- spec/unit/network/http/connection_spec.rb
- spec/unit/network/http/pool_spec.rb
This will allow the socket with the master to get closed when the
network connection breaks unexpectedly, and the agent to terminate with
an error, rather than waiting forever.
According to linux's tcp(7) manpage, such zombies connections get closed
by default after a bit more than 2 hours of idleness. Configuring this
is possible but not considered portable.
> (PUP-5617) enable keepalive on the TCP socket opened with the master

- acceptance/tests/apply/augeas/hosts.rb
- acceptance/tests/apply/augeas/puppet.rb
- acceptance/tests/apply/augeas/services.rb
Prior to this commit the augeas tests were in PE
acceptance tests. This is a vestige of when PE
agent and puppet agent were two different items.
Now in the puppet-agent world we need to move these
tests up so they are in the proper work stream.
> (maint) Move augeas tests into puppet acceptance

- lib/puppet/util/windows/process.rb
- spec/integration/util/windows/process_spec.rb
- The code introduced in 8d02eb133cb2783d976d270b7f2869140a48f0fc did
not properly handle environment variables containing =
This was not found in AppVeyor, local testing, or the ad-hoc
pipeline, but was discovered in the standard Jenkins pipeline
where the BUILD_URL env var is a URL containing = like:
https://jenkins.puppetlabs.com/job/platform_puppet_unit-ruby-win_stable/R=ruby-2.1.5.2-x86,S=unit-win2012/44/
Fix the parsing and add tests to verify
> (PUP-5726) Properly parse Windows env vars with =

- acceptance/tests/ssl/autosign_command.rb
- acceptance/tests/ssl/certificate_extensions.rb
This is a temporary adjustment to the CA autosign acceptance tests to
use a version of /bin/true that will drain the stdin stream. This is
necessary to get the test passing against Puppet Server while we work on
a bug fix for SERVER-1116.
> (maint) Use draining /bin/true for autosign tests

- lib/puppet/type/user.rb
Per DOC-455, generalize and update references to password hashes.
> (docs) Update password hash documentation.

- lib/puppet/functions/each.rb
- lib/puppet/functions/filter.rb
- lib/puppet/functions/map.rb
- lib/puppet/functions/reduce.rb
- lib/puppet/functions/slice.rb
- lib/puppet/pops.rb
- lib/puppet/pops/evaluator/runtime3_converter.rb
- lib/puppet/pops/types/enumeration.rb
- lib/puppet/pops/types/iterable.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- spec/lib/puppet_spec/compiler.rb
- spec/shared_behaviours/iterative_functions.rb
- spec/unit/pops/evaluator/runtime3_converter_spec.rb
- spec/unit/pops/types/iterable_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
This PR adds the new types `Iterable` and `Iterator` to the Puppet
type system together with the runtime support needed to represent an
object that has been transformed into an Iterator by a call to
`Iterable.on`. This method transforms an instance of an object that
Puppet can use in iterative functions into an Iterator. The Iterator
in turn, provides basic support for the iterative functions.
The PR also changes the iterative functions `each`, `filter`,
`map`, `reduce`, and `slice` so that the type of their declared
_enumerable_ parameter is `Iterable` instead of `Any`
> (PUP-5648) Add Iterable and Iterator to Puppet Type System

- ext/build_defaults.yaml
Ruby for windows was rebuilt with openssl 1.0.2f to address
CVE-2016-0701. This updates to use the latest ruby build.
> (maint) Update windows ruby builds

- spec/unit/network/http/pool_spec.rb
The sockopt data layout is platform-specific, and on Mac the result of
creating a boolean doesn't match `getsockopt(...).data`. Comparing the
data was originally a work-around for Windows because
`getsockopt(...).bool` produced an error. Switch to using bool on all
platforms but Windows.
> (maint) Fix spec test on Mac OS X

- spec/integration/util/execution_spec.rb
Previously there were no tests for creating processes with UTF8
characaters in the command line.  This integration test is required
to guard against regression failures whereby future changes may cause
commands in Non-English Operating Systems to fail e.g. Script files
in a user's directory where the user has non-english characters in the
username, such as Umlaut.  This commit adds a single test for running
a command with UTF8 charaters in the command line.
> (PUP-5736) Add test for Win32-Process and UTF8 filepaths

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
Adds an inline_metadata method called during catalog compilation, but
after parsing the catalog. This method will be used for inlining
metadata as part of building a static catalog.
Inlines checksum_value for plain files.
> (PUP-5117) Add inline_metadata method during catalog compile

- benchmarks/function_loading/benchmarker.rb
- benchmarks/function_loading/description
- benchmarks/function_loading/puppet.conf.erb
- benchmarks/function_loading/site.pp.erb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/loader/base_loader.rb
Before this the function_loading benchmark failed with a out of stack
error. This was caused by a combination of the deep recursion set up by
the benchmark, and that the rutime needs additional stack levels per
call.
The benchmark logic also had flaws that had gone undetected in older
puppet versions. Now with stricter module visibility rules the benchmark
generated modules did not have the correct deendencies in meta data.
This changes the recursion to not go as deep and fixes the module
dependency problems. The number of runs/modules/funcions were also
lowered to reduce the running time of the benchmark as he additional
iterations does not provide more information.
One problem remains - each iteration takes about 25% longer than the
previous. There could be a natural explanatoin for …
> (PUP-5724) Backport PUP-5693 Make function_loading benchmark operational

- lib/puppet/util/network_device/transport/ssh.rb
PUP-5291 fix "stream closed" problem with SSH transport closing the session with the IO handles still open
> PUP-5291 fix "stream closed" problem with SSH transport

- lib/puppet/agent.rb
- lib/puppet/application/device.rb
- lib/puppet/configurer.rb
- spec/unit/agent_spec.rb
- spec/unit/configurer_spec.rb
Prior to this commit, when attempting to use a cached catalog
the client would always make a node request and pluginsync,
even if there was a cached catalog available. This could cause
inconsistencies where the set of plugins used by the agent is
different than the set that was used when the catalog was
originally compiled.
This commit updates the client to first try to retrieve a cached
catalog if requested, skipping the node request and pluginsync.
In addition, if the agent's current environment differs from that
of the cached catalog, we now immediately switch to the cached
catalog's environment rather than going through the environment
convergence loop.
> (PUP-5703) Handle cached catalog and pluginsync inconsistencies

- lib/puppet/info_service/class_information_service.rb
- lib/puppet/pops/evaluator/json_strict_literal_evaluator.rb
- spec/unit/info_service_spec.rb
- spec/unit/pops/evaluator/json_strict_literal_evaluator_spec.rb
This PR has two commits:
* The first adds a JsonStrictLiteralEvaluator, which is similar to the LiteralEvaluator, but that only accept values as literals if they can be directly represented in JSON - i.e. no default or regexp values, or hashes with non string keys.
* The second changes the class_information_service to use the JsonSrictLiteralEvaluator instead of he LiteralEvaluator since the later accepts any puppet literal.
> (PUP-5744) Make class_information_service produce json-safe literals

- ext/windows/puppet_interactive.bat
- ext/windows/puppet_shell.bat
- ext/windows/run_puppet_interactive.bat
- install.rb
With the switch over to building puppet-agent for windows with Vanagon,
we need to effectively install puppet with install.rb. This script
installs puppet.bat, which is a wrapper that lets windows handle ruby
scripts. This commit updates puppet.bat to use our environment.bat file if
we install it, and to be more in line with the puppet.bat file installed
with the puppet-agent package as built by puppet_for_the_win
This takes advantage of `environment.bat` in puppet-agent installed with https://github.com/puppetlabs/puppet-agent/pull/512
> (PUP-5718) Update puppet.bat to current standard

- lib/puppet/configurer.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/parser/environment_compiler.rb
- lib/puppet/parser/functions.rb
- lib/puppet/pops/adaptable.rb
- lib/puppet/util/autoload.rb
- spec/unit/configurer_spec.rb
This PR contains two commits. The first that deals with a memory leak cause by a class-level instance variable that holds on to functions (puppet functions created in Ruby) that in turn have a dynamic scope that holds on to an environment. The second deals with the global $env_module_directories, a hash that uses environments as keys. Both commits uses the same approach for solving the problem. A dedicated adapter object that is adapted to the environment for which they hold data.
> (PUP-5813) Prevent memory leaks due to environments that doesn't get garbage collected

- lib/puppet/functions/reverse_each.rb
- lib/puppet/pops/types/iterable.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/functions/defined_spec.rb
- spec/unit/functions/reverse_each_spec.rb
This PR adds the new function `reverse_each(iterable)`. The function takes an iterable argument and an optional block.
If a block is given, it will be called with all elements of the given argument in reverse order.
Without a block, the function will return a new Iterable that will yield each element of the given argument in reverse order.
> (PUP-5729) Add iterative reverse_each function

- lib/puppet/functions/reverse_each.rb
- lib/puppet/functions/step.rb
- lib/puppet/pops/types/iterable.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/functions/defined_spec.rb
- spec/unit/functions/reverse_each_spec.rb
- spec/unit/functions/step_spec.rb
This PR adds the new function `step(iterable, n)`. The function takes two arguments, an iterable and an integer, and an optional block.
If a block is given, it will be called with each nth element of the given argument.
Without a block, the function will return a new Iterable that will yield each nth element of the given argument.
> (PUP-5730) Add iterative step function

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
This commit updates the static compilation inlining logic to
handle symlinks which have their `links` parameter set to manage.
The `source` parameter of such a resource references one of two
items: a link or a regular file.
When `source` references a link, the destination of that link is
inlined directly into the `target` parameter of the new resource.
If `source` references a regular file, the existing logic holds
and file content is copied into the new resource.
When `links` is set to `follow`, we fall back to the regular
content inlining behavior, which sets the `checksum_value` of
the new resource.
> (PUP-5699) Inline symlink metadata in static catalog

- lib/puppet/application/agent.rb
- lib/puppet/application/apply.rb
- lib/puppet/configurer.rb
- spec/unit/application/agent_spec.rb
- spec/unit/application/apply_spec.rb
- spec/unit/configurer_spec.rb
Previously, it was possible to run an agent in noop mode in a canary environment, but during the next normal agent run, it could fall back to the previously cached catalog from the noop run, causing changes to be deployed into production there were never meant to be.
The short version for this PR is: Don't save cached catalogs when running in `noop` mode and only fallback to a cached catalog whose environment matches the agent's configured environment, either through the ENC or agent-specified environment.
> (PUP-3077) Handle cached catalog inconsistencies

- lib/puppet/info_service/class_information_service.rb
- spec/unit/info_service_spec.rb
Before this, when a file did not exist it was retured as an empty set of
values.
Now, if the file does not exist it returns a mapping of:
{THEFILE.pp => {:error => "The file THEFILE.pp does not exist"}
> (PUP-5807) Produce error in class_info_service when file does not exist.

- lib/puppet/info_service/class_information_service.rb
- spec/unit/info_service_spec.rb
Before this, the class infor per file was returned in an array:
```
filename => [ {}, {}, ... ]
```
Now, the information is returned as:
```
filename => {:classes => [ {}, {}, ... ] }
```
Note that all the changes in the tests are only because of the added layer of {:class => ...}
> (PUP-5809) Change class-info-service return to wrap classes

- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- spec/integration/parser/compiler_spec.rb
Before this, only relationships formed with the relationship
operations <- -> <~ and ~> were validated. This validation checkes that
the referenced resource exists in the catalog and reports an error if
not.
The identical relationship formed via use of the meta parameters after,
require, subscribe, and notify were not validated. This led to that
errors in catalogs were not caught until the catalog was applied on the
agent.
This commit makes use of the recently added catalog validators and adds
validatio of all relationships.
When making this change the existing code in the relationship validator
needed refactoring. It was then detected that it used an array.find and
a predicate lambda to see if a variable was one out of 3 possible
symbols. That was measured to be 6x slower that the …
> (PUP-5659) Validate all relationships

- lib/puppet/data_providers/hiera_interpolate.rb
- spec/unit/data_providers/hiera_interpolation_spec.rb
Before this, an empty interpolation such as `%{}` was not considered
an interpolation at all. The interpolation regexp required at least one
character between the curly braces.
This commit will allow the empty interpolation and will also ensure
that the expression between the curly braces is trimmed from whitespace
at both ends. If the result of that trim yields the empty string or
a string that only contains a name separator '::', then the interpolated
result will be the empty string.
It is still possible to have interpolated expressions where the key has
leading or trailing whitespace by using the function syntax, e.g.
%{hiera(' key ')}.
> (PUP-5824) Support empty interpolation in Hiera data provider

- .travis.yml
- There have been intermittent failures occurring on Ruby 2.1.8 in
TravisCI when attempting to build / install native gems:
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
This is currently affecting JSON 1.8.3 and msgpack 0.7.4.  This
appears to be fixed by downgrading to Ruby 2.1.7
> (maint) Downgrade TravisCI Ruby 2.1.8 to 2.1.7

- lib/puppet/application/apply.rb
- lib/puppet/application/lookup.rb
- lib/puppet/face/epp.rb
- lib/puppet/face/parser.rb
- lib/puppet/file_system.rb
- lib/puppet/file_system/file_impl.rb
- lib/puppet/file_system/memory_impl.rb
- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/parser/lexer2.rb
- lib/puppet/util/resource_template.rb
- spec/unit/face/parser_spec.rb
- spec/unit/file_system_spec.rb
- spec/unit/pops/loaders/dependency_loader_spec.rb
- spec/unit/pops/parser/lexer2_spec.rb
- spec/unit/util/resource_template_spec.rb
- In PUP-2564, documentation was changed to indicate that all manifest
are expected to be in UTF-8 as part of Puppet 4.0.
However, this is not actually enforced, and causes problems on Windows.
There are more details to be sorted out on this, and I haven't run tests fully yet - but this is a good starting point for looking at this problem.
> (PUP-5728) Always load manifests as UTF-8

- lib/puppet/pops/evaluator/evaluator_impl.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
Before this a splat on an Iteraor had no effect - it resultet in the
Iterator (as it was an atomic value).
Now the splat operator will produce an intance of Array from the
iterable. If used in a context where the splat means that the array is
ufolded, it will also be unfolded.
> (PUP-5836) Make splat create Array from Iterator

- lib/puppet/defaults.rb
Add note about "Values must be comma-separated" like we do for tags and
reports settings.
> (maint) Add note about comma delimiting supported checksum types

- lib/puppet/pops/issues.rb
- lib/puppet/pops/parser/lexer2.rb
- lib/puppet/pops/parser/lexer_support.rb
- spec/unit/pops/parser/lexer2_spec.rb
See the commit e16a204 for details about this PR.
> (PUP-5819) Error on byte order mark in lexer

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
This test calls puppet lookup to find values for symbols resolved: (1) global hiera, (2) per-environment data providers (hiera, ruby-function, and puppet-function), (3) per-module data providers (hiera, ruby-function, and puppet-function).
Environments are selected by (1) default, (2) command line option (--environment <env>), (3) by setting in puppet.conf and (4) by a simple external node classifier (enc.rb) specified in puppet.conf.
Tests are executed for symbols defined at each location, symbols defined in more than one location (to ensure definition is from proper location in hierarchy) and symbols that are not resolved at any provider.
[skip ci]
> (PUP-5472) Acceptance test for puppet lookup command

- lib/puppet/node.rb
- lib/puppet/parser/compiler.rb
- spec/unit/node_spec.rb
- spec/unit/parser/compiler_spec.rb
Before this, if a node parameter had a Ruby Symbol value it would leak
to Scope, and into variables. This was especially true for the
$environment variable after at enviroment name is made into a Symbol.
This commit fixes the problem both by ensuring that when a node sets a
parameter (in itself) based on the environment's name it transformed the
symbolic name to a Strig, and in the general case, the compiler when
setting parameters for a node, will also transform a Symbol value to
Strig. The later to ensure the same kind of mistake does not leak out to
Scope.
This commit also includes unit tests that asserts that environmet name
as a symbol dos not leak, nor any other node parameter.
> (PUP-5835) Make node params String if they are Symbol

- lib/puppet/pops/types/iterable.rb
- spec/unit/pops/types/iterable_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this commit, the Iterator runtime implementation had no to_s
method. This commit adds that so that it prints:
"Iterator[T] value"
instead of the default and somewhat incomprehensible:
"<Puppet::Pops::Types::Iterator:0x007f93ec28f938>"
The commit also adds some missing tests for Iterable and Iterator
to_s methods.
> (PUP-5875) Add to_s to Iterator runtime implementation

- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/parser/egrammar.ra
- lib/puppet/pops/parser/eparser.rb
- lib/puppet/pops/parser/parser_support.rb
- spec/unit/pops/parser/parse_calls_spec.rb
Before this an expression like:
```
notice {a=>2}
```
Would result in an internal error.
That was caused by the "tree rewrite" that changes that expression from
being a resource expression without title to a function call with a hash
as an argument. When the hash had no location information it lacked
offset and length of its textual representation in source text.
This is now fied by propagating the tokens for the left and right braces
to the rewrite operation that now sets them.
> (PUP-5805) Set missing location in generated hash

- lib/puppet/pops/types/type_calculator.rb
- spec/unit/pops/types/type_calculator_spec.rb
This removes surprising output when doing:
```
notice Array
notice Hash
```
> (PUP-5861) Make Data matching Arrray and Hash not present type parameters

- lib/puppet/defaults.rb
- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/environments_spec.rb
- spec/unit/indirector/catalog/compiler_spec.rb
- spec/unit/settings/environment_conf_spec.rb
They will only be generated if code_id is provided when compiling the
catalog.
> (PUP-5876) Enable static catalogs by default

- lib/puppet/functions/reverse_each.rb
- lib/puppet/functions/step.rb
- spec/unit/functions/reverse_each_spec.rb
- spec/unit/functions/step_spec.rb
This PR changes the `step` and `reverse_each` functions so that so that they return the undef value instead of their first argument. This change was made to avoid any confusion on if the returned value is reversed, stepped, or if it somehow contains values returned from the given block.
> (PUP-5837) Change reverse_each and step functions to return undef when given a block

- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/type/file.rb
- spec/unit/indirector/catalog/compiler_spec.rb
Update the catalog compiler so it inlines directory metadata for
static catalogs. This means that when there is a file resource
that is a directory and has recurse set to true, we will add resources
for all it's children to the catalog.
In order to support this, make a few changes to the file type as
well so that we can easily reuse functionality for static catalogs.
> (PUP-5698) In-line directory metadata

- lib/puppet/functions/slice.rb
Fairly certain from searching the codebase and google that this is fixing a typo in the slice function.
I did not conform to the contributing guidelines on this because it was such a trivial fix, but I can cancel the PR and go through the process if need be.
> (maint) fixing a typo: :slize_size to :slice_size

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
Refactor the inline catalog unit tests to use `manifest_to_catalog` helper and resource matchers. I ran into an issue where generated resources didn't have an ensure value and calling `to_ral` doesn't work when you're on *nix and it's a Windows file path. The ensure value part is fixed in this PR, and I added a pending test for the second part. I recommend using `git log -p --reverse --patience 0dfeecd..` to review the changes.
> (maint) Use catalog and resource matchers

- lib/puppet/type/file.rb
- lib/puppet/type/file/checksum_value.rb
- lib/puppet/type/file/content.rb
- lib/puppet/type/file/data_sync.rb
- lib/puppet/type/file/ensure.rb
- lib/puppet/type/file/source.rb
- lib/puppet/util/checksums.rb
- spec/integration/type/file_spec.rb
- spec/unit/type/file/checksum_value_spec.rb
- spec/unit/type/file/content_spec.rb
- spec/unit/type/file/source_spec.rb
- spec/unit/type/file_spec.rb
If the checksum_value property is specified, use it instead of content
for verifying whether a file is insync.
Changes checksum_value to a property, and moves implementation of
writing data from source to the source parameter, rather than delegating
through a content property (which is no longer assumed to exist).
Separates writing source from content so it can be used by
checksum_value. In some cases content still triggers the write.
> (PUP-5701) Use checksum_value instead of content if specified

- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
This PR fixes three things.
1. The PTypeAlias is renamed to PTypeAliasType
2. The PTypeReference is renamed to PTypeReferenceType (didn't deserve an issue of its own)
3. The type mismatch describer reports type aliases by alias name instead of type name
> (PUP-5892) Alias types are presented with the wrong name in type mismatches

- lib/puppet/pops/evaluator/runtime3_support.rb
- spec/integration/parser/dynamic_scoping_spec.rb
This fixes a remaining "relative namespaces" issue in 3.x with future parser. (See ticket or commits for details).
WHEN MERGING TO 4X:
Follow the instructions given in comments:
* runtime_3_support contains code that should be removed in 4.x
* the dynamic_scoping_spec.rb should be added to 4.x but edited as instructed in comments in that file.
> (PUP-4818) Make class references absolute

- lib/puppet/data_providers/hiera_config.rb
- lib/puppet/data_providers/hiera_support.rb
- lib/puppet/data_providers/json_data_provider_factory.rb
- lib/puppet/data_providers/yaml_data_provider_factory.rb
- lib/puppet/plugins/data_providers/data_provider.rb
- spec/fixtures/unit/functions/lookup/environments/production/modules/bad_data/lib/puppet/functions/bad_data/data.rb
- spec/fixtures/unit/functions/lookup/environments/production/modules/bad_data/manifests/init.pp
- spec/fixtures/unit/functions/lookup/environments/production/modules/hieraprovider/data/first.json
- spec/unit/functions/lookup_spec.rb
This PR changes the behavior when validating the data of a module data provider so that:
- It is no longer considered an error if a key is unqualified. Instead a warning is logged.
- The validation works the same way for all types of module data providers (a design flaw prevented the Hiera module data provider from validating correctly).
Details can be found in the commit comments.
> (PUP-5761) Log warning instead of raising error when bad keys are detected in module data

- lib/puppet/provider/package/yum.rb
- spec/unit/provider/package/yum_spec.rb
Without this patch applied, the Yum package provider assumes all version
epochs are "0", i.e. a package with version "1:1.2.3-4.el5" will be
interpreted as having epoch "0" not "1". This causes version comparisons
made by puppet to be incorrect when comparing packages of different
epoch's.
This bug is caused by the line:
```
e = String(Bignum(e)) rescue '0'
```
Bignum is not a function, so the line always throws an exception and the
rescue is always invoked.
This patch uses Integer instead of Bignum, rescues the specific
exception needed (this is so that an epoch like "foo" is coerced into
"0"), and provides a test for non-zero epochs
> (PUP-5802) Make the Yum package provider correctly parse epochs

- lib/puppet/pops/types/type_calculator.rb
- spec/unit/pops/types/type_calculator_spec.rb
This makes minimal changes to fix the :undef problem described in
PUP-5898 when using parser=future on 3.x.
> (PUP-5898) Backport fix for :undef to 3.x from 4x.

- lib/puppet/pops/types/type_calculator.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this, if :undef was found in data coming from 3.x API into 4.x it
was inferred as Runtime[ruby, 'Symbol'] causing type mismatches to
occur.
This is now changed so that it is inferrd to be an Undef.
Unfortunately we had to revert the change that made :undef be treated as
an alien Ruby Symbol. It was intended to catch :undef leaking, but all
we achived was to catch ourselves in the act - and it is difficult to do
anything about this as some resurces do need 3.x call semantics and
others don't. It is not known a priori which ones.
> (PUP-5898) Make :undef be inferred as Undef (aka. bring back the undead)

- acceptance/tests/resource/package/common_package_name_in_different_providers.rb
If the environment variable GEM_SOURCE is specified on the master,
add it to the gem package resources as a source to remove external
dependencies. Without this we get transient failures when rubygems.org
has issues.
> (PUP-4929) Fix acceptance test to specify a gem source

- lib/puppet/configurer.rb
- lib/puppet/defaults.rb
- spec/unit/configurer_spec.rb
This commit adds a new Puppet option: `strict_environment_mode`.
This option ensures that the agent-specified environment is considered
authoritative, and fails the run if the environment of the retrieved
catalog does not match.
> (PUP-5815) Add strict_environment_mode option

- spec/unit/configurer_spec.rb
When running Puppet::Configurer::run_internal in spec tests,
attempting to send the report and write the class file error out
due to arbitrary files not existing on the filesystem. Stub
the methods responsible for these calls out so the error we are
trying to actually test can more cleanly be tested.
> (maint) Properly stub configurer methods to prevent errors in tests

- acceptance/tests/direct_puppet/cached_catalog_remediate_local_drift.rb
This commit adds the skeleton of an acceptance test for the scenario
where the server tells the agent to run from its cached catalog and
remediates local drift to file content.
Once further work has been done on actually retrieving file content
using content_uri (PUP-5114), this test will be expanded.
> (PUP-5122) Add acceptance test for direct puppet running from cache

- acceptance/tests/resource/package/common_package_name_in_different_providers.rb
When using GEM_SOURCE, the initial acceptance change fails because the
URL is unquoted. Quote it.
> (PUP-4929) Quote GEM_SOURCE path in puppet manifest

- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/type/file.rb
- spec/unit/indirector/catalog/compiler_spec.rb
- spec/unit/type/file_spec.rb
Prior to this commit, the compiler could not handle duplicate file
resources when recursively in-lining metadata. This meant that a case
where a file is explicitly managed and also covered by its parent
directory which has recurse turned on would raise an error.
Now this case is handled by using remove_less_specific_files to
prune out duplicate resources. We will always keep the explicitly
managed version of the resource over the one generated by recursion.
> (PUP-5118) Manage duplicate file resources

- lib/puppet/util/windows/user.rb
Without this commit, the detection of administrative rights on legacy
Windows operating systems (2003/XP) is incorrect.  The helper function
read_win32_bool returns a boolean type however it is compared against
an integer which causes the detection to always succeed.  This commit
uses the helper function return value directly.
> (PUP-5923) Fix Admin Token detection on legacy Windows OS

- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/type/file.rb
- lib/puppet/type/file/source.rb
- spec/unit/configurer/downloader_spec.rb
- spec/unit/indirector/catalog/compiler_spec.rb
- spec/unit/type/file/source_spec.rb
- spec/unit/type/file_spec.rb
Inlines `owner`, `group`, and `mode` permissions when
`source_permissions` is `use`. Not inlined when it's `ignore`, and
raises an error if `use_when_creating` is requested.
For Windows, modified how we assert that `source_permissions => use`
will not be used on Windows so it's still checked for the static
catalog. Check is done client-side, as the master usually doesn't care
what OS the client is.
Also added a maint change to always set :ensure and :checksum to prompt discussion.
> (PUP-5697) Inline file permissions to the static catalog

- lib/puppet/configurer.rb
- spec/unit/configurer_spec.rb
This commit ensures that if a cached catalog is explicitly requested
and strict environment mode is also requested, we do *not* switch the
local environment to match the cached catalog, as we do in all other
cases. This will cause the run to fail if the cached catalog's
environment does not match the agent specified environment.
> (PUP-5815) Handle cached catalogs with strict environment mode setting

- spec/integration/parser/undef_param_spec.rb
This commit adds an integration test that asserts that a given undef
parameter will be used when no parameter default expression exists
for resource declared with a `define` declaration.
> (PUP-5936) Add test to verify that given undef removes need for default

- acceptance/Gemfile
- acceptance/lib/puppet/acceptance/environment_utils.rb
- acceptance/tests/language/exported_resources.rb
This change adds a test that uses a yaml terminus for storeconfigs to
test exported resources.  Due to a deficiency in the yaml storeconfigs
terminus we create here, we can not use with_puppet_running_on.
This test solely collects all resources of a given type.  Because filtering is implemented in the puppetdb terminus, it does no good to test it here.  Even testing collecting various types would do no good since this matching is also done in the terminus.  
[skip ci]
> (PUP-5569) acceptance: ensure Resource Collectors can use resource references in search expressions

- acceptance/Gemfile
- acceptance/lib/puppet/acceptance/environment_utils.rb
This change uses Set instead of SortedSet which requires external gems
and could be actually slower in many cases than searching a Set which is
a valueless hash in ruby.
[skip ci]
> (PUP-5569) acceptance: use Set for mk_tmp_environment instead of SortedSet

- acceptance/lib/puppet/acceptance/static_catalog_utils.rb
- acceptance/tests/direct_puppet/cached_catalog_remediate_local_drift.rb
The first of these commits adds a new static catalog helper in lib/acceptance, abstracted away from the original direct puppet from cache test.
The second commit corrects an error with the `versioned-code` puppetserver.conf settings and removes the `expect_failure` from the test.
Tested in Centos and windows, both pass.
/cc @MikaelSmith @joshcooper
> (maint) Remove expectation of failure in direct puppet cache test

- lib/puppet/indirector/catalog/compiler.rb
This PR includes commits which add some profiling to help compare static catalog compiles to non-static catalog compiles as well as maintain counts for how often file metadata is and is not being inlined, and when not, for what reasons.
> (PUP-5121) Add profiling for static catalog and file metadata

- acceptance/lib/puppet/acceptance/static_catalog_utils.rb
- acceptance/tests/direct_puppet/cached_catalog_remediate_local_drift.rb
Previously, the `remediate_local_drift` test for direct puppet was
modifying the puppet-server configuration to enable static
compilation, but was not restoring that state. This adds a proper
teardown step which cleans up the master configuration and removes the
files for the test environment.
> (maint) Add teardown step to direct puppet test

- ext/project_data.yaml
- lib/puppet/util/windows/access_control_list.rb
- lib/puppet/util/windows/security.rb
- lib/puppet/util/windows/sid.rb
- spec/integration/type/file_spec.rb
- spec/integration/util/windows/security_spec.rb
- spec/unit/util/windows/adsi_spec.rb
- spec/unit/util/windows/security_descriptor_spec.rb
- spec/unit/util/windows/sid_spec.rb
The functionality of the Win32-Security gem has been merged into Puppet.
This commit moves the last of enumerations and updates the test suites to
use the newer namespace of Puppet::Util::Windows:SID.  This commit removes
Puppet's requirement of the win32-security gem, however the gem itself
still exists in the ruby gem library.  It will be removed from the library
in later commits.
> (PUP-5735) Remove requirement of Win32-Security gem from Puppet

- lib/puppet/transaction/additional_resource_generator.rb
- spec/integration/type/tidy_spec.rb
Recursive tidy resources depended on the resources returned by tidy's
`generate` to be handled by the additional_resource_generator in a
specific order. This restores that order. I actually think that this
is "correct" for all depth-first resources, and any depth-first
generation has been wrong since PUP-1963. This also adds a test for
Tidy, since we apparently didn't have any.
> (PUP-5963) Restore functionality of recursive tidy resources

- lib/puppet/transaction/resource_harness.rb
- spec/unit/transaction/resource_harness_spec.rb
Due to how resource generation was implemented, the purge check for
resource dependencies was actually broken until PUP-1963, which
accidentally caused that check to work.
Since that check has been broken for a long time, and users generally
have an expectation of being able to attach dependencies to a purge,
the check should be removed.
> (PUP-4748) Allow purging of resources that have dependencies

- api/docs/http_catalog.md
- api/docs/http_report.md
- api/schemas/catalog.json
- lib/puppet/resource/catalog.rb
- spec/unit/resource/catalog_spec.rb
Adds a `catalog_format` field to the catalog identifying the schema
version. That way future readers of the catalog can know what data
to expect. Also updates the api doc and schema to reflect the current
catalog_format version 1.
> (PUP-5970) Add catalog format

- lib/puppet/functions/regsubst.rb
- spec/unit/functions/regsubst_spec.rb
Allow a hash as replacement parameter to the function regsubst again as
it was possible with puppet 3.x.
> (PUP-5979) regsubst: hash as replacement parameter

- lib/puppet/type/sshkey.rb
The `sshkey` resource can managed more than just the global
`/etc/ssh/ssh_known_hosts` file. For example, if you specify a user's
personal `known_hosts` file, you can manage known hosts for a user.
> (PUP-5812) Made the docstring for sshkey more accurate

- lib/puppet/defaults.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/settings.rb
- lib/puppet/settings/symbolic_enum_setting.rb
- spec/unit/defaults_spec.rb
- spec/unit/parser/scope_spec.rb
This adds a --strict flag that can be set to warning, error or ignore. In this PR this new setting is made to play nicely with the --strict_variables such that, if --strict_variables is true then it always errors (this is what users expect). If it is not set, the behavior is controlled by the --strict setting.
The default for --strict is warn. This is also what is expected for --strict_variables (by default). Users can opt out by setting --strict=off.
It is expected that the --strict flag will be used in different ways for new kinds of validations. In this PR one tricky thing is to maintain the API for those that call directly into scope (not being prepared to catch the symbol :undefined_variable. This is now done by always throwing :undefined_variable, and catching the resulting …
> (PUP-5889) add a strict flag

- lib/puppet/pops/model/ast_transformer.rb
- lib/puppet/resource/type_collection.rb
Merge PUP-5889 before this PR as this depends on the --strict setting being present.
This PR errors or warns under the control of --strict if a user redefines/reopens a class. This is still allowed for the class named '' (a.k.a 'main'). as that is the compilers way of merging all top scope logic.
> (PUP-2695) Deprecate reopening and merging classes other than "top scope"

- lib/puppet/pops.rb
- lib/puppet/pops/evaluator/literal_evaluator.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/validation.rb
- lib/puppet/pops/validation/checker4_0.rb
- lib/puppet/pops/validation/validator_factory_4_0.rb
- spec/unit/pops/validator/validator_spec.rb
This PR is rebased on top of the PR for PUP-5889 which adds the --strict flag.
Merge PUP-5889 before merging this.
Replaces #4691
> (PUP-5937) Detect duplicate keys in hashes

- acceptance/lib/puppet/acceptance/static_catalog_utils.rb
On some platforms, `/bin/sh` is actually a link to `/bin/dash`
which doesn't handle conditional statements in the same way as
bash. This commit updates the static catalog utils code id and
code content scripts to use `bash` instead of `sh`.
[skip-ci]
> (maint) Use /bin/bash instead of /bin/sh in direct puppet test

- lib/puppet/resource/status.rb
- lib/puppet/util/log.rb
- spec/integration/transaction/report_spec.rb
Resource::Status and Util::Log objects were not including PsychSupport
to allow them to serialize their tags member as an array.
> (PUP-5341) Emit TagSets as arrays in report YAML

- appveyor.yml
AppVeyor instances now come with bundler pre-installed (see
https://www.appveyor.com/docs/installed-software). Remove the step
installing bundler.
> (maint) Skip updating bundler in AppVeyor

- lib/puppet/data_providers/hiera_interpolate.rb
- spec/unit/data_providers/hiera_interpolation_spec.rb
This commit improves the Hiera data provider so that it performs
interpolation of data found in arrays and hashes. The interpolation of
such data is recursive. Prior to this commit, only interpolations found
in strings at the topmost level were interpolated.
> (PUP-5983) Enable interpolation of nested data in hiera data provider

- .travis.yml
Now that https://bugs.ruby-lang.org/issues/11928 is fixed in the 2.3 ruby
branch (but not yet released), we can test against the 2.3.0-dev rvm version
in travis.
When 2.3.1 is released, we should bump to 2.3.1 as we don't really need to
track 2.3.0-dev.
> (maint) Restore 2.3.0 testing in travis

- spec/integration/type/package_spec.rb
The package_spec test was incorrect when run on Fedora 23, because the
default provider changed. Update the test to report `dnf` on Fedora 23.
> (maint) Fix package_spec on Fedora 23

- acceptance/tests/direct_puppet/catalog_uuid_correlates_catalogs_with_reports.rb
This commit adds a new acceptance test which ensures that reports
from cached catalog runs can be linked to a specific catalog using
catalog_uuid.
> (PUP-5872) Add acceptance test for catalog and report correlation

- acceptance/Rakefile
Provides default test targets to run on both Windows and Linux agents
when TEST_TARGET isn't specified. Provides a sane set of defaults for
verifying that tests will work.
> (maint) Add default TEST_TARGET when none specified

- acceptance/tests/direct_puppet/static_catalog_env_control.rb
This test verifies that the environment.conf setting:
static_catalogs = [true | false] controls whether catalogs for that
environment are static catalogs or not.  The same setting in
puppet.conf will determine the default behavior, that it if the
setting is not specified in environment.conf.  If the setting is not
specified in either configuration file, then static catalogs are
enabled by default.
[skip ci]
> (PUP-5866) Per-environmment control of static catalogs

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
Previously the test assumed there was a single agent, but when run with
multiple agents, beaker's `agent` method returns an array. And since
`on` accepts an array of hosts, and returns an array of results, we were
trying to call Array#stdout and failing.
This commit updates the test to use the first non-master agent. The test
then runs `puppet lookup --node <agent>` on the master. Since the test
is exercising lookup functionality on the master, we don't need to
repeat it for every agent.
The test also failed on master platforms that didn't have system ruby
installed in /bin/ruby, e.g. debian8. Instead we use privatebindir to
resolve ruby, which works for aio and git.
> (maint) Support multi-agent acceptance configurations

- acceptance/tests/direct_puppet/cached_catalog_remediate_local_drift.rb
…t only when drift is detected.
This PR adds a few test steps to an existing acceptance test,
puppet/acceptance//tests/direct_puppet/cached_catalog_remediate_local_drive.rb.
The new steps ensure that when the file has not drifted:
(1) the client does not make any requests to the server (for
file data or file metadata) and (2) the cached catalog application
results in report to the server.
It works by doing the following:
- Remove reports from server's report directory,
verifies "ls -l <report_directory> | wc -l" returns "0".
- Start a puppet run with options given to use the cached
catalog and to specify a non-existent server (no_such_host)
and to specify the actual server as the report server
destination.  If the agent issues a request to the server
(except for report delivery), the run …
> (PUP-5862) Only request file content when remediating drift 

- acceptance/tests/direct_puppet/static_catalog_env_control.rb
This commit updates the acceptance
`direct_puppet/static_catalog_env_control` test to use the beaker
`node_name` value when referencing value for puppet catalog
validation.
Prior to this change, the test would fail if the `hostname` was
not the same as the `node_name`.
> (PUP-6017) Use beaker node_name in static cat test

- lib/puppet/pops/types/types.rb
- spec/unit/pops/evaluator/access_ops_spec.rb
The Puppet type system used a `==` method in the topmost `PAnyType` and
then other types added overrides for that method. The topmost class
also declared `eql?` as an alias for `==`. This didn't work very well
because an alias is hard wired to the method in the class where it is
declared. It does not recognize that the method is overridden.
This commit changes all `==` methods in the `PAnyType` hierarchy to
`eql?` methods and adds a proper delegation method in the topmost
superclass.
> (PUP-6020) Use eql? and proper method override for == for Puppet Types

- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/type_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
- spec/unit/pops/types/types_spec.rb
This PR contains new functionality that enables puppet types to be normalized and then what's needed to make the TypeMismatchDescriber take advantage of that.
The details are in the commit messages.
> (PUP-5901) Make type mismatch describer use normalized types.

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
The service provider on systemd systems currently only use systemctl
command to check to service status. The patch aims to support customize
status command when using service type.
> (PUP-5992) Support custom status command for systemd provider

- api/docs/http_api_index.md
- api/docs/http_catalog.md
Puppet Server 2.3 adds its own `/puppet/v3/` endpoints for static file content and per-environment classes. Link to the Puppet Server documentation being written for these new endpoints from the Puppet API index, and add a supporting link for static catalogs to the `http_catalog` documentation.
Supports SERVER-1108 and SERVER-1114 for the Puppet 4.4 and Server 2.3 releases.
> (doc) Link to Puppet Server-specific API endpoints.

- lib/puppet/defaults.rb
- lib/puppet/file_system/uniquefile.rb
- lib/puppet/node/environment.rb
- lib/puppet/test/test_helper.rb
- lib/puppet/util.rb
- lib/puppet/util/windows/api_types.rb
- lib/puppet/util/windows/process.rb
- spec/integration/defaults_spec.rb
- spec/integration/file_system/uniquefile_spec.rb
- spec/integration/node/environment_spec.rb
- spec/integration/test/test_helper_spec.rb
- spec/integration/util_spec.rb
- spec/unit/util/run_mode_spec.rb
- spec/unit/util/windows/api_types_spec.rb
- spec/unit/util_spec.rb
The ENV class in Ruby is known to corrupt environment variables on Windows which contain UTF8 characters in their names and values.
This PR adds an operating system safe way of accessing environment variables as part of the Puppet::Util module, modifies the places in Puppet where it could potentially corrupt environment variables and adds tests to guard against the behaviour in the future.
Supercedes #4727 - sending through as a PR for final Travis / AppVeyor validation
NOTE: we should remove the mocking for tar_spec.rb in a future commit / PR.
> (PUP-5768) Fix problematic usage of ENV for Windows

- spec/lib/puppet_spec/files.rb
- Re-encode string returned by PuppetSpec::Files.tmpfile and
PuppetSpec::Files.tmpdir so that they can be concatenated with other
UTF-8 strings used in tests.
While Ruby internally will always return these strings intially in
the current local codepage on Windows (which may be fixed in later
Ruby versions), this primarily impacts testing scenarios where it is
useful to create temporary files that have UTF-8 names.
> (maint) Return PuppetSpec::File paths as UTF-8

- lib/puppet/functions.rb
- lib/puppet/pops/loader/ruby_function_instantiator.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions4_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
This PR modifies the `TypeParser` slightly so that it accepts either a loader or a scope as the optional second parameter when parsing. It also ensures that a loader is available to the type parser used when
evaluating 4x function dispatch declarations.
> (PUP-5986) Make loader available to type parser in 4.x function dispatch

- lib/puppet/functions.rb
- lib/puppet/parser/e4_parser_adapter.rb
- lib/puppet/pops/parser/evaluating_parser.rb
- spec/unit/functions4_spec.rb
This PR adds a new feature that makes it possible to define local type aliases in a 4.x Ruby function. These type aliases are only available inside the function.
Aliases are defined inside a block given to `local_types` by calling `type` with a puppet source string on the form `AliasT = T`.
```
Puppet::Functions.create_function(:example) do
local_types do
type 'MyType = Array[Integer]'
type ...
end
dispatch :example do
param 'MyType', :x
end
end
```
This PR supersedes [PR-4732](/puppetlabs/puppet/pull/4732)
> (PUP-5903) Add local type aliases to 4.x function API

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
Previously, we would inline file metadata for any file in the
per-environment directory, however, puppetserver would only serve file
content for files within the per-environment modules/<module>/files directory.
As a result, we were creating a catalog whose static file content could
not be retrieved in some situations, notably when using a control repo
with a source like:
puppet:///modules/profile/puppetmaster/update-classes.sh
which uses a custom modulepath in environment.conf to serve the
file from:
site/profile/files/puppetmaster/update-classes.sh
Note the module 'name' in this case is 'profile'.
This commit ensure we only inline file metadata when using the 'modules'
mount and the resolved path is in a per-environment directory with a
relative path of the form: <base>/<module>/files/
> (PUP-6024) Restrict sources of inlined file metadata

- lib/puppet/network/http/api/master/v3/environment.rb
- lib/puppet/parser/environment_compiler.rb
- spec/unit/appmgmt_spec.rb
- spec/unit/network/http/api/master/v3/environment_spec.rb
This follows the model of agent catalog compilation, passing code_id
from the HTTP request to the environment compiler, which adds it to the
catalog. We then read code_id from the environment catalog and include
it in our response.
This allows environment catalogs and agent catalogs to be correlated
with one another and against a specific version of code.
> (PUP-5099) Add code_id to environment catalog from request

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
If the puppet master's host and port are specified in the `source`
parameter, then we were not preserving the host and port when inlining
content_uri in the file metadata. As a result, the agent would either
use a host:port returned from DNS SRV records (if enabled) or the
Puppet[:server] and Puppet[:masterport] settings, which could be
different from what the manifest originally specified.
The code tried to do this, but `CGI.escape` should only be used on query
parameters, not the entire URI. And we were missing a test to verify the
behavior.
Also modifies another call site to use URI.parse(uri) instead of
URI(uri). The former should be called when parsing a String. The latter
should be called when you have either a String or a URI.
> (PUP-6031) Preserve source host and port during inlining

- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/type/file/source.rb
- spec/unit/indirector/catalog/compiler_spec.rb
Previously, if a source parameter had a trailing slash(es), we would
inline the metadata with the trailing slash. However, the agent always
strips trailing slashes from its sources, and it was not able to lookup
the inlined recursive metadata from the catalog.
This commit normalizes the source parameter when inlining file metadata,
so that `catalog.recursive_metadata[title][source]` works as expected.
Strangely, puppet strips trailing slashes for all file resources, not
just directories, so we apply the same logic when inlining
non-recursive metadata too.
> (PUP-6033) Normalize source parameter when inlining metadata

- lib/puppet/file_serving/metadata.rb
- spec/unit/file_serving/metadata_spec.rb
The content_uri metadata is composed from the source scheme, host, and
port, and the path of the file on disk, relative to the per-environment
directory. Since the path can contain characters that must be
percent-encoded, e.g. 'foo%bar', we need to escape the path prior to
trying to parse the URI.
> (PUP-6036) Escape path when validating content_uri

- lib/puppet/functions/lookup.rb
Before this, the lookup function had complicated string interpolations
that defined the parameter types.
This changes that to use function local type aliases with descriptive
names.
> (PUP-6029) Refactor lookup function to use type aliases

- lib/puppet/defaults.rb
- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- spec/integration/parser/compiler_spec.rb
Before this, only relationships formed with the relationship
operations <- -> <~ and ~> were validated. This validation checkes that
the referenced resource exists in the catalog and reports this.
The identical relationship formed via use of the meta parameters after,
require, subscribe, and notify were not validated. This led to that
errors in catalogs were not caught until the catalog was applied on the
agent.
This commit makes use of the recently added catalog validators and adds
validation of all relationships.
When making this change the existing code in the relationship validator
needed refactoring. It was then detected that it used an array.find and
a predicate lambda to see if a variable was one out of 3 possible
symbols. That was measured to be 6x slower that the fastest (hash …
> (PUP-5855) Add strict error/warning for missing references to resource

- lib/puppet/application/lookup.rb
This fixes the documentation and handling of knock out prefix and unpack
arrays options
> (PUP-6050) Improve puppet lookup cli

- lib/puppet/type/file.rb
Previously, the description of the `links` parameter in the file type
included misleading references to a nonexistent `ignore` value. This
commit removes those references.
> (PUP-5967) Remove reference to nonexistent links value in file type

- lib/puppet/application/inspect.rb
- spec/unit/application/inspect_spec.rb
Fix `puppet inspect` so it looks in the correct location for the cached
catalog.
> (PUP-5233) Restore `puppet inspect`

- acceptance/setup/common/pre-suite/100_SetParser.rb
Merge pull request #187 from jpartlow/issue/3.8.x/pe-13723-ensure-a-single-main-section-in-puppet-conf
(PE-13723) Ensure single main section in puppet.conf
> (PUP-5737) Backport test fix from a pe-puppet fork

- spec/integration/data_binding_spec.rb
This removes testing that the "puppet_backend" for hiera (in the
puppet code base) can be loaded if configured. The result is that it
tries to load a file that was deleted over a year ago.
The reason why this problem occurs now, is because of order dependencies
among the tests. When order depending tests were fixed the now removed
test became order dependent. When it works it got an already configured
hiera, and the test assumed everything worked, since the only thing the
test did was no ensure it was possible to load a configuration
containing "puppet_backend".
When the puppet_backend freak was removed, this test became void, but
because of ordering issues it has not been seen until now.
This commit removes the broken test and the helper setup method
that configured the "puppet_backend".
> (maint) Remove ancient broken test involving code removed > 1 year ago

- api/schemas/catalog.json
Previously, version was specified to be an integer. However, version is often
overridden by using a custom config_version script, which will return a
string. This commit updates the schema to include string for the
version type.
> (maint) Update catalog format api document for version

- lib/puppet/resource/catalog.rb
- lib/puppet/transaction.rb
- spec/unit/resource/catalog_spec.rb
These commits were part of a different PR that became obsolete once we changed how file metadata was generated. Submitting these separately as I think they're still relevant. Supercedes https://github.com/puppetlabs/puppet/pull/4698
> (maint) static catalogs cleanup

- acceptance/tests/language/class_inheritance.rb
This change adds a test to ensure we are inheriting classes properly and
from the correct namespace. We've regressed a couple times here.
no need to merge this just yet. Wait until acceptance is unfrozen after upcoming release(s)
[skip ci]
> (PUP-5877) acceptance: puppet class inheritance

- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
Before this commit, the hash computation of deeply nested structures
of objects could result in a hash value so large that it exceeded
what fits into a 64-bit integer. This lead to problems with JRuby
since it will error out if such objects are added to an array that
is then later asked to produce a hash. The error is:
```
RangeError: bignum too big to convert into `long'
```
This commit ensures that no such numbers are produced by replacing all
multiplications and additions in the #hash methods with logic that
either does an XOR of the values or, when several values are involved,
puts them into an array that is then asked to produce the hash.
> (PUP-6070) Ensure that hash numbers don't exceed 64-bit limit

- lib/puppet/data_providers/hiera_interpolate.rb
- spec/unit/data_providers/hiera_interpolation_spec.rb
This commit adds the ability to put quotes around keys. A key can be
quoted with either single or double quotes. A quoted key will be used
verbatim instead of splitting it on dots. In other words, quoting a key
will not use dots to navigate into hashes and arrays. Instead it will
match a dotted key at top level.
Interpolation expressions that use interpolation methods must have the
key quoted twice to get the effect. The reason for this is that the
argument to an interpolation method already had to be quoted. In order
to not introduce incompatibilities, a quoted key in this context must
therefore be quoted twice. Example:
```
---
a.quoted.key: 'Value for a quoted key'
ref.to.key: 'Put the value here: %{lookup("''a.quoted.key''")}'
```
> (PUP-5990) Add ability to use quoted keys

- lib/puppet/provider/package/pip3.rb
- spec/unit/provider/package/pip3_spec.rb
- spec/unit/provider/package/pip_spec.rb
Features are not inherited from the parent provider. Without this the
Pip3 provider is pretty limited. Specify features provided by Pip as
also provided by Pip3. Also add spec tests for Pip and Pip3 verifying
their features.
> (PUP-6067) Add features to Pip3 provider

- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/loaders/static_loader_spec.rb
Before this commit, the logic for registering known resource types in
the static loader was `TypedName`instances with capitalized names. This
resulted in that the `TypeParser` could never find these types since it
always passes a downcased name to the loader.
This commit changes the registration to instead use a downcased name
(for the registration, not for the registered resource). It also creates
a no-op '#resolve' method on the `PAnyType` so that type `TypeParser`
doesn't need to check what kind of type it is that the loader returns
before calling that method.
> (PUP-6075) Ensure known resource type registration use downcased names

- lib/puppet/util/monkey_patches.rb
- spec/unit/util/monkey_patches_spec.rb
We re-introduced a monkey patch that had previously come from a
vendored dependency in order to maintain compatibility during the 4.x
series. This adds a warning that the patch is deprecated.
> (PUP-5968) Add deprecation warning for Symbol monkey patch

- lib/puppet/provider/service/launchd.rb
Even though line continuations in text plist files is valid XML, the plist parser in facter 2.x can't handle it. In this case, rescue `NoMethodError' and let `plutil -convert xml1' normalize it.
> (PUP-6073) Handle launchd plists with line continuations

- lib/puppet/pops/types/type_mismatch_describer.rb
Struct member names were printed without quotes which made the error
message from the type mismatch describer harder to read. This commit
adds the quotes.
> (PUP-6053) Ensure that struct member names are quoted in mismatch output

- lib/puppet/data_providers/hiera_interpolate.rb
- spec/unit/data_providers/hiera_interpolation_spec.rb
Before this commit, a subkey of a dotted key could be matched by a
string that contained a matching text. Hiera would require that the
value responded to :[] and that it was not an Array (arrays should use
numeric index). A string fulfills that requirement.
This commit adds the constraint that the value cannot be a String when
subjected to a lookup.
> (PUP-6085) Prevent that subkeys can do lookups in string values

- acceptance/config/git/options.rb
Hiera stable is being shipped with puppet-agent. For puppet 3.x we
should be testing agsint the version of hiera we still ship as
standalone pacakges
> (maint) Pin Hiera to 1.3.4 in git tests

- lib/puppet/reference/providers.rb
The comment at the start of lib/puppet/reference/providers.rb was added in https://github.com/puppetlabs/puppet/commit/7835d2927ef360216612f1a782e88a6606a79d6b in 2007.
As we no longer use trac, this commit removes that comment.
> (maint) Remove comment referencing trac

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/types_spec.rb
Before this commit a type alias could reference itself or another alias
that referenced back to itself (chain could be of arbitrary length).
There was also a problem with endless recursion when a scalar type was
matched by a self referencing type alias such as:
```
type One = Variant[One,String]
'foo' =~ One
```
This commit fixes both problems. A chain of type aliases that does not
involve any other type than other aliases or variants thereof is now
detected and considered an error. A recursion guard was also added to
prevent the endless recursion case.
> (PUP-6108) Detect empty types and prevent endless recursion

- lib/puppet/functions/assert_type.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/assert_type_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
This PR fixes a couple of minor bugs and changes the behavior of the `assert_type` function so that it uses `TypeCalculator#infer_set` instead of `TypeCalculator#infer` when reporting mismatches.
> (PUP-6110) Make `assert_type` function use `#infer_set` when reporting type mismatches

- lib/puppet/util/monkey_patches.rb
- spec/unit/util/monkey_patches_spec.rb
We monkey patch OpenSSL::X509::Store#set_default_paths to load our own
additional certs. Sometimes one or more of our certs are already loaded,
however. Previously the code would try to load the cert and in doing so
raise, catch, and warn on the cert already being loaded. Under certain
conditions this superflous warning could print very verbosely, obscuring
the useful output.
This commit quiesces the warn, replacing it with a Puppet#debug. Such a
message at the warn level is not useful to the user and can cause
unnecessary concern or frustration regarding the product.
> (PUP-5588) Prevent redundant cert loading

- lib/puppet/functions.rb
- lib/puppet/functions/new.rb
- lib/puppet/loaders.rb
- lib/puppet/pops.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/loader/predefined_loader.rb
- lib/puppet/pops/types/string_converter.rb
- lib/puppet/pops/types/type_conversion_error.rb
- lib/puppet/pops/types/types.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/functions/new_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/pops/types/types_spec.rb
This adds the function 'new' which operates on a type. The same function can be called by directly calling a type e.g. `T()`.
Each type implements a `new_function` method that returns the 4.x function that acts as the initializer/instantiator function.
This is done to later enable obtaining its Puppet Signature and to allow that each type can specify a specific set of parameters.
The conversion to String is by far the most comprehensive, and it is implemented by delegating to a StringConverter utility - which is largely
modeled on Ruby's Kernel.format method, but catering to many specializations only available in the Puppet Language.
Simple conversions/instantiations are supposed to be simple. More comprehensive conversions should be seen as an interface to puppet's core to be used as
the …
> (PUP-5965) Add 'new' call and function

- lib/puppet/application/lookup.rb
- lib/puppet/functions/lookup.rb
- lib/puppet/parser/functions/lookup.rb
- lib/puppet/pops/merge_strategy.rb
- spec/unit/application/lookup_spec.rb
The unpack-arrays option is not of any value and is now removed.
> (PUP-6074) Remove 'unpack-arrays' options from lookup function and CLI

- lib/puppet/pops/loader/base_loader.rb
- lib/puppet/pops/loader/runtime3_type_loader.rb
- spec/fixtures/unit/pops/loaders/loaders/dependent_modules_with_metadata/modules/usee/lib/puppet/type/usee_type.rb
- spec/fixtures/unit/pops/loaders/loaders/dependent_modules_with_metadata/modules/user/manifests/init.pp
This commit fixes a regression introduced in PUP-6028 where a Resource
Not Found error is triggered on ruby Puppet::Type declarations that
resides in a module.
> (PUP-6121) Fix auto-loading of ruby types

- lib/puppet/pops/types/recursion_guard.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/types_spec.rb
An alias for a variant where one of the variants was the alias itself would always yield true when asked if an object was an instance of the alias. This PR fixes that.
The PR also ensures that variants like that gets normalized so the first problem may actually never occur. I decided to keep the fix anyway. It's semantically correct and may cover some future corner case.
> (PUP-6117) Fix bug with type alias and recursive variant

- lib/puppet/ssl/oids.rb
Refactor the load_custom_oid_file method by breaking out the
file parsing into a separate method, parse_custom_oid_file.
This is necessary so this logic can be shared by Puppet Server.
> (MAINT) Refactor load_custom_oid_file

- benchmarks/missing_type_caching/benchmarker.rb
- benchmarks/missing_type_caching/description
- benchmarks/missing_type_caching/module/testmodule.pp.erb
- benchmarks/missing_type_caching/puppet.conf.erb
- benchmarks/missing_type_caching/site.pp.erb
- lib/puppet/defaults.rb
- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/metatype/manager.rb
- lib/puppet/reference/providers.rb
- lib/puppet/util/feature.rb
- spec/unit/util/feature_spec.rb
If a Ruby type is not available in the file system, every time it is found by
the parser, the Autoloader will scan all over again the directories in
search_directories for it. This generates tons of stat()s that can be saved.
This patch annotates that a type could not be found so the next time it is
required during the compilation of a catalog, the file system is not hammered
again unnecessarily.
This optimization has given us a ~61% reduction in the number of stats per
compilation, as we make an extensive use of the concat module which only
provides Puppet "defined types".
> (PUP-5482) Flag that a type could not be found

- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/evaluator/runtime3_converter.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/model/model.rb
- lib/puppet/pops/model/model_meta.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/functions4_spec.rb
- spec/unit/parser/functions/shared.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
Before this commit, all qualified references were downcased immediately
in the AST model. Attempts where then made to restore the case when
reporting errors by capitalizing all segments in the name. So names
like `MyGreateResource` became `Mygreatresource`.
This commit changes the QualifiedReference so that it instead stores
the original name and will deliver the downcased name when asked to
do so. The logic is also changed in several places to avoid repeated
downcasing and capitalizing.
> (PUP-6128) Retain case in QualifiedReference

- lib/puppet/util/network_device/cisco/device.rb
- lib/puppet/util/network_device/cisco/interface.rb
- spec/unit/util/network_device/cisco/device_spec.rb
- adds error display for device commands, which used to fail silently
- removes duplicate command input from the error output
This also removes some tests which caused never-achieve-convergence
as it was dropping device properties that could be supplied as input
> (PUP-5616) fixes to improve error display

- lib/puppet/pops/loaders.rb
This commit changes the warning for missing module dependencies
to be less verbose.  It also adds support for the `:strict`
setting.  If `:strict` is set to `:warning`, then we only log
the missing module dependency once (per ruby instance).  If `:strict`
is set to `:error`, then we raise a LoaderError.  If `:strict`
is set to `:off`, then we don't log anything.
> (PUP-6142) Only warn once for missing module dependencies

- lib/puppet/provider/service/init.rb
This commit ensures that for init-based services on RedHat
platforms, the RedHat service provider is used to properly
handle them rather than its more general parent the init provider.
> (PUP-2744) Always use RedHat service provider instead of init

- lib/puppet/pops/types/types.rb
- spec/unit/functions/new_spec.rb
Before this, and attempt to create a new `NotUndef` resulted in
an error unless its type was narrowed.
NotUndef[Integer](42) worked but not
NotUndef(42)
This commit adds a new function to the Unit type. This is used by
NotUndef if it does not have a narrowed type.
> (PUP-6131) Make NotUndef.new be transparent

- lib/puppet/indirector/terminus.rb
Before this, there was an attempt to create a symbol from an empty
string (or worse case from nil). With the removal of monkey patching
symbol to compare equal to string and introducing warnings, it is
important to clean up odd usage of string symbol comparisons.
This is now changed to deal with the error condition of nil/empty string
before converting to symbol and using the value.
This also makes a small refactoring to the variable name as the
implementation in general uses a very confusing style where some
attributes have readers but no writers this resulting in confusion over
if the use of the attribute is a local variable or a function call to
the attribute reader.
> (PUP-6105) Avoid comparing symbol to string in terminus

- acceptance/lib/puppet/acceptance/service_utils.rb
- acceptance/tests/resource/service/AIX_service_provider.rb
- acceptance/tests/resource/service/launchd_provider.rb
- acceptance/tests/resource/service/puppet_mcollective_service_management.rb
This commit updates the service_utils helper to more robustly
test services being started, stopped, enabled and disabled. In
addition, the launchd and AIX service tests have been updated
to use the helper rather than reimplement its methods.
[skip-ci]
> (maint) Use service helper for launchd and AIX tests

- lib/puppet/pops/types/types.rb
- spec/unit/functions/new_spec.rb
Before this, it was not possible to create a new instance when using a
type alias. Now, calls to new delegate to the aliased type.
> (PUP-6129) Add new function support to type alias

- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
This modifies string representation of empty Array and Hash to `Array[0, 0]´ and `Hash[0, 0]´ respectively.
This also makes it illegal to attempt to type an empty collection  - these are now illegal:
* `Array[Integer, 0, 0]`
* `Hash[Integer, Integer, 0, 0]`
Internally it is still allowed to create such types if the key/value types are `Unit` (since that is how the empty states are encoded).
> (PUP-6089) Do not show unit type for empty collections, and make creation of empty Array/Hash illegal

- lib/puppet/provider/user/user_role_add.rb
This check was lost in a refactor back in 2014. Both the `password` and `password_max_age` getters retained their checks for absence.
> (PUP-6113) Don't fetch password_min_age on Solaris if it doen't exist

- acceptance/lib/puppet/acceptance/service_utils.rb
- acceptance/tests/resource/service/init_on_systemd.rb
An acceptance test for managing init.d services on systems where the
systemd provider is the default. This doesn't work without PUP-2744,
which ensures the fallback on RedHat systems is the RedHat provider
- which works - instead of the init provider - which doesn't on RedHat.
It also helps verify that managing SysV init scripts continues to work
after a fix for PUP-5296/PUP-5825, where enabled status was reported
incorrectly.
[skip ci]
> (PUP-6140) Acceptance test for init.d services when systemd is default

- lib/puppet/functions.rb
- lib/puppet/parser/ast/pops_bridge.rb
- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/integration/parser/compiler_spec.rb
- spec/unit/functions/assert_type_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
This PR adds one commit to change the Object type from being anonymous to being named, and one commit that leverages this to make feature related errors more descriptive.
> (PUP-6137) Change Object Type from anonymous to named

- lib/puppet/pops/loader/base_loader.rb
- lib/puppet/pops/loader/dependency_loader.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/loader/predefined_loader.rb
- lib/puppet/pops/loader/runtime3_type_loader.rb
- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
- spec/unit/pops/types/types_spec.rb
This makes it illegal to redefine an already defined (loaded) type. The main use case for adding this is to prevent redefinition/change of built in types like Integer or String - imagine the hilarity of doing `type Integer = String`.
This is now done by adding all types defined by the type system to the static loader (hence they are always loaded). Then, when defining a new type (data type or resource type), a check is made if this type is already loaded - and if so, an error is raised. Unfortunately it would not be backwards compatible to make it illegal to shadow what would potentially be loaded as that is legal in current puppet.
Two exceptions are made to the general rule. 4.x function (in Ruby) are allowed to shadow types - the rationale is that they may otherwise break if users add …
> (PUP-6102) Make it illegal to redefine any visible type

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/types_spec.rb
A `PTypeAliasType` with a resolved type that is a `PVariantType` where
one of the variants points directly the alias, would cause an endless
recursion since the recursion check resided in the `#_assignable?`
method. That method was never called due to special handling of type
alias and assignable in `PAnyType`. This commit fixes this by letting
the `PTypeAliasType` override the `#assignable?` method.
The commit also deals with a problem that occurred when calculating
whether or not a type was self recursive. If the computation involved
yet another alias that was not yet resolved, then it would yield a false
negative. Only the other type would be considered recursive (first type
was resolved when it resolves). This commit ensures that contained
aliases recompute their self-recursive state …
> (PUP-6145) Prevent self recursion in TypeAlias assignable? method

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/types_spec.rb
It's currently not possible to use a Struct type as a Hash key. This
is because the `PStructType#eql?` method is using array == which in
turn relies on the `#==` method of its elements. The `PStructElement`
class implements `#eql?` but not `#==`. This commit changes this so
that both methods can be used.
> (PUP-6133) Make struct functional as hash key

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
The `PStructType#assignable?` method would return `nil` instead of
`false` when compared to a PHashType. This commit fixes that.
> (PUP-6146) Fix bug causing Struct assignable? to return nil

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this PR, the method `PStructType#assignable?` would ignore
the key type for a `PHashType` and hence, give false positives for
cases when the struct contained keys that were incompatible with the
key of the hash. This commit fixes that problem.
NOTE! This PR relies on https://github.com/puppetlabs/puppet/pull/4865 which has not yet been merged.
> (PUP-6147) Make PStructType#assignable? consider PHashType key type

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
The `Callable#assignable?` would raise an undefined method when passed
a callable that didn't have any parameter definition. This commit fixes
that problem.
> (PUP-6148) Fix problem with Callable#assignable? and undefined method

- lib/puppet/pops/evaluator/access_operator.rb
- spec/unit/pops/types/types_spec.rb
The AccessOperator implementation for the Iterable type was missing.
This commit adds that and a test to verify that it works.
> (PUP-6155) Implement access operator for Iterable type

- lib/puppet/pops/evaluator/access_operator.rb
- spec/unit/pops/types/types_spec.rb
The AccessOperator implementation for the Collection type was flawed.
This commit fixes that and adds a test to verify that it works.
> (PUP-6149) Fix problem in access operator for Collection type

- lib/puppet/pops/types/p_runtime_type.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/types_spec.rb
This commit extends the Runtime type so that it can describe a pattern
match between a Puppet type name and a Runtime type name.
> (PUP-5928) Add pattern matching to Runtime type

- lib/puppet/pops/evaluator/access_operator.rb
- spec/unit/pops/types/types_spec.rb
The AccessOperator implementation for the Iterator type was missing.
This commit adds that and a test to verify that it works.
> (PUP-6156) Implement access operator for Iterator type

- lib/puppet/file_system/uniquefile.rb
- spec/unit/file_system/uniquefile_spec.rb
- Previously, if code in Puppet::FileSystem::UniqueFile.locking
errored, an ensure block was entered to cleanup any temporary
.lock directories that may have been created.  This code path is
used any time Puppet::FileSystem::UniqueFile.open_tmp is called.
Unfortunately, if the call to mkdir(lock) failed, there would be
no .lock directory to cleanup, and the actual error raised here
is a red herring, generated by the failed cleanup attempt.
On Windows, this can frequently lead to errors like
Errno::ENOENT: No such file or directory @ dir_s_rmdir - ... .lock
which obscure the real underlying issue, which is typically a
permissions problem writing to disk.
The simplest solution is to verify if the file exists prior to
attempting to delete it.
> (maint) Fix UniqueFile error propagation

- acceptance/setup/common/pre-suite/100_SetParser.rb
This reverts commit e623253792810533ba7df72c204b3fcf76851d98.
Note that the backported test fix actually breaks puppet testing because of
PUP-4755. The only impetus to backport was to minimize branch drift, but that
is unlikely to happen given that there is no active develoment on 3.x.
[skip ci]
> Revert "(PUP-5737) Backport test fix from a pe-puppet fork"

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
A default tuple has no size, but when compared it creates a range based
on the size of it's contained types. The default tuple has an empty list
of types which resulted in the range 0,0.
This commit changes this so that the computed range is 0 - infinity when
there are no types.
> (PUP-6167) Fix problem default Tuple having max size of zero

- lib/puppet/pops/types/iterable.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
This commit replaces direct calls to `PVariantType#new` with calls to a
new `PVariantType#maybe_create` method. The new method checks if only
one unique entry exists among the given types. When that's the case,
that entry is returned instead of creating a variant with only one
type.
> (PUP-6151) Create Variants only when there's a need for it

- acceptance/Rakefile
This commit adds a new acceptance rake task, `ci:test:quick`,
which runs a reduced subset of tests. The task is intended to be
run on a per-commit basis rather than the full suite, in order to
reduce time required for the development feedback cycle.
This task is *not* intended to replace puppet-agent's full suite
pipeline, which will still run all tests nightly.
The task includes a small set of tests which are an attempt at a
representative sample of the full suite. In addition, any tests
modified within the last two weeks are automatically added to the
list and run as well.
[skip ci]
> (PUP-5105) Add ci:test:quick for per-commit reduced subset of tests

- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- spec/unit/parser/resource_spec.rb
PUP-6028 fixed a bug in how the resource type and title was extracted
where the case when both where `nil` was undetected. This revealed
another bug in the `RelationshipValidator` where it attempts to create
a resource from a parameter with the value `nil`.
This commit ensures that no attempt is made to create a resource from
`nil` during parameter validation.
> (PUP-6176) Fix error when a resource reference is appointing undef

- lib/puppet/provider/service/systemd.rb
- lib/puppet/type/service.rb
- spec/unit/provider/service/systemd_spec.rb
- spec/unit/type/service_spec.rb
Static systemd services are defined as services that cannot
be enabled or disabled and are usually dependencies or tasks
of other services  Previously, Puppet would erroneously attempt
to disable these services, which is a no-op on the system. Upon
doing so, Puppet was fooled into believing that the service was
being successfully disabled in every run.
This commit updates the systemd provider to not attempt to disable
static services, and log a debugging message when a manifest
attempts to.
In addition, a new 'cached_enabled?' method is added which prevents
the provider from unnecessarily shelling out to systemctl multiple
times.
Thanks to Michael Smith for the research and part of the implementation
for this fix!
> (PUP-5353) Don't try to disable static systemd services

- lib/puppet/type.rb
- lib/puppet/type/service.rb
- spec/unit/type_spec.rb
Before this, service type will always retrieve the ensure status even if no
ensure parameters is given.
But, because no Service Type parameter is dependant on whether the service
is running or not, we can just skip the ensure status retrieval.
Now, a service type will only retrieve the ensure status when a ensure
parameter is given.
> (PUP-4760) Service type should not retrieve ensure status when unneeded

- lib/puppet/application/ca.rb
Calling setup on a face is required to initialize command-line
arguments. Without this the face silently fails to execute. Fix so when
we override setup in the CA face, we still call out to `super`.
> (PUP-6179) Fix the `puppet ca` face

- acceptance/tests/direct_puppet/supports_utf8.rb
This change adds a test containing a catalog (site.pp) with a file
resource whose contents has several utf8
chars of various categories.  It runs the agent twice, once with
--use_cached_catalog, and ensures its proper operation.
[skip ci]
> (PUP-5727) acceptance: cached catalog should allow encodings from utf8

- lib/puppet/file_system/windows.rb
- lib/puppet/util/windows.rb
- lib/puppet/util/windows/file.rb
- spec/unit/file_system_spec.rb
- spec/unit/util/windows/file_spec.rb
In c64fa0749f673cc75c09b986f3e50a80c7237314 code was introduced to add
symlink support on Windows. The GetFileAttributes API is used to detect
if a given file is a Windows reparse point, which means for Puppets
purpose that the path is a symlink.  However, due to the FFI
implementation of GetFileAttributes, exceptions are thrown under fairly
typical circumstances, when checking for file existence. Puppet performs
a fair amount of Disk IO as it loads (partially exploring module
directories for source to load) -- and this can generate many thrown /
silently eaten exceptions. In a basic Puppet run on Windows, nearly 1000
exceptions are thrown, creating a performance impact. It's uncertain how
much this might affect typical user code, but it's not negligible.
This commit updates the …
> (PUP-6025) Fix Windows FileSystem exist? symlink?

- lib/puppet/property.rb
knowing which provider was selected can be helpful in figuring out
why you're getting the 'Provider must have features...' message.
> (maint) add provider name to 'provider must have feature' error message

- lib/puppet/settings.rb
This should avoid slowing down if we initialize settings multiple times, what, for example, `foreman-proxy` does.
> (PUP-6000) Add only unique hooks during initialization

- lib/puppet/provider/service/smf.rb
- spec/fixtures/unit/provider/service/smf/svcs.out
- spec/unit/provider/service/smf_spec.rb
(PUP-6095) Service provider shouldn't die if an smf service is in state "degraded"
Without this patch attempts to view or manage smf services fail when any service
is in a degraded state. After patching, services in a degraded state are treated in an
identical manner to those in a maintenance state.
> (PUP-6095) Service provider shouldn't die if an smf service is in state "degraded"

- lib/puppet/util/plist.rb
Puppet::Util::Plist's dump_plist and write_plist_file methods both emit poorly-formatted XML plists by default. Thankfully, the cfpropertylist module this depends on has a :formatted option for both .to_str and .save. Setting this to true results in properly-formatted XML.
Also fix a call of Puppet.error to Puppet.err
> (PUP-6132) Emit formatted XML when using Puppet::Util::Plist

- acceptance/tests/direct_puppet/supports_utf8.rb
This change fixes the previous version of this test for windows10 32bit.
Tempfiles go in a different place (as addressed from cygwin) in 32bit
windows.
[skip ci]
> (PUP-5727) acceptance: fix utf8 cached_catalog test for windows10 32bit

- lib/puppet/data_providers/json_data_provider_factory.rb
- lib/puppet/indirector/msgpack.rb
- lib/puppet/module.rb
- lib/puppet/module_tool/applications/builder.rb
- lib/puppet/network/auth_config_parser.rb
- lib/puppet/settings.rb
- spec/fixtures/unit/data_providers/environments/hiera_env_config/data1/third_utf8.json
- spec/fixtures/unit/data_providers/environments/hiera_env_config/data1/utf8.yaml
- spec/fixtures/unit/data_providers/environments/hiera_env_config/hiera.yaml
- spec/fixtures/unit/data_providers/environments/hiera_env_config/manifests/site.pp
- spec/integration/util/settings_spec.rb
- spec/unit/data_providers/hiera_data_provider_spec.rb
- spec/unit/indirector/msgpack_spec.rb
- spec/unit/module_spec.rb
- spec/unit/module_tool/applications/builder_spec.rb
- spec/unit/network/auth_config_parser_spec.rb
- spec/unit/pops/loaders/loaders_spec.rb
- spec/unit/settings_spec.rb
Adds additional UTF-8 support to Puppet when reading files from disk, including:
* Settings like `puppet.conf`
* PMT ignore files - `.gitignore` and `.pmtignore`
* Hiera YAML and JSON files
* Modules `metadata.json`
* Route auth files
* MsgPack
> (PUP-5879) Use FileSystem.read where applicable to read JSON, settings and other files as UTF-8

- acceptance/tests/direct_puppet/supports_utf8.rb
skip due to PUP-6217. revert this change or remove skip_tests for fixed
platforms when 6217 resolves.
[skip ci]
> (PUP-5727) acceptance: skip supports_utf8 test on some agents

- lib/puppet/pops/loaders.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/puppet_object.rb
- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/ruby_generator_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
This PR adds a Ruby generator capable of generating a default implementation of an `Object` type. Instances of the object can be created either from a hash (validated by the `#i12n_type` of the `Object`) or by a constructor using anonymous parameters.
The generator is capable of generating both anonymous ruby classes and a static implementation intended to be written to files and then included in a code base.
> (PUP-6224) Add a Ruby generator that emits code based on Object types

- lib/puppet/module_tool/skeleton/templates/generator/Gemfile
Rake 11 dropped support for ruby 1.8.7, so if we are using that, we need
to pin rake to v10.
> (PUP-6232) Allow module_tool to keep supporting ruby 1.8.7

- CONTRIBUTING.md
- LICENSE
- docs/quickstart.md
This commit updates the CONTRIBUTING, LICENSE and quickstart markdown files
with the new branding name of Puppet and license dates
Note - There are many other instances of Puppet Labs in the codebase.  These will be addressed in later pull requests.
> (maint) Update docs and license with new branding

- acceptance/tests/modules/build/build_should_not_allow_symlinks.rb
The PMT skeleton has been changed to name the 'tests' directory
to 'examples' in commit 420cb9f6bb. This caused the
'build_should_not_allow_symlinks' test to fail because the test
was using the 'tests' directory.
This commit renames the 'tests' directory to 'examples' in the
'build_should_not_allow_symlinks' test.
[skip-ci]
> (PUP-6235) Change PMT tests to examples in build test

- .travis.yml
Ruby 2.3.1 has been released, which includes the fix for
https://bugs.ruby-lang.org/issues/11928, so bump travis to
use the released version of 2.3.
> (maint) Bump to ruby 2.3.1 in travis ci

- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/ruby_generator.rb
- spec/unit/pops/types/p_object_type_spec.rb
This PR adds the ability to create new instances of an Object type from the Puppet Language. It also adds the ability to call members (attributes and functions) on the object since it's difficult to test instantiations of an object if it is possible to examine the result.
> (PUP-6225) Add new function to object type

- lib/puppet/indirector/rest.rb
- spec/unit/indirector/rest_spec.rb
When making REST requests, the agent would include `yaml` in the HTTP Accept
header. However we removed network support for yaml in PUP-3272. In
particular, the Puppet::Network::HTTP::Request#assert_supported_format
method (on the server) will fail the request if it ever tries to return
yaml. Since the server should never return it (since 4.0) and 4.0 agents
can't communicate with 3.x masters (due to URL prefix changes), there's no
point in asking for it.
This commit strips `yaml` and `b64_zlib_yaml` from the HTTP Accept header
when making REST requests. It doesn't affect callers making direct
Puppet::Network::HTTP requests, e.g. providers, report processors.
> (PUP-3941) Exclude yaml from the Accept header

- lib/puppet/defaults.rb
- lib/puppet/test/test_helper.rb
The req_bits setting was added in bb4b5a54, but has only been used in
the test_helper.rb invoked by spec_helper.rb.
This commit deprecates the setting completely and removes it from the
test_helper.rb.
> (PUP-2419) Deprecate never used req_bits setting

- acceptance/lib/puppet/acceptance/rpm_util.rb
- acceptance/tests/resource/package/yum.rb
- lib/puppet/provider/package/rpm.rb
- lib/puppet/provider/package/yum.rb
- spec/unit/provider/package/rpm_spec.rb
- spec/unit/provider/package/yum_spec.rb
This commit updates logic in the RPM and Yum providers to
better handle the presence or absence of user specified epochs
and architecture fields. We now assert that absent epoch and
architecture values from the user are always insync with those
values as found by querying the system. This allows Puppet to
make the assumption that an unprovided epoch value can match
anything available on the system, not just the former default
of '0'.
In addition, this change also enables the detection of an
architecture in the title of a package and moves it to the
end of the version string for installation. Thanks to
Peter Souter (petems) for the work on this!
Note that there are still limitations based on the underlying
package manager when installing packages. DNF (a child of the
yum provider), for …
> (PUP-5025) Fix epoch and architecture handling for RPM systems

- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/evaluator/access_ops_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
This commit ensures that the following:
1. An Array type can be created with two integer arguments
2. A Hash type can be created with two integer arguments
3. An empty Array type can be created with an element type
4. An empty Hash type can be created with key and value types
5. All types of empty collection types are erased
8. A request for a type from an empty collection type returns Unit
> (PUP-6251) Ensure that both Array[0,0] and Hash[0,0] works.

- lib/hiera_puppet.rb
- lib/puppet/defaults.rb
- lib/puppet/settings/base_setting.rb
- spec/unit/hiera_puppet_spec.rb
This commit ensures that when Puppet is initialized, it will first check
if a Hiera config file is specified using the `hiera_config` setting. If
it is, then that setting will be used (and an warning is issued if it
doesn't exist). When`hiera_config` is not set, Puppet will first look
`hiera.yaml` in the codedir and if no such file exists, it will default
to `hiera.yaml` in confdir.
> (PUP-6178) Look for hiera.yaml in codedir first, then confdir

- lib/puppet/network/http/api/indirected_routes.rb
- spec/integration/network/http/api/indirected_routes_spec.rb
- spec/lib/puppet_spec/network.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
- spec/unit/network/http/api/master/v3_spec.rb
Prior to this the indirected routes would intercept any issues that
arose in processing the request and format them into a plain text
response with the proper error code.
All other routes pass issues up to the generic route handler which will
format them according to a documented schema.
This moves the indirected routes handler from never raising to always
raising on error, similar to other route handlers. This allows the
indirected routes to share the error handling code with other routes
and provides consistently formatted errors throughout the rest api.
Running the acceptance suite locally (via `SHA=$(git rev-parse HEAD) TEST_TARGET=ubuntu1404-64a bundle exec rake ci:test:git` I get:
```
Errored Tests Cases:
Test Case tests/direct_puppet/static_catalog_env_control.rb reported: …
```
> (PUP-3827) Return errors matching schema from indirected routes

- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/issues.rb
- spec/integration/parser/compiler_spec.rb
Before this, when using private implementation classes and wanting to expose many variables in a public facing class, code would consist of long sequences of assigns like:
```
$a = $other::inner::thing::a
$b = $other::inner::thing::b
#... repeat ad nauseum
```
This can now be achieved with a single multi assignment:
```
[$a, $b, ...] = Class['other::inner::thing']
```
The variables must exist (variable or parameter) in the referenced class, but they may be set to `undef`.
> (PUP-6174) Add multi-assign vars from class vars/params

- acceptance/lib/puppet/acceptance/environment_utils.rb
- acceptance/tests/direct_puppet/supports_utf8.rb
- acceptance/tests/language/exported_resources.rb
- acceptance/tests/parser_functions/no_exception_in_reduce_with_bignum.rb
This change adds a test to ensure no further regressions when using
bignums in manifests (see: PUP-6070).
[skip ci]
> (PUP-6189) no exception in reduce() with bignums

- ext/project_data.yaml
Puppet gems do not require at least ruby 1.9.3, even though the code
will not run on earlier versions.
Add the ruby and rubygems versions to project_data.yaml, which will be
copied by the `rake package:gem` task when building the gem.
I copied the values from the .gemspec, which is used when another
project, e.g. module, depends on a source checkout of puppet. The values
in .gemspec and ext/project_data.yaml should be kept insync.
> (PUP-3740) Require at least ruby 1.9.3 for the puppet gem

- acceptance/tests/ensure_puppet-agent_paths.rb
Update the ensure_puppet-agent_paths test to look for hiera.yaml in
confdir.
> (PUP-6178) Updates for hiera pathing

- acceptance/tests/resource/scheduled_task/should_destroy.rb
It is possible that due to contention in a VM that it will take longer than
5 seconds for a scheduled task to appear as deleted.  This commit increases the
timeout to a large value to give the operating system time to delete the task
> (PUP-6261) Increase timeout for scheduled tasks deletion in test

- lib/puppet/network/http/api/indirected_routes.rb
- spec/integration/network/http/api/indirected_routes_spec.rb
- spec/lib/puppet_spec/network.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
- spec/unit/network/http/api/master/v3_spec.rb
Reverts puppetlabs/puppet#4875
Tests failing - PUP-6270
> Revert "(PUP-3827) Return errors matching schema from indirected routes"

- lib/puppet/provider/service/daemontools.rb
- lib/puppet/provider/service/runit.rb
- lib/puppet/type/exec.rb
- lib/puppet/type/file/content.rb
- lib/puppet/type/file/ensure.rb
- lib/puppet/type/file/source.rb
- lib/puppet/type/file/target.rb
- lib/puppet/type/package.rb
- lib/puppet/type/schedule.rb
- lib/puppet/type/tidy.rb
- lib/puppet/type/zone.rb
Currently the code examples at: 
https://docs.puppet.com/puppet/latest/reference/type.html
are not all passing a puppet-lint run.
This PR fixes that.
> (doc) (DOCUMENT-541) Make resource type examples pass puppet-lint checks

- lib/puppet/functions/dig.rb
- lib/puppet/functions/lest.rb
- lib/puppet/functions/then.rb
- lib/puppet/functions/with.rb
- spec/unit/functions/dig_spec.rb
- spec/unit/functions/lest_spec.rb
- spec/unit/functions/then_spec.rb
This adds three functions 'dig', 'then', and 'lest', which together with the existing `assert_type` function makes complex data access easier to perform without complex conditional logic and temporary variables.
The *dig* function performs a sequence of access operations on a complex collection similar to the 'dot-notation' used in hiera and facter.
For example:
```
$some_data.dig(somekey, 1, otherkey)
```
If, at any point, the intermediate result is `undef` the operation stops and returns `undef`. It is an error to attempt to access something in a value that is neither Array nor Hash.
The *then* function, accepts a single argument, and if it is not `undef` if calls a given block with the value. If given `undef` the block is not called and `undef` is returned.
The *lest* function is the …
> (PUP-6046) Add functions 'dig', 'then', and 'lest'

- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/types/types_spec.rb
A Puppet Type Alias expression may not contain dynamic expressions. The
error issued when it did was not very informative since the actual
source of the dynamic expression was left out. This commit ensures that
it is included in the error message.
> (PUP-6229) Fix unclear error when dynamic expressions used in aliases

- lib/puppet/pops/types/iterable.rb
- spec/unit/pops/types/iterable_spec.rb
Use dash between the type and the text 'value' and capitalize
'value' to make the output of an iterator type more readable.
> (PUP-6151) Output Iterator value as Iterator-Value

- lib/puppet/pops/types/type_calculator.rb
- spec/unit/pops/types/type_calculator_spec.rb
The TypeCalculator::infer_set does not use the normal dynamic dispatch
algorithm. Instead, to speed things up, it uses a case/when. When adding
the SemVer type, an infer_set_Version method was added, but it was never
called because it was not added to that case/when. This commit fixes
this oversight and adds the tests needed to verify that infer_set works
for Semantic::Version.
> (maint) Fix bug for Semantic::Version in TypeCalculator::infer_set

- lib/puppet/application/cert.rb
Previously, `puppet cert print` would always show the OID for
custom X509v3 cert extensions:
X509v3 extensions:
1.3.6.1.4.1.34380.1.2.1.1:
..somedata
With this commit, if a `trusted_oid_mapping_file` is specified mapping
OIDs to their short and long human readable names, then the long name
will be displayed, similarly to what is displayed for puppet OIDs like
"Puppet Node UUID" and other well-known OIDs:
$ puppet cert print <hostname> --trusted_oid_mapping_file oids.yaml
...
X509v3 extensions:
Netscape Comment:
Puppet Ruby/OpenSSL Internal Certificate
X509v3 Subject Key Identifier:
47:BC:D5:14:33:F2:ED:85:B9:52:FD:A2:EA:E4:CC:00:7F:7F:19:7E
Puppet Node UUID:
ED803750-E3C7-44F5-BB08-41A04433FE2E
My Long Name:
..somedata
If the trusted_oid_mapping_file doesn't exist (the default), then …
> (PUP-4617) Display human readable cert extensions

- lib/puppet/provider/service/launchd.rb
- spec/unit/provider/service/launchd_spec.rb
This commit adds an override of the status method to
the launchd service provider to allow service resources
to utilize a custom status command in conjuction with
`hasstatus => false`.
> (PUP-5926) Allow status override in launchd provider

- acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb
- lib/puppet/provider/user/directoryservice.rb
- lib/puppet/util/plist.rb
- spec/unit/provider/user/directoryservice_spec.rb
Previously, Puppet would fail to set passwords in OSX via the
directoryservice provider due to CFPropertyList encoding problems
when converting entropy and salt strings into binary.
This was due to the fact that CFPropertyList was treating these
binary fields as CFStrings, which would then fail to
convert to binary due to invalid UTF-8 byte sequences.
In order to prevent this, the 'salt' and 'entropy' fields must
be converted into CFPropertyList::Blob's, which are interpreted
as CFPropertyList::CFData objects when parsed by CFPropertyList.
This is the correct data type for binary data values. (Thanks to 
@branan  for the help tracking this down!)
In addition, when setting shadow hash data, the binary_plist
string must also be converted into a Blob for the same reasons.
The second commit …
> (PUP-6159) Convert CFPropertyList binary strings to CFPropertyList::Blob's

- acceptance/tests/resource/service/AIX_service_provider.rb
This commit alters the setup step for ensuring that the test service is
stopped. It removes the validation that the service changed state. This allows
the step to pass if the service was already stopped prior to running the
setup step that stops it.
Prior to this commit, if the system did not automatically start the service
upon creation the test would fail during the setup step intended to ensure
that it was stopped.
> (PUP-6301) Make AIX service test setup idempotent

- ext/README.environment
- lib/puppet/defaults.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/settings/config_file.rb
-   Add link markup and update URL in `default.rb` markdown content.
-   Update URL in error messages and other locations.
> (doc) Fix/update links to environments doc.

- lib/puppet/provider/package/portage.rb
- spec/unit/provider/package/portage_spec.rb
Portage allows installing multiple versions of a package using slots.
To support slotted packages, Puppet needs to check only the packages
installed in the specified slot, as well as install using the slot
specifier. Other package managers have the slot as part of the package
name, but portage separates this its package name syntax.
This commit adds support for checking and installing packages with slot
specifiers, allowing one to keep multiple versions of a package
up-to-date.
This was originally PR #2649, but I updated the code, tests, and commit message.
Please read the discussion on that pull request.
> (PUP-2802) Add slot support for portage package provider

- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
Fixes a bug in the TypeMismatchDescriber that caused the type mismatch
reported when passing a zero sized array where a non empty array is
required to report an element type mismatch rather than the size
mismatch.
Also fixes so that array mismatches are reported with correct index
rather than just stating that there's a mismatch between an Array
and a Tuple where some element in the Tuple doesn't match the element
type of the Array.
> (PUP-6320) Fix error when reporting zero sized array mismatch

- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
Fixes a bug in the TypeMismatchDescriber that caused the type mismatch
reported when passing a zero sized hash where a non empty hash is
required to report an element type mismatch rather than the size
mismatch.
> (PUP-6319) Fix error when reporting zero sized hash mismatch

- install.rb
puppet-agent carries the batch files for all executables with the new move to
vanagon for windows projects, we will need an option to omit batch file
creation during installation of puppet so there are not more than one set of
batch files. So this commit adds a --no-batch-files option for cmake that omits
those files.
> (PUP-6318) Add --no-batch-files option to install.rb

- ext/debian/control
Since the vim and emacs extension packages conflicted with puppet <=
current version, if that package was upgraded it would remove puppet and
anything dependant on puppet. This is not correct behavior. Add puppet
>= current version as a dependency of those packages instead.
> (packaging) Bad conflicts for vim and emacs can uninstall puppet

- lib/puppet/pops/types/type_parser.rb
This makes the API for TypeParser.interpret public API (it is used by
Puppet Strings). This change is made to make Puppet aware that the API
cannot be changed without consequences.
It is a documentation change only since the method itself was not
technically Ruby private.
> (PUP-6088) Make TypeParser.interpret public API

- lib/puppet/type.rb
- spec/unit/type_spec.rb
Prior to this commit, an autorequire that produced `undef` values would
produce an error:
```
No title provided and :xxx is not a valid resource reference
```
This commit ensures that `undef` entries provided by an autorequire are
skipped over.
> (PUP-6321) Handle autorequire with undef values

- lib/puppet/pops/evaluator/runtime3_support.rb
- spec/unit/util/monkey_patches_spec.rb
Puppet has a monkey patch for `Symbol#<=>(String)` that enables
comparison. This is deprecated and slated for removal in puppet 5.0.0.
On JRuby, `String#==(other)` is implemented as `other<=>(self) == 0` which
causes the monkey patch in puppet to trigger.
In 1547756ad7caa5cb1f0add8161e51ac07f61bd67 we reversed a test from `x
== :undef` to `:undef == x`. And this caused the problem reported in
PUP-6336 as this logic now (via the MRI incompatible implementation in
JRuby) caused the monkey patch in puppet to kick in.
This commit changes the test `:undef == x` to `:undef.equal?(x)` which
avoids both the JRuby incompatibility, and the problem the change
solved in the first place (ending up in the same insane monkey patch).
> (PUP-6336) Fix problem with diff Jruby/MRI in String#==

- lib/puppet/data_providers.rb
- lib/puppet/data_providers/lookup_adapter.rb
- spec/fixtures/unit/data_providers/environments/hiera_module_config/modules/one/data1/name.yaml
- spec/fixtures/unit/data_providers/environments/hiera_module_config/modules/one/data1/server1.yaml
- spec/fixtures/unit/data_providers/environments/hiera_module_config/modules/one/data1/server2.yaml
- spec/fixtures/unit/data_providers/environments/hiera_module_config/modules/one/hiera.yaml
- spec/unit/data_providers/hiera_data_provider_spec.rb
Before this commit, the LookupAdapter used for providing environment and
module data providers, was attached to the current environment. This
caused all caches to have the same lifecycle as the environment which
is wrong. The caches should not survive between compilations.
This commit changes the LookupAdapter so that it instead attaches itself
to the compiler. This ensures that a new LookupAdapter instance (and
and hence, new caches) are created for each compilation.
> (PUP-6339) Bind lookup adapter to compiler instead of environment

- acceptance/tests/environment/custom_type_provider_from_same_environment.rb
This change adds a test to ensure a custom type and provider both come
from the same/correct environment as the rest of the agent run. We
create two modules with the same type and provider, one in production
and one in another environment. Only the file produced by the
type/provider in the 'other environment' shall be ensured.
[skip ci]
> (PUP-3964) acceptance: ensure provider from same env as custom type

- install.rb
Install.rb was just updated to add an install option to omit batch file
generation during installation. But this change was incomplete. This commit
should suffice to actually omit all batch files during install
> (PUP-6318) Update install.rb to actually honor InstallOptions.batch_files

- acceptance/tests/environment/custom_type_provider_from_same_environment.rb
This test was previously not cleaning out its production site.pp, which
broke subsequent tests.  This test really should be using a temp
environmentpath, to be even safer, but this is a bit slower as it
requires a server restart.  This change also only cleans out the files
on the master, saving a bit of time.
> (PUP-3964) fix previous test commit teardown.

- lib/puppet/type/ssh_authorized_key.rb
Something in the parser was choking on the long lines. Trimming them made it display properly.
> (PUP-4904) correct garbled ssh_authorized_key output

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/types_spec.rb
Before this something like `Enum[a,b,a,b]` would keep all values. Thus, when iterating the values ´a, a, b, b´ would be produced. 
Now the values are made unique.
> (PUP-6354) Make Enum values uniq

- lib/puppet/parser/functions/create_resources.rb
- spec/unit/parser/functions/create_resources_spec.rb
This adds logic that filters out all parameters that are undef from the
instruction built by create_resources.
This is done to prevent validation of relationships to flag
relationships to undef as an error.
This is done for all parameters since an undef parameter means that the
default value should be used. (The language evaluator does the same
thing).
> (PUP-6385) Make create_resources filter out undef relationships

- acceptance/tests/config/puppet_manages_own_configuration_in_robust_manner.rb
- acceptance/tests/modules/upgrade/that_was_installed_twice.rb
- acceptance/tests/modules/upgrade/with_scattered_dependencies.rb
- acceptance/tests/resource/service/ticket_4123_should_list_all_running_redhat.rb
- acceptance/tests/resource/service/ticket_4124_should_list_all_disabled.rb
- acceptance/tests/resource/zone/ticket_4840_should_create_zone_with_zpool.rb
Update acceptance tests to make the reasons for their status as 'skipped' explicit.
> (PUP-5284) Make test skip reasons explicit

- lib/puppet/network/rights.rb
- spec/unit/network/rights_spec.rb
Previously, an unauthenticated client could make a request to a route
protected by auth.conf and get back an error message including the IP address
and rule description. This is more information than is probably good to
provide over http, especially since it could potentially include internal IPs
of proxy servers, depending on how those are configured. This commit makes it
so that the response includes minimal information.
> (PUP-6150) Don't include IP address in auth error response

- lib/puppet/resource/capability_finder.rb
- spec/unit/resource/capability_finder_spec.rb
Previously when looking up capability resources, the compiler would
lookup resources resources strictly by code id. This effectively meant
that a node couldn't run against a certain code version until all of its
dependencies had run against that version.
For iterative development on changes that don't actually touch those
dependencies, this is an extremely onerous requirement. Further, it's
not sufficient for a node to only run after its dependencies; if the
capabilities it requires are changing, it needs to be run *quickly*
after its dependencies, which is a property that isn't satisfied by the
ordering requirement alone.
In order to provide more flexibility around running agents, particularly
when capabilities aren't being affected by a given change, we now use
any available version of …
> (PUP-6394) Relax code id requirement when finding capabilities

- lib/puppet/provider/mailalias/aliases.rb
mailalias aliases povider double-quotes recipient address
if it contains non-alphanumeric and few selected characters (- . @).
This list can be extended with plus ("+") character as it's very
common in e-mail addresses and it's not necessary to quote such e-mail
address. Current behavior doesn't break anything (it's not bug),
on the other hand if Puppet works on same file with other tools,
Puppet keeps changing these recipients, although not necessary.
This simple patch adds plus character into list of accepted
characters for NOT quoting the recipient.
> (PUP-6349) Don't quote mailalias recipients with +

- lib/puppet/provider/package/pip.rb
- spec/unit/provider/package/pip_spec.rb
We really shouldn't use this code any more. But we are using it.
Pypi changed behaviour today because of vulnerabilities in urrlib, which
is used by pip.
http://blog.blindspotsecurity.com/2016/06/advisory-http-header-injection-in.html
Pypi changed to denying http requests entirely instead of redirecting to
https. (I guess? I don't really understand)
Without this patch:
root@derpderp:~# cat foo.pp
package { 'diskimage-builder':
ensure   => latest,
provider => pip,
}
root@derpderp:~# puppet apply foo.pp
Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
(at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
Notice: Compiled catalog for derpderp in environment production in 0.14 seconds
Error: Could not get …
> (PUP-6413) Use https when talking to pypi

- api/docs/http_report.md
- api/schemas/report.json
- lib/puppet/transaction/report.rb
- spec/unit/transaction/report_spec.rb
`noop_pending` flag is set to `true` when noop resource events are available
> (PUP-6369) Add noop_pending flag to puppet report

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
This commit removes the tracking of specific systemd states and
replaces it with the exit code of the "is-enabled" subcommand.
This needs to be done so that the systemd provider always follows the
operating system's view of what enabled or disabled is, according to
its documenation[1] and shipped version of the init system.
[1] https://www.freedesktop.org/software/systemd/man/systemctl.html#is-enabled%20NAME...
> (PUP-6370) Honor systemd exitcodes as truth

- lib/puppet/util/plist.rb
- spec/unit/util/plist_spec.rb
CFPropertyList::List.new() can raise "NoMethodError: undefined method `elements' for nil:NilClass" if the data to parse isn't a valid (e.g., zero-length or not a plist).
* Catch NoMethodError in parse_plist
* explicitly return convert_cfpropertylist_to_native_types()
* add a 'return nil' at the end of read_plist_file so callers won't end up with the return value of Puppet.warning(...) if things fall through.
> (PUP-6410) puppet/util/plist should handle malformed plist data

- lib/puppet/application.rb
- spec/integration/agent/logging_spec.rb
When the verbose or debug flags are used log output is sent to the
default logger (syslog/eventlog) and console regardless if logdest is
set.
Without this PR
`puppet agent --verbose` prints to syslog and console
`puppet agent --verbose --logdest=syslog` **prints to syslog and console**
`puppet agent --verbose --logdest=console` prints only to console
With this PR
`puppet agent --verbose` prints to syslog and console
`puppet agent --verbose --logdest=syslog` **only prints to syslog**
`puppet agent --verbose --logdest=console` prints only to console
> (PUP-6125) send verbose/debug messages to console when logdest is unset

- lib/puppet/provider/package/pip.rb
- lib/puppet/provider/package/pip3.rb
The comment in the code pointed to a URL for pypa docs that was out of
date. This commit fixes the URLs.
> (doc) Update link to pypa in comments

- lib/puppet/provider/user/aix.rb
- spec/unit/provider/user/aix_spec.rb
This is fixed in Puppet 4 due to a rewrite of the parser.
This commit updates the handling of the attributes input to make sure
they are converted to an array. The parser previously converts single
element arrays into strings, causing this bug.
> (PUP-2316) Allow single element attribute array for AIX user.

- acceptance/tests/resource/service/ticket_1343_should_add_and_remove_symlinks.rb
This commit removes the pinned run order of the expected symlinks
created for the `netconsole` service. Prior to this commit,
Scientific Linux 6 instances were failing this test when the
generated run order did not equal '50'.
> (PUP-6228) Unpin run order in netconsole rc.d links

- acceptance/tests/resource/scheduled_task/should_modify.rb
- lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
- PR #5038 was accidentally merged out of order from #5036
and dragged in some almost, but not quite complete changes for
PUP-1498 that were still in progress.
- This commit adds the changes needed to make the test pass properly
and adds some additional notes about usage of the
Win32::TaskScheduler API
> (PUP-1498) scheduled_task test fixes

- lib/puppet/application/lookup.rb
- lib/puppet/data_providers/hiera_config.rb
- lib/puppet/functions.rb
- lib/puppet/functions/assert_type.rb
- lib/puppet/info_service/class_information_service.rb
- lib/puppet/parser/ast/pops_bridge.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/evaluator/relationship_operator.rb
- lib/puppet/pops/loaders.rb
- lib/puppet/pops/merge_strategy.rb
- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/type_parser.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/functions/match_spec.rb
- spec/unit/functions/regsubst_spec.rb
- spec/unit/functions/split_spec.rb
- spec/unit/functions/versioncmp_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/p_type_set_type_spec.rb
- spec/unit/pops/types/ruby_generator_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
A new TypeParser was created in lots of places in the code while other
places, like the evaluator, used a locally cached instance. Since using
a cached instance is quite safe, it's better to maintain such an
instance as a singleton in the class itself. This commit adds this
singleton and replaces all calls to TypeParser.new.
> (maint) Use singleton pattern for TypeParser

- acceptance/tests/resource/scheduled_task/should_modify.rb
Ruby 1.9.3 has an ecoding bug in REXML, where it disregards the text encoding on a
string in preference for the XML header encoding value.  This causes an issue because
the XML file is encoded as UTF8.  In this commit we modify the XML Encoding header
returned by schtasks.exe to be UTF-8 not UTF-16 if the ruby version matches 1.9x
Additionally fixed a typo in acceptance test as it was calling facter on all agents
instead of the agent under test
The encoding gets very strange because beaker is running a command over SSH so it is hard to determine exactly what the encoding should be.  In this case the string always comes back as UTF8
[ci skip]
> (PUP-1498) Fix scheduled_task acceptance test on ruby 1.9.3

- ext/project_data.yaml
The Win32-Service gem was updated to 0.8.9 however the new gem pulled in a
dependant gem called ffi-win32-extensions which has a name collision on the
FFI:Pointer.read_wide_string method.  This causes Puppet to fail in mutiple
locations.  This commit pins the Win32-Service gem to a prior version without
the dependency.
> (PUP-6445) Pin Win32 gems to explicit versions

- lib/puppet/pops/patterns.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/validator/validator_spec.rb
A class, define, function, or type declaration that uses a name that
start with '::' is illegal. This commit ensures that such names are
trapped by the parser validator.
> (PUP-6361) Add validation error on definition names starting with '::'

- lib/puppet/pops/patterns.rb
The VAR_NAME regexp in Puppet::Pops::Patterns had ':?' instead of
'?:' to denote non-capturing groups. The problem has gone unnoticed
since a) the ':' became optional, and b) no code attempts to use
that expression and extract the groups.
> (maint) Fix incorrect non-capturing group escapes

- lib/puppet/provider/package/dnf.rb
- spec/unit/provider/package/dnf_spec.rb
* Also add spec for default provider-ness
Closes #5052 and re-targets against stable
> (PUP-6430) Add Fedora 24 support for DNF

- lib/puppet/provider/service/smf.rb
- spec/unit/provider/service/smf_spec.rb
The synchronous `-s` flag for `smf restart` only exists in Solaris
11.2 and above. This commit ensures that we don't try to use it in
older Solaris versions.
See https://blogs.oracle.com/SolarisSMF/entry/synchronous_actions
> (PUP-6233) Only use smf restart -s flag in Solaris 11.2 and above

- lib/puppet/util/command_line.rb
- spec/unit/util/command_line_spec.rb
Previously, calling `puppet --help` would generate an error, because the
absence of a subcommand meant we created a NilSubcommand with an arg
count greater than 0:
Error: Could not parse application options: invalid option: --help
This commit alters the `find_subcommand` logic so that if a subcommand
is not specified, but --help or -h are, then we return an
ApplicationSubcommand for the `help` application. The result is the same
as if the user had typed `puppet help`, and will show global help for
all installed applications.
Since we return an ApplicationSubcommand and the subcommand is not agent
or master, we update the $LOAD_PATH allowing puppet to return help for
applications in modules. So the behavior of --help vs puppet help is the
same.
> (PUP-6094) puppet --help should show help

- lib/puppet/provider/group/windows_adsi.rb
- lib/puppet/provider/user/windows_adsi.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
Fixes issues with:
* The implementation of `:auth_membership => true` for the Windows ADSI Group provider
* The implementation of `:membership => inclusive` for the Windows ADSI User provider
> (PUP-6450) Fix Windows group and user authoritative membership

- lib/puppet/configurer.rb
- lib/puppet/defaults.rb
- lib/puppet/indirector/request.rb
- lib/puppet/indirector/rest.rb
- lib/puppet/settings.rb
- lib/puppet/settings/server_list_setting.rb
- spec/unit/configurer_spec.rb
- spec/unit/defaults_spec.rb
- spec/unit/indirector/rest_spec.rb
This adds master failover logic to the agent using the new `server_list` setting. The failover happens early in the configurer, with gating to ensure it doesn't happen when the legacy `server` setting is being used, or if the configurer is actually an `apply` run.
The use of the selected master is handled using Puppet's `lookup` system. This allows us to scope the bound server info to all logic that happens within a configuration run, without needing to refactor the entire indirector.
The changes on the indirector side are fairly simple - check if server/port have been bound with `lookup` and if not fall back to the `server` and `masterport` settings.
> (PUP-6376) Add failover logic to the agent

- lib/puppet/application/cert.rb
- lib/puppet/ssl/certificate_authority/interface.rb
- spec/unit/application/cert_spec.rb
- spec/unit/ssl/certificate_authority/interface_spec.rb
This provides a number of usability improvements triggered from the need to add meaningful certificate extension interactions.
When using `puppet cert list` this patch provides command line flags to print all pertinent information about signed and requested certs in either a machine parseable line-wise format[1] or a pretty printed human friendly format[2]. If no format options are given the current view is augmented with a double asterisk[3] to denote that further information is available through an alternate view.
When signing a cert the cert's information is now printed out before being signed. The formatting of this respects the conventions used above for cert listing. There is now an additional flag so admins can enforce an interactive prompt before signing a cert, as well as a flag …
> (PUP-6268) Improve cert listing and add interactivity for cert signing

- acceptance/fixtures/manifest_large_exported_classes_node.pp
- acceptance/lib/puppet/acceptance/environment_utils.rb
- acceptance/lib/puppet/acceptance/temp_file_utils.rb
- acceptance/tests/direct_puppet/supports_utf8.rb
- acceptance/tests/environment/custom_type_provider_from_same_environment.rb
- acceptance/tests/face/parser_validate.rb
- acceptance/tests/language/exported_resources.rb
- acceptance/tests/parser_functions/no_exception_in_reduce_with_bignum.rb
this works as-is, but has the default manifest case commented out.  
https://tickets.puppetlabs.com/browse/PUP-6431 causes parser validate to stall over SSH.
(PUP-5982) Acceptance: test 'parser validate'
Test parser validate with:
* large complex manifest including exported resources (fixture)
* expected failure with bad syntax
* manifest with function definition and call
* manifest with Type alias
(PUP-5982) Acceptance: allow get_test_file_path pre-initialization.
typically, one has to explicitly initialize the acceptance tempdirs when
using the library facilities.  This change works around that, as
required by the test in this ticket.
(PUP-5982) Acceptance: add host selection to mk_tmp_environment
In rare cases, we need to specify a host to create a tmp environment
upon. This might be …
> (PUP-5982) acceptance: add test case for parser validate

- lib/puppet/provider/package/tdnf.rb
- spec/shared_examples/rhel_package_provider.rb
- spec/unit/provider/package/tdnf_spec.rb
The tdnf package provider is used on PhotonOS as a smaller replacement for DNF. This commit adds support for using that package provider when running on Photon OS.
> (PUP-6323) Support tdnf package provider

- lib/puppet/parser/scope.rb
- lib/puppet/pops/evaluator/closure.rb
- lib/puppet/resource/type.rb
- spec/integration/parser/parameter_defaults_spec.rb
- spec/unit/resource/type_spec.rb
A parameter default expression that made an attempt to access a
parameter to the left in the parameter list when that parameter in turn
was unassigned, resulted in an error message "$y tries to illegally
access not yet evaluated $x". That message should only be used when
accessing parameters to the right. An access to an unassigned parameter
to the left should result in the same message as when a required
parameter is unassigned. This commit fixes that.
> (PUP-6463) Improved error message when accessing unassigned parameter

- Gemfile
The RSpec gem has been upgrade to 3.5.0 however this has caused the
Parallel:Spec grouping to fail by not finding any spec files.  This
commit pins the RSpec gem to less then version 3.5.0 and can be
reverted once the grouping code is fixed.
> (PUP-6466) Pin RSpec to less than 3.5.0

- api/schemas/report.json
- lib/puppet/configurer.rb
- lib/puppet/transaction/report.rb
- spec/unit/transaction/report_spec.rb
This commit adds information about which master was successfully
contacted to the report under the master field. This field will be blank
if no master was used (e.g. for `puppet apply` runs) and otherwise take
the form "servername:port".
> (PUP-6378) Add failover information to the report

- lib/puppet/provider/service/init.rb
This commit edits the init service provider to use the correct path for
init scripts on AIX.
> (PUP-1134) Add correct path for init scripts on AIX

- acceptance/tests/server_list_setting.rb
These tests verify that warnings are issued when the user attempts to
specify both server and server_list, as well as that the server_list
setting takes priority when both are specified.
> (PUP-6384) Acceptance: agent failover interacts correctly with server_list setting

- ext/project_data.yaml
An update to FFI (1.9.11) has caused downstream gems to error due to a bug
introduced in 1.9.11.  FFI Github issue 506 (https://github.com/ffi/ffi/issues/506)
shows this is affecting other users of FFI as well.  This commit pins FFI to the
latest known good working version of 1.9.10.  This change will be reverted in the
future once issue 506 is resolved.
> (PUP-6473) Pin FFI to 1.9.10

- acceptance/tests/server_list_setting.rb
In addition, clean up indentation and beaker steps
[skip ci]
> (PUP-6384) Use empty test puppet.conf for failover test

- lib/puppet/pops.rb
- lib/puppet/pops/parser/locator.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/serialization.rb
- lib/puppet/pops/serialization/abstract_reader.rb
- lib/puppet/pops/serialization/abstract_writer.rb
- lib/puppet/pops/serialization/deserializer.rb
- lib/puppet/pops/serialization/extension.rb
- lib/puppet/pops/serialization/instance_reader.rb
- lib/puppet/pops/serialization/instance_writer.rb
- lib/puppet/pops/serialization/json.rb
- lib/puppet/pops/serialization/object.rb
- lib/puppet/pops/serialization/rgen.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/pops/serialization/time_factory.rb
- lib/puppet/pops/types/p_meta_type.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/p_runtime_type.rb
- lib/puppet/pops/types/p_sem_ver_range_type.rb
- lib/puppet/pops/types/p_sem_ver_type.rb
- lib/puppet/pops/types/p_type_set_type.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/serialization/packer_spec.rb
- spec/unit/pops/serialization/rgen_spec.rb
- spec/unit/pops/serialization/serialization_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
This PR adds what's needed to perform serialization/deserialization of primitives, arrays, hashes, and complex objects that are described using the Puppet Object type. The mechanism is designed to work on differnent protocols using an underlying abstract reader/writer. A reader/writer pair for JSON is included in this PR.
> (PUP-5909) Add Serializer and Deserializer and a JSON packer/unpacker

- lib/puppet/type/yumrepo.rb
- spec/integration/provider/yumrepo_spec.rb
- spec/unit/type/yumrepo_spec.rb
Boolean value parsing is now case-sensitive and values must be specified
in all lowercase. Valid values are true|false|yes|no|1|0
> (PUP-4809) Fix yumrepo boolean value handling and spec test

- lib/puppet/pops/patterns.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/new_spec.rb
Before this commit, only `Numeric#new` would accept a white-space between
a sign prefix and the text representing the number. This commit ensures
that the `Integer#new` and `Float#new` functions also accepts this.
> (PUP-6314) Allow white-space between sign and number for numeric new()

- lib/puppet/pops/types/string_converter.rb
- spec/unit/pops/types/string_converter_spec.rb
Before this commit, the objects true, false, and :default was
not subjected to width, precision, and alignment flags. This commit
ensures that they are.
> (PUP-6346) Ensure that format width and precision is applied to literals

- lib/puppet/face/help.rb
- spec/unit/face/help_spec.rb
Previously, if a legacy app raised a StandardError when generating help,
puppet would try to append to the `results` variable that wasn't in
scope:
Error: undefined local variable or method `result'
This commit modifies the method to return the summary message. The
caller appends the appname and summary message to the `puppet help`
output.
> (PUP-6425) Handle errors when generating legacy app help

- lib/puppet/face/help.rb
- spec/unit/face/help_spec.rb
Previously `puppet help` could output nothing if one of the legacy or face-based applications raised an exception that the `help` app wasn't prepared to handle. This often could happen if you installed a module containing an app that had a gem dependency that wasn't installed, e.g. puppet-strings depends on yard, but that's not part of puppet-agent.
The behavior could occur in different ways, because the help application's exception handling wasn't consistent. When getting a listing of all apps via `puppet help`:
* if a face app raised something other than Puppet::Error
* if a legacy app raised a LoadError, like puppet-strings
When getting help for a particular app via `puppet help <app>`:
* if a face app raised something other than Puppet::Error
* if a legacy app raised anything
This …
> (PUP-1512) Display error message if we can't display app help

- lib/puppet/provider/service/debian.rb
- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/debian_spec.rb
- spec/unit/provider/service/systemd_spec.rb
Prior to this pull request, Cumulus Linux defaults to the debian provider which uses init as the parent.  Since Cumulus Linux 3.0 uses systemd, service resources are broken for CL 3 unless the user specifies the systemd provider.  This pull request changes the default provider for CL 3 to be systemd
> (PUP-6381) Use systemd default service provider for Cumulus 3

- ext/project_data.yaml
The FFI issue has been resolved and released as 1.9.13
This reverts commit 258d53597b2f6a460184b8c93cd083e7e3f28ffb.
> (PUP-6477) Revert "(PUP-6473) Pin FFI to 1.9.10"

- lib/puppet/pops/types/string_converter.rb
- lib/puppet/pops/types/type_formatter.rb
- spec/unit/functions/new_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/pops/types/types_spec.rb
Before this commit, the '%p' format and some alternative '#' formats
for string would output a programmatic string representation that
was using Ruby escapes. This commit changes this so that the
programmatic string representation conforms to Puppet syntax.
The following rules apply when the programmatic string representation
is created:
- The following codepoints will be escaped on output:
* 0x0a => \n
* 0x0d => \r
* 0x09 => \t
* 0x22 => \"
* 0x24 => \$
* 0x5c => \\
- All other characters with a codepoint < 0x20 or > 0x7f are represented
using \u{X} syntax (where X is a hexadecimal representation of the codepoint).
- Strings that are safe to quote using single quotes will be single
quoted.
> (PUP-6347) Use Puppet syntax in programmatic string representation

- api/schemas/report.json
- lib/puppet/property.rb
- lib/puppet/transaction/event.rb
- spec/unit/property_spec.rb
- spec/unit/transaction/event_spec.rb
This commit adds a `sensitive` attribute to properties to indicate that
the `should` and `is` values of a given property are sensitive and
should be specially handled. This commit also adds a `redacted` field to
events to indicate that the data contained in this event was sensitive
and has been redacted to prevent information leakage.
> (PUP-6440) Support sensitive data tagging

- lib/puppet/indirector/request.rb
- lib/puppet/indirector/rest.rb
- spec/unit/indirector/rest_spec.rb
Without this change, if failover has not occured, Puppet would ignore
the server_list setting and instead use the legacy server setting.
Now, the agent will use the first entry of server_list if it's
available, and only fall back to the legacy setting if the new setting
is not in use. This will catch any requests made outside of the
"configurer" which is what handles the fallback logic
> (PUP-6475) Use first server_list entry if failover hasn't occured

- Gemfile
- spec/unit/version_spec.rb
- util/rspec_grouper
Rspec_grouper currently tries to access an array of example groups
through a private function children() in RSpec::Core::ExampleGroups
in order to calculate example counts per spec file. With the RSpec
3.5.0 release, the example groups are no longer accessible through
children(). So, rspec_grouper cannot find example groups and is
reporting that no examples can be found.
This commit uses RSpec.world.example_groups instead to access the
array.
Also, version_spec fix.
> (PUP-6467) Fix Parallel Spec grouping for RSpec 3.5.0

- lib/puppet/module_tool/errors/installer.rb
- spec/unit/module_tool/tar/mini_spec.rb
This clarifies that the path is invalid. Prior to this, it wasn't super
clear why the PMT install failed.
> (PUP-6327) better invalid path error

- acceptance/tests/face/parser_validate.rb
puppet acceptance tests run from the root of puppetserver in a submodule
which is at `puppetserver/ruby/puppet`.  In order to use the fixutres in
this test (or any tests) we should use a path relative to the test file
itself, not where beaker thinks itself to be.
[skip ci]
> (PUP-6491) fix parser_validate acceptance test for puppetserver

- lib/puppet/provider/package/pip.rb
- spec/unit/provider/package/pip_spec.rb
Output from "pip install [PACKAGE]==versionplease" must be sorted to
determine latest version
> (PUP-6461) Fix latest package version check in pip package provider

- spec/integration/util/windows/security_spec.rb
- spec/unit/util/windows/sid_spec.rb
- When temp users are created for the sake of tests, they are not
assigned a password, and this causes the ADSI types to create a blank
password for the given user.  At certain times within AppVeyor,
machines are being used to run tests that have a minimum password
policy in place.  This causes test failures for not satisfying the
systems password complexity policy.
Generate random passwords in these instances, ensuring that the
string contains 3 of 5 character classes - upper case, numeric and
additional non-alphanumeric character.
Paired-with: Glenn Sarti <glenn.sarti@puppet.com>
Daniel Lu   <daniel.lu@puppet.com>
> (PUP-6427) Prevent AppVeyor password length fails

- lib/puppet/provider/package/pkgdmg.rb
- lib/puppet/provider/service/launchd.rb
- lib/puppet/util/plist.rb
- spec/unit/module_tool/applications/installer_spec.rb
- spec/unit/module_tool/applications/unpacker_spec.rb
- spec/unit/module_tool/applications/upgrader_spec.rb
- spec/unit/provider/package/pacman_spec.rb
- spec/unit/provider/package/pkg_spec.rb
- spec/unit/provider/package/pkgdmg_spec.rb
- spec/unit/provider/service/base_spec.rb
- spec/unit/provider/service/debian_spec.rb
- spec/unit/provider/service/gentoo_spec.rb
- spec/unit/provider/service/init_spec.rb
- spec/unit/provider/service/launchd_spec.rb
- spec/unit/provider/service/openrc_spec.rb
- spec/unit/provider/service/src_spec.rb
- spec/unit/provider/service/systemd_spec.rb
- spec/unit/provider/service/upstart_spec.rb
- spec/unit/settings_spec.rb
- spec/unit/util/execution_spec.rb
- spec/unit/util/plist_spec.rb
This supercedes #5041 with some changes to commits / commit messages
> (PUP-6398) Adjust specs / code organization to support parallel specs on Windows

- lib/puppet/ssl/host.rb
- Previously the instructions would say something like:
del "C:/ProgramData/PuppetLabs/puppet/etc/ssl/agent.pem" /f
This fails in a cmd.exe prompt, and is the incorrect directory anyhow
Updated so that it shows like:
del "C:\ProgramData\PuppetLabs\puppet\etc\ssl\certs\agent.pem" /f
> (PUP-6115) Fix Windows cert clean instructions

- lib/puppet/ssl/certificate_authority.rb
- lib/puppet/ssl/certificate_authority/interface.rb
- spec/unit/ssl/certificate_authority/interface_spec.rb
- spec/unit/ssl/certificate_authority_spec.rb
This fixes three important issues with the recent SSL Extension work that's landed in Puppet.
> (maint) Fixes for SSL Extension work

- lib/puppet/ssl/oids.rb
The information captured in PUPPET_OIDS in oids.rb is duplicated in the
puppetserver codebase. Creating a shared oids file isn't easily
achieveable today, so instead this commit adds a comment to the oids.rb
file explaining that any changes to the oids need to be replicated in
the puppetserver codebase.
> (PUP-6335) Add note explaining duplication to oids.rb

- lib/puppet/pops/parser/interpolation_support.rb
- lib/puppet/pops/parser/slurp_support.rb
- spec/unit/pops/parser/parse_basic_expressions_spec.rb
This commit fixes a lexer problem that prevented nested string
interpolations. A nested expression would shift a @token_queue
and "steal" a token that was intended for the top-level interpolation
expression only. Now, tokens already on the @token_queue will be left
intact by nested interpolations.
> (PUP-5887) Fix problem with nested string interpolation

- acceptance/tests/agent/should_not_use_cached_catalog_with_test_flag.rb
This commit adds an acceptance test to verify that using the
`--test` flag with `puppet agent` overrides the `--use_cached_catalog`
setting. This combination should not result in the use of a cached
catalog.
> (PUP-6042) acceptance: test flag overrides use_cached_catalog

- lib/puppet/module.rb
- spec/unit/module_spec.rb
Before this, an unparseable metadata.json would result in a logged
message at DEBUG level. This is something users typically do not do.
Now, there is always a warning, and if --strict=error is on, the
operation fails with a hard error.
> (PUP-5723) Improve error message when metadata.json cannot be parsed

- lib/puppet/pops/evaluator/collector_transformer.rb
- spec/integration/parser/collection_spec.rb
Before this, a query for a literal undef value in a collector would
lead to an exception.
This was caused by the collector transformer not handling a
LiteralUndef.
The fix is to add support for LiteralUndef in the transformer.
> (PUP-5463) Fix collector query with literal undef

- lib/puppet/pops/evaluator/access_operator.rb
- spec/integration/parser/compiler_spec.rb
Before this it was possible to reference classes using a bare
word with initial UC. When evaluating that, the evaluator must
resolve the type reference (for example `Foo`) which may lead to
resolution of `Foo` as a resource type. If at the same time, references
to resource types are validated (to exist), the user will later get an
error. (For the time being, such references are left unresolved until
actually used as a resource reference which makes it harder to report
the source location).
This commit adds a deprecation warning (or error/off) under the control
of the strict flag.
> (PUP-6083) Deprecate use of UC/Resourceref as <ref> in Class[<ref>]

- lib/puppet/util/windows/adsi.rb
- spec/unit/util/windows/adsi_spec.rb
(PUP-5938) Fix localized WinNT BUILTIN monikers
- When building WinNT monikers, BUILTIN and NT AUTHORITY cannot be
used to refer to users / groups and those names must be replaced
with "."  For instance, SYSTEM account must use the moniker:
WinNT://./SYSTEM,user - NOT WinNT://NT AUTHORITY/SYSTEM,user
455834e7f21f213e9d0085510d5b47c0c3e2a1ab added the initial code for
User moniker generation to take that into account
Similarly, a group moniker for Administrators should use:
WinNT://./Administrators,group - NOT WinNT://BUILTIN/Administrators,group
bd3f3a18fa4b5ae1f1f26d8aabf74edd18598746 made sure that monikers
for groups followed this behavior correctly as well.
NOTE: These monikers are used only for adding / removing users to
groups, or groups to a user - and aren't always able to be used …
> (PUP-5938) Fix localized WinNT BUILTIN monikers

- lib/puppet/util/windows/adsi.rb
- lib/puppet/util/windows/process.rb
- spec/integration/type/file_spec.rb
- spec/integration/util/windows/adsi_spec.rb
- spec/integration/util/windows/principal_spec.rb
- spec/integration/util/windows/process_spec.rb
- spec/integration/util/windows/security_spec.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/package/windows/package_spec.rb
- spec/unit/provider/package/windows_spec.rb
- spec/unit/util/storage_spec.rb
- spec/unit/util/windows/sid_spec.rb
- When retrieving the names of users / groups and their attributes
through WMI, Ruby will unfortunately convert any returned strings
into the local codepage (Default.external_encoding) instead of
converting the values from UTF-16LE to UTF-8 for internal
consumption.
This then causes problems with Puppets logging when attempting to
combine strings that are in UTF-8 and the local encoding.  This was
observed on French Windows where the default encoding is CP850.
Without these changes `puppet resource user` will fail to run with
the error:
Error: Could not run: incompatible character encodings: UTF-8 and CP850
> (PUP-6499) Ensure Windows ADSI strings UTF-8

- api/schemas/report.json
- lib/puppet/defaults.rb
- lib/puppet/property.rb
- lib/puppet/resource/status.rb
- lib/puppet/transaction/event.rb
- lib/puppet/transaction/persistence.rb
- lib/puppet/transaction/report.rb
- lib/puppet/type/notify.rb
- spec/integration/transaction/report_spec.rb
- spec/spec_helper.rb
- spec/unit/transaction/event_spec.rb
- spec/unit/transaction/persistence_spec.rb
The corrective_change field in events marks an event that was presumed to be a
manual out-of-band change from Puppet, that Puppet then corrected. In the
context of a noop or non-applying change, the same is true except that the
change was not corrected but is intended to be corrected once a real run is
applied.
This patch introduces the work necessary to calculate this change, introducing a
transaction store that stores the last known best applied value so we can
calculate that a change was indeed unexpected.
For each report, we also mark the resource that had a corrective_change plus
mark an overall report of this also so this information can be stored in
backends like PuppetDB for quick searching.
A metric has also been included, to count all resources that had
corrective_change marked …
> (PUP-6295) New corrective_change field

- lib/puppet/property.rb
- lib/puppet/transaction/resource_harness.rb
- spec/unit/transaction/resource_harness_spec.rb
This commit redacts event value fields for sensitive properties to
ensure that sensitive information isn't inappropriately logged or
stored.
> (PUP-6441) Redact event value contents

- acceptance/tests/face/help_test.rb
- acceptance/tests/ruby_compiler_optimization.rb
- acceptance/tests/windows/QA-506_windows_exit_codes_test.rb
- acceptance/tests/windows/QA-563_windows_exit_mcollective.rb
- acceptance/tests/windows/QA-760_win_dash_dot_file_test.rb
- acceptance/tests/windows/winexitcode/manifests/execute.pp
- acceptance/tests/windows/winexitcode/manifests/init.pp
This commit adds acceptance tests that were previously tested
as part of Puppet Enterprise. These tests are universally applicable
to the puppet product and are therefore being moved here.
> (PUP-6468) Add acceptance tests from PE

- Gemfile
- ext/project_data.yaml
- Hiera has an unbound dependency on json_pure. json_pure 2.0.2+
explicitly requires Ruby >= 2.0, though support was dropped for
Ruby 1.9 in json_pure 2.0.0 (though mistakently the Gemfile was
not updated).
Pin json_pure to a 1.8 series release everywhere.
Without this commit, bundler will pick json_pure 2.0.2 and then
fail to bundle install on Ruby 1.x.
> (PUP-6551) Pin json_pure to ~> 1.8

- Gemfile
- Rakefile
- lib/puppet.rb
- lib/puppet/face/help.rb
- locales/config.yaml
- locales/puppet.pot
Goal is to incorporate the gettext_setup gem, externalize a single string, and produce a pot file from a rake task. Expanded modestly from original scope (now externalizing all strings in help.rb) to work through a variety of translation scenarios.
> (PUP-6474) Incorporate gettext_setup gem into pupppet

- Gemfile
- ext/project_data.yaml
- lib/puppet/provider/user/aix.rb
- spec/unit/provider/user/aix_spec.rb
This is a merge up from 3.x. Note that several of the 3.x changes amounted to noops on stable, specifically:
* the pip provider is no longer XMLRPC based, but shells out to the pip cli, see https://github.com/puppetlabs/puppet/pull/4832
* the windows gem pinning already happened in stable, see https://github.com/puppetlabs/puppet/pull/5062
> 3.x merge to stable

- Gemfile
- ext/project_data.yaml
The cfpropertylist gem is needed to run unit tests against code that
parses plist files. We've gotten around this with lots of mocking and
stubbing in the past, but it's coming up to bite us in
https://github.com/puppetlabs/puppet/pull/5119
The core issue is that Windows is not the "ruby" platform - it's
"mingw". This adds a new special "all" platform to project_data.yaml,
where we can add gems which shouldn't be platform-constrained.
Probably what we really need is more complex logic around whether
platform-specific gems are needed only at runtime or also for tests,
and around which platform-specific gems are installable on a broader
array of platforms. This unblocks the above PR, though.
> (maint) install cfpropertylist gem on all platforms

- lib/puppet/parser/environment_compiler.rb
- spec/unit/parser/environment_compiler_spec.rb
A common pattern for hiera_include is to put it at topscope, which
causes environment compilation to fail as the behavior of hiera_include
(or hiera in general) isn't well-defined for the environment compiler.
In order to allow users to immediately start using application
management and direct change without needing to modify how they do
classification, we now simply ignore and warn if hiera_include is called
by the environment compiler.
> (PUP-6527) Ignore hiera_include calls from environment compiler

- Gemfile
- locales/puppet.pot
This update remove location comments from the auto-generated .pot
file to reduce source control churn.
> (maint) Update to gettext-setup 0.4 and regenerate .pot file

- api/schemas/catalog.json
- lib/puppet/parser/resource.rb
- lib/puppet/resource.rb
- spec/unit/parser/resource_spec.rb
- spec/unit/resource/catalog_spec.rb
- spec/unit/resource_spec.rb
Our current JSON based serialization format is limited in the data types
it can handle; this falls over for rich data types such as the Sensitive
type. This commit adds a sensitive field to resources to pass parameter
level sensitivity in a serializable manner.
> (PUP-6435) Convert sensitive params to resource metadata

- ext/project_data.yaml
- Version 0.8.7 of the win32-service gem had a bug that prevented it
from properly retrieving all services on Windows 10 with the
Win32::Service.services call.
In particular, the services pvhdparser and vhdparser don't have
delayed start info, which would previously cause errors.
This is fixed in the 0.8.8 version of the gem
> (PUP-6459) Update win32-service to 0.8.8

- acceptance/tests/resource/service/should_query_all.rb
Add a basic acceptance test to ensure that 'puppet resource service' does not error.
[skip ci]
> (PUP-6459) Acceptance test for 'puppet resource service'

- lib/puppet/pops/loader/runtime3_type_loader.rb
The PE-installer uses a non-directory environment during the install
of some modules. The Runtime3xLoader didn't handle this very well since
it then tried to cache a loaded user defined resource type in a
NullLoader instance which resulted in a `nil` return value. As a,
consequence, the loaded resource type was lost.
This commit fixes the loader so that it handles the case of not having
an environment path. It then skips the attempt to load a pcore type
definition and will always cache the value in the Runtime3Loader (as it
did before the pcore resource type definitions were introduced).
> (PUP-6558) Fix problem when loading UDRTs in non-directory environment

- api/schemas/report.json
- lib/puppet/defaults.rb
- lib/puppet/property.rb
- lib/puppet/resource/status.rb
- lib/puppet/transaction.rb
- lib/puppet/transaction/event.rb
- lib/puppet/transaction/persistence.rb
- lib/puppet/transaction/report.rb
- lib/puppet/transaction/resource_harness.rb
- lib/puppet/type/notify.rb
- spec/integration/transaction/report_spec.rb
- spec/spec_helper.rb
- spec/unit/property_spec.rb
- spec/unit/transaction/event_spec.rb
- spec/unit/transaction/persistence_spec.rb
The corrective_change field in events marks an event that was presumed to be a
manual out-of-band change from Puppet, that Puppet then corrected. In the
context of a noop or non-applying change, the same is true except that the
change was not corrected but is intended to be corrected once a real run is
applied.
This patch introduces the work necessary to calculate this change, introducing a
transaction store that stores the last known best applied value so we can
calculate that a change was indeed unexpected.
For each report, we also mark the resource that had a corrective_change plus
mark an overall report of this also so this information can be stored in
backends like PuppetDB for quick searching.
> (PUP-6295) Add corrective_change field to report and report events

- acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
Upstream httpd package requires an updated libnghttp2 package but is not
defined as such.
https://bodhi.fedoraproject.org/updates/httpd-2.4.23-4.fc23
https://bugzilla.redhat.com/show_bug.cgi?id=1358875
> (PUP-6549) add libnghttpd2 for fedora23 acceptance

- lib/puppet/network/http/rack/rest.rb
Add support for $trusted facts work with apache/unicorn
or nginx/unicorn via X-SSL-Client-Cert variable.
This PR is meant to replace #5013. It includes the same commit but
with a reformatted commit message.
> (PUP-6366) Support $trusted facts with apache/unicorn or nginx/unicorn

- acceptance/tests/windows/QA-563_windows_exit_mcollective.rb
This commit removes the English STDOUT assertion. Now that i18n
work is being integrated into Puppet products, English assertions
are no longer universally valid.
This test was failing when run against non-English versions of
Windows due to the localized translation of the service start/stop
messages. The test will now rely on the exit code to determine
success.
This commit duplicates commit `405e75a` from `pe_acceptance_tests`
repository.
> (PUP-6570) Remove English MCO assert

- lib/puppet/util/windows/adsi.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
- A new method localized_domains was introduced in 05d1ca2 to
Puppet::Util::Windows::ADSI::Shared to handle properly generating
URIs when the names BUILTIN and NT AUTHORITY are localized on
non-English versions of Windows.
At that time, the calls should have been mocked in:
* provider/group/windows_adsi_spec.rb
* provider/user/windows_adsi_spec.rb
The calls actually touch the system, and depending on test
ordering and how calls to name_to_sid_object are mocked, the code
execution path could produce failures.
Fix this oversight by simply mocking the return values for
localized_domains as they are not needed for these tests.
Paired-with: Daniel Lu <daniel.lu@puppet.com>
> (PUP-5938) Fix localized_domain test mocks

- lib/puppet/provider/user/windows_adsi.rb
- lib/puppet/type/user.rb
- lib/puppet/util/windows/adsi.rb
- lib/puppet/util/windows/user.rb
- spec/integration/util/windows/user_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
- `puppet resource user` will make calls to LogonUserW for each local
user that exists when enumerating / populating the user resources.
Unfortunately, it does so with a nil password (given the values are
not derived from a manifest).  The Windows API, even when a user
actually has an empty password, will return 1327 for account
restrictions when trying to call LogonUser.
This prevents additional calls to LogonUser with the wrong password
(which could cause accounts to be locked out), and it also adds
some warnings to Puppet to inform users that when users have blank
/ empty passwords, that Puppet will always set them, and will
always generate spurious change notices as a result.
> (PUP-6483) Prevent `puppet resource user` logins

- acceptance/Rakefile
This commit adds the package/yum and
service/ticket_5024_systemd_enabling_masked_service tests to the
smoke list of tests used for component testing. These two tests
have revealed issues with changes to support corrective change reporting
in PUP-6295.
> (maint) Add resource acceptance to smoke list

- lib/puppet/property.rb
- lib/puppet/transaction/event.rb
- lib/puppet/transaction/resource_harness.rb
We were previously just using the resource title instead of full
Type[title] syntax for looking up resources in the transactionstore.
This patch simply switches us to use the #to_s method instead of
> (PUP-6578) Use resource Type[title] for accessing system_values

- lib/puppet/provider/package/gem.rb
This allows consistent behavior for both gem provider on both linux and windows.
> (PUP-6563) Wrapping version in quotes on windows

- lib/puppet/pops/adapters.rb
- lib/puppet/pops/loader/base_loader.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/loader/null_loader.rb
- lib/puppet/pops/loader/puppet_function_instantiator.rb
- lib/puppet/pops/loader/puppet_resource_type_impl_instantiator.rb
- lib/puppet/pops/loader/runtime3_type_loader.rb
- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/loaders.rb
- spec/unit/functions4_spec.rb
- spec/unit/pops/loaders/loader_paths_spec.rb
- spec/unit/pops/loaders/loaders_spec.rb
- spec/unit/pops/loaders/module_loaders_spec.rb
Before this commit, 4x loaders were bound to AST model elements. That
was less than ideal since an AST model element has the same life cycle
as the environment. A new compile on the same environment would hence
find the loader created and attached to the adapter during the first
compile.
This commit retains the adapter but instead of attaching the actual
loader instance, it attaches the name of the loader. The loader is
then retrieved using scope.compiler.loaders[loader_name]
> (PUP-6582) Remove binding of loaders to AST model elements

- acceptance/tests/language/pcore_resource_types_should_have_precedence_over_ruby.rb
This commit adds an acceptance test to ensure that generated pcore
resource code is loaded over the ruby code that was used to create
it when using custom resource types.
[skip-ci]
> (PUP-6602) Add test for pcore loader precedence

- lib/puppet/generate/type.rb
This commit ensures that the output paths that are reported during
execution of `puppet generate types` correctly reflects the paths of
the generated files.
> (PUP-6594) Fix incorrectly reported output path from puppet generate

- lib/puppet/provider/nameservice/directoryservice.rb
- lib/puppet/provider/user/directoryservice.rb
- spec/unit/provider/user/directoryservice_spec.rb
We get all the data we need from the initial `dscl -readall /Users`; there's no need to specifically go through each user to ask for `ShadowHashData` later on.
Define post_resource_eval in lib/puppet/provider/nameservice/directoryservice.rb to reset @all_present as a poor man's cache invalidation.
If a user record contains both SALTED-SHA512-PBKDF2 and SALTED-SHA512 data, use SALTED-SHA512-PBKDF2, not the other way around.
> (PUP-6502) Use some memoization to stop calling dscl pathologically

- lib/puppet/provider/service/launchd.rb
- lib/puppet/util/plist.rb
- spec/unit/util/plist_spec.rb
If the launchd service provider encounters a file that's not plain text or a binary plist, it will error.
Catch the ArgumentError when trying to pattern match against bad_xml_doctype, and return nil.
> (PUP-6568) handle non-plist binary blobs in launchd service provider

- lib/puppet/pops/evaluator/runtime3_resource_support.rb
- spec/unit/parser/resource_spec.rb
Before this commit, two names `resolved_type` and `fully_qualified_type`
where used to denote the same value in the method #create_resources of
class `Runtime3ResourceSupport`. Depending on code-path, only the former
variable was initialized when the resource type was a class. The
uninitialized variable was then used to test if the resource should be
subjected to class evaluation. This commit ensures that only one name
is used for the variable.
> (PUP-6608) Fix problem with inline classes not getting evaluated

- acceptance/tests/language/pcore_resource_types_should_have_precedence_over_ruby.rb
This commit updates the pcore loader precedence test to execute
on the master only. Prior to this commit, the test failed when run
on an agent.
> (PUP-6602) Confine pcore loader test to master

- acceptance/tests/ensure_version_file.rb
- acceptance/tests/windows/env_windows_installdir_fact.rb
(PA-466) This PR adds a new test to ensure the presence of the version file as laid down by the AIO in accordance with the puppet agent path specification after a recent set of changes to packaging of the AIO impacted the VERSION file creation and a regression was discovered in associated logic. This is added as a new test (as opposed to an additional step in 'ensure_puppet-agent_paths') to take advantage of the benefits of `skip_test` since this test only applies to
packaged artifacts and not git/gem which don't create a VERSION file. 
This PR also adds a test to ensure the fact env_windows_installdir is present and set to the correct directory. This fact is set via the environment.bat file on Windows installations and recently was impacted by a regression in that file, so a test is …
> (PUP-6619) add tests for installdir and version

- spec/unit/module_spec.rb
- Duplicate test from 45b3908e03734388b6c699ffbc4223f43b44a1d5 was
identified in a test analysis blog post at:
http://ortask.com/how-well-is-it-tested-puppet-part-1-of-2/
> (maint) Remove duplicate test from module_spec

- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- lib/puppet/parser/functions/create_resources.rb
- lib/puppet/parser/resource.rb
- spec/integration/parser/pcore_resource_spec.rb
- spec/integration/parser/resource_expressions_spec.rb
- spec/unit/parser/functions/create_resources_spec.rb
`:undef` is the gift that keeps on giving...
The fix we added that filters out nil/undef values in create_resources proved to add too much filtering as it blocked the ability to give a parameter an explicit undef when it did not have a default value expression. OTOH, keeping the undef values meant that validation of relationships failed later. 
This PR fixes both problems and adds tests for use cases that were not earlier covered by tests.
> (PUP-6613) Fix given undef and filtering in relationships

- .gitignore
- function_loading.samples
- lib/puppet/pops/adapters.rb
- lib/puppet/pops/evaluator/external_syntax_support.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/parser/lexer2.rb
- spec/unit/pops/loaders/loaders_spec.rb
This PR contains two performance improvements to remedy regressions that were introduced in 4.6.0. It makes the "function_loading" performance benchmark run more than twice as fast (but not quite as fast as in 4.5.x). The main reason that performance is not on par is that in 4.6.0 we introduce a Puppet call stack. It is expected to slow function calls slightly.
> (PUP-6622) Fix two 4.6 performance regressions

- acceptance/tests/windows/env_windows_installdir_fact.rb
Prior to this commit, the env_windows_installdir_fact.rb test would fail because after all escaping was done, beaker would match a string literal path with two back slashes against a string literal path with four back slashes. The output of Beaker's assert match will have escaped backslashes '\' in facts output, so the output we match against looks like `C:\\\\Program Files...`.
This commit modifies the test to parse the fact output as JSON and perform a string comparison expecting the known correct value. No escaping necessary, so our test is more readable as well.
> (PUP-6619) Correct acceptance test for env_windows_installdir fact

- lib/puppet/pops/resource/resource_type_impl.rb
- spec/integration/application/apply_spec.rb
This commit contains a test that verifies that an apply on an already
existing catalog doesn't trigger a load of a pcore resource type.
The commit also adds an eql? method to the ResourceTypeImpl that
corresponds to its pcore description.
> (maint) Add test to assert that apply doesn't load pcore resource type

- lib/puppet/property.rb
- lib/puppet/transaction/resource_harness.rb
Currently, the corrective change logic uses the normal `should` and
`should=` accessors when messing with property values. This can cause
failures in property `validate` and `should=` if `unmunge` does not
put the data into a state that `munge` or `validate` is happy with.
By using a small amount of metaprogramming magic, we can access the
guts of the property value directly, bypassing those layers of logic
and creating a cleaner "transplant" of the value.
> (PUP-6628) Access @should directly when calculating corrective change

- lib/puppet/parser/resource.rb
- lib/puppet/parser/scope.rb
- lib/puppet/property.rb
In a few places, we were logging errors with locations specified as
<line>:<file>. In general, we specify locations as <file>:<line>, so
these exceptions are now removed.
> (maint) Fix file and line number output for certain errors

- lib/puppet/type/tidy.rb
Since tidy sets path as namevar, puppet tries to create aliases for it. This means multiple tidy resources with the same path (but different matches, e.g.) will fail.
> (PUP-6508) Make tidy resources non-isomorphic

- lib/puppet/type/mount.rb
- spec/unit/type/mount_spec.rb
Removes the mount autorequire on mountpoint file resources to avoid circular dependencies. Future new feature will resolve the File[mountpoint] --> Mount[dir] --> File[permissions] issue that people currently hack around with an exec.
Tightens the regexp on the mount autobefore on nested file resources to ensure only correct file resources are captured. Adds a test to ensure false autobefores are not being captured.
> (PUP-6397) mount remove autorequire and fix autobefore

- lib/puppet/property.rb
- lib/puppet/util/logging.rb
Previously, when a custom type was incompatible with corrective
change, it would log any exception caught at the error level. This
causes Puppet to fail the transaction.
Instead, we should log at a lower level, so that users can look into
making their types compatible without causing catalog applications to
fails in the meantime.
> (PUP-6621) Log corrective_change exceptions at info instead of error level

- lib/puppet/pops/evaluator/closure.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/functions/function.rb
- lib/puppet/pops/loader/puppet_function_instantiator.rb
- lib/puppet/pops/loader/ruby_function_instantiator.rb
- lib/puppet/pops/migration/migration_checker.rb
- lib/puppet/pops/parser/evaluating_parser.rb
- spec/integration/parser/parameter_defaults_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
This refactors Closure into two specific subclasses: Dynamic (for lambdas), and Named (static, bound by loader). This is done to ensure that all Named function closures refer to top-scope in a way that is resolved on demand rather than being bound in a member variable. The dynamic closures must bind to a scope. Such closures may never be bound in something that survives a compilation.
> (PUP-6582) loader bound functions cannot bind scope instance

- lib/puppet/property.rb
- spec/unit/property_spec.rb
We were using a four argument log_exception instead of a 3. This fixes the problem
and puts in a test for the condition.
> (maint) Correct usage of log_exception in property.rb

- lib/puppet/functions/unwrap.rb
- spec/unit/functions/unwrap_spec.rb
This commit adds an unwrap function for sensitive objects; this serves
to expose the plaintext value in case the wrapped value needs to be
operated on/interpolated/etc. While this does remove the safety measure
that the Sensitive object provides it also allows more general use of
the data type.
> (PUP-6623) Define an unwrap function

- lib/puppet/transaction/persistence.rb
- lib/puppet/util/yaml.rb
- spec/unit/util/yaml_spec.rb
This patch strips Ruby tags from the transactionstore before parsing, so we avoid
some deserialization issues.
> (PUP-6629) Be more careful about parsing YAML for transactionstore

- lib/puppet.rb
- lib/puppet/face/certificate.rb
- lib/puppet/ssl/validator/default_validator.rb
Puppet uses a fair amount of magic to request a CSR when using HTTPS for
the first time. While this normally works well enough when running a
Puppet agent this falls over badly with `puppet certificate generate`.
If the command is run on a node that hasn't submitted a CSR for itself
it will submit a CSR for itself before it submits a CSR for the node
requested on the CLI. If `puppet certificate generate` is used to
submit a CSR for the current node this fails badly as Puppet will try to
submit two CSRs for the same node, causing the command to fail.
The culprit behind this is `Puppet::SSL::Host.localhost`, which when
called will generate a CSR for the given node if it doesn't exist. This
function is used when setting up SSL validation and identity checking,
so by trying to validate a …
> (PUP-2018) Only submit one CSR with `certificate generate`

- lib/puppet/face/catalog.rb
- lib/puppet/indirector/face.rb
- spec/unit/indirector/face_spec.rb
Previously, `puppet catalog download` failed with an obscure error:
Instance name "<hostname>" does not match requested key {}
The problem occurred because Puppet::Indirector::Face called
Puppet::Indirector::Indirection#save(key, options) with the wrong set of
arguments. The save method expects to be called with:
def save(instance, key = nil, options={})
Note how the instance to save should be the first argument, key is the
second, and options is optional. But Face was passing key as the instance,
and options as the key, leading to "does not match requested key".
The code originally worked in 2.7.x, but passing options never worked
correctly for any face application. During a security event, we added
validation to the Indirection methods, ensuring the instance being
passed in matched the …
> (PUP-3182) Call Indirection#save with the correct arguments

- lib/puppet/functions/epp.rb
- lib/puppet/parser/functions/epp.rb
Currently the example at: https://docs.puppet.com/puppet/latest/reference/function.html#epp
uses an incorrect path in the example.
This PR fixes that.
> (doc) (DOCUMENT-579) Fix EPP function example path

- lib/puppet/functions.rb
- spec/unit/functions4_spec.rb
Before this commit, a dispatch for Puppet function written in Ruby that
declared zero parameters, would create a Callable with an unlimited
parameter tuple (no parameters, no size). This commit ensures that such
a dispatch adds the size Integer[0,0] to the parameter tuple.
> (PUP-6647) Fix problem with dispatch that declares zero parameters

- .yardopts
- lib/puppet/functions/regsubst.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/lookup/sub_lookup.rb
- lib/puppet/provider.rb
Fixes for docstrings to assist in running `puppet strings` on the Puppet source base itself.
> (doc) Fix minor doc string issues.

- lib/puppet/parser/environment_compiler.rb
- lib/puppet/pops/loader/base_loader.rb
- spec/unit/parser/environment_compiler_spec.rb
Before this commit, the EnvironmentCompiler would add function overrides
when it was instantiated (once for each compile). This approach was
fatal in a long lived environment (where a compile happens more than
once) since a loader doesn't accept a redefine.
This commit ensures that overridden functions are added at the beginning
of a compile and then subsequently removed at the end of that compile.
Overridden functions are preserved and restored in the process.
> (PUP-6650) Ensure that environment compiler overrides are removed

- lib/puppet/functions/defined.rb
- lib/puppet/pops/evaluator/collectors/exported_collector.rb
- lib/puppet/pops/evaluator/runtime3_converter.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/loader/runtime3_type_loader.rb
- lib/puppet/pops/resource/resource_type_impl.rb
- lib/puppet/resource.rb
- lib/puppet/resource/catalog.rb
- spec/integration/application/apply_spec.rb
- spec/lib/puppet_spec/compiler.rb
This commit ensures that Puppet::Resource instances created during
compile will not make attempts to load a Puppet::Type.
> (PUP-6653) Avoid ruby type loading and type redefine clashes

- lib/puppet/provider/user/directoryservice.rb
This commit adds back the dscl read implementation for the `exists?`
method of the user directoryservice provider. Currently, the
`@property_hash` is not being refreshed upon a `create` event. Therefore,
the previous query to `@property_hash.any?` returned `false even
though the user had been created.
> (PUP-6502) Reinstate dscl read for OSX user exists?

- acceptance/tests/environment/variables_refreshed_each_compilation.rb
This commit extends the `sleep` statement in the
`variables_refreshed_each_compilation` test to 61 seconds when
the platform is Solaris.
As per FACT-1497, the `system_uptime.seconds` fact updates
less frequently on Solaris. Prior to this change this test failed
on Solaris due to this issue with facter.
This is a work around and should be reverted when the underlying
facter issue is resolved.
> (PUP-6604) Extend variables_refreshed sleep on Solaris

- lib/puppet/face/epp.rb
- lib/puppet/pops/evaluator/closure.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/functions/dispatcher.rb
- lib/puppet/pops/functions/function.rb
- spec/unit/face/epp_face_spec.rb
This makes epp render use facts from the local node by default, or from a given node with `--node`.
Facts given on the command line (via a reference to a file .json  or .yaml) is merged on top of the node's facts.
> (PUP-6103) Make epp render use facts from localhost

- lib/puppet/pops/lookup.rb
- lib/puppet/pops/lookup/explainer.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/unit/application/lookup_spec.rb
This PR ensures that a lookup explainer is present when
`Puppet[:debug]` is `true` and that the information that it collects
is logged. For cases when `Puppet[:debug]` is `true` and an explainer is
present already (as when using the lookup command with --explain or
--explain-options), then the information from that explainer is mirrored
to the debug logger.
> (PUP-6513) Log lookup explainer info at debug level

- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/time/timestamp.rb
- spec/unit/pops/evaluator/arithmetic_ops_spec.rb
This commit fixes problems that occurs when a Timestamp or Timespan
is on the right hand side of an arithmetic operation and the left
hand side is an Integer or Float. The result of an addition,
subtraction, or multiplication was of the wrong type and some
nonsensical operations that really should be prohibited, were allowed.
A side effect of this fix is an improvement of the error message
when using '%' with a Float on the right hand side. The expression
1 % 1.0
would, before this commit, result in the message:
Operator '%' is not applicable to an Integer
now, the message will instead be:
Operator '%' is not applicable to an Integer when right side is a Float
> (maint) Fix problem with arithmetic involving TimeData on right side

- lib/puppet/property.rb
- The changes made in commits fc9e5b02de9c3876abaafbf879b77423c4d74173
and b941773cf0d138a12be68bb5cb718221ed38795c introduced exception
logging around corrective changes.  When comparison for a Puppet
property by way of insync_values? were performed, the intent was to
propagate this to an end user.
However, the code was written against a code path that didn't exist.
- Instead of refactoring the logging code to allow an info level
exception, emit an info message instead.
This has the downside of not carrying stack trace info in the message,
but has the upside of not changing any existing logging behavior.  A
stack trace at this point is not as valuable as it might seem given
there typically won't be any additional info to glean from it, other
than the failure point.
To make the message …
> (PUP-6629) Emit corrective change messages at info

- lib/puppet/parser/resource.rb
- lib/puppet/resource/type.rb
- lib/puppet/type/component.rb
- spec/unit/pops/types/p_sensitive_type_spec.rb
Before this, a Sensitive type value could only be used directly
in a native resource.
In order to fix this, there are some hoops to jump through.
* a puppet apply does not serialize the resources in the catalog which
means that the processing of sensitive data must take place in the
resources themselves.
* The early unwrapping and marking parameters as sensitive then occur
too early (finish) for classes and user defined types. For native types
there is no evaluation, and finish is only called post compile, but for
user defined resources / classes this occurs when the resource is
evaluated.
> (PUP-6662) Make Sensitive data work in user defined resources

- lib/puppet/application/apply.rb
- lib/puppet/network/http/handler.rb
Profiler output requires `puppet agent` or `puppet apply` to be run with
the `--profile` flag or for `profiler=true` to be set in puppet.conf.
Prior to this patch, profile output was logged at DEBUG level which meant
that the global log level for Puppet Server had to be raised, which required
hand-editing an XML file along with a  service restart before and after
profiling activities.
This patch raises Puppet Server profile output to the default INFO level since
an additional option is already required to enable the profiler. This change
allows on-demand profiling via `puppet agent -t --profile` without the need to
manually re-start the Puppet Server and edit configuration.
> (PUP-6275) Log profiler output at INFO level

- api/schemas/error.json
- lib/puppet/network/http/error.rb
- lib/puppet/network/http/handler.rb
- spec/unit/network/http/error_spec.rb
- spec/unit/network/http/handler_spec.rb
Previously, Internal Server Errors would return an API response that
included a stacktrace.
This is not considered a best practice and on non-standard setups
filesystem locations disclosed in a stacktrace could be considered
sensitive information.
This commit moves to logging the stacktrace at the error level while
returning only the exception message via the HTTP API.
> (PUP-6659) Remove Stacktraces in API responses

- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
Before this commit, the actual type in a type mismatch description was
generalized before it was included in an error message which resulted
in confusing and incomplete messages. This commit removes the
generalization.
> (PUP-6669) Improve error messages from TypeMismatchDescriber

- acceptance/tests/reports/corrective_change_new_resource.rb
- acceptance/tests/reports/corrective_change_outside_puppet.rb
- acceptance/tests/reports/corrective_change_via_puppet.rb
This PR contains two commits:
25c2843 - modify the existing corrective_change test (corrective_change_new_resource.rb) so that it tests precisely what its test_name suggests it will test
25a9a63 - adds two new acceptance tests. This includes the test scenario that corrective_change_new_resource.rb was previously covering, so we don't lose any test coverage.
> (PUP-6295) Acceptance tests for the corrective_change flag

- lib/puppet/functions/break.rb
- lib/puppet/functions/next.rb
- lib/puppet/functions/return.rb
- lib/puppet/parser/ast.rb
- lib/puppet/parser/ast/pops_bridge.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/parser/functions/break.rb
- lib/puppet/parser/functions/next.rb
- lib/puppet/parser/functions/return.rb
- lib/puppet/pops/evaluator/closure.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/functions/dispatcher.rb
- lib/puppet/pops/functions/function.rb
- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/puppet_stack.rb
- lib/puppet/pops/validation.rb
- spec/unit/functions/break_spec.rb
- spec/unit/functions/next_spec.rb
- spec/unit/functions/return_spec.rb
- spec/unit/pops/puppet_stack_spec.rb
This adds the functions break(), next() and return() which control the order of evaluation:
* break() breaks the innermost iteration as if end of input was reached
* next() returns a value from a lambda, function, class body or define body
* return() returns a value from a function, class body or define body
When next() or return() is used to break() a class or define body, the value is ignored.
> (PUP-4643) Add evaluation control functions break(), next(), and return()

- lib/puppet/pops/evaluator/compare_operator.rb
- lib/puppet/pops/time/timespan.rb
- spec/unit/pops/types/p_timespan_type_spec.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
Before this commit, a `Timespan` or `Timestamp` would yield `true` when
the operator `>=` or `<=` was used to compare them with an `Integer` or
`Float` that had the same magnitude (seconds or seconds since epoch) but
yield `false` when using the operator `==` on the same operands. This
commit changes this so that the latter case also yields `true`.
> (maint) Make time data compare equal to numbers with the same magnitude

- lib/puppet/parser/functions/strftime.rb
- lib/puppet/pops/time/timespan.rb
- lib/puppet/pops/time/timestamp.rb
- lib/puppet/pops/types/p_timestamp_type.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- spec/unit/functions/strftime_spec.rb
- spec/unit/pops/types/p_timespan_type_spec.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
Before this commit, a Timespan or Timestamp type that was parameterized
with just one parameter, would interpret this as a `from` argument and
consider the `to` argument unbounded. That contradicts from the Integer
and Float ranges where one argument is considered to define both 
boundaries (i.e. a range that is limited to an exact match).
This commit ensures that the Timespan and Timestamp type behaves the
same way as the Integer and Float types when only one parameter is used.
> (maint) Enforce consistent behavior on numeric type ranges

- lib/puppet/parser/functions/new.rb
Adds documentation that explains how to create an instance of
Timespan och Timestamp using the Puppet `new()` function.
> (PUP-6681) Add documentation for Timespan.new and Timestamp.new

- lib/puppet/util/tagging.rb
- spec/unit/util/tagging_spec.rb
This patch updates the tag validation regex so that it is anchored by `\A` and
`\Z` instead of `^` and `$`. The issue with using `$` is that it will terminate
validation when a newline is encountered, which allows non-valid tags to pass
through, which causes catalogs to be rejected by PuppetDB. The updated pattern
matches the anchors PuppetDB uses to validate tags.
> (PUP-6670) Update tag validation regex to handle newlines

- acceptance/tests/resource/tidy/resources_should_be_non_isomorphic.rb
Add an acceptance test for validating tidy resources
This PR is to verify that multi tidy resources with same path but different matches should not cause errors as found in the bug PUP-6508
[skip ci]
> (PUP-6655) Acceptance: tidy resources should be non-isomorphic

- MAINTAINERS
- README.md
Hi @hlindberg @joshcooper @MikaelSmith @thallgren @branan @HAIL9000 @Iristyle @whopper @adrienthebo @johnduarte @er0ck:
Anticipating some possible questions:
* This PR add a MAINTAINERS file to document who is maintaining this repo. The list of people started with the top 10 PR mergers in the last year, plus a little conversation from Michael and me here https://github.com/puppetlabs/kylo_scratchpad/pull/1/files#r76349506.
* If the list seems wrong, let's feel free to edit it.
* The format of the file is documented here: http://github.com/puppetlabs/maintainers
* And I used https://rubygems.org/gems/maintainers to construct the file
* I pushed the PR branch to the puppetlabs space (rather than mine) so that all parties can edit collaboratively as needed
* Note that this is a public repo. …
> (maint) Add a MAINTAINERS file

- lib/puppet/parser/functions/new.rb
- lib/puppet/pops/time/timespan.rb
- lib/puppet/pops/types/p_timespan_type.rb
- spec/unit/functions/strftime_spec.rb
- spec/unit/pops/time/timespan_spec.rb
The Timespan incorrectly uses an underscore in the name of the
attributes milli_seconds, micro_seconds, and nano_seconds. This commit
removes this underscore.
> (PUP-6685) Remove underscore from milli_-, micro_-, and nano_seconds

- ext/build_defaults.yaml
This commit updates the key that is used to sign packages. We are
in the process of introducing a new signing key to verify our packages.
As a part of this effort, we need to actually switch over to this new
key for our individual projects.
> (maint) Upgrade to new signing key

- lib/puppet/pops/time/timespan.rb
- lib/puppet/pops/types/type_formatter.rb
- spec/unit/functions/strftime_spec.rb
- spec/unit/pops/evaluator/arithmetic_ops_spec.rb
- spec/unit/pops/time/timespan_spec.rb
- spec/unit/pops/types/p_timespan_type_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
This PR aims to improve how a `Timespan` parses fractions. Instead of just treating the parsed value as milliseconds or nanoseconds, it will consistently be treated as fractions of a second. This is more intuitive and also aligned with how the Ruby implementation of `strptime()` does this (internally used as parser for `Timestamp`).
The PR also fixes the default format so that it contains fractions to avoid loss of precision when converting to and from string. Brought together, those changes made the string output more compact (default format strips trailing zeroes) and hence, more suitable to use a the default representation than the hash.
> (PUP-6686) Improve how Timespan parses and stringifies fractions of second (%L and %N)

- lib/puppet/pops/types/p_timespan_type.rb
- lib/puppet/pops/types/p_timestamp_type.rb
- lib/puppet/pops/types/types.rb
- spec/shared_contexts/types_setup.rb
The Timespan and Timestamp was implemented as Numeric types. This was
not correct as they break the Numeric contract. This commit alters the
type inheritance so that Timespan and Timestamp inherits directly from
Scalar.
> (PUP-6689) Change Timespan and Timestamp inheritance. Numeric => Scalar

- lib/puppet/parser/compiler.rb
- spec/integration/parser/compiler_spec.rb
Before this, symbols (and most likely other data values) leaked into the
puppet language and caused problems (a Symbol is not equal to a String
value).
This commit cleans all values and turns them into Integer, Float,
String, Array or Hash (containing clean values recursively).
> (PUP-6682) Clean $settings values from implementation runtime types

- lib/puppet/pops/evaluator/runtime3_support.rb
- spec/integration/parser/compiler_spec.rb
Before this assignments to $server_facts would go unnoticed unless
--trusted_server_facts was turned on.
Now a warning/error (or ignore) is under the control of the --strict
option.
> (PUP-6693) Add --strict control over assignment to $server_facts

- spec/integration/provider/service/windows_spec.rb
Previously the integration test for the Service provider for Windows used the
lmhosts service as a test fixture.  However in Windows 10 the start type for
this service changed to Manual (Triggered) which now fails the integration test.
This commit adds `:manual` as a valid return value of `enabled?`, which now
matches the provider for service in Windows.
Note that this platform is not tested for integration tests but can easily be tested locally via VMPooler
> (PUP-6641) Fix Service integration test for Windows 10

- lib/puppet/util/tagging.rb
- spec/unit/util/tagging_spec.rb
This reverts commit 06c710a2b227499d7d4710d5884a0f9d218e6467.
We need to revert this in stable until after release of 4.7.0
> Revert "(PUP-6670) Update tag validation regex to handle newlines"

- lib/puppet/pops/types/type_asserter.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/functions/assert_type_spec.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/functions/new_spec.rb
- spec/unit/functions4_spec.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/p_sensitive_type_spec.rb
- spec/unit/pops/types/p_type_set_type_spec.rb
- spec/unit/pops/types/ruby_generator_spec.rb
- spec/unit/pops/types/type_asserter_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
- spec/unit/pops/types/types_spec.rb
This commit PR the ability to pass a parameter indicating present or past tense to the `TypeMismatchDescriber`. All messages are instead hard-coded to use present tense.
> (PUP-6135) Use present tense in type mismatch errors

- lib/puppet/provider/mount/parsed.rb
- lib/puppet/type/mount.rb
- spec/integration/provider/mount_spec.rb
- spec/unit/provider/mount/parsed_spec.rb
- spec/unit/type/mount_spec.rb
Prior to this commit, it was possible for puppet to thing that a
mounted device was in sync with it's resource definition when it was
not. This was because if a resource had already been mounted, and a
remount was attempted with bad options, the remount would fail even
though the entry in /etc/fstab would be updated. Puppet was only
checking the resource options against etc/fstab which meant that
after this point, it would believe the mounted object to be in sync
with the puppet resource describing it, even though it was not.
Now, puppet will check the resource's options against both /etc/fstab
and the output of the mount command (on linux operating systems). This
means that it can now detect if the correct object is not mounted and
will attempt a remount.
> (PUP-6457) Always attempt remount for out of sync options

- lib/puppet/pops/types/types.rb
- spec/unit/functions/new_spec.rb
This commit adds an additional 'abs' argument to the #new functions
of the Numeric, Integer, and Float types.
> (PUP-6291) Add 'abs' support to #new function of Numeric types

- lib/puppet/network/http/api/master/v3.rb
- spec/unit/network/http/api/master/v3_spec.rb
Previously, the /environment/:env route wasn't properly anchored to the
start of the path, so routes with other prefixes would also match.
Because auth is performed separately based on the path, this allowed
requests like /status/environment/production to bypass auth checks and
retrieve environment catalogs. This also meant that other valid requests
ending in /environment/:foo, such as for files, would be handled
incorrectly.
We now properly anchor the /environment/:env regex to the beginning of
the path, so only explicit environment requests will match.
This is a cherry-pick
> (PUP-6636) Only match /environment/:env route as the whole path

- lib/puppet/parser/compiler.rb
- spec/integration/parser/compiler_spec.rb
A regression was introduced in PUP-6682 as the transformation of
settings values to safe values (no symbols) omitted handling boolean
values. They ended up being transformed to string, with the unfortunate
effect that a boolean `false` turned into the string `"true"` which is
"truthy".
This commit adds the correct handling of FalseClass and TrueType so that
they are not transformed to String values.
> (PUP-6701) Make settings data type cleanup handle boolean values

- lib/puppet/parser/functions/new.rb
Adds documentation of the optional `abs` parameter to Numeric#new(),
Integer#new(), and Float#new().
> (PUP-6291) Add documentation of `abs` parameter to #new() function.

- acceptance/tests/environment/variables_refreshed_each_compilation.rb
This commit extends the `sleep` statement in the
`variables_refreshed_each_compilation` test to 61 seconds when
the platform is AIX.
As per FACT-1497, the `system_uptime.seconds` fact updates
less frequently on AIX. Prior to this change this test failed
on AIX due to this issue with facter.
This is a work around and should be reverted when the underlying
facter issue is resolved.
[skip-ci]
> (FACT-1497) Extend variables_refreshed sleep on AIX

- lib/puppet/provider/mcx/mcxcontent.rb
- lib/puppet/provider/nameservice/directoryservice.rb
- lib/puppet/provider/package/pkgng.rb
- lib/puppet/provider/user/directoryservice.rb
- lib/puppet/provider/yumrepo/inifile.rb
- lib/puppet/provider/zpool/zpool.rb
```
lib/puppet/provider/mcx/mcxcontent.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 39.
lib/puppet/provider/nameservice/directoryservice.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 113.
lib/puppet/provider/package/pkgng.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 65.
lib/puppet/provider/user/directoryservice.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 103.
lib/puppet/provider/yumrepo/inifile.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 61.
lib/puppet/provider/zpool/zpool.rb
Array#reverse.each is slower than Array#reverse_each. Occurred at lines: 26.
```
* See https://github.com/JuanitoFatas/fast-ruby and https://github.com/DamirSvrtan/fasterer for more details
> (maint) Performance tweaks for hash key and array looping

- lib/puppet/agent.rb
- lib/puppet/configurer.rb
- spec/unit/agent_spec.rb
- spec/unit/configurer_spec.rb
Without this, a report can be passed to an agent run, but the
transaction_uuid used in that report can't match the transaction_uuid
used for node requests and sending the report. Allow the
transaction_uuid to be passed as an argument to the agent run.
> (PUP-6642) Provide a way to set transaction_uuid for an agent run

- acceptance/tests/reports/failover_master.rb
On 9/14 we had a failed cell (spurious failure) in the matrix run for test
acceptance/tests/reports/failover_master.rb due to a timeout sending the report
to the master for the test modified in this commit, 'master_field should not
appear when no master could be contacted'.
Prior to this commit, this test used two nonexistent servers in a server list
and specified a timeout of 3 seconds. In the beaker run noted, this led to a
test execution time of approximately 25 seconds. This commit updates the
timeout to 5 seconds, but reduces the check to only one nonexistent master as a
way to diminish the impact on overall test time of increasing the timeout.  The
fact that two masters are specified isn't actually intrinsic to the test, so
this should effectively be a no-op in terms of test …
> (PUP-6703) Tweak failover_master test for robustness

- lib/puppet/parser/compiler.rb
- lib/puppet/resource/type.rb
- spec/unit/capability_spec.rb
Before this commit redefining a capability mapping added both mappings to
the capability list. When producing and consuming resources only the
first mapping would be used. Now trying to add the second mapping
results in a ParseError.
In addition we previously evaluated mappings twice. Once before
evaluating main and a second time after evaluating applications. The
capability mappings were not properly cleared after the first
evaluation. As a consequence capability mappings were added twice. It
seems better if we only only evaluate them once so that they are
available for producing resources at a consistent place in compilation.
> (PUP-6087) Error when a capability mapping is redefined.

- lib/puppet/pops/serialization/abstract_reader.rb
- lib/puppet/pops/serialization/abstract_writer.rb
- lib/puppet/pops/serialization/extension.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/pops/types/p_sensitive_type.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/pops/serialization/packer_spec.rb
- spec/unit/pops/serialization/serialization_spec.rb
This commit adds everything needed to let instances of the Sensitive
data type participate in Pcore serialization.
> (PUP-6705) Add Pcore serialization for Sensitive data type

- lib/puppet/pops/serialization/abstract_reader.rb
- lib/puppet/pops/serialization/abstract_writer.rb
- lib/puppet/pops/serialization/extension.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/pops/types/p_sensitive_type.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/pops/serialization/packer_spec.rb
- spec/unit/pops/serialization/serialization_spec.rb
This commit adds everything needed to let instances of the Binary
data type participate in Pcore serialization. The binary will be
serialized using strict base64 encoding. Although not optimal (it
has a 33% overhead), it's widely available, relatively cheap in terms
of CPU-cycles, and well known.
Other algorithms such as base85 (7% less space overhead) is more
expensive to compute and not as common. basE91 has even less space
overhead but contains the double quote. It doesn't seem worth while to
pursue either of them. The pros with base64 outweighs the cons.
Compression was considered but rejected since: a) large binaries might
have be compressed already, b) it's very CPU demanding at both ends, and
c) it's not uncommon that compression is part of the actual transfer
protocol.
> (PUP-6706) Add Pcore serialization for Binary data type

- MAINTAINERS
This commit adds Moses as a maintainer to the puppet MAINTAINERS file, in the
format specified by https://github.com/puppetlabs/maintainers.
> (maint) add Moses as a maintainer

- lib/puppet/functions/strftime.rb
- lib/puppet/parser/functions/new.rb
- lib/puppet/parser/functions/strftime.rb
- lib/puppet/pops/time/timestamp.rb
- lib/puppet/pops/types/p_timestamp_type.rb
- spec/unit/functions/strftime_spec.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
This commit adds a new disptacher to the strftime function which is
backward compatible with the stdlib function with the same name.
The stdlib function also accepted a second `timezone` argument which
the new function did not provideand that was an oversight. It must be
provided to enable formatting of timezones other than UTC. The same
thing is true when parsing timestamps. A timezone must be provided to
parse a timestamp string that doesn't include a timezone unless a
default of UTC is acceptable in all cases (which it of course, isn't).
This commit therefore provides the timezone functionality needed to both
parse and format a timestamp.
> (PUP-6724) Make strftime compatible with function in stdlib

- lib/puppet/provider/package/pip.rb
In 152299cc, as part of PUP-6120, use of the xmlrpc library
was removed from the code, but the require itself was not
removed. This commit simply removes the vestigial require.
Note that this change is required to support ruby 2.4,
which no longer includes the xmlrpc library.
> (maint) Remove unused: requre 'xmlrpc/client'

- lib/puppet/util/tagging.rb
- spec/unit/util/tagging_spec.rb
This reverts commit 862b519b75a77ec904063ba8d0ee3c1cb29f62cf which reverted
06c710a2b227499d7d4710d5884a0f9d218e6467 since we did not want to ship that in
the 1.7.0 release, now that 1.7 has been released the original commit is good
to go back
> (PUP-6670) Revert Revert Update tag validation regex to handle newlines

- lib/puppet/version.rb
After the agent 1.7 release, the version for the next puppet needs to be
bumped
> (PUP-6738) Update version to 4.7.1 post release of 4.7.0

- lib/puppet_x.rb
Even with using the namespace ('user') as part of the PuppetX naming
convention, there still could be conflicts with other existing
modules in the same namespace. This could cause two files from
different modules that share the same name to overwrite each other
when they are synced to the same folder. It may not be immediately
obvious this is the reason when this occurs, and the results can
be disastrous. Due to these reasons, we should recommended that
Puppet Extensions submodules further define folder structure to
include the module name as well.
For example, a Puppet Extension for 'puppetlabs-powershell' would live at `lib/puppet_x/puppetlabs/powershell/<extension.rb>`.
> (doc) Recommend Puppet Extension add module name

- lib/puppet/generate/models/type/type.rb
- lib/puppet/generate/templates/type/pcore.erb
- lib/puppet/pops/resource/resource_type_impl.rb
- lib/puppet/pops/resource/resource_type_set.pcore
- lib/puppet/resource.rb
- lib/puppet/type.rb
- spec/integration/parser/pcore_resource_spec.rb
The capability flag of a resource (initiated by passing the option
`:is_capability => true`) was not included in the generated .pp file, and
also not recognized by the Pcore Resource type. This PR ensures that
the flag is generated by the generator and then handled correctly by
the type.
> (PUP-6714) Add missing capability flag to generated Pcore resource

- lib/puppet/functions/alert.rb
- lib/puppet/functions/crit.rb
- lib/puppet/functions/debug.rb
- lib/puppet/functions/emerg.rb
- lib/puppet/functions/err.rb
- lib/puppet/functions/info.rb
- lib/puppet/functions/notice.rb
- lib/puppet/functions/warning.rb
- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/util/log.rb
- spec/unit/functions/logging_spec.rb
- spec/unit/pops/loaders/static_loader_spec.rb
These commits replace the #create_logging_functions with proper Puppet
functions so that they can be documented separately.
> (PUP-6742) Separate logging functions

- acceptance/tests/language/break.rb
- acceptance/tests/language/next.rb
- acceptance/tests/language/return.rb
This commit adds acceptance tests for the new `return`, `break`,
and `next` iteration control functions introduced as per PUP-4643.
> (PUP-4643) Add acceptance for return,break,next

- lib/puppet/functions/alert.rb
- lib/puppet/functions/crit.rb
- lib/puppet/functions/debug.rb
- lib/puppet/functions/emerg.rb
- lib/puppet/functions/err.rb
- lib/puppet/functions/info.rb
- lib/puppet/functions/notice.rb
- lib/puppet/functions/warning.rb
- lib/puppet/util/log.rb
- spec/unit/functions/logging_spec.rb
This commit changes the helper method for all puppet log functions so
that it returns `nil`. A return_type of 'Undef' is also added to the
dispatcher for the log functions
> (PUP-6753) Ensure that log functions return undef

- api/schemas/catalog.json
- lib/puppet/defaults.rb
- lib/puppet/environments.rb
- lib/puppet/node/environment.rb
- lib/puppet/parser/resource.rb
- lib/puppet/pops/evaluator/runtime3_converter.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/functions/function.rb
- lib/puppet/pops/serialization/deserializer.rb
- lib/puppet/pops/serialization/json.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/resource.rb
- lib/puppet/resource/catalog.rb
- lib/puppet/settings.rb
- lib/puppet/settings/environment_conf.rb
- spec/integration/application/apply_spec.rb
- spec/unit/pops/evaluator/runtime3_converter_spec.rb
- spec/unit/resource/catalog_spec.rb
This PR adds a new `ext_parameters` entry to the JSON object that represents a `Resource`. The `ext_parameters`, like `parameters` is an object keyed by parameter names. The values are however not plain JSON types but instead an array representing an extended type created by the Puppet Serialization API.
Special hooks into the serializer enables several values to be generated, one at a time, while using the same tabulation context for all resources in the catalog.
> (PUP-5834) Add support for resource ext_parameters to catalog

- lib/puppet/parser/functions/new.rb
- lib/puppet/pops/types/p_binary_type.rb
- spec/unit/pops/evaluator/access_ops_spec.rb
- spec/unit/pops/types/p_binary_type_spec.rb
This commit changes the default encoding used by the Binary constructor
from '%b' (relaxed base64) to '%B' (strict base64).
> (PUP-6757) Make Binary use strict base64 encoding by default

- lib/puppet/parser/resource.rb
- lib/puppet/pops/resource/param.rb
- lib/puppet/resource/capability_finder.rb
- lib/puppet/resource/type.rb
- spec/unit/pops/resource/resource_type_impl_spec.rb
Ensures that the export/consume logic of the `Puppet::Resource::Type`
uses a generated Pcore resource type and never makes an attempt to load
the corresponding Ruby type.
> (PUP-6765) Ensure that produce/consume uses generated pcore resource

- acceptance/tests/parser_functions/calling_all_functions.rb
This commit removes the assumption that the 'notice' log function
will return anything in the calling_all_functions tests, as those
functions now return Undef (as they always should have).
[skip ci]
> (PUP-6766) Don't depend on log function return value in tests

- lib/puppet/resource/catalog.rb
- spec/unit/capability_spec.rb
Before this lookup, the code-paths for how a lookup was performed
differed slightly depending on the setting of the `app_management` flag.
While the setting should extend the lookup using the capability finder,
a malformed boolean expression made it have an additional and undesired
side effect.
This commit ensures that the code path is exactly the same until the
point where the decision is made to search for the capability.
> (PUP-6752) Fix diff in catalog lookup caused by app_management flag

- lib/puppet/resource.rb
The actual method name is `is_json_type?`
> (PUP-6774) Fix incorrect call to `is_json_type` in Puppet::Resource

- lib/puppet/pops/serialization/json.rb
- spec/unit/pops/serialization/serialization_spec.rb
- spec/unit/resource/catalog_spec.rb
This PR adds a test that verifies that arrays and hashes containing rich_data can be serialized in a catalog. It also contains a maint commit to fix a problem with unbalanced brackets in the serializer that was found when the test was written.
> (PUP-6774) Add test for ext_parameters containing hashes and arrays rich data

- lib/puppet/type/ssh_authorized_key.rb
- spec/unit/provider/ssh_authorized_key/parsed_spec.rb
* Lines in ssh authorized_keys file may have mulitple space as filed
separator. We need to use \s+ in REGEX instead of plain space.
* Adds spec to detect multiple spaces in ssh line
#5031 rebased with a spec as requested
@kylog can I get a merge or do we need more unit tests? 💃
> (PUP-6417) improve regex of line matching in authorized_keys

- acceptance/lib/puppet/acceptance/puppet_type_test_tools.rb
- acceptance/lib/puppet/acceptance/puppet_type_test_tools_spec.rb
- acceptance/tests/language/sensitive_data_type.rb
* add a test for Sensitive data type and its functions
* test employs a first pass at table driven testing
* could be used for other tests for puppet language and resource types
* the code generation portion could use a bit of work prior to expansion
[skip ci]
> (PUP-6592) acceptance: Sensitive data

- acceptance/tests/language/sensitive_data_type.rb
*  the previous commit did not take into account windows32 pathing
differences when abstracted into cygwin.  This change should allow the
test to run in both 64/32 bit windowses.
this will need a merge-up to master
> (pup-6592) acceptance sensitive data fix

- lib/puppet/pops.rb
- lib/puppet/pops/lookup/context.rb
- lib/puppet/pops/lookup/explainer.rb
- lib/puppet/pops/lookup/invocation.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/lib/puppet_spec/unindent.rb
- spec/spec_helper.rb
- spec/unit/pops/lookup/context_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
This PR adds a new Pcore Object type named `Puppet::LookupContext`
with attributes and methods.
> (PUP-6768) Add Pcore Object type Puppet::LookupContext

- lib/puppet/resource.rb
- spec/integration/application/apply_spec.rb
Before this commit, data that wasn't stricly compatible with JSON would
generate an error when rich_data was set to false. That was a regression.
This commit ensures that such data will be passed through and instead
print a warning.
> (PUP-6799) Allow data with unknown type in the catalog

- lib/puppet/pops/loader/loader.rb
- spec/unit/pops/loaders/dependency_loader_spec.rb
Previously, when calling inspect on a loader we would create a string
that contained the content of calling inspect on everything that is
reachable from a loader. The string formed could be larger than a
gigabyte in memory and would cause out of memory errors in production.
This replaces the default implementation of inspect with a call to #to_s
which is implemented in a number of Loader subclasses already. It also
provides a default #to_s implementation for all loaders.
> (PUP-6807 nee PE-17527) Show pretty string when inspecting loaders

- lib/puppet/provider/package/pkg.rb
- spec/unit/provider/package/pkg_spec.rb
Package installs which update multiple manifests may fail later
resources because the affected services do not exist until manifest
import has completed.
Solaris 11.2 or newer pkg install and update operations will wait
for actuators to complete after this change.
23107546 race condition with smf provider and manifest-import
> (PUP-6749) race condition smf and manifest-import

- lib/puppet/parser/functions/scanf.rb
On this page:
https://docs.puppet.com/puppet/latest/reference/function.html#scanf
The first example is not in a code block.
The second example includes: "- since 4.0.0"
And the "since" should be capitalised to match the rest of the document.
> (doc) (DOCUMENT-596) Fix code tags of scanf function

- acceptance/tests/resource/file/should_create_directory.rb
* there was a regression recently with --app-management and duplicate
file resources with and without a trailing slash. this should prevent
that.
[skip ci]
> (PUP-6790) acceptance: dir resource with and without trailing slash

- acceptance/tests/language/pcore_generate_env_isolation.rb
* add a test that produces an environment isolation issue with
conflicting custom types
* ensure that generating pcore files alleviates the issue
[skip ci]
> (PUP-6779) acceptance: puppet generate ensures env isolation

- lib/puppet/type/user.rb
Prior to this PR, it wasn't clear that groups listed in the `groups`
attribute were also autorequired. See lines 405-407.
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/type/user.rb#L404-406
> (DOCS) Corrected autorequire docs to include groups

- lib/puppet/type/user.rb
Previous one sentence description was insufficient. 
cc: @branan, I changed the sentence about 'inclusive', please take a look to make sure it's still technically accurate.
> (DOCS) Expand membership description

- acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb
Prior to this commit, the test '#6857: redact password hashes when applying in
noop mode' would fail on a host that had 'Password must meet complexity
requirements' set to true, because puppet was applying user management
manifests containing passwords that did not meet said requirements. This commit
updates the test to meet the complexity requirements (documented here:
https://technet.microsoft.com/en-us/library/hh994562(v=ws.11).aspx), allowing tests to pass.
Assumedly prior hosts in the acceptance testing systems were either
pre-configured with this requirement disabled or it was disabled at test time
for other tests (the latter of which seems unlikely).
> (PUP-6827) fix test to meet password complexity reqs

- lib/puppet/data_providers.rb
- lib/puppet/data_providers/data_adapter.rb
- lib/puppet/data_providers/data_function_support.rb
- lib/puppet/data_providers/function_env_data_provider.rb
- lib/puppet/data_providers/function_module_data_provider.rb
- lib/puppet/data_providers/hiera_config.rb
- lib/puppet/data_providers/hiera_env_data_provider.rb
- lib/puppet/data_providers/hiera_interpolate.rb
- lib/puppet/data_providers/hiera_module_data_provider.rb
- lib/puppet/data_providers/hiera_support.rb
- lib/puppet/data_providers/json_data_provider_factory.rb
- lib/puppet/data_providers/yaml_data_provider_factory.rb
- lib/puppet/plugins/data_providers.rb
- lib/puppet/plugins/data_providers/data_provider.rb
- lib/puppet/plugins/data_providers/registry.rb
This commit adds a @api private marker to the yardoc of all classes related
to the lookup provider framework. The reason for this is that the api will
change and several classes will be deprecated when lookup is productized.
> (maint) Mark all methods in the lookup framework api private

- lib/puppet/provider/package/yum.rb
- spec/shared_examples/rhel_package_provider.rb
* Previously, when ensuring latest the logic used to implement PUP-6324
didn’t take ensuring latest into account, just specifying a new version:
```
Debug: /Stage[main]/Main/Package[cockpit]/ensure: cockpit "0.55-1.fc22" is installed, latest is "0:0.67-2.fc22"
Debug: Package[cockpit](provider=dnf_update): Ensuring => latest
Debug: Executing: '/usr/bin/dnf -d 0 -e 1 -y install cockpit'
Notice: /Stage[main]/Main/Package[cockpit]/ensure: ensure changed '0.55-1.fc22' to '0:0.67-2.fc22'
Debug: /Stage[main]/Main/Package[cockpit]: The container Class[Main] will propagate my refresh event
```
* This meant the system reported that the package was updated, but it ran install rather than upgrade, which does nothing and exits zero
* Added new logic for when latest is used, add new spec, all working …
> (PUP-6798) Yum provider family ensuring latest

- lib/puppet/version.rb
This updates Puppet's version to 4.8.0 in preparation for the
puppet-agent 1.8.0 release.
> (PUP-6839) Bump version to 4.8.0

- lib/puppet/provider/package/pkgng.rb
- spec/unit/provider/package/pkgng_spec.rb
In cases where pkg execution fails within instances, the result returned
to prefetch is nil causing prefetch to fail poorly calling .find on a
nil object.  Here we modify the return value of instances in the event
of an exception to be an array instead of nil.  This leaves a cleaner
prefetch behavior intact, and allows the run to continue, even in the
absence of a successful package call.
> (PUP-6758) Fix pkgng provider condition

- acceptance/Gemfile
- acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb
This is a cherry-pick of several commits from master to LTS-1.7, in support of [PA-655](https://tickets.puppetlabs.com/browse/PA-655).
> (PA-655) Add Windows Server 2016 to the LTS agent

- lib/puppet/version.rb
This updates the Puppet version to 4.8.1 following the release of 4.8.0
as part of puppet-agent 1.8.0.
> (PA-652) Bump Puppet version to 4.8.1

- appveyor.yml
Previously the AppVeyor spec tests were executed sequentially.  Now that all of
the unit tests are functioning correctly when run in parallel mode, this commit
changes the execution command for AppVeyor to use parallel spec with two
threads.
> (PUP-6534) Use parallel specs in AppVeyor

- Gemfile
- The webmock gem has always depended on the addressable gem >= 2.3.6
and therefore it has been installed transitively.  As of 2.5.0, the
addressable gem released on Nov 4, 2016 has added a new dependency
on the public_suffix gem, which requires Ruby 2.
Since jobs still run against Ruby 1.9.3, pin addressable to a prior
version that doesn't need the public_suffix gem.
- Note that even when using `bundle install --without development`
this problem occurs, even though the webmock gem should be
excluded from installation. This is a bundler behavior.
> (maint) Fix TravisCI runs on Ruby 1.9.3

- spec/unit/transaction/persistence_spec.rb
Previously the unit test for transaction/persistence checked whether an error
was raised with specific text.  However the text was in English and the test
would fail if used on localized versions of Windows, such as French, where the
message is French.  This commit removes the text in the expectation so that it
will behave correctly on all language versions of Windows.
example error message in French is `Accès refusé`
> (PUP-6871) Fix transaction persistent unit test for non English Windows

- lib/puppet/reference/indirection.rb
originally raised as puppetlabs/puppet-docs#702
> (docs) fix typo in indirector docs (van->and)

- acceptance/tests/language/pcore_generate_env_isolation.rb
- acceptance/tests/reports/corrective_change_via_puppet.rb
Previously, the pcore_generate_env_isolation.rb and
corrective_change_via_puppet.rb tests were failing when run in a CI
configuration with more than one agent in it.  In each case, the test
changed some state after an agent was run on the first node which was
unintentionally picked up as the agent was run on the second node.  This
commit changes both tests to perform all related actions on each of the
nodes before any state changes are made.
> (PUP-6897) Fix for agent mishandling in pcore-gen and cor-change tests

- acceptance/tests/language/sensitive_data_type.rb
Previously, the sensitive_data_type test, when attempting to validate
the presence / absence of expected content in the syslog, performed
assertions against the full Beaker logger instead.  This would cause
assertions looking for the absence of sensitive content to fail for the
second agent run performed because the assertions themselves would
appear in the logger output.
This commit changes the syslog assertion logic to inspect just the
content of the syslog - without bringing in the rest of the current
Beaker logger.  The commit also only runs through the assertions which
confirm that sensitive data does not appear in the syslog and not the
assertions which confirm that other debug messages from the agent run
appear in the syslog.  This is done because the agent is run with a
"--debug" …
> (PUP-6898) Fix sensitive_data_type test validation of syslog output

- lib/puppet/face/config.rb
- lib/puppet/settings/ini_file.rb
- spec/integration/faces/config_spec.rb
- spec/unit/face/config_spec.rb
- spec/unit/settings/ini_file_spec.rb
- Previously, INI files were using the `\w` regex character class to
match the "key" in a INI file line like:
```ini
key = value
```
Unfortunately, `\w` is limited to ASCII characters `[a-zA-Z0-9_]` in
Ruby and will fail to match properly on any Unicode word
characters, such as:
```ini
Aۿᚠ𠜎 = value
```
- The \w regex character class was also used to match the section in a INI file line like:
```ini
[Aۿᚠ𠜎]
```
Unfortunately, due to the same limitation, an INI section like the above would not parse properly.
- Change the `\w` character class to `[[:word]]` which Ruby describes as a:
> character in one of the following Unicode general categories Letter, Mark, Number, Connector_Punctuation
- Supply tests demonstrating previously failing behavior
- In addition to fixing any code paths using …
> (PUP-6876) Fix INI parsing for UTF-8 keys / values / sections and `config set`

- lib/puppet/pops/lookup/interpolation.rb
- spec/unit/pops/lookup/interpolation_spec.rb
An interpolation that uses dotted keys that in turn results in a
`:no_such_key` being thrown (because the key is missing), would not catch the
throw and hence, yield strange results. This commit ensures that the thrown
symbol `:no_such_key` is caught so that the call instead results in an empty
string.
> (PUP-6856) Catch :no_such_key during interpolation sub_lookup

- acceptance/tests/environment/variables_refreshed_each_compilation.rb
Previously, the `variables_refreshed_each_compilation` acceptance test
could fail if the "earlier" uptime value that the test was comparing for
an agent run was lexicographically greater than the "later" uptime value.
For example, an earlier uptime of "9999" would be considered greater
than a later uptime of "10002" and, therefore, fail.
This commit changes the test to convert the uptimes to Integers before
comparing them so that the comparisons are done numerically rather than
as strings.
> (PUP-6911) Do uptime comparisons as integers in var-refresh test

- docs/quickstart.md
- docs/rspec_tutorial.md
- docs/windows.md
Mention 1.8.7 is not supported, and we support more recent versions than
2.1.
Describe executing a single test/group using line numbers and running
parallel specs.
Use rspec 3 syntax, not "should".
Update Windows section as envpuppet.bat is no longer necessary.
/cc @puppetlabs/puppet-maintainers
> (docs) Update developer docs

- lib/puppet/pops/merge_strategy.rb
- spec/unit/data_providers/hiera_data_provider_spec.rb
- spec/unit/pops/merge_strategy_spec.rb
Before this commit, the primary source for a deep merge was dup'ed to avoid
that the deep merge would mutate it (it mutates the primary source). A dup
is however not enough when the source is a nested hash. The dup will only
perform a shallow copy. This commit ensures that the source is deep copied
instead.
> (PUP-6834) Ensure that input to MergeStrategy deep does not mutate

- spec/integration/util/windows/principal_spec.rb
Previously, two tests failed when run on a Windows system whose hostname
exceeded 15 characters. In that situation, ruby's `Socket.gethostname`
returns the full name, e.g. jenkins-slave-windows2012r2-prod-1, which
causes `LookupAccountName` to fail when resolving a name into a SID.
This commit modifies the tests to use the NetBIOS name returned
via Win32 GetComputerNameW[1], which is a truncated version of the
full name, e.g. JENKINS-SLAVE-W.
[1] https://msdn.microsoft.com/en-us/library/windows/desktop/ms724295(v=vs.85).aspx
> (PUP-6913) Use NetBIOS name when resolving names to SIDs in tests

- acceptance/tests/language/sensitive_data_type.rb
By default, puppet logs to different syslog directories depending on the
platform it is running on. When Fedora recently changed how to access
system logs, this test broke, since it was explicitly looking for
specific default log locations on various platforms. This commit refactors the test
to specify a temp file to receive the logs, thereby avoiding brittle
platform-specific code.
> (PUP-6915) Specify log destination for sensitive data type test

- api/docs/http_api_index.md
- api/docs/http_file_content.md
- api/docs/http_file_metadata.md
* Update puppetlabs.com hostnames.
* Add the pluginfacts mount point, which works the same as the plugins one.
> (docs) Minor HTTP API doc fixes

- lib/puppet/provider/mount/parsed.rb
- lib/puppet/type/mount.rb
- spec/integration/provider/mount_spec.rb
- spec/unit/provider/mount/parsed_spec.rb
- spec/unit/type/mount_spec.rb
Revert "Merge pull request #5125 from HAIL9000/issue/master/PUP-6457_fail_on_bad_mount_options"
This reverts commit bcd1654afc5c2b4aa1397f7e0c1f13e02e269883, reversing
changes made to f4b86e08fa87159a84bc819458fdbe7017bcc088.
The original change relied on the idea that `/etc/mtab` would contain
an exact copy of the options specified in `/etc/fstab`. Unfortunately,
this is not correct, and causes this change to be overly-aggressive in
thinking that remounting failed.
Since there does not currently appear to be a way to check that a
mounted filesystem is in-sync with `fstab`, we unfortunately cannot
implement PUP-6457 as-described.
> (PUP-6861) Revert PUP-6457 bad mount option handling

- acceptance/tests/modules/upgrade/that_was_installed_twice.rb
- acceptance/tests/modules/upgrade/with_scattered_dependencies.rb
This commit updates the following PMT upgrade acceptance tests:
```
* tests/modules/upgrade/that_was_installed_twice.rb
* tests/modules/upgrade/with_scattered_dependencies.rb
```
Prior to this commit these tests were being skipped because they
were setting the `modulepath` via the `puppet.conf` file. This
method of managing `modulepath` has been deprecated. This commit
updates the tests to use directory based environments to install
the modules.
> (PUP-6244) Fix skipped PMT upgrade acceptance tests

- lib/puppet/pops/binder/producers.rb
- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/parser/locator.rb
- lib/puppet/pops/serialization/object.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/p_timespan_type.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/serialization/serialization_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
In this commit:
- The `element_type` attribute was removed from the `Collection` type and
instead added to the `Array` type and as `value_type` to the `Hash` type.
- Serialization of registered `Object` types now uses the parameter names
and order of the #initialize method to determine in which order the
contained attributes are serialized.
> (PUP-6924) Improve serialization of parameterized collection types

- lib/puppet/functions/binary_file.rb
- spec/unit/functions/binary_file_spec.rb
Ensure that the given file name is included in the message.
> (PUP-6821) Fix missing file in file not found message from binary_file()

- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/evaluator/closure.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- lib/puppet/resource/type.rb
- spec/unit/functions/new_spec.rb
- spec/unit/pops/evaluator/access_ops_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
Before this commit, the `PStringType` had two attributes. A `size_type` and
a `values` array. An inferred String would hence result in a String type
with two complex objects and all checkes would then take both objects into
account.
This commit simplifies the `PStringType` so that it only has one attribute.
The attribute can be either a size_type or a string value.
Since this means that a String can hold max one string value, the common
type of two different strings is now changed to instead be an Enum. I.e.
the inferred element type of the array ['a', 'b']. The logic for computing
assignability and commonality between Enum and String has been improved.
> (PUP-6921) Improve separation of concern between String and Enum types

- lib/puppet/pops/lookup.rb
- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/lookup_spec.rb
This PR changes the Pcore type used to validate data found by a lookup
so that it may contain any type except Runtime. The key and value types are
registered as aliases `Puppet::LookupKey` and `Puppet::LookupValue`. The
latter alias is self-recursive in that keys and values found in hashes and
arrays must conform to their respective type, even if nested.
> (PUP-6926) Enable lookup of rich data values

- lib/puppet/pops/parser/slurp_support.rb
- spec/unit/pops/parser/lexer2_spec.rb
Prior to this commit, the lexer would not detect that an escaped unicode
escape such as \\uFFFF was preceded by an escape and instead treat it as
a literal `\` followed by the unicode codepoint \uFFFF. This commit alters
the regexp used so that it detects a preceding escape.
> (PUP-6882) Fix problem with escaped unicode escapes

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
This commit updates the systemd provider to recognize services
with the 'indirect' enabled state. These units are disabled,
and thus when querying whether they are enabled we now return
false.
> (PUP-6759) Consider indirect systemd units to be disabled

- lib/puppet/defaults.rb
- man/man5/puppet.conf.5
Just as we ignore SVN, CVS, and Git artifacts while pluginsyncing,
we should also ignore those of Mercurial. This commit adds files
with the `.hg` extension to the list of extensions in the
`pluginsignore` option.
> (PUP-6844) Ignore Mercurial artifacts when downloading plugins

- lib/puppet/file_system.rb
- lib/puppet/indirector/file_bucket_file/file.rb
- lib/puppet/settings/config_file.rb
- lib/puppet/settings/directory_setting.rb
- lib/puppet/settings/file_or_directory_setting.rb
- lib/puppet/settings/file_setting.rb
- lib/puppet/util.rb
- lib/puppet/util/plist.rb
- spec/unit/file_system_spec.rb
Supercedes #5354 
Channeling @MosesMendoza from prior PR:
This PR builds on / supersedes #4898 from @Iristyle 
[PUP-6188](tickets.puppetlabs.com/browse/PUP-6188) tracks an effort to ensure Puppet's various file system interactions are specifying utf-8 encoding where possible/applicable, possibly in `Puppet::FileSystem.open` and `Puppet::FileSystem.exclusive_open`, but notes the problematic situation resulting from the reordering of method arguments from `Puppet::FileSystem::FileImpl#open` to [`::File.open`](https://ruby-doc.org/core-2.3.1/File.html#method-c-open):
> - Rubys `perm` in our call is renamed as `mode`, and is moved from position 2 to position 1
> - Rubys `mode` in our call is renamed as `options`, and is moved from position 1 to position 2
> - We don't support the passing in …
> (PUP-6188) Puppet::FileSystem and explicit Encoding changes

- lib/puppet/defaults.rb
- lib/puppet/forge/repository.rb
- lib/puppet/network/http/connection.rb
- spec/unit/network/http/connection_spec.rb
Previously, puppet did not specify an HTTP User-Agent string, so ruby
would send the default "Ruby". This made it difficult to debug and
interpret server-side logs when different versions of puppet agents
connect.
This commit adds a puppet setting `http_user_agent` which includes the
puppet and ruby versions. The default value is of the form:
```
Puppet/4.7.0 Ruby/2.1.8-p440 (x86_64-darwin15.0)
```
The string is exposed as a setting for cases where puppet is being used
as a library, and the enclosing application may need to override that.
Puppet's HTTP connection code will send the User-Agent header with the
above value for all requests. The value is taken from the Puppet Module
Tool code. However, the strings are not exactly the same, because the
PMT prefixes the string with additional …
> (PUP-1476) Include puppet and ruby versions in User-Agent

- lib/puppet/defaults.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/integration/defaults_spec.rb
- spec/unit/defaults_spec.rb
This adds a deprecation warning if a data binding terminus other than 'hiera' or 'none' are assigned.
> (PUP-6576) Deprecate data_binding_terminus

- lib/puppet/pops/types/p_type_set_type.rb
- lib/puppet/pops/types/type_formatter.rb
- spec/unit/pops/types/p_type_set_type_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
This commit fixes two minor problems in the TypeFormatter.
1. A String, when output in debug mode, didn't output a contained string
value correctly.
2. A qualified type name resolved using a TypeSet reference would raise
an exception due to a bogus method call in TypeSet#name_for method.
> (maint) Fix two minor glitches in the TypeFormatter

- lib/puppet/transaction/additional_resource_generator.rb
- spec/integration/transaction_spec.rb
- spec/unit/transaction/additional_resource_generator_spec.rb
When generating resources with
Puppet::Transaction::AdditionalResourceGenerator#eval_generate, we create a completed_ whit resource to "contain" the generated resource such that when its dependencies are satisifed, it effectively signals that the generating resource evaluation has completed. However, prior to this commit, the applicable tags of the parent resource were not propagated to the whit resource (they are propogated to all child resources later in Puppet::Transaction::AdditionalResourceGenerator#add_resource). Because the whit does not have any of the tags of the parent resource, if puppet is filtering resources by tags, resources in a subscribing relationship with the parent generating resources would not be refreshed, even when the generating resource issued a refresh event.
An …
> (PUP-6741) Correctly trigger tagged resources dependent on dynamically generated resources

- acceptance/Gemfile
- acceptance/config/aio/options.rb
- acceptance/setup/aio/pre-suite/015_PackageHostsPresets.rb
- acceptance/setup/aio/pre-suite/045_EnsureMasterStarted.rb
- acceptance/setup/aio/pre-suite/045_EnsureMasterStartedOnPassenger.rb
Bump beaker to 3.5.x, which added support for reloading puppetserver
using HUP.
Beaker will fail to reload the service if it isn't already running and
it will fall back to bouncing the service using puppet's resource
service ensure=stopped and ensure=running commands. To ensure reloading
always works, we now start puppetserver in the 045_EnsureMasterStarted
pre-suite step. We don't test against passenger or webrick, so there's
no point in making the step conditional on the server type.
Prior to commit 59cce2311, Beaker's `with_puppet_running_on` method would
start puppetserver twice. Once in the beginning before the test, and
once after. Each start takes ~30 seconds per test, and that caused an
overall 1+ hour increase in test times as compared to when we tested
against passenger …
> (PUP-6967) Reload puppetserver using HUP

- install.rb
- lib/puppet/provider/package/pkg.rb
- lib/puppet/provider/service/smf.rb
- lib/puppet/provider/user/user_role_add.rb
- spec/unit/provider/package/pkg_spec.rb
- spec/unit/provider/service/smf_spec.rb
- spec/unit/provider/user/useradd_spec.rb
(PUP-6792) SMF should recursively enable services
SMF supports enabling a service and all services which that service
requires. With this patch recursive starts are the default behavior.
(PUP-6793) pkg provider should be default for Solaris 12
Puppet needs to use the pkg provider to manage packages on Solaris 12
(PUP-6795) Solaris does not support gzipped man pages
Solaris does not support gzipped man pages. Skip gzipping when
installing on Solaris.
(PUP-6796) Support setting/checking shell in user_role_add
Puppet should allow a users shell to be set in a Solaris role
(PUP-6797) service should check for smf service first
(PUP-6860) puppet on solaris 11 should support exists? for services
Attempts to manage non-existent services resulted in uninformative
errors. With this patch …
> PUP-6792,6793,6795-6797 Solaris Updates

- CONTRIBUTING.md
This commit outlines the revert policy for code changes that result
in test pipeline failures. The purpose of this is to establish a
clear protocol for when a revert should take place and how it should
be communicated to the original contributor.
> (PUP-6840) Add revert policy

- lib/puppet/pops/lookup/configured_data_provider.rb
- lib/puppet/pops/lookup/data_hash_function_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/interpolation.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/unit/functions/lookup_spec.rb
When a hiera configuration contains values with interpolated expressions
that reference scope variables, there is a potential that such values may
change. A variable can be unset on first lookup and introduced later on, or
it may be a global variable shadowed by a local variable (or vice versa).
This commit ensures that such changes are detected and that the
configuration is reloaded.
> (PUP-6973) Make hiera configuration sensitive to scope changes

- lib/puppet/pops/lookup/interpolation.rb
- spec/unit/pops/lookup/interpolation_spec.rb
Interpolation of an `nil` should result in an empty string but `false`
must be interpolated as the string "false". This commit ensures that this
distinction is honored.
> (PUP-6974) Differentiate between nil and false when interpolating data

- Rakefile
TRAVIS_COMMIT_RANGE uses triple dots, which includes commits that are in
the base branch that are not in the PR. For example, if a commit is
pushed to master with an incorrect summary, then every PR created before
that commit will include the unrelated commit, causing the PR to fail
the summary check.
As suggested in https://github.com/travis-ci/travis-ci/issues/4596#issuecomment-139811122,
replace triple dots with double dots.
> (PUP-6850) Exclude commits unrelated to a PR

- spec/integration/util/execution_spec.rb
Previously the execution_spec.rb test was using LF line endings during the UTF8
test which worked on US English systems.  However when running on a Japanese
version of Windows, this test was failing incorrectly.  This commit forces the
line endings to Windows style CRLF so that the batch file will execute correctly.
> (maint) Use Windows line endings for batch file in integration test

- acceptance/tests/lookup/v4_hieradata_with_v5_configs.rb
* add a test for environment hiera.yaml v5 with yaml data files in ./data
* later we can uncomment the portion for using a global hiera v5 config file
[skip ci]
> (PUP-6928) acceptance: hiera yaml v5 with existing data files

- acceptance/config/git/options.rb
- acceptance/setup/git/pre-suite/000_EnvSetup.rb
- acceptance/setup/git/pre-suite/010_TestSetup.rb
- acceptance/tests/direct_puppet/static_catalog_env_control.rb
- acceptance/tests/ensure_version_file.rb
- acceptance/tests/language/exported_resources.rb
- acceptance/tests/language/pcore_resource_types_should_have_precedence_over_ruby.rb
- acceptance/tests/parser_functions/no_exception_in_reduce_with_bignum.rb
- acceptance/tests/reports/finalized_on_cycle.rb
- acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
Previously, `git` style acceptance cloned each repo specified in `config/git/options.rb`. If the repo contained `install.rb` at the root, then acceptance would call that file to install its lib directory and binstubs into system ruby.
However, this approach doesn't work for arbitrary dependencies, and `git` acceptance was broken when we added a hard dependency on `semantic_puppet`.
This commit installs bundler into system ruby, generates a Gemfile for the `puppet` gem at the ref specified by `ENV['SHA']`. It uses bundler to install a standalone bundle into system ruby and creates binstubs, e.g. `/usr/bin/puppet`. This eliminates the duplicate dependency information, and ensures `git` acceptance works as new dependencies are added.
A few tests need to be skipped for `git` because they …
> (PUP-6989) Use bundler to install dependencies for git acceptance

- lib/puppet/pops/lookup/data_hash_function_provider.rb
- spec/unit/functions/lookup_spec.rb
The 'verbatim' data provider option introduced unwanted complexity and is
therefore removed in this commit.
> (PUP-7004) Remove 'verbatim' data provider option

- lib/hiera/puppet_function.rb
- lib/puppet/functions/hiera_array.rb
- lib/puppet/functions/hiera_include.rb
- lib/puppet/pops/lookup.rb
- lib/puppet/pops/lookup/data_hash_function_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/invocation.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/fixtures/unit/functions/lookup/data/common.yaml
- spec/unit/functions/hiera_spec.rb
- spec/unit/functions/lookup_spec.rb
This commit changes the hiera_xxx functions so that they use the new lookup
framework instead of being hard-wired directly to the Hiera v3 code.
The functions will only use the global layer unless a hiera.yaml version 5
is present in the environment.
A special `data_hash` function dispatcher was designed to ensure that any
"override paths" that the hiera_xxx functions may provide are inserted
correctly into the hierarchy.
> (PUP-6981) Reroute hiera_xxx functions to new lookup framework

- lib/hiera/puppet_function.rb
- lib/puppet/parser/functions/hiera.rb
- lib/puppet/parser/functions/hiera_array.rb
- lib/puppet/parser/functions/hiera_hash.rb
- lib/puppet/parser/functions/hiera_include.rb
- spec/unit/functions/hiera_spec.rb
This commit adds a deprecation text to the documentation of the four
functions `hiera`, `hiera_array`, `hiera_hash`, and `hiera_include` that
informs the user that `lookup`should be used instead. Code is also added to
ensure that deprecation messages are logged when the functions are used.
The deprecation logging can be silenced by setting --strict setting to off.
> (PUP-6538) Deprecate hiera_xxx functions

- lib/puppet/pops/lookup/data_hash_function_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/lookup_spec.rb
This commit corrects two places where arguments was sent in the wrong order
to the hiera.yaml path resolver and adds unit tests that asserts that paths in
Hiera v3 are interpolated correctly.
> (PUP-7020) Fix bug preventing path interpolation in hiera.yaml version 3

- spec/unit/file_system_spec.rb
Minor correction of the determination of expected default mode for regular file
via umask in file_system_spec.rb to use bitwise operations - this will be more
familiar (and feels more correct) than previous represention.
> (maint) default mode via bitwise ops in file_system_spec

- install.rb
Prior to this commit, the win32/dir gem was not being required properly
in all places that install.rb attempts to use its constants. This commit
moves the require to a higher-level location, which allows all the supplied
defaults to resolve correctly.
> (maint) Fix windows default directories in install.rb

- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/recursion_guard.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/hiera_spec.rb
Lookup introduces a new recursive type `Puppet::LookupValue` which defines
all values that are legal for lookup (in essence, everything that can be
stored in a catalog). The type is recursive since hashes and arrays can
values of the same type.
The acceptance test for hiera_hash, uses a hash with two values that are
exactly the same (uid and gid are both 500). This revealed a bug in the
guard used for trapping endless recursion in recursive types where values
that are pushed didn't get popped after the branch where the recursiveness
was tested. This commit fixes that bug.
> (PUP-6981) Fix issue with recursive guard detection when validating types

- acceptance/tests/resource/user/utf8_user_comments.rb
- lib/puppet/feature/base.rb
- lib/puppet/provider/nameservice.rb
- lib/puppet/type/user.rb
- lib/puppet/util/windows/adsi.rb
- spec/unit/provider/nameservice_spec.rb
- spec/unit/type/user_spec.rb
The nameservice provider leverages the ruby Etc::getpwnam method to return
information regarding users (subclasses include useradd and pw). In Ruby <
2.1.0, this method always returns values as strings in binary encoding. In Ruby
2.1.0 and later, this method returns strings in either the current locale
encoding (Encoding::default_external) OR binary encoding if the string returned
does not encode correctly in the current locale encoding (how they determine
this is opaque, at best, and not exposed publicly).
Prior to this commit, the :comment property of the user type would set the
external encoding of the supplied value for :comment to binary if running ruby
< 2.1.0. This effectively handles the case of incompatible encodings with ruby
< 2.1.0. However, for ruby >= 2.1.0, this will always …
> (PUP-6777) (PUP-7031) address utf-8 related comment bugs in user providers

- lib/puppet/provider/package/dnf.rb
The dnf provider must be updated to add each new Fedora release.
This is caused by the defaultfor method in puppet which only accepts
hashes as arguments.  See https://tickets.puppetlabs.com/browse/PUP-6452
for more details.
> (PUP-7029) dnf provider does not support Fedora 25

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/hiera_spec.rb
Before this commit, the class Hiera wasn't loaded properly and its logger
was not initialized. Consequently, any custom backend that attempted to use
the logger would run into an error similar to: "Unable to instantiate
backend '<backend name>': undefined method 'debug' for nil:NilClass".
This commit adds the proper require for the class and ensures that the
logger is initialized.
> (PUP-6981) Ensure that legacy Hiera logger is initialized

- appveyor.yml
- spec/integration/test/test_helper_spec.rb
- spec/unit/util_spec.rb
Supercedes #5437 
See that PR for discussion about increase in matrix time, etc.  This turns on Japanese Windows spec testing on AppVeyor *and* fixes resulting test failures.
This just has some modifications to the final commit from prior PR to reduce test complication.
> (PUP-7015) Enable / Fix Ruby specs for Japanese Windows

- acceptance/tests/resource/user/utf8_user_comments.rb
Arista EOS has known issues with the user provider (ARISTA-42, PUP-7049)
causing it to fail the tests associated with PUP-6777. Effectively,  the
`getpwnam` function on Arista will return data for a non-existent user. Ruby
`Etc` module relies on this to return info on users, and Puppet relies on Ruby
`Etc` module in the useradd provider. This commit confines this test to not run
on EOS hosts.
> (PUP-6777) don't run utf-8 user tests on arista

- acceptance/tests/resource/user/utf8_user_comments.rb
By default AIX usernames are 8 chars. To ensure we pass in the default
configuration, shorten the username length in test utf8_user_comment to 8
characters.
> (PUP-7053) shorten username in utf-8 test for aix

- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/fixtures/unit/data_providers/environments/hiera_modules/modules/two/data/common.yaml
- spec/unit/functions/lookup_spec.rb
Before this commit, in order for a key to have lookup options specified,
the options had to be keyed with that same exact key. Now, such options can
also be defined for keys that matches a specific pattern. This is achieved
by treating all keys that start with a '^' as regular expression patterns.
A key that matches such a pattern is considered to have the options below
that key.
The commit also adds a check that key or pattern under `lookup_options`
in a module only can identify keys that belong to that module. Keys must
start with "<module_name>::" and patterns must start with "^" followed
by "<module_name>::".
> (PUP-6982) Allow keys to be specified using patterns in lookup_options

- lib/puppet/pops/parser/slurp_support.rb
- spec/unit/pops/parser/lexer2_spec.rb
The lexer was only capable of recognizing the first of several adjacent
unicode characters. This commit fixes that problem.
> (PUP-7030) Fix bug causing lexer hick-up on two adjacent unicode chars

- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/type_formatter.rb
- spec/unit/pops/types/p_object_type_spec.rb
This commit adds a to_s method that will the string that corresponds to
the calling the #new function on the type with an initialization hash.
> (PUP-7055) Add proper to_s method to class generated from pcore Object

- lib/puppet/pops/loaders.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/serialization/abstract_reader.rb
- lib/puppet/pops/serialization/abstract_writer.rb
- lib/puppet/pops/serialization/deserializer.rb
- lib/puppet/pops/serialization/extension.rb
- lib/puppet/pops/serialization/object.rb
- lib/puppet/pops/serialization/rgen.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/resource.rb
- lib/puppet/resource/catalog.rb
- spec/integration/application/apply_spec.rb
- spec/unit/resource/catalog_spec.rb
Ensure that when an instance of an ObjectType is serialized, that the type
itself is serialized along with it. Also ensure that when the instance and
its type is deserialized, that the type is added to the loader used during
deserialization.
> (PUP-7054) Serialize ObjectType's along with instances of the type

- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/types_spec.rb
This commit adds the method `create` to the `PAnyType` to make it easy to
create instances of a type from Ruby. It also adds the method `from_hash`
to the PObjectType which enables instance creation using an initialization
hash.
> (PUP-7058) Add Ruby API to #new function

- lib/hiera/puppet_function.rb
- lib/puppet/pops/lookup/global_data_provider.rb
- lib/puppet/pops/lookup/invocation.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/pops/lookup/lookup_spec.rb
This commit adds the ability to create a separate instances of configured
lookup layers. A new instance is created by subclassing `LookupAdapter`
and then pass that class to the `Invocation` constructor. By doing so, a
new adapter will be created and adapted to the compiler. All configured
providers are then properties of the new adapter.
The `LookupAdapter` can be configured to work in a "global layer only"
mode. The global configuration (normally determined by the Puppet setting
"hiera_config" can be overridden.
> (PUP-7059) Improve Lookup Ruby API to handle multiple instances

- acceptance/tests/modules/install/basic_install.rb
- acceptance/tests/modules/install/with_version.rb
This commit removed the confine against AIX for PMT install tests that
were previously skipped due to a failure to override DNS resolution
for the forge on AIX.
> (PUP-5501) Unblock PMT install tests on AIX

- spec/integration/util/windows/registry_spec.rb
- Current registry specs share global state in the same location within
the registry.  This can cause specs run in parallel on the same
machine to intermittently fail.
Move the subkey in use to a distinct location for each set of tests
so that tests do not share global state.
> (PUP-7064) Isolate Windows registry specs per run

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that a relative path in a Hiera version 3 config is
resolved using the current working directory.
> (PUP-7068) Resolve Hiera version 3 datadir against current working dir

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that an empty hiera.yaml is recognized as a default
Hiera version 3 config. This is needed in order to be backward compatible
with Hiera 3.
> (PUP-7067) Make hiera work with empty config file

- lib/puppet/util/network_device/config.rb
Prior to this update, any trailing whitespace left in a device
configuration file will cause `puppet device` to fail with
a cryptic message because it is using the string to construct
the path for an require statement.  Since require statements
should never have spaces in them, it makes more sense to have the
regex only accept the non-whitespace characters it finds in the
confiugration file.
> (PUP-6847) Omit whitespace from provider keyword in network_device

- Gemfile
- lib/puppet/feature/hocon.rb
- lib/puppet/functions/hocon_data.rb
- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit adds a 'hocon' feature to Puppet which gets enabled when the
hocon library is present. It also adds a data_set function named
`hocon_data` capable of producing a Hash from a file in hocon format. The
function can only execute if the 'hocon' feature is enabled.
The Hiera version 3 and version 4 configs are changed so that when the
'hocon' feature is enabled, the data provider will use the added function
rather than attempting to use a custom backend or a presumed data binding.
> (PUP-6476) Add Hocon data_set function for Hiera version 5

- lib/puppet/pops/lookup/explainer.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/fixtures/unit/application/environments/production/data/common.yaml
- spec/unit/application/lookup_spec.rb
The debug explainer that was added to an invocation and that emitted
debug info on each resolution of an interpolation, was incorrectly
removed before the interpolation call was finished. This resulted in
an attempt to do a pop on an attribute that no longer existed.
This commit ensures that the attribute is treated as read-only and
instead moves the ability to do normal explaining to the debug by having
it delegate to it's wrapped explainer.
> (PUP-7061) Fix problem with unbalanced pop of debug explainer

- lib/puppet/pops/issues.rb
- lib/puppet/pops/validation/checker4_0.rb
- lib/puppet/pops/validation/validator_factory_4_0.rb
- spec/unit/pops/validator/validator_spec.rb
This adds validation of duplicate literal default entries in case and selector expressions.
> (PUP-978) Multiple literal default in case and selector

- lib/puppet/application/face_base.rb
- lib/puppet/face/file.rb
- lib/puppet/face/help/face.erb
- lib/puppet/interface.rb
- spec/unit/application/face_base_spec.rb
- spec/unit/face/file_spec.rb
- spec/unit/face/help_spec.rb
- spec/unit/interface_spec.rb
PUP-869 tracks the deprecation of the `file` face - one of many upcoming deprecations of existing faces in the puppet codebase. After initial review, issuing a simple deprecation warning in a face proved more complex than one might hope - especially in testing that face is actually deprecated when a face is actually used.  I.e., we could just put a deprecation warning in the initial face definition block, but this block is only evaluated once, at load time - a deprecation there might be fine from a ux perspective but is executed via an `instance_eval` and difficult to test. This commit adds a simple `deprecated` attribute to the Puppet::Interface class, and ensures that if a face is deprecated, we issue an appropriate deprecation warning when an action is sent to that face.
The (perhaps …
> (PUP-869) deprecate file face and add easier face deprecations

- api/schemas/error.json
- lib/puppet/network/http/error.rb
- lib/puppet/network/http/handler.rb
- spec/unit/network/http/error_spec.rb
- spec/unit/network/http/handler_spec.rb
In 7a765b7 and 5ae2d155 we unintentionally introduced a backwards-incompatible change, removing the "stacktrace" array from the HTTP Error object schema. We also added the stack trace information to the Puppet error log. These commits were originally released in Puppet 4.8.0. There is a request to backport the intent of these fixes, that is to remove the stack trace information from the HTTP response, to the LTS-1.7 branch. This PR first cherry-picks back the original commits introduced in the 4.8.0 series, 7a765b7 and 5ae2d155. Since we have determined some of this change was backwards-incompatible, this PR includes partial reverts of these commits - returning the stack trace as formerly constituted, except that rather than return the actual stack trace content, we return a deprecation …
> (PUP-7066) return and deprecate stack trace in http server error response

- lib/puppet/functions/yaml_data.rb
- lib/puppet/pops/lookup/configured_data_provider.rb
- lib/puppet/resource.rb
- spec/unit/pops/lookup/interpolation_spec.rb
The code base contained some references to the old Puppet::DataProvider
module (experimental 4.x lookup implementation). This commit removes
them.
> (PUP-7083) Remove obsolete references to old DataProvider module

- lib/puppet/interface.rb
- lib/puppet/module.rb
- lib/semver.rb
- spec/unit/semver_spec.rb
This commit ensures that a deprecation warning is logged when an instance
of Puppet::SemVer is created unless `Puppet[:strict] == :off`
> (PUP-6240) Deprecate use of Puppet::SemVer

- lib/puppet/interface.rb
- lib/puppet/interface/face_collection.rb
- lib/puppet/module.rb
- lib/puppet/module_tool/applications/application.rb
- lib/puppet/module_tool/applications/installer.rb
- lib/puppet/module_tool/applications/uninstaller.rb
- lib/puppet/module_tool/metadata.rb
- lib/puppet/module_tool/shared_behaviors.rb
- spec/unit/interface/face_collection_spec.rb
- spec/unit/puppet_spec.rb
This commit switches the PMT from using the old Puppet::SemVer to instead
use SemanticPuppet::Version and SemanticPuppet::VersionRange.
The commit also changes one occurance in Puppet::Interface::FaceCollection
> (PUP-4283) Update Puppet Module Tool to use SemanticPuppet::Version

- lib/puppet/face/ca.rb
- lib/puppet/face/certificate_request.rb
- lib/puppet/face/certificate_revocation_list.rb
- spec/unit/face/ca_spec.rb
- spec/unit/face/certificate_request_spec.rb
- spec/unit/face/certificate_revocation_list_spec.rb
This PR deprecates the certificate_request, certificate_revocation_list, and ca faces.
Original context from @nfagerlund on redmine #15860:
The real puppet cert mgmt command is “puppet cert.” It’s one of the classic
applications. But for some reason, there are a TON of faces related to certs
hanging around! I’m seeing:
- ca
- ~certificate~ - _note it was decided to keep certificate in PUP-868_
- certificate_request
- certificate_revocation_list
- None of these act as a replacement for puppet cert.  By using a patchwork of
them, you might be able to get all of the functionality of puppet cert, but
it’s not clear. This is a result of us simply exposing these indirector
endpoints on the command line without spending any time thinking about a
usable API for interacting with them.
- Because …
> (PUP-868) deprecate misc cert-related faces

- lib/puppet/face/key.rb
- spec/unit/face/key_spec.rb
The key face is (self-described) not intended to be used - per PUP-871 it
should be removed.
From key.rb:
"it should not be necessary to use this subcommand directly"
> (PUP-871) deprecate key face

- lib/puppet/face/status.rb
- spec/unit/face/status_spec.rb
Deprecate the `puppet status` face.
Context from PUP-873/@zaphod42, suggesting this face is unusable:
"The status face could possibly be useful, but the usability of it is so
atrocious we are better removing it and revisiting it later."
Additional detail on the poor UX and broken-ness of this face can be found in
PUP-873.
> (PUP-873) deprecate status face

- lib/puppet/pops/issues.rb
- lib/puppet/pops/validation/validator_factory_4_0.rb
- spec/unit/pops/validator/validator_spec.rb
Before this, a DUPLICATE_KEY was under the control of the `strict`
setting. This commit changes that to be a hard error.
> (PUP-6930) Make DUPLICATE_DEFAULT an error

- benchmarks/hiera_env_lookup/benchmarker.rb
- benchmarks/hiera_env_lookup/description
- benchmarks/hiera_env_lookup/puppet.conf.erb
- benchmarks/hiera_function/benchmarker.rb
- benchmarks/hiera_function/description
- benchmarks/hiera_function/puppet.conf.erb
- benchmarks/hiera_global_lookup/benchmarker.rb
- benchmarks/hiera_global_lookup/description
- benchmarks/hiera_global_lookup/puppet.conf.erb
- benchmarks/legacy_hiera_lookup/benchmarker.rb
- benchmarks/legacy_hiera_lookup/description
This commit adds four different benchmarks
legacy_hiera_lookup:
Performs repeated lookups using the legacy Hiera version 3 class directly
hiera_global_lookup:
Performs repeated lookups in the global layer using the lookup API
hiera_env_lookup:
Performs repeated lookups in the environment layer using the lookup API
hiera_function:
Performs repeated lookups in the global layer using the `hiera` function
> (PUP-7086) Add benchmarks for lookup and data-binding

- lib/puppet/pops/lookup.rb
- lib/puppet/pops/merge_strategy.rb
This commit optimizes the MergeStrategy so that it uses fixed instances
when no options are given (which is true in 99.9% of the cases). It also
changes how the value is validated with respect to type so that it isn't
validated unless a type is given (basic Puppet::LookupValue validation
still takes place in the provider).
> (PUP-7087) Optimize lookup type checking and caching of merge strategy

- acceptance/tests/language/PUP-2630-server_set_facts.rb
- lib/puppet/application/apply.rb
- lib/puppet/defaults.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- spec/integration/application/apply_spec.rb
- spec/integration/parser/compiler_spec.rb
This changes trusted_server_facts setting such that it is always as if
it was set to true. The setting itself is deprecated (rather than
removed) to not cause immediate failure, but the settings has no effect.
The default of the setting has changed to true. The acceptance test is
updated to check that it is true, and the test of the false branch is
dropped.
> (PUP-6112) Make trusted_server_facts always be true

- lib/hiera/scope.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/lookup/function_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/interpolation.rb
- lib/puppet/pops/lookup/invocation.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- lib/puppet/pops/lookup/sub_lookup.rb
- spec/unit/hiera/scope_spec.rb
This commit contains a series of performance tweeks that were motivated
by findings when using a profiler. The optimizations makes the test
`benchmark:hiera_global_lookup` execute ~20% faster.
1. The special `Hiera::Scope` was improved to use frozen, predefined
arrays when checking if a key was one of the caller keys.
2. The `Puppet::Parser::Scope` was improved to use a predefined empty
`Hash` rather than creating a new dynamic hash on every call, and
to only check using `#include?` when a found value was `nil`
3. The FunctionProvider has a hash of contexts instead of a DataBinding
with a similar hash. This is OK since the provider itself is bound by
an adapter.
4. A check for stable interpolations of the configuration was improved.
Instead of using `#each_pair.all?` on a `Hash` it simply …
> (PUP-7087) Improve lookup performance

- lib/puppet/node/facts.rb
This commit is part of the Puppet 5.0 code removal effort.
> (PUP-3670) Remove Facts#strip_internal method

- lib/puppet/defaults.rb
- man/man5/puppet.conf.5
This commit is part of the Puppet 5.0 code removal effort.
> (PUP-6219) Remove deprecated req_bits setting

- lib/puppet/feature/external_facts.rb
- spec/unit/configurer/plugin_handler_spec.rb
- spec/unit/indirector/facts/facter_spec.rb
The external_facts feature is deprecated, since Puppet now relies on
a version of Facter with that support. This commit is part of the Puppet
5.0 code removal effort.
> (PUP-6481) Remove external_facts feature

- lib/puppet.rb
- spec/unit/puppet_spec.rb
This commit adds a deprecation warning for users running puppet under a version
older than 2.1.0. This is accomplished by adding a new constant,
Puppet::OLDEST_RECOMMENDED_RUBY_VERSION, which we later test for in issuing a
deprecation warning.
> (PUP-7038) deprecate ruby 2.0

- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/merge_strategy.rb
- spec/unit/functions/lookup_spec.rb
This commit adds the `UnconstrainedDeepMergeStrategy` to the list of
merge strategies supported by the lookup framework. This strategy is
used for deep merge options defined in a hiera.conf version 3 but not
otherwise accessible from Puppet.
> (PUP-7088) Let Hiera v3 honor deep merge options not supported by Puppet

- acceptance/tests/language/objects_in_catalog.rb
* errant code left in this test in previous commit
* allow beaker to properly apply the manifest
[skip ci]
> (PUP-7081) acceptance: fix objects_in_catalog

- lib/puppet/face/help.rb
- spec/unit/face/help_spec.rb
Previously in commit 7fefceae40d5ac a deprecation message was added to the face
and the help text for a face.  However when running `puppet help` it was not
obvious which faces were deprecated or not.
This commit adds the text `(Deprecated)` to the face summary when running
`puppet help`.
> (PUP-869) Add face deprecation message to help summaries

- Rakefile
- ext/project_data.yaml
- lib/puppet.rb
- locales/puppet.pot
- tasks/i18n.rake
This PR contains two commits, one of which ensures that the `locales` directory is properly packaged with the gem, and a second which removes the build-time dependency on the `gettext-setup` gem.
> (PUP-6958) Fix gem packaging to properly include i18n files

- lib/puppet/pops/lookup/context.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/lookup_spec.rb
This commit fixes a typo in the `LookupKeyFunctionProvider` that prevented it from being used together with a location.
The PR also contains a maintenance commit to allow that `undef` is used as a key in the lookup context cache (using `undef` is useful when testing if the cache is initialized, see added test).
> (PUP-7099) Fix typo in LookupKeyFunctionProvider

- acceptance/lib/puppet/acceptance/environment_utils.rb
- acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb
- lib/puppet/indirector/request.rb
- spec/unit/indirector/request_spec.rb
This PR supersedes #5176 
From @Iristyle / #5176
> By not preserving the original Path encoding of UTF-8 used for
incoming requests to the indirector, future string comparisons (using
Regex for instance) are invalid and will cause exceptions.
> This problem is trivially reproducible with a manifest like:
> file { "/tmp/test":
> ensure => file,
> source => 'puppet://modules/utf_8/静的',
> }
> The key of the request previously was "utf_8/\xE9\x9D\x99\xE7\x9A\x84"
> instead of the appropriate "utf_8/静的"
This PR includes the original commit from #5176 as well as an acceptance test and fix for the issue.
> (PUP-6448) Indirector URIs should remain UTF-8

- lib/puppet/pops/serialization/abstract_reader.rb
- lib/puppet/pops/serialization/abstract_writer.rb
- lib/puppet/pops/serialization/deserializer.rb
- lib/puppet/pops/serialization/extension.rb
- lib/puppet/pops/serialization/object.rb
- lib/puppet/pops/serialization/rgen.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/p_timespan_type.rb
- lib/puppet/pops/types/p_timestamp_type.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/serialization/packer_spec.rb
The current implementation of Sensitive serialization was broken. It assumed
that the same packer was used for both normal data and extension data and
made attempts to write rich data directly into the extension buffer. While
fine for JSON, that approach doesn't work at all for MsgPack.
This commit changes the serialzation so that a SensitiveStart marker is
written using an extension point and then the actual wrapped object is
written as a normal object.
> (PUP-7104) Fix for serialization of Sensitive with rich data.

- lib/puppet/ssl/certificate_authority.rb
- spec/unit/ssl/certificate_authority_spec.rb
This PR deprecates methods in `Puppet::SSL::CertificateAuthority` that were used by the PE License library (but no longer are). `#x509_store` (and its callers) in particular is problematic because it can cache the x509_store object once and never refresh it, even if it is no longer valid.
Commit outline:
> This commit deprecates Puppet::SSL::CertificateAuthority#list_certificates, as
> it is no longer used by anything. The PE License check code that originally
> used this been migrated to querying PuppetDB.
> To avoid superflous warnings emanating from use of
> Puppet::SSL::CertificateAuthority#list, that method is updated to directly do
> an indirector search instead of indirectly through #list_certificates. This is
> what it originally did, before #list_certificates was added, and is
> …
> (PUP-3534) Deprecate caching certificate authority verify methods

- lib/puppet/module.rb
- spec/unit/module_spec.rb
- spec/unit/pops/loaders/loaders_spec.rb
This commit ensures that the number of system calls needed to determine that
a metadata.json file exists and to load it, is kept to a minimum. The check
to see if the file exists was removed. Instead, an attempt is made to read
the file directly and the ENOENT error that might be the result is rescued.
The file is also read and parsed only once.
> (PUP-5027) Prevent that metadata.json is parsed multiple times

- Gemfile
- lib/puppet/feature/hiera_eyaml.rb
- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/lookup_spec.rb
This PR adds a Hiera version 5 style lookup_key function that relies on the functionality provided by the [hiera_eyaml](/TomPoulton/hiera-eyaml) gem. The function will refuse to execute unless this gem is installed (controlled by the added Puppet `hiera_eyaml` feature).
The lookup_key function will also be used if an eyaml backend is defined in a Hiera version 3 configuration.
> (PUP-7100) Add Hiera version 5 lookup_key function for eyaml

- .gemspec
- .rubocop.yml
- Gemfile
- ext/project_data.yaml
- lib/semantic_puppet.rb
- lib/semantic_puppet/dependency.rb
- lib/semantic_puppet/dependency/graph.rb
- lib/semantic_puppet/dependency/graph_node.rb
- lib/semantic_puppet/dependency/module_release.rb
- lib/semantic_puppet/dependency/source.rb
- lib/semantic_puppet/dependency/unsatisfiable_graph.rb
- lib/semantic_puppet/gem_version.rb
- lib/semantic_puppet/version.rb
- lib/semantic_puppet/version_range.rb
- As part of PUP-4742 the dependency on semantic_puppet was moved to
a gem.  The sequence of events leading up to its conclusion is
rather thorny, but ultimately code landed in
c111fb76b948d547fda7afa901802ff2e8b5a623
- Because puppet-server was not also shipping the semantic_puppet gem
this necessitated a strict conflict in the puppet-agent package
on puppet-server < 2.7.2 and pe-puppet-server < 2017.0.1.3
This has had quite a bit of fallout, including unintended upgrades
of the puppet-server package, which is extermely undesirable in a
production environment.
- Until Puppet 5 is released, which will allow for more latitude of
breaking changes and dependency requirements, it has been decided
that semantic_puppet should be temporarily re-vendored into the
Puppet repository.  Then there is …
> (PUP-7114) Re-vendor semantic_puppet gem

- lib/puppet/parser/compiler.rb
- lib/puppet/resource/type_collection.rb
- spec/unit/resource/type_collection_spec.rb
Before this, if a class was defined more than once their bodies would be merged. The output of a warning or error was under the control of the --strict flag.
Now, this is always an error except for the top scope class named '' (a.k.a 'main').
> (PUP-5954) Make class merge an error

- spec/unit/functions/lookup_spec.rb
- Add a test demonstrating the behavior of the lookup function when
Hocon is specified as a backend, but the hocon library is not
present.
This demonstrates what will happen if a newer agent is running
on puppet-server < 2.7.0, which does not include the hocon gem
> (maint) Ensure graceful lookup fail without hocon

- lib/puppet/version.rb
This commit bumps Puppet's version to 4.8.3 following the release of
4.8.2 as part of puppet-agent 1.8.3
> (packaging) Bump version to 4.8.3

- lib/puppet.rb
- lib/semantic_puppet.rb
We cannot guarantee that the gettext-setup gem will be present or of the
most recent version when running puppet from within puppetserver
(e.g. if the server version is < 2.7.2, the correct version of the gem
will not be present). This commit handles the absent case by stubbing
out the `_` method used for loading translations, and the out-of-date
case by using the old API for `initialize`, which removes support for MO
translation files. If gettext-setup < 0.8 is loaded, only PO translation
files will be used.
> (PUP-7116) Only use gettext functionality if gettext-setup gem is available

- lib/puppet/provider/yumrepo/inifile.rb
These headings should be h3 because all the h2 headings are for the resource types themselves. So currently it's causing it to display incorrectly in the docs navigation.
> (docs) Minor heading fix for yumrepo reference

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit fixes an oversight in the PR that was merged for PUP-7089
causing the options declared in a hierarchy entry not to be passed on to
the declared backend.
The commit also fixes a bug that made it impossible to declare more than
one hiera3_backend in the hierarchy.
> (PUP-7124) Pass options declared in Hiera v5 hierarchy to hiera3_backend

- lib/semantic_puppet.rb
- lib/semantic_puppet/locales/config.yaml
- Add locales content from the semantic_puppet gem that should have
been added in 65d1d94
- Previously in the gem, the content was laid out like:
lib/semantic_puppet.rb
locales/config.yaml
Therefore the appropriate relative path to find config.yaml was:
../locales/config.yaml
- However, under the puppet lib directory, the locales directory must
be isolated since it may otherwise conflict with other gems inside
lib, so the content is instead laid out like:
lib/semantic_puppet.rb
lib/semantic_puppet/locales
Therefore the appropriate relative path to find config.yaml becomes:
semantic_puppet/locales/config.yaml
> (PUP-7114) Vendor semantic_puppet locales

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit checks that options specified in a Hiera version 5 hierarchy
entry does not use the reserved keys 'path' or 'uri'.
> (PUP-7128) Error when reserved options are used in Hiera config

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
A hiera5_backend declared in such a way that no valid paths got configured
would cause a `undefined method `empty?' for nil:NilClass` problem when
the backend was configure. This commit ensures that this cannot happen.
> (PUP-7089) Fix problem with hiera5_backend and missing paths

- acceptance/tests/utf8/utf8-in-catalog.rb
This PR adds new acceptance test to verify correct behavior when
catalog containing utf-8 character5s is compiled and then applied
from cache.
> (PUP-7098) New acceptance test: utf-8 characters in the catalog

- locales/config.yaml
- locales/puppet.pot
The vendored semantic_puppet gem handles its own internationalization.
This commit adds a line to Puppet's gettext-setup config file which
causes it to ignore strings within semantic_puppet.
> (maint) Exclude vendored code from Puppet's gettext

- acceptance/tests/utf8/utf8-in-puppet-describe.rb
This PR adds a new acceptance test to verify correct behavior when
utf-8 chararcters are used the module description that is displayed
with the 'puppet describe' command.
> (PUP-7119) New Acceptance test: utf-8 characters in 'puppet describe'

- lib/puppet/pops/issue_reporter.rb
Before this, the error message for multiple errors simply said "multiple
errors. Giving up".
This commit changes this to say "Language valiation logged <n> errors.
Giving up". This tells the user that a) there is things in the log to
look at, and b) it was language validation (syntax errors and the like)
that caused the reported problems.
> (PUP-6006) Change phrasing of multiple errors final error

- lib/puppet/type/notify.rb
This avoids unexpected failures from skipping notify resources, when logging
on devices.
> (PUP-6783) Allow notify resources on both devices and normal hosts

- lib/puppet/ssl/certificate.rb
- lib/puppet/ssl/certificate_request.rb
- spec/unit/ssl/certificate_factory_spec.rb
- spec/unit/ssl/certificate_request_spec.rb
Further validation on these changes are needed; they work but I don't fully understand what changed to necessitate these fixes.
> (maint) SSL fixups for Ruby 2.4.0 

- lib/puppet/pops.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/evaluator/runtime3_converter.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/evaluator/arithmetic_ops_spec.rb
- spec/unit/pops/evaluator/runtime3_converter_spec.rb
- spec/unit/pops/validator/validator_spec.rb
This modifies the runtime3_converter to raise errors when converting integer values out of 64 bit range, or BigDecimal values out of range for Float.
> (PUP-3170) Cap integer size

- spec/unit/forge/repository_spec.rb
- spec/unit/network/http/factory_spec.rb
- spec/unit/util/http_proxy_spec.rb
If http_proxy is defined in the test environment specs fail due to
precedence of http_proxy over HTTP_PROXY.
With this change http_proxy is explicitly set to nil before tests as
needed.
> (PUP-6784) http_proxy specs fail if proxy is defined in test env

- lib/puppet/vendor/load_semantic.rb
- lib/puppet/vendor/semantic/lib/semantic.rb
In c111fb7, puppet switched to using the 'semantic_puppet' library instead of
'semantic'. Thus, the vendored libraries changed - 'semantic' was removed and
'semantic_puppet' added. Unexpectedly, this broke users of
garethr/puppet-module-skeleton, as this project at the time directly loaded the
'semantic' library via "require 'puppet/vendor/semantic/lib/semantic'".
This commit introduces a shim for puppet/vendor/semantic, so that users who
have required the library will not be broken. A warning is emitted as well,
noting that puppet's vendored libraries are private internal API and not
intended for external/public use.
> (pup-7156) add shim for semantic

- lib/puppet/functions/yaml_data.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that a hiera yaml file that parses correctly but
returns something other than a hash is accepted (as an empty hash) but
with a warning.
The commit also contains a fix that made type mismatch messages repeated
twice when the exception was logged.
> (PUP-7164) Handle empty hiera yaml data file gracefully

- lib/puppet/pops/lookup/environment_data_provider.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/functions/lookup_spec.rb
This commit changes the behavior when the lookup logic encounters a
hiera.yaml of version 3 in an environment root. The behavior is now
under control of --strict.
When set to `error`, an error will be raised.
When set to `warning` or `off`, a warning will be logged and the
hiera.yaml file is then ignored by the environment data provider.
> (PUP-7165) Handle hiera.yaml v3 in environment root using --strict

- locales/config.yaml
- tasks/i18n.rake
This adds a wrapper rake task for a new update_pot task that has been
added to the gettext-setup gem. This task will cache the old POT file,
generate a new one, diff them, and only replace the old one if actual
string changes have occurred. This can be used to reduce churn from
changing dates and SHAs.
The second commit adds the `vendor` directory to the ignore list for gettext-setup. Vendored code should handle its own internationalization.
> (PUP-7122) Add wrapper for gettext:update_pot rake task

- lib/puppet/pops/lookup/interpolation.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that when Hiera finds a hash, it resolves interpolated
expressions in both keys and values. Prior to this commit, only values
were resolved.
> (PUP-7167) Make Hiera interpolate keys in hash values

- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/lookup_spec.rb
This commit fixes an oversight in the logic that converts merge strategy
and options from Hiera 5 to Hiera 3. The special internal strategies
'unconstrained_deep' and 'reverse_deep' was not considered. Now they
are.
> (PUP-7169) Ensure propagation of Hiera 3 merge options to custom backend

- acceptance/Gemfile
This updates the Gemspec to allow the use of beaker 3.x, which
is needed to include support for new platforms (Ubuntu 16.10
in particular, which was added in beaker 3.10).
> (PUP-7123) Allow use of beaker 3.x in acceptance tests

- lib/puppet/pops/merge_strategy.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that a 'deep' merge that encounters a mixed set of
types or non mergable types defaults to a 'first found' strategy. This
is done by simply trusting the logic in the DeepMerge gem.
> (PUP-7176) Handle merge of scalar or mixed types as unique

- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/interpolation.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/unit/functions/lookup_spec.rb
The check if hiera.yaml was stable with respect to changing scope
between lookups, didn't take into account that the interpolated keys
could use dot notation. As a result, dotted keys were used for lookups
in the provided scope. When used with `strict_variables = true`, this
resulted in an error. When set to `false`, it degraded performance.
> (PUP-7171) Fix problem with dotted keys hiera.yaml interpolations

- Gemfile
- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
When a custom backend evaluates an interpolation expression that contains
a 'hiera' or 'alias' function, the resulting lookup must be dispatched
back to the lookup framework to perform a global lookup.
This commit ensures that the classic Hiera::Interpolation class is
patched so that the two functions are replaced with a Proc that performs
the needed dispatch.
This commit also adds a test that involves the eyaml backend that is
configured from a Hiera version 3 configuration.
> (PUP-7178) Dispatch hiera custom backend 'hiera' calls back to lookup

- lib/puppet/functions/assert_type.rb
- lib/puppet/pops/adapters.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/evaluator/relationship_operator.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loaders.rb
- lib/puppet/pops/types/type_parser.rb
- spec/lib/puppet_spec/language.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
- spec/unit/pops/evaluator/evaluator_rspec_helper.rb
- spec/unit/pops/loaders/loaders_spec.rb
- spec/unit/pops/types/ruby_generator_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
- spec/unit/resource/type_spec.rb
When resolving a type (Object, Alias, or TypeSet), it is essential that
the loader that initially loaded the type is used. This means that
if a type `A::X` in module `a` references type `B::Y` i module `b`, which
in in turn references a type `C::Z` in module `c`, then the loader for
module `a` must be used when resolving `A::X`, the loader for module `b`
must resovle `B::Y` and finally, the loader for module `c` resolves
`C::Z`.
In essence, this means that all loaders must be found by the loader names
adapted to the source of the AST that represents the type.
Fixing this resulted in cleaner code. It is now never necessary to pass
a `scope` to the TypeParser and only tests that lacks a fully configured
`Loaders` instance needs to pass a loader.
> (PUP-7179) Resolve Pcore types using the same loader that loaded the type

- lib/puppet/forge/repository.rb
- spec/unit/face/module/search_spec.rb
- spec/unit/forge/repository_spec.rb
Fixes the `--module-repository` argument when a remote URL includes a
path, as in `http://forge:8080/modules`. This allows the module tool to
work with repositories that use paths to separate different types of
artifacts.
I'd like to retarget this at stable after releases are cleaned up.
> (PUP-6588) Fix --module-repository to use full remote URL

- acceptance/tests/utf8/utf8-in-function-args.rb
The original version of this test was modified to set the environment
variable LANG to "en_US.UTF-8" on each call to on() and apply_manifest_on().
There are some VM pooler templates that to not set this by default.
In addition, the utf-8 string is now defined by using the unicode values.
> (PUP-7118) New Acceptance test: utf-8 characters in function args

- lib/puppet/type/notify.rb
This reverts commit 9fccfc7374e25795171bdaf6f34f3b207ad582e8, reversing
changes made to 89205d63a831deb732276d9b1bc412d45e7a6567.
This change was originally intended for a feature release, but due to
merge-hijinx ended up in position to be released in an up-coming 'z' release. On merge-up to master, this change should be negated, i.e., we want the original change-set to stay in master.
> Revert "Merge pull request #5276 from DavidS/notify-everywhere"

- lib/puppet/version.rb
puppet 4.9.2 will be included in puppet-agent 1.9.1.
> (packaging) Bump puppet version to 4.9.2

- lib/puppet/pops/types/ruby_generator.rb
- spec/unit/pops/types/ruby_generator_spec.rb
The RubyGenerator generates an `#eql?` method but didn't generated an
associated `#==` alias for it. This commit ensures that the alias is
also generated.
> (PUP-7168) Add `#==` alias for `#eql?` method of Pcore Objects

- acceptance/tests/lookup/lookup.rb
* automatic data-binding to functions in modules has been removed in puppet 5
* remove this portion of the test, retain the binding via metadata.json
* this change also adds do/end closures to test_name and step
[skip ci]
> (PUP-7175) lookup.rb failing automatic parameter lookup with module data binding

- acceptance/tests/aix/nim_package_provider.rb
The AIX nim provider tests previously relied on a real package. This package did not install cleanly on AIX 7.2. This updates the nim test to use a new test fixture created internally, which allows the test to function on all AIX versions.
> (PUP-7186) Switch AIX nim test to a simpler test fixture

- lib/puppet/provider/service/systemd.rb
Currently, the 'service' provider gets confused on a Debian 9 (stretch) (updated from Debian Jessie), when trying to restart services:
> Notice: /Stage[main]/Base::Ssh/File[/etc/ssh/sshd_config]/content: content changed '{md5}6c77ef6f38ca76a455809562c7f0a9a7' to '{md5}2f0a7d2e3d7cf30c3ba9eeff6af29189'
> Info: /Stage[main]/Base::Ssh/File[/etc/ssh/sshd_config]: Scheduling refresh of Service[sshd]
> Debug: /Stage[main]/Base::Ssh/File[/etc/ssh/sshd_config]: The container Class[Base::Ssh] will propagate my refresh event
> Debug: Executing: '/usr/sbin/service sshd status'
> Debug: Executing: '/usr/sbin/service sshd status'
> Debug: Service[sshd](provider=debian): Could not find sshd in /etc/init.d
> Debug: Service[sshd](provider=debian): Could not find sshd.sh in /etc/init.d
> Error: …
> (PUP-7129) Use systemd service provider for Debian 9 (Strech)

- acceptance/tests/utf8/utf8-in-function-args.rb
Our acceptance hosts are not configured with UTF-8 locale files, resulting in a
failure of these tests. Eventually we may reconfigure the hosts to support this
but for now confine this test to resume passing.
> (PUP-7190) confine utf-8 test against aix and huawei

- lib/puppet/provider/exec.rb
- lib/puppet/type.rb
- lib/puppet/type/exec.rb
- lib/puppet/util/execution.rb
- spec/unit/type/exec_spec.rb
- spec/unit/util/execution_spec.rb
This commit adds support for sensitive commands in the `Exec` resource type:
`command` parameters that are specified as `Sensitive.new(...)` are now
properly redacted when the command fails.  This supports using data from lookup
and hiera.
Example:
```puppet
exec { 'redacted':
command => Sensitive.new('/usr/bin/false SECRET_TEXT')
}
```
Output:
```
Error: [command redacted] returned 1 instead of one of [0]
Error: /Stage[main]/Main/Exec[redacted]/returns: change from notrun to 0 failed:
[command redacted] returned 1 instead of one of [0]
```
> (PUP-6494) Support sensitive commands in Exec resource type.

- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/loader/typed_name.rb
- lib/puppet/pops/types/p_type_set_type.rb
- spec/unit/pops/loaders/loaders_spec.rb
- spec/unit/pops/types/p_type_set_type_spec.rb
This commit adds a search algorithm to the module loader so that it
is capable of finding types that are embedded in TypeSets.
A `TypeSet` is a type and therefore autoloaded just like any other type.
That the file "types/x.pp" in module 'a' will contain the type `A::X`
still holds true. What is different is that if `A::X` is a `TypeSet`
which in turn contains the type `Z`, then the autoloader will find the
type `A::X::Z` by loading the `A::X` TypeSet and resolve it.
A special TypeSet that represents the module root can be added in the
file "types/init_typeset.pp". This file must define a `TypeSet` that
has an unqualified name that equals the capitalized name of the module
where it is defined.
> (PUP-7142) Autoload Pcore types from TypeSet.

- lib/puppet/provider/user/aix.rb
- According to AIX documentation for the /etc/security/passwd file
it is in an ASCII encoding
- Given -e is passed while calling chpasswd, which assumes an
already encrypted password, the contents should be written to
/etc/security/passwd directly by AIX.  Therefore, that value should
also be ASCII
> (PUP-7152) AIX encrypted user passwords are ASCII

- lib/puppet/functions/annotate.rb
- lib/puppet/pops/adaptable.rb
- lib/puppet/pops/parser/locator.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/types/annotatable.rb
- lib/puppet/pops/types/annotation.rb
- lib/puppet/pops/types/class_loader.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/p_type_set_type.rb
- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/annotate_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
This PR adds the `Annotation` type as an `Object`. The actual implementation class is a subclass of `Puppet::Pops::Adaptable::Adapter` and may be extended from the Puppet Language as an `Object` type that uses `Annotation` as its parent.
The commit also adds the function `annotate` that can be used in several different ways (see documentation in ruby source for the function).
> (PUP-7212) Add a Pcore Annotation type and an annotate function

- lib/hiera/puppet_function.rb
- lib/puppet/pops/lookup/global_data_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/invocation.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/hiera_spec.rb
A merge strategy that are passed as a parameter in a call to lookup
should always override a merge strategy defined in hiera.yaml. This
works as intended. However, this mechanism was also used by the hiera_xxx
functions to pass a strategy. The `hiera_array` and `hiera_include` will
pass `unique` and `hiera_hash` will pass `hash`, and when called from a
`hiera_xxx` function, the synthesized parameter must *not* override
a merge strategy defined in hiera.yaml.
This commit adds a `#hiera_xxx_call?` method to the `LookupInvocation`,
ensures that it is set for all hiera_xxx calls, and then ensures that
any merge strategy that is passed down in combination with that setting,
has lower priority than the strategy defined in the `hiera.yaml` file.
> (PUP-7216) Prevent merge strategy from hiera_xxx to override hiera.yaml

- lib/puppet/pops/types/annotatable.rb
- lib/puppet/pops/types/annotation.rb
- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/ruby_method.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/annotate_spec.rb
- spec/unit/pops/types/ruby_generator_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
This PR adds the `Annotation` type `RubyMethod`. It can be used on derived `Object` attributes and on `Object` functions. The annotation has two attributes. `body` which is mandatory and `parameters` which is optional and only indended for function annotations (needed since we don't have a `Callable` that uses named parameters).
> (PUP-7222) Add RubyMethod annotation and let RubyGenerator act on it

- lib/puppet/feature/hiera_eyaml.rb
- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/lookup_spec.rb
This PR contains all the commits that went in with PUP-7100 rebased to stable.
> (PUP-7205) Backport hiera_eyaml v5 lookup function to 4.9.z

- acceptance/tests/resource/service/AIX_service_provider.rb
- lib/puppet/provider/service/src.rb
- spec/unit/provider/service/src_spec.rb
Prior to this PR, attempting to manage a non-existent service would result in an error even when ensuring the service is stopped, ie:
```
$ puppet resource service foo ensure=stopped
Error: /Service[foo]: Could not evaluate: Cannot get status of foo, error was: Execution of '/usr/bin/lssrc -s foo' returned 1: 0513-085 The foo Subsystem is not on file.
Wrapped exception:
Execution of '/usr/bin/lssrc -s foo' returned 1: 0513-085 The foo Subsystem is not on file.
Error: Could not run: Cannot get status of foo, error was: Execution of '/usr/bin/lssrc -s foo' returned 1: 0513-085 The foo Subsystem is not on file.
Wrapped exception:
Execution of '/usr/bin/lssrc -s foo' returned 1: 0513-085 The foo Subsystem is not on file.
$ echo $?
1
```
This is in contrast to current and long-standing …
> (PUP-7191) consider non-existent services on AIX to be stopped/disabled rather than failing

- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/ruby_generator.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/ruby_generator_spec.rb
This commit adds the 'reference' as a valid _kind_ on a Pcore
Object attribute. Attributes that are of this kind will not participate
when iterating over contained objects using the generated `#_pcontents`
or `#_pall_contents` methods.
> (PUP-7227) Add "reference" as a valid Pcore Object attribute kind

- acceptance/lib/puppet/acceptance/classifier_utils.rb
- lib/puppet/indirector/key/file.rb
- lib/puppet/indirector/ssl_file.rb
- lib/puppet/ssl/base.rb
- lib/puppet/ssl/certificate_authority.rb
- lib/puppet/ssl/configuration.rb
- lib/puppet/ssl/inventory.rb
- lib/puppet/ssl/key.rb
- lib/puppet/type/user.rb
- spec/integration/ssl/autosign_spec.rb
- spec/integration/ssl/key_spec.rb
- spec/integration/type/user_spec.rb
- spec/unit/face/certificate_spec.rb
- spec/unit/indirector/key/file_spec.rb
- spec/unit/indirector/ssl_file_spec.rb
- spec/unit/ssl/base_spec.rb
- spec/unit/ssl/certificate_authority_spec.rb
- spec/unit/ssl/certificate_request_attributes_spec.rb
- spec/unit/ssl/certificate_request_spec.rb
- spec/unit/ssl/certificate_spec.rb
- spec/unit/ssl/configuration_spec.rb
- spec/unit/ssl/inventory_spec.rb
- spec/unit/ssl/key_spec.rb
~~Builds on #5370 which must be merged first~~
> (PUP-7134) Use Puppet::FileSystem for file access / explicitly specify encodings for SSL files

- lib/puppet/provider/package/rpm.rb
- spec/unit/provider/package/rpm_spec.rb
This fixes a regression introduced in PUP-6663 where
the package name contains a leading ' in some conditions
Strip out all uses of ' before applying the regex, as
according to most rpm guidelines ' is not a valid character.
See
https://fedoraproject.org/wiki/Packaging:Naming?rd=Packaging:NamingGuidelines
> (PUP-7214) PUP-6663 causes a regression of PUP-535

- lib/puppet/transaction.rb
The one use of Puppet::Transaction#failed? was removed in
https://github.com/puppetlabs/puppet/commit/84be695ddee004d7e358d9256f7929e1a2c400a3,
so we can now remove the method itself.
Note that the entire class is marked as api private, so no one should
be using the method.
> (PUP-6372) Remove unused Puppet::Transaction.failed? method

- lib/semver.rb
- spec/unit/semver_spec.rb
The constructor for the old deprecated `SemVer` class takes an optional
argument that, when set to true, will suppress the otherwise logged
deprecation warning. When creating some types of `SemVer` ranges, this
flag was not propagated correctly which resulted in warnings when using
Puppet module tool. This commit ensures that the flag is propagated
for all range constructs.
> (PUP-7232) Suppress deprecation warnings when creating SemVer ranges

- lib/puppet/pops/lookup/location_resolver.rb
- spec/unit/functions/lookup_spec.rb
This commit repairs the broken glob/globs implementation that was
introduced in hiera.yaml, version 5. Apparently there were no tests for
it, which of course was an oversight that had consequences. Tests are
also added in this commit.
> (PUP-7235) Fix bug causing crash when using hiera.yaml glob pattern

- lib/puppet/environments.rb
- lib/puppet/file_system/memory_file.rb
- lib/puppet/file_system/memory_impl.rb
- spec/unit/environments_spec.rb
This PR ensures that access problems on a directory that is a
candidate to be an environment (reachable using the environmentpath)
or the parent of such a directory results in an error and that puppet
gives up.
> (PUP-7102) Fail with error on access problems with environment directory

- lib/puppet/util.rb
- lib/puppet/util/character_encoding.rb
- spec/unit/util/character_encoding_spec.rb
This commit creates puppet/util/character_encoding, a single location to house
logic related to the management character encoding conversion logic in puppet.
Prior to this commit, conversion logic was just beginning to fan out and
duplicate throughout puppet - with all the associated risk and maintenance
burden. We will leverage this code in a separate effort adding a
character-encoding-aware wrapper for ruby's Etc module and rewiring our
providers to use that instead.
This commit actually only adds a single public method -
'Puppet::Util::CharacterEncoding::convert_to_utf8'.
This method applies a standard heuristic to attempt to convert a (copy of a)
passed in string to UTF-8. That heuristic is summarized and justified as
follows (much of this is left as code-comments in the commit as …
> (pup-7021) establish central string encoding conversion

- lib/puppet/file_serving/http_metadata.rb
- lib/puppet/indirector/indirection.rb
- lib/puppet/indirector/node/ldap.rb
- lib/puppet/indirector/request.rb
- lib/puppet/network/http/connection.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/evaluator/puppet_proc.rb
- lib/puppet/provider/augeas/augeas.rb
- lib/puppet/provider/user/aix.rb
- lib/puppet/provider/user/ldap.rb
- lib/puppet/ssl/certificate_factory.rb
- lib/puppet/type/file.rb
- lib/puppet/type/tidy.rb
- lib/puppet/vendor/rgen/lib/rgen/metamodel_builder/data_types.rb
- spec/unit/file_bucket/file_spec.rb
- spec/unit/file_serving/http_metadata_spec.rb
- spec/unit/functions4_spec.rb
- spec/unit/parser/scope_spec.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
- spec/unit/pops/visitor_spec.rb
- spec/unit/provider/augeas/augeas_spec.rb
- spec/unit/provider/user/directoryservice_spec.rb
- spec/unit/type/file/mode_spec.rb
- spec/unit/util/run_mode_spec.rb
- spec/unit/util_spec.rb
This PR changes three things to make the Puppet code base execute without problems using a Ruby 2.4.0 runtime.
1. Changes all Fixnum references to Integer.
2. Fixes an ambiguous time representation in `HttpMetaData` uses UTC.
3. Conditions some tests that sets ENV['HOME'] to nil (no-op on 2.4).
> (PUP-7130) Unify ruby Integer types, ENV['HOME'] handling and HTTP time

- lib/puppet/module_tool/skeleton/templates/generator/README.md.erb
The README template has changed to account for the availability of Puppet Strings. This PR revises the ## Reference section of the template.
> (docs)(PDOC-145) updating README template with puppet strings info

- spec/unit/util/execution_spec.rb
- This removes a warning from rspec about an unescaped ] used in a
regular expression:
warning: regular expression has ']' without escape: /Execution of '\[redacted]' returned 1/
> (maint) fix minor spec regex warning

- acceptance/tests/resource/service/puppet_mcollective_service_management.rb
This commit updated the `puppet_mcollective_service_management`
test to use the beaker helper `stop_agent` to set up the precondition
of ensuring that the `puppet` service is not running.
Prior to this commit, attempting to stop the `puppet` service with a
call to `puppet apply` would intermittently fail due to an active
puppet run on the agent. This caused the `puppet apply` attempt to
fail.
> (PUP-7252) Stop puppet service with helper

- lib/puppet/environments.rb
- lib/puppet/file_system/memory_file.rb
- lib/puppet/file_system/memory_impl.rb
- spec/unit/environments_spec.rb
Reverts puppetlabs/puppet#5650 which has the unintended side effect of causing puppetserver to fail to start.
> Revert "(PUP-7102) Fail with error on access problems with environment directory"

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
The eyaml backend, when configured in a Hiera version 3 config, can make
use of a special 'extension' option. The Hiera 5 function counterpart
(now also used from Hiera 3) did not take this option into account. This
commit ensures that if an extension option has been declared for a
backend in a Hiera version 3 config, that option will be honored.
> (PUP-7284) Reenable Hiera eyaml version 3 extension option

- lib/puppet/pops/lookup/invocation.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/pops/lookup/lookup_spec.rb
The logic that controls how a lookup invocation is inherited did not
take into account that a completely different lookup instance could
execute a lookup in a nested fashion. This made a lookup for the special
`lookup_options` key fail for custom adapters.
This commit ensures that the inheritance of adapter class is assigned
to the class of the parent when no explicit class is given. It also
ensures that no inheritance takes place when the adapter classes differ.
> (PUP-7240) Prevent invocation inheritance when lookup adapters differs

- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/unit/functions/lookup_spec.rb
Some unwanted explain output was generated during the check for changes of variables used in interpolation expressions in the hiera config. This PR ensures that this output is muted.
> PUP-7287) Ensure that explain is muted in check for stable config

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
Prior to this commit, the datadir in a Hiera version 5 config was not
subject to interpolation evaluation. This commit ensures that the
evaluation takes place.
> (PUP-7289) Ensure that Hiera datadir gets interpolations resolved

- lib/puppet/pops/lookup/global_data_provider.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- spec/unit/functions/hiera_spec.rb
- spec/unit/functions/lookup_spec.rb
An oversight caused the a merge behavior specified in the hiera.yaml
file to be applied to all hiera_xxx functions. The hiera_hash is the
only function that should use that definition.
This commit ensures that no other functions are affected by the
merge_behavior or merge_options in hiera.yaml.
> (PUP-7286) Fix regression in Hiera version 3 merge behavior

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
Only the `datadir` option in a Hiera 3 backend specific options entry was evaluated. This PR ensures that all keys and values in the options hash gets interpolations evaluated.
> (PUP-7293) Ensure that Hiera 3 interpolated options are evaluated

- lib/puppet/version.rb
This updates Puppet's version to 4.9.4 in preparation for the 1.9.3
release of puppet-agent.
> (packaging) Bump version to 4.9.4

- lib/puppet/functions/eyaml_lookup_key.rb
- spec/unit/functions/lookup_spec.rb
The eyaml_lookup_key function used by Hiera did not interpolated
keys in hashes. This commit ensures that it does.
> (PUP-7296) Ensure that hash key interpolations are evaluated.

- acceptance/tests/lookup/configuration_interpolation.rb
- acceptance/tests/lookup/hiera3_custom_backend.rb
- acceptance/tests/lookup/lookup_rich_values.rb
- acceptance/tests/lookup/v3_config_and_data.rb
- acceptance/tests/lookup/v4_hieradata_with_v5_configs.rb
This commit updates the v3_config_and_data test to ensure that it
manages the hiera.yaml config if it exists.
> (maint) manage hiera conf in lookup test

- benchmarks/hiera_include/benchmarker.rb
- benchmarks/hiera_include/description
- benchmarks/hiera_include/puppet.conf.erb
- Similar to the hiera_function benchmark, this benchmark will call
the hiera_include function over a large hiearchy.
The dataset was chosen to demonstrate a Puppet 4.9 regression where
the same benchmark runs approximately 5x slower than Puppet 4.8.2
Additionally, note that if groups.yaml has an additional
hierarchy added that it will run about 50% slower.  If the number
of users nested under a particular group is doubled from 125 to
250 that the benchmark will run 4x slower instead of 2x.
Paired-with: Josh Cooper <josh@puppet.com>
> (PUP-7294) Performance benchmark for hiera_include

- lib/puppet/pops/lookup.rb
- spec/unit/pops/lookup/lookup_spec.rb
Setting log-level to debug triggers full explainer output for calls
to lookup but not for automatic parameter lookups. This commit ensures
that the APLs are explained too.
> (PUP-7291) Enable APL explain output for log-level debug

- benchmarks/hiera_conf_interpol/benchmarker.rb
- benchmarks/hiera_conf_interpol/description
- benchmarks/hiera_conf_interpol/puppet.conf.erb
- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit changes the hiera configuration stability check so that it
no longer checks global variables once they have been set.
> (PUP-7303) Ensure exemption of global vars from hiera stability check

- lib/puppet/pops/functions/dispatcher.rb
- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/types/types.rb
Since type inference might potentially be very expensive (an instance
can be a very large hash or array), it should only be used unless there
are no cheaper alternatives.
This commit aims to limit the number of type inferences that are
performed during normal execution by:
1. Removing the need for inferring argument types in a call. Instead,
the callable checks if the argument array is an instance of the
parameter tuple and if the block is an instance of the block type.
2. Adding some `#instance?` methods where it is relatively easy to
compute the result without inferring the type.
The rake task `benchmark:hiera_include` shows a very drastic improvement
with this commit in place.
> (PUP-7301) Avoid unnecessary type inference

- lib/puppet/pops/lookup/data_hash_function_provider.rb
- lib/puppet/pops/lookup/data_provider.rb
Before this commit, the full hash returned by a `data_hash` function
would be validated. This is now changed so that each value is instead
validated when it is looked up.
> (PUP-7304) Defer validation of hiera data values until lookup

- benchmarks/hiera_include_one/benchmarker.rb
- benchmarks/hiera_include_one/description
- benchmarks/hiera_include_one/puppet.conf.erb
- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/functions/hocon_data.rb
- lib/puppet/functions/json_data.rb
- lib/puppet/functions/yaml_data.rb
- lib/puppet/pops/lookup/configured_data_provider.rb
- lib/puppet/pops/lookup/context.rb
- lib/puppet/pops/lookup/function_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/pops/lookup/context_spec.rb
This PR adds a file cache with environment life-cycle to the lookup context that is passed to all data provider functions. It also adds a new benchmark named `hiera_include_one` which recreates the compiler between each call to `hiera_include`. This benchmark should display a significant difference before and after the subsequent commits that adds the cache. The FileCache is enabled for the _hiera.yaml_ configuration and all bundled data provider functions (`yaml_data`, `json_data`, `hocon_data`, and `eyaml_lookup_key`).
> (PUP-7305) Add file cache to Hiera

- lib/puppet/pops/parser/lexer2.rb
- spec/unit/pops/parser/lexer2_spec.rb
Prior to this, puppet did not recognize newlines inside a regular
expression (the opening '/' and closing '/') would have to be on the
same line.
That is bad because the language specifications states that Puppet
Regexp is compatible with the implementation of Regexp used in Ruby
since 1.9.3 and it accepts newlines.
Without this fix, some regular expressions generated by for example URI
cannot be understood by puppet.
This fix removes the constraint that no newlines between the opening and
closing '/' are allowed.
> (PUP-7306) Accept newline in literal regular expressions

- lib/puppet/network/http/compression.rb
- spec/unit/network/http/compression_spec.rb
When puppet server recently correctly started sending gzip compressed content
(TK-429) we saw regressions in puppet's handling of UTF-8 characters in the
catalog, specificaly the test ticket_6448_file_with_utf8_source.rb. It turned
out that after decompression in Puppet::Network::Http::Compression, the catalog
had mangled UTF-8 bytes. This is because Zlib::GzipReader will decompress
content as whatever Encoding.default_external is. PSON (currently default
catalog content type) is BINARY encoded per specification
https://docs.puppet.com/puppet/latest/http_api/pson.html#differences-from-json.
Zlib::GzipReader will accept an encoding option just like an IO object, and
thus this commit updates the decompression to Encoding::BINARY.
This is confirmed by analyzing the body returned when puppet …
> (PUP-7251) decompress gzip as binary

- lib/puppet/parser/scope.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/location_resolver.rb
- spec/unit/functions/lookup_spec.rb
This commit adds support for a new hierarchy entry named `mapped_paths`.
It must be a three element array of strings where the first string
denotes a scope variable that should point to a collection of strings,
the second string is the variable name that will be mapped to each
element of the collection, and the third string is a template where that
variable can be used in interpolation expressions.
Paths are produced by iterating over the collection, mapping each entry
to the variable name in a local scope, and then resolve the template
using the local scope.
> (PUP-7204) Add support for mapped paths to hiera.yaml

- acceptance/tests/utf8/utf8-in-file-resource.rb
The original version of this test was modified to set the environment
variable LANG to "en_US.UTF-8" on each call to on() and apply_manifest_on().
There are some VM pooler templates that do not set this by default.
> (PUP-7117) Updated acceptance test for utf-8 characters in file resource

- acceptance/tests/utf8/utf8-in-catalog.rb
The original version of this test was modified to set the environment
variable LANG to "en_US.UTF-8" on each call to on() and apply_manifest_on().
There are some VM pooler templates that to not set this by default.
In addition, the utf-8 string is now defined by using the unicode values.
> (PUP-7098) Updated acceptance test for utf-8 characters in catalog

- acceptance/Rakefile
Sort ci:test:quick tests in lexicographical order.
[skip ci]
> (maint) Sort ci:test:quick tests

- acceptance/lib/puppet/acceptance/solaris_util.rb
- There have been intermittent test failures resulting from the
inability (under certain circumstances) to properly tear down
resources on Solaris 11 hosts.  Logs will typically show something
like:
rm -rf /ztstpool ||:
rm: Unable to remove directory /ztstpool/mnt: Device busy
rm: Unable to remove directory /ztstpool: Directory not empty
- According to Oracle docs for ZFS file system:
https://docs.oracle.com/cd/E19253-01/819-5461/gammq/index.html
And Oracle docs for ZFS storage pools:
https://docs.oracle.com/cd/E19253-01/819-5461/gammr/index.html
Both the zfs and zpool commands have -f switches available to force
removal when a device is busy.
> (PUP-7159) Force destroy zfs / zpool

- lib/puppet/network/http/connection.rb
- lib/puppet/reports/http.rb
- spec/unit/reports/http_spec.rb
Add a `metric_id` http option to the http request made by the http report
processor to report urls. This will allow Puppet Server to track the amount of
time it spends making these requests. The value for this metric id is
`[:puppet :report :http]`.
> (PUP-7285) Add metric_id http option to http report processor

- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/interpolation.rb
- spec/unit/functions/lookup_spec.rb
Before this PR, Hiera would consider an interpolation expression in the hiera.yaml that referenced a variable using a global key with subkey (a dotted key), to be initally set, although it wasn't. This was caused by the subkey lookup which transferred the nil value into an emtpy string. As a result, Hiera would skip that global key since global keys are known to be immutable (once set, they cannot change). This made Hiera miss that the value of such keys went from undefined to defined.
> (PUP-7336) Fix problem with interpolated global dotted key references

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
Previously, the `puppet_lookup_cmd.rb` acceptance test used the FQDN of
the master and the FDQN of an agent not running on the master in order
to have two unique hosts to use for node lookups when running the puppet
lookup command.  When run under a host configuration with only a single
node that has both the 'master' and 'agent' role, this test would fail
because a non-nil name could not be found for an agent not on the
master.
This commit reworks the test to use two arbitrary node names, node1 and
node2, which are exercised for puppet lookups.  This change allows the
test to be runnable in any case where there is a master in the host
configuration, even if the only agent in the host configuration is the
same as the master.
> (MAINT) Fix puppet_lookup_cmd test for single master/agent host config

- acceptance/tests/lookup/merge_strategies.rb
test hiera3 and hiera5 merge strategies using hiera_hash and lookup
functions
edit: added a commit for hiera_array and merge_hash_arrays
> (PUP-7309) acceptance: hiera merge strategies

- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/functions/lookup_spec.rb
Before this commit, if lookup_options was identified using regular
expressions, the lookup would crash unless there was also at least one
lookup option that was identified with an explicit key. This commit
fixes the problem and adds a test for the case when only regexp's are
used.
> (PUP-7341) Fix crash related to regexp identified lookup_options

- ext/project_data.yaml
We have updated the minitar component in the agent, and subsequently we will
need to update minitar for the puppet gem as well
> (PUP-7350) Update minitar to 0.6.1

- acceptance/tests/resource/sshkey/create.rb
PUP-5058 updated puppet to place sshkey resources in _/etc/ssh/ssh_known_hosts_ on OS X 10.11 and newer (it had been _/etc/ssh_known_hosts_ before 10.11). PUP-7342 is the ticket for verifying this behavior.
**NOTE TO REVIEWERS:** The OS version-handling on line 8 is clumsy and fugly. I'm open to something better.
> (PUP-5058)(PUP-7342) Adding sshkey adds it to the correct ssh_known_hosts file on OS X

- lib/puppet/functions/eyaml_lookup_key.rb
- spec/unit/functions/lookup_spec.rb
Before this commit, the `eyaml_lookup_key` function would not evaluate
interpolation expressions that were embedded in encrypted data. This
commit ensures that it does and adds a test to assert that function.
> (PUP-7359) Add evaluation of interpolation expressions in encrypted data

- lib/puppet/test/test_helper.rb
- spec/spec_helper.rb
- spec/unit/pops/lookup/context_spec.rb
A test that wrote new content with the exact same size to a file and
then checked if the file had changed by comparing inode, mtime, and
size, failed on OSX since the time resolution was too low for the rapid
create, read, change, check cycle and the inode stayed the same. This
commit ensures that the size of the file changes.
> (PUP-7340) Fix context_spec failure on OSX
