puppetlabs/puppet

- lib/puppet/parser/compiler.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/settings.rb
This PR contains a series of commits that aim to improve the time it takes for the Puppet compiler to initialize. The main problem that it solves concerns initialization of the compiler scope from the Puppet settings. That slowness of that initialization gets worse as the number of settings increases.
> (PUP-7313) Improve compiler initialization performance

- lib/puppet/pops/issues.rb
- lib/puppet/pops/lookup/data_dig_function_provider.rb
- lib/puppet/pops/lookup/data_hash_function_provider.rb
- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/lookup/environment_data_provider.rb
- lib/puppet/pops/lookup/function_provider.rb
- lib/puppet/pops/lookup/global_data_provider.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/interpolation.rb
- lib/puppet/pops/lookup/location_resolver.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- lib/puppet/pops/lookup/lookup_key_function_provider.rb
- lib/puppet/pops/lookup/module_data_provider.rb
- spec/unit/data_providers/function_data_provider_spec.rb
- spec/unit/functions/lookup_fixture_spec.rb
- spec/unit/functions/lookup_spec.rb
This commit contains an overhaul of the errors raised by the lookup
framework. Most errors are converted into proper issues and added to
lib/puppet/pops/issues.rb and, as such, allowed to be propagated all
the way to the log while retaining location information.
Many errors originating from the hiera.yaml will now also have line
information. This is accomplished by a combination of regexps and a
fairly naive parser that is aware of strings and comments.
The errors that were reported when a value was found that didn't conform
to the Puppet::LookupValue have been changed to explicitly state the
originating location and, when appropriate, the key of the culprit.
Unit tests were added to the unit/functions/lookup_spec.rb to cover all
the added issues.
> (PUP-7182) Improve error messages from Hiera 5

- lib/puppet/functions.rb
- lib/puppet/pops/evaluator/callable_signature.rb
- lib/puppet/pops/functions/dispatch.rb
- lib/puppet/pops/functions/dispatcher.rb
- lib/puppet/pops/types/p_object_type.rb
- spec/unit/functions4_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
This commit adds an alternative `dispatch` to a function. It is named
`argument_mismatch`. The function that it calls must produce a String
that represents a message describing that the matched arguments are in
fact in error. An `ArgumentError` is then raised when the function returns
that string.
An `argument_mismatch` dispatcher will be excluded when the default
argument mismatch handler describes viable options. It is also excluded
from the list of dispatchers returned from the `Dispatcher`.
A function may have zero to many `argument_mismatch` declarations and
when none of them matches, the default mismatch describer still kicks
in.
> (PUP-7368) Add ability to declare function argument mismatch handlers

- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/functions/hocon_data.rb
- lib/puppet/functions/json_data.rb
- lib/puppet/functions/yaml_data.rb
- spec/unit/functions/lookup_spec.rb
Before this commit, a missing path declaration in hiera.yaml resulted in
an error explaing that the options hash sent to a data_hash function that
required a path had an incorrect size (0 instead of 1). While correct,
that message was not very informative. This commit leverages the new
`argument_mismatch` dispatcher added by PUP-7368 to generate more useful
errors when the path is missing.
> (PUP-7273) Improve hiera function error message when path is missing

- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/pcore.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that the `Puppet::LookupKey` and
`Puppet::LookupValue` types are made known to the puppet type loader.
> (PUP-7330) Ensure that lookup types are registered with loader

- spec/unit/provider/package/pkg_spec.rb
Before this change attempts to execute only pkg_spec would fail while
mocking CHILD_STATUS. When executed with other specs that initialize
CHILD_STATUS in some way execution is successful
> (PUP-7158) pkg_spec.rb failure on individual execution starting c5d97e

- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/dig_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
- spec/unit/pops/types/types_spec.rb
The mismatch describer "forgot" that a type was optional when describing
it and in some cases simply dropped that type out of the description.
This commit ensures that the optional status is remembered and reported.
The commit also improves the type generalization of the `Variant` type
with respect to `Undef` and `Optional` so that a type that contains
either one becomes an `Optional` type that contains neither.
A side effect from fixing the above was that some tests needed to be
adjusted.
> (PUP-7371) Fix bug with missing undef in type mismatch description

- lib/puppet/pops/lookup/data_dig_function_provider.rb
- lib/puppet/pops/lookup/data_hash_function_provider.rb
- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/lookup/function_provider.rb
- lib/puppet/pops/types/type_asserter.rb
- spec/unit/functions/lookup_spec.rb
A data provider function that declares a return type, must use a type that is assignable to `Puppet::LookupValue` or, in case the function is a `data_hash`, to `Hash[Puppet::LookupKey,Puppet::LookupValue]`. This PR ensures that an error is raised if the return type is incorrect.
In this PR, it's also ensured that the lookup framework will rely on function to do return type validation when all of its dispatchers declares a correct return type.
> (PUP-7370) Ensure value returned from provider is checked only once.

- lib/puppet/network/http/api/master/v3/environment.rb
- lib/puppet/resource/type.rb
- spec/unit/network/http/api/master/v3/environment_spec.rb
This pull request includes two improvements to how application node/component
mapping specifications are validated:
- Require `nodes` param for application declarations
Previously, the `nodes` parameter of applications was marked as optional in the
type system, but would cause a failure when processing the catalog and
attempting to iterate the nodes hash. Since this was always implicitly required
and there's no good reason for it not to always be specified, we now explicitly
require it so as to cause a clear, early failure.
- Fail when non-existent components have nodes assigned
Previously, non-existent components in the node mapping of an application would
simply be ignored. Because this frequently happens when the user incorrectly
types the component name, it can be especially confusing …
> (PUP-6182) Improve validation of component mappings in applications

- lib/puppet/application/describe.rb
- spec/unit/application/describe_spec.rb
Before this fix a long line without spaces in a puppet type description
causes puppet describe to fail at formatting the description.  This is a
side effect of anchoring the match expression to ^, beginning of string,
when it should be anchored with \A, beginning of line.
For example, with this type, (described by modules/mytype_module/lib/puppet/type/mytype.rb):
Puppet::Type.newtype(:mytype) do
@doc = ". 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890 nick@magpie.puppetlabs.lan
**this part should not repeat!**
"
newparam(:name) do
isnamevar
desc " name parameter for mytype"
end
end
would give this result before the fix:
[root@syqs5cacqx016cd type]# puppet describe mytype
mytype
======
.
**this part should not
**this part …
> (PUP-7329) This change fixes a regex in describe.rb.

- spec/integration/type/package_spec.rb
PUP-2728 updated the default package provider to be `zypper` instead of `rug` on SUSE-family OSes. This PR, ticketed in PUP-7373, updates the package provider integration spec test to expect `zypper` as the default package provider on SUSE-family OSes 10.x and newer and `rug` on anything older.
> (PUP-7373) Zypper is default package provider on SUSE

- lib/puppet/pops/issues.rb
- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit makes it possible to declare an `options` hash under the
hiera.yaml `defaults` entry. That hash will then be used by all entries
beneath `hierarchy` that does not declare an `options` entry of their
own. The `options` hash is never merged. If an entry declares it, it
replaces the default.
> (PUP-7281) Add ability to declare options as an entry in Hiera defaults

- acceptance/Rakefile
Add the `gen_hosts` task as a dependency of `ci:test:quick` so that the
beaker-hostgenerator file is created before calling beaker.
/cc @puppetlabs/agent-team 
This needs to be merged up to 4.10.x and master
> (PUP-7330) Add gen_hosts dependency for quick target

- acceptance/Rakefile
Previously, the quick task was trying to run `.sh` files as beaker tests
which were recently modified.
This commit ensures we only try to run files ending in `.rb`. If those
are not beaker tests then they need to be in a different directory
other than `tests`.
Supersedes PR #5744.
[skip ci]
> (maint) Only ci:test:quick ruby files

- acceptance/Rakefile
Commit fb9ab3b18 removed the ability to specify a pre-generated beaker
hosts config file using the `BEAKER_HOSTS` environment variable which is
used in ci-job-configs. Instead the rake task was combining the default
master platform and the `TEST_TARGET`, which already contains the master
platform resulting in a BHG string like:
redhat7-64m-redhat7-64m-redhat6-64a
However, this causes the beaker run to fail because there are two master
platforms specified.
This commit restores the ability to specify a pre-generated beaker hosts
config file using `BEAKER_HOSTS`.
> (PUP-7237) Restore BEAKER_HOSTS env variable support

- lib/puppet/parser/compiler.rb
- spec/unit/functions4_spec.rb
- spec/unit/pops/loaders/loaders_spec.rb
Under some very rare circumstances, such as when the running the lookup
CLI command and the only available data provider for Hiera was a custom
backend written in Ruby, the Pcore would not be initialized by the
compiler since no loader was ever requested. This in turn, resulted in
that the `Puppet::LookupKey` and `Puppet::LookupValue` types never got
initialized.
This commit changes the compiler so that it performs the task of
initializing loaders and Pcore during its own initialization instead of
performing it lazily when the loaders are first requested.
The change in behavior broke a couple of tests that made assumptions on
the deferred loader initialization. This commit fixes those tests as
well.
The problem was triggered by commit 12b8ab94cd75c3db9feb858c4eccf61d9b6940db
> (PUP-7330) Ensure that lookup CLI initializes loaders

- lib/puppet/pops/issues.rb
- lib/puppet/pops/lookup/configured_data_provider.rb
- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/lookup/explainer.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- lib/puppet/pops/lookup/module_data_provider.rb
- spec/unit/functions/lookup_spec.rb
This commit adds the ability to declare a second hierarchy named
`default_hierarchy` to a hiera.yaml file that resides in a module root.
This hierarchy is only allowed in modules and will be consulted when, and
only when, a normal lookup does not find a value.
The `default_hierarchy` is insensitive to `lookup_options` declared in
the regular `hierarchy` and vice versa.
The `default_hierarchy` is also insensitive to any merge directives
passed in as a parameter in the lookup call.
> (PUP-7334) Add Hiera default_hierarchy to module hiera.yaml

- lib/puppet.rb
- lib/puppet/etc.rb
- lib/puppet/util/character_encoding.rb
- spec/unit/etc_spec.rb
- spec/unit/util/character_encoding_spec.rb
This PR includes the content of https://github.com/puppetlabs/puppet/pull/5633, and is separated out for ease of review. This PR content is the content of commit '(pup-7021) Add UTF-8-aware Etc wrapper'.
The Ruby Etc module will return various Struct objects containing strings in
the system's locale, or if they are invalid in the current locale, as
ASCII-8BIT (Binary). This leads to inconsistent and problematic behavior when
Puppet uses the Etc module in its providers, particularly when trying to
concatenate or compare strings which now may have different, and often
incompatible, encodings. The nameservice provider in particular makes heavy use
of Etc, which has resulted in numerous bugs reported regarding UTF-8.
Initial attempts to resolve the issues focused on the locations where string …
> (PUP-7021) Add UTF-8-aware Etc wrapper

- lib/puppet.rb
- lib/puppet/etc.rb
- lib/puppet/provider/nameservice.rb
- lib/puppet/util/character_encoding.rb
- spec/unit/etc_spec.rb
- spec/unit/provider/nameservice_spec.rb
- spec/unit/util/character_encoding_spec.rb
This PR includes the content of PRs https://github.com/puppetlabs/puppet/pull/5634 and https://github.com/puppetlabs/puppet/pull/5633. It is separated out for ease of review. This PR content is the content of commit '(PUP-7021) leverage Puppet::Etc in nameservice provider'.
This commit updates the nameservice provider to leverage Puppet::Etc instead of
ruby's Etc module, as Puppet::Etc converts field values to UTF-8, avoiding
problems with the concatenation, comparison and display of non-UTF-8
characters.
> (PUP-7021) leverage Puppet::Etc in nameservice provider

- lib/puppet/provider/package/portage.rb
- spec/unit/provider/package/portage_spec.rb
Allow the portage package provider to accept install and uninstall
options.  This is useful if you do not want to use the default global
EMERGE_DEFAULT_OPTS paramaters setable in make.conf.
Allow the portage package provider to purge package if requested.
Allow package sets (@world @system and the like)
> (PUP-7095) Enable portage install and uninstall options for the package provider

- lib/puppet/pops/lookup/global_data_provider.rb
- lib/puppet/pops/lookup/interpolation.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that a data file that is reached using a Hiera 3
configuration and that in turn contains interpolation expressions that
use the 'hiera' or 'lookup' function, will have that lookup confined
to the global layer unless an environment data provider, version 5
is present. It also ensures that when an interpolation that originas
from Hiera 3 is calling out, that the special `Hiera::Scope` class
is unwrapped.
This was not the case earlier which resulted in that the special class
`Hiera::Scope` was passed on to the environment and module layers which
resulted in errors as they tried to access the `Scope#environment`
method which is not present in that class. Other side-effects of passing
that scope would be to make the special variables that it contains
available to data …
> (PUP-7372) Confine Hiera 3 interpolations to the global layer

- lib/puppet/util/windows/file.rb
- Previously, anytime Puppet::Util:::Windows::File.replace_file is
called, it used the Windows ReplaceFile API with the flag
REPLACEFILE_WRITE_THROUGH
MSDN documentation specifies:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365512(v=vs.85).aspx
"
This value is not supported.
"
Unfortunately, this flag could prevent replace_file from behaving
properly on a UNC share.  When dealing with a UNC path, a 0 byte
file would get written, but due to the inability to set ACL
permissionss and the absence of REPLACEFILE_IGNORE_MERGE_ERRORS
being set on the API call - the file would fail to be written.
- When the original code in 73e302bbf5ab4a6c5513a39070e2c907542775ae
made the call to ReplaceFileW, it's my understanding that the flag
value was selected because the intent was to ensure …
> (PUP-7077) Fix Windows::File.replace_file on UNC

- lib/puppet/application.rb
- lib/puppet/application/inspect.rb
- lib/puppet/defaults.rb
- lib/puppet/type.rb
- spec/unit/application/inspect_spec.rb
- spec/unit/type/file_spec.rb
This PR:
1) Adds a utility for deprecating applications based on Moses's work in https://github.com/puppetlabs/puppet/pull/5449/commits/7fefceae40d5ace8df2bd85aefa8bdee3246d9e1
2) Deprecates the `inspect` command
3) Deprecates the `audit` metaparameter
> (PUP-893) Deprecate `inspect` command and `audit` metaparameter

- lib/puppet/parser/compiler.rb
- spec/unit/parser/compiler_spec.rb
Before this commit, each compilation would make an attempt to create
and add the 'settings' Class to the list of known resource types in the
environment. When more than one compilation was performed during the
life span of an environment, a warning "Class 'settings' is already
defined" would appear in the log. This is now changed so that the
compiler instead reuses the Class if it is already present in the
environment.
> (PUP-7328) Ensure that the 'settings' Class is created only once

- lib/puppet/application/lookup.rb
This help text was written in the Puppet 4.3 era, and it needed a post-Hiera 5
update.
> (docs) Revise the puppet lookup command's help text

- acceptance/tests/apply/augeas/hosts.rb
We have found that the new Cisco eXR 6.1.3 VM image has /etc/hosts
as a mount point, so the augeus host test fails to rename the it.
> (PUP-7380) Skip augesu test on Cisco XR

- lib/puppet/pops/loader/base_loader.rb
- spec/unit/pops/loaders/module_loaders_spec.rb
This commit ensures that the BaseLoader#internal_load method is prepared
for the case when its call to the parent loader initiates another load
of the same entity that it is currently loading. When this happens, the
resulting recursion loads the type and when it returns, the type will
be present in the loader. A check is therefore inserted to prevent an
attempt to add the entity once again, since that would result in an
error.
> (PUP-7391) Ensure that the BaseLoader can handle self recursion

- lib/puppet/application.rb
- lib/puppet/application/inspect.rb
- lib/puppet/defaults.rb
- lib/puppet/type.rb
- spec/unit/application/inspect_spec.rb
- spec/unit/type/file_spec.rb
This PR reverts the revert of the `inspect` command and `audit` metaparameter deprecation. It also adds a commit which causes the warning for `audit` to only be emitted when the parameter is set via a manifest.
This supersedes https://github.com/puppetlabs/puppet/pull/5756.
> (PUP-893) Revert inspect and audit deprecation revert

- lib/puppet/parser/compiler.rb
- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- lib/puppet/resource/catalog.rb
- spec/integration/parser/compiler_spec.rb
- spec/unit/parser/compiler_spec.rb
- spec/unit/resource/catalog_spec.rb
- spec/unit/settings_spec.rb
This PR combines fixes for PUP-5659 "Validate relationships formed via meta-parameter", and PUP-6984 "Make aliases work in resource references".
The behaviour in PUP-5659 was earlier controlled via `strict` and is now always an error. In order to make this change, it was also necessary to fix the problem of references to resources based on an alias would always error. Thus, `strict` could only be used by those that had no references to resources with aliases.
This was bad because it meant that compilation could not find the errors, and the errors would instead be runtime errors when the produced catalog was applied.
The problems were:
* explicit aliases were not added to the catalog when compiling
* validation conditional on strict when desired to always be validated
> (PUP-6984)(PUP-5659) Allow references to resource aliases

- acceptance/tests/ticket_1334_clientbucket_corrupted.rb
This commit adds an acceptance test to ensure that puppet gracefully
recovers from a clientbucket corruption. The assertions in this test
are currently expected to fail until PUP-7356 is resolved.
[skip-ci]
> (PUP-7356) Add clientbucket corrupted test

- acceptance/tests/ticket_1334_clientbucket_corrupted.rb
This commit removes the expect_failure conditions for the validation
steps in the corrupted clientbucket test. This issue has been fixed
and these are no longer expected to fail. Validation of the 'Warning'
emitted to STDOUT has also been added.
[skip ci]
> (PUP-7356) Remove expect failure clientbucket test

- lib/puppet/pops/evaluator/access_operator.rb
- spec/integration/parser/class_spec.rb
- spec/integration/parser/compiler_spec.rb
This removes the deprecated (since Puppet 4.6.0) construct of
referencing a class with an upper case name, for example Class[Foo] by
making it always be an error.
This is removed since Foo evaluates to a type reference, and it may be a
type alias or a Resource. It may also be a type that requires
parameters. The use of an upper case name thus creates unssesary type
loading, and potentially a mysterious error.
The correct reference is always a String, and this string is always in
lower case.
> (PUP-6084) Make reference to Class[<upper case name>] be an error

- lib/puppet/configurer.rb
- lib/puppet/configurer/downloader.rb
- lib/puppet/configurer/fact_handler.rb
This commit marks error and info strings in `lib/puppet/configurer.rb`
and `lib/puppet/configurer/*` for translation.
> (PUP-7042) Mark strings in configurer

- lib/puppet/reports/http.rb
- locales/config.yaml
This commit marks user-facing error strings in `lib/puppet/reports/*`
for translation.
> (PUP-7042) Mark strings in reports

- lib/hiera/puppet_function.rb
- lib/puppet/parser/functions/hiera.rb
- lib/puppet/parser/functions/hiera_array.rb
- lib/puppet/parser/functions/hiera_hash.rb
- lib/puppet/parser/functions/hiera_include.rb
- lib/puppet/version.rb
- spec/unit/version_spec.rb
Sometimes error messages link to versioned docs pages. The docs pages
are only versioned by minor numbers, such as `4.9`. Ergo, it would be
nice to have a method to generate those easily. This adds that method.
This "reimplements" some version parsing because attempts to load the
SemanticPuppet library became too heavy and fragile.
> (PUP-7360) Add a minor_version method to make docs links easier

- lib/puppet/transaction.rb
- lib/puppet/transaction/additional_resource_generator.rb
- lib/puppet/transaction/event.rb
- lib/puppet/transaction/event_manager.rb
- lib/puppet/transaction/persistence.rb
- lib/puppet/transaction/resource_harness.rb
This commit marks user-facing error and info level strings in
`lib/puppet/transaction.rb` and `lib/puppet/transaction/*` for
translation.
> (PUP-7042) Mark strings in transaction

- ext/project_data.yaml
- ext/windows/service/daemon.rb
- lib/puppet/feature/eventlog.rb
- lib/puppet/util/log/destinations.rb
- lib/puppet/util/windows.rb
- lib/puppet/util/windows/eventlog.rb
- spec/unit/util/log/destinations_spec.rb
- spec/unit/util/log_spec.rb
- spec/unit/util/windows/eventlog_spec.rb
Remove dependency on eventlog by including our own ffi definitions of the
required functions for puppet logging. Most simple implementation - write-only
support for event log.
API compatible with previous implementation.
Uses W (unicode) versions of API functions. The spec for these functions can be
found here:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363654(v=vs.85).aspx
Replace existing log destination of win32/eventlog with
Puppet::Util::Windows::EventLog. This means we don't need to check for the
eventlog library any more as part of the eventlog feature. We keep the eventlog
feature for backwards compatibility for now, but it can be removed.
Previous implementation with Win32::EventLog actually (unnecessarily) created
two handles to the event log - one opened with …
> (PUP-5756) remove dependency on win32/eventlog

- CONTRIBUTING.md
- lib/puppet/util/command_line/puppet_option_parser.rb
Now that we have begun merging PRs which mark all user-facing error
strings in Puppet, it is important that future work also have its
strings marked. This updates the contributor guidelines with details of
new expectations.
> (PUP-7404) Add guidelines for string marking to contributor guidelines

- lib/puppet/pops/types/type_calculator.rb
String formatting of types are done by the TypeFormatter.
The deprecated backwards compatible delegating methods in TypeCalculator
are now removed.
> (PUP-6015) Drop deprecated string formatting methods from TypeCalculator

- lib/puppet/pops/lookup/global_data_provider.rb
- lib/puppet/pops/lookup/interpolation.rb
- lib/puppet/pops/lookup/invocation.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/pops/lookup/interpolation_spec.rb
Before this commit, an interpolation using a module prefixed key and a
function that in turn made a full lookup (alias, lookup, or hiera),
would reset the `module_name` in the lookup invocation. This would
normally go undetected since the value, when found, would end the
lookup. During a deep_merge however, when the sub-lookup was made from
global or environment layer, the lookup's desire to find more data in
the module layer would not be satisfied correctly unless the sub-lookup
was targeting the same module as the original lookup.
This commit ensures that a new invocation is used for the sub-lookup,
leaving the original invocation untouched.
> (PUP-7418) Fix problem with interpolated lookups

- lib/puppet/pops/lookup.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/functions/lookup_spec.rb
This commit ensures that regular lookups and APLs are explained with a
correct heading and only once in a debug log. Before this commit, the
regular lookup would be logged twice, where the second time appeared to
be an APL.
> (PUP-7420) Ensure unique explain logs in debug output

- lib/puppet/application/apply.rb
- lib/puppet/application/device.rb
- lib/puppet/application/resource.rb
- spec/unit/application/apply_spec.rb
- spec/unit/application/device_spec.rb
- spec/unit/application/resource_spec.rb
This PR ensures that a `Puppet::Pops::Loaders` instance is created and adapted to the current environment when executing the `apply`, `device` or `resource` command. This enables subsequent ruby code to access the instance and load Pcore types dynamically.
> (PUP-7423) Make Pcore loader available for relevant CLI commands

- lib/puppet/node.rb
- lib/puppet/node/environment.rb
- lib/puppet/parameter/package_options.rb
- lib/puppet/parameter/path.rb
- lib/puppet/parameter/value_collection.rb
`lib/puppet/node.rb` and `lib/puppet/node/*` for translation.
> (PUP-7042) Mark strings in node

- lib/puppet/info_service/class_information_service.rb
`lib/puppet/info_service/*` for translation.
> (PUP-7042) Mark strings in info_service

- lib/puppet/generate/type.rb
`lib/puppet/generate*` for translation.
> (PUP-7042) Mark strings in generate

- lib/puppet/forge.rb
- lib/puppet/forge/errors.rb
`lib/puppet/forge.rb` and `lib/puppet/forge/*` for translation.
> (PUP-7042) Mark strings in forge

- lib/puppet/file_bucket/dipper.rb
- lib/puppet/file_bucket/file.rb
`lib/puppet/file_bucket/*` for translation.
> (PUP-7042) Mark strings in file_bucket

- lib/puppet/resource.rb
- lib/puppet/resource/capability_finder.rb
- lib/puppet/resource/catalog.rb
- lib/puppet/resource/status.rb
- lib/puppet/resource/type.rb
- lib/puppet/resource/type_collection.rb
`lib/puppet/resource.rb` and `lib/puppet/resource/*` for translation.
> (PUP-7042) Mark strings in resource

- lib/puppet/module_tool/tar.rb
- spec/unit/module_tool/tar_spec.rb
- For platforms that ship a minitar gem (currently Windows, about to
include Solaris, and will eventually be *all* platforms), prefer
that to a local `tar` binary.
Solaris 10 currently doesn't work properly with the `tar` binary
and will be soon bundled with the minitar gem.  However, to use
the minitar gem, the priority ordering needs to be adjusted.
- Currently only Windows ships the minitar gem (as it has a platform
specific gem), but eventually all platforms will reference the
minitar gem for the same reason - consistency and robustness.
> (PUP-7390) Prefer minitar for PMT when available

- acceptance/tests/lookup/config3_interpolation.rb
- acceptance/tests/lookup/config5_interpolation.rb
@thallgren @hlindberg 
we used to have a partly unwritten rule that any regression should get an acceptance test.  i had written most of this one last week to reproduce the errors in PUP-7336.
this is partly covered here: https://github.com/puppetlabs/puppet/pull/5706/files#diff-2c12cbb4931cfd2102db8d688e73049eR367
i might be missing the coverage in unit tests for the other variable scoping and subkeys i've used here.  
do you have feelings on which of these should be acceptance tests, and which not?  keeping in mind we're trying to push as many tests closer to the developers' unit test feedback loop as possible.
> (pup-7344) acceptance hiera5 config interpolated with various scoped and nested variables

- lib/puppet/parser/functions/new.rb
- lib/puppet/pops/types/string_converter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/pops/types/types_spec.rb
This PR changes the default string format (the '%s' format) so that
a formatted regexp results in a string that isn't delimited with
slashes.
The reason for the change is that the slashes are language specific, and
as such, should be produced using the '%p' format (which they already
are). The '%s' format should produce a language agnostic representation
that is suitable to pass to the Regexp constructor.
> (PUP-7429) Change default string format for Regexp

- acceptance/tests/resource/file/should_create_directory.rb
Previously, the test added two resources to the catalog where one had a
trailing slash. The test relied on `defined` returning false, as it did
before commit ae066f9.
As of ae066f9, puppet will now detect that the resource with the
trailing slash has the same name as the one without. So this test
started failing (since we never tried to add a duplicate resource).
This commit updates the test to unconditionally add the duplicate. It
also removes the app_management cases since that property is deprecated
and no longer controls any behavior.
Error: Evaluation Error: Error while evaluating a Resource
Statement, Cannot alias File[/tmp/create-dir.foyI4D/] ...
[skip ci]
> (PUP-7402) Update test now that trailing slash alias works

- lib/puppet/module.rb
- lib/puppet/pops/parser/interpolation_support.rb
This commit fixes some miscellaneous compiler warnings which appear when
running the server under JRuby 9000.
> (MAINT) Fix compiler warnings from jruby 9k

- lib/puppet.rb
- Previously, the minimum version comparison check was performed on a
string. This can lead to failures - for instance:
0.0.10 < 0.0.2 # true!
Version numbers should not be treated as strings for the sake of
comparisons.  Note that while we do have access to `SemVer` inside
of Puppet, its not yet loaded here, so return to the standard
`Gem::Version` for comparisons.
> (maint) Fix Puppet Ruby version check comparison

- .travis.yml
- Gemfile
- lib/puppet.rb
* upstream/stable:
(maint) Fix Puppet version check comparison
(maint) Mark net-ssh as Gemfile runtime dependency
(maint) Remove tzinfo gem from Gemfile
(maint) Move rake to Gemfile development / test
(maint) TravisCI should not bundle install extra
(maint) Remove TravisCI gem install of bundler
Preserve `gem update --system --no-doc` needed for ruby 2.4 (df0b1d0)
Preserve `extra` bundler_arg to be consistent with appveyor (f32b8dc)
> (maint) Merge stable to master

- lib/puppet/provider/package/pkgin.rb
- lib/puppet/provider/package/pkgng.rb
- spec/integration/type/package_spec.rb
DragonFly BSD has been using pkgng for a few years now. This changes the default
package provider on it to be pkgng as is correct for it, and adjusts the spec
tests for it accordingly.
> Make DragonFly BSD work out of the box

- .gemspec
- Gemfile
- Without platform-specific gem dependencies marked as such inside the
.gemspec, this can cause issues with a bundler based workflow that
uses `bundle install --system --binstubs c:\ruby\bin` on Windows
machines *even if* the given Ruby version already satisfies all of
the Puppet platform-specific dependencies. This is due to how a
Gem is installed by Bundler when it refers to a git repo and its
.gemspec is rewritten by Bundler as its installed.
- Note that all runtime dependencies are now present in the .gemspec
and that any development dependencies are still defined in the
Gemfile itself.
The .gemspec is included in a `bundle install` by calling the
`gemspec` method inside the Gemfile.  This is the intended inclusion
mechanism for Bundler.
The Gemfile continues to allow a few gem …
> (PUP-7425) Refactor Gemfile / .gemspec for Bundler workflow

- acceptance/config/common/options.rb
Puppet tests for passenger and active records storeconfigs used to rely
on epel repos. CI was failing with HTTP 404:
http://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm
Since we don't need epel anymore, configure beaker to not install it
during acceptance. Facter, hiera, and pxp-agent already do the same.
[skip ci]
> (PUP-7442) Don't install epel repos

- .gemspec
This PR is a follow on to #5797 
- 19f78a20b70660b30fff8c0c49e8b9a9b3c99b40 introduced a refactoring to
the Gemfile / .gemspec to support the Bundler workflow in use for
the `ci:test:git` task.
What was not realized at the time was that the .gemspec is copied
verbatim when building puppet-agent packages with Vanagon per
https://github.com/puppetlabs/puppet-agent/blob/37985352cb330aad2f8f3e8ad89f9267d6beb4fe/configs/components/puppet.rb#L166
This is to present `puppet` as a legitimate gem within the
puppet-agent package / Ruby runtime.
Interestingly, this varies from how the Puppet gem is produced where
a .gemspec that includes platform specific dependencies is built on
the fly from project_data.yaml using the rake task from the
packaging repo per `gem.rake`: …
> (PUP-7425) Fix .gemspec for Vanagon packages

- Gemfile
- appveyor.yml
- AppVeyor is generating intermittent failures when executing
`bundle exec rake parallel:spec[2]`, despite no spec tests
actually failing.
This has been narrowed down to a non-zero exitcode being returned
from bundler when yard is not present due to:
Document generation not available without yard. cannot load such file -- yard
It's unclear why this only intermittently fails when executed
through cmd, as it will always fail when executed within a
PowerShell script (like the refactoring in the next commit)
- Since `bundler` wants access to `yard`, move it out of the
:developemnt group (which is currently not installed in
AppVeyor / Travis) so that it's present in both the :test and
:development groups - allowing it to be installed in those
environments
- Previously test_script was a …
> (maint) Fix intermittent AppVeyor failures / rewrite AppVeyor test_script as PowerShell

- lib/puppet/type/augeas.rb
- lib/puppet/type/cron.rb
- lib/puppet/type/exec.rb
- lib/puppet/type/file.rb
- lib/puppet/type/filebucket.rb
- lib/puppet/type/group.rb
- lib/puppet/type/host.rb
- lib/puppet/type/interface.rb
- lib/puppet/type/k5login.rb
- lib/puppet/type/macauthorization.rb
- lib/puppet/type/mailalias.rb
- lib/puppet/type/maillist.rb
- lib/puppet/type/mount.rb
- lib/puppet/type/package.rb
- lib/puppet/type/resources.rb
- lib/puppet/type/schedule.rb
- lib/puppet/type/scheduled_task.rb
- lib/puppet/type/service.rb
- lib/puppet/type/ssh_authorized_key.rb
- lib/puppet/type/sshkey.rb
- lib/puppet/type/tidy.rb
- lib/puppet/type/user.rb
- lib/puppet/type/yumrepo.rb
- lib/puppet/type/zone.rb
`lib/puppet/type/*` for translation.
> (PUP-7042) Mark strings in type

- lib/puppet/application.rb
- lib/puppet/application/agent.rb
- lib/puppet/application/apply.rb
- lib/puppet/application/cert.rb
- lib/puppet/application/device.rb
- lib/puppet/application/doc.rb
- lib/puppet/application/face_base.rb
- lib/puppet/application/filebucket.rb
- lib/puppet/application/inspect.rb
- lib/puppet/application/lookup.rb
- lib/puppet/application/master.rb
- lib/puppet/application/resource.rb
`lib/puppet/application.rb` and `lib/puppet/application/*` for
translation.
> (PUP-7042) Mark strings in application

- lib/puppet/context.rb
- lib/puppet/context/trusted_information.rb
`lib/puppet/context.rb` and `lib/puppet/context/*` for translation.
> (PUP-7042) Mark strings in context

- lib/puppet/network/auth_config_parser.rb
- lib/puppet/network/authconfig.rb
- lib/puppet/network/authstore.rb
- lib/puppet/network/format_support.rb
- lib/puppet/network/formats.rb
- lib/puppet/network/http/api/indirected_routes.rb
- lib/puppet/network/http/api/master/v3/environment.rb
- lib/puppet/network/http/compression.rb
- lib/puppet/network/http/connection.rb
- lib/puppet/network/http/error.rb
- lib/puppet/network/http/handler.rb
- lib/puppet/network/http/pool.rb
- lib/puppet/network/http/rack.rb
- lib/puppet/network/http/request.rb
- lib/puppet/network/http/webrick.rb
- lib/puppet/network/http/webrick/rest.rb
- lib/puppet/network/rights.rb
- lib/puppet/network/server.rb
`lib/puppet/network/*` for translation.
> (PUP-7042) Mark strings in network

- lib/puppet/parser/ast/pops_bridge.rb
- lib/puppet/parser/ast/resource.rb
- lib/puppet/parser/ast/resource_instance.rb
- lib/puppet/parser/ast/resourceparam.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/parser/compiler/catalog_validator/env_relationship_validator.rb
- lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb
- lib/puppet/parser/compiler/catalog_validator/site_validator.rb
- lib/puppet/parser/environment_compiler.rb
- lib/puppet/parser/functions.rb
- lib/puppet/parser/functions/contain.rb
- lib/puppet/parser/functions/create_resources.rb
- lib/puppet/parser/functions/file.rb
- lib/puppet/parser/functions/generate.rb
- lib/puppet/parser/functions/include.rb
- lib/puppet/parser/functions/inline_template.rb
- lib/puppet/parser/functions/require.rb
- lib/puppet/parser/relationship.rb
- lib/puppet/parser/resource.rb
- lib/puppet/parser/scope.rb
- lib/puppet/parser/templatewrapper.rb
- lib/puppet/parser/type_loader.rb
`lib/puppet/parser/*` for translation.
> (PUP-7042) Mark strings in parser

- lib/puppet/module_tool.rb
- lib/puppet/module_tool/applications/application.rb
- lib/puppet/module_tool/applications/builder.rb
- lib/puppet/module_tool/applications/checksummer.rb
- lib/puppet/module_tool/applications/installer.rb
- lib/puppet/module_tool/applications/searcher.rb
- lib/puppet/module_tool/applications/unpacker.rb
- lib/puppet/module_tool/applications/upgrader.rb
- lib/puppet/module_tool/contents_description.rb
- lib/puppet/module_tool/errors/installer.rb
- lib/puppet/module_tool/errors/shared.rb
- lib/puppet/module_tool/errors/uninstaller.rb
- lib/puppet/module_tool/errors/upgrader.rb
- lib/puppet/module_tool/install_directory.rb
- lib/puppet/module_tool/installed_modules.rb
- lib/puppet/module_tool/local_tarball.rb
- lib/puppet/module_tool/metadata.rb
- lib/puppet/module_tool/shared_behaviors.rb
- lib/puppet/module_tool/tar.rb
`lib/puppet/module_tool.rb` and `lib/puppet/module_tool/*` for translation.
> (PUP-7042) Mark strings in module_tool

- lib/puppet/feature/base.rb
`lib/puppet/feature/*` for translation.
> (PUP-7042) Mark strings in feature

- lib/puppet/file_serving/base.rb
- lib/puppet/file_serving/configuration.rb
- lib/puppet/file_serving/configuration/parser.rb
- lib/puppet/file_serving/content.rb
- lib/puppet/file_serving/fileset.rb
- lib/puppet/file_serving/metadata.rb
- lib/puppet/file_serving/mount.rb
- lib/puppet/file_serving/mount/file.rb
- lib/puppet/file_serving/mount/modules.rb
- lib/puppet/file_serving/terminus_selector.rb
- lib/puppet/file_system/file_impl.rb
- lib/puppet/file_system/memory_impl.rb
- lib/puppet/file_system/path_pattern.rb
- lib/puppet/file_system/uniquefile.rb
- lib/puppet/file_system/windows.rb
`lib/puppet/file_server/*` for translation.
> (PUP-7042) Mark strings in file_serving

- acceptance/tests/allow_arbitrary_node_name_fact_for_agent.rb
- acceptance/tests/allow_arbitrary_node_name_for_agent.rb
- acceptance/tests/node/check_woy_cache_works.rb
/cc @rlinehan @jpinsonault @camlow325 
If we like this approach I can apply it to other instances where we need to modify auth.conf.
> (SERVER-1766) Use tk-auth rules when running acceptance under puppetserver

- lib/puppet/graph/simple_graph.rb
`lib/puppet/graph/*` for translation.
> (PUP-7042) Mark strings in graph

- lib/puppet/property/ensure.rb
- lib/puppet/property/list.rb
`lib/puppet/property/*` for translation.
> (PUP-7042) Mark strings in property

- lib/puppet/reference/indirection.rb
- lib/puppet/reference/metaparameter.rb
- lib/puppet/reference/providers.rb
- lib/puppet/reference/type.rb
`lib/puppet/reference/*` for translation.
> (PUP-7042) Mark strings in reference

- lib/puppet/settings/array_setting.rb
- lib/puppet/settings/autosign_setting.rb
- lib/puppet/settings/boolean_setting.rb
- lib/puppet/settings/config_file.rb
- lib/puppet/settings/duration_setting.rb
- lib/puppet/settings/enum_setting.rb
- lib/puppet/settings/environment_conf.rb
- lib/puppet/settings/file_setting.rb
- lib/puppet/settings/priority_setting.rb
- lib/puppet/settings/server_list_setting.rb
- lib/puppet/settings/symbolic_enum_setting.rb
- lib/puppet/settings/terminus_setting.rb
- lib/puppet/settings/ttl_setting.rb
`lib/puppet/settings/*` for translation.
> (PUP-7042) Mark strings in settings

- lib/puppet/ssl/base.rb
- lib/puppet/ssl/certificate_authority.rb
- lib/puppet/ssl/certificate_authority/interface.rb
- lib/puppet/ssl/certificate_factory.rb
- lib/puppet/ssl/certificate_request.rb
- lib/puppet/ssl/certificate_request_attributes.rb
- lib/puppet/ssl/certificate_revocation_list.rb
- lib/puppet/ssl/host.rb
- lib/puppet/ssl/inventory.rb
- lib/puppet/ssl/key.rb
- lib/puppet/ssl/oids.rb
`lib/puppet/ssl/*` for translation.
> (PUP-7042) Mark strings in ssl

- lib/puppet/functions.rb
- lib/puppet/functions/binary_file.rb
- lib/puppet/functions/defined.rb
- lib/puppet/functions/dig.rb
- lib/puppet/functions/hiera_include.rb
- lib/puppet/functions/hocon_data.rb
- lib/puppet/functions/json_data.rb
- lib/puppet/functions/match.rb
- lib/puppet/functions/require.rb
- lib/puppet/functions/slice.rb
- lib/puppet/functions/strftime.rb
`lib/puppet/functions.rb` and `lib/puppet/functions/*` for translation.
> (PUP-7042) Mark strings in functions

- lib/puppet/syntax_checkers/base64.rb
- lib/puppet/syntax_checkers/json.rb
`lib/puppet/syntax_checker/*` for translation.
> (PUP-7042) Mark strings in syntax_checker

- acceptance/config/aio/options.rb
Puppet's acceptance options did not define `puppetserver-config` causing
the beaker `modify_tk_auth` helper to execute `cat`, which hangs beaker.
This commit adds an option for puppetserver-config and converts several
of the options to match what puppetserver uses in their acceptance
setup. Note beaker options can be resolved using either symbol or
string:
(byebug) @options['use-service']
true
(byebug) @options[:'use-service']
true
(byebug) @options['puppetservice']
"puppetserver"
(byebug) @options[:'puppetservice']
"puppetserver"
(byebug) @options['puppetserver-config']
"/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf"
(byebug) @options[:'puppetserver-config']
"/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf"
(byebug) @options['puppetserver-confdir'] …
> (maint) Define puppetserver-config

- .gemspec
- The version of net-ssh Puppet previously consumed was ~> 2.1
but this version conflicts with Beaker and can cause gem installs,
particularly for module testing, to fail.
Beaker 3 moved to net-ssh 3.3.0beta1 to resolve some Unicode
related issues (see BKR-40 for further detail). When net-ssh 4
became available, Beaker 3.11.0 and higher began consuming it to
resolve other Bundler workflow problems.
net-ssh usage is limited to `puppet device` support and should be
safe to generally bump to a newer version, especially one that
resolves known UTF-8 issues.
- To allow for Puppet to run with any version of Beaker, allow
net-ssh 3 and 4 versions to be used by adjusting the .gemspec
accordingly.
To continue to allow the Puppet gem to be tested against Ruby
1.9.3, exclude net-ssh for Ruby < 2 …
> (PUP-7425) Update required version of net-ssh

- lib/puppet/application/face_base.rb
- lib/puppet/application/lookup.rb
- lib/puppet/application/master.rb
- lib/puppet/module_tool/applications/builder.rb
- lib/puppet/network/formats.rb
- spec/unit/application/face_base_spec.rb
- spec/unit/application/master_spec.rb
- spec/unit/network/formats_spec.rb
* Add missing tests for the console format
* Use JSON instead of PSON to pretty print
* Use JSON instead of PSON when rendering console output for face-based applications
> (PUP-7256) Use JSON to render console format

- api/schemas/catalog.json
- lib/puppet/defaults.rb
- lib/puppet/pops/serialization/object.rb
- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/resource.rb
- lib/puppet/resource/catalog.rb
- spec/integration/application/apply_spec.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/pops/serialization/serialization_spec.rb
- spec/unit/resource/catalog_spec.rb
This PR changes the way resource parameters with rich data values
are stored in the catalog. Instead of using a special 'ext_parameters'
entry, the value is stored as a two element hash containing a special
key in the normal 'parameters' entry. The special key is
'\_\_pcore_type\_\_' and its value is the name of the data type of the
value that is associated with the second key 'value' in the same hash.
Any client that reads this catalog and is aware of the special rich
data key, will deserialize the value correctly. Clients that are
unaware of the rich data will just see a hash.
The value will be the string representation of the original value
unless the original is an Array, Hash, or a Pcore Object, in which
case Pcore serialization will serialize the value into an array.
> (PUP-7427) Store rich data as normal parameter of type Hash

- acceptance/tests/allow_arbitrary_node_name_fact_for_agent.rb
tk-auth will generate an error if multiple rules have the same name.
> (maint) Ensure tk-auth rule name uniquness

- lib/puppet/parser/scope.rb
- spec/unit/parser/scope_spec.rb
This commit fixes a bug in the ephemeral local scope of a
`Puppet::Parser::Scope` that caused key declared with an undef value to
become invisible. Instead of returning such a value, the lookup
traversal continued to the parent scope. The value of found in the
parent scope was then returned.
> (PUP-7436) Fix bug causing ephemeral undef not to override parent scope

- lib/puppet/util/monkey_patches.rb
- spec/unit/util/monkey_patches_spec.rb
IO.binwrite has been available since ruby 1.9.3, and since we only
support 1.9.3 and up, there is no reason to carry this monkey patch
anymore.
This commit only removes the monkey patch, but not the tests, so that we
can execute the tests against ruby's version of IO.binwrite, and make
sure we don't get different behavior when the monkey patch is removed.
<hr>
Remove the related tests for the previously removed IO.binwrite monkey
patch.
<hr>
Note to reviewer, feel free to squash these commits. They are separate to demonstrate that the tests continue to pass with the monkey patch removed.
> (PUP-5974) Remove binwrite monkey patch

- lib/puppet/type/exec.rb
Switching to "true/false" at the end was confusing, so let's stick to strict
exit code descriptions.
When this PR is merged, please resolve [DOCUMENT-666](https://tickets.puppetlabs.com/browse/DOCUMENT-666). 😈
> (docs) Use consistent terminology in exec's unless/onlyif parameters

- lib/puppet/generate/models/type/type.rb
- lib/puppet/generate/templates/type/pcore.erb
- lib/puppet/pops/resource/resource_type_impl.rb
- lib/puppet/pops/types/string_converter.rb
- spec/integration/parser/pcore_resource_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
This PR fixes a bug in how the title pattern array for a Pcore
ResourceImpl was constructed. Before the fix, all entries for a specific
pattern were incorrectly wrapped in one single array. After the fix,
each entry is wrapped in an array of its own.
> (PUP-7465) Ensure that multiple entries can be used for a title_pattern

- lib/puppet/parser/compiler.rb
- lib/puppet/parser/environment_compiler.rb
- lib/puppet/parser/resource.rb
- spec/unit/parser/compiler_spec.rb
- spec/unit/parser/resource_spec.rb
This commit moves the evaluation of resource defaults so that it happens
before the evaluation of generators and collections. In addition, the
`add_defaults` method will now also set a tag if the name of the
parameter that receives a default value is `:tag`
> (PUP-25) Ensure that resource defaults are evaluated before collections

- lib/puppet/type.rb
This block removed in this commit iterates over all of the properties of the
type, checks if the given provider supports the property, and returns an array
of all the supported property names.  Except we don't do anything with the
result.  Before commit 53241a91, which was a maint commit to remove superfluous
variables we never used, the result of this block was assigned to the variable
`all_properties` - which was never used. The commit removed the variable, but
not the associated block.  I believe the intention was to filter out properties
that weren't supported by the provider before we called `newattr` on them,
except `newattr` already does this filtering, and provides helpful debug output
that a provider doesn't support a property so we're not managing it. Hence we
remove it here to …
> (PUP-7473) remove dead code in Puppet::Type::instances

- lib/puppet/pops.rb
- lib/puppet/pops/adapters.rb
- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/pops/lookup/data_provider.rb
- lib/puppet/pops/types/p_meta_type.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/p_sem_ver_range_type.rb
- lib/puppet/pops/types/p_timespan_type.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/functions/new_spec.rb
- spec/unit/pops/evaluator/basic_expressions_spec.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
- spec/unit/pops/types/iterable_spec.rb
- spec/unit/pops/types/type_acceptor_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_factory_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
- spec/unit/pops/types/types_spec.rb
This PR changes the Pcore `Data` type so that it is limited to the types that can be expressed in native JSON. This is done by first introducing a `ScalarData`, a subset of `Scalar` that is limited to the JSON scalars `String`, `Integer`, `Float`, and `Boolean`, and then having `Data` use that instead of `Scalar`. A `Hash` must have keys of `String` type to be assignable to `Data`.
An unparameterized `Hash` or `Array` will now use `Any` for the contained key and value types.
The PR also introduces a `RichData` type as a variant of all types except `Runtime`. The contained `Hash` is keyed by a `RichDataKey` which is a variant of `String` and `Numeric`
The `Puppet::LookupKey` is changed into an alias for `RichDataKey` and the `Puppet::LookupValue` is changed into an alias for `RichData`.
> (PUP-6994) Limit Pcore Data type to native JSON and introduce RichData type.

- acceptance/tests/agent/agent_parses_json_catalog.rb
Confirm that the agent can parse a JSON catalog and that the catalog request prefers JSON to PSON.
> (PUP-7357) Verify agent can parse a JSON catalog

- lib/puppet.rb
- lib/puppet/pops/loader/puppet_resource_type_impl_instantiator.rb
Puppet should be able to run without the gettext-setup gem. We had
previously stubbed the basic `_` translation function to avoid errors
when the gem is missing, but later string externalization commits also
made use of the `n_` function for pluralization handling. This commit
adds a stub for that method.
> (PUP-7480) Stub gettext pluralization function

- lib/puppet/pops/parser/lexer2.rb
- spec/unit/pops/parser/lexer2_spec.rb
Before this commit, it was not possible to declare a regexp that ended
with an escaped backslash because there was no logic to determine if
the backslash was preceded by a backslash.
This commit adds code to ensure that only an uneven number of subsequent
backslashes causes an escape of the token that follows.
> (PUP-7475) Fix problem with multiple backslashes in regexp literal

- lib/puppet/parser/compiler.rb
- lib/puppet/parser/environment_compiler.rb
- spec/unit/parser/resource_spec.rb
The fix in PUP-25, where the assignment of resource parameter default
values was moved to take place before resource generators was evaluated,
resulted in that no defaults were assigned to the generated resources.
This commit ensures that resources created during the evaluation of
generators will get their parameter defaults assigned.
> (PUP-7484) Ensure that generated resources get defaults assigned

- lib/puppet/parser/relationship.rb
- lib/puppet/pops/adapters.rb
- lib/puppet/pops/evaluator/relationship_operator.rb
- spec/integration/parser/compiler_spec.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
This makes chains or relationships close a gap in a chain of relationships. 
It used to break the chain.
Thus:
`[File[a], File[b]] -> [ ] ~> [File[aa], File[bb]]`
results in
```
a ~> aa
a ~> bb
b ~> aa
b ~> bb
```
This works for both explicitly empty sets, and for collections returning empty sets. Note that the gap is closed with the rightmost operator with a non-empty right set.
> (PUP-996) Make relationship with empty middle set work

- lib/puppet/parser/compiler.rb
- lib/puppet/parser/environment_compiler.rb
- lib/puppet/parser/resource.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- spec/unit/parser/compiler_spec.rb
- spec/unit/parser/resource_spec.rb
In PUP-25, an attempt was made to add another phase to the compiler that
was responsible for setting default values. That was not sufficient since
new resources were created after the fact.
The PR for PUP-7484 that went in prior to this one attempted to fix this
by setting resource defaults on all resources created after the phase
where defaults had been set. This wasn't good enough either, since in
some cases, resources are created during evaluate_main phase.
This commit uses a simpler and more straight forward approach. Defaults
are now assigned in the Puppet::Parser::Resource#initialize method. The
method has an additional and optional argument that enables this behavior
to be turned off (needed when creating resources for the sake of
overriding parameter defaults).
> (PUP-7484) Move resource defaults initialization to initializer

- lib/puppet/indirector/catalog/compiler.rb
- spec/unit/indirector/catalog/compiler_spec.rb
Accept JSON facts in catalog requests and continue to accept PSON from
older agents.
Note puppet has a long standing bug of double-escaping PSON facts. We
won't make the same mistake when sending facts as JSON.
> (PUP-7257) Accept JSON facts in catalog request

- api/docs/http_api_index.md
- api/schemas/error.json
- lib/puppet/network/http/error.rb
- spec/unit/indirector/rest_spec.rb
- spec/unit/network/http/error_spec.rb
- spec/unit/network/http/handler_spec.rb
Previously, our REST error responses contained a `stacktrace` element,
and in 4.x this was changed to a deprecation warning so that the server
did not leak sensitive information to the caller.
This commit removes the `stacktrace` element from the response, and
related schema and API docs. Note the `stacktrace` element was optional
according to our schema, so this should not be backwards incompatible.
> (PUP-7070) Remove stacktrace from HTTP error responses

- Gemfile
- lib/puppet.rb
This commit switches to using `GettextSetup.candidate_locales` instead
of calling out to the Locale gem directly to detect the locale.
Internally gettext-setup uses the locale gem anyway, but the wrapper
methods provide additional sorting and fallback features. This also
allows us to remove our dependency on Locale gem.
> (maint) Update locale detection to use gettext-setup wrapper

- lib/puppet/pops/types/string_converter.rb
- spec/unit/pops/types/string_converter_spec.rb
This commit adds some well needed tests for the `StringConverter` method
`string_PRuntimeType`. It also removes some dead code from that method.
> (PUP-7469) Add tests for runtime string conversion

- lib/puppet/etc.rb
- spec/unit/etc_spec.rb
Prior to this commit we errantly assumed all values from Etc were either
strings or arrays of strings. This was incorrect - Etc can return Fixnums as
well (and possibly others). Because we didn't handle this case, we dropped
these values when creating our new structs. This commit updates handling to
assign any existing non-String or Array values to their corresponding
fields in the new struct.
> (PUP-7498) copy all struct values from Etc

- ext/project_data.yaml
- ext/windows/service/daemon.rb
- lib/puppet/feature/eventlog.rb
- lib/puppet/util/log.rb
- lib/puppet/util/log/destinations.rb
- lib/puppet/util/windows.rb
- lib/puppet/util/windows/eventlog.rb
- spec/unit/util/log/destinations_spec.rb
- spec/unit/util/log_spec.rb
- spec/unit/util/windows/eventlog_spec.rb
This re-opens https://github.com/puppetlabs/puppet/pull/5509, which was reverted due to CI failures when ruby returned a binary string that originated in Encoding::Windows_31J that we attempted to report (see the last comments in PUP-5756).
This PR adds two new commits on top of the previous PR, one that improves our handling of conversion of BINARY strings in Puppet::Util::CharacterEncoding, and a second to leverage this in our EventLog reporting. A different approach would be to update the base Log class, but given CharacterEncoding hasn't been out in the wild yet I'm a little wary of patching everything to use it - one logging class felt like a reasonable test given this is where we saw the original error.
(PUP-5756) (PUP-7021) better handling of BINARY string conversion
Prior to this …
> (PUP-5756) remove dependency on eventlog

- lib/puppet/network/http/connection.rb
- lib/puppet/ssl/validator/default_validator.rb
Ruby 2.4 introduced a change to OpenSSL that adds a step to
certificate preverification that checks that the hostname matches what
is in the certificate. While this is not enabled by default for most use
cases, any use of `set_params` to configure OpenSSL will enable it.
In the past, the hostname was verified in a post-connection verification
step and produced a specific error message. Now it simply emits a generic
SSL error. Since we still want to give a more informative error message,
this commit changes our error handling to explicitly check for a hostname
mismatch when we receive an SSL error and emit our custom descriptive
message. Note that in Ruby 2.4, this duplicates work already done by Ruby,
but it allows us to be consistent with our error reporting.
> (PUP-7503) Fix hostname mismatch error reporting with Ruby 2.4

- lib/puppet.rb
`Gem.loaded_specs['gettext_setup']` doesn't work with Bundler's standalone binstubs, which intentionally avoids a dependency on RubyGems and, instead, manipulates Ruby's `$LOAD_PATH` directly. As such, Puppet 4 doesn't currently work using Bundler's standalone binstubs (Puppet 3, however, works fine):
```
/etc/puppet/vendor/bundle/ruby/2.1.0/gems/puppet-4.10.0/lib/puppet.rb:76:in `singleton class': undefined method `version' for nil:NilClass (NoMethodError)
from /etc/puppet/vendor/bundle/ruby/2.1.0/gems/puppet-4.10.0/lib/puppet.rb:55:in `<module:Puppet>'
from /etc/puppet/vendor/bundle/ruby/2.1.0/gems/puppet-4.10.0/lib/puppet.rb:49:in `<top (required)>'
from /usr/local/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from …
```
> (PUP-7470) Use a feature check instead of inspecting `Gem.loaded_specs['gettext-setup']`

- acceptance/config/git/options.rb
- acceptance/setup/git/pre-suite/000_EnvSetup.rb
- acceptance/setup/git/pre-suite/010_TestSetup.rb
Depends on #5779 
- This builds on top of changes that were necessary to make a
Bundler workflow behave properly with a Gemfile that references
the Puppet source as a gem via git repo / SHA - see PUP-7425
for details on that problem
- With changes to host images so that the Git package is installed
rather than using the problematic Cygwin git, passing Cygwin
style paths like /opt/puppet-git-repos now are considered to be
regular style Windows paths. This would result in puppet-win32-ruby
being cloned to c:\opt\puppet-git-repos rather than the path that
Cygwin maps /opt/puppet-git-repos to, which would cause issue with
later steps inside Cygwin.
- Also fixed a few issues with the Gemfile approach:
* Bundler supports binstubs, but they use Cygwin style paths
inside the shebang.  While this …
> (PUP-7009) Fix Windows ci:test:git

- lib/puppet/resource.rb
- spec/unit/resource/catalog_spec.rb
Before this, an :undef symbol nested in an Array or Hash used as a
resource's parameter value would serialize the Ruby `:undef` symbol.
The support for rich data checks if the value is compliant with Json an
if not transforms the entire Array or Hash into a String.
This commit modifies the "to_pson" such that an `:undef` value is
transformed to `nil` (which can be represented in JSON). Prior to this
commit, only Array's where scanned for values in need of transformation,
now also Hashes are transformed.
> (PUP-7464) Make json serialization handle :undef Symbol

- lib/puppet/pops/lookup/interpolation.rb
- spec/unit/pops/lookup/interpolation_spec.rb
This commit fixes a problem that caused a resolved "%{alias('key')}" to
be subject to interpolation once again after the alias had been resolve
which meant that sometimes, an alias would return a different value than
the key that it was an alias for.
> (PUP-7492) Prevent that an interpolated alias interpolates again

- lib/puppet/pops/adapters.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/loaders.rb
- spec/unit/pops/loaders/loaders_spec.rb
Prior to this PR, a global function or type that was not declared so that it was available to the auto-loader, would not be reachable from a module. This PR changes this so that such a function becomes known to the public environment loader.
> (PUP-7485) Ensure that global functions and types are publicly available

- acceptance/tests/resource/exec/should_accept_large_output.rb
- lib/puppet/util/execution.rb
- spec/unit/util/execution_spec.rb
Under selinux, when Puppet is invoked by another process with reduced
privileges, any sub-programs invoked by Puppet will not inherit Puppet's
selinux priveleges. This specifically causes silent failures when
invoking applications that don't normally have the ability to write
files - such as iptables-save or hostname - because Puppet redirects
their output to a temporary file.
Use pipes instead of a temporary file to capture the output of
subprocesses.
> (PUP-6675) Use pipes instead of temporary files for Puppet exec

- acceptance/lib/puppet/acceptance/rpm_util.rb
- acceptance/setup/git/pre-suite/000_EnvSetup.rb
- On 5/3/2017 version 7.43.0-5.fc25 of python-pycurl was released to
address issue https://bugzilla.redhat.com/show_bug.cgi?id=1446850
```
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (nss)
```
- Puppet performs some package tests with yum and dnf providers by
installing / using createrepo.  Createrepo requires python and a
number of python dependencies, including the python-pycurl bindings
for curl.  These bindings depend on the curl package.
Unfortunately on Fedora 25, the baseline curl package installed on
images is curl-7.50.3-1.fc25.x86_64. This curl package in
conjunction with the newer python-pycurl 7.43.0-5.fc25 will
generate an error when calling createrepo:
```
ImportError: pycurl: libcurl link-time version (7.50.3) is …
```
> (PUP-7516) Fix Fedora25 createrepo failures

- lib/puppet/parser/scope.rb
- spec/integration/parser/compiler_spec.rb
This makes the qualified variable $settings::all_local contain all the
settings individually found as a variable in the $settings namespace.
> (PUP-6692) Make $settings::all_local contain all "server settings"

- lib/puppet/configurer.rb
Once upon a time Puppet::Configurer#apply_catalog would retrieve a catalog if
not supplied, but this is no longer the case. Update the code comment to
reflect reality because its confusing.
> (maint) correct apply_catalog code comment

- api/docs/http_catalog.md
- api/docs/http_report.md
- api/schemas/report.json
- lib/puppet/agent.rb
- lib/puppet/configurer.rb
- lib/puppet/transaction/report.rb
- spec/unit/agent_spec.rb
- spec/unit/configurer_spec.rb
- spec/unit/transaction/report_spec.rb
This allows the job_id to be set when the agent is run directly. This
will be used to allow pxp_module_puppet to set job_id and
transaction_uuid for agent runs it initiates.
> (PUP-7149) Add job_id to catalog compilation and reports

- acceptance/lib/puppet/acceptance/rpm_util.rb
- acceptance/setup/git/pre-suite/000_EnvSetup.rb
- An assumption was made in 2a8ee90
that all versions of yum and dnf have a --best option during
install.
It turns out this isn't accuracte, so yum / dnf install cannot be
used to both install and upgrade.
Separate install / upgrade into two discrete options
- Furthermore, state tracking in RpmUtils for upgraded packages was
being managed across all agents instead of on an agent by agent
basis.
- Note that depending on `yum install` or `yum upgrade` actions the
yum cache may be considered current, so that when a new repo is
added to /etc/yum.repos.d that it may not actually be queried
despite having new content.
- Some gem install tests require rubygem-rdoc
- Added note about why ci:test:git won't work on RHEL6
Fixes #5852
> (PUP-7156) Fix Puppet::Acceptance::RpmUtils#setup

- .gemspec
- lib/puppet.rb
- lib/puppet/pops/types/string_converter.rb
The following fails on some buggy versions of rubygems in ruby 1.9.3[1]:
irb(main):001:0> Gem::Version.new(RUBY_VERSION)
RuntimeError: can't modify frozen String
As a result, puppet will not run when installed as a gem, until rubygems
is updated.
This commits `dup`s the version string as is done elsewhere[2].
[1] https://github.com/bundler/bundler/issues/3187
[2] https://github.com/puppetlabs/modulesync_configs/commit/be386b44b329e95dc8732155e76bee4353e61216
> (PUP-7523) Dup RUBY_VERSION in Gem::Version

- lib/puppet.rb
If gettext-setup's config file can't be found, it fails to initialize,
causing `method undefined` errors for `_` and `n_`. This commit moves
the check for locale files into the same block that checks for
gettext-setup, and stubs the methods if either one can't be found.
> (maint) Stub gettext methods when locale files can't be found

- lib/puppet/provider/package/rpm.rb
- spec/unit/provider/package/rpm_spec.rb
`rpmvercmp` handles only the leading tilde.
So,  the following test fails.
```
it { expect(provider.rpmvercmp("~", "~~")).to eq(1) }
```
A tilde must sort before everything else.
https://github.com/rpm-software-management/rpm/issues/214
> (PUP-7529) Handling of non-leading tildes in rpmvercmp

- lib/puppet/module_tool/skeleton/templates/generator/Gemfile
- lib/puppet/module_tool/skeleton/templates/generator/Rakefile
Ensure that puppetlab_spec_helper 1.2.0 or later is used which will run
metadata-json-lint as part of the validate rake task.
> (PUP-7017) Simplify metadata linting in generated modules.

- lib/puppet/util/monkey_patches.rb
Previously, we appended "!SSLv2" to the SSLContext
DEFAULT_PARAMS[:ciphers] to ensure that puppet never uses SSLv2, either
from our http client or when using open-uri. However, ruby 2.4 only
defines the `:ciphers` array if using openssl < 1.1.0[1]. As a result,
puppet as a gem running on newer systems would hard fail.
Check existence of array before trying to append to it.
[1] https://github.com/ruby/ruby/commit/c9dc016#diff-8406e11e4a42f9de6badcd0f6a6c4262R33
> (PUP-7383) Skip cipher monkey patch on ruby 2.4+

- lib/puppet/agent.rb
- lib/puppet/util/at_fork.rb
- lib/puppet/util/at_fork/noop.rb
- lib/puppet/util/at_fork/solaris.rb
- spec/unit/util/at_fork_spec.rb
Before this commit, it was not possible to restart/stop a puppet agent service on Solaris from an agent run executed by that very service without killing the agent run along with the service.
This was because services on Solaris run in so called contracts - a kind of process groups - and during a service restart/stop all processes in the contract are killed. Under normal circumstances the contract is inherited during fork system call so the child process is a member of the same contract as its parent process. This was the case of the puppet run executed by the puppet agent service on Solaris too, and that is why the puppet run could not restart/stop the puppet agent service without killing itself.
So in this commit we simply make sure the agent run is executed in a different contract than …
> (PUP-7110) Execute agent run in separate contract

- lib/puppet/provider/yumrepo/inifile.rb
Previously if a yumrepo inifile's permissions were not 644, puppet would
log a global info message:
Info: changing mode of /etc/yum.repos.d/puppet-agent.repo from 600
to 644
This commit passes the `resource` instance to the `store` method so that
the info message is generated relative to that context. The resulting
message looks like:
Info: Yumrepo[IUS](provider=inifile): changing mode of
/etc/yum.repos.d/puppet-agent.repo from 600 to 644
> (PUP-1723) Include context when logging yumrepo chmod

- lib/puppet/application/face_base.rb
The exception raised when the wrong number of arguments is supplied to a face
command has an incorrect externalization that references an undefined variable,
`s`. This was a carry-over from a previous form that we replaced when it was
pluralized.
> (PUP-7576) fix face_base arity check

- lib/puppet/pops/lookup/module_data_provider.rb
- spec/unit/functions/lookup_spec.rb
A v3 hiera.yaml in the root of a module directory should be a warning,
not an error. It should be roughly equivalent to not having a hiera.yaml
file there at all. This is to allow customers who currently have
hiera.yaml files in modules to install new versions of Puppet without
having to first refactor all their modules and CI systems.
> (PUP-7554) Don't error on v3 hiera.yaml in module

- lib/puppet/reference/configuration.rb
I tried to fix this earlier in commit f9df9c4a2, but apparently my brain
glitched out and I didn't use the correct setting name. This fixes the fix.
NB for reviewers: To see the result of this, run `puppet doc -r configuration`, pipe it to the pager of your choice, and scroll down to the `hiera_config` setting.
> (docs) Fix the hiera_config default value fix in configuration reference

- lib/puppet/parser/functions/create_resources.rb
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/semantic_error.rb
- lib/puppet/pops/validation/checker4_0.rb
- lib/puppet/pops/validation/validator_factory_4_0.rb
- spec/unit/parser/functions/create_resources_spec.rb
- spec/unit/pops/validator/validator_spec.rb
This adds warning/error under the control of --strict for resource stye class inclusion and `create_resources` when an attempt is made to use `@class` or `@@class` as neither virtual nor exported works with classes.
> (PUP-1606) Deprecate virtual class

- acceptance/tests/reports/corrective_change_new_resource.rb
- acceptance/tests/reports/corrective_change_outside_puppet.rb
- acceptance/tests/reports/corrective_change_via_puppet.rb
- acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb
These tests break the Image Acceptance Test suite, so are being tagged
so that they can be excluded pending further investigation as part of
ticket PUP-7521
This was labelelled IMAGES-555 but Travis is unable to accept this as PR
prefix.
This replaces #5860
> (PUP-7572) Tag Tests breaking Image Acceptance

- lib/puppet/provider.rb
- lib/puppet/provider/package/rpm.rb
- lib/puppet/util/execution.rb
- spec/unit/provider/package/rpm_spec.rb
- spec/unit/util/execution_spec.rb
Previously if `execfail` method failed to execute the command, it would
try to access the `backtrace` method on the exception class passed into
the method instead of the backtrace of the rescued exception.
This commit marks the execfail method as deprecated, since it's
confusing more than anything, and modifies the method to rescue the
exception and re-raise the rescued exception message and backtrace. It
also adds tests for the execfail method as previously there were none.
> (PUP-6517) Raise output and backtrace of rescued exception

- acceptance/tests/node/check_woy_cache_works.rb
The write_only_yaml cache test needs to explicitly set the node terminus as the default value is changing in Puppet 5.
> (PUP-6060) Manually set node_cache_terminus for woy test

- acceptance/setup/git/pre-suite/000_EnvSetup.rb
Now that Ruby 2.4 builds have been added to puppet-win32-ruby, this
commit updates puppet to use Ruby 2.4 when running acceptance tests on
Windows via ci:test:git.
Note that some tests are still failing when run this way. These failures
are being investigated separately.
> (PUP-7528) Update Windows ci:test:git to Ruby 2.4

- lib/puppet/application/lookup.rb
- lib/puppet/application/master.rb
- lib/puppet/defaults.rb
- lib/puppet/indirector/node/write_only_yaml.rb
- spec/unit/application/master_spec.rb
- spec/unit/indirector/node/write_only_yaml_spec.rb
(PUP-6060) stop setting node_cache_terminus
This PR stops overriding the default `node_cache_terminus` for lookup and master applications to `write_only_yaml` and removes the setting of Puppet::Node's indirection cache_class. In the case of the master application, with this, Puppet::Node's indirection won't cache by default and so won't use the write_only_yaml cache. Per PUP-6060, with the advent of PuppetDB, workflows using lists of nodes are better off querying it than these yaml files on the master, and since this was a `write_only` cache we were always querying the node terminus for nodes anyway. With respect to the lookup application, while we set the `node_cache_terminus` setting, we never set to the `Puppet::Node` indirection cache_class to its value, which meant it was never set …
> (PUP-6060) set node cache terminus to nil

- .gemspec
- Gemfile
- Move the hocon gem dependency from Gemfile to .gemspec, allowing
for ci:test:git with some Hiera tests to work properly on platforms
like Fedora 25.
> (PUP-7525) Move Hocon to runtime dependency

- lib/puppet/pops/serialization/serializer.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/serialization/serialization_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
This PR changes how subclasses of `Array` and `Hash` are handled by the Puppet type system. A derived class that includes the `Puppet::Pops::Types::PuppetObject` module is considered a `Object` type. A derived class that doesn't include that module will be considered a `Runtime` type.
> (PUP-7587) Puppet Type System should treat Hash and Array subclasses as objects

- lib/puppet/indirector/node/yaml.rb
- lib/puppet/node.rb
- lib/puppet/resource.rb
- lib/puppet/resource/status.rb
- lib/puppet/transaction/event.rb
- lib/puppet/transaction/report.rb
- lib/puppet/util/log.rb
- lib/puppet/util/metric.rb
- lib/puppet/util/psych_support.rb
- lib/puppet/util/tag_set.rb
- spec/unit/node_spec.rb
- spec/unit/resource/status_spec.rb
- spec/unit/resource_spec.rb
- spec/unit/transaction/event_spec.rb
- spec/unit/transaction/report_spec.rb
- spec/unit/util/log/destinations_spec.rb
- spec/unit/util/log_spec.rb
- spec/unit/util/metric_spec.rb
This PR unifies how several Puppet structures, defined in Ruby, interact with the YAML/Psych processor. The objective is to make the code insensitive to ruby versions and also to, to the extent possible, make the data serialized with JSON the same as the data serialized with YAML. One key factor in that effort is to get rid of the YAML tags that causes the YAML.load to directly create object instances.
This PR gets rid of such tags but retains them at the top level. The tags are still needed there for two reasons.
- Puppets own yaml indirections rely on this tag when deserializing.
- Other clients, like the MCO PuppetAgentMgr also relies on such tags.
> (PUP-7381) Consistent use of YAML

- acceptance/tests/agent/agent_disable_lockfile.rb
- lib/puppet/agent/disabler.rb
- lib/puppet/agent/locker.rb
- lib/puppet/application/master.rb
- lib/puppet/defaults.rb
- lib/puppet/functions/hiera_include.rb
- lib/puppet/network/http/request.rb
- lib/puppet/parser/ast/node.rb
- lib/puppet/parser/functions/hiera_include.rb
- lib/puppet/pops/issues.rb
- locales/puppet.pot
- spec/unit/application/master_spec.rb
Resolving old tech-debts: Renaming links.puppetlabs.com to links.puppet.com
> PUP-6164: Tech-debt: links.puppetlabs.com -> links.puppet.com

- lib/puppet/defaults.rb
(PUP-2551) Updates to simplify the certname case warning as well as the attached documentation.
[puppethack]
> (PUP-2551) Simplify lowercase certname warning

- ext/project_data.yaml
- lib/puppet/util/plist.rb
- tasks/cfpropertylist.rake
Supercedes #5186 
- 2.3.5 is necessary for Ruby 2.4 compatibility
- 2.3.3 addresses a serious bug in parsing large blocks of XML
and adds support for the plain ASCII format to puppet/util/plist
Note that the gem dependency is set to ~> 2.2 for now to increase
Facter compatibility. Facter 2.0.1 through 2.4.6 depend on ~> 2.2.6
which would conflict with Puppet were Puppet to specify ~> 2.3.5.
When Facter 2.5.0 is finally released for compatibility with gem
workflows and the Puppet 5 gem, it will have its compatiblity set
to ~> 2.2 as well, which will allow it to continue to work with
older versions of Puppet, even if the more desirable 2.3.5 is not
installed.
This change will not change any shipping agent packages, which define
dependencies elsewhere - but it will impact any source installs …
> (PUP-6596) Bump CFPropertyList to 2.3.5 

- lib/puppet/indirector/indirection.rb
The comment said this method prepares a request, which is not true. In fact,
this method never prepared a request - it was added in 2008 in f9881edd, but
even then it only selected the terminus and checked authorization. This commit
corrects the message and adds param/return doc strings so at least followers can
tell at a glance what's happening here.
> (docs) correct code comment for Indirection#prepare

- acceptance/tests/resource/group/should_modify_gid.rb
- acceptance/tests/resource/user/utf8_user_comments.rb
- lib/puppet/parameter.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/p_runtime_type.rb
- lib/puppet/pops/types/string_converter.rb
- lib/puppet/pops/types/type_formatter.rb
- spec/unit/parameter_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/pops/types/types_spec.rb
- spec/unit/resource_spec.rb
- spec/unit/type/user_spec.rb
The `Parameter#format_value_for_display` method had many issues. Strings
containing quotes would be emitted without escaping the quotes. All
values would be quoted (including numbers, booleans, and objects). The
output, allegedly "formatted fo display to a human" did not include
newlines and indentation. Output was sorted alphabetically although
Puppet specifies hashes as ordered.
This commit replaces the body of the method with a call to the
`StringConverter` class which is designed to address all described
issues.
> (PUP-7155) Make Parameter#format_value_for_display use StringConverter

- lib/puppet/pops/issues.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/validator/validator_spec.rb
When PUP-1600 was merged, the fact that the AST on master uses strings
for enums instead of symbols. This led to warning/error about attempts
to virtualize a class for perfectly valid code.
This went undetected because of a missing unit tests that tested that
the check put in place was not triggered by valid code. A test is now
added.
> (PUP-7590) Fix merge of PUP-1600 - symbols not used in AST

- acceptance/tests/resource/user/utf8_user_comments.rb
The AIX providers have not yet been made unicode-aware,
so this test is not valid on that platform.
> (PUP-7592) Disable unicode user comment test on AIX

- acceptance/setup/aio/pre-suite/010_Install.rb
This commit adds the ability to specify SERVER_VERSION=latest when running
puppet tests to test against server latest packages from nightlies.
Sanity checks are added to ensure that if SERVER_VERSION or SHA are set to
latest, download URLs are set correctly to pull from nightlies
> (PUP-7591) Add the ability to test against puppetserver latest

- lib/puppet/indirector/indirection.rb
- spec/unit/indirector/indirection_spec.rb
The last class in Puppet that defined `:select_terminus` was removed in 40ee670
in Puppet 2.7.18, but this check has remained in Indirection.rb ever since. The
method it is in is defined as api private, and it's now just cruft. Remove it
because its superfluous. A github search didn't show code that actually defined
this method, except for repos that vendored an old version of puppet.
> (PUP-7413) remove check for `:select_terminus` in indirection

- lib/puppet/pops/lookup/environment_data_provider.rb
- lib/puppet/pops/lookup/module_data_provider.rb
When a hiera.yaml file version 3 is found at the environment root or
module root Puppet will print a warning, indicating the file will not be
used. Prior to this commit it was not clear exactly which file the
warning pertained to.
This commit adds the specific file to the warning, making it clear what
file is causing the warning to be raised.
Given hiera.yaml v3 files at global, environment, and module, this is the difference in warning output.
Old output:
```
[root@master puppetlabs]# puppet apply -e 'include doozer'
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
(in /etc/puppetlabs/puppet/hiera.yaml)
Warning: hiera.yaml version 3 found at the environment root was ignored
(file & line not available)
Warning: …
```
> (maint) Improve hiera.yaml v3 warnings

- lib/puppet/defaults.rb
Pretty small change, but makes it a little more specific.
> (docs)(DOC-2736): Correct wording for clarification.

- lib/puppet/type/file/mode.rb
When this is merged, please resolve [DOCUMENT-661](https://tickets.puppetlabs.com/browse/DOCUMENT-661).
My source for the thing about 0644 for new files is this:
``` ruby
def write(property = nil)
else
umask = mode ? 000 : 022
Puppet::Util.withumask(umask) { ::File.open(self[:path], 'wb', mode_int ) { |f| property.write(f) if property } }
end
end
```
> (docs) Document behavior when file mode is omitted

- lib/puppet/provider/package/yum.rb
- spec/shared_examples/rhel_package_provider.rb
In some versions of CentOS/RHEL, yum check-update fails when `--enablerepo` preceeds` --disablerepo` This patch changes the order of install_options to prevent that failure.
> (PUP-6656) Reorder install_options for package resource

- lib/puppet/type/file/selcontext.rb
- lib/puppet/util/selinux.rb
- spec/unit/type/file/selinux_spec.rb
SELinux category names have two forms: an internal 'numeric' form, and
a human-readable name. Several SELinux commands rely on a service
called `mcstransd` to convert between them. When that service is not
functioning correctly, things will break.
Instead of using `mcstransd`, Puppet now queries the list of
translations itself and uses them to normalize all internal operations
on the numeric form.
> (PUP-7073) Normalize selinux category names

- spec/spec_helper.rb
Previously the spec_helper would configure rspec to output all to STDOUT due to
issues with the win32_console gem.  However as that gem was removed in Puppet 4,
it is no longer required.  This commit removes the redundant rspec configuration.
> (PUP-7596) Remove rspec configuration for win32_console

- acceptance/tests/resource/scheduled_task/should_create.rb
- acceptance/tests/resource/scheduled_task/should_modify.rb
- acceptance/tests/resource/user/should_modify_when_not_managing_home.rb
- acceptance/tests/resource/user/should_modify_while_managing_home.rb
puppet resource now emits double quotes for strings containing
backslashes, which must also be escaped. Update the acceptance tests to
match the new output.
> (PUP-7155) Expect double quoted strings

- lib/puppet/util/tagging.rb
- spec/unit/util/tagging_spec.rb
- The regex for tags was originally /^\w[-\w:]*$/ in a Luke commit
from 10 years ago f98be4a7198326b26f1072c401b3e337f340db40
- Over the years it has received updates to modernize it and has
shuffled around.
- 0badfce72bafc767bf3099718c63324f51108996 changed it from
/^\w[-\w:.]*$/
to
/^[0-9A-Za-z_][0-9A-Za-z_:.-]*$/
for performance reasons.
- The concat module depends on tags, and as such requires that tags
can contain other valid content.  The regex here is too
restrictive for that purpose and should be returned to its
original intent - word characters.
However, it now needs to be updated to accept word characters in
any language.
- This now allows for the follow manifest to not cause an error:
puppet apply -e 'notify { "hi": tag => "_メインディレクトリ_醸造所"  }'
> (PUP-7579) Allow tags to contain Unicode words

- acceptance/tests/resource/user/should_modify_when_not_managing_home.rb
- acceptance/tests/resource/user/should_modify_while_managing_home.rb
Due to earlier commits for PUP-7155, the home directory is double quoted
on Windows, but single quoted on Linux, due to Windows using a backslash
path separator. Update the test so it accepts both single or double
quotes.
> (PUP-7155) Allow single or double quoted home dir

- acceptance/tests/resource/ssh_authorized_key/create.rb
- acceptance/tests/resource/ssh_authorized_key/destroy.rb
- acceptance/tests/resource/ssh_authorized_key/modify.rb
New version of beaker exposed an oversight in the tests that
the user would be root, this is not the case on Cisco Nexus
> (PUP-7599) Fix authorized keys acceptance tests

- lib/puppet/network/format.rb
- lib/puppet/network/formats.rb
- lib/puppet/network/http/compression.rb
- lib/puppet/network/http/handler.rb
- lib/puppet/network/http/rack/rest.rb
- lib/puppet/network/http/response.rb
- lib/puppet/network/http/webrick/rest.rb
- spec/unit/network/format_spec.rb
- spec/unit/network/formats_spec.rb
- spec/unit/network/http/compression_spec.rb
- spec/unit/network/http/handler_spec.rb
- spec/unit/network/http/response_spec.rb
This PR marks text-based formats (json, text/plain) as supporting a `charset` parameter.
If the response body is a string and the serialization format supports charset, then Puppet will encode the body in that charset (if it isn't already), and include the `charset` parameter in the `Content-Type` header. In a future PR, Puppet's HTTP client will use that information to decode the response body, such as when the response is compressed.
The `charset` parameter will be omitted is the response body is a file or if the `Content-Type` is a binary format (`application/octet-stream`, `msgpack`), `pson`, or `yaml`.
We don't include it with `pson` because old agent's don't know about `charset`. We don't include it with `yaml` because it's not a network serialization format.
> (PUP-7261) Include `charset` parameter in the Content-Type

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/pops/lookup/lookup_spec.rb
Puppet 4.9+ currently converts hiera hash elements into strings unconditiionally. YAML.load_file() will deserialize say an Integer to a ruby Fixnum, but the function symkeys_to_string converts every key to a string, regardless of whether it is a symbol.
> (PUP-7594) Hiera hash keys are being converted to strings recursively.

- acceptance/tests/resource/scheduled_task/should_create.rb
- acceptance/tests/resource/scheduled_task/should_modify.rb
- acceptance/tests/resource/user/should_modify_when_not_managing_home.rb
- acceptance/tests/resource/user/should_modify_while_managing_home.rb
- lib/puppet/pops/types/string_converter.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/pops/types/types_spec.rb
Prior to this commit, the StringFormatter would use double quotes for
all strings that contained control-, non-ascii-, dollar, or backslash
characters. Double quoting is however only needed for strings that
contain control- or non-ascii characters.
This commit changes how the detection is made so that single quotes are
used whenever possible.
> (PUP-7603) Make StringFormatter use single quotes more diligently

- acceptance/tests/external_ca_support/fixtures/auth.conf
- acceptance/tests/external_ca_support/jetty_external_root_ca.rb
This commit updates the
`acceptance/tests/external_ca_support/jetty_external_root_ca.rb` test
to disable the puppetserver CA service rather than using the `ca = false`
setting in the `puppet.conf` file. The `auth.conf` file is also updated to
used the HOCON syntax and proper location for use with puppetserver.
[skip ci]
> (PUP-3486) Disable puppetserver CA service for test

- lib/puppet/graph/simple_graph.rb
- lib/puppet/relationship.rb
- spec/unit/graph/simple_graph_spec.rb
This commit adds the `#encode_with` support provided by the
`Puppet::Util::PsychSupport` module to the `Puppet::Graph::SimpleGraph`
class and thereby also to its subclass  `Puppet::Resource::Catalog`.
This PR has been tested against puppetdb at 4a5092d (current HEAD on master)
> (PUP-7381) Ensure that SimpleGraph includes Puppet::Util::PsychSupport

- lib/puppet/graph/simple_graph.rb
- lib/puppet/node.rb
- lib/puppet/parser/resource.rb
- lib/puppet/parser/resource/param.rb
- lib/puppet/parser/yaml_trimmer.rb
- lib/puppet/resource.rb
- lib/puppet/resource/status.rb
- lib/puppet/transaction/event.rb
- lib/puppet/transaction/report.rb
- spec/unit/node_spec.rb
- spec/unit/resource/status_spec.rb
- spec/unit/resource_spec.rb
- spec/unit/transaction/event_spec.rb
- spec/unit/transaction/report_spec.rb
- spec/unit/util/log_spec.rb
- spec/unit/util/metric_spec.rb
This commit removes the `#to_yaml_properties` method everywhere in the
Puppet code-base and adds an include of `Puppet::Util::PsychSupport`
where needed.
Some tests that only asserted the returned value from the removed
method was also removed. Other tests were rewritten so that they use
the keys of the hash returned from the `#to_data_hash` methods instead.
> (PUP-7583) Remove to_yaml_properties

- ext/rack/config.ru
- lib/puppet/defaults.rb
- lib/puppet/util/feature.rb
- man/man5/puppet.conf.5
The `always_cache_features` setting has been deprecated in favor of
`always_retry_plugins` for some time. This commit removes it.
> (PUP-7133) Remove deprecated `always_cache_features` setting

- lib/puppet/functions/eyaml_lookup_key.rb
- spec/unit/functions/lookup_spec.rb
Prior to this commit, the configuration of the eyaml backend was only
performed once per entry. That didn't work when several different
configurations were used, since the config is stored statically in an
Options class. This commit ensures that the configuration is instead
performed each time an encrypted entry is decrypted.
> (PUP-7543) Ensure that the eyaml_lookup_key gets configured on each call

- lib/puppet/pops/lookup/lookup_key.rb
- lib/puppet/pops/lookup/sub_lookup.rb
- spec/unit/pops/lookup/lookup_spec.rb
Prior to this commit, Hiera would consider an unquoted integer in a
dotted key to be an index in an array. This is now changed so that an
unquoted integer key can be used for navigating a hash that uses integer
keys.
> (PUP-7612) Allow dotted key with integers to navigate integer hash keys

- lib/puppet/pops/merge_strategy.rb
- spec/unit/functions/lookup_spec.rb
This commit changes the merge logic so that even a single entry is
subjected to a merge strategy. The change is needed to ensure that an
array containing duplicates is made unique when the unique merge
strategy is used and that this happens regardless of if it is merged
with other arrays or not.
> (PUP-7608) Ensure that a single array is "merged" during lookup

- lib/puppet/functions.rb
- lib/puppet/functions/call.rb
- spec/unit/functions/call_spec.rb
> (PUP-7174) Add 'call' to the Puppet built in language functions

- acceptance/tests/ticket_3360_allow_duplicate_csr_with_option_set.rb
The ticket_3360_allow_duplicate_csr_with_option_set.rb test contains a
couple of steps which sign certs via the puppet cert cli.  If the test
were run with the `autosign` setting in the puppet.conf set to `true`,
the sign steps could "fail" because they end up being no-ops since CSRs
are signed immediately as they are submitted.  This commit sets
`autosign` to `false` while the test is running in order to ensure that
the CSRs have not already been signed before the cli sign steps in the
test are run.
> (MAINT) Explicitly configure autosign to false for dup-csr test

- lib/puppet.rb
Because the config file for locale tooling is a relative path, in some
situations the Windows path is a valid path on Unix systems, even though
it does not point to the right location. This causes Puppet to look for
the locales config file in the wrong place and fail. This commit adds a
check, so we only try to use the Windows path on Windows, even if it is
valid elsewhere.
> (PUP-7617) Only use Windows locale path on Windows

- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/indirector/node/exec.rb
- lib/puppet/indirector/node/ldap.rb
- lib/puppet/indirector/node/plain.rb
- lib/puppet/node.rb
- spec/unit/indirector/catalog/compiler_spec.rb
- spec/unit/indirector/node/exec_spec.rb
- spec/unit/indirector/node/ldap_spec.rb
- spec/unit/indirector/node/plain_spec.rb
- spec/unit/node_spec.rb
(PUP-7198)(PUP-3438) use request facts for classification
Prior to this PR, the catalog compiler terminus would extract the facts from a given compilation request, save them, and then not use them when requesting classification for a node. Instead the node terminus would look up the facts for any given request. However, because fact submission can be asynchronous, it was possible that the facts saved by the compiler terminus would not ultimately be the ones used by the node terminus when retrieving classification - possibly instead retrieving stale/outdated facts for a node despite the correct facts having been submitted with the original compilation request. This race condition is most evident in environments using exported resurces with puppetdb that have not deployed (to every compile …
> (PUP-7198) Use facts from compilation request to retrieve node

- acceptance/tests/modules/build/build_agent.rb
This commit adds a setup step to the `modules/build/build_agent.rb`
acceptance test to ensure that the test directory does not exist
prior to the execution of the test.
> (PUP-7621) Ensure test directory is removed

- ext/project_data.yaml
0a9ba3e (PUP-6958) added locales to the gem file list, but not `files`,
so it's missing from the published Puppet tarballs.
> (maint) Ship locales/ in Puppet tarballs

- lib/puppet/configurer/fact_handler.rb
- lib/puppet/transaction/report.rb
- spec/unit/configurer/fact_handler_spec.rb
- spec/unit/node/facts_spec.rb
- spec/unit/resource/status_spec.rb
- spec/unit/transaction/event_spec.rb
- spec/unit/transaction/report_spec.rb
- spec/unit/util/log_spec.rb
- spec/unit/util/metric_spec.rb
Submit facts and reports as json by default. Fallback to pson if `preferred_serialization_format=pson`.
> (PUP-7487) Default facts and reports to JSON

- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/functions/hiera.rb
- lib/puppet/functions/hiera_array.rb
- lib/puppet/functions/hiera_hash.rb
- lib/puppet/functions/hiera_include.rb
- lib/puppet/functions/hocon_data.rb
- lib/puppet/functions/json_data.rb
- lib/puppet/functions/yaml_data.rb
This updates the hiera_xxx functions to clearly show that they are deprecated. They now also contain links to hiera 5 documentation instead of the old hiera 3.
This PR also contains an update of the hiera 5 data functions as they had no documentation at all earlier. Now they have a brief explanation what the function is about plus a link to the on-line documentation. (Without this users looking at the function reference will not understand what those functions are).
> (PUP-7515) update hiera functions with deprecation info

- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/serialization/to_data_converter.rb
- spec/unit/pops/serialization/to_from_hr_spec.rb
This commit fixes a typo (is_a instead of is_a?) in the `ToDataConverter`
class and adds test to cover some areas of the `ToDataConverter` /
`FromDataConverter` code that was not tested.
A new `Issue` is also added to improve the message for the case when a hash
key must be converted to a `String`.
> (PUP-7382) Fix typo in ToDataConverter and add more tests

- acceptance/tests/resource/user/utf8_user_comments.rb
- lib/puppet/pops/types/string_converter.rb
- spec/unit/pops/types/string_converter_spec.rb
- spec/unit/type/user_spec.rb
This commit changes the StringFormatter's '%p' representation of a
String so that it does not expand characters in the range above 0x7f
into unicode escapes.
> (PUP-7155) Avoid unnecessary unicode escapes in formatted strings

- lib/puppet/module.rb
- spec/unit/module_spec.rb
When running various puppet commands and there are modules installed
with faulty metadata, a user can be swamped with (in context) irrelevant
warnings.
This changes the output of warning when a metadata.json file cannot be
parsed such that:
* If --strict=off there will be no warning
* If --strict=off and --debug is on, then there is debug output
These continue to work as before:
* If --strict=warning, a warning is issued
* If --strict=error, an error is issued and the command stops
> (PUP-7615) Make squelching of faulty metadata.json possible

- acceptance/tests/reports/submission.rb
- lib/puppet/configurer/fact_handler.rb
- lib/puppet/file_serving/metadata.rb
- lib/puppet/forge.rb
- lib/puppet/forge/cache.rb
- lib/puppet/forge/repository.rb
- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/indirector/request.rb
- lib/puppet/network/http/rack/rest.rb
- lib/puppet/resource/capability_finder.rb
- lib/puppet/type/file/source.rb
- lib/puppet/util.rb
- lib/puppet/util/rdoc/generators/puppet_generator.rb
- spec/integration/type/file_spec.rb
- spec/unit/configurer/fact_handler_spec.rb
- spec/unit/file_serving/metadata_spec.rb
- spec/unit/forge/repository_spec.rb
- spec/unit/indirector/catalog/compiler_spec.rb
- spec/unit/indirector/request_spec.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
- spec/unit/network/http/rack/rest_spec.rb
- spec/unit/type/file_spec.rb
- spec/unit/util_spec.rb
- URI is obsolete and has some undesirable behaviors:
- URI.escape returns strings in US-ASCII instead of UTF-8
- URI.parse returns strings in their source encoding instead of
UTF-8
- CGI behaves correctly with UTF-8, but returns more characters
encoded, which might mess with URI.parse
> (PUP-1890) Change URI escaping to support UTF-8

- lib/puppet/indirector/file_server.rb
- spec/integration/indirector/file_content/file_server_spec.rb
- spec/integration/indirector/file_metadata/file_server_spec.rb
- spec/unit/indirector/file_server_spec.rb
The use of security directives in fileserver.conf mount points has been
deprecated for multiple releases in favor of the use of the auth.conf file.
This commit is a step toward complete removal of support for these
directives.
With this commit, requests will be denied access to a mount point at the
fileserver indirector layer, with a corresponding error message logged, if any
non-global allow (allow *) directives are present in the mount point definition.
Previously, requests made to mount points for which no security directives were
defined would fail authentication at the fileserver indirector layer.  With
this commit, these requests would be granted authentication at the fileserver
indirector layer.
> (PUP-6359) Fail fileserver auth for mounts with non-global allow

- lib/puppet/indirector/rest.rb
- lib/puppet/type/file/source.rb
- spec/unit/indirector/rest_spec.rb
- spec/unit/type/file/source_spec.rb
Previously, puppet sent the format names in the Accept header, e.g. `Accept: pson`. This modifies puppet to send the proper mime type, e.g. `Accept: application/json, text/pson`. It is backwards compatible with all puppet ruby REST endpoints, because it historically has always accepted either the format name or mime type. It is backwards compatible with puppetserver REST endpoints for CA and static_file_content, because puppetserver ignores the `Accept` header and always returns content as `text/plain` or `application/octet-stream` respectively.
> (PUP-3940) Send proper mime types in the Accept header

- spec/unit/configurer/fact_handler_spec.rb
- Previously by attaching facts to a node 'foo', the values being
saved / retrieved were not actually representative of what was
being encoded / compared.
add942b596aed014d2e69ab07078df37df05170b is the source of this
original mistake which was then propagated forward
- Parse the unencoded output to ensure that the original facts are
present
> (PUP-1890) Fix fact_handler_spec assertions

- lib/puppet/property.rb
- lib/puppet/property/list.rb
- lib/puppet/type/cron.rb
- lib/puppet/type/file/group.rb
- lib/puppet/type/file/mode.rb
- lib/puppet/type/file/owner.rb
- lib/puppet/type/mailalias.rb
- lib/puppet/type/package.rb
- lib/puppet/type/scheduled_task.rb
- lib/puppet/type/ssh_authorized_key.rb
- spec/integration/type/file_spec.rb
- spec/unit/property/list_spec.rb
- spec/unit/transaction/resource_harness_spec.rb
- spec/unit/type/file/group_spec.rb
- spec/unit/type/file/mode_spec.rb
- spec/unit/type/file/owner_spec.rb
- spec/unit/type/ssh_authorized_key_spec.rb
Prior to this commit, the method `Property#change_to_s` method would
call `#is_to_s` and `#should_to_s` to get a "pretty printed" string and
then pass that string to `#format_value_for_display` to pretty print it
again. This is now changed so that the `#format_value_for_display` is
instead called from the default implementations of `#is_to_s` and
`#should_to_s`.
> (PUP-7616) Fix broken Puppet::Property#xxx_to_s methods

- lib/puppet/feature/base.rb
- lib/puppet/util/windows/api_types.rb
- lib/puppet/util/windows/file.rb
- CreateSymbolicLinkW was intermittently returning non-zero on
different tests hosts, under similar circumstances.
Some discussion in:
https://github.com/puppetlabs/puppetlabs_spec_helper/pull/192
Note the original PR was wrong and updated in:
https://github.com/puppetlabs/puppetlabs_spec_helper/commit/bb46874846eeefbb0f03939bb66129bfa4a02236
- The signature for CreateSymbolicLinkW should return a BOOLEAN
(BYTE - aka unsigned char) value not a BOOL (4 byte / 32-bit
signed int).
Based on the presence of random data in the incorrectly sized
return value, the code may behave incorrectly.
- Fix the problem by sizing the return value correctly
> (PUP-7627) Fix CreateSymbolicLinkW BOOL return type

- lib/hiera/puppet_function.rb
- lib/puppet/functions/strftime.rb
- lib/puppet/indirector/node/write_only_yaml.rb
- lib/puppet/parser/ast/resource.rb
- lib/puppet/parser/ast/resource_instance.rb
- lib/puppet/parser/ast/resourceparam.rb
- lib/puppet/parser/functions/contain.rb
- lib/puppet/parser/functions/include.rb
- lib/puppet/parser/functions/require.rb
- lib/puppet/parser/scope.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/types.rb
- spec/unit/indirector/node/write_only_yaml_spec.rb
This cleans up calls to warn_once with the intent of logging a deprecation. The correct form of category is `'deprecations'` (a String, in plural).
> (PUP-7611) Cannot squelch all deprecation warnings

- lib/puppet/pops/model/model_label_provider.rb
This commit changes the Puppet::Pops::Model::ModelLabelProvider so that
it returns the string 'Anonymous Class' when passed a class that has
no name.
> (PUP-5912) Ensure that label for an anonymous class is a string, not nil

- lib/puppet/graph/relationship_graph.rb
- lib/puppet/graph/simple_graph.rb
- lib/puppet/resource/status.rb
- lib/puppet/transaction.rb
- spec/unit/functions/contain_spec.rb
- spec/unit/graph/simple_graph_spec.rb
- spec/unit/resource/status_spec.rb
- spec/unit/transaction_spec.rb
Prior to this commit, when a dependency cycle was detected in the resource
graph, the transaction would fail immediately with an error describing the
cycle. However, the resources in question were not considered problematic in
anyway. This commit updates transaction evaluation to consider resources
involved in a cycle as failed:
- Rather than fail when detecting resource dependency cycles, we return this
information back up to the caller to decide what to do with. Erroring was an
unexpected side-effect anyway given the name of the method is
`report_cycles_in_graph`. Still emit an error message though, as this is
thematically inline with "reporting cycles".
- Add a new handler defined in the context of Puppet::Transaction that is
invoked in the context of relationship graph traversal with …
> (PUP-3042) Report resources in a cycle as failed

- lib/puppet/type/file/group.rb
- lib/puppet/type/file/mode.rb
- lib/puppet/type/file/owner.rb
Because the file mode attribute must be a quoted string, we should display it that way when referencing it in the docs.
> (PUP-6395)(docs) Change references to mode to be quoted strings

- conf/auth.conf
- conf/fileserver.conf
This commit adds some documentation to the default fileserver.conf file
which indicates that, per PUP-6359, the use of auth directives is no
longer supported in the file.  The commit expands the example showing
how to implement auth directives in the auth.conf file instead of
fileserver.conf to include info about the format that Puppet Server's
HOCON-based auth.conf file uses.
> (PUP-7555) Doc removal of auth support in default fileserver.conf file

- lib/puppet/pops/serialization/from_data_converter.rb
- lib/puppet/pops/serialization/to_data_converter.rb
- lib/puppet/transaction/event.rb
- spec/unit/pops/serialization/to_from_hr_spec.rb
Before this commit, an attempt to send a report containing custom rich
data types (Objects) to a server would result in an "No implementation
mapping found for Puppet Type xxx" error. Since there's really no reason
why such types should be internalized in a report, this is now changed
so that it instead keeps the original rich-data hash.
> (PUP-7642) Allow rich-data of unknown type in reports

- lib/puppet/forge.rb
- lib/puppet/forge/repository.rb
- spec/unit/forge/forge_spec.rb
- b182a70 introduced a change to
additionally encode URI parameters for "module_groups" when making
a forge search or fetch request. This decision was made given other
query terms were being escaped in the URI as it was being built.
As it turns out this URI was being passed into the
Puppet::Forge::Repository class get_request_object method which
was also calling uri_encode.
As a result of the Puppet[:module_groups] setting being typically
set to base+pe in PE, queries were being sent to the forge that
included &module_groups=base%252Bpe instead of the correct
&module_groups=base%2Bpe as they were in the past.
- The interesting thing about this change is that it uncovered a
latent problem with how query has been handled in the past.
Any values that required percent encoding in the past …
> (PUP-1890) Fix double encoding forge request URIs

- lib/puppet/indirector/report/rest.rb
- lib/puppet/indirector/rest.rb
- spec/unit/indirector/report/rest_spec.rb
- spec/unit/indirector/rest_spec.rb
~PR https://github.com/puppetlabs/puppet/pull/5923, must be merged first.~
During a normal agent run, if the node response comes from a server whose major version is less than ours, then issue a warning, downgrade to pson, and continue the run. The agent will prefer pson for all future requests for that single run (excluding certs or binary file content). For pull-based requests, e.g. catalog, the agent will list pson first in the `Accept` header. For push-based requests, e.g. report, the agent will send the Content-Type as pson.
```
$ bx puppet agent -t
Warning: Downgrading to PSON for future requests
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
...
Info: Applying configuration version '1496559506'
Notice: Applied catalog in 0.01 …
```
> (PUP-7255) Graceful downgrade or fail when communicating with 4.x masters

- ext/logcheck/puppet
The compiler now emits the environment name when compiling a catalog, so
update the logcheck rule accordingly.
Environment names are restricted to alphanumerics and underscore, so
`.` and `-` are not allowed per
https://docs.puppet.com/puppet/4.10/lang_reserved.html#environments
> (PUP-7625) Add environment to logcheck rule

- conf/hiera.yaml
- ext/hiera/hiera.yaml
- install.rb
This is installed by PA instead of the previous hiera3 format file.
There are 2 files to be installed:
1. Empty (commented) global file in configuration directory
2. Production configuration file in production environment directory
This is #5927 targetted to master
> (PUP-7597) Add Hiera5 default yaml files

- acceptance/tests/direct_puppet/catalog_uuid_correlates_catalogs_with_reports.rb
Previously, the catalog_uuid_correlates_catalogs_with_reports.rb test
expected the value that it finds for the catalog_uuid in a report yaml
file for an agent run would not be surrounded with single quotes.
Starting with Ruby 2.3.2, however, some uuid values may be surrounded
with single quotes.  Quoting around the value is legal for the yaml
generator to do in either case.  This commit changes the test to
optionally allow for quotes around the value so that it will pass
reliably across Ruby versions.
> (PUP-7652) Allow quotes in report yaml uuid value for catalog_uuid test

- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/loader/typed_name.rb
- lib/puppet/pops/loaders.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/serialization/deserializer.rb
- lib/puppet/pops/types/p_type_set_type.rb
- lib/puppet/pops/types/type_set_reference.rb
- spec/unit/pops/loaders/loaders_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/p_type_set_type_spec.rb
Before this commit, if an instance of `Puppet::Pops::Loader::TypedName`
was created from a name that contained upper case letters, those letters
would be preserved. This meant that the responsibility for downcasing
the name was on the caller.
This commit removes the `downcase` from all calls to the `TypedName`
constructor and instead adds a `downcase` inside the `#initialize`
method.
> (PUP-7650) Ensure that Loader::TypedName always uses lower-case

- lib/puppet/transaction.rb
- lib/puppet/transaction/report.rb
- spec/integration/transaction_spec.rb
- spec/unit/transaction/report_spec.rb
- spec/unit/transaction_spec.rb
Previously, if a 'refreshonly' exec failed, this failure was not
propagated into the report because refresh failures are tracked via a
different resource status, `failed_to_restart` as opposed to just
`failed`.
This commit updates the failure check logic in the transaction to
include checks of `failed_to_restart`, as well as a
similar update to the way the report status is calculated. A run is now
marked as failed if any of its resources are marked `failed_to_restart`.
> (PUP-2280) Mark runs as failed when refresh events fail

- lib/puppet/util/character_encoding.rb
An early iteration of the scrub method always replaced invalid sequences with
'?'. This was amended to use the unicode escape character when the string is
UTF-8 or UTF-16LE, and only revert to '?' if the string is not in one of those
encodings. However, the doc string for the method was not updated. This commit
corrects it.
> (maint) correct comment in CharacterEncoding::scrub

- lib/puppet/pops/evaluator/runtime3_resource_support.rb
This commit removes two unnecessary calls to #downcase. One is actually
dead code since the downcased value is never used. The other is redundant
since all resolvers of type names will downcase the name.
Downcasing is either performed by `TypedCollection#munge_name` (for
defined resources or host classes), `Puppet::Type#type` (for resource
types), or `Puppet::Pops::Loader::TypedName#initialize` (for generated
resource types).
> (PUP-7650) Remove dead code and unnecessary call to #downcase

- appveyor.yml
- lib/puppet/indirector/file_bucket_file/file.rb
- spec/unit/indirector/file_bucket_file/file_spec.rb
- spec/unit/util/run_mode_spec.rb
- Now that RubyInstaller has produced an installer for Ruby 2.4.1 on
Windows and AppVeyor has integrated it into their workflow per
https://github.com/appveyor/ci/issues/1350 we can move from 2.3 to
2.4 given Puppet 5 will be shipping against 2.4
> (maint) Switch AppVeyor to Ruby 2.4 from 2.3

- lib/puppet/error.rb
- lib/puppet/indirector/catalog/json.rb
- lib/puppet/indirector/json.rb
- lib/puppet/network/format_handler.rb
- lib/puppet/network/http/api/indirected_routes.rb
- lib/puppet/network/http/request.rb
- lib/puppet/settings.rb
- spec/unit/indirector/catalog/json_spec.rb
- spec/unit/indirector/json_spec.rb
- spec/unit/network/format_handler_spec.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
- spec/unit/network/http/request_spec.rb
* Scrub Puppet::Error message strings, so they are always valid encodings.
* Add support for serializing binary catalogs as PSON when read/writing to local JSON files and when serializing in HTTP responses.
* When processing REST `find` and `search` requests, if we fail to serialize to a given format, fallback to the next best format, eventually returning 406 if none are acceptable.
> (PUP-7602) Support binary data in catalogs

- ext/hiera/hiera.yaml
As per post-merge review comment on PR #5972 fix documentation URL to
point to "latest" to avoid link going stale.
> (MAINT) Fix Docs pointer to latest.

- lib/puppet/resource/type_collection.rb
- spec/integration/resource/type_collection_spec.rb
Before this commit, if the `TypeCollection#find_or_load` was called with
uppercase characters in the name, it would make an attempt to first find
a resource using a munged (downcased) name, and then, if the resource
was not found, load the resource using the name without downcasing it.
This commit ensures that both find and load uses a downcased name.
> (PUP-7671) Ensure that TypeCollection uses downcased name for load

- lib/puppet/version.rb
This commit updates Puppet's version to 4.10.4 in anticipation of the
Puppet Agent 1.10.4 release.
> (packaging) Bump version to 4.10.4

- lib/puppet/pops/evaluator/collector_transformer.rb
- lib/puppet/pops/evaluator/collectors/catalog_collector.rb
- lib/puppet/pops/evaluator/collectors/exported_collector.rb
- spec/integration/application/apply_spec.rb
This commit changes the `CollectorTransformer` class so that it
propagates the resource type that it has already loaded down to the
collector that is created. Previously, only the name was passed down
which resulted in a load of a `Puppet::Type` when the collector created
a resource instance.
> (PUP-7674) Ensure that resource collectors uses generated resources

- acceptance/tests/ticket_2280_refresh_fail_should_fail_run.rb
This commit adds an acceptance test to verify that a puppet run fails
when using `--detailed-exitcodes` when a resource triggered by a
refresh fails.
> (PUP-2280) Add test for failed refresh = fail run

- acceptance/lib/puppet/acceptance/environment_utils.rb
Previously, users of the `assert_review` helper passed in an array with
failure strings, the results from a call to the `review_results` helper.
The `assert_review` helper, however, appeared to assume that the
argument was a hash with a key denoting the scenario and value
containing any failures, leading to an 'undef method empty? for
nil:NilClass' error as it processed any failures.
This commit changes the `assert_review` helper to instead treat its
parameter as an array of failure strings, allowing for any failures
found to be listed out properly in an assertion message.
> (MAINT) Fix assert_review environment_utils test helper

- Rakefile
Without this patch applied, build failures caused by commit summaries
that fail to match patterns as specified in `Rakefile` are providing
instructions not in line with actual practice in this project.
The Jira ticket is usually given as PUP-<digits>; doc updates are given
usually as (docs) and occasionally as (docs)(DOC-<digits>).
This patch updates the hint to give instructions in line with the actual
practice in the project.
> (maint) Update comments in commit Rake task

- lib/puppet/agent.rb
- spec/unit/agent_spec.rb
Before this commit, the `Agent#run` method would pass a block to the
`Agent#run_in_fork` that, in case a `StandardError` was raised, would
log the exception and then return the created `Log` instance. Since the
caller of the block expects an exit code, which it passes on in a call
to exit, it would fail with another exception when it instead passed
the returned `Log` instance.
This commit ensures that the block instead returns the integer 1 in case
a `StandardError` is raised.
> (PUP-6256) Ensure that agent run returns exit code instead of log entry

- lib/puppet/face/epp.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/parser/functions/assert_type.rb
- lib/puppet/parser/functions/binary_file.rb
- lib/puppet/parser/functions/break.rb
- lib/puppet/parser/functions/defined.rb
- lib/puppet/parser/functions/dig.rb
- lib/puppet/parser/functions/each.rb
- lib/puppet/parser/functions/epp.rb
- lib/puppet/parser/functions/filter.rb
- lib/puppet/parser/functions/find_file.rb
- lib/puppet/parser/functions/inline_epp.rb
- lib/puppet/parser/functions/lest.rb
- lib/puppet/parser/functions/map.rb
- lib/puppet/parser/functions/match.rb
- lib/puppet/parser/functions/new.rb
- lib/puppet/parser/functions/next.rb
- lib/puppet/parser/functions/reduce.rb
- lib/puppet/parser/functions/return.rb
- lib/puppet/parser/functions/reverse_each.rb
- lib/puppet/parser/functions/slice.rb
- lib/puppet/parser/functions/step.rb
- lib/puppet/parser/functions/strftime.rb
- lib/puppet/parser/functions/then.rb
- lib/puppet/parser/functions/type.rb
- lib/puppet/parser/functions/with.rb
- spec/unit/face/epp_face_spec.rb
Before this commit, the command 'puppet epp' would fail when the epp-
template contained code that required the 4x loader. The reason was that
the compiler was not properly initialized with its overrides. This
commit ensures that the compiler adds the overrides just as it would
when doing a proper compile of a catalog.
> (PUP-7691) Ensure that the 4x loader is present when epp face executes

- lib/puppet/pops/model/ast.rb
- tasks/generate_ast_model.rake
This commit changes the rake task `generate_ast_model` so that it emits
the method
```ruby
def current
self
end
```
for the Puppet::Pops::Model::Program class.
> (PUP-7364) Make generate_ast_model task restore method Program#current

- appveyor.yml
- RubyInstaller is currently shipping 2.4.1-1 to AppVeyor which
contains an OpenSSL bug documented at:
https://bugs.ruby-lang.org/issues/11033
This bug can cause intermittent failures, which due to the
fast fail flag being enabled in AppVeyor, will terminate
all cells.
- To compile under msys2 requires that OpenSSL source package
be installed to c:\msys64\mingw64, which AppVeyor appears to
already have setup correctly.
Otherwise, pacman package manager would be used under msys2
to install the source like:
pacman -S mingw-w64-x86_64-openssl --noconfirm
NOTE: pacman isn't actually in PATH on AppVeyor currently
> (maint) Fix intermittent AppVeyor OpenSSL fails 

- tasks/parallel.rake
- util/rspec_runner
This commit updates the existing `parallel:spec` rake task to accept
arguments to be passed on to RSpec. These will primarily be used in CI
to correctly generate test result log files.
> (PUP-7695) Update `parallel:spec` rake task to pass extra args to RSpec

- lib/puppet/parser/resource.rb
- lib/puppet/pops/evaluator/collector_transformer.rb
- spec/integration/parser/collection_spec.rb
This commit changes the `Puppet::Parser::Resource#set_parameter` so that
it checks if the resource has already been evaluated. If that's the case,
then the behavior is controlled by the setting of `Puppet[:strict]`:
strict=off, the attempt silently sets the parameter although no
re-evaluation of the resource takes place. In essence, the new value is
ignored (same as before this commit).
strict=warning, same as strict=off, but the attempt is also logged as a
warning.
strict=error, compilation fails.
> (PUP-6290) Ignore, warn, or fail when evaluated resources are overridden

- tasks/generate_ast_model.rake
The generate_ast_model rake task requires puppet, which requires facter.
At build-time, we don't always have facter gems available (but we also
don't need the tasks defined in generate_ast_model). To make it possible
to build puppet, we need to not load the generate_ast_model tasks if
facter is not available.
> (PUP-7736) Conditionally require 'puppet'

- acceptance/tests/resource/file/symbolic_modes.rb
The symbolic file and directory mode tests was very slow as it
called puppet apply for each set of file and directory. The new version
calls puppet apply 4 times total. (On CentOS7 the test went from
270 seconds to 24 seconds).
> (PUP-1607) Refacter the symbolic_modes tests to be faster

- acceptance/lib/puppet/acceptance/agent_fqdn_utils.rb
- acceptance/tests/reports/corrective_change_new_resource.rb
- acceptance/tests/reports/corrective_change_outside_puppet.rb
- acceptance/tests/reports/corrective_change_via_puppet.rb
- acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb
On the new Linux Power8 system the "facter fqdn" did not match
the agent.hostname, this caused these tests to fail. This fixes
them to use the real fqdn value whether its the short or long name
(This will also fix other vmpooler systems that have the same issue
with these tests)
While I was working on the tests I also correct some quoting of paths
and code formatting
> (PUP-7684) correct tests to use the real fqdn of the host

- lib/puppet/reports/http.rb
The built-in http report processor is only capable of establishing connections
over HTTPS to URLs which present a certificate issued by the same Puppet CA
that Puppet Server is running under. This patch updates the docs to note this
limitation.
Ref: https://tickets.puppetlabs.com/browse/PUP-5069
Ref: https://tickets.puppetlabs.com/browse/SERVER-1543
> (doc) Note CA requirements for http report processor

- acceptance/README-ec2.md
- acceptance/setup/aio/pre-suite/010_Install.rb
This commit updates the aio install pre-suite to allow installing
an ec2 master dynamically on a el based system without intervention.
Due to the expectations of the nightly puppetserver repo, the nightly
puppet-agent is installed first and then over-written with the
puppet-agent version under test. The specification of a SERVER_VERSION
is also supported.
Documentation has also been added in a `README-ec2.md`
file.
> (PUP-7740) Enable EC2 master install

- lib/puppet/application/lookup.rb
- lib/puppet/pops/merge_strategy.rb
- spec/unit/application/lookup_spec.rb
- spec/unit/functions/lookup_spec.rb
This commit corrects the spelling of the deep merge option
`sort_merged_arrays` (previously spelled "sort_merge_arrays") and adds
tests to assert its function.
> (PUP-7751) Correct misspelled sort_merged_arrays

- lib/puppet/pops/time/timestamp.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
This commit adds default formats to enable parsing of timestamps where
the date and time part are separated by space. It also adds tests to
assert that such timestamps are fully parsed.
An attempt was made to check if a string is fully parsed so that partly
parsed strings would raise an error. Unfortunately, the parser in
`DateTime#strptime` that Puppet currently relies on, does not make this
possible. It parses up to the point where a format is fully satisfied
and then returns the result without detecting trailing garbage.
A test to detect such garbage is added in this commit, but since it
would require a complete rewrite of the parser, it's currently set
to "pending".
> (PUP-7753) Ensure that timestamps using space separator can be parsed.

- acceptance/Gemfile
- acceptance/tests/loader/autoload_from_resource_type_decl.rb
- acceptance/tests/loader/resource_triggers_autoload.rb
This PR includes a merge-up from 4.10.x to 5.0.x following the revert of the accidental merge of 5.0.x into 4.10.x. To avoid bringing the changes from that revert into this branch, I kept everything in this branch, which caused the changes from Eric's autoloader test commit to get lost. I subsequently cherry-picked that commit from 4.10.x onto 5.0.x.
> Merge 4.10.x -> 5.0.x

- lib/puppet/pops/time/timestamp.rb
- spec/unit/functions/new_spec.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
This commit changes the Timestamp#parse method so that it uses the
method `DateTime#_strptime` instead of `DateTime#strptime` internally.
The `_strptime` returns a `Hash` instead of a `DateTime` and this hash
will contain the undocumented field `leftover` in case the parsed string
was not consumed in full. In Puppet, it's desirable to treat such data
as an error since it means that only part of a string represented the
desired `Timestamp`.
Some extra logic was added to process the parse result since it's now
in the form of a `Hash` instead of a `DateTime`. Also, the previous
begin/rescue was no longer needed.since the `_strptime` returns `nil`
instead of raising an ArgumentError for unparsable input.
> (PUP-7757) Raise errors unless Timespan#parse consumes all input

- lib/puppet/vendor/semantic_puppet/lib/semantic_puppet/gem_version.rb
- lib/puppet/vendor/semantic_puppet/lib/semantic_puppet/version.rb
This commit updates the vendored `semantic_puppet` to version 1.0.1
which provides a fix for MODULES-5159.
> (PUP-7747) Update vendored semantic_puppet gem to 1.0.1

- acceptance/setup/aio/pre-suite/010_Install.rb
This commit corrects the logic for puppetserver install during
acceptance tests to install from nightlies when the SERVER_VERSION
is unspecified or set to 'latest'.
> (PUP-7740) Fix acceptance puppetserver install

- acceptance/tests/resource/service/service_enable_linux.rb
This commit adds a conditional to interpret `el` versions greater
than `2016` as sysv system. This is used to accommodate amazon linux
release versions which are based on the release year, but are currently
based on RedHat 6 which does not use systemd for its service management.
> (PUP-7752) amazon rel ver to service test

- lib/puppet/functions/reduce.rb
- lib/puppet/parser/functions/reduce.rb
This adds an example of how to use the `reduce` function to iteratively
update a Hash of Hashes.
> DOCUMENT-692: Add another reduce example

- lib/puppet/provider/package/pip.rb
- spec/unit/provider/package/pip_spec.rb
On Windows:
The package provider for Python's pip fails when Perl's pip is installed
and Perl is first in the PATH, sincle both install a pip command.
This fix specifies a unique command (pip.exe) for Python pip on Windows.
See also:
https://www.penwatch.net/cms/pip_conflict/
https://bugzilla.redhat.com/show_bug.cgi?id=958377
> (PUP-6895) Specify unique command for Python pip on Windows

- acceptance/tests/catalog_with_binary_data.rb
This commit adds an acceptance test to for a catalog containing
binary data. The integrity of the binary data should remain intact
through the process of transmission from the server and application
on the client.
> (PUP-7681) Add test for binary data in catalog

- lib/puppet/provider/nameservice.rb
A regression introduced in PUP-7498 commit e45ae7c where an iteration
was introduced that started with `setpwent` or `setgrent` and then iterated
each entry with the corresponding `getpwent` or `getgrent` until no more
entries were found. A call to `endpwent` or `endgrent` was never made.
In essence, this means that the internal iterator is reset to the start
before each iteration so it should be fine. The problem is that on some
platforms (notably on CentOS 7) the lack of the call to `endpwent` or
`endgrent`, causes a cached iterator to be reused. It is never refreshed
with new values. Consequently, a call to `useradd` would succeed, but the
added user would then not be found.
This commit replaces the initial call to `setpwent` or `setgrent` with
an ensured call to `endpwent` or …
> (PUP-7742) Ensure getpwent and getgrent iterators are properly closed

- spec/unit/indirector/file_bucket_file/file_spec.rb
Previously the unit test failed on big-endian IBM z Sytems, because the
array contains integers in little-endian. Pack using "V" 32-bit
unsigned, VAX (little-endian) byte order, instead of "I" unsigned
int, native endian.
> (PUP-4962) Pack array as little-endian

- acceptance/tests/resource/package/common_package_name_in_different_providers.rb
We can't install the `guid` package from Amazon repos when running in
EC2. Skip the test if the hypervisor is ec2. I could have checked an
`ec2` fact, but this should be quicker.
> (PUP-7774) Skip common package name acceptance in EC2

- lib/puppet/util/execution.rb
- spec/integration/util/execution_spec.rb
- `Puppet::ExecutionFailure` is derived from `Puppet::Error`, which in
future versions of Puppet (5.0.0+) performs additional scrubbing of
passed strings to ensure that they match the output encoding.
In that future case, the behavior of the initializer is subtly
different from the current code:
```ruby
def initialize(message, original=nil)
super(message)
@original = original
end
```
Calling `super` directly in the current code will call `RuntimeError`
within Ruby, which despite the Ruby documentation, will implicitly
call `.to_s` on the second parameter, which is always intended to be
a string.  That means that Ruby allows things like:
```
[1] pry(main)> raise RuntimeError, 2
RuntimeError: 2
[2] pry(main)> raise RuntimeError, ['foo']
RuntimeError: ["foo"]
[3] pry(main)> raise …
```
> (PUP-7772) Ensure string msg in ExecutionFailure

- acceptance/tests/environment/negative/agent_run_should_fail_if_env_unreadable.rb
- acceptance/tests/environment/negative/agent_run_should_fail_if_site_pp_unreadable.rb
This commit adds an acceptance test to ensure that executing a
`puppet agent` run against an unreadable environment does not
succeed without an error.
> (PUP-6241) Acceptance unreadable environment

- lib/puppet/module.rb
- spec/unit/module_spec.rb
This adds to Puppet::Module to "initialize" a module for translations. Each module must be added to FastGettext.translation_repositories, so that translations in the modules code will be available to Puppet. Two methods are added here, one to check if a module has been initialized and another to initialize. To initialize, we are just wrapping GettextSetup.initialize basically.
> (PUP-7518) i18n module loading

- lib/puppet/face/module/search.rb
- lib/puppet/forge.rb
- lib/puppet/module.rb
- lib/puppet/module_tool.rb
- lib/puppet/module_tool/applications/installer.rb
- lib/puppet/module_tool/applications/uninstaller.rb
- lib/puppet/module_tool/applications/upgrader.rb
- lib/puppet/module_tool/shared_behaviors.rb
- lib/puppet/util/logging.rb
- spec/unit/face/module/search_spec.rb
- spec/unit/module_spec.rb
- spec/unit/module_tool_spec.rb
- spec/unit/parser/scope_spec.rb
- spec/unit/util/logging_spec.rb
This commit adds an arity check to be able to call the method
`SemanticPuppet::VersionRange#parse` with one or two arguments from the
`Puppet::Module#parse_range` method.
When the arity is found to be just 1, a check is made if the gem version
of the semantic_puppet gem is < 1.0.0, in which case it is assumed that
the parse method is incapable of creating a range that adheres to strict
semantics. A warning is logged if a request for a strict range is made.
Conversely, if the gem version is >=1.0.0, it is assumed that strict
semantics will be honored and a warning is issued if a request for a
non-strict range is made.
> (PUP-7738) Ensure that Puppet can be used with semantic_puppet gem.

- lib/puppet/version.rb
This updates Puppet's version number for the upcoming 5.0.1
release.
> (packaging) Bump version to 5.0.1

- lib/puppet/version.rb
This commit bumps Puppet's version to 4.10.5 in preparation for the
puppet-agent 1.10.5 release.
> (packaging) Bump version to 4.10.5

- lib/puppet/provider/package/pip.rb
- spec/unit/provider/package/pip_spec.rb
https://tickets.puppetlabs.com/browse/PUP-6405
This pull request adds management of the "core" pip packages. The current special case only handles the pip package while this pull request will take care of all the others.
I would feel better if I receive confirmations about a few topics:
1. Someone double check the unit tests: I am not experienced in Ruby.
1. Make sure version 8.1.0 of pip is really the one that implemented the `freeze --all` option: the jira issue explains more why I am confused about this.
> (PUP-6405) Use `pip freeze --all`

- lib/puppet/parser/resource.rb
- lib/puppet/resource/capability_finder.rb
- spec/unit/resource/capability_finder_spec.rb
When a capability resource is moved from one node to another, either due
to a code change or because an application component is classified to a
different node, the database can contain multiple resource instances
matching the capability ref. This happens when the new node has run
puppet but the old node hasn't. In those cases, we try to decide which
resource to use by repeating our search but limiting it to only
resources with the same code_id as the catalog we're currently
compiling.
When the code_id search doesn't find _any_ matching resources, we were
previously returning `nil` and the Catalog#resource method was raising
an error indicating the capability couldn't be found and may not have
been produced yet. This is misleading, since the problem is actually
that there are _too many_ …
> (PUP-6497) Improve error message with conflicting capability resources

- lib/puppet/provider/package/gem.rb
- spec/unit/provider/package/gem_spec.rb
- spec/unit/provider/package/puppet_gem_spec.rb
Prior to this commit, the 'install_options' attribute was passed to the gem
command after the 'source' attribute, preventing the use of '--clear-sources'
in 'install_options', as '--clear-sources' is positionally dependent.
With this commit, the 'install_options' attribute is passed first.
This was identified and resolved in MODULES-4815.
While the subject of the ticket is 'making the source parameter authoritative',
in MODULES-4815 we decided to maintain backwards compatibility and not imply
'--clear-sources' when the 'source' attribute is specified.
> (PUP-5506) making the source parameter authoritative for gem provider

- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/functions/hiera_spec.rb
Prior to this commit, all global lookups would be affected by the
`data_binding_terminus` setting. This commit ensures that this is no
longer the case when the lookup origins from `hiera`, `hiera_array`,
`hiera_hash`, or `hiera_include` function.
The change is made to ensure backward compatibility with Hiera 3 where
the `hiera_xxx` calls would go directly to the classic Hiera and thus
not be affected by the `data_binding_terminus`.
> (PUP-7802) Make hiera_xxx functions unaffected by data_binding_terminus

- docs/index.md
In `docs/index.md`, update the link to the documentation on how to run
the acceptance tests.
> (maint) Update link to acceptance test docs

- acceptance/tests/environment/negative/agent_run_should_fail_if_env_unreadable.rb
Previously, our tests for an environment bug on JRuby 1.7 would execute
on any Puppet Server instance.
Since we have a regular JRuby 9k version of our Puppet Server jobs this
means this test, which expects a bug that only exists in JRuby 1.7
fails.
This patch updates the acceptance test to skip if Puppet Server is using
JRuby 9k.
> (PUP-6241) Only expect incorrect File exception on JRuby 1.7

- lib/puppet/util/suidmanager.rb
On Macs which are domain-joined, lookups between group ID and name can
fail if the domain isn't accessible at that moment. In these situations,
lookups on files and other objects return a GID for the user that is
already an integer, which is then passed to convert_xid, which tries to
re-lookup that GID and fails, returning an "Invalid group: ###" error.
This PR bails early if the user/group ID is already numeric, and thus
doesn't need to be looked up.
> (PUP-5047) POSIX Exec throws error when group has no name

- lib/puppet/type/file.rb
- spec/unit/type/file_spec.rb
The fix for PUP-6966 introduced a new error, halting file removal if
backup could not be performed. While ultimately this seems like the
correct behavior, we will need to further investigate the implications
of this logic change. For the time being, this commit changes the
error to a warning, allowing the code to proceed to try to remove the
file even if backup has failed.
> (maint) Restore attempting to remove files even if backup fails

- lib/puppet/provider/package/gem.rb
- spec/unit/provider/package/gem_spec.rb
Prior to this patch, the HOME environment variable was stripped
before the gem command was executed by the provider.  Since the
gem command uses the HOME environment variable to locate the
appropriate gemrc file to load, this was causing it to look at
/.gemrc.  Since Puppet runs as root, it is far more reasonable for
a customer to expect to find the gemrc file in /root/.gemrc.  This
patch maintains the previously existing HOME environment variable,
which forces gem to look in /root/.gemrc during puppet runs.
> (PUP-5645) Preserve HOME env variable in gem provider

- lib/puppet/indirector/request.rb
- spec/unit/indirector/request_spec.rb
Previously, when failover was attempted but unsuccessful, the
agent would default to using the `server` setting. This is
incorrect, since that setting might be at its default value,
or be set to the same value as one of the server_list entries.
Instead, we should not attempt to connect to any server if failover
was not successful. This allows the agent to "fail fast", instead of
timing out trying to connect to an incorrect server.
> (PUP-7804) Do not use server setting when failover fails

- lib/puppet/pops/types/string_converter.rb
- spec/unit/pops/types/string_converter_spec.rb
Before this the string converter would pad the given element separator for array and hashes with an extra space when producing the string representation.
This was bad because it made it impossible to have an empty string as a separator.
> (PUP-7760) Remove automatic element separator padding

- lib/puppet/functions/all.rb
- lib/puppet/functions/any.rb
- spec/unit/functions/all_spec.rb
- spec/unit/functions/any_spec.rb
This adds the functions `any()` and `all()` (with functionality comparable to Ruby's `any?` and `all?`.
> (PUP-7678) Add functions any and all

- acceptance/Gemfile
- acceptance/tests/loader/autoload_from_resource_type_decl.rb
Changed the autoload of resource tests to use the behavior of require
statements instead of looking at the puppetserver.log file.
The puppetserver.log file can rotate to a new file when the date
changes which could cause the test to fail
> (PUP-7776) update autoload resource test to not use the masters log

- lib/puppet/util/windows/api_types.rb
- lib/puppet/util/windows/process.rb
- spec/integration/util/windows/process_spec.rb
- spec/unit/util/windows/api_types_spec.rb
- When reading environment variables, request that invalid byte
sequences be replaced with the Unicode replacement character. This
will prevent Puppet from crashing hard when reading the block of
memory representing environment variables and it contains bytes
that are not valid UTF-16LE.
- When iterating over the individual key=value pairs representing
environment variables in get_environment_strings, check the strings
for the Unicode replacement character \uFFFD. If found, then emit
a warning and discard the variable as its not particularly useful
to Puppet.
- Add test demonstrating bad byte sequences embedded in Windows API
response are ignored and that Puppet will emit a warning in this
case.
> (PUP-7821) Handle corrupt windows environment variables

- lib/puppet/provider/package/aix.rb
- spec/unit/provider/package/aix_spec.rb
Previously, the prefetch for the `aix` package provider assumed
that all resources would have a `source` parameter. While this
parameter is required in order to *install* a package, it is
not needed to remove one, so it's possible some package resources
might lack a value.
This fixes the prefetch to skip any empty source values, allowing
prefetch to succeed when some packages do not have a source.
> (PUP-7818) Prefetch AIX packages when not all have sources

- lib/puppet/pops/types/string_converter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/string_converter_spec.rb
The regexp used for checking format specifiers for the string formatter
was not anchored at the end. Also, the regexp was duplicated. It was
specified once in string_formatter.rb and then again in as a parameter
type in types.rb.
This commit adds the anchor and removes the duplification.
> (PUP-7824) Fix bad problem with unanchored end in string format regexp

- lib/puppet/generate/models/type/property.rb
- lib/puppet/parser/ast/leaf.rb
- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/model/model_tree_dumper.rb
- lib/puppet/pops/types/string_converter.rb
- lib/puppet/pops/types/type_calculator.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/types.rb
- spec/unit/parser/ast/leaf_spec.rb
- spec/unit/pops/types/string_converter_spec.rb
This commit adds a new method called `#regexp_to_s_with_delimiters` to
the PRegexpType and ensures that it is used throughout to get consistent
string format of regexps.
> (PUP-7825) Fix problems with regexp string representation

- lib/puppet/parser/functions/new.rb
- lib/puppet/pops/types/p_sem_ver_range_type.rb
- lib/puppet/pops/types/p_timespan_type.rb
- lib/puppet/pops/types/p_timestamp_type.rb
- lib/puppet/pops/types/type_mismatch_describer.rb
- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/evaluator/access_ops_spec.rb
- spec/unit/pops/types/p_timespan_type_spec.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
The `TypeParser` did not check that the parameters used when creating
a `Variant` type were types. Consequently, some variants created
internally in dispatchers used for the function `new` on `Timespan`
and `SemVerRange`, were incorrect. The faulty declarations were also
copied into the corresponding documentation of the `new` method.
Incidentally, the code did work anyway since the type, when created
from the `TypeParser`, will do a `#to_type` on the argument, thus
converting the keyword `default`, or an integer value into it's type.
> (PUP-7829) Ensure that Variant parameters are types

- acceptance/tests/resource/package/yum.rb
The guid package used by the yum package test is not present in the
repos on targeted Amazon Linux instances in EC2. Therefore, this
test should be skipped when being tested in that environment.
> (maint) Skip yum package test on ec2

- lib/puppet/info_service.rb
- lib/puppet/info_service/task_information_service.rb
- lib/puppet/module.rb
- lib/puppet/module/task.rb
- spec/lib/puppet_spec/modules.rb
- spec/unit/info_service_spec.rb
- spec/unit/module_spec.rb
- spec/unit/task_spec.rb
Supercedes #6100
Add a new class to represent tasks contained in modules. There's not much functionality in it yet: it can find valid task files in a module's tasks directory and construct tasks composed of them, where the tasks
can't do anything but tell you their name, their payload files, their metadata file (if they have one), and the module they belong to, all via attribute reader instance methods. There are no other instance methods,
but there are a few public class methods for validating task names and file names.
When modules are created, they check to see if their tasks directory exists. If so, they use the Puppet::Module::Task class to create a Task object for every task that exists in their task directory.
Also adds two new methods to the InformationService module, both of …
> (PUP-7815) Add Task class, TaskInfoService class

- lib/puppet/file_serving/configuration.rb
- lib/puppet/file_serving/configuration/parser.rb
- lib/puppet/file_serving/mount/tasks.rb
- lib/puppet/module.rb
- spec/integration/indirector/file_content/file_server_spec.rb
- spec/integration/indirector/file_metadata/file_server_spec.rb
- spec/unit/file_serving/configuration_spec.rb
- spec/unit/file_serving/mount/modules_spec.rb
- spec/unit/file_serving/mount/tasks_spec.rb
- spec/unit/module_spec.rb
Add a new special file serving mount point to serve task file content.
It works very similarly to the modules mount point, except that it only
finds files in the module's `tasks` directory.
Add the new tasks mount point to the set of default mounts for file
serving.
> (PUP-7840) Add a file serving mount point for tasks.

- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/types/p_object_type_spec.rb
Prior to this commit, the `TypeParser` would raise an exception when it
encountered a `HeredocExpression`. As a consequence, no strings could
be entered as heredoc in a type description.
This commit adds the methods necessary to make the `TypeParser`
understand literal heredoc. Interpolations are not allowed (goes for
both heredoc and double quoted strings).
> (PUP-7768) Enable use of heredoc in a type description

- lib/puppet.rb
- lib/puppet/gettext/config.rb
- lib/puppet/gettext/stubs.rb
- lib/puppet/module.rb
- lib/puppet/vendor/semantic_puppet/lib/semantic_puppet.rb
- spec/spec_helper.rb
- spec/unit/gettext_config_spec.rb
Normally, Puppet loads translations from a binary MO file, to match what
the C++ projects do. However, since we do not check these MO files into
source control, instead building them as part of the agent package build,
they are not available when running from source or when running as a
gem. The only functionality change in this refactor causes Puppet to
load PO files when its gettext config files are found locally, rather
than in the puppet-agent package structure.
Besides that, this commit significantly refactors the way gettext-setup is
initialized to encapsulated the complicated logic around finding config
files and choosing translation file format.
> (PUP-7645) Load translations from PO file when running as a gem

- acceptance/tests/cycle_detection.rb
- acceptance/tests/environment/environment_scenario-bad.rb
- acceptance/tests/ticket_4233_resource_with_a_newline.rb
- acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb
- acceptance/tests/ticket_6928_puppet_master_parse_fails.rb
Currently the puppetserver CI jobs which run the puppet agent tests are failing
When puppetserver runs the puppet tests it uses a beaker config which creates
multiple machines with agent roles. This causes the 'agent' beaker variable to
be a list of hashes instead of a hash. Tests which access the agent array as if
it's a hash throw errors
This commit modifies the offending tests to work under both conditions
> (MAINT) Fix tests for puppetserver pipelines

- lib/puppet/pops/patterns.rb
- spec/unit/functions/epp_spec.rb
The VAR_NAME regular expression caused an infinite left recursion due to
an ambiguity in this regular expression. This manifested itself when the
trailing part of a FQN did not match the trailing part of the regexp.
For example `$foo::bar::WRONG`
This commit changes the regexp so that left recursion is not needed.
> (PUP-7848) Modify var name regexp to avoid infinite recursion

- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/serialization/to_data_converter.rb
- spec/unit/pops/serialization/to_from_hr_spec.rb
Before this commit, the `ToDataConversion` would convert the special
`default` value using rich data semantics even when `rich_data` was
set to false. This commit ensures that a) this only happens when rich
data is enabled, and b) when it happens, a proper warning is logged.
A new issue was added to avoid logging info about the symbol `:default`
and instead mention the "special value default" (the use of the symbol
is an an internal concern of the ruby implementation).
> (PUP-7855) Ensure proper Data conversion the special default value

- lib/puppet/module.rb
With the recent refactor of GettextSetup configuration, a check to make
sure that gem had already been loaded when initializing a module was
also removed. This ensures that we don't try to call the module's
methods before requiring it.
> (PUP-7857) Guard reference to GettextSetup

- lib/puppet/provider/package/yum.rb
- spec/fixtures/unit/provider/package/yum/yum-check-update-plugin-output.txt
- spec/unit/provider/package/yum_spec.rb
The yum plugin API allows for plugins to send output via info or
error messages to stdout. This can break assumptions the yum provider
is making in terms of the output from commands like check-update.
This adds a check to ensure that when parse_updates is called, the
second argument in the tuple matches an RPM version and skips over it
if not. This should help guard against multiple types of bad output.
> (PUP-7813) Ensure yum plugins don't break yum

- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/types.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this commit, only subclasses to `PScalarDataType` were considered
assignable the `ScalarData` type. This commit ensures that all variants
containing assignable types (i.e. `Optional`, `NotUndef`, or `Variant`)
are assignable (with the exception of `NotUndef[Undef]`, which isn't
assignable to anything).
The `Scalar` datatype which experienced the same problem, is also fixed
by this commit.
> (PUP-7862) Ensure variant assignability to Data and RichData

- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/pops/types/types.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/pops/types/type_calculator_spec.rb
This commit adds the `Default` type to the `RichData` variant.
Since `default` now an instance of `RichData` it is also an instance of
an unparameterized `Init` type which called for an adjustment on the
test that checks what default is an instance of.
> (PUP-7863) Make Default part of the RichData variant

- lib/puppet/functions/lookup.rb
- lib/puppet/type.rb
Also fixes missing details on lookup merge option "knockout_prefix"; tiny doc fixes.
> (docs)(DOCUMENT-652) fixes metaparameter log level order

- lib/puppet/application.rb
- lib/puppet/application/agent.rb
- lib/puppet/application/apply.rb
- lib/puppet/application/cert.rb
- lib/puppet/application/describe.rb
- lib/puppet/application/device.rb
- lib/puppet/application/doc.rb
- lib/puppet/application/filebucket.rb
- lib/puppet/application/lookup.rb
- lib/puppet/application/master.rb
- lib/puppet/application/resource.rb
- lib/puppet/face/catalog.rb
- lib/puppet/face/certificate_request.rb
- lib/puppet/face/certificate_revocation_list.rb
- lib/puppet/face/help.rb
- spec/unit/face/help_spec.rb
Some summary texts for subcommands appearing in `puppet help` missed
being translated. For some of these, that was because the string was
embedded in a larger help text (which was not intended for translation)
and extracted on the fly. This commit isolates all of these summary
texts and makes them available via a `summary` method. This allows them
to be marked for translation.
The summary method return an empty string by default. If users of puppet
have created their own applications without summaries, the `help`
command will still attempt to extract the summary text from the help
body.
> (PUP-7858) Isolate and externalize all `puppet help` summary texts

- lib/puppet/pops/issues.rb
Fix 3 error messages that used #{} instead of the preferred %{}
for string interpolation to enable localization
> (PUP-7820) correct error  messages for I18N support

- api/docs/http_file_content.md
- api/docs/http_file_metadata.md
Add descriptions of the new special `tasks` mount point to the API
documentation on the v3 file_content and file_metadata endpoints. The
mount point behaves analagously to the `modules` endpoint, so the
description mirrors that one's.
> (PUP-7840) Document `tasks` file content mount

- lib/puppet/parser/functions/dig.rb
Currently, the dig function's documentation doesn't realllllly explain
what specifically what the function does, or what arguments are
expected, unless you're already familiar with the general concept of a
dig function.
* Clarified that dig expects to be called on a hash or array, as
opposed to the generic term "structure" which, while accurate, is less
informative to the inexperienced.
* Quoted all bare strings being passed to the dig function.
- https://docs.puppet.com/puppet/5.0/style_guide.html#quoting
- Note that leaving the keys unquoted in the original hash is standard practice. Although not explicitly called out in the hash section of the style guide, that style is used in the examples:
- https://docs.puppet.com/puppet/5.0/style_guide.html#arrays-and-hashes
* Explain the …
> Update and clarify `dig` function documention.

- lib/puppet/functions/run_task.rb
This adds a mocking version of run_task where it is possible to simulate
running of a task by giving it an Object instance that has the
attributes simulated_exit_code and simulated_result. All other
attributes are ignored.
The function logs information at notice level.
This behavior will be replaced when there are real Task instances.
> (PUP-7875) Add a mocking version of run_task

- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/functions/regsubst_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
The `TypeMismatchDescriber` contained some less ideal logic that made
attempts to revert the effect or using normalized types or types
extracted from an `Optional` or a `TypeAlias`. This commit removes that
code and adds a parameter to get track of the original instead which
results in a simpler and more reliable solution.
> (PUP-7835) Refactor how TypeMismatchDescriber tracks expected type

- lib/puppet/loaders.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/loader/task_instantiator.rb
- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/task.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/loaders/module_loaders_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/task_spec.rb
This commit adds a loader that finds files under the 'tasks' folder
in a module root directory. The loader will expect to find exactly one
file that matches the expected task name and has an optional or
arbitrary file extension that is different from '.json'. That file may
optionally be accompanied by file that has the same name and a '.json'
extension. The json latter is then the metadata that describes the task
type.
> (PUP-7864) Add Puppet Type Loader for Tasks

- lib/puppet/util/log.rb
- spec/unit/util/log_spec.rb
- Log message objects contain attributes other than the string
message itself, which may be concatenated to form the actual string
to write when the handle method of each instance of
Puppet::Util::Log::Destination is executed.
For instance, the :console destination and :file destination may
concatenate the @source and @message of a Log message.
- While Puppet began coercing log messages to UTF-8 as part of
c47be2d3b3d002f02cbed6edee8dfee119152b46 it didn't also coerce the
source.
In many circumstances, Ruby is happy to concatenate UTF-8 strings
with strings of other encodings that only use 7-bit ASCII characters
that are consistent amongst all encodings.
However, it is also possible under certain circumstances to
generate a @source and @message that are of different encodings
that cannot …
> (PUP-7880) Ensure log message attributes are UTF-8

- lib/puppet/pops/types/puppet_object.rb
- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/task.rb
- spec/unit/pops/loaders/module_loaders_spec.rb
- spec/unit/pops/types/task_spec.rb
This PR fixes several issues with the GenericTask class and adds tests that uses the puppet evaluator to produce and notice the string form of created tasks.
See individual commits for details.
> (PUP-7864) Fix issues with GenericTask and add tests

- lib/puppet/pops/types/task.rb
- spec/unit/pops/types/task_spec.rb
This commit changes the signature of the GenericTask constructor so that
an instance can be creatd without providing any parameters. Prior to
this commit, it was necessary to provide {} as a parameter.
> (PUP-7864) Remove the need to provide {} for empty GenericTasks

- lib/puppet/provider/package/aix.rb
- spec/unit/provider/package/aix_spec.rb
Previously, the latest version of a package in AIX was not
being returned when `ensure => latest` was used. In the calculation
of the latest version of the package, `latest_info` was being assigned
to `nil` rather than the package itself, most likely because the method
was written to handle an Array but the data type is a Hash.
The fix is to assign `latest_info` to the package, rather than the 0th
index of the package.
> (PUP-6364) Fix `ensure => latest` on AIX

- lib/puppet/application/device.rb
Prior to this commit, the help for puppet-device ...
contained language and syntax errors
did not document all of the available device.conf properties
included specific device configuration that should be documented in device.conf
See also: https://github.com/puppetlabs/puppet-docs/pull/756
Refer to (DOC-1967) for more information.
> (DOCS) Update help for puppet-device

- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/types/type_parser_spec.rb
A parameterized `Enum` must only accept parameters of type string
(or identifier, since it's converted to a string) but prior to this
commit it was possible to use arbitrary parameters such as integers if
the string was parsed/evaluated by the internal TypeParser. This commit
adds the check needed to prevent this from happening.
> (PUP-7885) Ensure that Enum data type only accepts string parameters

- acceptance/tests/reports/agent_sends_json_report_for_cached_catalog.rb
This commit adds an acceptance test to ensure that the puppet agent
submits its report as `json` after applying a cached catalog.
> (PUP-7730) Add test of json report for cached catalog

- acceptance/tests/server_returns_pson_when_preferred_serialization_set.rb
This commit adds an acceptance test to ensure that the puppet server
returns the catalog in the expected serialization format base on the
defined value for the `preferred_serialization_format` option.
> (PUP-7729) Add preferred_serialization_format test

- acceptance/lib/puppet/acceptance/mount_utils.rb
AIX 5.3 images have been updated to use jfs2, so we need to update our tests
to use jfs2 when doing tests with mounts
> (PUP-7893) Update aix tests to use jfs2 for mounting on 5.3

- acceptance/tests/aix/aix_package_provider.rb
This commit modifies the test to catch regressions of PUP-7818; users
ought to be able to ensure a package is absent without passing a source
attribute.  PUP-7818 required at least two packages in a manifest to
reproduce.
> Catch regressions of PUP-7818

- .gemspec
Rubygems has some undesirable behavior when doing dependency solving
with versions that are looked up from within a library. This can be seen
when using the rubygems in the puppet-agent package to install r10k, and
then installing a second version of a gem that r10k depends on, such as
minitar.
When more than one version of a dependent gem is installed, rubygems
loads all of the gemspecs and tries to decide which gems to activate.
When loading all of the gemspecs, rubygems encounters the require on
`puppet/version`, which brings us to the second half of our story.
Rubygems monkey patches `Kernel.require` to first search gems for a path
before searching the load path. This means that to find
`puppet/version`, rubygems first looks through all of the gems it knows
about, which means loading …
> (PUP-7889) Begin hard-coding puppet version in gemspec

- lib/puppet/pops/loader/base_loader.rb
- lib/puppet/pops/loader/dependency_loader.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/loader/runtime3_type_loader.rb
- lib/puppet/pops/loader/static_loader.rb
- spec/unit/pops/loaders/loader_spec.rb
This commit adds a `#discover` method to all pcore loaders. This new
method can be used to discover all entities that the loader has access
to. The type of entity to search for must be provided. A filter can
also be provided in the form of a block.
Current limitations:
- All entities that are discovered will be loaded. This has pros and
cons. The pro is that once loaded, the type will be cached in memory.
The con is that loading and keeping all entities in memory might be
resource demanding.
- Resource types are currently not loaded.
A solution for both limitations would be to provide a utility program
that would execute separate from the puppet runtime to maintain an
index of everything that can be loaded.
> (PUP-7890) Add discovery to the Puppet Loader system

- lib/puppet/error.rb
- lib/puppet/parser/functions/inline_template.rb
- lib/puppet/parser/functions/template.rb
- lib/puppet/pops/issues.rb
- spec/unit/parser/functions/inline_template_spec.rb
- spec/unit/parser/functions/template_spec.rb
This adds a feature switch so that `template` and `inline_template` are not supported when running with --tasks turned on.
> (PUP-7909) ERB not supported with task feature

- lib/puppet/error.rb
- lib/puppet/functions/contain.rb
- lib/puppet/functions/include.rb
- lib/puppet/functions/require.rb
- lib/puppet/parser/functions/create_resources.rb
- lib/puppet/parser/functions/inline_template.rb
- lib/puppet/parser/functions/realize.rb
- lib/puppet/parser/functions/tag.rb
- lib/puppet/parser/functions/tagged.rb
- lib/puppet/parser/functions/template.rb
- lib/puppet/pops/issues.rb
- spec/unit/functions/contain_spec.rb
- spec/unit/functions/include_spec.rb
- spec/unit/functions/require_spec.rb
- spec/unit/functions/shared.rb
- spec/unit/parser/functions/create_resources_spec.rb
- spec/unit/parser/functions/inline_template_spec.rb
- spec/unit/parser/functions/realize_spec.rb
- spec/unit/parser/functions/tag_spec.rb
- spec/unit/parser/functions/tagged_spec.rb
- spec/unit/parser/functions/template_spec.rb
This makes all of the functions performing catalog operation illegal when --tasks is on.
THIS PR IS BASED ON PUP-7909 WHICH SHOULD BE MERGED FIRST.
> (PUP-7910) Make catalog functions illegal when tasks are on

- lib/puppet/functions/run_plan.rb
- lib/puppet/functions/run_task.rb
- lib/puppet/pops/issues.rb
- spec/unit/functions/run_plan_spec.rb
This makes it illegal to call run_task and run_plan when --tasks is not on (i.e. when compiling a catalog).
This PR also contains a fix of a spelling error causes the error message for one issue added in PUP-7910 to not appear correctly.
> (PUP-7912) feature switch run task/plan

- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/puppet_object.rb
- lib/puppet/pops/types/ruby_generator.rb
- lib/puppet/pops/types/type_calculator.rb
- spec/unit/functions4_spec.rb
- spec/unit/pops/types/p_object_type_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
This commit adds a check to the `PObjectType#_pcore_init_from_hash`
that prevents a type from being created unless the parent is resolved.
Some tests broke as a consequence of this new check. Those tests were
in error and hence corrected.
> (PUP-7916) Prevent that Object can be parented by an unresolved type

- .travis.yml
All other Travis 2.y Ruby stacks are using Bundler 1.15.4, but 1.9.3 is still
stuck on 1.7.6 for some reason. Bundler 1.7.6 is incompatible with the recent
Rubgems 2.6.13 security release, so this patch updates the Ruby 1.9.3 test
to use Bundler 1.15.4.
> (PUP-7920) Pin bundler to 1.15.4 for Ruby 1.9.3

- lib/puppet/pops/parser/heredoc_support.rb
- spec/unit/pops/parser/lexer2_spec.rb
Before this commit, the regexp that was used to trim off the last
newline (or cr-nl) was not a multi-line regexp and used the '$' (end of
line) which resulted in that all empty lines where removed. This commit
changes the regexp into a multiline that uses \z (end of string), thus
ensuring that only the last occurrence is removed.
> (PUP-7902) Ensure that empty heredoc lines are not trimmed

- lib/puppet/pops/patterns.rb
- spec/unit/functions/epp_spec.rb
- spec/unit/pops/validator/validator_spec.rb
This is yet another fix of the same problem as earlier believed to be
fixed. When input such as $aaaaa::bbbbb::ccccc::UPPER was encountered
the regexp matcher for variable/name ended up taking an enormous amount
of time. The initial regexp triggered this problem on very short
sequences. The updated worked for short sequences, but not for longer
(also took a very long time to complete).
The regexp is now updated with a more complex negative lookahead of '_'
as the problem is to prevent that a segment other than the last starts
with '_'.
Tests are updated to have longer sequences, and also includes the
original reported name.
> (PUP-7848) Fix problem with VAR pattern and longer segments

- lib/puppet/pops/issues.rb
- lib/puppet/pops/validation/checker4_0.rb
- lib/puppet/pops/validation/tasks_checker.rb
- lib/puppet/pops/validation/validator_factory_4_0.rb
- spec/unit/functions/run_plan_spec.rb
- spec/unit/pops/validator/validator_spec.rb
This commit adds a new `TasksChecker` validator and ensures that it
is used instead of the `Checker4_0` validator when the --taskss feature
is enabled.
> PUP-7905) Add a --tasks feature flagged expression validator

- appveyor.yml
- AppVeyor appears to have fixed their OpenSSL issue, as performing
a gem install now seems to be skipped given the message:
```
gem : warning: mingw-w64-x86_64-openssl-1.0.2.k-1 is up to date -- skipping
At line:11 char:3
+   gem install openssl --version '~> 2.0.4' --no-ri --no-rdoc -- --wit ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (warning: mingw-...ate -- skipping:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
```
- Update the code to first perform a version check before attempting
to install
> (maint) AppVeyor Ruby 2.4 openssl gem install fix

- lib/puppet/parser/script_compiler.rb
- lib/puppet/pops/loaders.rb
- spec/integration/parser/script_compiler_spec.rb
- spec/unit/pops/types/task_spec.rb
This commit changes the `ScriptCompiler#evaluate_main` so that it no
longer creates a class with an empty name (a.k.a. 'main').
The method `Environment#perform_initial_import` was moved to the
`Loaders` class and rewritten to no longer create wrappers for the
version 3 AST. Instead, it directly returns an array of Program
instanses.
The `ScriptCompiler#evaluate_main` calls the new method on the `Loaders`
instance to obtain the programs to evaluate. It then evaluates them in
sequence and returns the result of the last evaluation.
The new behavior is tested by the integration test for the
`ScriptCompiler` and also by the `Task` unit test which was rewritten
to use the `ScriptCompiler`.
> (PUP-7908) Remove use of 'main' class for ScriptCompiler

- lib/puppet/functions/run_task.rb
This corrects the documentation of run_task() function wrt running on
local host and that an empty host list results in no action (should not
log).
(The current simple simulation does however log if list is empty for
testing purposes).
> (PUP-7875) Correct the documentation of run_task localhost, no hosts

- lib/puppet/parser/ast/pops_bridge.rb
- lib/puppet/pops/loaders.rb
This commit moves the instantiation of 4.x definitions from the class
`Puppet::Parser::AST::PopsBridge` to class `Puppet::Pops::Loaders` so
that such definitions can be instantiated without involving the former.
The method `Puppet::Pops::Loaders#load_main_manifest` is changed so
that it now instantiates all loaded definitions using the public
environment loader.
> (PUP-7908) Ensure that ScriptCompiler instantiates definitions

- lib/puppet/type/scheduled_task.rb
This commit removes all references to the special value `last` from the docs
for the scheduledtasks type. These references are erroneous, as the version of
the Scheduled Tasks api used (v1) does not support the `last` special value.
> (PUP-7933) Remove documentation about last in scheduledtasks type

- lib/puppet/transaction/report.rb
- spec/unit/transaction/report_spec.rb
If a puppet run is interrupted, the local puppet report in
last_run_report will be incomplete, which will mean that the metrics
instance variable will portentially be the empty hash. Because the
lookups in `exit_status` against `metrics` is not safe, it could raise
an exception. This commit updates the `exit_status` method to check to
make sure `metrics` has the expected keys and if not to return -1
instead of raising an exception.
> (PUP-7844) Return -1 for exit_status for interrupted runs

- Gemfile
- This commit was originally in 19f78a20b70660b30fff8c0c49e8b9a9b3c99b40
but due to a bad merge-up at 8dd78d37f049b4bb81f6146e4fa8af39b88a6130
was not correctly carried over.
As a result, the current branch thinks it has these changes, but
none of the Puppet 5 branches / tags have the following fixes:
- Without platform-specific gem dependencies marked as such inside the
.gemspec, this can cause issues with a bundler based workflow that
uses `bundle install --system --binstubs c:\ruby\bin` on Windows
machines *even if* the given Ruby version already satisfies all of
the Puppet platform-specific dependencies. This is due to how a
Gem is installed by Bundler when it refers to a git repo and its
.gemspec is rewritten by Bundler as its installed.
- Note that all runtime dependencies are now …
> (PUP-7425) Refactor Gemfile / .gemspec for Bundler

- lib/puppet/environments.rb
- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This makes it possible to specify the use of an environment:
* by name and a directory where this environment is (name and directory name does not have to match)
* by name that is found on an environment path in a directory on that path having the name of the wanted env
> (PUP-7946) Add support for existing env in Pal API

- lib/puppet.rb
- lib/puppet/defaults.rb
- lib/puppet/indirector/certificate_revocation_list/rest.rb
- lib/puppet/network/http/connection.rb
- lib/puppet/settings.rb
- lib/puppet/settings/certificate_revocation_setting.rb
- lib/puppet/ssl/certificate_authority.rb
- lib/puppet/ssl/host.rb
- spec/unit/indirector/certificate_revocation_list/rest_spec.rb
- spec/unit/network/http/connection_spec.rb
- spec/unit/settings/certificate_revocation_setting_spec.rb
- spec/unit/ssl/host_spec.rb
Puppet has always performed chain revocation checking when revocation
checking was enabled, but has never been able to load more than a single
CRL. Because of this Puppet could only be used with a root CA if
revocation checking was desired, and if intermediate CAs were in used
revocation had to be entirely disabled.
This commit sidesteps the issue of loading multiple CRLs by allowing
certificate revocation checking to be performed on the leaf certificate
only. This allows users to revoke certificates with an intermediate CA
that Puppet is managing, which is a definite improvement over not
allowing any revocation checking at all.
For the sake of compatibility certificate_revocation still defaults to
full chain checking; users must opt in to leaf revocation checking.
> (PUP-7845) Implement leaf certificate revocation checking

- lib/puppet/settings/ini_file.rb
- spec/unit/settings/ini_file_spec.rb
The `puppet config set` command previously allowed and preferred
that the [main] section header be omitted, and [main] settings be
written in the ini file as global.
This commit rejects that standard, preferring instead that the [main]
section header always be explicitly written in the file when `puppet
config` is used.
> (PUP-4755) prefer explicit [main] section header

- acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
On SLES, the apache2-worker package is not a dependency of apache2, and
so doesn't get installed at the start of this test. Our new Power8
platform is based on SLES 12 SP2 and now causes zypper to return a
non-zero error when you explicitly try to uninstall a package that is
not already installed, which fails this test without this fix.
> (PA-7959) Fix apache2 dependent package list in service test

- lib/puppet/vendor/pathspec/lib/pathspec.rb
Avoid overmatching characters between "Z" and "a" (such as _ or ^), should be a-zA-Z, not a-zA-z
Otherwise this is over-matching (matches anything between ASCII A and ASCII z, which is much more than just characters).
> (PUP-7926) Fix capitalization in regexp

- acceptance/tests/resource/file/symbolic_modes.rb
The teardown that removes the user and group used in the test
is leaving something behind on Fedora 26. Nothing obvious, since
all of the expected resources seem to be removed. However, on
Fedora 26 the gid value conflicts with the one created in the
resource/group/should_create test.
> (maint) remove teardown for symbolic_modes test

- acceptance/Gemfile
- acceptance/README.md
- acceptance/lib/puppet/acceptance/install_utils.rb
- acceptance/lib/puppet/acceptance/install_utils_spec.rb
- acceptance/setup/aio/pre-suite/010_Install.rb
- acceptance/setup/gem/pre-suite/010_GemInstall.rb
- ext/build_defaults.yaml
The latest beaker release includes new install utilities that enable
less reliance on correctly guessing the path to artifacts staged on
builds.delivery.puppetlabs.net. This commit updates the puppet tests to
use these new install utilities.
> (packaging) Update beaker and install methods

- lib/puppet/ssl/certificate_revocation_list.rb
- lib/puppet/ssl/certificate_signer.rb
- spec/unit/ssl/certificate_revocation_list_spec.rb
SHA1 is being phased out in favor of SHA256 and greater owing to the
increasing feasibility of attacks on the algorithm; this commit updates
the CRL signing code to use the same digest algorithm used when signing
certificates.
> (PUP-7957) Use SHA256 when signing CRLs

- .gemspec
- ext/project_data.yaml
- lib/puppet/version.rb
- libbolt/puppet_bolt.rb
We need to make sure that when this branch gets installed via a Ruby gem,
that we do not interfere with any other Puppet installations that the user
might already have. We do this by not mentioning 'lib/' in the require_path
of our gemspec. This effectively hides everything in 'lib/' from gem and
will keep ruby from ever satisfying a require of 'puppet/<somewhere>' with
files from this gem.
Code that consciously wants to load this gem, needs to instead require
'puppet_bolt'. That manipulates $LOAD_PATH so that 'lib/' does become
available. After that, any 'require "puppet/<somewhere>"' will resolve to a
file from this gem.
I have tried this out by making a gem with `rake package:gem` and installing the resulting gem in a container that did not have puppet. I then ran this script to verify …
> (PUP-7961) Change packaging so that puppet-bolt does not conflict with an existing puppet

- acceptance/tests/aix/aix_package_provider.rb
This commit augments the aix package provider acceptance test
to validate that it properly upgrades to the latest package when
using `ensure => latest` if the package is already installed.
The test has also been refactored to use blocks for each of the
test steps.
> (PUP-7899) Test aix package installs latest

- lib/puppet/functions/file_upload.rb
- lib/puppet/functions/run_task.rb
- lib/puppet/pops/issues.rb
- spec/unit/functions/file_upload_spec.rb
Adds a `file_upload` function that can upload a file or directory
to a set of nodes by calling the `Bolt::Executor#file_upload`. The
function requires that --tasks is enabled and that the `bolt` feature
is present.
> (PUP-7967) Add file_upload function

- lib/puppet/functions/run_command.rb
- spec/unit/functions/run_command_spec.rb
Adds a `run_command` function that can run a command on a set of nodes
by calling the `Bolt::Executor#execute`. The function requires that
--tasks is enabled and that the `bolt` feature is present.
> (PUP-7979) Add run_command function

- lib/puppet/functions/run_script.rb
- lib/puppet/pops/issues.rb
- spec/unit/functions/run_script_spec.rb
Adds a `run_script` function that can upload and execute a script
remotely on a set of nodes by calling the `Bolt::Executor#run_script`.
The function requires that --tasks is enabled and that the `bolt`
feature is present.
> (PUP-7980) Add run_script function

- lib/puppet/agent/locker.rb
- lib/puppet/face/catalog/select.rb
- lib/puppet/face/help.rb
- lib/puppet/face/man.rb
- lib/puppet/face/node.rb
- lib/puppet/face/plugin.rb
- lib/puppet/face/status.rb
- lib/puppet/forge/errors.rb
- lib/puppet/module_tool/errors/installer.rb
- lib/puppet/parser/compiler.rb
- lib/puppet/pops/loader/puppet_resource_type_impl_instantiator.rb
- lib/puppet/pops/lookup/hiera_config.rb
- lib/puppet/ssl/certificate_revocation_list.rb
- lib/puppet/ssl/host.rb
Avoid translating the keyword `new`, used as part of reading pcore
types. Translating it meant that reading pcore would fail on non-english
locales.
> (PUP-7992) Avoid translating keyword `new`

- lib/puppet/graph/relationship_graph.rb
- spec/integration/transaction_spec.rb
- spec/unit/graph/relationship_graph_spec.rb
Without this patch applied, the admissible whit does not have the same
tags as the initial class. When sending a refresh event to a class and
running puppet with a specific tag, if that class loses it's tags,
then the agent unschedules all the refresh events (because it thinks
the class does not have the tag in question).
This patch copies tags from the initial class resource to the
admissible whit that it gets replaced with.
> (PUP-7308) Propagate class tags to admissible whits

- lib/puppet/functions/run_task.rb
- lib/puppet/pops/issues.rb
- lib/puppet/pops/loader/static_loader.rb
- lib/puppet/pops/loaders.rb
- spec/unit/functions/run_task_spec.rb
- spec/unit/pops/loaders/static_loader_spec.rb
This commit ensures that the `StaticLoader` doesn't add any built in
resource types and that the `Runtime3Loader` doesn't get created and
added to the chain of loaders.
The change is necessary to:
a) Prevent that the names of built in puppet types collide with task
names.
b) Prevent that files residing under a modules 'manifests' folder are
loaded.
> (PUP-7996) Ensure that --tasks disables the Runtime3Loader

- lib/puppet/functions/run_task.rb
- lib/puppet/pops/issues.rb
- spec/unit/functions/run_task_spec.rb
This commit adds a check to the run_task function so that verifies that
the loader actually finds the given task when the task is given as
a string
> (PUP-7994) Add check to run_task that task is found before calling new

- acceptance/tests/loader/autoload_from_resource_type_decl.rb
Some of the tests for autoloading resource types from generated types
ran code on masters when the master was also an agent, which caused test
failures. This commit specifically skips test steps that must only occur
on agents.
> (maint) Skip autoload tests on masters

- lib/puppet/pops/loader/module_loaders.rb
- spec/unit/functions/run_plan_spec.rb
- spec/unit/functions/run_task_spec.rb
This commit will make the loader search for files named 'init' (with
appropriate extensions) under the 'plans' and 'tasks' directory. If such
a file is found, it's assumed to contain a plan or task that has the
same name as the module that contained the 'plans' or 'tasks' directory.
> (PUP-7997) Add ability to declare plan or task named after module

- acceptance/setup/common/pre-suite/030_StopSssd.rb
- acceptance/tests/resource/file/symbolic_modes.rb
Thanks to @geoffnichols the root cause of the user/group test conflict on Fedora 26 has been identified as caching caused by the sssd service. This PR adds a pre-suite to stop the service and reverts the previous commit that skipped the user teardown on Fedora 26.
> (maint) Disable sssd service on SUTs

- acceptance/config/aio/options.rb
This commit adds the beaker pre-suite to ensure that the `sssd`
service is stopped to the options for the `ci:test:aio` rake task.
> (PUP-7988) Add stop sssd pre-suite to aio testing

- acceptance/tests/i18n/check_puppet_run_message.rb
- acceptance/tests/loader/autoload_from_resource_type_decl.rb
- lib/puppet/gettext/config.rb
- spec/unit/gettext_config_spec.rb
- spec/unit/module_spec.rb
A significant (~30%) performance regression was found when gettext is
enabled. Until we can resolve it, disable gettext with a fix we've
tested. The root cause isn't clear, but appears to be that we configure
gettext too often.
> (PUP-8009) Disable gettext

- lib/puppet/external/nagios/grammar.ry
- lib/puppet/external/nagios/parser.rb
- spec/unit/type/nagios_spec.rb
This PR contains the code from https://github.com/puppetlabs/puppet/pull/6169 / @duritong, retargeted at 4.10.x for merge-up through master. From that PR:
> As reported in other places - e.g. (PUP-4633), with ruby >= 2.1.0
we don't need to enforce encoding anymore. This adds the same fix
also to the Nagios parser and adds a test that takes the example
from the bug report, which fails when running on 2.4.1.
> (PUP-3368) fix parsing of unicode in nagios resources on ruby >= 2.1.0

- lib/puppet/indirector/node/ldap.rb
- spec/unit/indirector/node/ldap_spec.rb
* the environment parameter from ldap was accessed with a string instead of a symbol
* jruby-ldap does not provide a to_hash method - add a ldap_entry_to_hash() method
* remove environment from parameters  hash to prevent duplicate declaration error
* downcase key in ldap_entry_to_hash for consistent key names
> (PUP-7883) Make node_terminus=ldap working with jruby/puppetserver

- acceptance/tests/i18n/check_puppet_run_message.rb
- lib/puppet/defaults.rb
- lib/puppet/gettext/config.rb
- lib/puppet/module.rb
- spec/unit/gettext_config_spec.rb
- spec/unit/module_spec.rb
A recent refactor of the gettext initialization code caused the require
for gettext-setup and locale to be called repeatedly during module
loading. This commit updates the gettext configuration module to only
require those gems once, and prevent unnecessary searching of the load
path.
This PR also adds a setting that allows gettext to be disabled entirely.
> (PUP-8009 & PUP-7769) Optimize gettext initialization and add settings toggle

- lib/puppet/gettext/config.rb
- spec/unit/module_spec.rb
This commit updates the file existence check in the gettext config
module to check for the config.yaml file itself, rather than its
containing directory. This should avoid an exception in GettextSetup
when that file is missing.
> (PUP-8009) Avoid throwing an exception when gettext config is missing

- lib/puppet/functions/all.rb
- lib/puppet/functions/any.rb
- lib/puppet/functions/each.rb
- lib/puppet/functions/filter.rb
- lib/puppet/functions/map.rb
- lib/puppet/pops/types/execution_result.rb
- lib/puppet/pops/types/iterable.rb
- spec/unit/pops/types/execution_result_spec.rb
This PR contains a series of commits to enable:
1. Hash-like iterable features for non Hash objects
2. A new API to be used by classes that want to present themselves as `Iterable`
3. Iterable features on the `ExecutionResult` object.
> (PUP-8010) Add iterable features to the ExecutionResult data type

- lib/puppet/provider/package/gem.rb
- spec/unit/provider/package/gem_spec.rb
The `^` is apparently ignored in windows, but `\A` works.
> (PUP-7973) gem package provider should match exactly

- lib/puppet/network/http/webrick.rb
It appears that binding to '\*' is platform-specific on Ruby, but
binding to 'nil' works everywhere. Since Puppet settings aren't
nillable, we keep '\*' as the setting value, but munge that to 'nil'
in the HTTP setup code.
> (PUP-7472) Make binding to '*' work on non-Linux platforms

- lib/puppet/indirector/file_bucket_file/file.rb
- spec/integration/file_bucket/file_spec.rb
Puppet::Indirector::FileBucketFile::File#verify_identical_file is used to
validate that an incoming file to back up is identical to an existing backup we
believe to matches it. As a part of this comparison, we attempt to compare the
size of the content of the incoming IO object to the size of the existing
backup on disk, before doing a more resource-intensive byte-by-byte comparison.
Prior to this commit, we would call Puppet::FileBucket::File#size on the
incoming object, and compare it to the Puppet::FileSystem#size of the existing
backup. The former can actually call String#size or Puppet::FileSystem#size, as
the contents of a Puppet::FileBucket::File are represented either as a
StringContents or FileContents depending on the class of content supplied at
initialization. The latter is …
> (PUP-7951) correct size comparison in filebucket

- lib/puppet/module.rb
This commit fixes a typo in an if-block handling error messaging around
loading gettext for modules. It corrects nested ifs, replacing them with
a cleaner if-elsif-else flow.
> (maint) Fix if block around gettext initialization

- benchmarks/many_modules/benchmarker.rb
To ensure we excerise the i18n initialization code path when loading modules,
we need to have the appropriate scaffolding in place in the module for i18n.
This adds the most basic required information.
> (maint) add a locale/i18n file for the many modules benchmark

- lib/puppet/module.rb
Previously, Puppet would issue a warning about gettext being unavailable
each time a module was loaded. This commit updates that warning to only
be issued once.
> (PUP-8039) Only warn once when module loading code can't find gettext

- lib/puppet/provider/service/launchd.rb
- spec/unit/provider/service/launchd_spec.rb
On macOS puppet throws the infamous warning:
```
Warning: The /System/Library/LaunchDaemons/com.apple.jetsamproperties.Mac.plist plist does not contain a 'label' key; Puppet is skipping it
```
I switched the warning to a debug message, just as @MosesMendoza recommended in #5730.
> (PUP-6854) degrade missing label warning to debug

- lib/puppet/provider/package/dnf.rb
- spec/unit/provider/package/dnf_spec.rb
The default package provider should be set to use dnf on Fedora 26.
> (PUP-8045) Add support for Fedora 26 to the dnf provider

- lib/puppet/defaults.rb
Clarify how the `static_catalogs` setting behaves in the configuration reference, and link to context about what static catalogs are and how they work.
> (DOCUMENT-729) Add context to static_catalogs setting.

- lib/puppet/configurer.rb
- We don't use the exception variable `e`, so we shouldn't retain it. Minor,
but enough of these and we have a lot of extra expensive objects getting
created.
- Don't `rescue Exception`, just rescue. `rescue` by default will rescue
StandardError. Rescuing Exception is broader in its scope. It's most
likely we just want to rescue if the rest indirection recieves a 404 because
the node wasn't found (which raises Puppet::Error) or the server wasn't
found, and we get an Errno::ECONNREFUSED. Both of these inherit from
StandardError.
> (maint) cleanup exception in Configurer#find_functional_server

- lib/puppet/defaults.rb
Prior to this commit, puppet device could not write to the privatekeydir and
certdir for devices.
drwxr-x---.  3 root      root        18 Jun 28 22:55 devices
With this commit, the $vardir/devices directory’s group is set to pe-puppet,
so that the puppet user can traverse the directory via the group permissions.
drwxr-x---.  3 root      pe-puppet   18 Jun 28 22:55 devices
> (PUP-1391) puppet device cannot create certs when run as root

- .rubocop.yml
- Gemfile
- Rakefile
Update the version of rubocop which caused some of the names in the
.rubocop.yml file to change. Added and disabled some of the new checks.
> (PUP-7955) update the version of rubocop used

- lib/puppet/type/yumrepo.rb
- spec/unit/type/yumrepo_spec.rb
RHEL 7.4 introduces a new booelean parameter payload_gpgcheck to do a
signature check on the payload sections of packages before installing
it.
> (PUP-7781) Add payload_gpgcheck param to the yumrepo type

- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/ruby_generator.rb
- spec/unit/pops/types/ruby_generator_spec.rb
When generating Ruby code from an `Object` data type containing
attributes or functions with names that are Ruby keywords, those names
were used verbatim in the generated code. This made it impossible to use
attribute or function names such as `ensure`.
This commit alters the generator so that all names that are reserved in
Ruby get prefixed with an underscore letter in the generated Ruby code.
The change is invisible from the Puppet code.
> (PUP-8046) Fix problem with Ruby generator and Ruby keywords

- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
- spec/unit/pops/types/task_spec.rb
This commit changes the file based loader so that rejecs the directory
entries that are returned by the ruby `Dir#glob` method in case the
glob is executed without any known extension (as is the case when doing
a glob to find tasks).
The change fixes the problem where a directory would be interpreted as
a task, or interfere with a task using the same name (but different
extension) as the directory.
> (PUP-8028) Ensure that directories are ignored by the file based loader

- lib/puppet/pops/types/p_error_type.rb
- spec/unit/pops/types/p_error_type_spec.rb
This commit adds a dispatcher to the `Error` data type that takes a hash
as an argument so that `Error` instances can be created from named
arguments.
> (PUP-8056) Add by-name initializer to the Error data type

- lib/puppet/type/mount.rb
AIX options for the mount type were added in Puppet 3.x in #3769, along with documentation explaining those options. The options are part of Puppet 4 onward, but the documentation wasn't brought forward.
Restore the AIX documentation to the mount type's options.
> (docs)(DOCUMENT-730) Restore AIX mount option docs.

- lib/puppet/provider/mount.rb
- spec/unit/provider/mount_spec.rb
Contains the content of PR https://github.com/puppetlabs/puppet/pull/6105, but with added test and a bit of refactor/DRYup.  See that PR for context.
> (PUP-7807) Add mount options on AIX remount

- lib/puppet/provider/package/pkg.rb
- spec/unit/provider/package/pkg_spec.rb
The latest method currently uses `pkg list -Hvn` which does not imply a
periodic refresh of package metadata. With this change the latest method
calls `pkg refresh`.
> (PUP-7745) package latest method does not refresh metadata on Solaris

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This makes it possible to set variables in any scope/name-space when
defining the environment to run in.
> (PUP-7987) Add ability to set variables in Pal API

- lib/puppet/application/script.rb
- lib/puppet/functions/run_command.rb
- lib/puppet/functions/run_script.rb
- lib/puppet/functions/run_task.rb
- spec/unit/functions/run_command_spec.rb
- spec/unit/functions/run_script_spec.rb
- spec/unit/functions/run_task_spec.rb
Lookup the bolt executor from puppet's context system instead of relying on the
Bolt::Executor.from_uris factory method. The latter did not preserve options set
on the bolt command line, e.g. default user, password, tty, etc. which prevented
plans for working in some situations.
> (PUP-8068) Lookup bolt executor

- lib/puppet/type/exec.rb
Intuitively, one may think that `exec`'s environment parameter takes a
Hash, however, it expects an Array, which was not documented anywhere.
> (docs) exec's environment takes an array

- lib/puppet/provider/service/base.rb
- spec/fixtures/unit/provider/service/base/ps_ef.mixed_encoding
- spec/unit/provider/service/base_spec.rb
This patch updates the base service provider such that the binary
"ASCII-8BIT" string encoding is used when a process table scan is run by
service resources that have `hasstatus => false` set. This scan runs
regex matches against the output of `ps -ef` which could contain
arbitrary byte sequences depending on which services are running on the
system and how they are configured.
> (PUP-6986) Use binary encoding when searching for pids

- lib/puppet/pops/types/p_binary_type.rb
Before this, the documentation for the Binary data type was a pasted
copy from SemVer.
> (PUP-8071) Fix documentation of Binary data type

- lib/puppet/provider.rb
- spec/unit/provider_spec.rb
This PR is the content of https://github.com/puppetlabs/puppet/pull/5069 with one additional commit added containing a refactor that achieves the original goal. See https://github.com/puppetlabs/puppet/pull/5069 for context. From that PR:
> - Allows easier matching for defaults. For example, Fedora 22+ uses DNF. It's easier to just give a regex of 22-29 rather than add a new one each time
> 
> Code is rough right now, but working according to the specs! 😄
> (PUP-6452) Allow defaultfor to accept regex

- lib/puppet/provider/zfs/zfs.rb
- spec/unit/provider/zfs/zfs_spec.rb
This is the content of #4990, with commit message adjusted and an additional test that adjusts the spec to account for this change.
From #4990:
> Zfs of type "volume" (not filesystem) must be created with the -V option and the volsize param is only used in this case.
> So puppet should not specify -o volsize=N but -V N . 
> 
> It has already been asked the 11/26/2014 and updated twice in 2015 : https://tickets.puppetlabs.com/browse/PUP-3713
> 
> Thx
> (PUP-3713) Fix zfs type volume with volsize param

- lib/puppet/pops/loaders.rb
- spec/unit/pops/loaders/loaders_spec.rb
It is an unwanted complications that a module must have a metadata.json with dependencies on other modules in order to be able to use them.
This PR removes that requirement - after this all modules see all other module's functions and types.
> (PUP-6964) Make modules see all other modules

- ext/redhat/logrotate
This PR contains the content of https://github.com/puppetlabs/puppet/pull/5708, with the commit message amended per contributing guidelines.
From that PR:
> ext/redhat/logrotate: really avoid 'service puppet reload' in favor of 'service
puppet rotate' with the correct signal
>
> It looks like there was an intention to introduce this fix in
793d713503d27600b4c64e4e0c331d6d7365e3c4
'(PUP-4918) Updated logrotate and init scripts',
where the "rotate" command was added to
ext/redhat/client.init specifically for this purpose.
>
> This doesn't apply to ext/debian/puppet.logrotate because
ext/debian/puppet.init lacks a special command with this signal.
> (PUP-4918) `rotate` instead of `reload` for logrotate

- acceptance/tests/resource/package/yum.rb
- lib/puppet/provider/package/yum.rb
- spec/unit/provider/package/yum_spec.rb
This PR contains the content from #5986, with an additional couple commits that complete the functionality for the ensure => version case.
From that PR:
> If the source parameter is set when using the yum package provider, then use it with yum directly. This has the advantage of bringing in a package's dependencies while allowing direct installation from the internet without already setting up a repository
#5986 sufficiently covered the ensure present case, ie
```
package { "foo":
source => "http://foo.com/foo-1.1.0.rpm",
}
```
will work correctly.
This PR completes this with the ensure => version case, ie
```
package { "foo":
ensure => "1.2.0",
source => "http://foo.com/foo-1.2.0.rpm",
}
```
This PR also adds spec tests to yum_spec.rb for the functionality.
> (PUP-3323) Support `source` in yum provider

- lib/puppet.rb
- lib/puppet/gettext/config.rb
- lib/puppet/module.rb
- lib/puppet/vendor/semantic_puppet/lib/semantic_puppet.rb
- spec/unit/gettext_config_spec.rb
- spec/unit/module_spec.rb
This commit majorly refactors the way we load tranlsations, to avoid
using the gettext-setup gem altogether. This allows us to set the locale
globally, rather than thread-locally, and also paves the way for
maintaining a different text domain for each environment.
> (PUP-8040) Do not use thread local locale

- lib/puppet/util/windows/file.rb
In addition to symbolic links, reparse points on Windows may also be mount points (as is the case with DFS volumes).
Add support for this.
> (PUP-8083) Support Windows reparse mount points

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this commit, any ruby object that would respond `true` to
`#is_a?(Numeric)` would be considered an instance of the Puppet
`Numeric` data type. This commit alters the constraint to only include
values that respond true to `#is_a?(Integer)` and `#is_a?(Float)`
> (PUP-8057) Ensure that only Integer and Float is considered Numeric

- lib/puppet/gettext/config.rb
if fast_gettext wasn't loaded, initializing modules would result in an
exception because loaded_repositories was never set. This was found in
puppetserver unit tests. It's unlikely to affect other places as
gettext-setup - and thus fast_gettext - are runtime dependencies in the
gemspec.
> (PUP-8040) Fix error if fast_gettext isn't loaded

- acceptance/tests/resource/package/yum.rb
When testing the yum utilities, we are creating an empty rpm package so
that we can install from a repo without hitting any external repos.
However, we aren't bothering to sign that empty package. When we go to
do the actual install, yum bails out because the package isn't signed.
This is great, but not in this instance. We don't care that the package
isn't signed, we just want to make sure the install works. This commit
adds in a flag to the install to make sure yum doesn't check the
signature.
> (PUP-3323) Ensure we don't check gpg

- lib/puppet/file_serving/configuration.rb
- lib/puppet/file_serving/configuration/parser.rb
- lib/puppet/file_serving/mount/locales.rb
- lib/puppet/module.rb
- spec/unit/file_serving/mount/locales_spec.rb
locales is a new default mountpoint desiged to serve modules' translations from their locales directories, in order to download those files from the master to the agent during pluginsync
> (PUP-8100) add locales mountpoint.

- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
- spec/unit/pops/types/types_spec.rb
This commit adds the ability to declare a boolean case insensitive flag
as the last argument to an `Enum` data type. The default, when no such
flag is given, is that the `Enum` is case sensitive.
> (PUP-8119) Add case insensitive flag to the Enum data type

- lib/puppet/pops/evaluator/access_operator.rb
- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/type_formatter.rb
- lib/puppet/pops/types/type_parser.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_formatter_spec.rb
- spec/unit/pops/types/type_parser_spec.rb
- spec/unit/pops/types/types_spec.rb
This commit makes it possible to parameterized the `Boolean` data type
using a boolean value. When set, the resulting type will only represent
that value.
> (PUP-8117) Make it possible to parameterize Boolean data type

- lib/puppet/configurer/downloader_factory.rb
- lib/puppet/configurer/plugin_handler.rb
- lib/puppet/defaults.rb
- spec/integration/faces/plugin_spec.rb
- spec/unit/configurer/downloader_factory_spec.rb
- spec/unit/configurer/plugin_handler_spec.rb
- spec/unit/face/plugin_spec.rb
This commit adds a new downloader to pluginsync, responsible for syncing
the locales directories of modules. Without this, translation files are
not synced from the master to the agent, and module translations will
not be displayed during agent runs.
> (PUP-8089) Add a new pluginsync downloader for module translations

- lib/puppet/functions/new.rb
- lib/puppet/pops/types/p_init_type.rb
- lib/puppet/pops/types/p_sem_ver_type.rb
- lib/puppet/pops/types/types.rb
- spec/unit/functions/new_spec.rb
- spec/unit/pops/types/p_init_type_spec.rb
The `Init` data type bases assignability and instance computation on the
signatures of the #new function for a given type. Before this commit,
those signatures were very relaxed. An `Integer` could for instance be
created from any `String` which gave that "blue" was an instance of
`Init[Integer]`. This commit tightens the constraints.
> (PUP-8121) Make #new function signatures more strict

- lib/puppet/agent.rb
- lib/puppet/defaults.rb
- spec/unit/agent_spec.rb
On occasion, a puppet agent can end up waiting indefinitely on some process
that will never return or terminate. This patch adds a new setting, runtimeout,
that can be used to specify the maximum duration allowed for a puppet
run. When set to a non-zero value, the agent daemon will send a SIGTERM to any
agent run it starts which exceeds this value.
This patch does not handle runs started outside of the agent daemon by
`puppet agent --onetime`.
> (PUP-7517) Allow agent daemon to time out stalled runs

- lib/puppet/application/agent.rb
- lib/puppet/application/apply.rb
CLI help content suggests the `--logdest` flag can take a file as a destination. It requires an absolute file path. Specify this in the CLI help content.
This content is also used to generate some docs site content.
> (PUP-5987) Specify that logdest accepts an absolute file path.

- lib/puppet/pops/loader/task_instantiator.rb
- spec/unit/pops/types/task_spec.rb
This commit adds the task metadata field "sensitive" to the whitelist of
metadata fields. This field can be used to specify that a parameter
value should be redacted from logs, etc.
This does not include any behavior change to actually redact data, just
to allow those tasks to be run.
> (PUP-8134) Allow tasks to specify that parameters are "sensitive"

- lib/puppet/pops/types/type_calculator.rb
- spec/unit/face/epp_face_spec.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this commit, `true` and `false` would be inferred to `Boolean`
without parameters. This commit ensures that the value is retained so
that the inferred type is `Boolean[true]` or Boolean[`false`].
> (PUP-8138) Ensure that the inferred type of a boolean retains value

- lib/puppet/functions/run_script.rb
- spec/unit/functions/run_script_spec.rb
Before this the run_script function did not accept arguments and did not
call bolt executor correctly.
Now, the run_script function accept a hash with a single key 'arguments'
that can be set to an array of strings to give as arguments to the
script. This solution was decided to make the run_script and run_task
functions similar in signature. It would otherwise be difficult to
support the list of targets in the same manner.
> (PUP-8137) Make run_script accept arguments

- lib/puppet/functions/file_upload.rb
- spec/unit/functions/file_upload_spec.rb
- spec/unit/functions/run_command_spec.rb
- spec/unit/functions/run_script_spec.rb
Commit b6a166974 changed how bolt related run_* functions lookup the executor,
but I forgot to apply the same change to the file_upload function.
/cc @hlindberg @thallgren
> (PUP-8133) Lookup bolt executor for file_upload function

- lib/puppet/defaults.rb
Prior to this commit, users had to spell out `--environment`
on the command line, which was repetitious and long.
This adds a short `-E` flag as a synonym since `-e` is already
in widespread use for inline code with `puppet apply -e ...`
PS I looked through the acceptance and unit tests and didn't see any that specifically tested command line arguments so there wasn't an obvious place to start adding them.
PPS I targeted 4.10.x for this as the oldest branch, happy to retarget if that's wrong.
> (PUP-8050) Add shorter `-E` flag for `--environment`

- lib/puppet/interface.rb
- spec/unit/interface_spec.rb
Prior to this patch, error messages raised by `Puppet::Face` objects would
print the generic Ruby representation of the object, which is just the
class name plus the object instance id. The instance id is exactly as
useful as a random number when trying to figure out which face or version
of a face was involved in the error. This patch aliases the `inspect` method
of the `Puppet::Face` class to the `to_s` method so that error messages
include both the face name and version number.
> (PUP-8140) Add inspect method to Puppet::Face

- lib/puppet/functions/lookup.rb
Before this, it was possible to misinterpret `{strategy =>
'first|hash|deep'}` as making it possible to set a combined strategy.
This is made clearer by showing three separate entries, one per strategy.
> (PUP-8144) Make it clear that | between strategies means 'or'

- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/types/p_object_type_extension.rb
- spec/unit/pops/types/p_object_type_spec.rb
An `Object` instance, when inferred to a parameterized type (and hence
to an `PObjectTypeExtension` instead of an `PObjectType` does not
make its attributes accessible using functions in Puppet. This is
because the evaluator triggers on the `PObjectType`.
This commit fixes this glitch by also checking for the class
`PObjectTypeExtension`.
> (PUP-8078) Ensure that attribute access works for PObjectTypeExtension

- lib/puppet/pops/types/type_mismatch_describer.rb
- spec/unit/functions/defined_spec.rb
- spec/unit/pops/types/type_mismatch_describer_spec.rb
Before this commit, a type mismtach involving the the types `Optional`,
`NotUndef`, `Sensitive`, and `Type` would be reported without the type
parameter when the base type differered between actual and expected
type. The resulting output was often somewhat cryptic since it's almost
always desirable to know the the contained type.
This commit ensures that the aformentioned types are always reported
with their included type.
> (PUP-7401) Include type parameter in type mismatch report

- lib/puppet/pops/types/iterable.rb
- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_calculator_spec.rb
Before this commit, a type alias for an `Iterable` type such as an
bounded `Integer` type or an `Enum` would not be considered `Iterable`.
This commit ensures that a type alias is iterable when the type that
the alias resolves to is iterable.
> (PUP-7401) Ensure that a type alias for an Iterable type is Iterable

- acceptance/Gemfile
The latest version of Beaker Host Generator is 1.1.3, which was excluded
by the current Gemfile rule. Update to fix, especially since
Windows-2012r2-core and Windows-2016-core have been introduced.
Submitting this as a trivial MAINT PR
> (MAINT) Update Beaker Host Generator Gem

- lib/puppet/module_tool/errors/shared.rb
- lib/puppet/module_tool/errors/uninstaller.rb
Fix the translations cases where a generated list of things in the
message output can be an empty list and an incorrect translation variable.
> (PUP-8092) address translations with empty lists

- lib/puppet/defaults.rb
This is a backport of the same fix from 5.4.0 #6026 
Prior to this commit, puppet device could not write to the privatekeydir
and certdir for devices.
drwxr-x---.  3 root      root        18 Jun 28 22:55 devices
With this commit, the $vardir/devices directory’s owner and and group are set
to the service user, so that the service user can traverse the directory.
drwxr-x---.  3 pe-puppet pe-puppet   18 Jun 28 22:55 devices
> (PUP-8108) puppet device cannot create certs when run as root

- lib/puppet/transaction.rb
- lib/puppet/transaction/persistence.rb
- spec/unit/transaction_spec.rb
The transactionstore.yaml file used to calculate corrective change is updated on each agent run with the set of applied resources. When the --tags option is provided, only the state of the resources matching the tags were stored, with the state for other resources discarded. That means corrective change is not correctly determined on future runs for those resources excluded by the tags.
This commit updates the transactionstore when resources are skipped to preserve the last seen value.
> (PUP-8096) Preserve transactionstore when tags are applied

- CONTRIBUTING.md
This commits adds in a few details on exactly how to run all the tests.
Prior to this commit, we simply had a mandate that users run tests
before opening pull requests. This commit details how to do that. Users
are only expected to ensure the unit tests are passing prior to opening
a pull request.
> (docs) Provide instructions on running puppet unit tests

- lib/puppet/pops/merge_strategy.rb
- spec/unit/functions/lookup_spec.rb
This PR is a backport of [PR-5931](/puppetlabs/puppet/pull/5931) for [PUP-7608](https://tickets.puppetlabs.com/browse/PUP-7608).
> (PUP-8182) Backport PUP-7608 to 4.10.x

- lib/puppet/application/lookup.rb
- lib/puppet/node.rb
- lib/puppet/node/facts.rb
- spec/fixtures/unit/application/environments/production/data/common.yaml
- spec/unit/application/lookup_spec.rb
Prior to this commit, the content of a yaml or json file passed to the
lookup CLI with the --facts option was just added to the node parameters
hash (which in essence means that they were just added to top scope).
This commit ensures that they are added to the contained facts instance
in the node and and hence, made available also when the dotted name
'facts.xxx' is used.
> (PUP-7507) Ensure that --facts are propagated to top scope and facts

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This makes it possible to just parse puppet language and get AST back. The returned AST is validated.
The AST can then either be evaluated using `evaluate(ast)` or `evaluate_literal(ast)`.
> (PUP-8170) Add parsing to PAL API

- lib/puppet/provider/service/init.rb
- spec/unit/provider/service/init_spec.rb
In Puppet 5, some Solaris services were failing to start because Puppet
was abandoning them before making sure that they started correctly. This
caused Puppet to report that the service had started, when it actually
had not. Passing "child" to the ctrun command causes Puppet to manage
the service start more closely, while still retaining the contract
behavior for which ctrun was added (see PUP-2455).
> (PUP-8143) Pass "child" to ctrun on Solaris instead of "none"

- lib/puppet/functions/each.rb
- lib/puppet/functions/map.rb
- spec/unit/functions/break_spec.rb
Without this patch applied, the break() function fails on hash iterations
using each() or map(), with the error "break() from context where this is
illegal". break() is expected to break out of an iteration regardless of
context. This is happening because each() and map() rescue the StopIteration
exception for enumerables, but not for hashes. eval_Program() throws the
illegal context error when it catches the previously unhandled StopIteration
for a hash. This patch fixes the issue by rescuing StopIteration for hashes
in each() and map().
reduce() and slice() were already behaving as expected, while with() and
filter() are not conducive to a break() operation.
My assumption is that the Puppet `each()` and `map()` functions were written without `StopIteration` in mind because there was no …
> (PUP-8181) Rescue StopIteration for hash in each and map functions

- lib/puppet/ssl/certificate_authority.rb
An exception message in certificate_authority.rb is missing a period
between sentences. This patch simply adds that missing punctuation.
> (PUP-7937) Add missing period to exception message in certificate_authority.rb

- lib/puppet/pops/types/execution_result.rb
- spec/unit/pops/types/execution_result_spec.rb
Makes it easier to test functions that return ExecutionResults.
> (maint) Add equality operator for ExecutionResult

- lib/puppet.rb
- lib/puppet/configurer.rb
- lib/puppet/environments.rb
- lib/puppet/gettext/config.rb
- lib/puppet/gettext/module_translations.rb
- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/module.rb
- lib/puppet/node/environment.rb
- lib/puppet/util/command_line.rb
- spec/unit/gettext/config_spec.rb
- spec/unit/gettext/module_loading_spec.rb
- spec/unit/module_spec.rb
- spec/unit/node/environment_spec.rb
These commits change the way module translations are loaded. Previously, module translations were only loaded from the module's directory when a new module object was created. This didn't work agent-side, where module files are loaded from `$vardir` instead of from the modulepath, and it also caused some unnecessary loading of translations.
The first commit causes all available module translations to be loaded from both the module path and `$vardir` when a puppet subcommand is run from the command line.
The second commit causes module translations to be loaded from `$vardir` on the agent whenever pluginsync occurs, before facts are loaded, to ensure that any messages in facts get translated.
> (PUP-8090) Load module translations from modulepath and vardir

- lib/puppet/parser/functions/sprintf.rb
- spec/unit/parser/functions/sprintf_spec.rb
This makes named arguments in a sprintf work. The problem is that it requires symbols and we don't have those. We also don't want to always change a hash with string keys into a hash with symbol keys because if the hash is output with a %s format it will output symbols.
The approach taken is to only transform if needed (on the KeyError that is raised when it does not find the keys). Thus, this is also future proof if Ruby should change and allow string keys (then it would work on the first attempt).
> (PUP-5556) sprintf named arguments needs symbols

- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This adds support for checking arguments to a plan against its parameters. This is implemented by having PAL specific Signature type classes that have a limited set of features compared to returning the more detailed type system descriptions. For Plan that would require modifying PCallableType, or having yet another type for "args by name" in order for that to be useful to the caller of 'plan_signature'. 
Now, plan_signature returns a Puppet::Pal::PlanSignature and it has a simple `callable_with?` method (for args in a hash)
Also added is a Puppet::Pal::FunctionSignature with a simple `callable_with`` method (for args in an array).
More details about the underlying data type is available in the respective signature classes.
> (PUP-8171) add support for checking parameters of plan

- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
- spec/unit/pops/loaders/loader_spec.rb
This PR adds a new `EmptyLoader` to be used as the environment loader for environments that does not have a valid path such as the tmp_environment created by `Puppet::Pal`.
The PR also contains a commit that addresses a bug where a file could not coexist with it's metadata. The fix was a slight refactoring of the code checking what paths that are valid for a specific `SmartPath`.
> (PUP-8204) Add an EmptyLoader to be used by static environment

- lib/puppet.rb
- lib/puppet/gettext/config.rb
The GettextConfig module controls all access to the FastGettext and
Locale libraries. A previous commit accidentally introduced a reference
to the Locale library outside of this module, which caused errors during
puppetserver unit testing, when the gem was not installed. This commit
moves all references to Locale behind the guards set up in the
GettextConfig module.
> (PUP-8090) Do not reference the Locale gem outside of GettextConfig

- lib/puppet/face/config.rb
This commits adds in a warning to encourage users to set the environment
in a subsection of puppet.conf rather than globally. This is because the
environment setting has different meaning depending on which context it
is being used in. It can either refer to the environment defined locally
on the filesystem or the environment that it is requesting from the
master. These different uses can lead to issues when the user has set
environment globally to an environment that only exists on the master
and not the agent. In this case, puppet subcommands that interpret
environment to refer to the environment as defined locally will fail
because that environment does not exist on the local filesystem. This
can be very frustrating and unintuitive to users.
> (PUP-6739) Encourage users to limit where they set environment

- lib/puppet/application.rb
- lib/puppet/application/config.rb
- lib/puppet/application/help.rb
- lib/puppet/application_support.rb
- spec/unit/application/config_spec.rb
- spec/unit/application_spec.rb
- spec/unit/face/config_spec.rb
Prior to this commit, we had a number of users running into an issue
where if they set the environment in either the toplevel or [main] of
puppet.conf, and that environment did not have a corresponding directory
in the local file system, commands like `puppet config` and `puppet
help` would bail out. This commit adds in the ability to specify
environment requirements on the application level. Commands like `puppet
config` and `puppet help` shouldn't require the environment to exist
locally.
This issue mainly surfaces because the concept of environment is used in
multiple contexts. The use case this change is meant to address is when
a user has set environment to refer to an environment that only exists
on the master. Under this scenario, `puppet agent` can check into the
master to request …
> (PUP-6739) Certain apps shouldn't fail if env is not local

- lib/puppet/defaults.rb
See [puppet-docs PR #816](https://github.com/puppetlabs/puppet-docs/pull/816)
by @melissa.
This commit expands the information provided for just how environment is
used when defined in puppet.conf. This variable has different
implications when defined in different contexts. Prior to this commit,
we simply had a very vague description of how it is used, with no
explicit detail about what happens if the user sets environment in the
different sections of puppet.conf. This commits adds in some of that
detail that was previously lacking.
> (docs)(PUP-6739) Expand environment setting doc.

- lib/puppet/pops/types/types.rb
- spec/shared_contexts/types_setup.rb
- spec/unit/pops/types/type_calculator_spec.rb
This changes the (broken) type algebra for empty Variant type such that
it is only assignable to empty Variant, Any, NotUndef[Variant], and
Unit, and that any Variant is assignable to an empty Variant.
This modifies the setup in `types_setup` by removing Variant type from
`all_types` - this because it is not meaninful to test all other data
types against empty Variant with one and the same rule. Instead, there
are now explicit tests for empty Variant.
> (PUP-8212) Fix strange behavior of empty Variant data type

- lib/puppet/pops/loader/task_instantiator.rb
- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This adds `list_functions`, `list_plans` and `list_tasks` to the PAL API. It also adds a `TaskSignature` that is obtained from the new method `task_signature`.
The `TaskSignature` can answer if a hash of arguments is acceptable when running the task.
> (PUP-8202) Add list kind to pal api

- lib/puppet/pops/loader/task_instantiator.rb
The task metadata specification says every field in metadata should have
a reasonable default so they can be omitted. For parameters that's
equivalent to not having metadata, i.e. any input is allowed. Update the
task loader to make parameters an optional property.
> (PUP-8197) Make parameters optional

- lib/puppet/gettext/config.rb
When an English string changes slightly, the FastGettext will
attempt to choose a translation that seems similar, update its English
key, and mark the translation as "fuzzy", to inform the translator that
review is needed. By default, FastGettext will issue a warning when a
fuzzy translation is used at runtime. This warning comes out of FastGettext
directly, circumventing our logging framework, and so is impossible for
a user to turn off, and in some cases impossible for them to fix.
Therefore, this commit passes a flag to FastGettext to suppress the
warning.
> (maint) Suppress fuzzy translation warning

- .rubocop.yml
- lib/puppet/face/config.rb
- lib/puppet/face/module/list.rb
When sorting an array, just call `sort` instead of `sort_by` with a
block returning each element. Also enable the rubocop check for this.
See https://github.com/bbatsov/rubocop/blob/master/manual/cops_performance.md#performanceredundantsortby
Follow up from PR #6372
> (maint) Eliminate redundant sort_by

- lib/puppet/application/device.rb
Prior to the commits for PUP-1391 and PUP-8108 it was neccessary
for `--user=root` be set when `puppet device` was creating certs.
This commit updates the `puppet device` man page to reflect this is
no longer needed.
> (PUP-8183) Update puppet device documentation for --user

- lib/puppet/type/tidy.rb
As mentioned in PR #3693 Tidy shouldn't output anything in the Puppet logs when no objects are cleaned up, i.e. when everything is already tidy.
This change adds the missing `if` statement to avoid the `Tidying 0 files` log message.
> (PUP-8219) Don't log no-op Tidy runs

- lib/puppet/configurer.rb
Before this commit, when using a cached catalog, module translations
did not get loaded because we do not pluginsync when using a cached
catalog. This commit ensures that translations get loaded when using
a cached catalog. The translations must be loaded before preparing the
catalog to ensure that messages from types get translated.
> (PUP-8090) Load module translations when using a cached catalog

- lib/puppet/pops/lookup/hiera_config.rb
- spec/unit/functions/lookup_spec.rb
This commit removes the requirement that an uri in the hiera.yaml must
match a URI pattern. The only requirement now is that a URI can be
created from the given string.
> (PUP-8216) Relax URI type constraint in hiera.yaml

- lib/puppet/pops/loader/static_loader.rb
- spec/unit/pops/loaders/static_loader_spec.rb
The Augeas type in static loader was misspelled.
I'm not sure how much this would break things. It doesn't seem that there were many complaints, so I'm assuming this would fall back to the older type system possibly and still function? Ping @hlindberg or @thallgren to help me understand the behavior here.
> (Maint) Fix Augeas typo

- lib/puppet/parser/scope.rb
- spec/integration/parser/scope_spec.rb
A regression introduced in PUP-5635 caused the evaluator to omit the
parameter scope when evaluating parameter default expressions and
resolving qualified names of variables. As a result, a reference to a
parameter to the left of the one declaring the default expression,
declared using the qualified name of the class holding the parameter
list, would be unresolved.
This commit ensures that resolution of qualified names will include the
parameter scope when the name appoints the current class.
> (PUP-8124) Resolve qualified names in class parameter scope

- lib/puppet/pops/types/type_factory.rb
- lib/puppet/pops/types/types.rb
- lib/puppet/settings/environment_conf.rb
- spec/unit/environments_spec.rb
Before this because an environment.conf file is validated mulitple times there could be many logged warnings for ignored but invalid contents.
This changes the logging of these warning to use `warn_once` - there will now only be one logged message per environment.conf file for extra sections, and one for extraneous settings found.
> (PUP-4065) Warn once about illegal environment.conf setting

- lib/puppet/gettext/config.rb
- lib/puppet/gettext/module_translations.rb
- lib/puppet/module.rb
- lib/puppet/vendor/semantic_puppet/lib/semantic_puppet.rb
- locales/en/puppet.po
- spec/unit/gettext/config_spec.rb
- spec/unit/gettext/module_loading_spec.rb
This commit ensures that a module's locales directory contains a set of
translation files for the selected locale before creating the
translation repository for that module. Since translation files are
lazily loaded by FastGettext, it will create the repo first and look for
the files later. If it can't find them, it will create and read an
empty MO file as a placeholder. To avoid this extra work, we now do that
check up front.
> (PUP-8191) Don't initialize gettext for modules without relevant translations

- lib/puppet/face/module/search.rb
- lib/puppet/forge.rb
- spec/unit/face/module/search_spec.rb
- spec/unit/forge/module_release_spec.rb
Updates `puppet module search` to clearly indicate any deprecated
modules in the returned search results. Updates `puppet module
install` and `puppet module update` to emit a warning if a deprecated
module is being installed.
> (PUP-8082) Add warnings to PMT for deprecated modules

- lib/puppet/application_support.rb
This method is used outside of just puppet, so in order to maintain
backward compatibility, we need to allow the method to be used with only
one argument. This commits adds in a default for `environment_mode`, so
that projects like puppetserver can still use the method.
> (maint) push_application_context should have a default

- lib/puppet/pops/evaluator/epp_evaluator.rb
- spec/unit/face/epp_face_spec.rb
- spec/unit/functions/epp_spec.rb
Before this it was not possible to give names of fully qualified
variables on the command line to `puppet epp --values` as those were
simply ignored.
Now, all variable names with '::' are set as fully qualified names and
thus available to epp templates when referenced the same way.
> (PUP-7806) Allow epp CLI to set fully qualified variables

- acceptance/tests/resource/file/content_attribute.rb
- lib/puppet/application/filebucket.rb
- spec/unit/application/filebucket_spec.rb
Previously, using the --local option would use the server's
filebucket instead of the actual local filebucket. This changes behavior
to use the clientbucketdir instead of bucketdir.
> (PUP-5206) Use clientbucketdir instead of bucketdir

- lib/puppet/pops/parser/parser_support.rb
- spec/unit/face/parser_spec.rb
This changes the error message produced when there is a syntax error
because the parser hits the end of its input. When this happens the
parser does not know if the text it is parsing is from a file or from a
string, or from the command line.
Since users found it confusing that the error speaks of "end of file"
when there is no file involved, the best is thought to be naming it "end
of input" as that works for all of the various ways input may be given.
> (PUP-6043) Change syntax error "at end of file" to "end of input"

- lib/puppet/functions/convert_to.rb
- spec/unit/functions/convert_to_spec.rb
This adds a 'convert_to(value, type)' function that can be used to make
chained creation/operations more readable than having to use `new`
(which has the type first), or directly calling the type using `()`.
The `convert_to` also accepts a one-arg lambda to complete the
conversion operation.
> (PUP-7619) Add a 'convert_to' convenience function

- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
A regression in PUP-7864 add the assumption that the 'lib' directory in
puppet would always be present. This assumption is false since the 'lib'
directory is renamed to 'site_ruby' during installation.
There are no unit tests to check this (since a bundle exec always has
a 'lib' under the puppet root). The problem, if present, is however
caught by acceptance tests that uses the loader.
> (PUP-8229) Assume that Puppet 'lib' directory can be relocated

- lib/puppet/gettext/module_translations.rb
- spec/unit/gettext/module_loading_spec.rb
This commit fixes a bug where, when loading module translations, if a
module was encountered for which no tranlsations could be loaded, the
loop exited instead of continuing to iterate over the remainder of the
list.
> (maint) Do not exit loop early when loading module translations

- acceptance/tests/resource/package/common_package_name_in_different_providers.rb
We were skipping tests when the hypervisor was ec2.  I have added support in QENG-5106 to use abs as a hypervisor.  This change will now skip tests for any ec2 host whether created with the ec2 hypervisor or abs hypervisor.
> (QENG-5106) Skipping tests for ec2 hosts

- lib/puppet/functions.rb
- spec/unit/functions4_spec.rb
Before this, errors in `local_types` or in one of the methods that define a parameter type in a 4.x functions raised an unactionable error.
Now the error messages output as much information as they have about the type string being in error, what the error was, and where it came from (as much as it knows).
> (PUP-6162) Improve function local type errors

- docs/quickstart.md
I saw that "RSpec" was capitalized correctly, so I thought I'd give the same treatment to "GitHub".
> Fix capitalization of "GitHub".

- acceptance/tests/resource/package/common_package_name_in_different_providers.rb
Backports the following from the master branch:
```
We were skipping tests when the hypervisor was ec2. I have added support in QENG-5106 to use abs as a hypervisor.
This change will now skip tests for any ec2 host whether created with the ec2 hypervisor or abs hypervisor.
```
> Cherry pick change to skip tests for ec2 hosts unconditionally

- acceptance/tests/resource/package/yum.rb
We were skipping tests when the hypervisor was ec2. I have added support in QENG-5106
to use abs as a hypervisor. This change will now skip tests for any ec2 host
whether created with the ec2 hypervisor or abs hypervisor.
> (maint) Skipping test if facter finds this is an ec2 host

- lib/puppet/module.rb
(PUP-3963) Error message gives wrong advice for allowed module names
Improved the error message concerning an invalid module name to accurately reflect the documentation by removing the hyphen as a valid character, specifying letters must be lowercase and underscores are acceptable, and noting that the name must start with a lowercase letter.
> (PUP-3963) [#puppethack] Improve module name invalid character warning

- lib/puppet/type/schedule.rb
- spec/unit/type/schedule_spec.rb
Previously, you could use a number (0-6) to assign weekdays but they had to be in a string. This was confusing for some users, so this changes the behavior to also accept integers 0-6 as valid days of the week.
> (PUP-7221) Type schedule should accept integers for weekdays

- lib/puppet/functions.rb
- lib/puppet/pops/functions/dispatch.rb
- lib/puppet_pal.rb
- spec/unit/puppet_pal_2pec.rb
This commit makes the `Puppet::Pal::ScriptCompiler` available using a
`Puppet::Context` override. The compiler is available using the symbol
`:pal_script_compiler`.
A new special parameter type named `script_compiler_param` is also added
to the Ruby function dispatcher builder for `InternalFunction`. Usage is
similar to `scope_param` but it injects the script compiler instead of
injecting the scope.
> (PUP-8237) Make Puppet::Pal::ScriptCompiler available to functions

- lib/puppet/parser/scope.rb
- spec/unit/parser/scope_spec.rb
This fixes a TODO for shortening the path to a module when Scope.to_s
does not have a resource and the path on top of the puppet stack is to a
.pp file in a module.
Earlier only paths into the environment got this treatment and paths to
files in modules were output in full.
> (PUP-8235) Shorten paths to file in module in Scope.to_s

- acceptance/tests/ssl/puppet_cert_generate_and_autosign.rb
- lib/puppet/ssl/host.rb
When a user runs Puppet not as root, the error message starts them down
a certificate rabbit hole. This commit adds a friendly reminder and updates the associated acceptance test.
> (DOCS) Update error message [#puppethack]

- acceptance/tests/resource/service/smf_should_be_idempotent.rb
- acceptance/tests/resource/service/smf_should_create.rb
- acceptance/tests/resource/service/smf_should_query.rb
- acceptance/tests/resource/service/smf_should_stop.rb
- lib/puppet/provider/service/smf.rb
- spec/unit/provider/service/smf_spec.rb
The changes made as a result of PUP-6860 and PUP-6797 made non-existent services from the SMF (Solaris service) provider return a state of :absent instead of :stopped. This diverts from what pretty much all of our other service providers do. Customers in the field are reporting PE upgrade errors due to this changed behavior (See PE-22951). 
I'll also note that after Moses made these changes to address PUP-6797, his thinking appears to have evolved, because he later made changes to the AIX service provider that again ensured that non-existent services report :stopped. See:
https://github.com/puppetlabs/puppet/pull/5632
For these reasons I think reverting the commits related to PUP-6860 and PUP-6797 is the way to address the problems customers are having upgrading agents on Solaris.
> (PUP-8262) Revert changes which made non-existent SMF services return :absent instead of :stopped

- acceptance/tests/i18n/check_puppet_run_message.rb
- ext/puppet-test
- lib/puppet/configurer.rb
- lib/puppet/face/catalog.rb
- lib/puppet/indirector/catalog/compiler.rb
- lib/puppet/parser/templatewrapper.rb
- lib/puppet/transaction/persistence.rb
- lib/puppet/util.rb
- lib/puppet/util/storage.rb
Update the benchmark method to have the call pass in a complete sentence
including the ' in %{seconds} seconds' which benchmark can format to
include the time take if it needs to log the message
> (PUP-8131) update the calls to benchmark to pass in complete sentences

- lib/puppet/type/mount.rb
- spec/unit/type/mount_spec.rb
Without this patch, the `mount` type might try to mount a filesystem
before its mountpoint is created.
> (PUP-8106) Make the `mount` type autorequire its `file` mountpoint

- appveyor.yml
- The fix in place here was temporary due to AppVeyor having available
an older Ruby 2.4.x that shipped a buggy OpenSSL 2.0.3 with a race
condition. Without the upgrade to at least OpenSSL 2.0.4, installing
large gemsets would intermittently fail.
* Original RubyInstaller discussion at:
https://github.com/oneclick/rubyinstaller2/issues/68
* Ruby bug is documented at https://bugs.ruby-lang.org/issues/11033
* OpenSSL 2.0.4 contains the patch as of 8/8/2017
https://github.com/ruby/ruby/commit/b08e0ade5baacbc7d4754e9f6afe8d09a3e00bc5#diff-51a5e2412fcf851e37d1883b1ae53de5
* RubyInstaller 2.4.2-2 picked up the fix and was released 9/15/2017
https://rubyinstaller.org/2017/09/15/rubyinstaller-2.4.2-2-released.html
* AppVeyor issue was filed
https://github.com/appveyor/ci/issues/1790
AppVeyor …
> (maint) Remove AppVeyor OpenSSL update

- spec/unit/application/filebucket_spec.rb
Spec test did not fail when code change was reverted.
With this spec test update, the code fails before and passes after this update.
> (maint)(PUP-5206) Update spec test so it fails on code before this update.

- lib/puppet/pops/loader/loader_paths.rb
- spec/unit/pops/loaders/loader_spec.rb
Before this commit, the discovery mechanism would incorrectly consider a
file named plans/init.pp to denote a plan named `<module-name>::init`.
The same thing was true files under tasks with names starting with
'init'.
This commit ensures that the `SmartPath` used for Plans and Tasks is
aware of the 'init' semantics when producing the `TypedName` for the
actual Plan or Target, thus avoiding errors about a name mismatch when
the corresponding entity is loaded.
> (PUP-8271) Make loader discovery find 'init' for plans and tasks

- lib/puppet/pops/types/type_formatter.rb
- spec/unit/functions/new_spec.rb
- spec/unit/functions/step_spec.rb
- spec/unit/pops/types/type_formatter_spec.rb
Several data types have a string representation that includes a range
with min and max values. Such representations will always come last in
an array. When creating type with a range from parameters, it's standard
that when the 'max' parameter is omitted it gets the default (unbounded)
value. This commit ensures that a 'max' with default value also is
omitted when the type is represented as a string. E.g. an integer
created as `Integer[2]` will presented as 'Integer[2]' instead of
'Integer[2, default]'.
> (PUP-8270) Skip range max when presenting types with max == default

- lib/puppet/defaults.rb
- lib/puppet/reference/configuration.rb
- Removes language suggesting splay period is consistent across agent restarts.
- Adds example of how splay works.
- Adds a bullet point noting that splay doesn't persist across restarts.
> (DOC-3310) Fix and expand splay docs.

- lib/puppet/pops/pcore.rb
- spec/unit/pops/types/task_spec.rb
This commit removes the constraint that task parameters must be Data.
> (PUP-8283) Allow non-Data task parameters

- acceptance/README.md
Prior to this commit, we were referencing an incorrect environment
variable to specify if the user wanted to hit a specific git mirror. In
Beaker, the environment variable we look for is either SERVER or
PROJECT_NAME_SERVER (i.e., PUPPET_SERVER). This commit updates
acceptance/README.md to accurately reflect this.
> (PUP-7861) Update git mirror instructions

- acceptance/tests/face/parser_validate.rb
- lib/puppet/error.rb
- lib/puppet/parser/resource.rb
- lib/puppet/resource/catalog.rb
- lib/puppet/util/errors.rb
- lib/puppet/util/log.rb
- spec/integration/parser/collection_spec.rb
- spec/integration/parser/scope_spec.rb
- spec/unit/face/epp_face_spec.rb
- spec/unit/functions/break_spec.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/functions/next_spec.rb
- spec/unit/functions/return_spec.rb
- spec/unit/info_service_spec.rb
- spec/unit/parser/environment_compiler_spec.rb
- spec/unit/parser/resource/param_spec.rb
- spec/unit/pops/evaluator/evaluating_parser_spec.rb
- spec/unit/pops/parser/parse_containers_spec.rb
- spec/unit/resource/catalog_spec.rb
- spec/unit/type_spec.rb
- spec/unit/util/errors_spec.rb
- spec/unit/util/log_spec.rb
Created a common method for making a string of the the location of an error
Changed the error reporting and logging systems to use the common methods
Updated all the unit tests
> (PUP-8127) change the error location output to be translationable

- lib/puppet/application/inspect.rb
- lib/puppet/transaction.rb
- lib/puppet/transaction/report.rb
- spec/unit/application/inspect_spec.rb
- spec/unit/resource/catalog_spec.rb
- spec/unit/transaction/report_spec.rb
Without this patch, exceptions during a transaction that are not caught will not be marked as failed.
Users and tools that use exit status information are not catching these failures due to the incorrect information.
This patch creates a flag that must be positively changed at the end of the transaction flow to allow the transaction to be marked with success.
> (PUP-8288) Report exceptions during transactions as failed status.

- lib/puppet/resource/capability_finder.rb
- lib/puppet/resource/catalog.rb
- lib/puppet/resource/type.rb
- lib/puppet/settings.rb
- lib/puppet/ssl/base.rb
- lib/puppet/type.rb
- lib/puppet/type/file/source.rb
- lib/puppet/type/group.rb
- lib/puppet/type/mount.rb
- lib/puppet/type/resources.rb
- lib/puppet/type/zone.rb
- lib/puppet/util.rb
- lib/puppet/util/fileparsing.rb
- lib/puppet/util/log.rb
- lib/puppet/util/logging.rb
- lib/puppet/util/nagios_maker.rb
- lib/puppet/util/posix.rb
- lib/puppet/util/provider_features.rb
- lib/puppet/util/selinux.rb
Decorate strings when we raise a DevError error so that we'll
have translations for the error (Part 3 of 3)
Coding fix in lib/puppet/type/mount.rb
Added quotes in lib/puppet/type.rb to make this message readable
"The 'is' value is not in the 'is' array for '%{name}'"
> (PUP-8313) raise DevError decorate strings part 3

- spec/unit/indirector/json_spec.rb
This test was attempting to verify that the json terminus would error
in the face of files on disk with binary names. It doesn't actually do
that, and is also broken on High Sierra with APFS
Since this is not a particular valuable thing to test, instead of
attempting to repair the test it is simply being removed.
> (maint) Remove unnecessary binary json test

- lib/puppet/pops/issues.rb
- lib/puppet/pops/loader/base_loader.rb
- lib/puppet/pops/loader/dependency_loader.rb
- lib/puppet/pops/loader/loader.rb
- lib/puppet/pops/loader/module_loaders.rb
- lib/puppet/pops/loader/runtime3_type_loader.rb
- lib/puppet/pops/loader/static_loader.rb
- lib/puppet_pal.rb
- spec/unit/pops/loaders/loader_spec.rb
Before this commit, a function, type, plan, or task declaration that
contained errors would cause the loader discovery to raise an exception.
This is now changed so that the discovery will either raise warnings or
collect errors in an `error_collector` array that can be passed as an
optional argument. If the `error_collector` is provided, errors will not
be logged but instead converted into `Puppet::DataType::Error` instances
and added to the collector.
> (PUP-8259) Make loader discovery report errors instead of failing

- lib/puppet/pops/types/types.rb
- spec/unit/pops/types/type_formatter_spec.rb
Data types with a range min/max that denotes a size should ensure that
the lower bound is set to zero when given as 'default'.
> (PUP-8291) Ensure that default min is 0 for ranges that represent size

- lib/puppet/pops/issue_reporter.rb
We now have 2 different strings for printing if we have errors or
warning and errors when giving up on language validation that are translated
> (PUP-8331) split and add translation for giving up error message

- .travis.yml
Prior to this commit the Travis config included a `before_install`
step which installed bundler at `1.15.4` to resolve an issue with
compatibility in the matrices for Ruby `1.9.3`. However, during
research for MODULES-6339 it was discovered that Travis now keeps
their matrices updated with the latest compatible bundler install.
For all of the builds in this matrix Travis is currently using
bundler `1.16.0` and the builds pass successfully.
This maintenance commit removes the pinned-version install of
bundler and instead returns to relying on Travis to build and
maintain images with compatible versions. This also follows the
advice in the comment in the config file on this step.
> (MAINT) Remove Travis before_install step

- lib/puppet/util/http_proxy.rb
- spec/unit/util/http_proxy_spec.rb
When retrieving file resources from http/https sources, accept all content types (`Accept: */*`), accept compressed content (`Accept-Encoding: gzip,...,identity`), and send our standard `User-Agent` string. Also eliminate a redundant `HEAD` request when retrieving file metadata.
This changes allow puppet to retrieve file sources that don't accept the `binary` content type, e.g. IIS, or other files whose extension maps to a well-known MIME type, e.g. `image/gif`.
> (PUP-7482) Accept all content types with http file sources

- .gemspec
- Gemfile
We no longer rely on gettext-setup at runtime, instead using
fast_gettext directly. This commit adds fast_gettext to the gemspec and
moves gettext-setup to the Gemfile, so it can be pulled in for its rake
tasks used when manipulating translation files at build time.
> (PUP-8249) Remove gettext-setup as a runtime dependency

- lib/puppet/pops/types/type_parser.rb
This adds a table lookup of commonly used data type specifications
in string form; for example 'String', 'Integer', 'Any'.
This has been measured to improve the parsing by 150-200 times.
> (PUP-8327) Make parsing of most common data types 150-200x faster

- lib/puppet/type/user.rb
If you read the docs page describing the user resource, the summary for
the `expiry` parameter says `The expiry date for this user. Must be
provided...`, which might lead a user to believe that the parameter is
required.
This rewords the description so that the truncated version is clearly
not implying a required parameter.
I think there's a high chance that PUP-7663 originated as the user
mistakingly believing that they had to provide a value. (it's also
possible that they've specified defaults in `login.defs` and are trying
to override it for a specific user account.)
> (docs) Reword description to clarify truncated text

- acceptance/tests/resource/package/common_package_name_in_different_providers.rb
- acceptance/tests/resource/package/yum.rb
Skipping tests for ec2 hosts now correctly iterates over the agents rather then hosts.
> (maint) Skipping tests for ec2 hosts

- .travis.yml
- lib/puppet/network/http/webrick.rb
- spec/unit/network/http/webrick_spec.rb
Ruby 2.3.6 and 2.4.3 changed webrick to use nonblocking I/O when accepting client connections[1,2]. This exposed a bug in puppet's webrick handler due to us calling the blocking version of accept on the already connected socket, resulting in:
SSL_accept returned=1 errno=0 state=unknown state: unexpected record
Remove the call to accept, since it's no longer needed, add tests and bump our travis CI matrix, including 2.3.6 which has the new ruby behavior.
[1] https://bugs.ruby-lang.org/issues/14005
[2] https://github.com/ruby/ruby/commit/1beda2970b1c17daf34c15a1ee1c551b29080bdd
> (PUP-8297) Don't accept already connected socket

- lib/puppet/transaction.rb
- lib/puppet/transaction/persistence.rb
- spec/integration/transaction/report_spec.rb
- spec/unit/transaction/persistence_spec.rb
- spec/unit/transaction_spec.rb
In the past enforcing change using "puppet apply" or "puppet resource"
would cause the transactionstore.yaml file to be overwritten. This
happened because persistence was enabled regardless of how
puppet was being run.
This commit adds the `enabled?` method to Transaction::Persistence which
now checks how puppet is being run to determine if persistence should be
enabled, which means we no longer overwrite transactionstore.yaml
during a "puppet apply" or "puppet resource" run.
> (PUP-8227) puppet apply/resource should not overwrite transactionstore

- lib/puppet/face/module/search.rb
Since the PMT search output uses printf to pad the results into
consistent width columns, we need to insert the color modifying control
sequences only AFTER the widths and padding have been calculated,
otherwise the padding calculations will be incorrect when the terminal
interprets the control sequences.
> (PUP-8082) Fix incorrect field padding in colorized PMT search results

- lib/puppet/ssl/oids.rb
- spec/unit/util/monkey_patches_spec.rb
This fixes most tests for ruby 2.4 built with openssl 1.1.0. The biggest issue is that in tests we register our OIDs multiple times, which openssl 1.1.0 complains about.
> (maint) Fix tests for OpenSSL 1.1.0 

- acceptance/tests/resource/service/service_enable_linux.rb
Fixed service_enable_linux.rb test to work with ec2 hosts
> (maint) Fix service_enable_linux.rb test to work with ec2 hosts

- spec/integration/agent/logging_spec.rb
If these tests encounter an error they will just exit without reporting
it. Stubbing exit_on_fail causes the original exception to be raised and
reported as a test failure.
> (maint) Don't exit on error in logging specs

- lib/puppet/type/group.rb
- spec/unit/type/group_spec.rb
(PUP-7968) [#puppethack] Add a default to present for the ensure param
Before this commit, the group resource didn't have a default `ensure => present`, which was inconsistent with other resources such as package (assumes you want to install the package and defaults to `ensure => installed`)
> (PUP-7968) [#puppethack] Add a default to present for the ensure param

- spec/unit/transaction/persistence_spec.rb
Here we change the before :each block into a let block to prevent state
leaking across rspec tests.
> (PUP-8227) Update transaction tests

- spec/integration/provider/cron/crontab_spec.rb
These tests fail when run on a machine where the crontab file is not
suitable. There's no need for this, so just stub it to always be
suitable.
> (maint) Make crontab provider suitable in specs

- lib/puppet/type/user.rb
Clarify when Puppet manages a user's home directory when the
`managehome` parameter is set to true.
> (docs)(DOCUMENT-777)(PUP-8211) Clarify managehome.

- lib/puppet/pops/loader/loader_paths.rb
- lib/puppet/pops/loader/module_loaders.rb
- spec/unit/pops/loaders/module_loaders_spec.rb
Previously, the existing_paths method for the FileBased loader was using
naive string matching to determine which files were associated with a
particular task. This resulted in the wrong set of files being found for
a task, in the case where the name of one task was a prefix of the name
of an adjacent task. For example, task `foo` would match both `foo.py`
and `foobar.py`. The desired behavior is that filenames need to match
all the way up to the file extension, in order to be associated with a
particular task.
This commit changes the existing_paths method to compare basenames
exactly, excluding file extensions.
> (PUP-8357) Correctly match files for tasks

- lib/puppet/util/network_device/config.rb
Use the error_location() to tell the error location when processing
the network device config file
I refactored the code to be more understandable
> (PUP-8347) use error_location for network device config file

- lib/puppet/file_serving/configuration/parser.rb
- spec/unit/file_serving/configuration/parser_spec.rb
Use error_location() in the file_server config file parser code
> (PUP-8347) use error_location in file_server config parsing

- lib/puppet/network/auth_config_parser.rb
- spec/integration/network/authconfig_spec.rb
Use the error_location() method when parsing network auth config files
> (PUP-8347) usr error_location for auth config parsing

- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/serialization/to_data_converter.rb
- spec/integration/parser/compiler_spec.rb
Before this given rich-data (not all data types though) were transformed to String when given as arguments to classes and defines.
This was not good because it works against the purpose of type checking.
> (PUP-8343) let rich data params through to resources

- lib/puppet/network/http/webrick.rb
- spec/unit/network/http/webrick_spec.rb
Previously, our webrick code set the webrick option SSLStartImmediately to true
and then called `SSLServer#start_immediately = false`, in that order. Ruby
versions 2.3.6/2.4.3 and up will skip the call to SSLSocket#accept if the
SSLStartImmediately option is false. However, older versions will skip the call
if the SSLServer `@start_immediately` instance variable is false[1].
Prior to commit a358d5e, newer ruby versions caused an error because
SSLSocket#accept was called twice on the same socket, once by webrick and again
by us.
Commit a358d5e fixed the newer ruby case, but regressed on the older ruby
case, since SSLSocket#accept was never being called.
This commit eliminates the call to `start_immediately = false`, and sets the
configuration option to false. This works as far back as ruby …
> (PUP-8297) Ensure we call SSLSocket#accept once

- lib/puppet/pops/issues.rb
- lib/puppet/util/errors.rb
Updated error_location() to be called with nil when something is not known
but understand empty string too. Along with documentation updates
> (maint) update error_location() to prefer nil and documentation

- lib/puppet/face/module/build.rb
- lib/puppet/face/module/install.rb
- lib/puppet/face/module/uninstall.rb
- lib/puppet/face/module/upgrade.rb
- lib/puppet/module_tool/applications/builder.rb
- lib/puppet/module_tool/applications/installer.rb
- lib/puppet/module_tool/applications/uninstaller.rb
- lib/puppet/module_tool/applications/upgrader.rb
- spec/unit/module_tool/applications/builder_spec.rb
- spec/unit/module_tool/applications/installer_spec.rb
- spec/unit/module_tool/applications/uninstaller_spec.rb
- spec/unit/module_tool/applications/upgrader_spec.rb
We now disallow the module tool operations of install, uninstall, and upgrade
besides building to be able to provide an appropriate error message instead
of the operations getting aborted due to FIPS preventing use of any
unapproved algorithms/operations like MD5.
Module checksums use MD5 and cannot be changed easily without requiring a
large number of design changes throughout.
> (PUP-4963) Puppet module build fails on FIPS enabled system

- acceptance/tests/environment/variables_refreshed_each_compilation.rb
Previously, we used the system_uptime fact as a form of randomness when
testing that topscope variables (ie, return values from pure puppet functions
that do not enter ruby land) were refreshed when environment_timeout was
unlimited.
Unfortunately, facter's system_uptime may not return a valid value on
Windows (see FACT-1504 for details).
To avoid using Ruby on the server, while still having a constantly
changing variable, we continue to use the agents under test to provide a
value (fact) but now move from using system_uptime to an external fact.
> (PUP-8363) Do not use system_uptime fact on windows

- acceptance/tests/resource/service/service_enable_linux.rb
- lib/puppet/provider/service/systemd.rb
- lib/puppet/provider/service/upstart.rb
- spec/unit/provider/service/systemd_spec.rb
Previously I had mistakenly thought that Amazon Linux v2 returned a year-based version string from facter, but that's only the case for Amazon Linux v1. v2 returns "2.0" instead.
> Amazon Linux fixes

- lib/puppet/gettext/config.rb
- spec/unit/gettext/config_spec.rb
If this isn't passed through the tests can fail sometimes depending on
the order in which they're run. I don't think this is ever a problem in
production but adding an argument with a default makes it a little more
robust.
> (maint) Pass through text domain when loading translations

- acceptance/tests/i18n/check_puppet_run_message.rb
Updated the test to use the new translation string
(Now 1 sentence instead of 2 sentence fragments)
> (PUP-8252) update test with new translation string

- acceptance/tests/i18n/modules/puppet_agent_cached_catalog.rb
- acceptance/tests/i18n/modules/puppet_apply_unsupported_lang.rb
The windows ja skip test check should have been a regex
Skip the unsupported lang tests on solaris 10 for now - Filed PUP-8377
> (PUP-8080) fix issues with new i18n tests

- lib/puppet/util/windows/file.rb
- Previously, any file that returned FILE_ATTRIBUTE_REPARSE_POINT
in a call to GetFileAttributes would be considered a "symlink" for
Puppets purpose. This is relevant specifically to file resources.
However, Puppet cannot resolve the destination location for many of
the reparse point types, namely the following (some of which may
not actually resolve to a different path):
IO_REPARSE_TAG_HSM
IO_REPARSE_TAG_HSM2
IO_REPARSE_TAG_SIS
IO_REPARSE_TAG_WIM
IO_REPARSE_TAG_CSV
IO_REPARSE_TAG_DFS
IO_REPARSE_TAG_DFSR
IO_REPARSE_TAG_DEDUP
IO_REPARSE_TAG_NFS
- Modify the behavior of symlink? such that Puppet only considers
reparse points IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_SYMLINK
as resolvable symlinks.
The others will continue to be treated as regular files /
directories.
- Existing symlink? …
> (PUP-8337) Change Windows symlink? check behavior

- lib/puppet/functions/module_directory.rb
- spec/unit/functions/module_directory_spec.rb
This adds the function module_directory() that returns the first found
module's root directory path given one or more module names directly or
in an array.
> (PUP-6977) Add a module_directory(names...) function

- acceptance/tests/i18n/modules/puppet_agent_cached_catalog.rb
Re-enable the cached catalog acceptance test now that the underlying
Ruby issue is fixed.
This is blocked on https://github.com/puppetlabs/puppet-agent/pull/1310
> (PUP-8368) Reenable cached catalog acceptance on Japanese Windows

- Gemfile
`ronn` is used for generating manpages.
> (PUP-8361) Add 'ronn' to the development/test group in the Gemfile.

- acceptance/tests/direct_puppet/supports_utf8.rb
The test included a skip which was pattern matching on ..."|sles-10|)/"
which is an empty string which would match anything and the test would
always be skipped.
> (PUP-8369) fix tests/direct_puppet/supports_utf8.rb to run

- README.md
Update links to the docs site in the README, and point relative
developer docs links to absolute GitHub URLs in order to resolve issues
with YARD-generated docs and the Puppet docs site.
> (docs) Update README links.

- lib/puppet/settings/ini_file.rb
- spec/unit/settings/ini_file_spec.rb
Previously, when we were trying to add a new setting to a section, if the last setting in the section was identical (same prefix, name, infix, value, and suffix) to a setting in another section that came first in the file, we'd get confused about which one we should be adding the new setting after, and add it after the one that appeared first in the file.
We now take the line number of the `SettingLine` into consideration when testing equality (`==`), which means that `Array#index` will no longer give us the index of the first `SettingLine` with the same prefix/name/infix/value/suffix combination as the one we're looking for, and will give us the index of the one that is at the same line number.
> (PUP-5426) Consider an IniFile::SettingsLine to be "different" from another if their line numbers differ

- Gemfile
- README.md
- acceptance/tests/direct_puppet/supports_utf8.rb
Resolves a conflict in a README docs link, and updates the link to point to 5.3.
> Merge up 4.10.x to 5.3.x

- .rubocop.yml
This operator requires Ruby 2.3.0, which means we can't use it in puppet
The most interesting addition to Ruby 2.3.0 is the Safe Navigation Operator(&.).
> (PUP-8400) disable rubocop Style/SafeNavigation

- acceptance/tests/direct_puppet/supports_utf8.rb
Skip the test direct_puppet/supports_utf8.rb on cisco and solaris machines
where the LANG=C is set and we fail due to mixed encoding issues
> (PUP-8369) skip test supports_utf8.rb on cisco and solaris

- lib/puppet/defaults.rb
- lib/puppet/util/platform.rb
- spec/unit/defaults_spec.rb
We need to adjust some settings based on whether fips mode is enabled
or not for FIPS compliance. Till now the later was done using a fact (PUP-8141).
However that created a dependency in puppetserver which cannot load facts in certain configurations like dev testing and running from sources.
This change implements fips mode detection using a local method instead of facter.
> (PUP-8356) Base fips specific behaviors without using facts

- acceptance/tests/modules/build/build_should_not_allow_symlinks.rb
The following test had got left out to be adjusted/skipped when running
on FIPS enabled platform as part of original PUP-8066 work.
- acceptance/tests/module/build/build_should_not_allow_symlinks.rb
> (PUP-8066) Fix failing acceptance tests on FIPS platforms

- lib/puppet/provider/nameservice/objectadd.rb
- lib/puppet/provider/user/useradd.rb
- spec/unit/provider/user/useradd_spec.rb
Fixed the provider to use chage/lchage when password_warn_days is set
Added better unit tests for forcelocal and password_warn_days
Deleted an old version of ObjectAdd.modifycmd() which is overwritten by everything that inherits from ObjectAdd
> (PUP-8381) fix password_warn_days to user chage/lchage

- lib/puppet/provider/ssh_authorized_key/parsed.rb
The fact that `ssh_authorized_key` calls `mkdir` as the target user (as opposed to the user running puppet) is not directly clear and may lead to non-obvious permission errors. Increasing the debug output to indicate this might make the pitfall a bit more clear.
> (PUP-8404) add more debuging to ssh_authorized_key

- CONTRIBUTING.md
This commit updates CONTRIBUTING.md to include more up to date
information on our contribution guidelines.
This includes more details around running tests and more guidance around
the definition of a trivial contribution.
> (docs) Update the contributing guidelines

- Rakefile
Previously running the puppet benchmarks failed with an error "no
implicit conversion of nil into String" when trying to load module
translations.
The issue occurs because puppet initializes FastGettext's default locale
in a way that avoids the "available locales" machinery, by setting
default_available_locales to nil.
Later puppet's Rakefile calls `GettextSetup.initialize`, which
incorrectly sets default_available_locales to an empty array[1]. It
later tries to set the default_locale[2] to 'en'. However, since the
empty array doesn't include 'en', FastGettext.best_locale_in('en')
returns nil[3], and that becomes the default locale.
Since we only need the gettext-setup gem when generating puppet.pot
files in CI, only load it if the currently executing rake task starts
with gettext.
[1] …
> (PUP-8407) Only load gettext-setup when executing gettext rake tasks

- lib/puppet/application/cert.rb
- spec/unit/application/cert_spec.rb
Prior to this commit, running `puppet cert clean` against a
certname that does not have a signed cert but has a CSR would
cause a failure because we tried to revoke the cert when
of course you cannot revoke an unsigned cert.
After this commit, we check to make sure the certname passed into
puppet cert clean is not currently waiting to be signed.  If the
cert is waiting to be signed then we do not try to revoke it and
move along to destroying which clears the CSR.
If you pass a certname that has no signed cert and no CSR then
cert clean will fail in the same way that it did before.
```
[root@split-master ~]# puppet cert list --all
"split-puppetdb-2.puppetdebug.vlan"      (SHA256) 42:3F:8E:C5:68:13:AB:2F:74:6D:2A:D7:83:B4:DB:C9:BB:19:39:C7:97:36:EB:97:55:B3:6D:E0:EF:60:91:5B
+ …
```
> (PUP-1916) Allow cert clean when node has a CSR

- acceptance/tests/environment/variables_refreshed_each_compilation.rb
After the change to use an external fact instead of system_uptime to
deal with a windows issue (PUP-8363), the format of the time string we
get back changed. Early in the day this string can begin with zero,
which causes an Integer cast to interpret it as an octal. We can use
`to_i` to avoid this.
> (maint) Integer cast doesn't work with new fact

- acceptance/tests/i18n/modules/puppet_apply_unsupported_lang.rb
We've updated the i18ndemo module to always raise instead of checking for
openssl which was failing on solaris10. It now passes when run on Solaris10 hosts
> (PUP-8377) update puppet_apply_unsupported_lang.rb to run on solaris

- lib/puppet/face/help/action.erb
- lib/puppet/face/module/generate.rb
- lib/puppet/interface/action.rb
- lib/puppet/interface/action_builder.rb
- spec/unit/interface/action_spec.rb
PR includes:
- Helper methods to allow deprecation of individual face actions.
- Deprecation warning to the help page and cli output of `puppet module generate`. The warning also informs the user that the action has been replaced by PDK and where to get PDK.
> (PUP-7398) Deprecates puppet module generate.

- lib/puppet/pops/evaluator/evaluator_impl.rb
- lib/puppet/pops/types/tree_iterators.rb
- spec/unit/functions/tree_each_spec.rb
Before this, it was not possible to turn the iterators returned by the
function `tree_each` into an Array unless this was done as a `filter` or
`map` operations.
This was caused by two undetected problems:
* the iterator should have implemented `to_a`
* the splat/unfold operator checked for instance of `Iterator` instead
of `Iterable`.
> (PUP-8393) Fix problem transforming tree iterators to Array

- lib/puppet/pops/resource/resource_type_impl.rb
- spec/integration/parser/pcore_resource_spec.rb
Before this, there was a typo in the logic in resource_type_impl.rb
that made it always use the default name pattern of "entire string".
This meant that if the generated type used a different pattern it would
not be used.
> (PUP-8411) Fix typo in impl of processing namevar patterns

- lib/puppet/settings/ini_file.rb
- spec/unit/settings/ini_file_spec.rb
`puppet config` should be able to update an empty setting on the same line, without adding more excess lines.
Previously, if you tried to add a value to an existing setting that had no value, it would place it on the following line. There was a new line being added in the infix instead of the suffix when the file is written, so even if you had previously set the value to `''`, a newline would already be there, and would cause a Parse Error, but still edit the file. So each time you did this, it would add more new lines and error, never actually editing the setting value on the same line as the setting name. This solution strips any existing newlines on the setting before attempting to set the value.
> (PUP-3321) puppet config should be able to alter an empty setting

- lib/puppet/provider/service/redhat.rb
- spec/unit/provider/service/redhat_spec.rb
(PUP-8114) Make enabled state check accurate for SLES 11 boot services in redhat service provider
Without this patch applied, the redhat service provider is not idempotent
in enabling SLES 11 boot services. These are special Sys V services beginning
with the string 'boot.'. When `chkconfig` is run against them, they print
'<name>  B' instead of '<name>  on', so the existing regex does not match them.
Thus the redhat provider always sees them as disabled, and tries to enable
them on each agent run.
This patch adds the '<name>  B' condition to the regex.
```
$ chkconfig boot.kdump
boot.kdump  B
```
Before:
```
$ puppet agent -t --debug 2>&1 | grep -i kdump | grep -i enable
Notice: /Stage[main]/Kdump/Service[kdump]/enable: enable changed 'false' to 'true'
```
After: 
```
$ puppet agent -t …
```
> (PUP-8114) Make enabled state check accurate for SLES 11 boot services in redhat service provider

- lib/puppet/provider/package/dnf.rb
The dnf provider is hard coded to work with Fedora 22-25.  This update
converts the release list into a range which will work Fedora through
version 30.
> (PUP-7046) Update dnf provider to support future Fedora releases

- lib/puppet/type/tidy.rb
- spec/unit/type/tidy_spec.rb
If tidy resource's noop metaparameter is true or false, but not nil,
then generate file resources with the same noop-ness. If the noop
metaparameter is not set, but the Puppet noop setting is, then just
let puppet handle it.
> (PUP-7349) Generated tidy resources should have the same noop-ness

- lib/puppet/pops/loaders.rb
- spec/unit/pops/loaders/loaders_spec.rb
Commit c6ed30db modified the module loaders such that all modules have
visibility into all other modules' content. This was done to support
bolt, but it generally beneficial for all puppet modules. However, the
change increases the module search space and caused a performance
regression.
These commits revert the merge commit c2d64762630716df4af53d98bc7a7f5927fbd740
and restore the behavior for tasks such that modules can call
functions in other modules, e.g. boltlib, without an explicit module
dependency in metadata.json.
> (PUP-6964) Revert c2d6476 due to perf regression

- lib/puppet/application/agent.rb
- lib/puppet/application/apply.rb
- lib/puppet/configurer.rb
- lib/puppet/environments.rb
- lib/puppet/indirector/indirection.rb
- lib/puppet/indirector/request.rb
- spec/unit/application/agent_spec.rb
- spec/unit/application/apply_spec.rb
- spec/unit/configurer_spec.rb
- spec/unit/indirector/indirection_spec.rb
When running apply & agent in noop mode, we do want to be able to retrieve previously cached catalogs according to the "normal" cache lookup rules, but we should never write the retrieved catalog back to the cache.
Since ignore_cache only affects retrieving from the cache, we can't use it to turn off saving to the cache. Also, we do want to be able to look up from the cache so even if it did turn off cache saving, we wouldn't want to use it.
Now, we can explicitly specify that we do not wish to save to the `cache_class` for the terminus by specifying `ignore_cache_save`, and we set that depending on the value of `noop`.
> (PUP-8258) Use Catalog cache in noop mode, but do not write to it

- lib/puppet/module_tool/tar/mini.rb
Fixnum and Bignum are deprecated, use Integer instead.
> (maint) Use Integer instead of Fixnum

- lib/puppet/defaults.rb
- lib/puppet/type/file/checksum.rb
- spec/unit/defaults_spec.rb
- spec/unit/type/file/checksum_spec.rb
FIPS enabled agents will segfault if they attempt MD5 related operations. The `digest_algorithm` is used for filebucketing, and is the default checksum type for file resources. The `supported_checksum_types` setting is used when requesting a catalog, so that the server has an opportunity to inline file metadata in the static catalog.
This PR does not attempt to prevent the user from setting `md5` in puppet settings, as that is a more general problem in puppet.
Supersedes PR #6581
> (PUP-8378) Reject MD5 related digest algorithms in FIPS mode

- acceptance/tests/direct_puppet/supports_utf8.rb
With 5.3.x we handle UTF-8 strings better, so we should run this
test on more platforms.
> (PUP-8397) Update test supports_utf8.rb to run on more platforms

- lib/puppet/face/config.rb
- lib/puppet/settings/ini_file.rb
- spec/unit/face/config_spec.rb
- spec/unit/settings/ini_file_spec.rb
This commit adds a message to every 'puppet config print' invocation on stderr with section and environment, and gives an additional warning about a default section if the '--section' argument is not given.
> (PUP-2868) Give puppet config print info about section

- lib/puppet/indirector/file_content/http.rb
- lib/puppet/util/http_proxy.rb
- spec/unit/util/http_proxy_spec.rb
Prior to commit a5f9d599, puppet agent and apply could both download compressed
file sources using http, however, they followed different code paths to
accomplish the same thing. In the agent case, the `source` parameter's
`each_chunk_from` method calls `HttpProxy.request_with_redirects` with a block,
which had the side-effect of setting the `Accept-Encoding` header explicitly.
This tells Ruby that we accept compressed responses, and more importantly, we
want to decompress the response body, if necessary.
In the apply case, the `each_chunk_from` method calls
`HttpProxy.request_with_redirects` without a block. Although we don't add an
`Accept-Encoding` header, Ruby does[1] (surprise!) and it automagically
decompresses the response body, if neceessary[2].
Commit a5f9d599 changed …
> (PUP-8420) Uncompress http file source response body

- .gemspec
- ext/project_data.yaml
Puppet uses ext/project_data.yaml as the source for its gem dependencies
when it is packaged as a gem. Remove gettext-setup as that is only
needed when generating the pot files containing strings to be localized.
This is a follow up to commit 53aa50aa.
> (PUP-8432) Remove gettext-setup as a runtime gem dependency

- lib/puppet/provider/package/gem.rb
- spec/unit/provider/package/gem_spec.rb
In rubygems 2.7, `gem list` now shows 'default: ' next to the default version of a gem. Puppet tries to include this text as a part of that gem's version number, and it breaks things during a Puppet run.
This simply strips out that string in the gem package provider, leaving only the version number.
> (PUP-8255) 'default' in gem package provider confuses puppet

- lib/puppet/node.rb
- spec/unit/node_spec.rb
Previously we would effectively pre-load the cache of what a node's environment is when initializing from a data hash, but this could be problematic outside of the context of a compilation master.
The biggest problem is that in the context of a compilation master, we have much stronger constraints around what constitutes a valid environment, such as the environment having a corresponding directory on disk (which are enforced by using the #get! version of retrieving an environment object). In pretty much all other contexts, the only real constraint we have around an environment is "it's a string that the compilation master gave us". This would be much less of a problem if we had separate `Node` objects for use in compilation master context & all other contexts, as we could directly use a …
> (PUP-8419) Do not "pre-cache" the Node's environment when creating from a data hash

- lib/puppet/provider/nameservice.rb
- spec/unit/provider/group/groupadd_spec.rb
- spec/unit/provider/group/pw_spec.rb
- spec/unit/provider/nameservice_spec.rb
- spec/unit/provider/user/hpux_spec.rb
- spec/unit/provider/user/openbsd_spec.rb
- spec/unit/provider/user/pw_spec.rb
- spec/unit/provider/user/useradd_spec.rb
We pass the customer_environment when we create a user or group, but not
when we modify or delete it. We should be more consistent
> (PUP-8374) pass our custom_environment to user and group commands

- ext/project_data.yaml
- On Feb 6, 2018, the FFI maintainers released a FFI 1.9.19, then a
1.9.20, failing to produce all the various platform specific gems
that had been published. Both of these versions were yanked, and
a 1.9.21 was released with all the platform specific gem versions.
However, there are a few problems with 1.9.21:
* The Windows gem has inexplicably doubled in size, even though
the changes to the FFI code should have been minor
* There are a number of problems compiling the gem now, on
platforms where it previously worked (CentOS as noted by the
Bolt team + about 10 tickets on the FFI GitHub issue tracker
for a variety of other problems)
For Puppet, this isn't strictly a problem at the moment as Windows
doesn't need to compile gems, but it feels safest at the moment pin
to known working.
FFI …
> (PUP-8438) Pin FFI to 1.9.18

- acceptance/lib/puppet/acceptance/install_utils.rb
- acceptance/setup/aio/pre-suite/010_Install.rb
This commit changes the name of the nightlies server to the actual hostname so that when we remove the 'nightlies' cname (to use for *new* nightlies), tests won't break. THIS SHOULD NOT BE PERMANENT (see RE-10231).
> (maint) Update acceptance tests that reference nightlies

- lib/puppet/configurer/downloader_factory.rb
- lib/puppet/defaults.rb
- spec/unit/configurer/downloader_factory_spec.rb
Previously, *.pot files were excluded from all pluginsync related mounts
(plugins, pluginfacts, locales). Since fact files can be named anything,
and only need to be executable, this could have prevented a necessary
fact from being downloaded to an agent.
Move the *.pot exclusion so it only affects the 'locales' mount.
> (PUP-8436) Exclude *.pot files only during locales sync

- lib/puppet/provider/zfs/zfs.rb
- lib/puppet/type/zfs.rb
- spec/unit/provider/zfs/zfs_spec.rb
Adds property 'acltype' to the accepted list of ZFS properties.
> (PUP-8098) adding 'acltype' as a valid property for a ZFS file system

- lib/puppet/pops/types/p_timespan_type.rb
- lib/puppet/pops/types/type_factory.rb
- spec/unit/pops/types/p_timespan_type_spec.rb
- spec/unit/pops/types/p_timestamp_type_spec.rb
Prior to this commit, a `Timespan[x]` and `Timestamp[x]` would be
interpreted as `Timespan[x,x]` and `Timestamp[x,x]` respectively. This
was inconsistent with `Float` and `Integer` whose interpretation of
one parameter is that the second parameter is unlimited.
This commit changes the `Timespan` and `Timestamp` data types so that
they intepret one single parameter the same way as `Float` and
`Integer`, i.e. `T[x] == T[x, <unlimited>]`.
> (PUP-8439) Change how Timespan and Timestamp interprets one parameter

- spec/unit/application/cert_spec.rb
`ruby -wc` let us know that we had some chained logic in a spec file that wasn't actually chaining. Because of this, we were only using the last test in the chain, instead of and'ing all of the tests together.
> (maint) Remove 'possibly useless use of == in void context' warnings

- lib/puppet/util/windows/adsi.rb
- spec/integration/util/windows/adsi_spec.rb
- spec/unit/util/windows/adsi_spec.rb
(PUP-8231) Support Windows virtual accounts in groups
- When retrieiving a groups members, Puppet has historically returned
the "Name" property of each `IAdsUser` COM component instance when
enumerating the members of a group.
For instance, given a group with members:
```
NT AUTHORITY\SYSTEM (Well known SID S-1-5-18)
%HOSTNAME%\Administrator
Everyone (well known SID S-1-1-0)
IIS APPPOOL\DefaultAppPool
```
The list of members that the ADSI provider would return is:
```
SYSTEM
Administrator
Everyone
DefaultAppPool
```
This is problematic.
The first three accounts will properly resolve via
`Puppet::Util::Windows::ADSI::Group.name_sid_hash`, which uses
`Puppet::Util::Windows::SID.name_to_sid_object` to translate names to
canonical SIDs. The last account `DefaultAppPool`, which is a …
> (PUP-8231) Domain prefix Windows group members

- lib/puppet/face/config.rb
- lib/puppet/settings/ini_file.rb
- spec/unit/face/config_spec.rb
- spec/unit/settings/ini_file_spec.rb
This reverts commit e9bf54fd34387fc6bd9ddc81f97cc9d270e2aa8b, reversing
changes made to 81c7c762ebd4759d727791f718961147d7c64c57.
Reverting this because each time `puppet config set` is called without a
section, it creates a duplicate [main] section. This arises because the
default section in code is :main (symbol), but the default section read
from the inifile is 'main' (string).
> Revert "Merge pull request #6603 from kris-bosland/fix/master/pup-2868"

- lib/puppet/application/cert.rb
- spec/unit/application/cert_spec.rb
Previously, we would pass an empty list of hosts to the `Puppet::SSL::CertificateAuthority::Interface` when asking it to revoke the certificates if all of the certificates we were asked to clean were
unsigned. This broke the CA's expectations, and would cause it to raise an exception. We now only ask the CA to revoke the list of certificates if there is at least one signed certificate in the list of certificates to clean.
This also fixes a spec that was attempting to test for this exact scenario, but wasn't quite stubbing/expecting the method calls on `Puppet::SSL::CertificateAuthority::Interface` correctly to detect the issue.
> (PUP-8448) Only revoke certificates in puppet cert clean if any have already been signed

- lib/puppet/type.rb
- lib/puppet/type/user.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/type/augeas_spec.rb
- spec/unit/type/file_spec.rb
- spec/unit/type/group_spec.rb
- spec/unit/type/user_spec.rb
- spec/unit/type_spec.rb
Prior to this commit, parameters that had a default of false set
wouldn't populate properly. This is because in ruby, both `nil` and
`false` are considered to be 'falsey'. In effect, `defaultto false` was
treated the same as having no default value specified. This is not
ideal, considering there are cases where we treat a param set to `false`
differently then we would if that param were set to `nil`.
This commit fixes the bit in the code that short circuits when default
is set to `false`. Parameters with a default of `false` will not return
nil anymore.
This commit also fixes up some test cases that had worked around this
expectation, either by checking for 'falsiness', or not checking the
default value at all.
> (PUP-8442) Params should allow default of `false`

- lib/puppet/functions.rb
- lib/puppet/indirector/certificate_status/file.rb
- lib/puppet/indirector/facts/facter.rb
- lib/puppet/pops/issues.rb
- lib/puppet/provider/package/pacman.rb
- lib/puppet/provider/package/pip.rb
- lib/puppet/provider/package/pkgdmg.rb
- lib/puppet/provider/package/pkgutil.rb
- lib/puppet/provider/package/portage.rb
- lib/puppet/provider/package/zypper.rb
- lib/puppet/provider/zfs/zfs.rb
- lib/puppet/resource/status.rb
- lib/puppet/transaction/event.rb
- lib/puppet/util/windows/com.rb
- spec/integration/type/file_spec.rb
- spec/shared_behaviours/things_that_declare_options.rb
- spec/unit/interface/action_spec.rb
- spec/unit/provider/cron/crontab_spec.rb
- spec/unit/provider/nameservice_spec.rb
- spec/unit/resource/catalog_spec.rb
- spec/unit/type/mount_spec.rb
`find lib spec -type f -name \*.rb | xargs -n1 ruby -wc > /dev/null` gives a rather large number of warnings. This only addresses a small number of those warnings. Specifically:
* `&` being interpreted as an argument prefix (typically because of a lack of parenthesis around function arguments).
* `*` being interpreted as an argument prefix (typically because of a lack of parenthesis around function artuments).
* Use of `==` in a void context. Typically this means there was a `&&` missing somewhere.
The specific "`==` in void" case that this addresses is because it was originally meant to be an rspec `.should` when it was created, but the `.should` was accidentally left off (which means we never noticed that the test wasn't ever passing).
> (PUP-8463) Warning cleanup

- .rubocop.yml
- ext/regexp_nodes/regexp_nodes.rb
- lib/puppet/external/dot.rb
- lib/puppet/pops/issues.rb
- lib/puppet/provider/service/smf.rb
- spec/unit/provider/service/smf_spec.rb
Turns out that the SMF provider was never actually running `svcs -l <name>` to see if a service was enabled and was instead creating an array that would immediately get thrown away as it was used in void context. We now run the svcs command, and check that it didn't raise a Puppet::ExecutionFailure due to exiting with anything other than a `0` return value.
There were also a handful of other violations that are cleaned up in a separate commit from the SMF change.
> Clean up & enable Lint/Void Rubocop

- lib/puppet/face/man.rb
- spec/unit/face/man_spec.rb
Properly print a default help for "puppet man"
Validate the command line arguments
Added a few basic tests (since we're going to deprecate man)
> (PUP-8444) fix puppet man parsing

- lib/puppet/parser/compiler.rb
- spec/unit/parser/compiler_spec.rb
Rather than relying on node.parameters to populate the topscope environment variable, we now populate this variable by looking directly at the node's environment. This means that if a node terminus sets the environment on a node, but then later sets the node's parameters to a new
hash (instead of merging the new parameters into the existing one), we will now properly populate the topscope environment with a value that matches the node's environment, instead of having it be nil.
> (PUP-8443) Populate topscope environment variable directly from node's environment

- lib/puppet/functions/map.rb
Previously, we had an ambiguous operator that would always cause
warnings when running with JRuby 9k.
These warning are suspected of causing unwanted interactions with
production logging systems and should be removed regardless.
This removes the ambiguous operator usage.
> (PUP-8467) Fix ambiguous operator in functions/map.rb

- lib/puppet/application/apply.rb
- lib/puppet/settings/config_file.rb
- lib/puppet/type/host.rb
- spec/integration/application/apply_spec.rb
- spec/integration/transaction/report_spec.rb
- spec/integration/type/file_spec.rb
- spec/unit/functions/assert_type_spec.rb
- spec/unit/functions/lookup_fixture_spec.rb
- spec/unit/pops/loaders/loaders_spec.rb
- spec/unit/provider/service/base_spec.rb
- spec/unit/provider/service/init_spec.rb
- spec/unit/provider/service/openrc_spec.rb
- spec/unit/provider/service/redhat_spec.rb
- spec/unit/provider/service/systemd_spec.rb
- spec/unit/provider/service/upstart_spec.rb
- spec/unit/puppet_pal_2pec.rb
- spec/unit/type/exec_spec.rb
- spec/unit/type/file_spec.rb
- spec/unit/type_spec.rb
We had a few regexes that had redundant character classes in them, and a large number of cases where we were using the same variable name in an inner scope as a variable in an outer scope, which would mask the outer variable.
While the variable masking wasn't causing any issues in these cases, it can often be the source of confusion.
This does not fix the variable masking in `lib/puppet/vendor/semantic_puppet/lib/semantic_puppet/dependency/module_release.rb` as that is vendored code from another repo, and because fixing the variable masking in that file causes the test suite to use 100+GB of RAM, so we'll need to do some investigation as to what's going on there.
> (PUP-8463) Remove "shadowing outer local variable" and "character class has duplicated range" warnings

- lib/puppet/parser/functions/new.rb
Function reference docs generate a second-level heading for each
function. Having second-level headings inside a function's description
causes issues with the generated docs' hierarchy.
Drop Markdown heading levels to 3rd or lower for all sections.
> (docs)(DOCUMENT-820) Fix function ref headings.

- lib/puppet/functions/all.rb
- lib/puppet/functions/annotate.rb
- lib/puppet/functions/any.rb
- lib/puppet/functions/assert_type.rb
- lib/puppet/functions/call.rb
- lib/puppet/functions/convert_to.rb
- lib/puppet/functions/defined.rb
- lib/puppet/functions/each.rb
- lib/puppet/functions/filter.rb
- lib/puppet/functions/hiera.rb
- lib/puppet/functions/hiera_array.rb
- lib/puppet/functions/hiera_hash.rb
- lib/puppet/functions/hiera_include.rb
- lib/puppet/functions/inline_epp.rb
- lib/puppet/functions/map.rb
- lib/puppet/functions/match.rb
- lib/puppet/functions/reduce.rb
- lib/puppet/functions/tree_each.rb
- lib/puppet/functions/unique.rb
- lib/puppet/functions/unwrap.rb
- lib/puppet/functions/with.rb
Before this, function documentation was written with three tildes and
the language name (or no language).
This is now changed in all 4.x functions as the three tildes syntax is
not standard markdown.
> (docs) Replace 3 tildes (+lang) with 3 backticks

- lib/puppet/face/help/action.erb
- lib/puppet/face/help/face.erb
- lib/puppet/face/man.rb
- spec/unit/face/man_spec.rb
Marked the 'man' face as deprecated
Updated manpage and refereneces to using man to use help instead
> (PUP-8445) mark the man face as deprecated

- lib/puppet/parser/compiler.rb
- lib/puppet/pops/parser/egrammar.ra
- lib/puppet/pops/parser/eparser.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/parser/parse_capabilities_spec.rb
The component of a capability is a type reference but the parser created
a QNAME for it which was then validated using a QREF pattern. This
commit changes this so that the parser instead creates a QREF.
> (PUP-8475) Change capability component to QREF instead of QNAME

- lib/puppet/parser/compiler.rb
- lib/puppet/pops/model/model_tree_dumper.rb
- lib/puppet/pops/parser/egrammar.ra
- lib/puppet/pops/parser/eparser.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/parser/parse_basic_expressions_spec.rb
- spec/unit/pops/parser/parse_calls_spec.rb
- spec/unit/pops/parser/parse_capabilities_spec.rb
- spec/unit/pops/parser/parse_functions_spec.rb
- spec/unit/pops/parser/parse_lambda_spec.rb
- spec/unit/pops/parser/parse_resource_spec.rb
Prior to this commit, the ModelTreeDumper would dump both QNAME and
QREF using their 'value' and thereby render them indistinguishable
in the output since that attribute is always downcased. This commit
changes the dumper so that it uses the 'cased_value' when dumping a
QREF.
NOTE! PR #6656 must be merged before this one or the parse_capability_spec test will fail.
> (PUP-8474) Make ModelTreeDumper dump QREFs using cased value

- lib/puppet/parser/compiler.rb
- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/model/model_tree_dumper.rb
- lib/puppet/pops/parser/egrammar.ra
- lib/puppet/pops/parser/eparser.rb
- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/parser/parse_basic_expressions_spec.rb
- spec/unit/pops/parser/parse_calls_spec.rb
- spec/unit/pops/parser/parse_capabilities_spec.rb
- spec/unit/pops/parser/parse_functions_spec.rb
- spec/unit/pops/parser/parse_heredoc_spec.rb
- spec/unit/pops/parser/parse_lambda_spec.rb
- spec/unit/pops/parser/parse_resource_spec.rb
Before this commit, the parser would create ConcatenatedString instances
with empty string segments when encountering variable references without
curly braces in a double qouted string. I.e "$x" would yield the three
segments <empty string> <text of var x> <emtpy string>. This commit
changes this so that the empty strings are removed.
NOTE: In order to avoid conflicts in spec tests, this should go in after PR #6657 (sorry for the somewhat confusing reverse order of ticket numbers).
> (PUP-8473) Remove empty segments from ConcatenatedString

- lib/puppet/pops/types/p_type_set_type.rb
- lib/puppet/pops/types/type_parser.rb
- spec/unit/pops/loaders/loaders_spec.rb
Before this commit, the TypeSet loader that provides internal access
to the types defined locally in the set was replaced by the loader
that is associated with the file containing the type set source. This
replacement happened in the TypeParser when resolving the types
contained in the TypeSet. This commit prevents that replacement from
taking place.
> (PUP-8471) Prevent TypeSet loader from being replaced

- lib/puppet/datatypes.rb
- lib/puppet/pops/loader/task_instantiator.rb
- lib/puppet/pops/loaders.rb
- lib/puppet/pops/pcore.rb
- lib/puppet/pops/types/implementation_registry.rb
- lib/puppet/pops/types/p_object_type.rb
- lib/puppet/pops/types/ruby_generator.rb
- spec/unit/pops/types/ruby_generator_spec.rb
This PR contains the commits necessary to make the `ImplementationRegistry` parented and to split the `Pcore` initialization into a static part and an environment initialization part.
> (PUP-8481) Load the major part of pcore types statically instead of per environment

- lib/puppet/pops/issue_reporter.rb
- lib/puppet/pops/loader/type_definition_instantiator.rb
- lib/puppet/pops/model/factory.rb
- lib/puppet/pops/types/p_type_set_type.rb
- spec/unit/pops/types/p_type_set_type_spec.rb
This commit improves the TypeSet resolver so that it accepts the
bracket less forms of Object type definitions inside the TypeSet.
> (PUP-8472) Allow Object data type short form in TypeSet

- lib/puppet/functions/map.rb
- spec/unit/pops/factory_spec.rb
- spec/unit/pops/parser/lexer2_spec.rb
The only remaining warnings after this are in an auto-generated file, vendored code from `semantic_puppet`, and spec fixtures that intentionally have errors in them. 🎉
> (PUP-8463) Remove the last lingering warnings

- tasks/manpages.rake
This gets printed at the bottom of every manpage, and since we changed the name of the company like two years ago, it should probably be updated.
> (maint) remove "labs"

- lib/puppet/provider/group/windows_adsi.rb
- lib/puppet/provider/user/windows_adsi.rb
- lib/puppet/util/windows/adsi.rb
- lib/puppet/util/windows/principal.rb
- lib/puppet/util/windows/sid.rb
- spec/integration/util/windows/adsi_spec.rb
- spec/integration/util/windows/principal_spec.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
- spec/unit/util/windows/adsi_spec.rb
- spec/unit/util/windows/sid_spec.rb
(PUP-7326) Handle Windows unresolvable SIDs
- bef10f187f10b5083e73c888d1b4f663ce3a67d9 improved the handling of
account names within local groups that refer to domain or virtual
accounts. Prior to that change, Puppet could not manage groups
with virtual accounts, failed to properly disambiguate accounts
with the same name that came from different authorities (for
example local Administrator from NT AUTHORITY vs domain), and
would produce output from `puppet resource` that didn't include
the authority.
Puppet has always emitted errors when managing groups with
unresolvable SIDs (typically domain accounts that have been deleted
but that are still present in local groups), but the previous 
change degraded the behavior of `puppet resource` so that instead
of producing output like the …
> (PUP-7326) Handle Windows unresolvable SIDs

- MAINTAINERS
Several folks in the MAINTAINERS file no longer actively contribute to Puppet
or have commiters rights. This commit removes them from the MAINAINTERS file.
Signed-off-by: Moses Mendoza <mendoza.moses@gmail.com>
> (PUP-8490) Remove inactive maintainers

- lib/puppet/parser/functions/fqdn_rand.rb
- spec/unit/parser/functions/fqdn_rand_spec.rb
Restoring the old behavior to base seed computation on md5 on non-fips
enabled hosts as it has a cascade effect resulting in problems of multiple
service restarts.
FIPS enabled hosts should expect a change of using SHA256 for seed computation.
> (PUP-8469) fqdn_rand should use md5 on non-fips enabled hosts

- .rubocop.yml
- lib/puppet/file_bucket/file.rb
- lib/puppet/functions.rb
- lib/puppet/indirector/facts/facter.rb
- lib/puppet/module/task.rb
- lib/puppet/network/resolver.rb
- lib/puppet/pops/evaluator/epp_evaluator.rb
- lib/puppet/pops/evaluator/runtime3_resource_support.rb
- lib/puppet/pops/loader/ruby_data_type_instantiator.rb
- lib/puppet/pops/loader/ruby_function_instantiator.rb
- lib/puppet/pops/parser/locator.rb
- lib/puppet/pops/types/class_loader.rb
- lib/puppet/resource/capability_finder.rb
- lib/puppet/ssl/certificate_factory.rb
- lib/puppet/ssl/certificate_request.rb
- lib/puppet/type.rb
- lib/puppet/util.rb
- lib/puppet/util/log.rb
- lib/puppet/util/warnings.rb
- lib/puppet/util/windows/file.rb
- lib/puppet/util/windows/taskscheduler.rb
- lib/puppet_pal.rb
The Lint/UselessAccessModifier can let us know when we think we've marked something as public/protected/private, but haven't. Some examples of common reasons for things being not-actually private are Ruby syntax, or Ruby not actually supporting the thing in question being private at all.
We have a large number of violations of the Lint/UselessAccessModifier cop for a few different reasons:
* Trying to mark constants private. Ruby doesn't do this.
* Trying to mark classes private. Ruby doesn't do this.
* Trying to mark class methods defined using `def self.foo` private. This doesn't work by placing the definition below `private`, and needs to be done by calling `private_class_method :foo` after the method definition.
* Marking the following methods as public when the methods were already …
> (maint) Enable Lint/UselessAccessModifier Rubocop cop

- spec/unit/provider/package/yum_spec.rb
The debug option varies depending on the version of the OS, causing this test to
fail on older redhat systems or newer non-redhat systems with lower version
numbers. It's not relevant to the test so don't check that part.
> (maint) Don't depend on os-specific args in yum test

- lib/puppet/environments.rb
- lib/puppet/face/config.rb
- lib/puppet/settings.rb
- lib/puppet/settings/base_setting.rb
- lib/puppet/settings/ttl_setting.rb
- spec/unit/environments_spec.rb
- spec/unit/face/config_spec.rb
- spec/unit/settings_spec.rb
When showing a setting with config print, without this change values are returned formatted for internal use.
With this change, returned values are formatted like the conf file expects.
> (PUP-8409) Enable config cmd to print conf file compatible format

- lib/puppet/provider/group/windows_adsi.rb
- lib/puppet/provider/user/windows_adsi.rb
- lib/puppet/util/windows/adsi.rb
- lib/puppet/util/windows/principal.rb
- lib/puppet/util/windows/sid.rb
- spec/integration/util/windows/adsi_spec.rb
- spec/integration/util/windows/principal_spec.rb
- spec/unit/provider/group/windows_adsi_spec.rb
- spec/unit/provider/user/windows_adsi_spec.rb
- spec/unit/util/windows/adsi_spec.rb
- spec/unit/util/windows/sid_spec.rb
PR #6647 had a single test failure, but was otherwise ready for merge (but unfortunately accidentally merged). That single fail is addressed in a9d6a83. The additional commits improve some of the messages that appear during error handling.
Comments from original PR #6647:
(PUP-7326) Handle Windows unresolvable SIDs
- bef10f187f10b5083e73c888d1b4f663ce3a67d9 improved the handling of
account names within local groups that refer to domain or virtual
accounts. Prior to that change, Puppet could not manage groups
with virtual accounts, failed to properly disambiguate accounts
with the same name that came from different authorities (for
example local Administrator from NT AUTHORITY vs domain), and
would produce output from `puppet resource` that didn't include
the authority.
Puppet has always …
> (PUP-7326) Handle unresolvable SIDs in Windows groups

- lib/puppet/functions/empty.rb
- spec/unit/functions/empty_spec.rb
This moves the `empty()` function from stdlib to puppet and brings it up
to the 4.x function API. This new version is backwards compatible. It
also adds support for asking a `Binary` value if it is empty.
> (PUP-8492) Move the empty() function from stdlib to puppet

- lib/puppet/provider/user/useradd.rb
- spec/unit/provider/user/useradd_spec.rb
When forcelocal is true and groups are defined for a user, use usermod since
lusermod does not support -G.
> (PUP-8470) Use usermod to manage group membership when user forcelocal is true

- lib/puppet/functions/length.rb
- spec/unit/functions/length_spec.rb
This also adds support for the `Binary` data type, and adds
documentation with examples.
> (PUP-8497) Add the `length` function from stdlib to puppet

- lib/puppet/application/lookup.rb
- spec/integration/application/lookup_spec.rb
This commit ensures that the lookup CLI uses the node terminus "plain"
unless given the --compile flag. The reason for this is that an ENC
can pull in classes and cause a compile anyway.
Acceptance tests must be created to ensure that the lookup CLI works
correctly in combination with an ENC. We need tests asserting that:
1. node terminus "plain" is used by the lookup CLI even when another
terminus such as "exec" is configured.
2. a configured node terminus which is different from "plain" is used
when the lookup CLI is passed the --compile flag.
Both cases have been tested manually.
> (PUP-8502) Use node terminus "plain" for lookup CLI unless --compile

- lib/puppet/type/augeas.rb
- lib/puppet/type/cron.rb
- lib/puppet/type/exec.rb
- lib/puppet/type/file.rb
- lib/puppet/type/package.rb
- lib/puppet/type/schedule.rb
- lib/puppet/type/scheduled_task.rb
- lib/puppet/type/ssh_authorized_key.rb
- lib/puppet/type/sshkey.rb
- lib/puppet/type/tidy.rb
For clarity and to aid in localization, remove Latin abbreviations and replace them with English equivalents.
CC @mindymo; this PR is for the March potholes project with edits to content in code repos used to generate docs content.
> (docs) Replace Latin abbreviations with English.

- acceptance/tests/parser_functions/puppet_lookup_cmd.rb
This commit modifies the existing acceptance tests. The old behavior
asserted that the ENC was always used. The new behavior instead asserts
that the ENC is used only when lookup is invoked with the --compile
option.
> (PUP-8502) Add acceptance test for lookup with ENC

- lib/puppet/pops/types/p_object_type.rb
- spec/unit/datatypes_spec.rb
This commit adds the ability to specify a custom `new_function` in an
Object data type.
> (PUP-8510) Enable custom new_function for ruby Object type implementations

- lib/puppet/functions/flatten.rb
- spec/unit/functions/flatten_spec.rb
This adds the flatten function from stdlib to puppet.
This version is a 4.x implementation of the function and it is backwards
compatible. It adds a new feature in that it will concatenate and
flatten multiple arguments, and this also turns non array values into
being wrapped into an array.
> (PUP-8509) Add flatten() function from stdlib to puppet

- lib/puppet/functions/join.rb
- spec/unit/functions/join_spec.rb
In addition to being backwards compatible this version of `join()` also:
* adds support for joining Iterables (such as from `reverse_each` and 
Hash
* adds support for joining nested hashes and arrays nested in hashes
* improves documentation by including several examples and explains
details about how the join behaves.
> (PUP-8507) Add function `join` from stdlib to puppet

- lib/puppet/functions/empty.rb
- spec/unit/functions/empty_spec.rb
This PR fixes that empty(undef) must return true instead of failing.
This PR also adds deprecation warning for calling empty with Numeric or Undef argument.
> (PUP-8492) make empty(undef) work

- lib/puppet/util/inifile.rb
- spec/unit/util/inifile_spec.rb
Ignore white space that occurs between the '=' and the value so that the
white space is not included as part of the value.
> (PUP-6639) ignore white space after '=' and before the value

- acceptance/tests/environment/enc_nonexistent_directory_environment.rb
- acceptance/tests/environment/environment_scenario-bad.rb
- acceptance/tests/environment/use_agent_environment_when_enc_doesnt_specify.rb
- acceptance/tests/environment/use_agent_environment_when_no_enc.rb
- acceptance/tests/environment/use_enc_environment.rb
- acceptance/tests/environment/use_enc_environment_for_files.rb
- acceptance/tests/environment/use_enc_environment_for_pluginsync.rb
- acceptance/tests/environment/use_environment_from_environmentpath.rb
- acceptance/tests/environment/variables_refreshed_each_compilation.rb
Update a subset of the enc tests
Add a test to verify that we're only compiling and caching the catalog once. (The test catches the regression on agent 5.3.4)
> Task/5.3.x/pup 8459/add test for enc regression

- lib/puppet/error.rb
- lib/puppet/pops/issue_reporter.rb
- lib/puppet/pops/parser/lexer_support.rb
- spec/unit/pops/issues_spec.rb
This commit ensures that the arguments hash used when an issue message
is formatted is retained in logged entries and raised errors. The hash
makes it possible to write tests that asserts that warnings or errors
are emitted with correct input rather than verifying the fully formatted
message using string matching.
> (PUP-8494) Retain issue arguments in logs and errors

- acceptance/tests/catalog_with_binary_data.rb
- acceptance/tests/language/binary_data_type.rb
- acceptance/tests/pluginsync/4420_pluginfacts_should_be_resolvable_on_agent.rb
- acceptance/tests/pluginsync/4847_pluginfacts_should_be_resolvable_from_applications.rb
- acceptance/tests/pluginsync/7316_apps_should_be_available_via_pluginsync.rb
- acceptance/tests/pluginsync/feature/pluginsync_should_sync_features.rb
- acceptance/tests/utf8/utf8-in-catalog.rb
Updated 7 tests to enable them to run in the agent pipeline
I updated the test style and in 3 cases, made serious updates to the tests
commit (Make major test updates...)
I changed the test to actually do a pluginsync (which it wasn't before)
4847_pluginfacts_should_be_resolvable_from_applications.rb
Your best off reviewing the separate commits, as I was careful what I put in each one.
> (PUP-8505) Re-add some server tests back to agent pipeline

- lib/puppet/type/yumrepo.rb
- spec/unit/type/yumrepo_spec.rb
This commit adds support to yumrepo so that it can manage the username
and password for a given repo. This commit also sets password to be
sensitive so that information doesn't show up in any logs.
> (PUP-7400) Yumrepo should manage username/password

- lib/puppet/type.rb
To improve clarity and make localization easier, we should avoid using `(s)` to indicate when something is optionally plural. This PR removes `(s)` from docs generated from code in `/puppet/lib/`, including metaparameter docs.
CC @EamonnTP who reported the issue.
> (DOC-3502) Remove (s) from metaparameter docs.

- lib/puppet/pops/issues.rb
- lib/puppet/pops/parser/heredoc_support.rb
- spec/unit/pops/parser/lexer2_spec.rb
When a heredoc is used with empty endtag spec (for example `@("")`) this
error was reported with an issue code that does not exist causing a
different error to be raised (a Ruby NameError).
This is now corrected and the issue HEREDOC_EMPTY_ENDTAG is raised.
> (PUP-8519) Fix problem with error using missing issue code

- lib/puppet/pops/validation/checker4_0.rb
- spec/unit/pops/validator/validator_spec.rb
Before this, it was considered an error to have a match expression
followed by an expression that uses the numeric variables. This was
caused because the "idem" validation did not consider that match
expression have a potential side effect on the numeric match variables
(setting or clearing them).
This is not changed.
It is however not possible (with reasonable effort and cost at runtime)
to authoritatively find cases when a match does not modify the numeric
variables. It therefore allows all match expressions even if some could
have no side effect and thus be a potential error.
> (PUP-8537) Change match expression validation to have side effect

- lib/puppet/type/k5login.rb
- spec/unit/type/file_spec.rb
- spec/unit/type/k5login_spec.rb
Prior to this commit, if selinux bindings were not available, Puppet
would be unable to see what the selinux attributes were currently set
to. This would trigger a sync where puppet would attempt to set the
attributes, even though we have no way of managing them. This commit
sets the parent of the sel specific parameters to those defined in
puppet/type/file/selcontext.rb. This brings with it `insync?` which
checks for selinux support, and returns `true` if there is none.
This says that we cannot read in the current state, so we are not
attempting to manage it, so don't try to sync it.
Adding this parent also means we can remove the default getters and
setters for these parameters, since we can use the sync and retrieve
methods defined in selcontext.rb as well.
We had to add the stat …
> (PUP-8477) Ensure selinux params not set every run

- api/docs/http_api_index.md
- api/docs/http_facts.md
- conf/auth.conf
- lib/puppet/application/facts.rb
- lib/puppet/face/facts.rb
- lib/puppet/indirector/facts/rest.rb
- lib/puppet/indirector/facts/yaml.rb
- lib/puppet/network/http/api/indirected_routes.rb
- spec/unit/face/facts_spec.rb
- spec/unit/indirector/facts/rest_spec.rb
- spec/unit/indirector/facts/yaml_spec.rb
- spec/unit/network/http/api/indirected_routes_spec.rb
This changeset reverts pieces of [PUP-2560](https://tickets.puppetlabs.com/browse/PUP-2560) in order to re-add the ability to upload facts outside of a catalog request. Specifically, this patch re-adds the following functionality:
- The `puppet facts upload` command.
- The Puppet::Node::Facts::Rest terminus for saving facts to Puppet Servers.
- The ability to handle requests for the `/puppet/v3/facts` endpoint.
> (PUP-8232) Add back 'puppet facts upload' face and update

- lib/puppet/face/config.rb
- spec/integration/faces/config_spec.rb
- spec/unit/face/config_spec.rb
Without this change, it is confusing to users what section is used in the config when they don't specify a section for the config command.  With this change, a message is printed to stderr for all commands, and an extra warning is given to the print command if the user doesn't specify a section.
> (PUP-2868) Add information about section and environment to config

- lib/puppet/functions/eyaml_lookup_key.rb
- lib/puppet/functions/yaml_data.rb
- spec/unit/pops/lookup/lookup_spec.rb
Prior to this commit, a warning would be logged when data that was read
by the lookup function `yaml_data` or `eyaml_lookup_key` wasn't in the
form of a hash. This commit retains that behavior with the addition that
if `--strict=error` is given, and the data doesn't indicate an empty
file (`YAML#load` returns `false` for this), then an error will be
raised.
> (PUP-8541) Make lookup of yaml_data fail on bad data when --strict=error

- lib/puppet/functions/lookup.rb
- lib/puppet/pops/lookup.rb
- lib/puppet/pops/lookup/lookup_adapter.rb
- spec/unit/application/lookup_spec.rb
- spec/unit/functions/lookup_spec.rb
- spec/unit/pops/lookup/interpolation_spec.rb
This adds support for convert_to in lookup_options.
The convert_to key should be either String (a data type string), or Tuple[String, Any, 1].
The result is only converted at the very end.
There is no conversion of a default value given to the lookup function,
or returned from a block computing the default value - they must return
the expected result type.
> (PUP-7675) Add support for convert_to lookup option

- lib/puppet/confine.rb
- spec/unit/confine_spec.rb
When `always_retry_plugins` is not set we can cache the result of
Confine tests to avoid repeatedly requiring a file that doesn't exist.
Require calls generate a lot of garbage so this is a meaningful
optimization.
> (PUP-8485) Cache failed confine lookups

- lib/puppet/type/yumrepo.rb
The target parameter does not work for yumrepo. So change the description 
so that we inform the user that the parameter will be enabled in a future
release and should not be used.
> (PUP-8542) change target description from yumrepo

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
This is a trivial patch that adds support for Ubuntu 17.04 and 17.10.
> (PUP-8495) Systemd support, Ubuntu 17.04 and 17.10

- lib/puppet/util/plist.rb
- spec/unit/util/plist_spec.rb
Previously, puppet would try to read plist files with the CFPropertyList
gem. If that failed, it would use `plutil -convert xml1 -o /dev/stdout` to
attempt to work around any issues with the file. It appears, though, that
writing to /dev/stdout directly in ruby 2.4 is blocked.
plutil's man page suggests '-o -' instead:
-o path Specify an alternate path name for the result of the -convert
operation; this option is only useful with a single file to be converted.
Specifying - as the path outputs to std-out.
This commit changes the plutil command accordingly, letting certain malformed
plists be read correctly.
> (PUP-8545) Don't write directly to /dev/stdout

- lib/puppet/pops/parser/epp_support.rb
- spec/unit/pops/parser/lexer2_spec.rb
This changes the default behaviour of an EPP comment `<%#` to not trim
left by default as that is both not compatible with ERB and makes it
hard to use when spaces should be kept.
To make it possible to trim left, a new EPP tag `<%#-` has been added
that will make the EPP comment behave as it did prior to this change.
> (PUP-8476) Make EPP comment not trim left by default and add <%#-

- lib/puppet/type/tidy.rb
- spec/unit/type/tidy_spec.rb
Adds a check to the `tidy?` function to ignore file paths that are already managed by file resources, since `tidy` cannot generate file resources for those paths anyway.
> (PUP-7307) Only tidy unmanaged files

- lib/puppet/network/http/connection.rb
This is an improvement for PUP-3238, though not a solve.
Net::HTTP will raise an EOFError when something goes wrong at the network stack level, such as a connection being interrupted or terminated by a load balancer in the middle of a transaction. By default, Ruby raises an EOFError with the message "end of file reached" and no backtrace.
This commit catches EOFError exceptions raised by Net::HTTP#request, and re-raises the EOFError with a meaningful message and backtrace. Because this type of error is typically caused by problems from the network stack level, which are frequently timeout-related, the error message will include how long the request ran before termination.
At the very least it will be much clearer what is happening when these kinds of errors occur. It will also show a …
> (maint) Add trace, clearer message to EOFError

- lib/puppet.rb
Deprecate end of life versions of ruby.
> (PUP-8504) Deprecate Ruby < 2.3.0

- lib/puppet/provider/service/systemd.rb
- spec/unit/provider/service/systemd_spec.rb
As requested in https://github.com/puppetlabs/puppet/pull/6706#issuecomment-373134781
~Removing any versions from `defaultfor :operatingsystem => :ubuntu` should be work in the same way like `defaultfor :osfamily => :redhat` in systemd.rb and redhat.rb~
Add 18.04 to the list for systemd.
> (PUP-8495) Systemd support, Ubuntu 18.04

- lib/puppet/provider/yumrepo/inifile.rb
- spec/unit/provider/yumrepo/inifile_spec.rb
In the event that a yumrepo file is deleted after a prefetch has been called,
puppet attempts to stat the deleted file when updating another yumrepo
resource. Instead we check to make sure the file exists on disk before calling
stat.
> (PUP-8421) Do not attept to fix permission on yumrepo files that do not exist on disk

- lib/puppet/util/tagging.rb
- spec/unit/util/tagging_spec.rb
Previously, when checking if a string was a valid tag we would not
ensure the encoding of either the tag string or the validation regex.
Usually, when one is in a "compatible" encoding of the other, ie the
string is in ASCII_8BIT and the regex is in UTF_8 Ruby will attempt to
"do the right thing" and convert one to the other.
However, this implicit converstion may convert the regex to the value
of the string, which means a new regex will be compiled each time a
string with a different encoding is reached. And because we will often
read manifests of one encoding and then create strings out of them into
a different encoding we may end up recompiling the regex frequently
during a catalog compilation. This is primarily a problem because the
character class `[[:alnum:]]` that we use in tag …
> (PUP-8549) Force tag validation to be done in UTF-8

- .gemspec
- .travis.yml
- Gemfile
- appveyor.yml
- docs/quickstart.md
- ext/project_data.yaml
- lib/puppet.rb
Remove support for end of life rubies.
> (PUP-8483) Require Ruby 2.3.0 or up

- lib/puppet/type/yumrepo.rb
- spec/unit/type/yumrepo_spec.rb
The default priority is 99 so limiting it with puppet to
99 too made it impossible to add a repository with a lower
priority to protect system packages. This change removes
this limitation.
> (PUP-4678) Allow yumrepo priority below the default

- lib/puppet/util/json.rb
JrJackson will parse very large or small numbers as BigDecimals rather
than floats. BigDecimals are rendered as strings by the built-in JSON
gem, resulting in strings where our schemas are expecting numbers. This
commit adds an option to the MultiJson options hash when using the
JrJackson backend, disabling the parsing as BigDecimal. JrJackson will
now parse all numbers as basic number types instead.
> (PUP-8583) Prevent JrJackson from using BigDecimals

- lib/puppet/provider/user/aix.rb
Prior to this PR the AIX user resource would fail on newer AIX releases. IBM changed the behavior of `chpasswd` to error when extra parameters were sent to the `chpasswd` command, so setting the password on AIX 7.1 SP5 and AIX 7.2 SP1 would fail. The command contained an unnecessary parameter, which this PR removes.
> (PUP-8538) Remove chpasswd username for AIX

- ext/upload_facts.rb
- lib/puppet/application.rb
- lib/puppet/application/face_base.rb
- lib/puppet/application/resource.rb
- lib/puppet/module_tool/dependency.rb
- lib/puppet/network/http/compression.rb
- lib/puppet/util/checksums.rb
- lib/puppet/util/instance_loader.rb
These were discovered with the aid of RubyMines `Incorrect call argument count` inspection, which is just one of many inspections it supports in code analysis..  There were a lot of false positives that turned up, but these seem legit.
> (maint) Address incorrect argument passing within Puppet

- acceptance/Gemfile
This pulls in updates to how puppetserver is installed. It allows us to
access the newly reformated nightlies repos so that we can test against
the latest passing puppetserver packages.
This will not impact the puppet 4.10.x tests, as those must still be
pinned to a specific puppetserver release.
> (maint) Bump beaker-puppet to 0.12

- spec/integration/parser/compiler_spec.rb
This removes strict=off in a before around relationship tests
that always error. This is done since the behavior is no longer
under control of the strict flag and the change from being under control
of strict happened several releases ago.
It is just confusing to test with strict=off for behavior that is the
same for all settings of strict (we are not testing this for all other
things in the code base).
> (maint) Drop strict=off around tests no longer needing this

- lib/hiera/scope.rb
Before this, the general handling of undefined variable caused the throw
of :undefined_variable to be translated into an exception  - which in
turn was handled under the control of Puppet[:strict], leading to a
warning or error (or no action).
When running on j9k JRuby it has been showed that the exception is aprox
70 times slower than catching the symbol, and thus when running with
strict mode off or warning, the performance suffers greatly.
This commit adds a catch around the call to `lookupvar` in the special
scope used with hiera and issues the same warning/error under control of
Puppet[:strict] as the original implementation in the real Scope.
> (PUP-8486) Catch undefined_variable in hiera's scope

- lib/puppet.rb
- spec/unit/puppet_spec.rb
Puppet.newtype has officially been deprecated since 5ceefea32da (2014-11-12), when it started issuing a deprecation warning, and has internally been considered deprecated since 2011. After a nearly four-year deprecation cycle, we're finally removing the method.
> (PUP-7078) Remove Puppet.newtype
