puppetlabs/puppet

acceptance/tests/ticket_6857_password-disclosure-when-changing-a-users-password.rb
We've updated how passwords are redacted, but I forgot to update these
acceptance tests. Oops!
=> (PUP-8514) Update acceptance tests for password change

lib/puppet/defaults.rb
The configtimeout setting has been deprecated since 2014-11-13, in 462d43ecdb, and was replaced by `http_connect_timeout` and `http_read_timeout`.
Note: This PR doesn't update the `puppet.conf` manpage, as that should be automatically taken care of by CI.
=> (PUP-8534) Remove deprecated configtimeout setting

lib/puppet/type/user.rb
Note use of Sensitive data type to redact passwords from user resources and provide an example.
=> (PUP-7057) Mention Sensitive type in password prop.

lib/puppet/parser/functions/return.rb
Apply suggested documentation updates from [PUP-7904](https://tickets.puppetlabs.com/browse/PUP-7904) explaining this function's usage in lambdas.
=> (PUP-7904) Update return() documentation.

lib/puppet/error.rb, lib/puppet/functions/break.rb, lib/puppet/functions/empty.rb, lib/puppet/functions/next.rb, lib/puppet/functions/return.rb, lib/puppet/functions/strftime.rb, lib/puppet/parser/functions/create_resources.rb, lib/puppet/parser/scope.rb, lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/pops/puppet_stack.rb, lib/puppet/pops/serialization/to_data_converter.rb, spec/unit/parser/functions/create_resources_spec.rb, spec/unit/pops/puppet_stack_spec.rb
All place where the stacktrace is used the logic is only interested in
getting the file, line from the top of the stack.
This commit adds a top_of_stack method to PuppetStack and makes use of
that in all locations where file & line are needed.
If it proves that getting the entire caller() stack is time consuming,
it can be changed to loop over the history in batches of n.
=> (PUP-8610) Speedup PuppetStack by adding top_of_stack and use that

lib/puppet/functions/empty.rb, spec/unit/functions/empty_spec.rb
Before this (introduced in Puppet 5.5.0), the empty function would issue
a deprecation warning for empty(undef). This deprecation is now dropped.
=> (PUP-8623) Drop deprecation of empty(undef)

lib/puppet/parser/compiler/catalog_validator/relationship_validator.rb, spec/integration/parser/compiler_spec.rb
Before this, the error that resulted when trying to use a resource
reference consisting of only a String title did not include any
information about the source location.
Now the catalog validator rescues this error and re-raises it with
location information.
=> (PUP-8498) Make sure faulty resource ref is shown with location info

lib/puppet/pops/parser/epp_parser.rb, lib/puppet/pops/parser/lexer2.rb, spec/unit/functions/epp_spec.rb
Before this the lexer read with only encoding set - it needs to also pass in mode = 'rb' in order to preserve line endings when reading on windows.
The special method "read_preserve_line_endings" available in the Windows implementation of FileSystem cannot be used as it takes no options and cannot be guaranteed to return UTF-8 (which it must for EPP).
The change here is simply to pass in `:mode => 'rb'`
=> (PUP-8240) make epp read with preserved line endings

lib/puppet/provider/augeas/augeas.rb, spec/unit/provider/augeas/augeas_spec.rb
The argument for commands like 'set' can be enclosed in single or double
quotes. To place the quote character into the string, they can be escaped
with a backslash.
So far, the provider did not remove the backslash-escape from the string,
making it impossible for users to have, e.g., a plain double quote inside a
double-quoted argument.
With this change, backslash-escaped quote characters are unescaped from
strings that are enclosed with that quote character; e.g., a
backslash-escaped double quote is reduced to just a double quote in a
string enclosed in double quotes (but left untouched if the string
is enclosed in single quotes)
Fixes https://tickets.puppetlabs.com/browse/PUP-8561
=> (PUP-8561) Augeas provider: unescape escaped quotes

Rakefile
Previously the `rake warning` task would fail if the range of commits
included a deleted file. Restrict the check to files that were added,
modified or copied, but not deleted, renamed, etc.
=> (maint) Exclude deleted files from warning task

lib/puppet/configurer.rb, lib/puppet/transaction/report.rb, spec/unit/configurer_spec.rb, spec/unit/transaction/report_spec.rb
Without this change, the reported total time is incorrect, since it was double counting.
With this change, the total is now reported from measuring the time of the run operation.
=> (PUP-6344) Capture the time of the entire run as the total

lib/puppet/parser/ast/pops_bridge.rb, lib/puppet/resource/type.rb, spec/unit/resource/type_spec.rb
Before this, in some circumstances puppet ends up wanting to merge
definitions into main. When freeze_main is on, the check for allowed
merge was very simplistic and did not allow for definitions to be
merged. This is always ok since they are just definitions that does not
lead to any declaration of resources in the catalog.
=> (PUP-8637) Allow merge of definitions to main when --freeze_main is on

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
Previously if anything raised during a run, the total time would be nil, as the thinmark wouldn't be able to return & set run_internal_time. To get around this we're now manually recording when the run_internal starts, and comparing that against Time.now at the end to record the total run time.
=> (PUP-6344) Always populate total time metric in reports

lib/puppet/type/file/content.rb, spec/integration/type/file_spec.rb, spec/unit/type/file/content_spec.rb, spec/unit/type/file/source_spec.rb
We will be removing the ability to use checksum in the content property to
retrieve content from the filebucket. Properties checksum and checksum_value
should be used instead.
=> (PUP-7534) Add deprecation warning for file checksums in content property of file type

lib/puppet/face/module/install.rb, lib/puppet/face/module/list.rb, lib/puppet/face/module/search.rb, lib/puppet/face/module/uninstall.rb, lib/puppet/face/module/upgrade.rb, lib/puppet/forge.rb, lib/puppet/module.rb, lib/puppet/module_tool.rb, lib/puppet/module_tool/applications/installer.rb, lib/puppet/module_tool/applications/uninstaller.rb, lib/puppet/module_tool/applications/upgrader.rb, lib/puppet/module_tool/installed_modules.rb, lib/puppet/module_tool/local_tarball.rb, lib/puppet/module_tool/shared_behaviors.rb, lib/puppet/node/environment.rb, lib/puppet/vendor/semantic_puppet/lib/semantic_puppet/version_range.rb, spec/unit/face/module/list_spec.rb, spec/unit/face/module/search_spec.rb, spec/unit/module_spec.rb, spec/unit/module_tool_spec.rb
This commit removes the option to have relaxed semver in the puppet
module tool. When this was added it caused problems because puppet agent,
puppet server, and puppet all store and look for semantic_puppet in different
locations and with different methods with differing number of arguments, which
caused major discrepancies between versions. This also caused some semver
issues with installing directly from the forge with the PMT. This is the first
step to completely unvendoring semantic_puppet so that it can exist in only one
place and all three products get it from the same location. Removed all
references to strict_semver as well as related logic around pre-release
versioning, code checking to see if this option was set, as well as all related
tests for this option.
=> (PUP-8558) Remove strict_semver option from PMT and always enforce strict semver logic.

lib/puppet/type/tidy.rb
Having the "File does not exist" message from the tidy resource can be very chatty for letting a user know that their desired state is already achieved. The message can still be useful for debugging, however. So, we now only emit the message if the log level is debug or higher.
An example of when the "File does not exist" message would be annoying, is if there is a tidy resource for the directory `/tmp/foo`, with `rmdirs => true`. The tidy resource would remove the `/tmp/foo` directory itself, and subsequent runs would emit the "File does not exist" message until something recreated the `/tmp/foo` directory.
=> (PUP-8667) Move tidy's "File does not exist" message from info to debug

lib/puppet/ssl/validator/default_validator.rb, spec/unit/ssl/validator_spec.rb
Previous to this commit, the DefaultValidator took a parameter of a
Puppet::SSL::Host to initialize. This commit removes that requirement and does
the lookup for the ssl_host if #setup_connection method is called. This allows
for any arbitrary class to still use this class for for SSL verification without
requiring the need for a Puppet::SSL::Host.
=> (PUP-8655) Remove host parameter for validator initialization

lib/puppet/pops/types/types.rb, spec/unit/functions/new_spec.rb
This is a bugfix since `Numeric("0")` should return `0`.
Instead it raised an error.
=> (PUP-8703) Fix error raised from Numeric("0")

lib/puppet/functions/sort.rb, spec/unit/functions/sort_spec.rb
This adds the sort function from stdlib to puppet and makes it possible to use a lambda to do the compare.
Note that this needs to be merged after PUP-8603.
=> (PUP-8605) add sort function from stdlib

lib/puppet/vendor/load_semantic.rb, lib/puppet/vendor/semantic/lib/semantic.rb
I was having troubles updating/re-loading my gem list locally post https://github.com/puppetlabs/puppet-runtime/pull/55 so some tests were failing for me. They may still need to be updated/removed but figured I'd open the PR to see if they worked on jenkins.
=> (PUP-7157) remove 'semantic' shim from puppet

acceptance/tests/parser_functions/puppet_lookup_cmd.rb
Remove unused variables which cause ruby -wc to fail.
=> (maint) Remove unused variables

lib/puppet/transaction/report.rb
- lak introduced this original code in Feb 2010, using the
initializer for Resource in 9919b14f262c994a58eb202cda408f1b90d728e
- At this point in time, the Resource::Status object was not very
well defined, and did not contain the type of resource in the
`resource_type` attribute.
- Later in Dec 2010 the resource_type value was added in
1f72c31f9e0223e71e2729da96e0e98ebea5417 but not all code was
refactored to take advantage of this
- This code simply uses what is already available, rather than
creating a new Resource instance that is immediately thrown away,
solely for the sake of retrieving the type
=> (PUP-8746) Minor report metric optimization

lib/puppet/external/dot.rb, lib/puppet/graph/simple_graph.rb, spec/unit/graph/simple_graph_spec.rb
When using resource names with quotes, the `--graph` functionality of puppet produce a broken dot file:
```
λ dot /var/puppet/state/graphs/relationships.dot
Error: /var/puppet/state/graphs/relationships.dot: syntax error in line 5765 near '"'
```
The [puppetlabs/puppetlabs-postgresql](https://github.com/puppetlabs/puppetlabs-postgresql) generates [a](https://github.com/puppetlabs/puppetlabs-postgresql/blob/5d50a6658bd49bf2c58478d4258ef06f614c4bc3/manifests/server/schema.pp#L46) [lot](https://github.com/puppetlabs/puppetlabs-postgresql/blob/5d50a6658bd49bf2c58478d4258ef06f614c4bc3/manifests/server/schema.pp#L53) [of](https://github.com/puppetlabs/puppetlabs-postgresql/blob/217405e04c1872501df9f67800ad2df6390e213e/manifests/server/database.pp#L76) …
=> (PUP-2838) Fix invalid .dot files due to missing escapes of quoted strings in resource names

lib/puppet/functions/convert_to.rb, spec/unit/functions/convert_to_spec.rb
Before this it was only possible to call convert_type() with just the
type but not with arguments to the type's new() function.
This is now possible.
=> (PUP-8761) Make convert_to() accept additional arguments

lib/puppet/indirector/request.rb, lib/puppet/network/resolver.rb, lib/puppet/rest/client.rb, lib/puppet/rest/route.rb, lib/puppet/rest/routes.rb, lib/puppet/ssl/host.rb, spec/unit/indirector/request_spec.rb, spec/unit/network/resolver_spec.rb, spec/unit/rest/client_spec.rb, spec/unit/rest/route_spec.rb
This adds SRV support with caching to Puppet::Rest::Client. It updates the existing Puppet::Network::Resolver to cache the results of a DNS lookup per service, subject a TTL. In the new REST client, when a server is chosen for a given request, that chosen server is cached until it can't be reached, at which point servers are re-resolved. If SRV records are in use, the Network::Resolver will check its cache at this time, and either return the appropriate cached list of DNS records or query DNS again if the TTL for that service has expired.
=> (PUP-8705) Add SRV record support with caching

lib/puppet/pops/loader/loader_paths.rb, lib/puppet/pops/loader/module_loaders.rb, lib/puppet/pops/loader/task_instantiator.rb, lib/puppet/pops/pcore.rb, spec/unit/pops/loaders/loader_spec.rb, spec/unit/pops/loaders/module_loaders_spec.rb, spec/unit/pops/types/task_spec.rb
Previously, tasks could only have a single executable and a metadata file.
Any task with more than one executable would fail to load. In order to
support cross-platform tasks, we now allow tasks to have multiple
implementations, differentiated with the new 'implementations' key in the
metadata.
The 'implementations' key is a list of executable files, along with a set
of 'requirements', which are implementation-defined features that necessary
to run that version of the task. A task can have multiple executables, so
long as the implementations key is present and lists them. If there are
multiple executables but no implementations key, the task will fail to load
as before.
It is now also possible for tasks to refer to executables that *don't* match
the task name. This allows for multiple …
=> (PUP-8588) Support multiple implementations for a single task

lib/puppet/defaults.rb, lib/puppet/pops/serialization.rb, lib/puppet/pops/serialization/from_data_converter.rb, lib/puppet/resource.rb, spec/unit/pops/serialization/to_from_hr_spec.rb, spec/unit/resource/catalog_spec.rb
This shortens the tags used by pcore rich serialization to use the
shorter tags `__ptype` and `__pvalue`.
=> (PUP-8597) Change __pcore_<tag>__ to __p<tag>

lib/puppet/util/log/destinations.rb, spec/unit/util/log/destinations_spec.rb
This fixes PUP-8773 whereby setting the `--logdest` option to a JSON file target causes the following:
```
[root@localhost ~]# /opt/puppetlabs/bin/puppet agent -t --noop --logdest "/tmp/foo.json"
/opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/multi_json-1.13.1/lib/multi_json.rb:130:in `current_adapter': undefined method `[]' for #<File:/tmp/foo.json> (NoMethodError)
from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/json.rb:61:in `dump'
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log/destinations.rb:112:in `handle'
from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:191:in `block in newmessage'
from …
```
=> (PUP-8773) Fix logging to a JSON file target

acceptance/fixtures/manifest_large_exported_classes_node.pp
tested with `HOSTS=centos7-64ma SHA=5.3.6 TESTS=tests/face/parser_validate.rb be rake ci:test:aio`
introduced for PUP-5982 @ 524dff2c
affected branches:
4.7.x
5.0.x
5.3.x
master
edit: updated target branch.  fork branch remains the same with unfortunate magic number
=> (maint) acceptance: remove some personal info

acceptance/tests/modulepath.rb, lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
Append the vendor_modules directory to the basemodulepath setting so that vendored modules are available in all environments.
On most platforms, the resulting basemodulepath corresponds to global, site and vendored modules directories, respectively.
On Windows, the resulting basemodulepath contains at least the global modules directory. Additionally if the env_windows_installdir fact[1] is set, which it is when running from puppet-agent packages, then we include the site and vendored modules directories.
For all platforms, the global modules directory ($codedir/modules) depends on whether we are running in a privileged context or not (so it's either in /etc/puppetlabs or ~/.puppetlabs).
[1] https://puppet.com/docs/facter/3.11/core_facts.html#envwindowsinstalldir
=> (PUP-8582) Add vendor_modules to basemodulepath

lib/puppet/type/file/mode.rb
Fix to a string appearing in generated reference docs.
=> (DOCS) fix 'and/or' in generated docs

lib/puppet/pops/pcore.rb, spec/unit/puppet_pal_2pec.rb
Make default input_method nil instead of "both". This allows Bolt to define default input_method based on combo of task language and transport.
=> (PUP-8898) Change default input_method for Task

lib/puppet/reference/configuration.rb
Some `puppet.conf` settings are modified in a default PE installation. This leads to some customer confusion, such as assuming the open source configuration reference generated from Puppet code is incorrect (DOCUMENT-803).
This PR adds a bullet point to the top of the configuration reference noting that PE defaults might differ, provides examples, and reminds users to check `puppet.conf` to confirm PE defaults. An equivalent paragraph is also being added to the PE configuration overview.
CC @melamos
=> (docs)(DOC-3458) Note that PE defaults may differ

lib/puppet/util/windows.rb
Currently I am seeing the following error message:
`bundler: failed to load command: pdk (/Users/paula/workspace/puppetlabs-motd/.bundle/gems/ruby/2.5.0/bin/pdk)
NameError: uninitialized constant Puppet::Util::Platform
`
As puppet is not being required the code doesn't have access to the following: `Puppet::Util::Platform`
I have added `require 'puppet/util/platform'` and I am no longer seeing this issue.
Unsure if I should be making this PR against master or any particular branch. Any guidance or input would be greatly appreciated.
=> (maint) - Requiring puppet as Puppet::Util::Platform is uninitialized

lib/puppet/util/windows/file.rb, lib/puppet/util/windows/security.rb, spec/integration/util/windows/security_spec.rb
- Previously, the group and other (Everyone) permissions are setup
so that the ability to modify the DACL is restricted. A member of
a group cannot take ownership of a file / directory, cannot write
to the DACL or delete the DACL.
This is by design to prevent a scenario where a group is given
read-only access to a file, so that a user in that group may not
rewrite a DACL, or take ownership, in a way that escalates
privilege to this file.
Maintain the same previous behavior, *except* when the mode is
7, which should be equivalent to (F) / FullControl within the DACL,
allowing the same behavior that is presently exhibited for a file
owner.
- Note that the previous behavior of removing FILE_EXECUTE for files
written to a directory (86f2876)
is maintained for the CREATOR OWNER:(OI) and …
=> (PUP-4684) Ensure Windows mode of 7 is FullControl

lib/puppet/util/autoload.rb, spec/integration/data_binding_spec.rb, spec/unit/util/autoload_spec.rb
The implementations of `require` in JRuby and MRI don't check the same
paths in `$LOADED_FEATURES`. Both check a version of the relative path, but
MRI checks with the file extension and JRuby checks without. Both check the
absolute path, so if we save that instead we should get consistent behavior
across platforms.
=> (PUP-8733) Store full file path in LOADED_FEATURES in autoloader

lib/puppet/rest/client.rb, lib/puppet/rest/routes.rb, lib/puppet/ssl/host.rb, spec/unit/ssl/host_spec.rb
Previous to this change, the CRLs used the indirector to find and save
the CRLs to disk. This change updates the usage in the ssl host class to
use the rest httpclient instead.
=> (PUP-8654) Use REST client to download CRLs

acceptance/tests/resource/package/yum.rb
The acceptance test accidentally used `agent` instead of `agents`[1].
Beaker only defines the former if there is at least one host with the
agent role, while the latter always exists.
[1] https://github.com/puppetlabs/puppet/commit/a5d1913bf6250dc8649d1198603412eb7c8a00e8#diff-68234540237967bc3500e7864184f30eR109
=> (maint) Use agents not agent

lib/puppet/resource/type_collection.rb, spec/integration/type/file_spec.rb, spec/shared_examples/rhel_package_provider.rb, spec/unit/provider/package/aptitude_spec.rb, spec/unit/provider/package/aptrpm_spec.rb, spec/unit/provider/package/dpkg_spec.rb, spec/unit/provider/package/nim_spec.rb, spec/unit/provider/package/opkg_spec.rb, spec/unit/provider/package/pkg_spec.rb, spec/unit/provider/package/rpm_spec.rb, spec/unit/provider/package/urpmi_spec.rb, spec/unit/provider/service/openrc_spec.rb, spec/unit/resource/type_collection_spec.rb, spec/unit/util/diff_spec.rb, spec/unit/util/execution_spec.rb, spec/unit/util/filetype_spec.rb, spec/unit/util/plist_spec.rb
If `config_version` was an executable, then we emitted the YAML tag for a `Puppet::Util::Execution::ProcessOutput` class in the last run summary. Capture the config version output as a String instead. Also update specs to accurate reflect what the `execute` method returns.
=> (PUP-8767) Emit config version as a string

.gemspec, Gemfile, Rakefile, api/schemas/file_metadata.json, docs/rspec_tutorial.md, ext/project_data.yaml, spec/lib/matchers/json.rb, spec/unit/node_spec.rb, tasks/ci.rake
Remove pins for gems now that Puppet requires ruby 2.3 and up.
Drop RSpec JUnit output formatter and unused rake task.
Add missing httpclient dependency
Run schema validation on Windows
=> (PUP-6894) Unpin ruby 1.9.3 compatible gems 

lib/puppet/test/test_helper.rb
This fixes order dependent failures caused by some tests setting the
ca_location, which is retained between tests, and others expecting it
not to have been set. For example:
`rspec spec/integration/agent/logging_spec.rb spec/integration/ssl/autosign_spec.rb`
=> (maint) Reset ca_location between tests

lib/puppet/rest/client.rb, lib/puppet/rest/response.rb, lib/puppet/rest/routes.rb, lib/puppet/ssl/host.rb, spec/integration/ssl/autosign_spec.rb, spec/lib/puppet_spec/ssl.rb, spec/unit/rest/client_spec.rb, spec/unit/ssl/certificate_revocation_list_spec.rb, spec/unit/ssl/host_spec.rb
This commit updates the SSL::Host class to use the new
Puppet::Rest::Client to submit CSRs, instread of going through the
indirector. Some of the logic can be made simpler once the CA code is
removed.
=> (PUP-8905) Do not use the indirector to manage CSRs

lib/puppet/provider.rb, lib/puppet/provider/package/dnf.rb, lib/puppet/provider/service/systemd.rb, spec/unit/provider/package/dnf_spec.rb, spec/unit/provider/package/yum_spec.rb, spec/unit/provider/service/systemd_spec.rb, spec/unit/provider_spec.rb, spec/unit/type/package_spec.rb
Without this change, defaultfor needed to be explicit for os versions to separate older and newer providers.
With this change, newer providers can blacklist older os versions with the new notdefaultfor method,
so that they can be the default for unspecified future os versions without a code update.
=> (PUP-8552) Create notdefaultfor blacklist for better management of default providers.

lib/puppet/provider/selmodule/semodule.rb, spec/unit/provider/selmodule_spec.rb
Add a beginning-of-line marker to the regex to match the
complete selmodule name.
If not matching the beginning of the line, a modulename of
`foo` also matches for a moudlename of `myfoo`.
=> (PUP-8943) Match full selmodule name in exists? check

acceptance/tests/ssl/autosign_command.rb, lib/puppet/rest/route.rb, lib/puppet/rest/routes.rb
In the process of untangling SSL management from the indirector, some
logging was lost. This commit adds logging around when SSL artifacts are
downloaded.
=> (maint) Improve logging around SSL downloads

lib/puppet/environments.rb, lib/puppet/gettext/config.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/node/environment.rb, lib/puppet/util/command_line.rb, spec/unit/gettext/config_spec.rb, spec/unit/node/environment_spec.rb
Previously we never successfully cleared translation repositories because we used symbols as the keys when creating them but strings as the keys when deleting them. Normalize environment names to symbols so that we consistently add and delete translation repositories, and fix issues with thread-specific storage for `text_domain` working with Puppet Server where multiple threads may use the same JRuby instance.
=> (PUP-8672) Ensure cache expiration clears translation domains

api/schemas/report.json, lib/puppet/resource/status.rb, lib/puppet/transaction/event_manager.rb, lib/puppet/transaction/report.rb, spec/unit/resource/status_spec.rb, spec/unit/transaction/event_manager_spec.rb
1) We now (de)serialize the `failed_to_restart` attribute of `Puppet::Resource::Status`.
2) EventManager also calls `resource_status.fail_with_event(message)`, when setting `resource_status.failed_to_restart = true` to set the over-all `failed` attribute on a resource status.
=> (PUP-8908) Resource::Status failed_to_restart improvements

lib/puppet/provider/service/upstart.rb
Prior to this commit, the upstart provider would be detected as
suitable on Ubuntu and RHEL 6 as long as /sbin/start was present.
Unfortunately, on newer versions of Ubuntu, such as 16.04, it is
possible for /sbin/start to be present, but for upstart to not be
in use.  In that scenario, puppet resource service will simply
fail as it will not be able to execute initctl since the upstart
socket will not be present.
This commit adds a confine to the upstart provider that checks for
the existence of the upstart socket pid file.  If that is present,
it is more reasonable to assume that upstart is in use and can
be checked.  If it is not present, such as on Ubuntu 16.04, we
will fall through to systemd even when the upstart package happens
to be installed.
=> (PUP-8396) Add confine detecting upstart socket pid

lib/puppet/rest/client.rb, lib/puppet/rest/ssl_context.rb, lib/puppet/ssl/host.rb, spec/unit/rest/client_spec.rb, spec/unit/ssl/host_spec.rb
Supersedes https://github.com/puppetlabs/puppet/pull/6880.
This makes the SSL state of the Rest::Client configurable by the caller on creation of the client.
=> (PUP-8748) Explicity set SSL configuration of Rest::Client

lib/puppet/util/network_device/base.rb
This was missed in 4909a533fb as the tests are behind a feature flag that isn't on by default in the testing matrix.
=> (maint) Explicitly pass current environment to autoloader in Puppet::Util::NetworkDevice::Base

lib/puppet/network/http/connection.rb, lib/puppet/rest/client.rb, lib/puppet/rest/routes.rb, lib/puppet/ssl/host.rb, lib/puppet/util/ssl.rb, spec/lib/puppet_spec/validators.rb, spec/unit/network/http/connection_spec.rb, spec/unit/rest/client_spec.rb
Prior to this, despite using the existing validator, we did not handle
erros that might be thrown from validation. This refactors existing
validation handling to be used by our new client.
=> (PUP-8950) Handle SSL connection errors in new client

acceptance/tests/server_list_setting.rb, lib/puppet/indirector/rest.rb, lib/puppet/rest/client.rb, lib/puppet/rest/route.rb, lib/puppet/rest/routes.rb, lib/puppet/util/connection.rb, lib/puppet/util/ssl.rb, spec/unit/rest/route_spec.rb
This commit updates the server resolution logic of the
Puppet::Rest::Client to respect the `server_list` setting. Previously
is was falling back to the `server` setting (or whatever server it was
configured with) even when `server_list` was set and supposed to take
precedence.
This commit also updates the acceptance test to verify that
`server_list` is preferred first, to avoid hiding that large bug behind
less consequential failures.
=> (PUP-8952) Respect server_list setting when using Rest::Client

lib/puppet/defaults.rb, lib/puppet/ssl/certificate_request.rb, spec/unit/ssl/certificate_request_spec.rb
Currently, CSRs can only be signed using DNS type subject alt names (referred to as ``--dns_alt_names`` or ``--dns-alt-names``). This commit provides support for IP SANs, but does not address any of the naming issues brought up in this ticket. More information on the blocking factors for that name change can be found at #6888.
=> (PUP-8942) Provide support for IP subject alt names

acceptance/tests/resource/cron/should_allow_changing_parameters.rb, acceptance/tests/resource/cron/should_be_idempotent.rb, acceptance/tests/resource/cron/should_create_cron.rb, acceptance/tests/resource/cron/should_match_existing.rb, acceptance/tests/resource/cron/should_remove_cron.rb, acceptance/tests/resource/cron/should_remove_leading_and_trailing_whitespace.rb, acceptance/tests/resource/cron/should_remove_matching.rb, acceptance/tests/resource/cron/should_update_existing.rb
Fedora 28 does not ship with a crontab executable -- [PC-697](https://tickets.puppetlabs.com/browse/PC-697) has been filed to address this better, but for now, [here's a successful run](https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/189/) of these changes alongside the agent platform adddition from https://github.com/puppetlabs/puppet-agent/pull/1462.
=> (PUP-8970) Skip cron tests on Fedora 28

lib/puppet/application/device.rb, spec/unit/application/device_spec.rb
puppet device --apply, doesnt error without having to register it with a puppet master.
=> (PUP-8632) device --apply works without a cert

lib/puppet/pops/serialization/to_data_converter.rb, spec/unit/pops/serialization/to_from_hr_spec.rb
Before this, if a Hash had a key `__ptype` it would be taken as a
special type marker. That was bad because it makes some keys reserved in
a hash.
In this commit, such hashes are treated as having "non string keys"
which means it uses an alternative representation. This avoids the
problem when the rare cases there is such a hash occurs.
=> (PUP-8976) Make it safe to use __ptype as a key in a hash

lib/puppet/defaults.rb
Clarify that facts are not updated when fetching cached catalogs. CC @hpcprofessional
=> (docs)(DOC-3669) Clarify facts in cached catalogs

lib/puppet/provider/augeas/augeas.rb, spec/unit/provider/augeas/augeas_spec.rb
The augeas provider used `Kernel#eval` to convert stringified arrays to Ruby arrays. For example, it extracted the array part of the "clause" below:
```puppet
onlyif => 'values HostKey == ["/etc/ssh/ssh_host_rsa_key"]'
```
and called `Kernel#eval` with `'["/etc/ssh/ssh_host_rsa_key"]'`. Using eval is bad because it executes arbitrary code.
This commit changes the provider to convert the comma delimited string to a Ruby array. This mostly maintains the functionality of the original `Kernel#eval` (minus running arbitrary code) except for no longer handling the `\M-x`, `\M-\C-x`, `\M-\cx`, `\c\M-x`, `\c?`, and `\C-?` escape sequences in double-quoted strings, and `\u{nnnn ...}` is more lenient about whitespace.
=> (PUP-8974) Safely deserialize stringified array

acceptance/tests/modulepath.rb, lib/puppet/defaults.rb, lib/puppet/util/autoload.rb, spec/unit/defaults_spec.rb, spec/unit/util/autoload_spec.rb
Previously, vendored modules behaved like any other module in the
modulepath. When acting as a server, agents would pluginsync the
vendored modules. This can cause problems if the vendored module is not
compatible with an older agent.
This commit makes vendored modules behave as though they are part of
puppet. They are not pluginsynced, but the autoloader can resolve
types, providers, etc from vendored modules. Vendored modules always
have least precedence.
=> (PUP-8988) Don't pluginsync vendored modules

lib/puppet/indirector/ldap.rb, spec/unit/indirector/ldap_spec.rb
After this update, the LDAP Terminus will report with a Puppet.deprecation_warning when instantiated.
=> (PUP-7600) LDAP Terminus gives a deprecation warning

lib/puppet/defaults.rb, spec/integration/util/settings_spec.rb, spec/unit/defaults_spec.rb, spec/unit/settings/autosign_setting_spec.rb, spec/unit/settings/file_setting_spec.rb
This is a slightly updated version of #6910 - opening only to run through Travis / AppVeyor before merging.
Original comments from @glennsarti 
> Previously the MSI packaging for Puppet Agent changed the default for the
manage_internal_file_permissions setting to false as part of CVE-2018-6513.
However puppet still had a default of true.  This commit changes the default to
false for Windows platforms, to mirror that of the packaging, and to not undo
the remediation for the CVE.
=> (PUP-8985) Default manage_internal_file_permissions to false on Windows

spec/integration/util/windows/security_spec.rb
Update to #6919 
Previously there some tests around round tripping the file mode however they
missed many scenarios.  This commit adds the following scenarios;
* Where the owner and group are the same
* Where the files/dirs are created by Puppet when running as a Windows Service
as LOCAL SYSTEM
* Where the files/dirs are created by Puppet when running as a Scheduled Task
as LOCAL SYSTEM
=> (PUP-8939) Add tests for round tripping file modes as SYSTEM

lib/puppet/defaults.rb
Calling `Puppet.settings.use(<section>)` will create files and directories
for all of the `:file` and `:directory` based settings in that section.
Previously, running `puppet lookup` as a non-root user failed, because
lookup uses the `master` section, the `vendormodulesdir` setting is
defined in the `master` section, and the user did not have permission to
create the `/opt/puppetlabs/puppet/vendor_modules` directory.
This commit changes the vendormoduledir setting to be of type `:string`.
This way puppet never tries to manage its existence via a settings
catalog. It doesn't use `:path`, because that settings type is reserved
for settings that allow multiple directories separated by
File::PATH_SEPARATOR.
=> (PUP-8988) Define vendormoduledir as a string

lib/puppet/face/certificate.rb
The `certificate` face was the last of the SSL-related faces that had
not yet been deprecated. This commit deprecates it. All of these faces,
as well as the `cert` application, will be replaced with new, more
streamlined tools in Puppet 6.
=> (PUP-8997) Deprecate the certificate face

lib/puppet/application/cert.rb, spec/unit/face/help_spec.rb
This commit deprecates the `cert` application, which will be updated in
Puppet 6 to error with instructions on how to use the Puppet Server CA
CLI to do the actions that `cert` currently performs.
Unlike with face, calling the `deprecate` message in an application only
causes a warning to be issued when it is run, and does not update the
summary (and therefore not the help output), so this commit updates the
summary to indicate the deprecation.
=> (PUP-8997) Deprecate the `cert` subcommand

lib/puppet/provider/service/upstart.rb, spec/unit/provider/service/upstart_spec.rb
Previously, we'd confine the upstart provider to platforms where the
/var/run/upstart-socket-bridge.pid file exists because that would mean
that the upstart daemon was running. This was not quite correct. The
upstart daemon could still be running even if that file did not exist
(e.g. such as on a RHEL 6 machine, for example).
We can use `initctl version --quiet` instead to check if the upstart
daemon's running. If that command fails, then the upstart daemon isn't
running so we cannot use the upstart provider. If it succeeds, then the
upstart daemon is running so we can use the upstart provider. We confine
our provider to platforms that result in a successful execution of this
command.
=> (PUP-9008) Use `initctl version --quiet` to detect upstart daemon

lib/puppet/application/apply.rb, lib/puppet/configurer.rb, lib/puppet/configurer/fact_handler.rb, lib/puppet/functions.rb, lib/puppet/functions/call.rb, lib/puppet/pops.rb, lib/puppet/pops/adapters.rb, lib/puppet/pops/evaluator/deferred_resolver.rb, lib/puppet/pops/evaluator/evaluator_impl.rb, lib/puppet/pops/functions/dispatch.rb, lib/puppet/pops/loaders.rb, lib/puppet/pops/pcore.rb, lib/puppet/pops/types/type_factory.rb, spec/unit/configurer_spec.rb, spec/unit/functions/call_spec.rb, spec/unit/functions4_spec.rb, spec/unit/pops/evaluator/arithmetic_ops_spec.rb, spec/unit/pops/types/deferred_spec.rb, spec/unit/ssl/certificate_factory_spec.rb
This adds the Deferred type and makes --rich_data work on the agent. It also adds resolution of Deferred values.
@joshcooper This is the rebase for Puppet 6.0.
=> (PUP-8598, 8622, 8635, 8641, 8657, 8676) Add Deferred Type and Make Rich Data work on Agent - For Puppet 6

CONTRIBUTING.md, docs/quickstart.md, docs/windows.md
I've found there can be quite a bit of confusion of how exactly to run
spec tests, especially when it comes to windows. This commit attempts to
add some clarity around how to do that. A step by step guide might be
too prescriptive, but it should be quite helpful for those who are
unfamiliar with working in a windows environment.
=> (maint) Add additional details on how to run spec tests

lib/puppet/defaults.rb, lib/puppet/util/autoload.rb, spec/unit/puppet_spec.rb, spec/unit/util/autoload_spec.rb
Append the vendored modules directory to the ruby $LOAD_PATH, which is effectively how things worked before we extracted them into modules. Note vendored_modules have least precedence so that it can be overridden by pluginsynced modules.
=> (PUP-9015) Append vendored modules to $LOAD_PATH

acceptance/tests/resource/service/smf_basic_tests.rb, lib/puppet/provider/service/smf.rb, spec/unit/provider/service/smf_spec.rb
This commit reverts any changes that made the SMF provider return
:absent for nonexistent services, while preserving some of the
acceptance test improvements made during this work (e.g. like
consolidating all SMF tests to a single file). These involve the
following commits:
* (PUP-6797) service should check for smf service first
** Hash: 3d7a3c4c1c6697047ae356c8765928f68618bc69
* (PUP-6860) puppet on solaris 11 should support exists? for services
** Hash: dd30a54c9ff5fba9f980147b4a7af80442e009ed
* (PUP-6797) Update SMF tests for nonexistent service
** Hash: 7085af0b7e508d86caa9e30bf44bed931d65f0df
* (maint) (PUP-6767) remove redundant smf acceptance testing
** Hash: b539fe581f372514e28f4c7e095d81dc8b0f500c
* (PUP-8167) SMF provider: do not try to stop :absent services
** Hash: …
=> (PUP-8957) Revert changes that made SMF return :absent (again)

lib/puppet/defaults.rb
Previously puppet could hang reading from a socket if the response never
arrived, for example if the TCP FIN or RST never arrived. Set a default
http read timeout to avoid that. Note the http connect timeout already
defaults to 2 minutes.
Similarly, set the watchdog timeout (runtimeout) to 1 hour. If a puppet
run takes more than that it will be killed by the watchdog. Overrun can
occur but at least puppet won't hang indefinitely, such as if puppet
executes a command that waits indefinitely. Prime example is a Windows
MSI that displays a UI waiting for user input that never happens.
=> (PUP-8683) Change default http read and run timeouts

lib/puppet/parser/functions/tagged.rb, spec/unit/parser/functions/tagged_spec.rb
As tags are always stored downcased, we should also downcase
passed arguments, otherwise function will never return true.
=> (PUP-9024) tagged: downcase arguments before checking

acceptance/tests/pluginsync/7316_apps_should_be_available_via_pluginsync.rb, lib/puppet/type/file/source.rb, spec/integration/type/file_spec.rb, spec/unit/configurer/downloader_spec.rb
Allowing default source_permissions to be nil so we can detect user setting the value.
=> (PUP-5921) Issue a deprecation warning when users set source_permissions.

lib/puppet/pops/issues.rb, lib/puppet/pops/validation/checker4_0.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/unit/pops/validator/validator_spec.rb
Before this update, there was no check to compare file locations to the definitions contained in them.  After this check, if a definition is located in an inappropriate file, the user will receive a deprecation warning.
=> (PUP-8894) Deprecate illegal definition locations.

lib/puppet/provider/service/debian.rb, spec/unit/provider/service/debian_spec.rb
Since facter 3.7 Devuan will be detected as operatingsystem and should use the right service provider https://tickets.puppetlabs.com/browse/FACT-1579
=> (PUP-9048) Make Debian init service provider default for Devuan

acceptance/lib/puppet/acceptance/windows_utils.rb
In Ruby 2.5, the `-rubygems` flag is both unnecessary and no longer valid
=> (PA-1824) Update ruby flags in Windows test utils for Ruby 2.5

lib/puppet/defaults.rb, spec/unit/ssl/certificate_authority_spec.rb
In Puppet 6, as part of splitting the CA directory out of the SSL
directory, we are also moving the settings related to CA file locations
in puppetserver's config file. Any settings in Puppet's config file will
be ignored starting then.
=> (PUP-9027) Deprecate CA file settings

lib/puppet/ssl/certificate_authority.rb, spec/unit/ssl/certificate_authority_spec.rb
The puppet cert, ca, etc subcommands have various methods for
determining if a certificate is valid. This is used to see which certs
have been signed, are still waiting to be signed, or have been revoked.
Historically, puppet set the purpose to PURPOSE_SSL_CLIENT on the
X509::Store used to verify certificates, but ruby+openssl 1.0 ignored
it. When using openssl 1.1, purpose is checked, which causes
CertificateAuthority#verify to raise an error when verifying the puppet
CA cert, since it doesn't have the 'SSL Client' purpose. This
corresponds to the 'id-kp-clientAuth' extended key usage extension[1].
However, puppet doesn't really need to care about the purpose when
determining if the cert has been signed, is expired, or revoked. This
commit changes the verify method to default to …
=> (PUP-9064) Ignore X509 purpose during cert verification

lib/puppet/functions/filter.rb, lib/puppet/parser/functions/filter.rb, spec/unit/functions/filter_spec.rb
Before this, `filter()` was different from other functions taking
a predicate lambda in that it required the lambda to return
a boolean `true` to not filter.
This is now changed to make `filter` behave like the other functions
where any truthy value returned from the lambda means do not filter this
value.
=> (PUP-8320) Make filter less strict and accept truthy predicate

lib/puppet/defaults.rb, lib/puppet/test/test_helper.rb, spec/unit/application/master_spec.rb
As part of PUP-8591 we removed the master application in Puppet 6. This
orphaned many settings that are not applicable to running a master with
Puppet Server or are better served living within its configuration
files.
To prepare for the removal of the puppet master application in Puppet 6,
this patch deprecates those settings.
---
Also correctly deprecates configprint.
=> (maint) Deprecate settings used by `puppet master`

Gemfile
Previously we pinned Rake to a float through the 12 version series.
However 12.3 dropped support for versions of Ruby less than 2.0.
This works fine for our master branch but for 5.x release of Puppet
we still support Ruby 1.9, run in a runtime that implements 1.9's
interface in Puppet Server and use 1.9 for some of our automation.
This pins us to the last minor series of Rake that supports Ruby 1.9.
It sets the minimum version to 12.2.1 specifically because that is the
version of Rake that the last vesion of our packaging utilties that
support Ruby 1.9 uses (packaging 0.99.8). It floats the version along
the 12.2 minor series to pick up any bugfix patches.
=> (maint) Pin Rake to versions that support Ruby < 2

lib/puppet/type/exec.rb
Note that this attribute doesn't work in Windows, and tighten some phrasing.
=> (docs)(DOCUMENT-807) Clarify user attribute in exec.

lib/puppet/type/file/source.rb
The file resource's http source checksum behavior, which relies on headers in the HTTP server response, is not documented in the type. Document this behavior.
=> (PUP-4533)(DOC-3685) Document http source checksum

lib/puppet/info_service/task_information_service.rb, lib/puppet/module/task.rb, spec/lib/puppet_spec/modules.rb, spec/unit/info_service_spec.rb, spec/unit/task_spec.rb
Previously the task details of the info service to included only
information about the files present in the tasks directory matching the
task name. In order to support the multi-platform tasks it has to
instead read the metadata.json file, find all task implementation and
include file information about them. So that validation logic doesn't
have to implemented twice task validation has moved out of puppet-server
into puppet ruby code. This will also allow the logic to be shared with
bolt.
This commit should not be merged until puppet-server is ready for the new task details schema
=> (PUP-9073) Add multi-platform task support to task info service

lib/puppet/functions.rb, lib/puppet/parser/catalog_compiler.rb, lib/puppet/parser/script_compiler.rb, lib/puppet/pops/functions/dispatch.rb, lib/puppet_pal.rb, spec/unit/puppet_pal_catalog_spec.rb
This adds the ability to compile a catalog and render it as JSON to the Puppet PAL API.
An example using this:
```ruby
result = Puppet::Pal.in_tmp_environment('pal_env', modulepath: modulepath, facts: node_facts) do |pal|
pal.with_catalog_compiler do |c|
c.evaluate_string("notify {'test': message => /a regexp/}")  # add a resource to the catalog (after main manifest has been evaluated)
c.with_json_encoding() {|encoder| encoder.encode } # results in pretty json
end
end
```
=> (PUP 8973) add catalog compilation to pal

lib/puppet/provider/package/zypper.rb
Prior to this PR, the zypper package provider did not have a source,
so the package lists would be duplicated with the rpm provider. This
PR adds rpm as the source to the zypper package provider to
eliminate the duplicate package when using `providers_by_source`.
=> (PUP-9009) Add Zypper package provider source

lib/puppet/version.rb
Due to some late-breaking shenanigans, we ended up shipping 5.5.6
instead of 5.5.5. This has necessitated a manual version bump since we
bypassed our normal automation process here.
=> (maint) Bump version to 5.5.7

acceptance/tests/lookup/lookup.rb, benchmarks/serialization/catalog.json, lib/puppet/defaults.rb, lib/puppet/resource/catalog.rb, spec/unit/network/http/api/master/v3/environment_spec.rb
The config setting has been deprecated for a while, and has not done anything during that time.
=> (PUP-8531) Remove unused app_management config setting

lib/puppet/functions/new.rb
The docs site builds the function reference by making each function name
a second-level heading (h2). The `new()` function docs contain several
second-level headings, which breaks table-of-contents generation on the
docs site. Change those headings to third-level headings, and change
fourth- and fifth-level headings to bold text.
=> (docs) Change heading levels on new() function

lib/puppet/parser/functions/sprintf.rb
The `sprintf()` function docs point users to the Ruby docs for the function, but could also link to them. Add a link to the Ruby `sprintf` docs.
=> (docs)(DOC-3488) Link to sprintf docs.

lib/puppet/type/augeas.rb, lib/puppet/type/exec.rb, lib/puppet/type/file.rb, lib/puppet/type/group.rb, lib/puppet/type/k5login.rb, lib/puppet/type/notify.rb, lib/puppet/type/package.rb, lib/puppet/type/schedule.rb, lib/puppet/type/selboolean.rb, lib/puppet/type/selmodule.rb, lib/puppet/type/service.rb, lib/puppet/type/tidy.rb, lib/puppet/type/user.rb, lib/puppet/type/yumrepo.rb, lib/puppet/type/zone.rb
Several type attributes list default values in their description, but also have `defaultto` definitions. When generating reference docs, this results in output that contains duplicate lists of default values. Remove these redundant defaults from the descriptions.
Defaults that required additional information were intentionally left in the description, but should be minded should the `defaultto` value change.
Two attributes also included extraneous formatting that appeared in output as raw text. Remove or replace that formatting.
=> (docs) Address some issues when generating type reference docs

spec/unit/gettext/config_spec.rb
If a default text domain is still present, then calling `text_domain`
will not return nil. Update the test to ensure that the configured text
domain is `default_text_domain` after calling `clear_text_domain`, to
make it resilient to whether the default is set or nil.
=> (PUP-8959) Update test to fix order-dependent issue

lib/puppet/provider/service/systemd.rb
This adds support for the next version of RHEL in the systemd provider.
Note: I have no idea when it'll be released but we need this patch as we
need to make Puppet systemd provider working.
=> (PUP-9069) Add support for RHEL8

lib/puppet/module/task.rb, spec/unit/task_spec.rb
Commit fad1d81e1 switched from JSON.load to Puppet::Util::Json.load, but didn't
account for the methods raising different exceptions. Update the rescue and add
a unit test for invalid metadata.
=> (maint) Rescue our JSON ParseError

lib/puppet/util/windows.rb, lib/puppet/util/windows/adsi.rb, spec/integration/util/windows/adsi_spec.rb, spec/unit/util/windows/adsi_spec.rb
There's some shared code in the User/Group ADSI classes. This
commit moves these over to a common Base ADSI class.
=> (maint) Create Base class for User/Group ADSI objects

Gemfile
Our docker images are missing headers/libs needed to compile the
ruby-ldap's native extensions. Comment out the gem for now.
=> (maint) Disable ruby-ldap gem

lib/puppet/pops/evaluator/runtime3_converter.rb, lib/puppet/provider/package/rpm.rb, lib/puppet/provider/package/windows/package.rb, lib/puppet/type/user.rb
This removes the logic that duplicated frozen strings before giving them to the 3.x "runtime API". That was done because some resource types mutated their given arguments. (Notably the user resource type). 
This PR changes the runtime3converter (no longer duplicates frozen strings) as well as user resource type and a questionable mutating gsub! in the windows package.
=> (PUP-7141) stop dup of frozen string in 3x converter

lib/puppet/pops/issues.rb, lib/puppet/pops/validation/checker4_0.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/unit/pops/validator/validator_spec.rb
With this change, if a user defines a top level construct (resources, variable assignments, include statements, import statements, etc) a deprecation warning is issued.
=> (PUP-9020) Issue deprecation for top level constructs in module files.

lib/puppet/node/facts.rb, lib/puppet/pops/model/model_label_provider.rb, lib/puppet/pops/serialization.rb, lib/puppet/pops/serialization/to_stringified_converter.rb, lib/puppet/transaction/event.rb, spec/unit/pops/serialization/to_stringified_spec.rb, spec/unit/transaction/report_spec.rb
This adds a new `ToStringifiedConverter` that `Event` is now using to serialize its content. Earlier, if `--rich_data` was on, the result would be that a Report could end up containing rich data in JSON form. The downstream processing of that (PDB and report processors as well as other custom consumers) are not expecting this format as the specification states
that events report "before" and "after" as `String` values - although that is a lie as it includes JSON standard data types.
This is also an improvement over earlier processing in that both `Binary` and `ASCII-8BIT` encoded strings are treated as binary and result in `Base64` encoded strings.
All other `String` values are re-encoded to replace illegal and undefined code points with the standard Unicode replacement character. This …
=> (PUP-9093) Make Reports contain stringified rich data

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
The ability to set a catalog ordering other than "manifest" is going to be removed in 6.0.0 (PUP-6165). We now issue a deprecation warning if someone is using a value other than "manifest", and have updated the setting's documentation to mention that in 6.0.0 and up it will effectively always be set to "manifest".
=> (PUP-9107) Deprecate ability to change catalog ordering

lib/puppet/util/yaml.rb
This corrects `@returns` to `@return` and fixes faulty indentation.
=> (DOCS) Fix formatting errors in yarddoc of YAML.safe_load

lib/puppet/util/yaml.rb, spec/unit/util/yaml_spec.rb
By default `safe_load` does not allow aliases which means that the following YAML would fail:
```
---
resources:
Panos_test[panos_test]:
parameters:
ensure:
system_value:
- present
tags:
system_value:
- &1 []
Panos_test[panos_test2]:
parameters:
ensure:
system_value:
- present
tags:
system_value:
- *1
```
Can be reproduced by using the following commit on `puppetlabs-panos` https://github.com/Thomas-Franklin/puppetlabs-panos/tree/default-bug
- `export PUPPET_GEM_VERSION=https://github.com/puppetlabs/puppet.git#master`
- `bundle install --path=.bundle/gems`
- `bundle exec rake spec_prep`
- update the file path in `puppetlabs-panos/spec/fixtures/device.conf` to point to your `test-password.conf`
- `bundle exec puppet device --modulepath spec/fixtures/modules/ --deviceconfig …
=> (PUP-9104) allow aliases in YAML safe_load

lib/puppet_pal.rb, spec/unit/puppet_pal_catalog_spec.rb
Before this it was not possible to perform subsequent evaluations
of logic containing definitions of CatalogEntry type (define, class,
etc).
This is now made possible by using the PopsBridge classes and
integrating with the TypeCollection holding all such definitions.
=> (PUP-9114) Make PAL CatalogCompiler instantiate CatalogEntry definitions

spec/unit/node/facts_spec.rb
This adds a test that prevents a string returned from `to_s` on
some arbitrary "alien" runtime value to be returned with ascii-8bit
encoding (which is bad because that is later taken as being a binary
value and not text).
=> (PUP-9093) Add test for facts sanitize regarding to_s returning 8bit str

lib/puppet/resource.rb, spec/unit/resource_spec.rb
Before this, the to_data_hash for a Resource would either return
generic data representing rich data, or a stringified version +
warnings or error (depending on strictness).
For use cases such as PDB that cannot handle rich values a more DB
friendly format is required. In order to allow PDB terminus to get a
data hash of a Resource with suitably stringified parameter values (as
produced by the ToStringifiedConverter) it is now possible to get this
by setting :stringify_rich to true in the context.
```
Puppet.override(:stringify_rich => true, 'example') do
a_resource.to_data_hash
end
```
=> (PUP-9118) Add option to stringify resource parameters

acceptance/tests/pluginsync/feature/pluginsync_should_sync_features.rb
In #6963, the pluginsync test was modified to use facter; the invocation
used was not compatible with Windows. This changes that error to use the
beaker helper.
=> (maint) fix facter call in pluginsync test

acceptance/tests/server_list_setting.rb, lib/puppet/configurer.rb, lib/puppet/indirector/request.rb, spec/unit/configurer_spec.rb
Previously, puppet would make a node request to determine which server
in its `server_list` was functional. The node request is non-trivial as
puppetserver needs to acquire a JRuby instance, query puppetdb and
classifier for node information, and return it. The agent normally
passed the node object through to the normal agent run, so the effort
wasn't wasted. But if `strict_environment_mode` is enabled, then the
node was never used.
Also, if there is a classification error, then the agent will interpret
that to mean the server is unreachable until it exhausts all servers in
the list.
This commit switches the agent to sending a HEAD request to the
/status/v1/simple endpoint. This means the agent will make at least one
additional HTTP request per run when using `server_list`. But it should …
=> (PUP-8967) Request simple status to detect if server is functional

lib/puppet/functions.rb, lib/puppet/loaders.rb, lib/puppet/parser/functions.rb, lib/puppet/pops/evaluator/runtime3_converter.rb, lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/pops/loader/loader.rb, lib/puppet/pops/loader/loader_paths.rb, lib/puppet/pops/loader/module_loaders.rb, lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, lib/puppet/pops/loaders.rb, spec/unit/pops/evaluator/evaluating_parser_spec.rb, spec/unit/pops/loaders/loaders_spec.rb
This is an updated version of the PR #6614 that now intermixes 3x function loading with 4.x loading, thus making the precedence 4.x, then 3.x per module rather than doing all 3.x at the end of having searched the module path. A small benchmark run showed this to be more or less a wash in terms of performance.
At this point tests needs to be added. PR here for early review and to get a jenkins run.
=> (PUP-6964) Make all modules visible when making function calls

acceptance/fixtures/MockService.cs, acceptance/lib/puppet/acceptance/windows_utils.rb, acceptance/lib/puppet/acceptance/windows_utils/service.rb, acceptance/tests/resource/service/windows.rb, acceptance/tests/resource/service/windows_mixed_utf8.rb, lib/puppet/provider/service/windows.rb, lib/puppet/util/windows.rb, lib/puppet/util/windows/service.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/util/windows/service_spec.rb
Neither net.exe or sc.exe really satisfy our management needs for windows services, so this PR adds a new Util::Windows::Service ruby module to puppet's utilities that implements service control on windows directly with the windows API via FFI.
Subsequently, this PR updates the service provider to re-implement the various functions of the provider API using the Windows::Service utility rather than win32-service + net.exe
=> (PUP-5475) Refactor windows service provider to connect directly to windows API

lib/puppet/util/tagging.rb, spec/unit/util/tagging_spec.rb
Before this (caused by PUP-9112) an undef/nil value given to
tagging would do `to_s` and end up with an invalid empty string tag.
Now, nil (undef) values are removed from the arguments before tagging.
=> (PUP-9130) Drop undef from tags before tagging

lib/puppet/application/ssl.rb, lib/puppet/ssl/host.rb, spec/unit/application/ssl_spec.rb, spec/unit/ssl/host_spec.rb
Create an ssl application for managing client keys and certs. Currently
it can only generate and submit a certificate request. As part of the
bootstrapping process, the application will download the CA and CRL
bundles if they don't exist, and use them for subsequent REST requests.
The application will also generate a key pair if it doesn't exist, and
use that to generate the CSR.
=> (PUP-9028) Create ssl application for managing client keys/certs

lib/puppet/gettext/config.rb
In puppet6, install paths for puppet agent are updated to build all
all of the agent components with the same prefix, instead of giving each
one its own directory. This adjusts the search path for locale files so
that it matches the new structure.
This PR shouldn't be merged until pathing updates are approved in https://github.com/puppetlabs/puppet-specifications/pull/123.
After that, this PR should be merged alongside the puppet-agent changes that require it, here: https://github.com/puppetlabs/puppet-agent/pull/1517.
=> (PA-1923) Update Windows locale path

Gemfile, ext/project_data.yaml
The resource API will be shipping as part of puppet-agent 6.0, and we
are currently planning to encourage the community and partners to
build content for it. It should be part of the default Puppet Gem
distribution so that it can be picked up by PDK and other
non-package-based workflows easily.
=> (PUP-8987) Add resource_api to gemspec/Gemfile

lib/puppet/pops/serialization/from_data_converter.rb, lib/puppet/pops/serialization/to_stringified_converter.rb, spec/unit/pops/serialization/to_from_hr_spec.rb, spec/unit/pops/serialization/to_stringified_spec.rb
Before this, the ToStringifiedConverter produced hashes that could take the form `{"__ptype" => 10}` which would make FromDataConverter crash as it tries to
parse an Integer as if it was a type name. This is now fixed by:
* Making sure ToStringifiedConverter changes all `__ptype` and `__pvalue` keys in hashes to `"reserved key: __p<the key>"`
* Making sure FromDataHash does something more sensible instead of crashing when given input that is not compliant with the output of ToDataHash
=> (PUP-9134) handle  __ptype key in ToStringifiedConverter and ToDataHash

acceptance/tests/language/objects_in_catalog.rb, lib/puppet.rb, lib/puppet/defaults.rb, lib/puppet/indirector/catalog/json.rb, lib/puppet/network/format_support.rb, lib/puppet/network/formats.rb, lib/puppet/network/http/api/indirected_routes.rb, lib/puppet/parser/catalog_compiler.rb, lib/puppet/parser/script_compiler.rb, lib/puppet/resource.rb, spec/integration/application/apply_spec.rb, spec/unit/application/apply_spec.rb, spec/unit/resource/catalog_spec.rb
Add two new network formats for representing rich data over json and
msgpack. This allows server and agent to negotiate rich data support and
maintain compatibility across versions.
This slightly changes the behavior of `preferred_serialization_format`.
This now controls the underlying format (json vs msgpack) and the
`rich_data` setting controls whether the rich data variant will be used.
For example, if `preferred_serialization_format` is set to `json` and
`rich_data` is enabled, puppet will list
`application/vnd.puppet.rich+json` first in the list of formats. If
`rich_data` is not enabled then it will list `application/json` first and
not include `application/vnd.puppet.rich+json`.
This also enables rich data by default.
=> (PUP-8601) Add rich data formats

lib/puppet/module/task.rb, spec/unit/task_spec.rb
Previously, we were raising a ModuleNotFound error in the case where a task
depended on a file from another module that didn't exist. Raising that
error caused a failure that was difficult to debug (the task was treated as
simply not existing). In reality, this scenario is generally a problem with
the metadata just like any other metadata error. Because of that, we now
raise InvalidMetadata, which causes the actual error message to propagate
through puppet-server and orchestrator, to the client.
Additionally, this error message was vague and fairly unhelpful as it
didn't explain *why* it was trying to load that module in the first place.
That message has been improved.
(PUP-9135) Check for path traversal before checking file existence
Previously, we were checking whether the referred file …
=> (PUP-9135) Treat task metadata referring to missing module as invalid

lib/puppet/face/help.rb, lib/puppet/face/help/global.erb
With this command, several broken subcommands are hidden and some useful
ones are listed at the top so that newer users will look there first.
=> (PUP-6507) Hide broken subcommands and highlight useful ones.

lib/puppet/indirector/catalog/json.rb
If rich_data is enabled, use it when saving cached catalogs. This should be
okay even if rich_data was not negotiated when requesting the catalog, as
any information lost is already lost and rich_data won't add anything
incompatible back.
=> (PUP-9138) Use rich data when saving cached catalogs

lib/puppet/rest/routes.rb, lib/puppet/ssl/host.rb, spec/unit/application/ssl_spec.rb, spec/unit/ssl/host_spec.rb
We had been working to have our rest client use the httpclient gem for
cert related HTTP requests. Unfortunately, we weren't able to finish
that work in time for Puppet 6.0.0. This commit switches those requests
back to using Puppet::Network::HttpPool.
Unfortunately, this isn't a clean switch back. We are preserving all the
existing work as much as possible so we can more easily get back to the
httpclient gem in the future. For now, we have to sacrifice some nice
new functionality in favor of the old way of doing things. Notably, if
users have an invalid or out of date cert on their agent, they have to
remove it as the automation will not update it. This is consistent with
how things used to work prior to the httpclient gem.
=> (PUP-9094) Switch rest client back to our HttpPool

acceptance/tests/ordering/master_agent_application.rb
The ordering manifest is the only available ordering available in Puppet
6. The flag itself was deprecated in 5 and removed in 6. This removes it
from the test that ensure manifest ordering is correct.
---
This test is gated on the server tag so it was missed in normal agent PR testing.
=> (PUP-6165) Remove --ordering flag from acceptance test

acceptance/tests/resource/service/windows.rb
We added a floor on the timeout when puppet is waiting for pending states to
30 seconds. This broke the service acceptance tests because they were set to
'break' at 4 seconds (which is impossible with the new 30 second minimum
timeout). This commit updates the tests to break at 30 seconds by having the
broken services wait for 60 seconds.
This wait time is long, and will add just about a minute to the test run for
services. However we believe it's important to test the failure state that
puppet will actually time out, so we believe it's worth the extra time.
=> (PUP-5475) Update windows service acceptance tests with new timeout

lib/puppet/application/device.rb, spec/unit/application/device_spec.rb
This commit removes a reference to Host#ca_location in the `puppet
device` application that was left over from the CA removal.
=> (PUP-9143) Remove reference to `ca_location` from `puppet device`

lib/puppet/pops/evaluator/deferred_resolver.rb, lib/puppet/pops/serialization.rb, lib/puppet/pops/serialization/to_data_converter.rb, spec/unit/pops/serialization/to_from_hr_spec.rb
This serializes an ASCII-8BIT as rich Binary data type in a catalog, and when the agent resolves the catalog for Deferred values, it also replaces
and Binary with its ASCII-8BIT equivalent String.
=> (PUP-9110) Serialize Ascii-8bit string as rich Binary, and convert Binary on agent

lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/unit/pops/loaders/loaders_spec.rb
Before this, when a 4x loader tries to load a 3x function it
would not check if the 3c function had already been loaded via
the 3x API. This would cause the function to be reloaded and
the information already loaded would be overwritten and this causes
a warning to be issued.
Now, a check is made if function is already loaded and if so using
the loaded function instead of loading it again.
=> (PUP-9137) Avoid reloading a 3x function

lib/puppet/application/apply.rb, spec/unit/application/apply_spec.rb
This adds resolution of deferred values to `puppet apply --catalog <file>` (and when file is stdin).
As part this, the existing logic was DRYed up or too much logic would have been duplicated between the `main` and `apply/read_catalog` methods.
=> (PUP-9121) make puppet apply with --catalog resolve deferred

lib/puppet/provider/package/portage.rb
(null) was a output given by glibc to prevent errors, the null output is
now properly handled and portage-utils (qatom specifically) will use
<unset> now.
See https://bugs.gentoo.org/662818 for more details.
Further, standardize the output format with brackets instead of braces.
=> (PUP-9044) Fix puppet porage package provider for newer portage-utils versions

spec/integration/application/apply_spec.rb, spec/unit/indirector/catalog/json_spec.rb
PR #7063 introduced a change to serialize binary in ASCII; tests in
the json_spec with binary data started failing after merge. This change
modifies the test to provide the need context for a loader and updates
the expects to look use the `binary_buffer` method on the content of a
resource in the catalog.
=> (MAINT) Fix json_spec for binary files

lib/puppet/provider/service/launchd.rb, spec/unit/provider/service/launchd_spec.rb
When restarting a service, the launchd provider calls `stop` and then `start`.
The `stop` method executes `launchctl unload -w <plist path>`, and then calls
`enable`. The `enable` method reads the disable overrides pilst and modifies it.
However, there is a race. While the `launchd` process is changing states, the
disables plist is sometimes zero-length. When this occurs, `read_plist` fails,
causing the refresh to fail.
Add a `read_overrides` method which retries the read_plist with a short sleep.
=> (PUP-9111) Retry reading overrides plist to avoid launchd race

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
The 'simple' status includes the status of all trapperkeeper services
such as the broker-service. Request status for the 'master'
service specifically.
=> (PUP-9159) Request status of the master service

lib/puppet/application/cert.rb
In Puppet 6 we replaced `puppet cert` with `puppetserver ca`. We tried
to make `puppet cert` error when it was used, but accidentally only
caused the error message to print when no subcommands or args were
passed. This commit updates `puppet cert` to error helpfully in all cases.
=> (PUP-9155) Make `puppet cert` error when args are passed

lib/puppet/defaults.rb, spec/unit/ssl/certificate_authority_spec.rb
We ended up not removing the CA-related settings in Puppet 6, with the
exceptions of `capass` and `caprivatedir`, so this commit removes the
deprecation warnings.
=> (PUP-9158) Remove deprecation warnings for CA settings

lib/puppet/module/task.rb, lib/puppet/pops/loader/task_instantiator.rb, lib/puppet/pops/pcore.rb, lib/puppet_pal.rb, spec/unit/pops/loaders/loader_spec.rb, spec/unit/pops/loaders/module_loaders_spec.rb, spec/unit/pops/types/task_spec.rb, spec/unit/puppet_pal_2pec.rb, spec/unit/task_spec.rb
Simplify task methods. Also refactor them to make it easier to re-use `Task.find_files` and `Task.find_implementations`.
Drop `requirements` from `Task#implementations`. Requirements are retrieved from `metadata`, the separate implementations helper is around finding paths to the implementation files.
Adds support for `files` and additions to `implementations` in the Task
spec revision 3.
Updates the `Task` pcore type definition to more closely mirror how the
Task Info Service represents task data. Also allow unknown keys in the
metadata.
Refactors the TaskInstantiator to share validation with Module::Task.
Once PUP-5942 is complete, we should update the metadata representation
to include validation of known properties with an open-ended Struct.
=> (PUP-9153) Support task spec revision 3

lib/puppet/parser/catalog_compiler.rb, lib/puppet/parser/compiler.rb, lib/puppet_pal.rb, spec/unit/puppet_pal_catalog_spec.rb
Before this, after the initial compilation (controlled by manifest/code
options) with PAL for catalog compilation there was no way to get lazy
constructs evaluated or to again run validation. Lazy constructs and
validation was performed for the initial compilation so the problem
addressed here is not super critical, but makes it impossible to
continue to build up the catalog with dynamic sequences.
To fix this, the PAL API for the exposed `CatalogCompiler` class is
extended with three methods: `compile_additions`, `evaluate_additions`
and `validate`, where the first method calls the other two. This allows
a dynamic sequence of operations that for example uses `evaluate_string`
to add definitions, declare a user defined resource in the catalog and
make it (and all other queued lazy …
=> (PUP-9144) Add the ability to continue building a catalog with PAL

lib/puppet/configurer.rb
Attempting to read from the cached `:configuration` section to get the `:compile_time` would create an empty `:configuration` section that would get written back to the state.yaml. The `:compile_time` is never written to in the cache, and the attr_reader (and instance variable) are never used beyond the initialization, so we can safely delete the code entirely.
=> (maint) Remove dead caching code from configurer

acceptance/lib/puppet/acceptance/common_utils.rb, acceptance/tests/resource/exec/should_run_command_as_user.rb, acceptance/tests/resource/group/should_manage_members.rb, acceptance/tests/resource/user/should_manage_groups.rb, lib/puppet/provider/group/aix.rb, lib/puppet/provider/group/pw.rb, lib/puppet/provider/group/windows_adsi.rb, lib/puppet/provider/nameservice/directoryservice.rb, lib/puppet/type/group.rb, lib/puppet/util/windows/adsi.rb, spec/integration/util/windows/adsi_spec.rb, spec/unit/provider/group/aix_spec.rb, spec/unit/provider/group/pw_spec.rb, spec/unit/provider/group/windows_adsi_spec.rb, spec/unit/provider/nameservice/directoryservice_spec.rb, spec/unit/type/group_spec.rb, spec/unit/util/windows/adsi_spec.rb
This PR refactors the members property of the Group resource to be more like the groups property of the User resource. Doing so not only makes things consistent, but it also lets Puppet correctly report the change notifications which fixes the bug described in the ticket.
=> (PUP-6542) Refactor members property to be more like the groups property

lib/puppet/util/windows/service.rb, spec/unit/util/windows/service_spec.rb
This commit updates the transition functions for windows service start/stop in
the following ways:
1. Both start/stop now exit immediately if the service is already in the
respective state. It will wait on a pending state if the pending state
indicates the service will be in the respective state requested, i.e. if the
service is in STOP_PENDING the stop function will wait for the service to
enter the STOPPED state and then exit immediately.
2. The stop method now accepts RUNNING as an acceptable state after sending
the stop control to the service. Though this _should_ be an API breakage in
the windows API ( services _should_ enter STOP_PENDING immediately ) in the
wild (and in PXP-Agent) we can't guarantee that.
3. Since we have the same issue with stop and the RUNNING state, this commit …
=> (PUP-5475) Add better state transitions to windows service start/stop

lib/puppet/util/windows/adsi.rb, spec/unit/util/windows/adsi_spec.rb
This commit adds the #userflag_set?, #set_userflags, and #unset_userflags
methods to the Windows::ADSI::User. These methods will be
used to implement the work required in PUP-5216 and PUP-6569.
=> (PUP-9177) Add userflag support to Windows::ADSI::User

lib/puppet/pops/evaluator/runtime3_converter.rb, spec/unit/pops/evaluator/runtime3_converter_spec.rb
Before this, nested :undef values were converted to the given
"undef value" (either nil, or empty string). When this was changed for
puppet 6.0.0 the language no longer produces :undef and the logic was
simplified. This did however break tests that assumed that functions
would be called with :undef.
This commit makes one change; a nested `:undef` will be converted to
`nil`.
=> (PUP-9180) Convert nested :undef to nil in 3x converter

acceptance/README.md, acceptance/Rakefile, acceptance/tests/resource/user/should_purge.rb, lib/puppet/type/resources.rb, spec/unit/type/resources_spec.rb
Attempting to purge local users was failing on Windows, since the code
for that was Unix-centric, assuming a numeric user ID. Windows uses
a string for this (the SID), so a comparison was failing.
This adds in some logic to check for system users by marking some SID
formats as system users, via regex.
=> (PUP-6716) Purge local users on Windows

spec/unit/util/storage_spec.rb
JRuby can't reliably round-trip Time objects keeping the subseconds the same. Fortunately, we don't actually care about subsecond resolution for the pruning tests, so we can round off the subseconds to 0, to try to get JRuby to consistently round-trip the Time.
This also bumps the amount the stale cache entry has been stale for to give a buffer around possible rounding of the time.
=> (maint) Don't care about subseconds in state file pruning tests

lib/puppet/defaults.rb, lib/puppet/face/config.rb, lib/puppet/face/key.rb, lib/puppet/ssl/host.rb
This commit removes some (and hopefully all) of the last remaning
references to the removed `puppet cert` command in Puppet's logging and
doc strings.
=> (PUP-9187) Remove references to `puppet cert` in errors and docs

lib/puppet/util/windows/user.rb, spec/integration/util/windows/user_spec.rb
Previously the "root" user check on Windows would only consider the elevation
token, or for Windows 2003, the group membership.  However on modern Windows
operating systems it is possible to craft a user which is NOT a member of local
administrators, which can elevate.  This causes Puppet to consider that user an
Administrator, even though they are not members of the Local Administrators
group.
This commit modifies the Puppet::Util::Windows::User.admin? method to first
check if the user is a member of the Local Adminstrators group, and then check
the token for elevation, assuming it's supported.
This commit also modifies the tests to test for these scenarios and make the
unit tests less coupled with execution order of methods.
Paired with @ThoughtCrhyme
=> (PUP-9068) Windows admin? check should consider group membership

lib/puppet/util/windows/adsi.rb
This was overlooked in the Windows ADSI User/Group refactor.
=> (maint) Use @object_class in ADSIObject.parse_name error msg

lib/puppet/util/windows/service.rb, spec/unit/util/windows/service_spec.rb
Previously, the transition_service_state helper used by the
Windows::Service.start and Windows::Service.stop methods had
a verbose interface that made it a bit more confusing to
understand what was going on than it needed to be. For example,
it was not clear what the difference between the preceding_transition
and preceding_state parameters is from the parameter names alone.
This commit refactors the transition_service_state helper to more
consistently model the Windows service state transition diagram. It
also extends the helper to support the possibility that the service
may have already transitioned to the final state, whereby it will
return early (without performing the transition), or that it is is in
the middle of a pending transition to the final state, whereby it
will wait for the …
=> (PUP-9189) Refactor the state transition code in Windows::Service

lib/puppet/util/windows/process.rb
@onyxmaster noticed we always wait a minimum of 1 second when launching external processes on Windows, which can greatly slow down puppet when there are a large number of exec resources. Now we wait at most 1 second, and repeat as necessary until the process exits or we're interrupted. Credit to @onxymaster for finding this and submitting a PR.
This supersedes PR#7038.
=> (PUP-9092) Improve process termination handling on Windows

acceptance/lib/puppet/acceptance/windows_utils.rb, acceptance/tests/windows/prevent_password_changes.rb, lib/puppet/provider/user/windows_adsi.rb, lib/puppet/util/windows/adsi.rb, spec/unit/provider/user/windows_adsi_spec.rb
Updates the ADSI user provider so that when a user account is locked
out, expired, or disabled, puppet logs a warning and refuses to change
the password.
=> (PUP-6569) Prevent password changes for inactive Windows accounts

acceptance/tests/resource/exec/should_run_command_in_cwd.rb, lib/puppet/provider/exec.rb
PUP-6919 introduced a regression where check commands like unless
and onlyif no longer respected the cwd parameter. Instead, they would
always execute in the pwd. The regression came about due to a
misinterpretation of the code in the original base Exec provider.
Specifically, the base Exec provider was cleaned up to utilize the
newly added :cwd option in Puppet::Util::Execution.execute. The cleanup
tried to preserve the original semantics of the code, but ended up
mistaking an unless statement for an if statement, which made it seem like
a check command did not use the cwd parameter (when, in fact, it did).
This commit fixes the base Exec provider to now use the cwd parameter for
check commands. It also updates the acceptance tests with this
change.
=> (PUP-9194) Use the cwd param. for check commands (e.g. unless, onlyif)

lib/puppet/util/windows/service.rb, lib/puppet/util/windows/user.rb, spec/integration/util/windows/user_spec.rb, spec/unit/util/windows/service_spec.rb
This reverts a couple of larger, riskier changes for the 6.0.2 release. They are:
* 2d235b17b4 (PUP-9189) Refactor the state transition code in Windows::Service
* 182af7e73c (PUP-9068) Windows admin? check should consider group membership
=> (maint) Revert larger changes for 6.0.2 release

acceptance/Rakefile
The path to puppet's libdir changed in puppet6
=> (maint) Update sync task's puppet path for puppet6+

acceptance/fixtures/MockInstaller.cs, acceptance/fixtures/MockUninstaller.cs, acceptance/lib/puppet/acceptance/windows_utils.rb, acceptance/lib/puppet/acceptance/windows_utils/package_installer.rb, acceptance/tests/resource/package/windows.rb, acceptance/tests/resource/service/windows.rb, lib/puppet/provider/package/windows.rb, lib/puppet/type/package.rb, spec/unit/provider/package/windows_spec.rb
This commit updates the windows package provider to execute package
installations in the same directory as the package resource.
=> (PUP-6920) Execute windows package installs in source dir

lib/puppet/util/windows/service.rb, lib/puppet/util/windows/user.rb, spec/integration/util/windows/user_spec.rb, spec/unit/util/windows/service_spec.rb
Now that everything's been tagged for the 6.0.2 release,
we can add these changes back to 6.0.x.
This reverts commit 55fd36dcaf731d54926cb611e57341f95d23b3ab.
=> (maint) Add-back the code removed in 6.0.2

acceptance/tests/utf8/utf8-recursive-copy.rb, lib/puppet/file_serving/fileset.rb, spec/unit/file_serving/fileset_spec.rb
Fixes a bug where, when recursively copying a directory with files saved
in UTF-8 on a non-UTF-8 system, a call to Dir.entries in Fileset would
disregard the encoding of the filenames, producing garbage characters in
the destination filenames.
=> (PUP-8735) Preserve UTF-8 encoding on recursive file copy

acceptance/tests/resource/package/windows.rb, lib/puppet/provider/package/windows.rb, lib/puppet/provider/package/windows/exe_package.rb, lib/puppet/util/execution.rb, lib/puppet/util/windows/process.rb, spec/unit/provider/package/windows/exe_package_spec.rb, spec/unit/provider/package/windows_spec.rb, spec/unit/util/execution_spec.rb
Previously, the windows package provider for exe packages would ignore the
exit code from the installation because cmd.exe would return the exit code
from the cmd.exe executable and not the installer executable.
This commit removes the use of cmd.exe to execute install/uninstall commands
We now ensure that processes don't open a new window by using the
CREATE_NO_WINDOW flag passed to Process.create (which in turn will send that
flag to CreateProcessW in the windows API).
This should solve all our problems: the process will wait for execution to
finish, not open a new console, and exit with the correct exit code
=> (PUP-9193) Make puppet honor installation exit code, still suppress console

acceptance/tests/i18n/modules/puppet_agent.rb, acceptance/tests/i18n/modules/puppet_agent_cached_catalog.rb, acceptance/tests/i18n/modules/puppet_apply.rb, acceptance/tests/i18n/modules/puppet_apply_module_lang.rb, acceptance/tests/i18n/modules/puppet_apply_unsupported_lang.rb, acceptance/tests/i18n/modules/puppet_facts.rb
It seems there may be something about testing with facter 2 that these
tests aren't working. We're still getting translations, but the failure
is that it's expecting an error and getting a warning. Rather than
checking warning vs. error, we should only be checking that translations
are present/absent.
=> (maint) i18n tests should only test translations

lib/puppet/util/windows/security.rb, spec/integration/type/file_spec.rb, spec/integration/util/windows/security_spec.rb
Previously it was possible to specify an octal mode for setting file permissions
which would end up with the SYSTEM account in Windows not having Full Control.
This could then cause permission issues as the SYSTEM account is a priveledged
account.  This commit intercepts attempts to set the mode on files/directories
for the SYSTEM account to something other than Full Control; and then issues a
warning and corrects the ACE back to Full Control.
=> (PUP-9106) Ensure SYSTEM ACE entries are Full Control

Gemfile
Previously we pulled in a pre-1.0 version of puppetserver-ca as a
development dependency. With Puppet Server 6.0.0 we shipped 1.0.0 and
consequently developers should have a 1+ version available during
development.
This updates to the latest y release of puppetserver-ca and ensures the
bundle installs should receive the latest y release of the 1 major
series.
=> (maint) Update dev dep of puppetserver-ca to 1.1

lib/puppet/application.rb, lib/puppet/application/apply.rb, lib/puppet/application/master.rb, lib/puppet/application/script.rb, lib/puppet/defaults.rb, spec/integration/parser/collection_spec.rb, spec/spec_helper.rb, spec/unit/application/apply_spec.rb, spec/unit/application/master_spec.rb, spec/unit/application_spec.rb
The `--logdest` option can now be set via the `logdest` setting in puppet.conf.
Unfortunately, handling setting the logging destination itself via an `:on_initialize_and_write` hook ended up playing very poorly with a large number of tests that were expecting to be able to arbitrarily reinitialize Puppet's settings without having it affect the logging setup so they could look for warnings/deprecations/errors.
Moving the setting of the log destination itself into the applications turned out to be less problematic, even though it's a bit awkward to work with because of some of the applications overriding `#setup` and `#setup_logs`.
=> (PUP-2997) Allow setting `--logdest` via puppet.conf

acceptance/tests/resource/user/should_create_with_gid.rb, acceptance/tests/resource/user/should_modify_gid.rb
Beaker 4 changes how we get the user gid. In earlier versions of beaker,
we run `dscacheutil -q user -a name #{name}`, but in beaker 4 we switch
to `id -P #{name}`. Since this test is currently run with beaker 3, and
we're getting ready to switch it to beaker 4, we need this test to be
able to handle both methods of parsing the user gid.
=> (maint) Change osx user gid check

lib/puppet/pops/validation/checker4_0.rb, spec/unit/pops/validator/validator_spec.rb
Before this change, when an earlier module path is a substring of a later module path, puppet would give a location deprecation warning for items in the later path.
This change prevents those incorrect warnings from being created.
=> (PUP-9211) Don't emit location error with subsr path

lib/puppet/util/windows/security.rb
Previously when SYSTEM was being set to lower than Full Control a warning was
emitted however the mode in the warning was the base 10 representation of the
mode, not the octal version.  This commit changes the warning message to emit
the octal representation of the proposed mode.
=> (PUP-9106) Output mode warning using octal number

acceptance/tests/apply/hashes/should_not_reassign.rb
In this loop, though we're only acting on our hosts classified as
`agent`, we're assigning each agent host the name `host`, not `agent`.
So the test needs to be updated to reflect that assignment.
=> (maint) Test fix: reference host not agent

acceptance/tests/i18n/check_puppet_run_message.rb
We want to make sure we're resetting the language for every host. If we
have multiple servers classified as an agent, there's a potential we
reset what `language` is. So instead of `ja_JP`, we could have
`ja_JP.uft8`. This isn't so ideal on ubuntu, for example, where
`locale-gen` doesn't recognize `ja_JP.uft8` as a language, where it
would recognize `ja_JP`. Generating `ja_JP` will then fail, and the test
itself will also fail.
=> (maint) Reset language for every agent 

acceptance/tests/i18n/modules/puppet_agent_with_multiple_environments.rb
Not sure why, but this seems to be isolated to how we're running tests
with git-based acceptance. It may have something to do with facter 2 or
something else.
=> (maint) Sometimes the environment classification is doubled

Gemfile
Previously the version of Rake was pinned to an old Ruby 1.9 compatible version
however this is beginning to cause issues with compatibility in other gems,
for example the packaging gem.  This commit changes the rake requirement in the
gemfile to use the older version for old versions of Ruby (< 2.0) and uses a
more relaxed pin, protecting on major version, for newer Ruby versions (>= 2.0).
This commit also adds a RAKE_LOCATION environment variable which can be used in
any instance to specify the the version of Rake required, much like the FACTER
and HIERA variables.
=> (PUP-9175) Use modern version of Rake gem

lib/puppet/type/user.rb
On Windows, the managehome property manages creation/deletion of
the user profile, _not_ the home directory. This commit updates
the docs with this information.
=> (PUP-4687) Update the managehome property's docs for Windows

Gemfile
This is a cherry-pick of 6e88c554f9bcf168596f30ddeaf02b2358f73722 but
simplified because puppet 6 requires ruby 2.3 or greater.
=> (PUP-9175) Allow specifying rake version from the environment

lib/puppet/application/ssl.rb, lib/puppet/face/node/clean.rb, lib/puppet/feature/base.rb, lib/puppet/ssl/host.rb, spec/lib/puppet/test_ca.rb, spec/unit/application/ssl_spec.rb, spec/unit/face/node_spec.rb, spec/unit/network/http/connection_spec.rb
Adds a `puppet ssl clean` action to delete a host's client cert, private key, public key, CSR and private key password file. Only the current host's files are deleted based on the `$certname` setting.
If the `--localca` option is specified, then the host's local copy of the CA certificate and CRL bundle are deleted.
=> (PUP-9156) Add puppet ssl clean action

lib/puppet/resource/catalog.rb, spec/unit/application/apply_spec.rb, spec/unit/resource/catalog_spec.rb
Checking this in with a non-working unit test (and no code fix) so that I can collaborate with the team.
I was able to manually reproduce this with this short test.pp file:
$secret = Sensitive('cat /tmp/secret_file_name.txt')
exec { 'do it':
command => $secret,
path    => '/bin/'
}
However, I have not been able to reproduce with a unit test.
=> (PUP-7580) Don't show the namevar to protect sensitive data.

lib/puppet/util/windows/security.rb
Previously in commit 2a4ba1c9f2ac1b the set_mode method was changed so that it
was not possible to set an ACL which contained an ACE with SYSTEM, without
Full Control rights.  That commit emitted a warning when the SYSTEM mode was
changed from what was requested to Full Control.  However this caused issues
with some internal Puppet settings which caused Warnings to be emitted for
things a User had no control over.
A message is still required to be emitted because Puppet is changed a requested
behaviour.  This commit changes the message from a Warning to Debug.
=> (PUP-9106) Change messages to debug when SYSTEM ACE is not Full Control

lib/puppet/provider/package/pkgng.rb, spec/fixtures/unit/provider/package/pkgng/pkg.info, spec/fixtures/unit/provider/package/pkgng/pkg.query, spec/fixtures/unit/provider/package/pkgng/pkg.query.zsh, spec/fixtures/unit/provider/package/pkgng/pkg.query_absent, spec/unit/provider/package/pkgng_spec.rb
These commits improve the pkgng provider used on FreeBSD.  The initial goal was to unbreak the mcollective_package_agent which was broken with the provider because the `#query` method itself was not working as expected.
While here, a few more minor improvements where introduced (unused fixtures removed, misnamed fixtures renamed).
=> (maint) FreeBSD package provider improvements (pkgng)

lib/puppet/transaction/persistence.rb, lib/puppet/util/logging.rb, spec/unit/agent_spec.rb, spec/unit/application/face_base_spec.rb, spec/unit/application_spec.rb, spec/unit/configurer/downloader_spec.rb, spec/unit/configurer_spec.rb, spec/unit/ssl/host_spec.rb, spec/unit/transaction/persistence_spec.rb, spec/unit/util/logging_spec.rb
Puppet.log_exception had an option to change the log level which only
worked in a very specific case (where the exception is a
Puppet::ParseErrorWithIssue and the message argument is `:default`).
This makes the argument work consistently.
=> (PUP-9185) Fix logging exceptions at debug level

spec/unit/util/suidmanager_spec.rb
The stub was incorrect, but the test passed because we don't typically
run tests as root. Just confine the test to only run on Windows.
=> (PUP-9244) Skip test on non-Windows

lib/puppet/pops/evaluator/collectors/abstract_collector.rb
Prior to this commit, the resource collection code used a pre-pops
API for finding resource types. This triggered the same error as
exported/collected resources ran into in PDB-3734.
This patch updates the code to use the new pops-related API for
finding resources, similar to the fix for the puppetdb terminus,
but without the conditions excluding classes and nodes since they
could be valid in this context.
=> (PUP-8002) Use new resource initialization methods when realizing

lib/puppet/util.rb
Previously, safe_posix_fork would reference the child process' stdin,
stdout, and stderr streams via. the global variables $stdin, $stdout,
and $stderr. This was not good because these are mutable variables;
they may not always point to the right thing. However the STDIN, STDOUT
and STDERR constants do point to the child process' stdin, stdout and
stderr streams. This commit uses these constants instead of the global
variables.
=> (PUP-9250) Use the STDIN, STDOUT, STDERR constants in safe_posix_fork

lib/puppet/provider/cron/crontab.rb, lib/puppet/provider/parsedfile.rb
The latter is a better name and results in slightly cleaner code.
=> (PUP-9217) Change swallow_prefetch_errors => raise_prefetch_errors

Rakefile
Localized translations are committed using (L10n) as the summary prefix.
Accept them case-insensitively.
=> (maint) Accept localization commits

lib/puppet/provider/package/dnf.rb, spec/unit/provider/package/dnf_spec.rb
dnf should be the default for RHEL8
=> (PUP-9198) Add RHEL8 support in the dnf provider

LICENSE, README.md
Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in
https://landscape.cncf.io/selected=puppet)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit makes a couple changes so that Licensee recognizes Puppet's
license type as Apache 2.0. It updates LICENSE so that it stores only
the text of the Apache license in its entirety. It also updates the
README to hold some of the info that was previously stored in LICENSE
and that does not exist elsewhere. The updated README section has been
renamed to "Licensing", so that Licensee correctly recognizes LICENSE
as the only license-related file.
I think my change …
=> (docs) edit Puppet license info so that GitHub recognizes it

lib/puppet/util/log/destinations.rb, spec/unit/util/log/destinations_spec.rb
Before this change, if Puppet was run as root, it would (attempt to) chown any file added as a log destination to the Puppet user/group from the settings.  On some systems, this caused errors when the user or group did not exist.
With this change, Puppet will not chown pre-existing log files when they are added as logging destinations.
=> (PUP-7331) Don't chown existing files when added as a log

lib/puppet/defaults.rb
Previously the deprecation warning for `ca` would appear whenever the
setting was checked in code, rather than only when it was spotted in a
config file. This commit makes it only appear when actively configured.
=> (PUP-9266) Only show `ca` setting deprecation when configured

lib/puppet/application/cert.rb
Fixing a minor typo in the name of the flag provided to `puppetserver ca`.
=> (maint) Fixing typo

acceptance/tests/resource/service/windows.rb, lib/puppet/provider/service/windows.rb, lib/puppet/type/service.rb, lib/puppet/util/windows/service.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/type/service_spec.rb, spec/unit/util/windows/service_spec.rb
It may be useful to users to specify their own value for timing out during a
service operation. The primary use case for which is a large service (like
MySQL) that may take longer than the default timeout period to start/stop.
This commit adds a new parameter to the service type called 'timeout'.
Currently the timeout param is only available in the windows service provider
=> (PUP-9132) Add configurable timeout for windows service operations

lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load.rb, spec/unit/pops/loaders/loaders_spec.rb
This fixes an error in ruby_legacy_function_instantiator when it
detects that a loaded 3x function is not the expected "func_info" hash.
Instead of getting a hash, something else is returned, and the raised
error should have reported the class name of what it got instead of a
hash, but it was copy pasted from elsewhere and ended up referencing
something that was not yet instantiated.
This fixes the error so that it reports the class name of the func_info
that it got.
The problem arises when someone has mocked functions in a way that makes
them not work as functions.
=> (PUP-9270) Fix broken raised error in legacy function loader

.travis.yml
Travis is having issues with ruby 2.4.0p0. Bump to latest 2.4 version.
=> (maint) Bump travis to latest ruby versions

lib/puppet/plugins/configuration.rb, lib/puppet/pops/evaluator/evaluator_impl.rb, lib/puppet/pops/evaluator/external_syntax_support.rb, lib/puppet/pops/validation/checker4_0.rb, lib/puppet/syntax_checkers/epp.rb, lib/puppet/syntax_checkers/pp.rb, spec/unit/face/parser_spec.rb, spec/unit/pops/evaluator/evaluating_parser_spec.rb
This adds syntax checkers for 'pp' and 'epp' to heredoc.
This is of value when sending a heredoc to a Deferred function as it is preferable to get syntax errors when compiling as opposed to when applying a catalog.
To use `@(EOT:pp)` for puppet, and `@(EOT:epp)` for EPP.
=> (PUP-9257) Add pp syntax check to heredoc

spec/unit/application/lookup_spec.rb
The behavior of dropping the yaml end of document changed between
Ruby 2.4.4p296 and 2.4.5p334. The tests regarding lookup are really
not about yaml output compatibility and this commit drops
the optional end of document at the end of the output if it is present
so that the individual tests can compare against the rest of the
produced yaml output.
=> (maint) Update tests requiring a yaml end of document in output

Rakefile
These files often intentionally have code that will cause Ruby warnings, and should not be checked to make sure that they do not have any warnings.
=> (maint) Update 'rake warnings' to ignore all spec & acceptance fixture files

spec/integration/ssl/key_spec.rb, spec/unit/ssl/key_spec.rb, spec/unit/util/monkey_patches_spec.rb
OpenSSL 1.1.1 now enforces a minimum of 512 bit RSA keys and it performs a noop if the same cert is added to an X509 store. This PR updates the tests accordingly.
Note we're currently only testing openssl 1.1.1 in the puppet 6.0.x branch with ruby 2.5 on appveyor, but it seems like a good thing to fix in 5.5.x.
=> (maint) Account for new OpenSSL 1.1.1 behavior

spec/unit/pops/loaders/loader_spec.rb
One of the tests in `spec/unit/pops/loaders/loader_spec.rb` was accidentally inside the set up block for its test data, so it wasn't actually being run.
=> (maint) Adjust scoping of setup in loader_spec to be able to run all tests

lib/puppet/application/device.rb, lib/puppet/application/ssl.rb, lib/puppet/ssl/host.rb, spec/unit/application/device_spec.rb, spec/unit/application/ssl_spec.rb, spec/unit/ssl/host_spec.rb
Prior to this commit ...
An SSL error involving a device prompts the user to run the 'puppet ssl clean'
command which cleans agent ssl files instead of the device ssl files,
and prompts the user to run 'puppet agent' instead of 'puppet device'.
With this commit ...
An SSL error involving a device outputs valid commands for devices.
Puppet::SSL::Host implements a 'device' parameter to specify it is a device.
The 'puppet ssl clean' command implements a '--device CERTNAME' parameter.
=> (PUP-9248) add support for devices to puppet ssl clean

lib/puppet/util/windows/api_types.rb
Previously it was possible for UTF-16LE forced encoding to fail and generate an
error, however the error handler always expected the string to not be nil.  This
commit modifies the error message to guard when the string is nil and therefore
raise the correct error message up to Puppet
=> (PUP-9293) Update error message when decoding read_wide_string

lib/puppet/pops/evaluator/collectors/abstract_collector.rb
This backports the fix for PUP-8002 to 5.5.x.
Prior to this commit, the resource collection code used a pre-pops
API for finding resource types. This triggered the same error as
exported/collected resources ran into in PDB-3734.
This patch updates the code to use the new pops-related API for
finding resources, similar to the fix for the puppetdb terminus,
but without the conditions excluding classes and nodes since they
could be valid in this context.
=> (PUP-9317) Use new resource initialization methods when realizing

acceptance/tests/resource/package/does_not_exist.rb, lib/puppet/resource.rb, lib/puppet/type.rb, lib/puppet/type/package.rb, spec/unit/resource_spec.rb
Knowing the provider of a given package resource is useful when it
differs from the operating system default.
Note that this commit also introduces a generic way for types to
specify any parameters they want included in puppet resource's
default output. All they need to do is override parameters_to_include
to return these parameters.
=> (PUP-2175) Include the package provider in puppet resource's output

acceptance/Gemfile
Nightly acceptance tests are already using beaker 4, but the default wasn't updated in the gemfile. This sets beaker 4 as the default, and adds beaker-vmpooler explicitly, since it's not included as part of beaker anymore.
=> (maint) Update acceptance Gemfile for beaker 4

lib/puppet/transaction/resource_harness.rb, spec/unit/transaction/resource_harness_spec.rb
Without this change, Puppet will fail to log any message for some errors during sync.  With this change, there will be a minimal log message and the rest of the information will be preserved.
=> (PUP-1542) Ensure errors during sync have some kind of error message

lib/puppet/parser/functions/generate.rb
This adds an additional caveat to the docs for the generate()
parser function to suggest cleaning whitespace from returned values.
=> (PUP-9320) Generate function docs include whitespace warning

lib/puppet/provider/service/systemd.rb, lib/puppet/provider/service/upstart.rb, spec/unit/provider/service/systemd_spec.rb
LinuxMint switched to using Systemd as it's init system with the release of version 18. Currently, Puppet runs will fail on LinuxMint 18 and LinuxMint 19 machines when using the `service` resource as Puppet tries to use upstart to manage the services. This PR adds support for Systemd on LinuxMint 18 & 19 as well as updates the `systemd_spec.rb` unit test to reflect the changes.
=> (PUP-9326) Adds Systemd support for LinuxMint 18 & 19

lib/puppet/provider/package/windows/exe_package.rb, lib/puppet/provider/package/windows/msi_package.rb, lib/puppet/provider/package/windows/package.rb, lib/puppet/util/windows/registry.rb, spec/integration/util/windows/registry_spec.rb
Previously, the Windows package provider would enumerate all
registry values affiliated with a given product.
Products are enumerated under
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
Where each individual product resides in a subkey, like 7-Zip
This could result in reading quite a bit of extraneous data.
- In reality, there are only 9 key values that the package provider
is interested in, so whitelist those values when enumerating
for a given product.
- This also fixes an issue where some products may install bad data
into registry values (one such product stores binary data inside
of a REG_SZ which breaks Puppets abiliy to interpret the value
as a string).
While this is really the fault of the product and not of Puppet,
Puppet must be resilient to such bad data.
--- …
=> (PUP-9312) Whitelist registry reads for Windows package providers

acceptance/tests/resource/package/ips/basic_tests.rb, acceptance/tests/resource/package/ips/should_create.rb
In adding Solaris 11.4, we discovered that output from 'resource package'
had subtly different output, which resulted in test failures due to cosmetic
changes. This updates the matching regex to accomodate all current variations.
=> (maint) PA-2344 update tests to work across multiple version of solaris

spec/unit/indirector/yaml_spec.rb
The search results aren't guaranteed to come back in a specific order, so now the test looks to make sure that the set contains the right number of items, and that it also contains the items we're looking for.
=> (PUP-9340) Update test to account for differently-ordered search results

lib/puppet/functions/new.rb, lib/puppet/pops/types/string_converter.rb, spec/unit/pops/types/string_converter_spec.rb
This adds support for the alternative flag # when using the %p
String formatting rule. By default it selects single or double
quotes around the string based on its content. Single quoted
output may sometimes not be desired.
Thus `String("hello world", '%#p')` will produce `"hello world"` and
`String("hello world", '%p')` will produce `'hello world'` since it can
be expressed as a single quoted string.
=> (PUP-9344) Add alt # flag to String %p formatting rule

lib/puppet/pops/types/p_timespan_type.rb, spec/unit/pops/types/p_timespan_type_spec.rb, spec/unit/pops/types/p_timestamp_type_spec.rb
There were typos (`==` instead of `=`) in the logic that converted type parameters for `Timestamp` and `Timespan`. This corrects both of them and adds tests.
=> (PUP-9310) Make time datatypes work with integer and float

lib/puppet/pops/types/string_converter.rb, spec/unit/pops/types/string_converter_spec.rb
Before this, if specifying a short format (e.g. "%#a") for an
Array or similar for a Hash, the rule would not be applied as
a collection format.
This commit adds the special processing to take the simplified form
when given for a top level Array or Hash to be applied as a format
specification of `{ BASE_TYPE => { 'format' => GIVEN }`.
=> (PUP-9329) Fix short form format rule for Array/Hash in string converter

lib/puppet/util/windows/service.rb
It turns out the actual query return from windows service queries was freed
before returning from teh functions, so we had a use-after-free scenario.
This commit updates the service query functions to perform the queries and
then yield a block with the query return. This way after the block completes
the return value is freed but the method would be done with that value, so no
more use-after-free
=> (PUP-9292) Change windows service query functions to take blocks

lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load2.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load3.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load4.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load5.rb, spec/unit/pops/loaders/loaders_spec.rb
Before this, methods added in a legacy function implementation file
could reside a) inside the body given to `newfunction` or b) before or
after the call to `newfunction` in the `Puppet::Parser::Functions`
module. or c) outside the module, In all three cases the method could be added with a `def mname`
or `def self.mname` neither defining a method where the user expects it
to be added. 
This commit adds protection against these method definitions by raising
an error when they are added.
=> (PUP-9294) Report illegal 3x function defining methods

acceptance/Gemfile
Since we have the ability to run acceptance tests with the docker
hypervisor, we should make it easily available for users
=> (maint) Add beaker-docker to acceptance gemfile

lib/puppet/util/command_line.rb
The changes in PUP-8766/#7242 removed plugin loading from a local
environment for `puppet device`, even in the cases where local content
is supposed to be used.
This change reverts the part of #7242 that was causing this. By allowing
puppet to load local content for '--apply', '--facts' and '--resource',
those run modes can now work stand alone again.
=> (PUP-9356) Allow loading local content for local `puppet device` modes

lib/puppet/functions/abs.rb
Documentation is partially broken here: the `alert` and `all` functions documentation appears under the `abs` section:
https://puppet.com/docs/puppet/6.0/function.html
This should fix the issue.
=> (docs) Fix markdown markup

Rakefile
Before this, whenever the grammar was regenerated, the warnings rake
task would find warnings in it related to indentation. Unfortunately it
is not possible to fix those without modifying racc as it produces many
lines with inconsistent indentation.
This makes the rake warnings task simply skip the generated file
puppet/pops/parser/eparser.rb
=> (maint) Update Rakefile warnings task to not check generated egrammar.rb

.gemspec, spec/unit/util/logging_spec.rb
Facter 2.4.0 has been out since Jan 22, 2015, and is the minimum version to contain all of the Facter.debuggin, Facter.trace, and Facter.on_message methods. By requiring at least version 2.4.0 of the Ruby Facter, we no longer have to carry along tests with fragile setup to test for Puppet working if the version of Facter is too old to have any of these methods.
=> (maint) Bump minimum Facter gem version & remove obsolete tests

.travis.yml
When running on ruby < 2.3, use bundler 1.x and rubygems 2.7.8.
When running on ruby >= 2.3, use bundler 2 and rubygems 3.
This is necessary because bundler 2 requires rubygems 3 and ruby 2.3.
This also uses the `--no-document` option as `--no-rdoc` and
`--no-ri` were removed in bundler 2.
=> (maint) Update for bundler 2

lib/puppet/pops/model/pn_transformer.rb, spec/unit/pops/model/pn_transformer_spec.rb
This makes a transformation of AST containing a nil body produce a Nop
PN call instead of crashing.
This is important since PN should be able to represent code that is not
100% semantically valid.
=> (PUP-9400) Fix problem with PNTransformerer crashing on nil

lib/puppet/rest/route.rb, spec/unit/rest/route_spec.rb
SRV resolution was broken for CA related routes because we were passing
the `ca` SRV service name as the SRV domain, and ignoring the
`srv_domain` setting. This wasn't noticed because the service name will
default to `:puppet`.
This commit passes the SRV domain name as the first argument and service
name as the second argument.
=> (PUP-9399) Pass srv domain to resolver for CA routes

lib/puppet/defaults.rb, lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load2.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load3.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load4.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/bad_func_load5.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/good_func_load.rb, spec/unit/pops/loaders/loaders_spec.rb
Before this, methods added in a legacy function implementation file
could reside a) inside the body given to `newfunction` or b) before or
after the call to `newfunction` in the `Puppet::Parser::Functions`
module. In both a) and b) the method could be added with a `def mname`
or `def self.mname` neither defining a method where the user expects it
to be added.
This commit adds protection against these method definitions by raising
an error if found in the parsed Ruby source by using the "Ripper" to
generate a Ruby AST that is then walked and checked for illegal constructs.
This also introduces a new setting `--func3x_check` (default `true`) to
enable users to switch of the Ripper parsing and subsequent assertions;
thus making the system behave in the same undefined way as it did before
the …
=> (PUP-9294) Fix error when 3x func has illegal constructs

lib/puppet/transaction/resource_harness.rb, spec/unit/transaction/resource_harness_spec.rb
Prior to this PR, the log messages for intentional and corrective
changes were identical. This PR changes the logging to append
'(corrective)' to log messages for a corrective change. Intentional
change logs are not affected by this change.
=> (PUP-9324) Ensure logs denote corrective changes

acceptance/tests/resource/group/should_manage_members.rb, lib/puppet/provider/group/windows_adsi.rb, spec/unit/provider/group/windows_adsi_spec.rb
PUP-9265 fixed the Group resource's members property to print the
right change notifications for a given Puppet run. Part of that work
improved the parity between how the Windows group provider handles
group members with how the Windows user provider handles user groups.
However, that work introduced a regression to `puppet resource`'s
output, which now printed member SIDs instead of member names.
This commit modifies the Windows group provider to return member names
instead of member SIDs, which fixes the `puppet resource` regression.
=> (PUP-9435) Return member names for Windows groups, not SIDs

acceptance/lib/puppet/acceptance/windows_utils.rb, acceptance/tests/resource/exec/should_run_command_in_cwd.rb, lib/puppet/util/windows/process.rb, spec/unit/util/execution_spec.rb
Since Dir.chdir is not thread safe we need to update the implementation of
Puppet::Util::Exection.execute with the cwd option. This commit updates the
implementation to pass the working directory directly to Process.create,
where Process.create will pass that directly to the API call in windows to
CreateProcess.
When we eventually move puppet to FFI calls directly to CreateProcess
(instead of using the win32-process gem) we should continue to pass the
current working dir to CreateProcess when the :cwd option is given to
Puppet::Util::Execution.execute
=> (PUP-9150) Update windows execute to pass cwd directly to Process

lib/puppet/application.rb, lib/puppet/util/log.rb, spec/unit/application_spec.rb, spec/unit/util/log_spec.rb
If setting logdest fails, we should raise an exception, and if there are no successful log destinations, we should exit.
=> (PUP-6571) Raise error when setting logdest fails

lib/puppet/functions/group_by.rb, lib/puppet/functions/partition.rb, spec/unit/functions/group_by_spec.rb, spec/unit/functions/partition_spec.rb
Add functions for operating on iterables to easily separate their
contents based on a block.
=> (PUP-9372) Add group_by and partition functions on iterables

lib/puppet/util/pidlock.rb, lib/puppet/util/windows/process.rb, spec/unit/util/pidlock_spec.rb
Under rare but possible conditions, a stale Puppet pidlock file may exist which contains a pid that refers to another (non-puppet) process. This adds a check of the process name to avoid locking issues under these
circumstances.
This check is currently limited to POSIX and Windows platforms only.
=> (PUP-9247) Check process name when clearing pidlock

acceptance/tests/server_list_setting.rb, lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
From the ticket description, when we added `server_list`, it was with
the idea that it would be used in place of `server` for all things. We
never really made strides with that, and now have a mixture of code that
uses `server` or `server_list` or just the first entry from
`server_list`.
Generally, `agent` is the only puppet application that knows about both
`server` and `server_list`.
=> (PUP-6885) Remove server and server_list conflict warning

lib/puppet/pops/types/type_mismatch_describer.rb, spec/unit/pops/types/type_mismatch_describer_spec.rb
Before this, puppet could crash when an `Optional` type was used without a subtype. It really means `Optional[Any]`, but this is represented internally with a `nil` type parameter.
The TypeMismatchDescriber (involved in type checking and forming of type errors) did not take the `nil` into account.
This PR fixes this and adds a test.
=> (PUP-9467) Fix problem with Optional without type

lib/puppet/functions/call.rb, spec/unit/pops/loaders/loaders_spec.rb
Before this the call() function was only capable of calling functions defined in puppet core.
=> (PUP-9477) Make call() load functions from any loader

lib/puppet/functions/index.rb, spec/unit/functions/index_spec.rb
This adds the function index() that returns the index of a found value
or `undef` if not found. The function operates on any iterable and
search can be made with explicit value, or a lambda that should return
truthy for the wanted value.
=> (PUP-9482) Add an index() function returning index of found value

lib/puppet/provider/package/windows.rb, spec/unit/provider/package/windows_spec.rb
After PUP-6920, the Windows package provider requires the "directory"
part of the source path to be something which can be set to the
working directory. Unfortunately, for http sources of MSI files, chdir
doesn't work. This has broken installing those packages.
This change allows MSIs to be installed without setting the working
directory if it does not exist. It still prefers to set the directory
when possible, just in case any MSIs out there are as badly-behaved as
legacy exe installers are.
=> (PUP-9496) Allow MSI packages to install without setting CWD

lib/puppet/util/pidlock.rb
PE's puppet-infrastructure backup and restore system uses
Puppet::Agent::Locker to avoid conflicts with normal runs of the node's
agent. Due to this, the pidlock process name check needs to be expanded
to include process names such as puppet-infrastucture. This loosens the
regex slightly to ensure the lock is still valid when these maintenance
tasks are run.
=> (PUP-9247) Update the pidlock process name check for posix platforms

lib/puppet/x509/cert_provider.rb
Commit 568c900038c45463fe11cbe29fb3e73f35f5d461 specified an empty
passphrase when loading an rsa private key so that ruby does not prompt
and hang if the key is encrypted. However, ruby 2.4.0 and 2.4.1[1] have
a bug which requires the passphrase to be at least 4 bytes. This was
fixed in 2.4.2[2]. Since we don't actually care about the passphrase,
specify a 4 byte empty string, so it works on all ruby versions.
[1] https://github.com/ruby/ruby/commit/f52ab6e4940f9095c4fc5e2f7860bd56747f1c7c#diff-40e4270ec386990ac60d7ab5ff80454aR166
[2] https://github.com/ruby/ruby/commit/f012932218fd609f75f9268812df61fb26e2d0f1#diff-40e4270ec386990ac60d7ab5ff80454a
=> (PUP-9455) Ensure dummy passphrase is 4 bytes

lib/puppet/network/http/connection.rb, spec/unit/network/http/connection_spec.rb
This is another improvement for PUP-3238, though not a solve.
It turns out Net::HTTP will raise other errors, such as Timeout::Error, in
addition to the previously caught EOFErrors. To further clarify to the user
what is happening when these network issues occur, this commit also catches and
adds contexual information to Timeout::Error exceptions.
For completeness, in the event any other type of exception is raised we also
catch it and add the uri context. Seconds elapsed is omitted in the general
case because not knowing what the exception is, it's not certain whether or
not seconds elapsed will be relevant.
See also: bd737a89a213e15c3d1db32e64bd596b08886b2a
=> (maint) Clarify error on Timeout::Error exception

lib/puppet/network/http/connection.rb, spec/unit/network/http/connection_spec.rb
Previously, if the server's cert did not match the hostname we tried to connect
to, puppet would output a confusing message:
certificate verify failed: [ok for /CN=XXX]
This occurs because ruby 2.4 introduced a new security feature whereby the cert
is automatically verified during the call to `SSLSocket#connect`[1]. In earlier
ruby versions, the application had to call `SSLSocket#post_connection_check`,
but of course, many people forgot to, or didn't know they had to, leading to
MITM vulnerabilities.
However, when a mismatch occurs, ruby 2.4 invokes our `verify_callback` with
`preverify_ok=false`, but `store_context.error=0` which is `OpenSSL::SSL::V_OK`.
Ruby then raises an `SSLError` whose message is 'certificate verify failed',
which matches the first "if" statement in our error …
=> (PUP-8213) Display correct message when certname is mismatched

lib/puppet/type/exec.rb, spec/unit/type/exec_spec.rb
If any of :command, :onlyif, or :unless are sensitive, mark them all sensitive.
Also, revert some earlier changes to exec provider run methods try to work around this issue.
=> (PUP-9357) Redact check if sensitive

lib/puppet/defaults.rb
For Windows agents, the default is false for versions 4.10.13+, 5.5.6+, and 6.0+
=> (Docs) Adding note to manage_internal_file_permissions

lib/puppet/configurer.rb
Commit 2e24fb76c84c8604da3606967f69a0a29b85f265 ensures we no longer
push nil on the context. As a result, we can remove the nil check inside
the block, and specify the `master_used` in the else clause.
=> (maint) Remove unnecessary condition

lib/puppet/network/http/connection.rb, spec/unit/network/http/connection_spec.rb
This reverts commit aab7b62b40b05445db09ea3f5ece6d7a52a0cd49, reversing
changes made to 2c3f51ba1a10fdc3ba1398b4e214c6e09c43a85f.
=> Revert "Merge pull request #7401 from joshcooper/certmismatch_8213"

lib/puppet/util/ssl.rb, spec/unit/network/http/connection_spec.rb
Restore the previous behavior of checking for "certificate verify failed" message first, expecting `hostname was not match with server certificate` (sic), and skipping some tests on windows and jruby.
=> Merge 5.5.x to 6.0.x

spec/unit/util/storage_spec.rb
Before this change, sometimes tests could fail because Floating point numbers would not be exactly equal.
With this change, comparison is now within a small amount of time, so a false fail is less likely.
=> (maint) Convert time eq to within in spec test

lib/puppet/type/exec.rb, spec/unit/type/exec_spec.rb
Prior to this, an exec's check that the `creates` path exists was hidden from the user.
That behavior was inconsistent with the `onlyif` and `unless` checks as those log to debug when they are being checked.
After this commit, when the creates path is being checked for existence, a debug-level message will be shown to inform the user that the check is happening.
```
Checking that 'creates' path '/path/to/creates' exists
```
=> (PUP-9511) Log an exec's "creates" check to debug

acceptance/tests/reports/failover_master.rb
When `server_list` is set, rather than fall back to the default `server`
setting, puppet should just fail.
This commit updates the acceptance tests, which were missed when this
change was originally made.
=> (PUP-9076) Puppet should fail when it cannot find a functional server

lib/puppet.rb, lib/puppet/configurer.rb, lib/puppet/indirector/rest.rb, lib/puppet/network/http_pool.rb, lib/puppet/reports/http.rb, lib/puppet/ssl/ssl_provider.rb, lib/puppet/ssl/verifier.rb, lib/puppet/test/test_helper.rb, lib/puppet/type/file/source.rb, lib/puppet/util/connection.rb, lib/puppet/x509/cert_provider.rb, spec/integration/network/http_pool_spec.rb, spec/unit/configurer_spec.rb, spec/unit/indirector/rest_spec.rb, spec/unit/network/http_pool_spec.rb, spec/unit/reports/http_spec.rb, spec/unit/ssl/ssl_provider_spec.rb, spec/unit/type/file/source_spec.rb
Load an `ssl_context` based on available cert and keys, and make it
available in puppet's global context. Update call sites to use the new
`HttpPool.connection` method.
This doesn't change the certificate related rest methods as they are
called during SSL bootstrapping, before we have a complete SSL context.
If certs, private key, or CRL are not available, then raise an error telling
users which file is missing and to run `puppet agent -t` to bootstrap the SSL
process. For example, if the agent has never run, so there's no CA cert:
$ puppet filebucket backup file.txt
Error: Failed to initialize SSL: The CA certificate is missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Error: Run `puppet agent -t`
If all of the prerequisite files exist, but we fail to load the SSL context,
such as a …
=> (PUP-9461) Use new http connection method

lib/puppet/provider/file/windows.rb, lib/puppet/type/file/mode.rb, lib/puppet/util/windows/security.rb, spec/integration/provider/file/windows_spec.rb, spec/integration/type/file_spec.rb
This commit updates the mode calculations in puppet to treat "FullControl" as insync for the SYSTEM user in the following specific scenario:
1. the file resource does _not_ manage the group
2. the group set for the file is the "SYSTEM" (this is set automatically in windows when puppet runs as the SYSTEM user and creates a file)
This scenario occurs when a file resource does not manage the group on windows and the puppet run that creates the file is run as SYSTEM. Puppet runs will run as SYSTEM when puppet runs as a service, or during invocations from pxp-agent.
For more details on the underlying problems, see https://tickets.puppetlabs.com/browse/PUP-9337
=> (PUP-9337) Update mode check to treat FullControl as insync for windows SYSTEM user

lib/puppet/loaders.rb, lib/puppet/pops/loader/generic_plan_instantiator.rb, lib/puppet/pops/loader/loader_paths.rb, lib/puppet/pops/loader/module_loaders.rb, lib/puppet/pops/loader/puppet_plan_instantiator.rb, spec/unit/pops/loaders/loader_spec.rb
This adds a second loader for plans which will find plans with a .yaml
extension. Because plans in general, and YAML plans especially, aren't a
meaningful concept in Puppet proper, this loader just calls out to an
injected `yaml_plan_instantiator` to handle actual creation of the plan
once it's been loaded.
This will prefer .pp plans over .yaml when two files with the same name
exist.
=> (PUP-9512) Allow discovering and loading of YAML plans

lib/puppet/file_system.rb, lib/puppet/file_system/file_impl.rb, lib/puppet/file_system/jruby.rb, lib/puppet/file_system/windows.rb, lib/puppet/x509/pem_store.rb, spec/unit/file_system/uniquefile_spec.rb, spec/unit/file_system_spec.rb
Add a `FileSystem.replace_file` method to supersede `Puppet::Util.replace_file`, as the latter only applies the specified mode if it needs to create the file, but not overwrite it.
=> (PUP-9499) Add FileSystem.replace_file

lib/puppet/x509/cert_provider.rb, lib/puppet/x509/pem_store.rb, spec/unit/file_system_spec.rb, spec/unit/x509/cert_provider_spec.rb, spec/unit/x509/pem_store_spec.rb
Set the mode, and optionally owner & group when saving PEM files, based on the corresponding puppet setting, eg `:hostprivkey`. The private key mode is 0640, the other PEM files are 0644. If the service user & group accounts are available, then also chown/chgrp the files. This is necessary when puppet is running on the puppetserver host, since the jetty process shares the agents private key, and must be readable by that process.
PR https://github.com/puppetlabs/puppet/pull/7426 must be merged first
=> (PUP-9463) Set mode when saving private keys

lib/puppet/network/http/connection.rb, lib/puppet/type/file/source.rb, lib/puppet/util/http_proxy.rb
Print HTTP request and response info when running with debug:
Debug: HTTP GET https://puppet.delivery.puppetlabs.net:8140/puppet/v3/file_metadatas/pluginfacts returned 200 OK
Unfortunately there isn't a single place where all connections route through, so
we have to account for the three different cases:
* Puppet::Network::HTTP::Connection.request_* Used to stream file sources with
scheme 'puppet'
* Puppet::Util::HttpProxy.request_with_redirects Used to stream file sources
with 'http(s)' schemes.
* Puppet::Network::HTTP::Connection.{get,post,etc} Used in REST termini,
configurer, etc.
=> (PUP-8769) Print HTTP request and response

lib/puppet/application/ssl.rb, lib/puppet/ssl/state_machine.rb, spec/unit/application/ssl_spec.rb, spec/unit/ssl/state_machine_spec.rb
Run the SSL state machine to ensure we have a CA bundle, CRL bundle (if
revocation is enabled), and a private key and signed client cert. This makes it
possible to bootstrap an agent without having to apply a catalog. The bootstrap
command behaves like the agent command, waiting every `waitforcert` seconds if
the cert is not signed. The wait interval can be changed via the setting of the
same name, or disabled by setting it to 0:
puppet ssl bootstrap --waitforcert 0
In order to see any useful information, set the log level to :info. But don't
lower the log level from :debug, if that's what the user requested.
=> (PUP-9556) Add puppet ssl bootstrap action 

lib/puppet/util/connection.rb, lib/puppet/util/feature.rb, spec/unit/util/feature_spec.rb
This commit re-words the debug message emitted when a library required by a
feature could not be loaded. The new message clarifies that an optional feature
is not being enabled and removes the word "fail" which ensnares folks who are
attempting to debug problems unrelated to the feature system.
=> (PUP-8586) Improve missing library debug message

lib/puppet/ssl.rb, lib/puppet/ssl/host.rb, lib/puppet/ssl/state_machine.rb
Reduce state machine debug output, so there's just one debug per state. Remove dead code from `Puppet::SSL::Host`, and remove duplicate `CA_NAME` constant.
=> (maint) Reduce state machine debug output

lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
Improve message when cert can't be downloaded, so it's clear the agent
is waiting for the cert to be signed on the CA.
Previously the stdout expectation wasn't testing anything due to the
SystemExit. Switch the order of expectations so we rescue the SystemExit
first, and then assert the expected output.
=> (PUP-3122) Improve message when cert hasn't been signed yet

lib/puppet/defaults.rb
The setting does not allow a cert request to overwrite a certificate. It's more
that the CA will accept a CSR while there is already a pending CSR or a signed
cert with that name. If it's the former, then the new CSR will overwrite the old
one. If it's the latter, then the CSR will be saved, but the user must still
clean (revoke+delete) the old cert, and sign the new CSR.
=> (PUP-9574) Reword allow_duplicate_certs setting

lib/puppet/application/device.rb, spec/unit/application/device_spec.rb
Successful run with this patch against two devices at the same time:
```
david@davids:~/git/puppet$ bundle exec puppet device --verbose --trace --strict=error --deviceconfig device.conf 
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: starting applying configuration to spinner1 at file:///home/david/git/puppetlabs-test_device/conf.conf
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Spinning for 0.1s and waiting for 0.2s
Info: Caching catalog for spinner1
Info: Applying configuration version '1554129791'
Notice: Applied catalog in 0.07 seconds
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: starting applying configuration to spinner2 …
```
=> (PUP-9587) `puppet device` SSL initialisation fixes

lib/puppet/application/ssl.rb, lib/puppet/ssl/certificate.rb, lib/puppet/ssl/error.rb, lib/puppet/ssl/ssl_provider.rb, lib/puppet/ssl/state_machine.rb, lib/puppet/ssl/validator/default_validator.rb, lib/puppet/ssl/verifier.rb, lib/puppet/util/monkey_patches.rb, spec/integration/network/http_pool_spec.rb, spec/integration/rest/client_spec.rb, spec/unit/application/ssl_spec.rb, spec/unit/ssl/ssl_provider_spec.rb, spec/unit/ssl/state_machine_spec.rb, spec/unit/ssl/validator_spec.rb, spec/unit/ssl/verifier_spec.rb, spec/unit/util/monkey_patches_spec.rb, spec/unit/util/windows/root_certs_spec.rb, spec/unit/x509/cert_provider_spec.rb
The `OpenSSL::X509::Name#to_s` method uses the default "oneline"
format, which corrupts non-ASCII characters. For example, the 𠜎 character when
UTF-8 encoded is 0xF0, 0xA0, 0x9C, 0x8E, but `Name#to_s` encodes each byte as
the 4 byte sequence `\\`, 'x', &lt;hex&gt;, &lt;hex&gt;, resulting in a 16 byte sequence.
irb(main):006:0> name = "CN=root-ca-𠜎"
=> "CN=root-ca-𠜎"
irb(main):007:0> OpenSSL::X509::Name.parse(name).to_s
=> "/CN=root-ca-\\xF0\\xA0\\x9C\\x8E"
irb(main):008:0> OpenSSL::X509::Name.parse(name).to_utf8
=> "CN=root-ca-𠜎"
Use `OpenSSL::X509::Name#to_utf8` explicitly. This is mostly an issue
for CA certs, since the subject doesn't correspond to a hostname and can
be anything like:
C=HU, L=Budapest, O=NetLock Kft., OU=Tanúsítványkiadók (Certification Services), CN=NetLock Arany …
=> (PUP-9472) Emit X509::Name as UTF-8

lib/puppet/transaction/event_manager.rb, spec/unit/transaction/event_manager_spec.rb
Having both add_callback_status_event and fail_with_event created two almost identical events.  These events were causing problems with checks in PuppetDB.  After this change, only one event is generated.
=> (PUP-9586) Remove Duplicate Failed Event

acceptance/tests/server_list_setting.rb, lib/puppet/application/filebucket.rb, lib/puppet/configurer.rb, lib/puppet/indirector/request.rb, lib/puppet/indirector/rest.rb
This commits adds additional debug statements to show exactly where the
server setting is being defined. This hopefully will help elucidate some
of the confusion around the `server` and `server_list` settings.
=> (PUP-9470) Document which settings the value of server originates

spec/unit/transaction/event_manager_spec.rb
Though 5.5.x tests were passing, this change is required for 6.0.x
=> (PUP-9586) Fix spec failure

lib/puppet/transaction/event_manager.rb, spec/unit/transaction/event_manager_spec.rb
Preserve the original behavior of emitting an error message that the
callback failed, followed by the exception that caused the issue:
Error: /Stage[main]/Main/Exec[exec]: Failed to call refresh: '/usr/bin/false' returned 1 instead of one of [0]
Error: /Stage[main]/Main/Exec[exec]: '/usr/bin/false' returned 1 instead of one of [0]`
=> (PUP-9586) Preserve error showing callback failed

spec/unit/transaction/event_manager_spec.rb
In 6.x, puppet's `log_exception` no longer calls `Puppet.err`, instead
using `send_log(:err, 'message')`, which breaks our expectation. Since
the expectation is already handled by examining the collected logs, just
do that.
=> (PUP-9586) Account for different Puppet.err behavior

lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
Previously, `puppet agent -t --waitforcert N` ignored `waitforcert`. This was
because `-t` implies `--onetime`, and the state machine would always exit when
`onetime` was set, regardless of `waitforcert`.
This commit simplifies the state machine to only observe the `waitforcert`
setting. The `puppet agent` application already maps `onetime=true` to
`waitforcert=0`, so it doesn't need to be repeated in the state machine.
The `puppet device` application doesn't have the same problem, because
it doesn't have a `--test` option, nor does it automagically map options
to `onetime`.
=> (PUP-9589) Ignore onetime in state machine

.gemspec, ext/project_data.yaml
When fast_gettext was added as a dependency back in 2dffc4eab942e987dbf9d365b4c3c3e2448cfafa, fast_gettext-1.2 required Ruby 2.1 and it was decided to use fast_gettext-1.1.x (probably an old legacy version of Puppet was using an older Ruby?).
Now that all supported releases of Puppet are shipped with Ruby 2.1+, fast_gettext constraint can be relaxed.
`~> major.minor` dependencies make it easier to maintain he Puppet stack in an non-AIO system-wide environment.
=> (maint) Relax fast_gettext gem constraint

lib/puppet/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
Currently, On AmazonLinux, every puppet run throws this warning message: 
```
Warning: Found multiple default providers for package: yum, pip3, puppet_gem; using yum
```
Here is the `os` facts hash on Amazon Linux:
```
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Amazon",
release => {
full => "2018.03",
major => "2018",
minor => "03"
},
selinux => {
enabled => false
}
}
```
Here is the `os` facts hash on Amazon Linux 2:
```
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Amazon",
release => {
full => "2",
major => "2"
},
selinux => {
enabled => false
}
}
```
=> (maint) Amazon linux reports majrelease as '2018'

lib/puppet/application/device.rb, spec/unit/application/device_spec.rb
Call `Puppet.settings.use` at the right point where all paths are
configured but before any work happens. This will ensure that all
directories are available that puppet requires.
This also removes the undocumented `:device` section, that likely was
overridden anyways as it was called too early.
The initial edge case hit was when specifying `--graph` on the CLI or
`graph=true` in the configuration file while running in `--apply` mode,
the `$statedir/graphs` directory was missing.
=> (PUP-9047) Refactor Puppet.setting usage

lib/puppet/application/device.rb, spec/unit/application/device_spec.rb
This commit fixes two performance issues with pluginsyncing:
* plugins were synced twice
* the HTTP connections were not re-used
With this commit applied, a full (no-resource) run against a device
improved from 32s to 13s wall clock time
=> (PUP-9584) optimize pluginsync for devices

lib/puppet/application/device.rb, spec/unit/application/device_spec.rb
Previously the device application failed when trying to download a
catalog for a device, because the SSL statemachine doesn't take a
`certname` keyword argument.
If `--libdir` is specified, then we want to continue skipping pluginsync, but we
still need to ensure the per-device ssl_context is initialized before requesting
a catalog on behalf of the device. If we created a per-device ssl_context, then
push that on the context stack so we don't accidentally fall back to the
non-device one.
=> (PUP-9579) Push device specific ssl_context

acceptance/tests/server_list_setting.rb, lib/puppet/application/device.rb, lib/puppet/application/filebucket.rb, lib/puppet/configurer.rb, lib/puppet/indirector/request.rb, lib/puppet/transaction/event_manager.rb, lib/puppet/util/connection.rb, spec/unit/application/device_spec.rb, spec/unit/transaction/event_manager_spec.rb
Had a few conflicts with device, debug_once and ssl_context:
* Use persistent http connections when pluginsyncing per device using http_pool
* If `libdir` device option is used, setup the ssl context, but don't pluginsync
* If we have a per-device `ssl_context` use that during the configurer run
* Use global `device` settings once, and then re-use `main`, etc settings per device
* Update indirector request to use `debug_once` like `puppet/util/connection`
* Emit debug showing how server/server_list was resolved
* Don't emit duplicate refreshed failed event
=> (maint) Merge 6.0.x to 6.4.x

lib/puppet/type/notify.rb
This addition was suggested by a Puppet docs site feedback provider, who cited PUP-1113 and noted that the 'notify' resource type doc currently doesn't mention this type's lack of idempotency.
=> (docs) Note changes on every Puppet run in 'notify' doc

lib/puppet/defaults.rb
It is possible that when `environment_timeout = unlimited`, the value
has already been converted to `Infinity` by the time we reach the
deprecation hook. In order to avoid printing out the warning
unexpectedly, we should account for that possibility in the hook itself.
This commit updates the deprecation accordingly.
=> (PUP-9497) Allow envioronment_timeout to be Infinity

lib/puppet/type/schedule.rb
A Puppet docs site feedback provider asked for clarification on this attribute.
=> (docs) Clarify `period => never`

acceptance/lib/puppet/acceptance/common_utils.rb, acceptance/tests/resource/cron/should_allow_changing_parameters.rb, acceptance/tests/resource/cron/should_be_idempotent.rb, acceptance/tests/resource/cron/should_create_cron.rb, acceptance/tests/resource/cron/should_match_existing.rb, acceptance/tests/resource/cron/should_remove_cron.rb, acceptance/tests/resource/cron/should_remove_leading_and_trailing_whitespace.rb, acceptance/tests/resource/cron/should_remove_matching.rb, acceptance/tests/resource/cron/should_update_existing.rb, acceptance/tests/resource/cron/should_write_new_users_crontab_after_puppet_creates_them.rb, acceptance/tests/resource/file/symbolic_modes.rb, acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_home.rb, acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_uid.rb, acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb, acceptance/tests/resource/user/should_create.rb, acceptance/tests/resource/user/should_create_with_gid.rb, acceptance/tests/resource/user/should_manage_groups.rb, acceptance/tests/resource/user/should_manage_shell.rb, acceptance/tests/resource/user/should_modify_gid.rb, acceptance/tests/resource/user/should_modify_home.rb, acceptance/tests/resource/user/should_modify_uid.rb, acceptance/tests/resource/user/utf8_user_comments.rb, acceptance/tests/ticket_9862_puppet_runs_without_service_user_or_group_present.rb, lib/puppet/provider/user/directoryservice.rb, spec/unit/provider/user/directoryservice_spec.rb
Due to FDA restrictions puppet is unable to change NFSHomeDirectory
or uid of an user using `dscl . -merge`.
Replaced `dscl . -merge` with `dscl . -create` when adding a new resource.
Added a failure message when trying to update the home/uid of an user on OS X 10.14
Added tests for home and uid.
=> (PUP-9640) Change user management on OS X 10.14

lib/puppet/type/exec.rb
hi. :)
I can't believe this wasn't written down anywhere before, but anyway, I was actually using it in anger and had to double-check that it worked like I remembered.
=> (docs) exec resources are non-isomorphic (duplicate namevars allowed)

lib/puppet/application.rb, spec/unit/application_spec.rb
Before PUP-2997 (dbf0ac4f3d) it was possible to specify multiple log destinations on the command line by repeating the --logdest arg. In order to restore this ability, we're still setting a flag that lets us know that we've already set a log destination whenever we handle_logdest_arg, but handle_logdest_arg no longer bails out early if this flag has been set. We now use the flag to avoid calling handle_logdest_arg with the "default" log destination if we've already set the log destination based on command line arguments.
=> (PUP-9565) Allow specifying --logdest multiple times on the command line

lib/puppet/provider/package/gem.rb, spec/unit/provider/package/gem_spec.rb, spec/unit/provider/package/puppet_gem_spec.rb
With this commit, install specifies version-specific parameters to not install
documentation, and specify those parameters independent of the source parameter.
=> (PUP-9395) specify version-specific documentation params with install

lib/puppet/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
Prior to this commit, Amazon Linux did not have a default package provider set. This commit ensures that all versions of Amazon Linux will default to using the yum package provider.
Users will no longer get a warning about multiple default package providers.
=> (maint) Default Amazon Linux to yum

lib/puppet/functions/regsubst.rb
Generated docs for these examples is not showing up, and it might be an issue with the empty line in between the @ tag and the example.
=> (DOCS) PDOC-265 fix example formatting

lib/puppet/face/catalog.rb
The `master` subcommand was removed in Puppet v6 but is still in use by
users to compile catalogs without a server (e.g. `puppet master
--compile ...`).
Setting `run_mode` to `master` for the Catalog face effectively makes
`puppet catalog compile` behave the same way that `puppet master --compile` did. 
This is due to how "run mode" is used inside Puppet (changes default
config paths and which config option names are used).
Unfortunately I cannot find a way to get the `run_mode` override in
`Puppet::Application`, where it's used before the face options are
parsed, _and_ provide a help message for it.
=> (PUP-9055) Expose function similar to `puppet master --compile`

Gemfile
This is depended on by webmock and has caused puppetserver tests to start failing.
=> (maint) Pin hashdiff to ruby 1.9 compatible version

lib/puppet/error.rb, lib/puppet/face/parser.rb, spec/unit/face/parser_spec.rb
Tools like the Puppet Development Kit which invoke `puppet parser validate` on behalf of the user need a consistent, machine-readable output format so that they don't have to rely on complex and brittle regular expressions matching output that may change between Puppet releases.
=> (PUP-8984) Add --format=json option to `puppet parser validate`

lib/puppet/pops/types/types.rb, spec/unit/pops/types/types_spec.rb
Before this it was not possible to conveniently create a regular
expression with all regexp special characters escaped.
With this commit, an optional boolean flag is added to `Regexp.new` such
that if set to true, the created regexp will have all special characters
in the input escaped.
=> (PUP-9554) Add ability to create Regexp with boolean to control escape

lib/puppet/pops/types/types.rb, spec/unit/functions/new_spec.rb
Before this, the input to Integer.new was checked with a regexp such
that if a value started with a leading zero it must also be a valid
octal number. That was bad because it prevented an explicit conversion
from for example "08" with radix 10.
This is now changes so that leading zeros are accepted by the function,
and that any error is instead triggered when the conversion takes place.
Additional test cases added.
=> (PUP-9689) Make Integer.new accept leading 0 for explicit base 10 conv

lib/puppet/defaults.rb, lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
If `waitforcert` is specified, such as when using `puppet agent -t`, then the
agent will wait indefinitely for its cert to be signed, which can be a problem
if there's an infrastructure issue.
This commit adds a `maxwaitforcert` setting of type `ttl`. Acceptable values are
`unlimited` or a duration, such as `5m`, `1h`, etc. The default value is
`unlimited`, so the new behavior must be opted into.
=> (PUP-3237) Accept maximum time to wait for cert

lib/puppet/application/lookup.rb
fix lookup option spelling to be consistent with code and documentation
=> (maint) fix lookup option spelling to be consistent

lib/puppet.rb, lib/puppet/application/agent.rb, lib/puppet/application/ssl.rb, lib/puppet/ssl/ssl_provider.rb, lib/puppet/ssl/state_machine.rb, lib/puppet/x509/cert_provider.rb, spec/unit/application/ssl_spec.rb, spec/unit/ssl/ssl_provider_spec.rb, spec/unit/ssl/state_machine_spec.rb, spec/unit/x509/cert_provider_spec.rb
Historically `Puppet::SSL::Key` supported password protected private keys,
provided the password file `Puppet[:passfile]` existed prior to
`Puppet::SSL::Host` being initialized the first time. However, it has two
limitations:
* If the private key was encrypted and the `passfile` was later deleted, then
ruby would hang trying to prompt for the password.
* Private keys were encrypted using 3DES-CBC, which is outdated.
This commit adds an optional `password` keyword argument to encrypt and decrypt
the private key. Decryption will use the cipher and IV specified in the PEM
header, such as `DEK-Info: AES-128-CBC,7D9CB780A5571FAC184E44E1D736A163`, and
the provided password.
Encryption will always use AES-128-CBC and save the private key in the
"traditional" PEM format, not PKCS8. GCM is not an …
=> (PUP-9466) Readd encrypted private keys

lib/puppet/defaults.rb, lib/puppet/file_system.rb, lib/puppet/file_system/file_impl.rb, lib/puppet/rest/routes.rb, lib/puppet/ssl/state_machine.rb, lib/puppet/test/test_helper.rb, lib/puppet/x509/cert_provider.rb, spec/unit/file_system_spec.rb, spec/unit/ssl/state_machine_spec.rb, spec/unit/x509/cert_provider_spec.rb
Allow the agent to periodically refresh its CRL using `If-Modified-Since`
header support added in PUP-8913.
By default, the agent will never refresh its CRL. However, a refresh interval
can be specified in `Puppet[:crl_refresh_interval]`. If set, the agent will
refresh at most once within that interval, eg once every '8h'.
If the refresh request succeeds, then the agent will use the newly downloaded
CRL for subsequent requests.
If the refresh request fails, then the agent will ignore the error and continue
running with the existing set of CRLs. However, if the failure occurs when
downloading the initial CRL, then the agent run will fail.
=> (PUP-2310) Allow agent to refresh CRL periodically

lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/fixtures/unit/pops/loaders/loaders/mix_4x_and_3x_functions/usee/lib/puppet/parser/functions/func_with_syntax_error.rb, spec/unit/pops/loaders/loaders_spec.rb
Before this, if there was a syntax error in a loaded 3.x function
it would be reported as "not containing a call to newfunction" and
the syntax error information would not be shown.
This commits changes this so that syntax errors surface unchanged.
A change was made to the code assertion such that it returns boolean tru
if it was possible to parse, and false otherwise. If false it lets the
real eval of the code string take place and to produce the error.
=> (PUP-9643) Make syntax errors from 3x function loading surface

lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
Prevent multiple puppet processes from running the state machine
concurrently, as it can cause the second process to overwrite the
private key saved by the first process.
=> (PUP-2958) Protect the ssl state machine with the agent lock

lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/pip.rb, lib/puppet/provider/package/pip3.rb, lib/puppet/provider/package_targetable.rb, lib/puppet/type/package.rb, spec/integration/type/package_spec.rb, spec/unit/provider/package/gem_spec.rb, spec/unit/provider/package/pip3_spec.rb, spec/unit/provider/package/pip_spec.rb, spec/unit/provider/package/puppet_gem_spec.rb
With this commit ...
Package providers can implement a targetable `command`.
The gem (and puppet_gem) package provider implements a targetable `command`.
The pip (and pip3) package provider implements a targetable `command`.
=> (PUP-6488) targetable package command

lib/puppet/util/skip_tags.rb, spec/unit/util/skip_tags_spec.rb
Don't split tags in skip_tags on namespace separator.
I noticed this issue in Puppet 5.4.0 and I was able to reproduce it on `master` branch(`e1aee1ccb17a49798f3dae90172e7cb0b9c8518f`). My patch makes `skip_tags` behave similarly to `tags` option. Let me know, if you would like to change/add anything, before you consider merging.
Manifest:
```ruby
class l1 {
contain l1::l2_1
contain l1::l2_2
file { '/home/jakub/test':
ensure => directory,
}
}
class l1::l2_1 {
file { '/home/jakub/test/l2_1':
}
}
class l1::l2_2 {
file { '/home/jakub/test/l2_2':
}
}
include l1
```
Running without patch:
```
$ bundle exec puppet apply test.pp --skip_tags l1::l2_1 --debug | grep 'Skipping with skip tags'
Debug: Class[L1]: Skipping with skip tags l1::l2_1, l1, l2_1
Debug: …
```
=> (PUP-8215) Don't expand skip_tags

acceptance/lib/puppet/acceptance/common_utils.rb, acceptance/tests/provider/package/dpkg_ensure_held_package_is_latest.rb, acceptance/tests/provider/package/dpkg_ensure_held_package_should_preserve_version.rb, lib/puppet/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
This PR fixes the following bug:
When setting a package to held first it checks if the package is installed on the system, if true then it only sets it's state to held, if false then it installs the latest package and after it sets it's state to held.
Before this it would install the latest package and after that the state would change to held.
=> (PUP-9564) Fix package update on resource held

lib/puppet/configurer.rb, lib/puppet/settings/server_list_setting.rb, spec/unit/configurer_spec.rb, spec/unit/settings/server_list_setting_spec.rb
This PR changes the output of server_list when using `config print` as well as in error messages when no server could be reached. It also changes and adds tests to ensure this change.
=> (PUP-9495) formatting server_list output

lib/puppet/util/windows/registry.rb, spec/integration/util/windows/registry_spec.rb
Sanitize the values after they are read from the windows registry.
=> (PUP-9639) Sanitize Windows Registry read strings

spec/integration/provider/service/init_spec.rb
The init provider also asks Facter for the :osfamily, so add that to the
spec.
This fixes the init_spec.
=> (maint) init_spec, expect :osfamily as well

lib/puppet/parser/functions/fail.rb
#fixes: https://tickets.puppetlabs.com/browse/DOCUMENT-1004
The [documentation](https://puppet.com/docs/puppet/latest/function.html#fail)  for the [`fail()`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/parser/functions/fail.rb) function should mention what it does with its parameters.
=> [DOCUMENT-1004] Improve docstring for the fail() function.

spec/integration/type/file_spec.rb
The test command is found in /usr/bin rather than /bin on Debian, as it
is on Ubuntu. Use :osfamily rather than :operatingsystem to set the
correct value for any Debian flavor.
This fixes this test when run on Debian.
=> (maint) file_spec, fix path to test command on Debian

lib/hiera/scope.rb, spec/unit/hiera/scope_spec.rb
Before this, interpolating keys into a hiera 3 backend managed value where the key specified a `convert_to` would fails because the `convert_to` makes a call to `call_function` on the scope that is passed in. This did not work because in Hiera 3 there is a special `Hiera::Scope` wrapper around the real scope, and the hiera wrapping scope is passed around. This PR makes the Hiera::Scope delegate `call_function` to the real scope.
=> (PUP-9693) add call function to hiera wrapping scope

acceptance/Gemfile
vcloud hyperisor is needed by the imaging pipelines so adding this to
the Gemfile.
=> (MAINT) Add Beaker vcloud hyperisor to Gemfile

acceptance/tests/puppet_device_test.rb, lib/puppet/application/device.rb
The `puppet device` application is using the `confdir` setting to have
puppet create a new private directory for the device's use. This causes
the directory to be created for each new device through the magic of
`Puppet.settings.use`.
* The defaults do not specify a filemode for `confdir`.
Therefore any environmental markers, like `umask`, get propagated
through to the file system.
* The settings subsystem switches to the configured `user`/`group` before
writing files, and PE is setting those configuration values to non-root
values.
Therefore any filesystem operation has to pass through filesystem
permissions.
With `umask 0027` the `$devicedir/$devicename` directory gets created as
`root/root` with `drwxr-x---` permissions, and the subsequent attempt to
write the private key into a …
=> (PUP-9642) explicitly set the confdir permissions

lib/puppet.rb
The error messaging that occurs when you attempt to load Puppet with an
invalid Ruby version occurs before the i18n machinery is initialized, so
it can't be translated. This commit removes the translation method from
that error.
=> (maint) Remove translation from Ruby version error

lib/puppet/face/catalog.rb
Clarifying what the `catalog find` command retrieves.
=> (DOCS) PUP-9576 clarify catalog find behavior

lib/puppet.rb, lib/puppet/provider.rb
Preserve the changes made in f942554, but puppet 6.0.x requires ruby 2.3 or greater.
=> (maint) Merge 5.5.x to 6.0.x

lib/puppet/util/windows/user.rb, spec/integration/util/windows/user_spec.rb
This PR fixes the following:
When Deny access to this computer from the network is set by group policy in windows
puppet agent tries to logon with LogonUserW function by providing fLOGON32_LOGON_NETWORK logon type. and by default at every agent run it will set the same password because the function returns false.
Refactored the code to use different logon types and added an if block to try to logon with interactive logon type to skip creating a new password at every run.
=> (PUP-9688)-User resource sets password on every PA run

lib/puppet/defaults.rb, lib/puppet/file_system/file_impl.rb, lib/puppet/ssl/state_machine.rb, spec/unit/file_system_spec.rb, spec/unit/ssl/state_machine_spec.rb
Commit 926e0e6436 locked the agent lockfile before running the SSL state machine, but had to be reverted in 3e82d0f860 due to `puppet infrastructure` locking the agent lock and running `puppet ssl bootstrap`.
These commits introduce a new ssl lockfile so that the ssl and catalog application lock files have different scopes.
=> (PUP-2958) Protect the SSL state machine with an ssl lockfile

lib/puppet/provider/package/yum.rb
Amazon machines should use `yum` as their default
package provider.
Due to the recent changes on package providers, when
no default package provider is explicitly set it will
always fallback to puppet_gem/pip/pip3/gem because of the way
that specificity is calculated for a system which does
not have a default(number of ancestors)
Their specificity was lowered to 1 If none of those providers are set as defaults on any operating system.
Code output on an amazon machine: https://gist.github.com/gimmyxd/301a2d38daa6d1e852a117662d18892e
=> (PUP-9724) Use yum as default provider for Amazon

lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/pip.rb, lib/puppet/provider/package/yum.rb, spec/unit/provider/package/gem_spec.rb, spec/unit/provider/package/pip3_spec.rb, spec/unit/provider/package/pip_spec.rb, spec/unit/provider/package/puppet_gem_spec.rb
Due to the recent changes on package providers, when
no default package provider is explicitly set it will
always fallback to gem/puppet_gem/pip/pip3 because of the way
that specificity is calculated for a system which does
not have a default(the match expresion and number of ancestors)
Since those are specific language package managers,
their specificity was lowered to 1 if none of those providers
are set as default provider, otherwise the specficity
is calculated like it was before.
=> (PUP-9727) Reduce specificity of gem, pip providers

lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/pip.rb, spec/unit/provider/package/gem_spec.rb, spec/unit/provider/package/pip3_spec.rb, spec/unit/provider/package/pip_spec.rb, spec/unit/provider/package/puppet_gem_spec.rb
The only conflict was on the man files
```
❯ git merge --no-ff --log pl/5.5.x
--
Auto-merging spec/unit/provider/package/puppet_gem_spec.rb
Auto-merging spec/unit/provider/package/pip_spec.rb
Auto-merging spec/unit/provider/package/gem_spec.rb
Auto-merging man/man8/puppet.8
Auto-merging man/man8/puppet-node.8
Auto-merging man/man8/puppet-module.8
CONFLICT (modify/delete): man/man8/puppet-master.8 deleted in HEAD and modified in pl/5.5.x. Version pl/5.5.x of man/man8/puppet-master.8 left in tree.
Auto-merging man/man8/puppet-key.8
Auto-merging man/man8/puppet-config.8
CONFLICT (modify/delete): man/man8/puppet-certificate_revocation_list.8 deleted in HEAD and modified in pl/5.5.x. Version pl/5.5.x of man/man8/puppet-certificate_revocation_list.8 left in tree.
CONFLICT (modify/delete): …
```
=> (maint) Merge 5.5.x to 6.0.x 

acceptance/tests/resource/user/should_destroy_with_managehome.rb, lib/puppet/provider/user/useradd.rb
See https://tickets.puppetlabs.com/browse/PUP-9706
> *Puppet Version: 6.4.2*
> *Puppet Server Version: N/A*
> *OS Name/Version: Solaris 11*
> 
> *Desired Behavior: Able to remove a user without any errors*
> 
> *Actual Behavior:*
> 
> When applying the following an error occurs:
>```
> root@yz4rr58lsjdxqz3:~# puppet apply -e 'user { "testuser": ensure => "present", managehome => false }'
> Notice: /File[/etc/puppetlabs/code/environments/production]/ensure: created
> Notice: Compiled catalog for yz4rr58lsjdxqz3.delivery.puppetlabs.net in environment production in 0.03 seconds
> Notice: /Stage[main]/Main/User[testuser]/ensure: created
> Notice: Applied catalog in 0.06 seconds
> root@yz4rr58lsjdxqz3:~# puppet apply -e 'user { "testuser": ensure => "absent",  managehome => true  }'
> Notice: …
```
=> (PUP-9706) Solaris userdel does not properly implement :manages_homedir feature.

lib/puppet/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
this PR fixes the following:
When using package ensure => held
If the package is present, lock it to that version,
If the package is not present, install it and lock it to that version.
=> (PUP-9564) fix debian dpkg package installation for resource held.

spec/unit/util/ldap/manager_spec.rb
The setup data for the test preceding the ones removed structured things in such a way that all four tests (including the one not removed) had identical content, and expectations. Rather than run the exact same data through the exact same process, and expect the exact same results, we only do this once now, even though it's not (and never was) individually testing each aspect of the transformation.
=> (PUP-9362) Remove redundant tests

lib/puppet/provider/service/upstart.rb, spec/unit/provider/service/upstart_spec.rb
Previously, the upstart service tests called `unprovide` to force the confine
logic to be re-evaluated for another test. This causes warnings due to constants
being redefined:
warning: already initialized constant START_ON
This commit moves the confine logic to a class method, which allows the
different cases to be tested without unproviding the provider.
=> (maint) Don't reload the upstart provider for 5.5.x

lib/puppet/provider/service/upstart.rb, spec/unit/provider/service/upstart_spec.rb
Previously, the upstart service tests called `unprovide` to force the confine
logic to be re-evaluated for another test. This causes warnings due to constants
being redefined:
warning: already initialized constant START_ON
This commit moves the confine logic to a class method, which allows the
different cases to be tested without unproviding the provider.
=> (maint) Don't reload the upstart provider for 6.0.x

lib/puppet/application/device.rb
This adds the changes from https://github.com/puppetlabs/puppet/commit/92ffa950dd3ce1d22e0129383d92d352e6b7eaab lost in https://github.com/puppetlabs/puppet/pull/7548 merge-up
=> (maint) fix PUP-9047 Refactor Puppet.setting usage

lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
Previously, puppet's ssl state machine would fail to run if the ssl lockfile
existed, no matter what it's contents were. Change the state machine to use
`Puppet::Util::Pidlock` instead which is capable of detecting if the pid refers
to an already running puppet instance.
=> (PUP-2958) Reclaim stale ssl lockfiles

lib/puppet/network/http/factory.rb, spec/unit/network/http/factory_spec.rb
Ruby 2.1.5 introduced automatic retry for idempotent HTTP methods
which ruby defines as: GET HEAD PUT DELETE OPTIONS TRACE. In order to
be idempotent, resending the same request should produce the same
effect as if the request was only sent once.
However, puppetserver processes each report, producing multiple entries in
puppetdb. The latest report doesn't overwrite the earlier report.
Also when puppet submits a report, it will block waiting for the HTTP response
until all report processors are finished. If the connection is dropped, eg load
balancer kills the idle connection, then the agent will retry the request,
causing another instance of the report to be processed.
Ruby 2.5 added an `Net::HTTP#max_retries=` method which defaults to 1, which
means the request will be made once, and …
=> (PUP-3905) Disable ruby's http retry

acceptance/tests/resource/service/init_on_systemd.rb
This commit confines Fedora init-enabled versions to 20-29. Having Sys-V type services is not applicable for Fedora 30 and later since they have migrated to systemd.
Failing run when integrating Fedora 30: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/601/RMM_COMPONENT_TO_TEST_NAME=puppet,SLAVE_LABEL=beaker,TEST_TARGET=fedora30-64a/testReport/junit/(root)/tests_resource_service/init_on_systemd_rb/
=> (maint) Add support for Fedora 30

acceptance/tests/resource/service/init_on_systemd.rb
This commit confines Fedora init-enabled versions to 20-29. Having
Sys-V type services is not applicable for Fedora 30 and later since
they have migrated to systemd.
Same as https://github.com/puppetlabs/puppet/pull/7543, but for 5.5.x
=> (maint) Add support for Fedora 30 (5.5.x)

lib/puppet/util/pidlock.rb, lib/puppet/util/windows/process.rb, spec/unit/util/pidlock_spec.rb
Applying changes from  PUP-9247 on 5.5.x and also fixing the case when puppet runs as a gem. 
This will fix PA-2669 also.
=> (PUP-9691) Puppet pidlock incorrectly clears lock when running under bundler

acceptance/tests/provider/package/dpkg_ensure_held_package_is_latest.rb, acceptance/tests/provider/package/dpkg_ensure_held_package_should_preserve_version.rb, acceptance/tests/puppet_device_test.rb
The puppetserver pre-suites add the 'dns_alt_names' setting to
puppet.conf. This setting is picked up by `puppet device`, meaning that
the CSRs generated for the devices have the alt names in them. In order
to sign these, we need to pass the flag allowing it.
=> (maint) Fix device test to run in the server pipeline 

lib/puppet/application/ssl.rb, spec/unit/application/agent_spec.rb, spec/unit/application/ssl_spec.rb
This will enable puppet ssl tool to work for tasks that need the OIDs.  We are leaving the registration in the agent, and registration is cached so there is minimal extra cost.
=> (PUP-9746) Add registration of OIDs to SSL Context initialization

acceptance/tests/puppet_device_test.rb
Not all tests restart the server as part of state cleanup in their
teardown blocks. Recommended practice instead is to do master
interaction inside a `with_puppet_running_on` block, which resets state
before and after the block. This commit adds such a block to the `puppet
device` test.
=> (maint) Add `with_puppet_running_on` to device test

lib/puppet/provider/cron/crontab.rb
Solaris lists all the crontabs in the same place as Debian, without this, only current user's crontabs will be listed.
=> (PUP-9697) Updated crontab read path for Solaris

lib/puppet/ssl/host.rb, lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
Backports several commits from master: 81e2668, 5c7bfb7, c487c2f 
Updates the state machine to retry when exceptions occur, not just when the CSR hasn't been signed yet. By default the state machine will either reach the Done state or keep retrying, waiting every `waitforcert` seconds in between.
Preserves the behavior where if we ever try to wait, but `waitforcert < 1`, then exit.
Adds a `onetime` option to the state machine so it will raise if an error occurs, and never retry. This is needed for things like `puppet agent --test/--onetime`, which don't retry on errors. It is also needed to preserve the legacy `Puppet::SSL::Host#certificate` behavior.
=> (PUP-9717) Retry state machine on errors

lib/puppet/application/agent.rb, spec/unit/application/agent_spec.rb
PR https://github.com/puppetlabs/puppet/pull/7560 must be merged first
This restores the pre-6.4 behavior of printing the CSR fingerprint if the client
cert doesn't exist. It only looks in the local file system and doesn't change
system state as one would expect when running `puppet agent --fingerprint`.
It does not restore the behavior of downloading the CA/CRL bundle, generating a
key (if missing) or attempting to download the client cert.
If an exception occurs, such as the client cert is invalid, then the exception
is logged instead of using writing to stderr so that the backtrace can be
displayed when running with --trace.
=> (PUP-9720) Restore puppet agent --fingerprint

acceptance/tests/server_list_setting.rb
Applied commit https://github.com/puppetlabs/puppet/commit/6cb9d307541d9ccf356ab13a35db2bea444ac109 which did not target 5.5.x branch
=> (maint) Fix server list setting test

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
The 'simple' status includes the status of all trapperkeeper services
such as the broker and filesync services. Request status for the 'master'
service specifically.
Backports commit 604212978 from PUP-9159
=> (PUP-9698) Request status of the master service

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
PUP-1082 introduced an error by dropping '.class' from
'self.class.pip_version' in the 'latest' class method.
This commit restores that reference, and updates the spec test stubs.
=> (PUP-9790) restore class to pip_version in latest

lib/puppet/provider/package.rb, lib/puppet/provider/package/pip.rb, lib/puppet/provider/package/puppet_gem.rb, lib/puppet/provider/package_targetable.rb
With these commits, 'package_targetable.rb' requires 'puppet/provider/package'
avoiding errors when the gem package provider is the first provider to
be autoloaded, which varies depending on the inode order of files in
'puppet/provider/package' and which one 'Dir.entries' happens to returns first.
The 'package_provider' fact in puppetlabs-stdlib triggers this error when it
requires the 'puppet/type/package' outside the body of 'setcode'.
In between the time that 'puppet/type.rb' is required and when when providers
are loaded 'Puppet::Provider::Package' refers to the wrong object. An explicit
'require puppet/provider/package' overwrites an earlier 'Puppet::Provider::Package'
constant, resulting from a mixin of Puppet::Util and Puppet::Provider.
=> (PUP-9794) prevent autoload superclass errors

lib/puppet/info_service.rb, lib/puppet/info_service/plan_information_service.rb, lib/puppet/module.rb, lib/puppet/module/plan.rb, spec/lib/puppet_spec/modules.rb, spec/unit/info_service_spec.rb, spec/unit/module_spec.rb, spec/unit/plan_spec.rb
This extends the information service to supply information about plans.
Given a module and environment, this code will return all valid plan
files in the `/modules/<name>/plans` directory.
It works similarly to the tasks information service, just without
metadata and multiple implementations.
=> (PUP-9718) Create plan information service

lib/puppet/type/user.rb
If the `gid` user property is managed, but the `groups` property is not, then
the `groups` variable will already be set to an Array. Ensure we only split the
comma delimited string if we're managing the `groups` property.
=> (maint) Only autorequire groups if it's managed

lib/puppet/defaults.rb, lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
If `ca_fingerprint` puppet setting is specified, then the agent will verify the downloaded CA certificate and reject it if its fingerprint does not match.
=> (PUP-9638) Verify CA fingerprint 

acceptance/tests/environment/variables_refreshed_each_compilation.rb
The test relies on nanosecond resolution, but `date` on AIX and OSX don't
support that. Since this is a server test, just skip the test for those agents.
This supersedes the change made in 87083b13ab233a152fdbb07a490a06c613180814
=> (maint) Don't run test on AIX, Solaris or OSX

ext/solaris/smf/puppet.xml
Prior to this commit, the `refresh` action was executed by SMF when the package manifest changed. However, no action was implemented for `refresh`, hence the puppet service did not automatically restart
when the puppet-agent package was upgraded.
This commit adds functionality to the `refresh` action, killing the service for it to be restarted automatically by SMF, which is the intended behavior.
=> (PA-2104) Restart Solaris 11 puppet service on package upgrade

lib/puppet/environments.rb, lib/puppet/pal/catalog_compiler.rb, lib/puppet/pal/pal_impl.rb, spec/unit/puppet_pal_catalog_spec.rb
I have so far found two updates needed to PAL to support adding an AST parsing endpoint to Puppet Server (see https://github.com/puppetlabs/puppetserver/pull/2082).
1) Allow retrieval of the catalog object
2) State cleanup from catalog compiler block
=> (PUP-9818) PAL updates

lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
Implementation for apt and dpkg to allow virtual packages to be installed on the system.
=> (PUP-9824) Allow virtual packages for debian

lib/puppet/face/facts.rb, spec/unit/face/facts_spec.rb
This adds a test to verify `puppet facts upload` passes the current environment and it makes the environment passing explicit. It doesn't result in a functional change, because the indirector request [defaults to the current environment](https://github.com/puppetlabs/puppet/blob/57492210f3b93f7709ea2ad9b6ccc00839a98b70/lib/puppet/indirector/request.rb#L32).
=> (maint) Make facts upload environment explicit

acceptance/tests/modulepath.rb, acceptance/tests/ssl/autosign_command.rb, acceptance/tests/ssl/certificate_extensions.rb
When running beaker tests it's no longer necessary to specify the master,
unless it needs to be overridden, such as to test failover, or if the agent
is using a non-default puppet.conf.
=> (maint) Remove --server option

lib/puppet/face/parser.rb, spec/unit/face/parser_spec.rb
In PUP-8984 the `puppet parser validate` face was refactored to
support the `--render-as json` option and also support validating
multiple files with parse errors in a single execution. (Previously it
would exit immediately on the first parse error.)
The implementation of PUP-8984 introduced a data structure to collect each
file that contained a parse error as well as the error itself.
Unfortunately a bug was introduced where when a manifest with no parse
errors was passed to `puppet parser validate` via the STDIN pipe (e.g.
`puppet parser validate < good.pp`) an entry in the "files with errors"
data structure was still created for "STDIN" but with a value of `nil`
instead of a parse error object. This empty entry caused the output renderer
to pass `nil` to the formatting methods …
=> (PUP-9816) Fix `puppet parser validate` handling of STDIN

lib/puppet/indirector/certificate/file.rb, lib/puppet/indirector/certificate/rest.rb, lib/puppet/indirector/certificate_request/file.rb, lib/puppet/indirector/certificate_request/memory.rb, lib/puppet/indirector/certificate_request/rest.rb, lib/puppet/indirector/key/file.rb, lib/puppet/indirector/key/memory.rb, lib/puppet/ssl/certificate.rb, lib/puppet/ssl/host.rb, lib/puppet/ssl/key.rb
Generate a deprecation warning if `Puppet::SSL::Host` is created. Add `@deprecated` tag to SSL related models and termini.
=> (PUP-9513) Deprecate Puppet::SSL::Host

acceptance/tests/modules/list/with_environment.rb, acceptance/tests/ssl/autosign_command.rb, acceptance/tests/ssl/certificate_extensions.rb
I found these while running `server` tests on the FIPS platform. It turns out they're not exactly FIPS related, but are still good cleanup.
Once these are cleaned up, all `server` tests passed on the FIPS platform, with the caveat that we are not yet using the FIPS version of BouncyCastle. However, with these fixes (notably the tag-related one), we should be able to enable testing on redhatfips in the server pipeline.
=> Test fixes

lib/puppet/provider/service/systemd.rb
With the release of buster planned for July 6, it might be time to set the defaultfor for it (current testing branch reports 10); when the release  is done it will report "bullseye/sid" so set that too.
=> (PUP-9752) defaultfor for released Debian 10 and bullseye/sid

lib/puppet/util/windows/security.rb, lib/puppet/util/windows/sid.rb, spec/integration/type/file_spec.rb
Files present in a system protected filder, like C:\Windows or
C:\Program Files will inherit some additional ACE(Access Control Entries) from the
protected dir. So the file ACL(Access Control List) that stores ACEs will have
additional entries.
The ACE added is "APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES"
with a SID(Security Identifier) of "S-1-15-2-1".
"S-1-15-2-1” is not identified by security.rb as a well known SID,
as it was added in windows 8 to the list of well known SIDs
(https://msdn.microsoft.com/en-us/library/cc980032.aspx), and it is used for
execution of sandboxed applications.
Since it was unable to match to a well known SID, it was unable to map the SID
into POSIX mode, so when getting the mode, it added the S_IEXTRA bit flag indicating
that an access control …
=> (PUP-9722) File mode change on every puppet run

lib/puppet/provider/service/systemd.rb, spec/integration/provider/service/systemd_spec.rb
This PR backports https://github.com/puppetlabs/puppet/pull/5693 to 5.5.x
=> (PUP-7312) - Backport PUP-7312

lib/puppet/forge.rb, lib/puppet/module_tool/applications/installer.rb, spec/unit/forge/module_release_spec.rb, spec/unit/module_tool/applications/installer_spec.rb
The forge API recently added `file_sha256` to the fetch module release
response[1] containing the SHA-256 checksum of the module release tarball. This
commit modifies the `puppet module install` command to prefer SHA-256, or
fallback to MD5 as it did before. If the PMT falls back to MD5 and FIPS is
enabled, then raise an exception like we did before. If both checksums are
missing, raise an exception.
We cannot drop MD5 yet, because some 3rd party forge implementations like
Artifactory haven't been updated to respond with `file_sha256`.
[1] https://forgeapi.puppetlabs.com/#operation/getRelease
=> (PUP-9909) Prefer SHA-256 for forge downloads

lib/puppet/transaction/report.rb, lib/puppet/type/exec.rb, lib/puppet/util/fileparsing.rb, spec/fixtures/unit/provider/parsedfile/aliases.txt, spec/unit/provider/parsedfile_spec.rb
Also:
- remove whitespaces in: lib/puppet/transaction/report.rb
- do an extra check in: lib/puppet/type/exec.rb:576
=> (PUP-9914) Fixed ParsedFile behaviour for records

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
Make the systemd defaultfor the opposite of debian defaultfor. This
should avoid the need for updates with every future Debian release.
=> (PUP-9915) service provider: sync defaultfor :debian

acceptance/tests/resource/service/launchd_provider.rb, lib/puppet/provider/service/launchd.rb, spec/unit/provider/service/launchd_spec.rb
On osx machinse when a service changes its status from running to
stopped, or from stopped to running, it clear its cached status variable
and will return ensure = 'absent'.
Now after the cache is cleared and a service status is requested, it
will reload the status before returning it.
=> (PUP-9908) puppet resource service bad return

lib/puppet/application/device.rb, lib/puppet/defaults.rb, spec/unit/application/device_spec.rb
Prior to this commit, SSL certificates, along with the rest of the Puppet device configuration were stored under cache.
When the proxy Puppet agent for a device is the master, and the user executes a backup and restore (manually, or as automated in OpsWorks), the certificate and keys in the `ssldir` in each `devicedir` are lost, requiring certificate regeneration for those devices.
This commit symlinks the `ssl` directory from `/opt/puppetlabs/puppet/cache/devices/DEVICE/ssl` to `/etc/puppetlabs/puppet/devices/ssl/DEVICE`, ensuring that SSL certificates are not lost when cache is deleted.
=> (PUP-8736) Symlink puppet device certs to /etc

lib/puppet/defaults.rb
The `ssl_server_ca_auth` setting is dead and has been since the ruby webrick
puppet master was removed. Any attempt to get or set the setting will generate a
deprecation warning.
The `ssl_client_ca_auth` setting was created in 3.x to support certificate
chains back when `ca.pem` could only contain a single root CA. The setting is
read whenever `Puppet::Network::HttpPool.http*instance` is called. To prevent
deprecation spamming, only warn if the value is set, as that may indicate the
`ca.pem` does not contain all of the CA certificates that the agent needs to
verify the server's SSL chain.
=> (PUP-9513) Deprecate ssl_{server,client}_ca_auth settings

lib/puppet/pops/lookup.rb, lib/puppet/pops/lookup/key_recorder.rb, lib/puppet/pops/lookup/lookup_adapter.rb
This adds an API for recording all looked up hiera keys (except the
always implicitly looked up `lookup_options` key built into hiera).
=> (PUP-9699) Add recording of all looked up (hiera) keys

lib/puppet/util/monkey_patches.rb, lib/puppet/x509/cert_provider.rb, spec/unit/x509/cert_provider_spec.rb
The method is broken in MRI 2.3, doesn't exist in JRuby 9.1, and is broken in
JRuby 9.2. Just call the appropriate key subclass based on the PEM header. Also
remove our monkey patch since it's no longer used.
As a result of this change, the exception message is different when trying to
read an EC password protected private key, and providing the wrong password,
and the wording is different for MRI 2.3 vs 2.4+.
=> (PUP-9927) Don't call OpenSSL::PKey.read

Gemfile
Ruby no longer supports libshadow, ruby-shadow is now the supported gem for shadow password file interactions.
=> (maint) Update to ruby-shadow gem

.travis.yml, spec/integration/provider/service/systemd_spec.rb
- reworked the travis matrix config to run the checks for ruby
1.9.3 on trusty due to https://github.com/puppetlabs/puppet/pull/7649#issuecomment-516851032
- removed the not needed tests from `spec/integration/provider/service/systemd_spec.rb`
due to https://github.com/puppetlabs/puppet/pull/7649#issue-302942712
=> (maint) Fix tests on travis

.travis.yml, lib/puppet/defaults.rb, spec/integration/provider/service/systemd_spec.rb
Setting `$deviceconfdir` in the main section makes puppetserver want to create it, which it shouldn't.
Starting puppetserver with an affected puppet version fails because of this. Changing the section of `$deviceconfdir` to `agent` fixes the issue.
=> (PUP-9936) Change deviceconfdir section to agent

acceptance/tests/face/parser_validate.rb, acceptance/tests/resource/group/should_query.rb, acceptance/tests/resource/group/should_query_all.rb, acceptance/tests/resource/user/should_purge.rb, acceptance/tests/resource/user/should_query_all.rb
All of these test fails because of Cygwin/UTF handling issues. So going to skip these tests completely on Windows/French locale platform similar to what was done for Japanese.
If we ever get off Cygwin as a test/ssh platform, this should be revisited.
=> (PUP-8319) Skip Failing Windows/French tests

lib/puppet/network/http/factory.rb, spec/unit/network/http/factory_spec.rb
Commit 90560edf0f was supposed to allow puppet to skip a proxy if the host
we're trying to connect to matched an entry in the `NO_PROXY` environment
variable.  However, it didn't actually work, because it passed the `Site`
object instead of a String or URI to `no_proxy?`.
Pass a string representation of the site URI and update tests to not stub
`no_proxy?` behavior.
=> (PUP-9942) Allow puppet to skip a proxy

docs/index.md, docs/indirector.md, docs/quickstart.md
Add docs for indirector subsystem based on https://puppet.com/docs/puppet/5.5/indirection.html
Group deprecated ssl related indirections.
Remove smart quotes.
Update rspec quickstart to not reference deprecated code.
=> (maint) Add indirector docs

acceptance/tests/resource/file/source_attribute.rb, acceptance/tests/ticket_4622_filebucket_diff_test.rb
This commit skips a filebucket test when running in FIPS mode because we
only support FIPS in PE, which disables filebucket. It also fixes up a
typo around FIPS detection logic, to avoid testing md5 sums when
running in FIPS mode.
=> (maint) Update more beaker tests for FIPS mode

lib/puppet/defaults.rb, lib/puppet/util/http_proxy.rb, spec/unit/network/http/factory_spec.rb, spec/unit/util/http_proxy_spec.rb
Prior to this commit, puppet implemented http_proxy* settings in
puppet.conf or as ENV variables, if set; but only implemented the
no_proxy setting as an ENV variable.
With this commit, puppet also implements no_proxy as a setting,
and continues to implement it as an ENV variable, if set.
=> (PUP-9316) implement no_proxy in puppet.conf

lib/puppet/defaults.rb
Previously if an http proxy was configured, then puppet would use it when trying
to connect to localhost or 127.0.0.1. Note HTTPS connections to localhost almost
certainly would have failed due to certname mismatch. However, HTTP connections
would unnecessarily connect via the proxy. In addition to being inefficient,
many network environments don't allow internal users to route through a proxy to
reach other internal hosts, so such requests would fail.
=> (PUP-2172) Don't use an http proxy for localhost

lib/puppet/network/http/factory.rb, spec/unit/network/http/factory_spec.rb
Previously, puppet couldn't connect to an authenticating http proxy for REST
requests.
The Puppet::Util::HttpProxy.proxy method will return a connection object of
class Net::HTTP or the subclass Net::HTTP::Proxy based on the currently
configured proxy host, port, user and password.
=> (PUP-4470) Observe http proxy user/password

acceptance/tests/aix/nim_package_provider.rb
The AIX NIM master is overloaded when this test runs across multiple
branches and AIX versions. Since the code hasn't changed in any
meaningful way since 2015, restrict the test to only AIX 7.2 and
releases greater than 6.4.
Remove outdated comment about pe_acceptance_tests
=> (maint) Restrict where aix nim test runs

lib/puppet/face/plugin.rb, spec/unit/face/plugin_spec.rb
Previously, `puppet plugin download` created a new TCP connection for each file
it downloaded.
Instead use the persistent HTTP pool, which should result in the same behavior
and speed as a normal agent run.
=> (PUP-8662) Use persistent HTTP pool to download plugins

lib/puppet/face/help.rb
Executing puppet help does not show the plugin subcommand, even if the
subcommand is available and working.
Now puppet help includes the plugin subcommand.
=> (PUP-9959) Add plugin to puppet help command

lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
This reverts commit f33a531d71a960360c519e38e977b37112fc99b3.
#	lib/puppet/provider/package/dpkg.rb
=> Revert "(PUP-9824) Allow virtual packages for debian"

lib/puppet/util/execution.rb, spec/integration/util/execution_spec.rb
Previously, calling execute with an array of arguments and `sensitive: true`
options would fail to stringify the array. If one of the arguments wasn't a
string, such as the useradd provider passing a `uid`, then the call to
Kernel.exec would generate a "no implicit conversion of Integer into String"
error.
Commit e1dd1301003 added the `sensitive` option handling, but it wasn't until
commit 70d20329012 that it caused a problem for user providers.
Change the redaction logic so that we always process the `command` string or
argument as before, and afterwards decide whether to redact the command
displayed in debug output.
#	spec/integration/util/execution_spec.rb
=> (PUP-9973) Always stringify execute array arguments

lib/puppet/type/exec.rb, spec/unit/type/exec_spec.rb
When unless or onlyif checks are sensitive, don't log check output to debug
=> (PUP-9956) Suppress exec output when sensitive

lib/puppet/functions/regsubst.rb
YARD tags for ruby code functions should be on the dispatch call, not the function definition.
See https://puppet.com/docs/puppet/latest/puppet_strings_style.html\#functions
=> (docs) Move regsubst function yard tags

.gemspec, ext/project_data.yaml, lib/puppet.rb, lib/puppet/context.rb, spec/unit/context_spec.rb
Make Puppet::Context thread local so that we can do one compilation per thread without needing separate JRuby instances.
This refactors Puppet::Context to use an immutable Stack data structure so that it's easy to put into a single ThreadLocalVar.
This does not address the thread safety of any objects stored within the Context, only the Context itself.
I've removed the ignore feature of Context for now as it appears to be unused and was marked as private api. I can reimplement that if it turns out to be necessary.
=> (PUP-9931) Make Puppet::Context thread local

lib/puppet/module_tool/applications/uninstaller.rb, spec/unit/module_tool/applications/uninstaller_spec.rb
The `uninstall` action detects if there are local modifications to a module
before deleting it. Since module checksum metadata is hardcoded to use MD5, the
entire uninstall action was disallowed in FIPS mode.
This commit relaxes the restriction so that uninstall is allowed provided
`--ignore_changes` or `--force` are specified, since they both skip the check
for local modifications.
=> (PUP-9991) Allow module uninstall in FIPS

Gemfile, spec/lib/puppet_spec/matchers.rb, spec/spec_helper.rb, spec/unit/face/help_spec.rb, spec/unit/functions/contain_spec.rb, spec/unit/node/environment_spec.rb, spec/unit/provider/package/pkgin_spec.rb, spec/unit/type/schedule_spec.rb, spec/unit/util/inifile_spec.rb
* Remove `gem` annotation from spec_helper.rb
* replace last usages of rspec2 collection matchers
=> (maint) cleanup rspec requirements

lib/puppet/context.rb, lib/puppet/thread_local.rb
If we cycle out JRuby instances while using the Java ThreadLocal class,
we end up retaining references to the old JRuby instances. A simple
solution to this is to use the native ruby ThreadLocalVar
implementation, so that when a JRuby instance is GCd everything
stored on the ruby Thread class will be collected as well.
=> (PUP-9931) Use ruby threadlocal implementation

lib/puppet/util/http_proxy.rb, spec/unit/forge/forge_spec.rb, spec/unit/forge/repository_spec.rb, spec/unit/util/http_proxy_spec.rb
Previously puppet would attempt to connect via a proxy if the HTTP_PROXY
environment variable was set, but the destination server matched the
Puppet[:no_proxy] setting. The confusion occurred because ruby's Net::HTTP
automagically resolved proxy settings from the environment, after puppet had
already decided not to use one.
The disconnect is due to ruby 2.0 changing the default behavior of
Net::HTTP.new, which is called by Net::HTTP::Proxy[1]. If the third argument to
the initialize method (`p_addr`) is not specified, then it defaults to :ENV
causing ruby to lookup proxy configuration from the environment. In ruby 1.9 and
before, `p_addr` defaulted to nil.
Net::HTTP::Proxy is also marked as obsolete, so this commit switches to
Net::HTTP.new instead. If puppet decides not to use a proxy, …
=> (PUP-9990) Use Net::HTTP.new instead of Net::HTTP::Proxy

lib/puppet/provider/service/systemd.rb, spec/integration/provider/service/systemd_spec.rb
Reading the symlink of `proc/1/exe` is not the most reliable way
to determine if systemd is the correct service provider
because non root users might not have access to read the symlink:
```
$ ls -l /proc/1/exe
ls: cannot read symbolic link '/proc/1/exe': Permission denied
```
This is causing issues when Puppet is not run as root.
Confine systemd provider based on the content of `proc/1/comm`
```
/proc/[pid]/comm (since Linux 2.6.33)
This file exposes the process's comm value—that is, the com‐
mand name associated with the process.  Different threads in
the same process may have different comm values, accessible
via /proc/[pid]/task/[tid]/comm.  A thread may modify its comm
value, or that of any of other thread in the same thread group
(see the discussion of CLONE_THREAD in clone(2)), by …
```
=> (PUP-10016) Confine systemd based on proc/1/comm

spec/unit/application/agent_spec.rb
Commit b375c9792e added a new describe block in puppet#5.5.x, and that
version doesn't contain the SSL state machine. When the commit was merged
up to 6.4.x, it causes the state machine to run, causing the test to hang
indefinitely.
This commit moves the state machine stub to the top level `before` block so that it applies to all tests (now and in the future).
=> (maint) Always stub state machine

lib/puppet/util/http_proxy.rb, spec/unit/util/http_proxy_spec.rb
This commit adds the query parameters to the HTTP request done by
`request_with_redirects`. This is needed for the `source` attribute of
the `file` resource type if the source URL contains query parameters.
The code itself was extracted from #5002, originally developed by
@mcasper. The reason for the extraction is:
* The original PR seems to be stale.
* The PR fixes another (S3) issue as well
=> (PUP-9109) Add query parameters for HTTP request

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
Without this patch the pip provider doesn't correctly parse pip freeze
output specified with arbitrary equality.
https://www.python.org/dev/peps/pep-0440/#arbitrary-equality
This is manifest with triple === separating the package name from the
package version, e.g.
$ pip freeze | grep pytz
pytz===2012f
By not correctly parsing this output, puppet tries to continually
install this package on each run.
The patch updates the regex to handle arbitrary equality.
=> (PUP-10015) Add support for arbitrary equality to pip provider

lib/puppet/functions/yaml_data.rb
Moves the documentation comments to the right place in the yaml_data function for Puppet Strings output.
=> (docs) move docs strings in yaml_data

lib/puppet/application/device.rb, lib/puppet/application/resource.rb, lib/puppet/resource.rb, spec/unit/application/device_spec.rb, spec/unit/resource_spec.rb
When using --to_yaml, Puppet sometimes produce invalid YAML output. This PR add a unit test that ensures the produced YAML is valid and can be parsed, and rework the way this YAML is produced so that the output can be successfully used in scripts.
=> (PUP-7808) Fix for --to_yaml producing invalid YAML

lib/puppet/ssl/openssl_loader.rb
Previously, we were setting the termini for Certificate,
CertificateRequest, and Key to ensure these indirections that assumed a
working OpenSSL could not be used when JRuby was in FIPS mode (JRuby
does not support its OpenSSL library in FIPS mode).
This seemed to work in Puppet Server integration tests, however when
deployed to servers the load order appears to have changed and now the
openssl_loader is being loaded prior to the Puppet::SSL namespace being
defined causing a NameError.
This simply removes the terminus setting code because:
1) A non-cyclical way to declare this is non-obvious
2) These indirections are deprecated anyway
3) This will cause an ugly error message but it's not clear if that's
a worse UX then not being able to find an appropriate terminus if a
user is unaware of …
=> (maint) Do not set SSL related termini in JRUBY_FIPS

lib/puppet/type/service.rb
From ticket DOC-3261, it appears that defaults for the service type's `enable` and `ensure` attributes vary depending on platform. This PR adds language to that effect.
=> (docs) defaults for service type enable, ensure

lib/puppet/defaults.rb, lib/puppet/indirector/indirection.rb, lib/puppet/test/test_helper.rb, spec/unit/indirector/indirection_spec.rb
This change makes it so that certain settings set at initialization are
threadsafe, so that puppetserver can spawn new threads safely.
=> (PUP-9933) Make indirector settings threadsafe

lib/puppet/util/platform.rb
In unit/integration testing and at the repl (in instances when JRuby is
interpreting the Ruby code and dynamically loading its Java
dependencies) attempting to load 'openssl' in a FIPS environment raises
a Ruby LoadError.
In a packaged environment where all of our java dependencies and JRuby
itself have been compiled, requiring openssl causes a NameError when
JRuby's OpenSSL implementation actually attempts to reference the
non-existant BouncyCastle classes.
Rescue both LoadError and NameError to provide the same behavior
regardless of runtime environment.
=> (maint) Rescue NameError when checking JRuby OpenSSL

lib/puppet/type/exec.rb
Clarifies how an exec resource with a condition such as `onlyif` is considered successful even if the command was not actually executed.
=> (docs) clarify exec conditional success

lib/puppet/indirector.rb
This change makes the configure_routes method setxs indirection
:terminus_class and :cache_class using the global setter.
=> (PUP-9933) Configure routes globally

lib/puppet/module_tool/applications/installer.rb, lib/puppet/network/uri.rb, spec/unit/network/uri_spec.rb
This PR addresses [PUP-9787](https://tickets.puppetlabs.com/browse/PUP-9787) by masking password, if password was set in module_repository setting.
=> (PUP-9787) Mask password on Forge URL if given

lib/puppet/node/environment.rb
Environment.new and Environment.create used to do custom logic around
memoization and environment creation. However separate refactors led to
`.create` implementing the behavior that `.new` noramlly would have plus
some parameter munging that would normally be inside an `#initialize`
method (bdce6832a). And later `.new` was refactored to simply calling
`.create` (45f98c38).
This refactors `.new`, `.create`, and `#initialize` to a more idiomatic
initialization pattern while retaining the existing APIs.
=> (maint) Remove Node::Environment allocate/initialize construct

ext/project_data.yaml, lib/puppet/module_tool/tar/mini.rb, spec/unit/module_tool/tar/mini_spec.rb
We added an options hash to minitar so that we could turn off fsync and avoid redundancy when unpacking tars. This is adding the option.
=> (PUP-10013) Update minitar to 0.9

lib/puppet/pops/validation.rb
Previously, we used a clas variable to store valid severity states in
our default SeverityProducer. Ruby's class variables are strongly
discouraged and nothing currently updates these severities. In this case
using a constant would be more idiomatic.
=> (maint) Prefer constant to class variable in validation.rb

spec/unit/network/http/api/indirected_routes_spec.rb, spec/unit/type/file/source_spec.rb, spec/unit/type/schedule_spec.rb
Previously, some tests were passing a lambda or proc as the matcher to the
`expect` method. Since rspec-expecations 3.8.5 this is not allowed. Instead pass
it as an implicit block.
=> (maint) Call expect with a block

lib/puppet/module_tool/tar/mini.rb
Previously puppet failed to install modules if a version prior to minitar 0.9
was installed, such as with pe-r10k. Since puppet doesn't have a hard dependency
on minitar, we can't be sure which version is installed. Only include the fsync
option when running with minitar 0.9 or above.
=> (PUP-10013) Detect when running with an older minitar

Gemfile
We updated this in project_yaml.yaml but in 6.4 and newer branches we're also specifying this in `Gemfile` (thanks @glennsarti for pointing this out!)
=> (PUP-10013) Update minitar in Gemfile in 6.4 and newer

lib/puppet/type/notify.rb, spec/integration/type/notify_spec.rb
Previously, puppet redacted sensitive notify messages, but not if the sensitive
value was interpolated in another string. This commit redacts the message in
both cases, and adds tests.
=> (PUP-9295) Redact sensitive notify messages

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
Previously the `pip --version` command failed if the version string
wasn't the first line of output. This could occur when `pip --version`
generated a warning on stderr, since `execpipe` redirects stderr to
stdout.
Check if the regex matches before grabbing the first capture group.
=> (PUP-8986) Parse multiple lines of pip --version output

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
If the resolved pip path contains a space, then calls to `execute` will work,
but `execpipe` will not, because `execute` calls into `CreateProcess` which
handles a command with spaces, while `execpipe` calls `Kernel.open` which does
not.
If the path contains a space, wrap in quotes before calling `execpipe`. This
change is less risky then switching everything to `execute` due to the different
ways that they handle environment variables like `LC_ALL`.
Thanks to Sean Millichamp <sean@bruenor.org> for identifying why this
was failing on Windows.
=> (PUP-9647) Quote pip path when calling execpipe

.rubocop.yml, lib/puppet/functions.rb, lib/puppet/util/log.rb, lib/puppet/util/logging.rb
In Ruby 2, and JRuby 9k, `Kernel#caller` got a new optional argument that
controls how many frames to go back when constructing the call stack.
In most cases where we call `caller` we also throw away most of the
call stack. This has performance implications for every Ruby environment
and especially for JRuby.
Most of the time this doesn't matter because we are getting the call
stack for error reporting, however in at least one case this
information is used for non-fatal warnings.
=> (maint) Improve Kernel.caller() usage

lib/puppet/application/agent.rb
Documented --skip_tags option for the Puppet agent with wording from official documentation referenced in this ticket.
=> (PUP-10026) document skip_tags option for the puppet agent

lib/puppet/module/task.rb, lib/puppet/pops/loader/task_instantiator.rb, spec/unit/pops/loaders/module_loaders_spec.rb
This commit adds some error handling around loading task metadata where previously cryptic errors would be raised when the user specified metadata had the wrong shape.
=> (PUP-10095) Better error handling for loading task metadata

lib/puppet/provider/exec.rb, spec/unit/util/execution_spec.rb
Without this patch, the base Exec provider defaults the cwd parameter to
Puppet's working directory.  As a result, in the event that no cwd is
explicitly specified, Puppet attempts to change to the directory that is
already its working directory when it runs the Exec's command.  In most
cases that's merely wasteful, but under some circumstances it causes the
Exec to fail needlessly.
With the defaulting removed, the provider's
Puppet::Util::Execution.execute() call just does the right thing.
That is, it avoids attempting a working-directory change in the event
that no value was specified for the cwd parameter.
=> (PUP-5915) Stop Exec defaulting its cwd parameter

acceptance/tests/provider/package/dnfmodule_ensure_versionable.rb, lib/puppet/provider/package/dnfmodule.rb, lib/puppet/type/package.rb, spec/fixtures/unit/provider/package/dnfmodule/dnf-module-list-installed.txt, spec/unit/provider/package/dnfmodule_spec.rb
This commit introduces support for managing DNF/YUM modules through the `module` subcommand. Modules are groups of packages that represent an application, a language runtime, or any logical group.
Modules can be available in multiple streams, usually representing a major version of the software they include. Profiles are package subsets representing a specific use case of the module (these are handled by the `flavor` parameter of the package type).
A sample module installation using all applicable flags would be:
```puppet
package { 'postgresql':
ensure   => '9.6' # stream
flavor   => 'client' # profile
provider => 'dnfmodule'
}
```
Due to the significant difference between a package and a module, `dnfmodule` is an opt-in provider and should be explicitly specified in the manifest.
More …
=> (PUP-9978) Support for DNF modules

acceptance/tests/windows/enable_password_changes_special_users.rb
Windows has a password policy, where it prompts the
user based on password complexity, password length
and history. In our case, it is prompting since password
exceeds the limit of 14 characters. This is to enable
using the user accounts on Windows versions older
than Windows 2000, since they don't support long passwords.
Since we are using `net user /add` only in tests,
it is safe to use a shorter password for this test.
=> (PUP-10021) fix net user /add prompt in tests

lib/puppet/pops/loader/module_loaders.rb, spec/unit/pops/loaders/loaders_spec.rb
Previously in PUP-6964 [1] the system loader was modified to to be able to load
Puppet 3 API functions:
Note that https://github.com/puppetlabs/puppet/pull/7019/files#diff-83a8daf215ff39828e0e3758c2e5a866R34
has loadables of `[:func_4x, :func_3x, :datatype]`.
However when the system cache loader was introduced in PUP-9035 [2]the loadables
specified did not include the Puppet 3 API functions:
Note that https://github.com/puppetlabs/puppet/pull/6963/files#diff-83a8daf215ff39828e0e3758c2e5a866R30
has loadables of `[:func_4x, :datatype]`
The comment at https://github.com/puppetlabs/puppet/pull/6963/files#diff-83a8daf215ff39828e0e3758c2e5a866R22
says they should be the same but is clear they are not.
This commit updates the loadables for the cache system loader to include
`:func_3x` as per the …
=> (PUP-9509) Puppet 3 API functions should be loaded from cache

lib/puppet/util/http_proxy.rb, spec/unit/forge/forge_spec.rb, spec/unit/forge/repository_spec.rb, spec/unit/util/http_proxy_spec.rb
Backports PUP-9990 to 5.5.x
Previously puppet would attempt to connect via a proxy if the HTTP_PROXY
environment variable was set, but the destination server matched the
Puppet[:no_proxy] setting. The confusion occurred because ruby's Net::HTTP
automagically resolved proxy settings from the environment, after puppet had
already decided not to use one.
The disconnect is due to ruby 2.0 changing the default behavior of
Net::HTTP.new, which is called by Net::HTTP::Proxy[1]. If the third argument to
the initialize method (`p_addr`) is not specified, then it defaults to :ENV
causing ruby to lookup proxy configuration from the environment. In ruby 1.9 and
before, `p_addr` defaulted to nil.
Net::HTTP::Proxy is also marked as obsolete, so this commit switches to
Net::HTTP.new instead. If puppet …
=> (PUP-10112) Use Net::HTTP.new instead of Net::HTTP::Proxy

spec/unit/pops/loaders/loaders_spec.rb
Previously the unit tests for the cache loader only checked that a loadable was
specified.  However order is important.  This commit updates the unit test to
confirm that all loadables are specified in the correct order.
=> (PUP-9509) Update unit tests for cache loader

lib/puppet/parser/scope.rb, spec/unit/parser/scope_spec.rb
This commit adds an optional `include_undef` parameter to the `to_hash` method for the `Puppet::Parser::Scope::ParameterScope` class. When `include_undef` is true, variables that have been explicitly declared as `undef` will be included in the hash of variable/value pairs. This work enables passing variables from Bolt `plan` scope accross the `apply` boundry. (https://github.com/puppetlabs/bolt/blob/f5c7023ecf1fd937ca795e8168b0064b39af117a/lib/bolt/applicator.rb#L156-L157). See [Bolt issue 1288](puppetlabs/bolt#1288) for more details.
=> (PUP-10114) Optionally include undef vars in ParameterScope to_hash method

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
Without applying this page any service beging with a '-' (dash) cannot
be started by systemd. This is a problem because it's conventional in
systemd services to do so. This patch allows users to run commands
systemctl enable [service] and systemctl disable [service] by
appending a -- (em dash) between the command and service name. Tests
have been updated to verify corrected output.
=> (PUP-7218) systemd service provider missing double dash

acceptance/tests/provider/package/pip.rb, lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
Prior to this commit ...
The 'latest_with_new_pip' and 'latest_with_old_pip methods' (called by the
'latest' method) failed to execute `pip install` with the resource's
`install_options` attribute, potentially resulting in a lack of idempotency.
With this commit ...
Any 'install_options' are applied whenever 'install' is executed.
=> PUP-8949 use install_options with 'latest' methods

spec/unit/provider/exec_spec.rb
This excludes tests that cover  exec functionality
we don't expect to work on JRuby
=> (maint) Exclude tests on JRuby

lib/puppet/provider/service/daemontools.rb, lib/puppet/provider/service/runit.rb, spec/unit/provider/service/daemontools_spec.rb, spec/unit/provider/service/runit_spec.rb
When running on distributions that do not have a
default service provider puppet will try to
evaluate `runit` and set `defpath` default
before verifying that `runit` is suitable. Raising an
error when setting defpath results in a state that should
not be reached.
This commit removes the raise exception from defpath
and let puppet decide if the provide is suitable or not.
=> (PUP-10102) fix service crash

acceptance/tests/provider/package/pip.rb, lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
CentOS 8 does not come with the python package:
```
[root@rmql4g2dj6dsuwv ~]# yum install python
Last metadata expiration check: 0:12:38 ago on Fri 01 Nov 2019 11:37:30 AM UTC.
No match for argument: python
There are following alternatives for "python": python2, python36
Error: Unable to find a match
```
thus causing the pip test to fail.
On centos-7 the `python` package installs python2:
```
[root@ix0x69pe3wfm16j ~]# yum install python
........
Updating   : python-libs-2.7.5-86.el7.x86_64                                                                                                                      1/4
Updating   : python-2.7.5-86.el7.x86_64                                                                                                                           2/4
Cleanup    : …
```
=> (maint) fix pip tests on centos-8

lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
A user resource configured with `forcelocal` will still try to sync the comment with the external directory services. It does use `lusermod` to modify the local `/etc/passwd` to the comment specified in the user resource, but it compares the `in_sync` with the external directory
services, meaning that it always updates the comment on catalog compilation.
This commit queries the comment from the local `/etc/passwd` if the `forcelocal` parameter is set. It also modifies the `finduser` method to return a hash of parameter/value type, since returning numbered elements is more error-prone.
=> (PUP-9562) User resource should respect forcelocal for the comment parameter

.gemspec, lib/puppet/version.rb
This PR sets the version for the next agent release
=> (packaging) Bump to version '6.11.0' [no-promote]

ext/project_data.yaml
- Per the FFI CHANGELOG, Ruby 2.6 compatible Windows binaries were not
added until FFI 1.10.
See https://github.com/ffi/ffi/blob/master/CHANGELOG.md
- Relax Puppets dependency to set a minimum of 1.9.25 and a maximum
of 2.0.
1.9.21 was necessary to support Ruby 2.5, but newer versions are
preferred due to fixing CVE-2018-10000201
- Loosens restriction from c4833518958f2cfbbab8fa8b59309fac71f885aa
where FFI dependency was last set to < 1.10.
=> (PUP-9555) Relax FFI gem requirements for Ruby 2.6

.travis.yml, appveyor.yml, lib/puppet/indirector/request.rb, lib/puppet/pops/types/p_uri_type.rb, lib/puppet/type/file/source.rb, lib/puppet/util.rb, spec/unit/pops/loaders/loaders_spec.rb
* Run Travis & Appveyor specs on ruby 2.6
* Address behavior changes in 2.6
* `Pathname#read` now calls `File.read` instead of `IO.read`
* Syntax error message changed when `end` keyword is missing
* `URI#host` returns an empty string instead of `nil` for file URIs.
=> (PUP-9650) ruby 2.6

lib/puppet/defaults.rb, lib/puppet/util/http_proxy.rb, spec/unit/util/http_proxy_spec.rb
Previously, the `no_proxy` setting only supported domain exceptions using a
wildcard (*.example.com) or a dotted-domain (.example.com). However, curl and
ruby accept a dotted-domain and a domain suffix (example.com, ample.com), but
not wildcards.
This could lead to strange behavior if puppet executed ruby or curl during an
exec resource, and the `no_proxy` environment variable was specified as a domain
suffix -- puppet would still use the proxy, while ruby & curl would not.
This commit allows puppet to accept `no_proxy` environment variables or puppet
settings containing domain suffixes, while retaining support for wildcards and
dotted domains. As a result, it's no longer possible to force puppet to not use
a proxy for a specific host, but not any domains that happen to match that …
=> (PUP-10106) Don't require domain proxy exceptions to start with dot

lib/puppet/context/trusted_information.rb, spec/unit/context/trusted_information_spec.rb
rspec-puppet creates an instance of Puppet::Context::TrustedInformation
instead of using the `remote` class method[1]. To reduce compatibility issues
with rspec-puppet and any other users of trusted information, make the
`external` argument optional.
Also update docs as the setting was changed from terminus to command.
[1] https://github.com/rodjek/rspec-puppet/blob/a4749c804c820977c2f507133d01f56006b22f47/lib/rspec-puppet/support.rb#L407
=> (PUP-9994) Make external argument optional

lib/puppet/network/http/connection.rb, spec/unit/network/http/connection_spec.rb
Rather than create a new exception class when we catch connection
errors, we should raise the original exception. Previously, this rescue
block was modified to add additional contextual information to the
exceptions we were catching to give the user more information around the
context of failures. Rather than raising the original message, it would
create a new exception with the additional information.
This commit simply logs the error with Puppet with the additional
information, and raises the original caught exception. This saves us
from errors that stem from different error initializer expectations.
=> (PUP-10121) Simplify connection error handling

lib/puppet/http.rb, lib/puppet/http/client.rb, lib/puppet/http/errors.rb, lib/puppet/http/redirector.rb, lib/puppet/http/response.rb, lib/puppet/http/retry_after_handler.rb, lib/puppet/network/http/pool.rb, lib/puppet/network/http/site.rb, spec/unit/configurer_spec.rb, spec/unit/http/client_spec.rb, spec/unit/network/http/site_spec.rb
=> (PUP-10033) HTTP Client

lib/puppet/http.rb, lib/puppet/http/client.rb, lib/puppet/http/errors.rb, lib/puppet/http/resolver.rb, lib/puppet/http/resolver/settings.rb, lib/puppet/http/resolver/srv.rb, lib/puppet/http/service.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/session.rb, lib/puppet/network/resolver.rb, spec/unit/http/client_spec.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/service/ca_spec.rb, spec/unit/http/service_spec.rb, spec/unit/http/session_spec.rb
Adds a CA service to the http client:
```
client = Puppet::HTTP::Client.new
session = client.create_session
ca = session.route_to(:ca)
crl = ca.get_certificate_revocation_list(if_modified_since: Time.now)
```
The client will use SRV records (if enabled) or puppet settings to route to the CA service. Routing will only be performed once per session. The CA service provides methods for interacting with the puppetserver's CA REST API. The methods either return the entity (eg pem encoded crl), or raise one of the `Puppet::HTTP::HTTPError` exceptions.
=> (PUP-10037) Add CA service

lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/pops/puppet_stack.rb
Previously, we used `Kernel.eval` to add additional information to the
Ruby call stack. That information would show that the call had come from
a Puppet manifest. We did this to interleave Puppet "function calls"
with Ruby function calls. Then when creating error or warning messages
we would retrieve the entire Ruby call stack and strip out everything
from the call stack save for the Puppet manifest files.
This moves us to use a threadsafe variable to store Puppet stack
information bypassing the performance issues that come from interacting
with the Ruby call stack.
=> (maint) Do not use Ruby stacktrace for "Puppet" stack

lib/puppet.rb, lib/puppet/application/ssl.rb, lib/puppet/http.rb, lib/puppet/http/client.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/session.rb, lib/puppet/network/http.rb, lib/puppet/rest/errors.rb, lib/puppet/rest/response.rb, lib/puppet/rest/route.rb, lib/puppet/rest/routes.rb, lib/puppet/runtime.rb, lib/puppet/ssl/state_machine.rb, lib/puppet/util/http_proxy.rb, spec/unit/http/client_spec.rb, spec/unit/ssl/state_machine_spec.rb
Change the `puppet ssl` application and the ssl state machine to use the http client, and deprecate the `Puppet::Rest`.
Depends on PR https://github.com/puppetlabs/puppet/pull/7825
=> (PUP-10040) Use http client for cert related requests

lib/puppet/http/session.rb, spec/unit/http/session_spec.rb
Previously, if an agent couldn't connect to the CA to bootstrap its SSL certs,
it only printed "No more routes to ca" while the actual connection failure was
logged at :debug level. This caused the windows eventlog acceptance test to
fail, since "puppet agent -t" sets the log level to :info, preventing the
expected message from being logged.
This commit continues to log each individual connection failures at debug as is
done in Puppet::Configurer#find_functional_server and Puppet::Rest::Routes when
using SRV records, but if we exhaust all resolvers, then we log each exception
at error level, and raise the "no more routes" error as we did before:
C:\> puppet agent -t
...
Error: Failed to connect to https://127.0.0.1:8140/puppet-ca/v1: Failed to open TCP connection to 127.0.0.1:8140 …
=> (PUP-10040) Print resolution exceptions when routing fails

acceptance/tests/resource/service/puppet_mcollective_service_management.rb, ext/windows/service/daemon.rb
puppet-agent 5.5.x fails to start, because if ENV['RUBYLIB']
is not defined, then daemon.rb tries to append nil to a string.
This raises an exception "TypeError (no implicit conversion of nil into String)".
=> (PUP-10140) fix puppet service on windows

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
When running facter -p on windows, if there are custom facts or module
facts that require some additional files that that are not yet present
in $LOAD_PATH, it will cause an error.
This error is caused by the way base modules/vendor paths are generated.
When running facter -p, puppet needs to set $LOAD_PATH so that facter
will know where to check for module facts. When loading the module path,
puppet will call Facter.value of a non core fact, and this will start
the re-evaluation of all custom/plugin facts without setting the
$LOAD_PATH. This step fails if a fact requires some additional files not
yet in $LOAD_PATH.
Now the $LOAD_PATH will be set  without using Facter, getting it
directly from the system environment.
=> (PUP-10136) premature facts loading under facter -p

lib/puppet/http/resolver/srv.rb, lib/puppet/http/service.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/session.rb, spec/unit/http/service/ca_spec.rb, spec/unit/http/service_spec.rb, spec/unit/http/session_spec.rb
Previously, information needed to create the CA service was stored in a misnamed `Routes` map. The information was used to build the URL to the CA prior to creating the CA service.
This commit moves the `api`, `server_setting` and `server_port` information into the CA service itself, eliminating the need for the `Routes` map.
It also moves the CA service tests to test at a higher level via `client.create_session.route_to(:ca)`.
=> (maint) Refactor how services are created

lib/puppet/defaults.rb, lib/puppet/transaction.rb, spec/unit/transaction_spec.rb
Merge (n) resource dependency failures into (1) class failure.
When a class has a failed dependency, every individual resource in the class
generates a notice level message about the dependency failure,
and a warning level message about skipping the resource.
At large-code and/or large-node scale, one class dependency failure can create
an overwhelming number of messages ... obscuring the root cause and increasing
the use of system resources required to process and store the resulting reports.
With this commit (and 'merge_dependency_warnings' set to true) ...
All messages caused by a class dependency failure are coalesced into one message
associated with the class.
=> (PUP-10017) coalesce resource dependency failures into class failures

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
This commit restores the functionality of
https://tickets.puppetlabs.com/browse/PUP-3483
It was broken my the merge-up of the PR for
https://tickets.puppetlabs.com/browse/PUP-7218
Without this change
```
systemctl show -- some.service --property=NeedDaemonReload
```
shows *all* properties and the `.strip.split('=').last` doesn't work.
The option `--property=NeedDaemonReload` is not being treated as an
option, but a very obscurely named service.
The fix is trivial.  By moving the `--property=NeedDaemonReload` to be
before the `--`, it works again.
=> (PUP-10149) Fix regression in systemd daemon-reload

spec/unit/network/http/connection_spec.rb
Use stub_request in puppet 6.x instead of Net::HTTP, so we're not tied to a
specific http implementation. T
=> (maint) Prefer stub_request over any_instance_of(Net::HTTP)

lib/puppet/functions/camelcase.rb
It looks like this was copy & pasted from the `capitalize()` function
and this was left over.
=> (DOCS) Correct the name of a function in docs

lib/puppet/functions/find_file.rb
=> (DOCS) grammar fixes for find_file() function docs

lib/puppet/runtime.rb
This file use the Singleton pattern implemented by Ruby's Singleton class in the singleton module.  Require the singleton module before using the Singleton class.
Problem was spotted while updating the puppetserver ports on FreeBSD:
```
[...]
Caused by: org.jruby.exceptions.NameError: (NameError) uninitialized constant Puppet::Runtime::Singleton
at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3746)
at RUBY.<class:Runtime>(/usr/local/lib/ruby/site_ruby/2.6/puppet/runtime.rb:4)
[...]
```
Cc @joshcooper who authored this file recently.
=> Add missing require: singleton

spec/spec_helper.rb
Facter 2 will soon be updated to use the non-deprecated GCE metadata endpoint
see FACT-2102. Update puppet's webmock stub to accept both.
=> (maint) Update GCE metadata endpoint

lib/puppet/functions/find_template.rb, spec/unit/functions/find_template_spec.rb
This makes it easier users to render templates on the agent, meaning that
they can use secret values resolved by deferred functions directly with
e.g. Vault. That means that the master no longer needs keys to the kingdom.
=> (PUP-10139) Add find_template function

lib/puppet/pal/pal_impl.rb
The `Puppet::Pal.with_script_compiler` method sets the
`Puppet[:tasks]` setting to true for the duration of the block, but
never sets it back to its original state. This means that the mode of
operation the process is in will be globally changed depending on
whether this method has been called. The corresponding
`with_catalog_compiler` method has similar behavior in setting
`Puppet[:tasks]` to false, but it ensures that the setting is reset to
its previous value when the method returns. We now copy that behavior in
`with_script_compiler`.
=> (maint) Reset "tasks" setting after with_script_compiler

lib/puppet/ssl/ssl_provider.rb, spec/integration/http/client_spec.rb, spec/unit/ssl/ssl_provider_spec.rb
Add SSLProvider#create_system_context which returns an SSLContext configured to
trust the specified cacerts and any certs in OpenSSL's default verify path
location. This is necessary so that puppet can make HTTPS connections to servers
whose certs are not issued by puppet's PKI.
=> (PUP-10144) Add method for loading system ssl context

acceptance/tests/resource/file/diff_output_content_attribute.rb, lib/puppet/type/file/data_sync.rb, spec/unit/type/file/content_spec.rb
in case diff output contains invalid encoding, generic
`Binary files <A> and <B> differs` is logged instead
=> (PUP-10097) fix diff output for binary files

lib/puppet/provider/package/portage.rb, spec/unit/provider/package/portage_spec.rb
until now slot was expected to contain `:` which is not the case in current Linux Gentoo
=> (PUP-10124) fix slot for portage package provider

lib/puppet/util/windows/adsi.rb, spec/unit/util/windows/adsi_spec.rb
Behavior of the user resource goes wonky when an AD account exists with
the same name as the local user account you’re trying to manage on a
domain-joined Windows server.
This commit queries the WMI database for the computer's Domain Role. If
it's domain-joined, it will compare the found user's domain with the
computer name to confirm the account exists locally.
This issue is caused by the LookupAccountNameW function automatically
trying to resolve the name using domain controllers trusted by the local
system if the name cannot be resolved on the local system.
Still needs tests.
=> (PUP-10057) User resource on Windows confuses domain and local accounts

lib/puppet/functions/epp.rb, lib/puppet/functions/inline_epp.rb, lib/puppet/parser/functions/epp.rb, lib/puppet/parser/functions/inline_epp.rb, lib/puppet/type.rb
Changes to the docs site structure resulted in changed or removed
redirects for absolute URLs (ie. `/puppet/latest/...`) as well as
for URLs referring to the `references` subdirectory.
Update Markdown docs in comments and heredocs to use fully
qualified URLs (`https://puppet.com/docs/...`) and update their
targets to avoid relying on redirects that no longer exist.
=> (docs) Use fully qualified docs URLs

lib/puppet/provider/service/systemd.rb
Cumulus v4 is much the same as v3, it's based on Debian and also uses SystemD.  The only change necessary for it to work is ensuring the service provider uses SystemD
=> (PUP-10162) Add support for Cumulus v4.0.0

tasks/manpages.rake
Running `mkdir -p man/man{5,8}` makes `/bin/sh` (which is the default
shell for rake) create a single directory titled `man{5,8}`, since this
type of grouping is bash-specific.
The previous implementation might work on most modern systems where
`/bin/sh` is a symlink to `bash`, but to be safe we create the
directories individually.
=> (maint) Create man directories before manpage generation

lib/puppet/type/group.rb, lib/puppet/type/user.rb
To manage a local user/group resource on AIX, the `ia_load_module`
parameter needs to be set to `files`. This has the same effect as
`forcelocal` on Linux.
Since the `forcelocal` parameter is linked to the `libuser` feature
which is platform-specific, we cannot use it on AIX.
Extend the documentation on these flags to reflect this use case.
=> (PUP-7113) Document AIX local resource functionality

lib/puppet/http/client.rb, lib/puppet/http/resolver/server_list.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/session_spec.rb
This commit enables the ServerList resolver for the ca service and adds
tests to ensure a consistent flow when resolving the route to the
server.
=> (PUP-10157) Observe ServerList Resolver

lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/pops/puppet_stack.rb
Previously, we used `Kernel.eval` to add additional information to the
Ruby call stack. That information would show that the call had come from
a Puppet manifest. We did this to interleave Puppet "function calls"
with Ruby function calls. Then when creating error or warning messages
we would retrieve the entire Ruby call stack and strip out everything
from the call stack save for the Puppet manifest files.
This moves us to use a threadsafe variable to store Puppet stack
information bypassing the performance issues that come from interacting
with the Ruby call stack.
Conflicts:
- lib/puppet/pops/evaluator/runtime3_support.rb
- lib/puppet/pops/puppet_stack.rb
cherry-pick note:
The original threadsafe class is not available in this stream. This
may be merged up to Puppet 6.5.x but not later …
=> (PUP-10170) Do not use Ruby stacktrace for "Puppet" stack

acceptance/Rakefile, acceptance/config/git/options.rb
This uses git-based acceptance, skips setting up a master, and does not
run any tests tagged `server`. It also creates and munges a hosts file
for beaker to use. This removes any manual munging that was otherwise
needed when running acceptance tests with docker.
This commit also modifies the git testing to prevent the automation from
provisioning a server. This might be too big of a hammer for this, but
generally git-based acceptance tests should be light weight. The tests
should error if we ever run one that does require a master, but
generally this should be safe.
=> (maint) Add a rake task to run tests with docker

lib/puppet/network/http/base_pool.rb, spec/integration/http/client_spec.rb
If debugging is enabled, print TLS protocol and ciphersuites.
```
$ bx puppet agent -t
Debug: Creating new connection for https://crested-pursuer.delivery.puppetlabs.net:8140
Debug: Starting connection for https://crested-pursuer.delivery.puppetlabs.net:8140
Debug: Using TLSv1.2 with cipher DHE-RSA-AES128-SHA256
```
=> (maint) Print TLS connection info at debug level

.gemspec, .travis.yml
The last bundler update cause `gem update --system` to become interactive causing our travis builds to get stuck.
This PR attempts to provide a temporary workaround until upstream fixes it.
More info here: https://github.com/rubygems/rubygems/issues/3030
=> (maint) attempt to fix travis

lib/puppet/configurer.rb, lib/puppet/network/http/pool.rb, spec/unit/configurer_spec.rb
Previously during the environment convergence loop, we downloaded a resource catalog, updated the cached catalog as a side effect of the indirector's cache class, and converted the resource catalog into a RAL catalog. However, if our current environment did not match, then we switched to the new environment, and re-requested facts and a new catalog.
The process of serializing the catalog to the cache and converting the resource catalog to a RAL catalog causes puppet to load types and providers. This is unnecessary and can lead to environment isolation problems if a type or provider loads helper code (since the helper code is not reloaded).
This commit defers the RAL catalog transformation and cached catalog update until after we've converged the environment.
From …
=> (PUP-10160) Defer catalog transformation until after environment convergence

lib/puppet/configurer.rb, lib/puppet/network/http/pool.rb, spec/unit/configurer_spec.rb
* upstream/5.5.x:
(PUP-10160) Cached catalog takes precedence over options catalog
(PUP-10160) Emit info message after caching catalog
(PUP-10160) Convert catalog and update cache after convergence
(PUP-10160) Don't conflate cached and ral catalogs
(maint) Add environment convergence tests
(maint) Add tests for cached catalog behaviors
(maint) Use webmock to test server list
(maint) Account for stubbed Net::HTTP
(maint) Remove private method stubs
(maint) Remove instance_variable_get/set
(maint) Use let(:facts) instead of @facts
(maint) Don't stub Catalog#to_ral
(maint) Use let(:report) instead of @report
(maint) Fix bad expectation
(maint) Use let(:configurer) instead of @agent
(maint) Don't stub storage
(maint) Don't stub settings catalogs
(maint) Don't execute facter during failover …
=> (maint) Merge 5.5.x to 6.4.x

lib/puppet/x509/cert_provider.rb, spec/unit/x509/cert_provider_spec.rb
Previously the hostprivkey and hostcert settings were ignored, and paths to the
client cert and private key were resolved based on the cert/key directories and
certname setting.
This is acceptable for puppet agents, because puppetserver generally requires
that the client cert's common name (and therefore <name>.pem) match the node's
identity in the HTTP request (which is determined by certname).
But this is an issue for other parts of the puppet ecosystem, such as running
`puppet apply` and using a trusted client cert to connect to puppetdb.
To allow this, allow the hostprivkey and hostcert puppet settings to override
the default paths.
=> (PUP-10165) Allow hostprivkey and hostcert to override certname

.travis.yml
Rubygems release version 3.1.2 that contains the fix for --force: https://github.com/rubygems/rubygems/issues/3030
This PR removes the `yes` workaround in favor for --force
=> (maint) use --force for gem update

lib/puppet/http/service.rb, lib/puppet/http/service/ca.rb, spec/unit/http/client_spec.rb, spec/unit/http/service/ca_spec.rb
When `Puppet[:profile]` is true, we should always add
`'X-Puppet-Profiling' => 'true'` to all requests made by
`Puppet::HTTP::Client`. By default, this header should be omitted.
This header is used to tell the server that it may log
profiling data for that agent run. See
https://github.com/puppetlabs/puppet/blob/90f42e963a2f2147a6153977e7ef3cbacad5a0ef/docs/profiling.md
=> (PUP-10148) Include X-Puppet-Profiling Header

lib/puppet/pops/evaluator/runtime3_support.rb, spec/unit/pops/evaluator/evaluating_parser_spec.rb
Previously, `optionally_fail` in `Runtime3Support` would always create an
exception if it was not given one. However, said exception would only be
used if the issue reported was given a severity of `:error`. On certain
platforms creating exceptions are slow and some users have many warnings
within their manifests which can lead to slow compile times.
This patch checks with the `diagnostic_producer`'s `severity_producer` to
see if the given issue warrants a backtrace before creating an exception
to provide one. If no backtrace is needed (we do not currently report
backtraces for warnings) then we skip the creation of an exception.
A note about the tests. I did not find any specific tests around
`optionally_fail` though I added assertions to the `EvaluatorImpl` tests
where we already test …
=> (PUP-10213) Do not create unused exceptions in evaluation

lib/puppet/http/service/ca.rb
Prior to this commit, we had added the ability to add the profiling
header to http calls so that we can log profiling data for a given agent
run. However, we forgot to add that capacity everywhere in the ca
service. This commit fixes that omission.
=> (PUP-10148) Add X-Puppet-Profiling for all ca service calls

lib/puppet/http.rb, lib/puppet/http/service.rb, lib/puppet/http/service/report.rb, spec/unit/http/service/report_spec.rb
This commit adds in the Report HTTP service, which has the ability to
submit puppet run reports to the report server.
=> (PUP-10038) Add Report HTTP Service

lib/puppet/http/service/ca.rb, lib/puppet/http/service/report.rb, spec/unit/http/service/report_spec.rb
Add the profile headers when submitting the report. Also raise a protocol
error when talking to an older server that doesn't support JSON.
Since `add_puppet_headers` always returns a duplicate, it's safe to mutate that
when sending the if-modified-since header.
=> (PUP-10038) Send profile header to the report service

lib/puppet/util/windows/adsi.rb, spec/unit/util/windows/adsi_spec.rb
Allow case mismatches when comparing the resource domain with the computer name. The computer name *should* always be uppercase, while the domain might be lowercase in some cases. It looks like Windows prefers uppercase but does not enforce it.
=> (PUP-10219) Windows confuses domain/local accounts

lib/puppet/pops/model/pn_transformer.rb, lib/puppet/pops/serialization/json_path.rb, lib/puppet/pops/types/string_converter.rb, lib/puppet/pops/types/type_calculator.rb, lib/puppet/pops/types/type_formatter.rb
Several singletons use Puppet::Pops::Visitor which has some caching. To
be sure that this is safe, implement these using ThreadLocalSingleton.
Some of these used class variables referred to from inside the singleton
instances. This seems redundant and should be safe to make instance
variables.
=> (PUP-10163) Add thread safety for singletons using Visitor

lib/puppet/pops/types/p_object_type_extension.rb, spec/unit/pops/serialization/to_from_hr_spec.rb
This adds the `implementation_class` method to `PObjectTypeExtension` type,
which simply calls the base types `implementation_class` method. This
method is called as part of serializing `Puppet::Datatypes::Error`
objects, which currently errors if the method isn't defined.
=> (PUP-10221) Add implementation_class method to PObjectTypeExtension

acceptance/tests/catalog_with_binary_data.rb, acceptance/tests/language/binary_data_type.rb, acceptance/tests/language/objects_in_catalog.rb, acceptance/tests/lookup/lookup.rb, acceptance/tests/lookup/lookup_rich_values.rb, acceptance/tests/modules/list/with_environment.rb, acceptance/tests/reports/agent_sends_json_report_for_cached_catalog.rb, acceptance/tests/reports/corrective_change_via_puppet.rb, acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb, acceptance/tests/server_returns_pson_when_preferred_serialization_set.rb, acceptance/tests/ssl/autosign_command.rb, acceptance/tests/ssl/certificate_extensions.rb, acceptance/tests/ticket_13948_lib_dir_hook_should_be_called_on_initialization.rb, acceptance/tests/utf8/utf8-in-catalog.rb
Prior to this commit, some of the tests had code that required a master
host before we could specify the tags. The tags are important to define
first because they let us know when the test requires a provisioned
master. There are scenarios where we do not bother to provision a
puppetserver (aka master host). We need to be able to skip all tests
that require a server. These tests are generally tagged with 'server'.
However, if there is code evaluated before the tags are defined that
reference the master host, that test will fail. This commit fixes that.
This commit also adds 'server' tags if they're missing from a test.
=> (maint) Update tests to actually not require a master host when running

lib/puppet/defaults.rb, lib/puppet/ssl/certificate.rb, spec/unit/ssl/certificate_spec.rb
PUP-6258 introduced the new oid ppAuthCertExt, but this new OID was
never added to the custom_extensions method. This commit adds the
missing OID and ensures that it can be accessed.
=> (PUP-10234) Add ppAuthCertExt to custom_extensions

lib/puppet/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
* previously the parsing of install_options only
worked with a hash.  This fixes the code to also
work with a array of strings as it was originally
intended to.
* This bug has been present since 2014!
Current issue when using an array of strings 
```
package{'nginx':
ensure => latest,
install_options => ['--disable-repo=dev*'],
provider => yum,
}
```
* This fix may have unintended changes to users since they are used to the current implementation. However, if a user is not seeing the results with the current implementation prior to this patch they can work around the bug by using an array of hashes instead of an array of strings. 
Workaround with hashes:
```
package{'nginx':
ensure => latest,
install_options => [{'--disable-repo' =>'dev*'}],
provider => yum,
}
```
=> (PUP-10177) Fixes scan_options parser with yum package provider

acceptance/tests/resource/exec/should_run_command_in_cwd.rb
As this test doesn't require a master host to exist, we should remove
all references to master. We have the option to run tests without even
bothering to provision a master. When we do this, any reference to a
master in the tests will cause that test to fail. We want to be able to
run this test without provisioning a master host, so we need to remove
the reference to a master.
=> (maint) remove references to master where we don't need them

lib/puppet/http/service/file_server.rb, spec/unit/http/service/file_server_spec.rb
Previously if the caller specified a block, we yielded the entire response body
and then raised an exception due to the missing return.
Now, if the response is successful, stream the response body to the caller in
chunks, and return nil. Otherwise raise a Puppet::HTTP::ResponseError.
Also added some missing environment query parameters to file_metadatas (plural)
and file_content.
=> (PUP-10146) Stream file content response body

acceptance/tests/environment/negative/agent_run_should_fail_if_env_unreadable.rb, acceptance/tests/environment/negative/agent_run_should_fail_if_site_pp_unreadable.rb, acceptance/tests/modules/list/with_environment.rb, acceptance/tests/utf8/utf8-recursive-copy.rb, acceptance/tests/windows/enable_password_changes_special_users.rb
This commit adds 'audit' tags to untagged acceptance tests to ensure
that they are properly scoped when using Beaker's tagging facility to
filter tests.
[skip-ci]
=> (PUP-10236) Tag untagged acceptance tests

lib/puppet/transaction/resource_harness.rb
As defined on L296, this is a ResourceApplicationContext, not a ResourceApplicationContent. The typo makes it a lot harder than necessary to understand what's going on here.
=> (maint) Fix typo breaking reference chain

lib/puppet/pops/loader/puppet_plan_instantiator.rb, lib/puppet/pops/validation/checker4_0.rb, lib/puppet/pops/validation/tasks_checker.rb, spec/unit/pops/validator/validator_spec.rb
Previously, we explicitly forbade node definitions in plans entirely as
Bolt didn't know how to interpret them. This changes to allowing node
definitions in apply blocks so that they can be interpreted by Bolt.
When validating node definitions, we now check whether we're in an apply
block and fail if we aren't. Otherwise, we defer to the standard
validator. That validation will fail however, because definitions are
only allowed at the top level. For the intents and purposes of a plan,
an apply block is effectively a top-level construct, as it will be used
as the top-level input to a catalog compilation. Therefore, we now allow
node definitions to be defined directly within apply blocks (but not
nested any deeper than that).
The last piece of the puzzle is to change the plan instantiator …
=> (PUP-10223) Allow node definitions in apply blocks

lib/puppet/provider/group/groupadd.rb, lib/puppet/provider/user/useradd.rb, spec/unit/provider/group/groupadd_spec.rb, spec/unit/provider/user/useradd_spec.rb
This adds memoization to the `finduser` and `findgroup` methods to avoid reading the `/etc/passwd` or `/etc/group` file multiple times per resource. 
I need to write some specs for this.
=> (PUP-10117) Read passwd and group files once per resource

lib/puppet/configurer.rb, spec/integration/configurer_spec.rb
This commit updates the logic to resubmit facts to use the new HTTP
Client code.
The one test change required is that we now expect a
Puppet::HTTP::ResponseError rather than a Net::HTTPError when fact
submission fails.
=> (PUP-10232) Use HTTP client to resubmit facts

benchmarks/type_inference/site.pp.erb, lib/puppet/pops/evaluator/access_operator.rb, lib/puppet/pops/evaluator/evaluator_impl.rb, lib/puppet/pops/types/type_calculator.rb
Before this, the logic that evaluates method calls and the logic
that evaluates the [] operator would do a type inference and then check
if the type supports methods.
This was bad because it requires a full type inference that may be quite
expensive (for a large hash for example).
This is now fixed by adding a specific inference method in the
TypeCalculator that quickly returns nil for all types known to not have
methods, and infers the type for the rest.
Updates type inference benchmark. Chained function calls run nearly twice
as fast given the hash in the benchmark.
Supersedes #7797
=> (PUP-10113) Speed up method calls and calls to []

lib/puppet/face/facts.rb, spec/unit/face/facts_spec.rb
Previously, `puppet facts upload` only tried the first entry in `server_list`,
but never fell back to other entries in the list.
Now it uses the http client which attempts to connect to each entry in the
`server_list`, so that `puppet facts upload` behaves the same as `puppet
agent` for SRV, `server_list` and `server` resolution.
There's one minor change to the log message to remove the extra ':'
Faces will output to the console whatever the `when_invoked` block
returns, so return an explicit `nil` which is what `indirection.save`
did.
=> (PUP-8900) Use HTTP client to upload facts

acceptance/tests/resource/file/ticket_8740_should_not_enumerate_root_directory.rb, acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb, acceptance/tests/resource/user/should_modify_home.rb, acceptance/tests/resource/user/should_modify_uid.rb, lib/puppet/util/plist.rb, spec/unit/util/plist_spec.rb
Apple Property List (plist) XML data is always UTF-8. When executing commands such as `/usr/bin/dscl -plist . readall /Groups`, Puppet would consider the command output to be US-ASCII, which could ultimately break if the output contained non-ASCII characters. Until now this didn't seem to be an issue, but with the addition of macOS 10.15 (Catalina) this isn't the case anymore.
The `Puppet::Util::Plist.parse_plist` method can be called with either XML or binary data, and based on this we can force the encoding of the XML data to UTF-8.
With a non-existing user:
```sh-session
> puppet resource user testuser ensure=present --debug
...
Debug: Prefetching directoryservice resources for user
Debug: Executing: '/usr/bin/dscl -plist . readall /Users'
Debug: Executing: '/usr/bin/dscl -plist . …
```
=> (PUP-10241) Force UTF-8 encoding on XML plist data

lib/puppet/defaults.rb
Since disable_warnings is an array-based setting, join the values so the error
message describes what valid input looks like:
Cannot disable unrecognized warning types 'foo'. Valid values are 'deprecations, undefined_variables, undefined_resources'.
Previously it displayed a stringified array, which isn't a valid value for
that setting:
Cannot disable unrecognized warning types ["foo"]. Valid values are ["deprecations", "undefined_variables", "undefined_resources"].
=> (PUP-2820) Print meaningful disable_warnings error message

lib/puppet/application/resource.rb, spec/unit/application/resource_spec.rb
The `puppet resource <type>` command lists all instances from all suitable
providers. However, the output is ambiguous when a resource with the same name
but different providers is present, such as gem and rpm/apt packages.
Include the provider parameter in the output of `puppet resource` to avoid
ambiguity.
=> (PUP-3721) Include provider parameter in puppet resource output

lib/puppet/configurer.rb, lib/puppet/util/storage.rb
Puppet used to rely on sync, but that was removed awhile ago. Remove the
orphaned require statements in preparation for ruby 2.7, as sync is now an
external gem.
=> (maint) Delete sync requires

acceptance/tests/provider/package/dnfmodule_manages_flavors.rb, lib/puppet/provider/package/dnfmodule.rb, lib/puppet/provider/package/openbsd.rb, lib/puppet/type/package.rb, spec/unit/provider/package/dnfmodule_spec.rb, spec/unit/provider/package/openbsd_spec.rb, spec/unit/type/package_spec.rb
On platforms where we have the `flavor` parameter, we cannot change it once a package is installed. The only way to do it is to use `ensure => absent` on the package, then install the different flavor.
This behavior is achievable on both `dnfmodule` and `openbsd` package providers. To do this we change `flavor` to be a property instead of a parameter, so it gets tracked as part of the resource state.
To ensure we don't call flavor methods on unsupported providers, we confine the property to the newly added `supports_flavors` feature.
I manually tested this on an OpenBSD box, but I'll write some specs too.
=> (PUP-10171) Support changing package flavors 

lib/puppet/ssl/certificate_authority.rb, spec/unit/ssl/certificate_authority_spec.rb
Backport PUP-9064 as specs fail when running with openssl 1.1 due to
certificate verification now checking the purpose field.
The puppet cert, ca, etc subcommands have various methods for
determining if a certificate is valid. This is used to see which certs
have been signed, are still waiting to be signed, or have been revoked.
Historically, puppet set the purpose to PURPOSE_SSL_CLIENT on the
X509::Store used to verify certificates, but ruby+openssl 1.0 ignored
it. When using openssl 1.1, purpose is checked, which causes
CertificateAuthority#verify to raise an error when verifying the puppet
CA cert, since it doesn't have the 'SSL Client' purpose. This
corresponds to the 'id-kp-clientAuth' extended key usage extension[1].
However, puppet doesn't really need to care about the purpose when …
=> (maint) Backport ignore X509 purpose during cert verification

lib/puppet/test/test_helper.rb, spec/integration/indirector/facts/facter_spec.rb, spec/unit/application/apply_spec.rb, spec/unit/configurer/fact_handler_spec.rb, spec/unit/configurer_spec.rb, spec/unit/indirector/catalog/compiler_spec.rb, spec/unit/puppet_pal_2pec.rb
Previously we were running facter many times during specs due to facter being
the default facts terminus.
This commit changes the default terminus to :memory when running tests, and
saves an empty facts node so it's available to tests. We only run facter once
in the facts integration test, and there we opt-in by setting the terminus
to `:facter`.
This commit only addresses tests that use the indirector to access facter. It
doesn't change how code or tests call Facter.value(key) or Facter[:key]
directly. More work is needed to ensure those calls don't cause facter to run.
It's not necessary to clear termini or caches before/after tests as that's
already done in the spec_helper.
Also delete useless test.
On OSX with 16 workers, rake parallel:spec now runs 25% faster:
Before:
Finished in 1 …
=> (maint) Speed up rspec tests

lib/puppet/util/log/destinations.rb
The "file" log destination type matches any log destination that is an
absolute file path. It determines that by calling
Puppet::Util.absolute_path? on the log destination name. That method
creates a regex and checks whether the argument matches. If the argument
is not a string (for instance, when it is a Puppet::Transaction::Report
object) then the default Object#=~ implementation is typically invoked
and always returns nil. This is technically correct, as the non-string
object is not in fact an absolute path. Thus, the "file" destination
never actually matches non-strings.
In Ruby 2.7, the default Object#=~ method is deprecated and a warning is
issued whenever an object is used as a log destination. This commit
therefore changes the "file" log destination to first check whether its …
=> (PUP-10247) Only try to match strings in file log destination

acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb, lib/puppet/provider/user/directoryservice.rb, spec/unit/provider/user/directoryservice_spec.rb
Due to macOS 10.15 no longer allowing direct manipulation of binary
plists under `/var/db/dslocal/nodes/Default/users`, we cannot set or
change user passwords.
This commmit implements a workaround involving the `dsimport` utlilty,
which we can use to directly manipulate the user plists.
We also sleep for one more second before flushing the dscl cache,
since the cache takes longer to populate after using `dsimport`.
=> (PUP-10246) Use dsimport to set OS X user passwords on macOS 10.15 and higher

lib/puppet/http/service.rb, spec/unit/http/service/report_spec.rb, spec/unit/http/service_spec.rb
In various services, we allow arbitrary strings to be added to an http
request url. We need to ensure the urls we pass into an http request are
valid, so this commits adds percent encoding.
=> (PUP-10226) URL encode paths in http client

acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_home.rb, acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_uid.rb, lib/puppet/provider/user/directoryservice.rb
This commit makes the assumption that macOS versions >= 10.14 will not
allow changing the home directory or UID of an user once created (this
has been true for 10.14, 10.15, and will also be for future versions I
assume), so make the checks more lenient.
=> (maint) Adjust OS X versions on acceptance tests

lib/puppet/defaults.rb
This commit adds a feature flag (setting) for using versioned environment
directories, symlinked to the configured environment directory. This enables
the work for lockless deployments.
=> (PUP-10256) Add `versioned_environment_dirs` feature flag

lib/puppet/indirector/catalog/compiler.rb, spec/unit/indirector/catalog/compiler_spec.rb
Since PE 3,x, there is no concept of a "PE" Puppet Agent, and therefore
the 'pe_version' fact in 'puppetlabs-stdlib' is nil on platforms > PE 3.x.
Code that varies based upon FOSS vs PE platforms requires a consistent method
to determe whether the platform is FOSS or PE.
Calling a function like 'pe_compiling_server_version' in FOSS will generate an
error in FOSS, and the `is_function_available` function is deprecated,
The concept of a "PE" Puppet Server is valid.
With this commit, Puppet Server sets a 'peserverversion' key in the 'server_facts'
hash of server-side facts for direct inspection, and for use by a future version
of 'puppetlabs-stdlib' that can inspect this key in a best-practice function.
=> (PUP-9750) optionally add pe_serverversion to server_facts

lib/puppet/parser/ast/pops_bridge.rb, lib/puppet/pops/parser/evaluating_parser.rb
Avoid sharing an EvaluatingParser across threads in PopsBridge by using the thread-local singleton instance instead.
=> (PUP-10231) Use EvaluatingParser singleton in PopsBridge

lib/puppet/indirector/catalog/compiler.rb
Document the other set_server_facts in puppetserver,
to reduce the chance of them being out of sync.
=> (maint) document the 'other' set_server_facts

spec/unit/indirector/catalog/compiler_spec.rb
The newly added test fails on ruby 2.6, because Pathname#read now calls
File.read instead of IO.read, such our expectation is invoked for things
other than the pe_serverversion file. See also d116100af06.
=> (maint) Allow File.read calls

acceptance/tests/provider/package/dpkg_hold_true_package_is_latest.rb, acceptance/tests/provider/package/dpkg_hold_true_should_preserve_version.rb, lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/dpkg.rb, lib/puppet/provider/package/fink.rb, lib/puppet/provider/package/pkg.rb, lib/puppet/type/package.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/aptitude_spec.rb, spec/unit/provider/package/dpkg_spec.rb, spec/unit/provider/package/pkg_spec.rb
This commit adds `mark` property for package providers on
Debian(dpkg/apt/fink/aptitude) and Solaris(pgk) as
alternative of using "held" value for `ensure`.
Using "held" value for `ensure` works as before, but it shows
deprecation warning and will be removed in further release.
Allowed values for `mark` are "hold/none", default to "none".
Mark can be specified with or without `ensure`, if `ensure` is
missing it will default to "present".
Mark cannot be specified together with "purged", "absent" or "held"
values for `ensure`.
=> (PUP-1537) add mark property for package

lib/puppet/http/service/file_server.rb, lib/puppet/http/session.rb, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_fetch_if_not_on_the_local_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_not_update_if_content_on_disk_is_up-to-date.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_update_if_content_differs_on_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_mtime_is_older_on_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_no_header_specified.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_not_on_the_local_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_not_update_if_mtime_is_newer_on_disk.yml, spec/unit/http/service/file_server_spec.rb, spec/unit/http/session_spec.rb
The `Session.route_to` method takes an optional URL parameter. If given and a non-nil/empty host is specified, then always route to that host.
Changes the fileserver methods to require an absolute "joined" path such as "/plugins" and "/modules/<module>/path/to/file", and adds path validation.
Prunes stale HTTP request/responses from VCR recordings.
=> (PUP-10267) Support routing to the file server given a URL

lib/puppet/indirector/catalog/compiler.rb
We don't need a regex to validate (presumably) already validated data.
Just transparently pass the data to the server fact.
=> (maint) simplify reading /opt/puppetlabs/server/pe_version

acceptance/tests/resource/group/should_manage_members.rb, lib/puppet/provider/group/groupadd.rb, spec/unit/provider/group/groupadd_spec.rb
Apart from being able to operate on local users, `libuser` can also manage members of a group. We can make use of that to implement the `manages_members` feature in the `groupadd` provider.
After this change, `groupadd` will use `libuser` commands in 2 cases:
- when managing users with forcelocal set
- when changing the members of a group
=> (PUP-9465) Implement `manages_members` in the groupadd provider

lib/puppet/network/http/connection.rb, lib/puppet/network/http/pool.rb, spec/unit/network/http/connection_spec.rb, spec/unit/network/http/pool_spec.rb
To prevent thundering herds, puppetserver may return Retry-After and ask
the agent to sleep.
When this happens, this commit closes the connection prior to sleeping.
It also ensures that closed connections are not added back to the pool.
This reduces resource usage on puppetserver.
=> (PUP-10227) Close the HTTP connection

.travis.yml, spec/unit/node/facts_spec.rb
JRuby 9.2.0.0 has a bug in StringIO#binmode, and was fixed in 9.2.1.0. Move to
the same version that we're currently shipping in puppetserver.
=> (maint) Bump to JRuby 9.2.8.0 in Travis

.gitignore, lib/puppet/environments.rb, lib/puppet/file_system/memory_file.rb, lib/puppet/file_system/memory_impl.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/settings.rb, spec/unit/environments_spec.rb
This commit adds a `real_path` method that will follow symlinks in the given
directory, which is then used when getting the environment.conf and generating
metadata for a given environment. This enables us to have multiple code
dirs for a given environment, with the set `environmentpath` pointing to the
most recent version, which enables lockless deployments.
=> (PUP-10255) Follow symlinks in environment path

lib/puppet.rb
The puppetserver will begin generating new settings objects during
compilations; in order to keep the code DRY, it needs to be able
to tell initialization methods whether or not to load the global
context.
=> (PUP-10142) Add flag for global context initialization during settings configuration

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
This commit makes facter-ng activation available on all platforms.
It also removes `Facter` module before loading `facter-ng`
to ensure that Facter 2.x and its Utils are not used.
=> (PUP-10263) facter-ng available on all platforms

lib/puppet/network/http/connection.rb, spec/unit/network/http/connection_spec.rb, spec/unit/network/http/pool_spec.rb
Stub the "Net::HTTP#started?" method so finish happens as expected. Protect
against Net::HTTP#finish being called twice, and ensure the "Closing connection"
debug message is printed after the redirect, since Pool#close_connection will be
a noop.
=> (PUP-10227) Preserve expectation for http.finish

lib/puppet/defaults.rb, spec/unit/node_spec.rb
Previously our default value of strict_hostname_checking was false which
allowed matching dotted segments of a nodes certname (its CN in its
certificate) as well as the segments of its fqdn fact, or hostname +
domain fact.
This was for compatibility when fact based classification within a
site.pp was a more common pattern and node declarations were much less
powerful than they are now.
With the ability to use regular expressions in a node declaration the
auto segmenting is no longer needed and with the ability to use facts
directly, to use fact interpetation in hiera lookups, or create a custom
external node classifier the injecting of facts into the nodes "name" is
unneeded.
The desire is to remove the setting completely in Puppet 7, while
leaving it in 6 so those that depend on this …
=> (PUP-10238) Change default value of strict_hostname_checking to true

lib/puppet/http/client.rb, spec/unit/http/client_spec.rb
This is a continuation of work for PUP-10227.
To prevent thundering herds, puppetserver may return Retry-After and ask
the agent to sleep. This commit ensures the connection is closed prior
to sleeping.
=> (maint) Close the HTTP connection prior to sleeping

lib/puppet/network/http/pool.rb, spec/unit/network/http/pool_spec.rb
Previously when the last connection for a site was borrowed, the pool still
contained a map entry for the site to an empty array of connections. The
entry persists until the pool is closed or a new connection is attempted
for the same site.
Now delete the map entry when the last connection for a site is borrowed.
=> (PUP-10286) Delete the pool entry when the last connection is borrowed

lib/puppet.rb, lib/puppet/configurer/plugin_handler.rb, lib/puppet/http.rb, lib/puppet/http/client.rb, lib/puppet/http/resolver/server_list.rb, lib/puppet/http/resolver/settings.rb, lib/puppet/http/resolver/srv.rb, lib/puppet/http/response.rb, lib/puppet/http/service.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/service/compiler.rb, lib/puppet/http/service/file_server.rb, lib/puppet/http/service/report.rb, lib/puppet/http/session.rb, lib/puppet/runtime.rb, lib/puppet/test/test_helper.rb, spec/integration/faces/plugin_spec.rb, spec/unit/http/response_spec.rb, spec/unit/http/service/ca_spec.rb, spec/unit/http/service_spec.rb
Process each response collecting per-site server versions. If server version
is >= 5 then JSON is supported. If version is >= 5.3.4, then the locales mount
is supported.
Because file metadata and content requests don't use the httpclient yet, we
have to lookup the server version in both the context and session.
The plugin integration test is unrealistic because it sets the metadata
and content termini to memory, so we can't determine what version the puppet
server is. So push a version onto the context during the test.
=> (PUP-10147) Keep track of per-site versions in the session

spec/unit/network/http/pool_spec.rb
Due to a semantic conflict between 5727d31e08 and 762446ad19, if the last
cached connection for a site is borrowed, and later closed, then sessions for
that site will be nil instead of an empty array.
=> (PUP-10286) Expect nil session when connection is closed

lib/puppet/configurer/plugin_handler.rb, lib/puppet/http/service/report.rb, lib/puppet/http/session.rb, spec/unit/configurer/plugin_handler_spec.rb, spec/unit/face/plugin_spec.rb, spec/unit/http/session_spec.rb
Previously, if the agent run failed to connect to the compiler service, then it
would exit without falling back to the cached catalog.
This occurred because we only store `server_agent_version` in the context for
successful REST requests. If the "plugins" and "pluginfacts" mounts fail to
connect, then `Session#route_to` triggered the resolution logic, and that would
raise after exhausting the various resolvers.
Now we check if the compiler service has been resolved without triggered the
resolution code. If we haven't connected to the compiler service successfully at
some point earlier in the run, then preserve the original 6.x behavior of
skipping the "locales" mount.
Ideally, pluginsync would abort if any part of it failed, but that is a larger
issue, see PUP-1763.
=> (PUP-10147) Don't resolve the compiler service for the locales mount

lib/puppet/type/file/source.rb, spec/unit/type/file/source_spec.rb
By default, requests to "puppet" URLs are routed to the `rest` file_metadata and
file_content termini. However, if the host and port are unspecified, such as
"puppet:///modules/mod/file", then we route metadata and content requests based
on the `Puppet[:default_file_terminus]` setting[1]. When running `puppet apply`,
the setting is set to `file_server`, so that metadata and content are handled
by in the in-process file server.
The in-process file server resolves the path portion of the URL
"/modules/mod/file" and returns a `Metadata` object taking into consideration
the environment, whether to follow or manage links, checksum, etc.
Prior to this commit, when configured to use the in-process file server, puppet
retrieved file content using the indirector for all sources (absolute path or …
=> (PUP-8338) Stream file content when using puppet apply

acceptance/tests/resource/user/utf8_user_comments.rb, acceptance/tests/utf8/utf8-in-function-args.rb
This commit reduces the audit risk level of UTF-8 acceptance tests from
"audit:high" to "audit:medium".
=> (PUP-10309) Reduce UTF-8 acceptance risk

spec/unit/indirector/resource/ral_spec.rb, spec/unit/settings/autosign_setting_spec.rb, spec/unit/transaction_spec.rb, spec/unit/type/file/ensure_spec.rb, spec/unit/util/at_fork_spec.rb
Previously, puppet tests could generate warnings like
warning: already initialized constant CREATORS
due to puppet types being loaded twice. This happened if a spec required the
type directly and it was later loaded by the autoloader. This is possible
because the autoloader does not consult $LOADED_FEATURES before checking to see
if a file should be loaded.
Updates tests to lookup a type on-demand using `Puppet::Type.type(:name)`.
There are still some warnings due to faces.
=> (maint) Remove some constant redefinition warnings

lib/puppet/defaults.rb, lib/puppet/http/service.rb, lib/puppet/settings.rb, lib/puppet/settings/http_extra_headers_setting.rb, spec/unit/http/service/ca_spec.rb, spec/unit/http/service/compiler_spec.rb, spec/unit/http/service/file_server_spec.rb, spec/unit/http/service/report_spec.rb, spec/unit/http/service_spec.rb, spec/unit/settings/http_extra_headers_spec.rb
When we submit a request to the server, we now have the ability to add
in additional arbitrary headers. This should be isolated only to
requests made to a puppetserver, and these headers should not be
included in a request to an arbitrary external host.
These headers can be set with the `:http_extra_headers` setting in
Puppet. As illustrated in the various tests, this setting can be defined
in the following four forms:
- string:
`'header1:value,header2:value'`
- array:
`['header1:value', 'header2:value']`
- array of arrays:
`[['header1', 'value'], ['header2', 'value']]`
- hash:
`{'header1' => 'value', 'header2' => 'value'}`.
This commit also updates tests for the different services. It bundles
the test for the puppet profile header with the test for these custom
headers. These are both …
=> (PUP-9566) Include user-specified headers in http requests

lib/puppet/application/describe.rb, spec/unit/application/describe_spec.rb
Previously if the description for a type was missing a dot, then `puppet
describe --list` would print `.. no documentation ..` for that type. Now print
as much as the description as will fit, stopping at the end of the string or
the first dot, whichever comes first.
=> (PUP-2641) Try harder to print type's description

lib/puppet/application/device.rb, lib/puppet/configurer.rb, lib/puppet/face/plugin.rb, lib/puppet/http/client.rb, lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
Previously, requests based on `Puppet::Network::HttpPool.http_instance` and the
http client used two different pools, so it was possible for connections to not
be reused when they could be.
This commit pushes the http client's pool onto the context for cases where we
explicitly want to use persistent connections.
----
When running the ssl state machine, close the pool before sleeping so that we
don't keep connections open on the server. It also avoids trying to reuse a
connection that the remote side closed due to an idle timeout. This is similar
to the change made in 8639f0c5176b6bf65c0b9b18803f20708f7bfe28 for PUP-10227.
=> (PUP-10288) Close http pool before sleeping

spec/unit/indirector/catalog/rest_spec.rb, spec/unit/indirector/facts/rest_spec.rb, spec/unit/indirector/file_content/rest_spec.rb, spec/unit/indirector/file_metadata/rest_spec.rb, spec/unit/indirector/node/rest_spec.rb, spec/unit/indirector/report/rest_spec.rb, spec/unit/indirector/status/rest_spec.rb, spec/unit/type/file/source_spec.rb
Adds tests for rest termini. Use webmock instead of manually stubbing Net::HTTP.
=> (PUP-10260) Add rest terminus tests

lib/puppet/http/service.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/service/compiler.rb, lib/puppet/http/service/file_server.rb, lib/puppet/http/service/report.rb, spec/unit/http/service/compiler_spec.rb, spec/unit/http/service/file_server_spec.rb
Add service methods for getting facts, status, static file content.
Rename get_catalog to post_catalog
Simplify response handling.
Blocked on https://github.com/puppetlabs/puppet/pull/8006
=> (PUP-10260) Add http service methods

lib/puppet/configurer.rb, lib/puppet/http/service/report.rb, lib/puppet/indirector/catalog/rest.rb, lib/puppet/indirector/facts/rest.rb, lib/puppet/indirector/file_content/rest.rb, lib/puppet/indirector/file_metadata/rest.rb, lib/puppet/indirector/node/rest.rb, lib/puppet/indirector/report/rest.rb, lib/puppet/indirector/rest.rb, lib/puppet/indirector/status/rest.rb, lib/puppet/type/file/source.rb, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_fetch_if_not_on_the_local_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_not_update_if_content_on_disk_is_up-to-date.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_md5/should_update_if_content_differs_on_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_mtime_is_older_on_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_no_header_specified.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_fetch_if_not_on_the_local_disk.yml, spec/fixtures/vcr/cassettes/Puppet_Type_File/when_sourcing/from_http/using_mtime/should_not_update_if_mtime_is_newer_on_disk.yml, spec/unit/configurer_spec.rb, spec/unit/http/service/report_spec.rb, spec/unit/indirector/catalog/rest_spec.rb, spec/unit/indirector/facts/rest_spec.rb, spec/unit/indirector/file_content/rest_spec.rb, spec/unit/indirector/file_metadata/rest_spec.rb, spec/unit/indirector/node/rest_spec.rb, spec/unit/indirector/report/rest_spec.rb, spec/unit/indirector/status/rest_spec.rb
Modify the various rest termini to use the http client to make rest requests instead of relying on the base `Puppet::Indirector::REST` terminus. This mostly decouples the indirector from making http requests.
For now, we continue to use the base rest terminus when running in puppetserver.
Blocked on https://github.com/puppetlabs/puppet/pull/8007
=> (PUP-10260) Use http client for rest requests

lib/puppet/http/client.rb, lib/puppet/network/http/base_pool.rb, lib/puppet/network/http/pool.rb, spec/unit/network/http/pool_spec.rb
Trying to start a non-ssl connection in debug mode would fail trying to call a non-existent method `TCPSocket#ssl_version`.
=> (PUP-10314) Skip ssl debug for non-ssl connections

lib/puppet/http/client.rb, spec/integration/http/client_spec.rb, spec/integration/network/http_pool_spec.rb
Previously, if puppet made an HTTP(S) connection using the new HTTP client, and the server responded that it wanted to keep the connection alive, but decided later to close it, such as when puppetserver restarts, then the HTTP client would receive an EOFError as soon as it tried to reuse the connection.
The issue was due to Puppet::HTTP::Client making a non-local return from the block passed to Net::HTTP#request, which caused the Net::HTTP#end_transport method to be skipped, which resulted in the last_communicated instance variable never being set. The next time a request was made, the Net::HTTP connection thought it was "newly connected", so it skipped the logic to check if it had exceeded the keepalive timeout or if the remote side closed the connection[1].
The legacy Connection class …
=> (PUP-10347) Reconnect when using a cached connection

lib/puppet/provider/group/groupadd.rb, spec/unit/provider/group/groupadd_spec.rb
Group parameter `members` was validated by checking if each member user
exists before the manifest is applied. This will make a manifest containing user creation and group members update with the new user to fail.
By this change there is no parameter validation and the check of user existance
is done right before group modify command execution.
This is somehow consistent with other providers supporting `members` parameter
(aix/windows) for which the group change command fails if user is not existing.
=> (PUP-10320) update group membership user check

lib/puppet/configurer.rb, lib/puppet/http/resolver/server_list.rb, spec/unit/http/resolver_spec.rb
Blocked on https://github.com/puppetlabs/puppet/pull/8010
If server_list is specified, then use the http client to route to the `puppet`
service and store the resulting server and port in the context so that
Puppet::Util::Connection.determine_{server,port} still return the last
resolved server/port.
If we failed to connect to an entry in the server list, then we tried to
access a variable that didn't exist while logging the debug message, which
masked why the server wasn't available.
=> (PUP-10315) Use http client to process the server list

.gemspec, acceptance/tests/aix/aix_package_provider.rb
Because a resource used in acceptance testing was moved to different
location and http redirect was set in place, we need to update
`curl` call to include `-L` argument to follow http redirects.
Also removed deprecated `rubyforge_project` to make spec tests pass
=> (maint) curl should follow redirect when downloading

lib/puppet/http/client.rb, lib/puppet/http/service.rb, lib/puppet/type/file/source.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/service_spec.rb, spec/unit/http/session_spec.rb, spec/unit/type/file/source_spec.rb
Previously the agent did not accept rich data in the catalog because the
service cached the mime types from the previous node request.
Don't cache mime types in the service since they can be different for each model.
---
Retrieving static catalogs was broken because of a variable name mismatch.
---
Resolving fileserver and report services using server_list was broken because the server list resolver was only used for the ca and report services. Instead use the server_list resolver for all services, and exclude ones that have been explicitly configured in puppet.conf or the command line.
=> (PUP-10359) Resolve problems uncovered when running 'server' acceptance tests

lib/puppet/type/file/source.rb
In the file resource, attribute source, for the local file to be replaced, the `Last-Modified` header needs to be greater than modified time of local file, unlike the `Content-MD5` header that only needs to be different from local file's MD5.
=> (docs) Explain how Last-Modified header is used

lib/puppet/forge/repository.rb, lib/puppet/http/client.rb, lib/puppet/http/resolver/server_list.rb, lib/puppet/http/service.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/service/compiler.rb, lib/puppet/http/service/report.rb, spec/integration/http/client_spec.rb, spec/unit/http/client_spec.rb, spec/unit/http/service_spec.rb
This commit removes keyword arguments in favor of a generic options
hash. Though keyword arguments are cleaner, we decided to go with the
options hash to give us more flexibility moving forward. As we add new
options, like report compression, we need to be able to do so without
changing the API. If the new option is there, we use it, otherwise, we
behave like we previously did. This makes everything a bit easier and
eliminates the need to have puppetserver enforce hard dependencies on
puppet versions because of API changes.
=> (PUP-10353) Replace keyword arguments to generic options hash

lib/puppet/http/client.rb, lib/puppet/http/resolver/server_list.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/session_spec.rb
Previously, puppet walked the server_list once per service: puppet, fileserver,
and report, assuming the corresponding settings were not overridden,
e.g. report_server.
Now walk the server_list once per session. So if we resolve server_list for the
`puppet` service, then use the same for other services.
Since the server_list resolver is now stateful, create new resolver instances
for each session.
=> (PUP-10363) Process server list once per session

lib/puppet/util/package/version/range.rb, lib/puppet/util/package/version/range/gt.rb, lib/puppet/util/package/version/range/gt_eq.rb, lib/puppet/util/package/version/range/lt.rb, lib/puppet/util/package/version/range/lt_eq.rb, lib/puppet/util/package/version/range/min_max.rb, lib/puppet/util/package/version/range/simple.rb, spec/unit/util/package/version/range_spec.rb
This class is meant to be generic and to be used with any package version
In order to instantiate a Version::Range, you need to provide:
- a version_range string
- a version class implementing parse method and comparison operators
=> (PUP-10357) Basic implementation of Version::Range

lib/puppet/http/resolver/server_list.rb, spec/unit/http/resolver_spec.rb
The server_list resolver cached the service whose host and port it first
connected to, such as Puppet::HTTP::Service::Compiler. However, the next
request for a different service, would return the cached service, which wasn't
what the caller expected.
Instead cache the URL that we successfully connected to, and use that to
create the service of the correct type.
=> (PUP-10363) Cache the server list url not the service

lib/puppet.rb, lib/puppet/ssl/host.rb, spec/integration/network/http_pool_spec.rb, spec/unit/ssl/host_spec.rb
Allow the deprecation warning to be suppressed as the Host object is
still used when connections are made via `HttpPool.http_instance`. Calls
to `Puppet::SSL::Host.new` or `.localhost` will generate the deprecation
warning.
=> (PUP-10355) Don't emit a deprecation warning when using http_instance

lib/puppet/provider/package/gem.rb, lib/puppet/type/package.rb
Document and add a `version_ranges` feature to the package resource, which should be activated in providers that can ensure a valid version range.
Add the feature to the `gem` provider since the current implementation can handle version ranges.
=> (maint) Add version ranges feature for packages

lib/puppet/type/file/source.rb, spec/fixtures/ssl/unknown-127.0.0.1-key.pem, spec/fixtures/ssl/unknown-127.0.0.1.pem, spec/fixtures/ssl/unknown-ca-key.pem, spec/fixtures/ssl/unknown-ca.pem, spec/integration/application/agent_spec.rb, spec/lib/puppet/test_ca.rb, spec/lib/puppet_spec/https.rb, tasks/generate_cert_fixtures.rake
Commit 11eee4e886d3a67b1973610727df17306607f164 changed puppet to use the http
client to retrieve file content from https sources. In the process, we were
using the default SSLContext, whose X509 store only trusts the puppet PKI, so
connections to 3rd party HTTPS servers failed.
Pass `include_system_store` so that we use the system SSLContext.
Add an integration test to verify an agent can download file content from an
HTTPS server whose CA cert is not the puppet CA and is in the system CA bundle.
Also verify the download fails if the CA cert is not in the system CA bundle.
=> (PUP-10365) Fix https file source regression

lib/puppet/ssl/oids.rb, spec/unit/ssl/oids_spec.rb
In Puppet-as-a-Service use cases it is common for individual nodes to be owned by various different tenant, or customer, teams. None of the registered ppRegCertExt OIDs we currently provide cleanly allow generic specification of an owner in this context.
Provide a new OID, pp_owner, which generically fits this use case.
=> (PUP-10364) Add pp_owner ppRegCertExt OID

lib/puppet/type/user.rb, spec/unit/application/device_spec.rb, spec/unit/type/user_spec.rb
The user type has a long-standing custom retrieve() method which
returns values not in keeping with the standard retrieve() from
Puppet::Type.retrieve(). This patch removes the custom method
and adjusts the tests dependent on the particular behavior from
it.
=> (PUP-9943) Remove user type's custom retrieve()

lib/puppet/type/file/source.rb, spec/integration/application/apply_spec.rb
This commit fixes a regression in 6.14.0 that prevented puppet apply from
sourcing a recursive directory.
`Metadata#path` is the absolute path from which metadata is collected. For files
and non-recursive directories, it is the same as `Metadata#full_path`.
However, for recursive directories, `path` and `full_path` are different for all
children of the directory. The `path` is always that of the base directory where
recursion started, while `full_path` is the absolute path of the subdirectory or
file within the base.
=> (PUP-10367) Source files using full_path

lib/puppet/provider/selmodule/semodule.rb, spec/unit/provider/selmodule_spec.rb
Add method to base class to statically load results of
"semodule --list" command. Store output parsed into hash with keys
being module name and value being module version. Add prefetch method
to initially populate hash.
This change results in a substantial performance increase when checking
current resource state, on the order of 50% or more.
=> (MODULES-7319) Call "semodule --list" only once.

lib/puppet/provider/package/apt.rb, spec/unit/provider/package/apt_spec.rb
downgrade warning to debug messages, as they are not warnings for
our users
also, fixed one code review remark that got somehow overlooked
=> (maint) unify log messages with other providers

lib/puppet/provider/package/puppet_gem.rb, spec/unit/provider/package/puppet_gem_spec.rb
Without this patch after a gem is uninstalled from puppet's ruby
environment using the `puppet_gem` `package` provider other actions in
an agent's run fail.  For instance, modifying a file fails whilst trying
to back it up.
eg.
```
Error: Could not back up /some/file: pid: 21277 nil spec! included in [#<Gem::StubSpecifi...
--- SNIP (massive array ommitted) ---
]
/opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/specification.rb:743:in `_all'
/opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/specification.rb:1153:in `latest_specs'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/rubygems.rb:44:in `directories'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:142:in `gem_directories'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:172:in …
```
=> (PUP-10319) Invalidate rubygems cache after uninstalling puppet_gem package

lib/puppet/http.rb, lib/puppet/http/client.rb, lib/puppet/http/external_client.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/service/compiler.rb, lib/puppet/http/service/report.rb, lib/puppet/network/http_pool.rb, spec/unit/http/client_spec.rb, spec/unit/http/external_client_spec.rb
Adds Puppet::HTTP::ExternalClient. It implements a subset of the new HTTP API and delegates to the external `http_client_class`, if it's been overridden (via puppetserver).
Moves `content-type` from an option to the header.
DRY query parameter encoding.
=> (PUP-10324) Adapt HTTP API to puppetserver's external implementation

acceptance/tests/provider/package/pip.rb, lib/puppet/provider/package/pip.rb, lib/puppet/util/package/version/pip.rb, spec/unit/util/package/version/pip_spec.rb
Add support of `>`, `>=`, `<`,` <=`, `>=A <=B` ranges for package version specified in the :ensure manifest field. This will install a version that satisfies the provided range. The package version must respect pip's package versioning format (https://www.python.org/dev/peps/pep-0440/).
=> (PUP-10296) Add version range support to pip package provider

lib/puppet/reports/http.rb, spec/integration/application/agent_spec.rb, spec/integration/application/apply_spec.rb, spec/integration/application/plugin_spec.rb, spec/integration/http/client_spec.rb, spec/integration/module_tool/forge_spec.rb, spec/lib/puppet_spec/https.rb, spec/shared_contexts/https.rb, spec/unit/reports/http_spec.rb
Blocked on https://github.com/puppetlabs/puppet/pull/8051
Update the "http" report processor to send reports using the http client. The normal client is used when running `puppet apply`. When running in puppetserver, the external http client is used, which delegates to puppetserver.
Adds an integration test to verify `puppet apply` submits a report to an HTTPS URL whose server cert is issued by the puppet CA.
Adds an "https client" shared context to simplify test setup.
=> (PUP-10316) Update "http" report processor to use the http client

lib/puppet/defaults.rb, lib/puppet/reports/http.rb, spec/integration/application/apply_spec.rb
Blocked on https://github.com/puppetlabs/puppet/pull/8054
Adds a `Puppet[:report_include_system_store]` setting that defaults to false. If
set to true, the "http" report processor will trust the system certificate store
when submitting reports to an HTTPS report server. If false, then the processor
only trusts the puppet CA.
When installed from puppet-agent packages the system store is installed in
`/opt/puppetlabs/puppet/ssl/cert*` or on Windows
`C:\Program Files\Puppet Labs\Puppet\puppet\ssl\cert*`.
Note this change only affects the `http` report processor when running `puppet
apply`. A separate change is needed in puppetserver when the "http" processor
runs in puppetserver.
=> (PUP-7737) Allow http report processor to trust the system CA store

lib/puppet/provider/service/systemd.rb
systemd service provider should be default for newer Ubuntu
versions: 18.10, 19.04, 19.10, 20.04
=> (maint) default to systemd also on Ubuntu 20.04

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
When we enable facterng feature flag `puppet config set facterng true` and run `puppet facts --debug` log messages use Facter 4 logger instead of Puppet logger
Facter 4 logger output format is
```
[<date_time> ] <log-level> <class-name> - <log-message>
```
Puppet debug logs fro facter
```
Debug: Facter: <log-message>{code}
```
When staring puppet, `setup_facter_logging!` method from `module Puppet::Util::Logging` is called before feature switches are evaluated. The `setup_facter_logging!` tells Facter to use the Puppet logger in order to log debug messages. If the `facterng` feature switch if enables, we load facter-ng (Facter 4), but we need to `setup_facter_logging!` again in order to send the Puppet logger to facter-ng.
=> (PUP-10322) Set puppet logger in facter-ng.

acceptance/tests/provider/package/dnfmodule_enable_only.rb, lib/puppet/provider/package/dnfmodule.rb, lib/puppet/type/package.rb, spec/fixtures/unit/provider/package/dnfmodule/dnf-module-list-enabled.txt, spec/unit/provider/package/dnfmodule_spec.rb
Add an optional `enable_only` parameter to the package type.
If set to `true` on a `dnfmodule` resource, it will cause the module
to be enabled instead of installed. The flag cannot be set together
with the `flavor` property, since they conflict.
DNF modules that have no default profile (and cannot be installed)
will be enabled by default, so there is no need to add `enable_only`.
To enable a module that has a default profile, `enabled_only` has to
be set.
=> (PUP-10235) Support enabling DNF modules

lib/puppet/provider/group/windows_adsi.rb, lib/puppet/util/windows/adsi.rb, lib/puppet/util/windows/sid.rb, spec/integration/util/windows/adsi_spec.rb, spec/unit/provider/group/windows_adsi_spec.rb, spec/unit/provider/user/windows_adsi_spec.rb, spec/unit/util/windows/adsi_spec.rb, spec/unit/util/windows/sid_spec.rb
After a domain user that is member of a local group is removed,
puppet cannot manage respective local group anymore
In this commit methods `name_sid_hash` and `name_to_principal` where
extended to allow option to handle unresolved SIDs. Current members
handling was changed to allow unresolved SIDs.
`unresolved_principal` method was also updated to not add
' (unresolvable)' to a Principal as this will whill change
'S-1-2-3' to 'S-1-2-3 (unresolvable)' and will make
it dificult to transform back.
=> (PUP-10303) unresolvable domain accounts handling

acceptance/tests/provider/package/gem.rb, lib/puppet/provider/package/gem.rb, lib/puppet/util/package/version/gem.rb, lib/puppet/util/package/version/range/min_max.rb
Add support for range intersection (min,max such as: `>=A <=B`) specified in the :ensure manifest field. This will install a version that satisfies the provided range.
=> (PUP-10295) Add range intersection support to gem package provider

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
Removed expliciti call to Kernel.require due to the fact that the require method is monkey patched by Rubygems, and by default Kernel.require does not search for gems and raises LoadError
=> (PUP-10322) Update facterng feature flag not to use Kernel.require

lib/puppet/provider/package/pkgng.rb, spec/fixtures/unit/provider/package/pkgng/pkg.version, spec/unit/provider/package/pkgng_spec.rb
This is a fix for https://tickets.puppetlabs.com/browse/PUP-10382
=> (PUP-10382) Ignore packages of which the latest version is not in the index

lib/puppet/provider/package/pacman.rb, spec/unit/provider/package/pacman_spec.rb
Using the `-y` switch in Pacman refreshes the catalog, but doesn't
upgrade existing packages. This causes a "partial upgrade".
From the Arch Linux wiki: [Partial upgrades are
unsupported](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported)
This change removes the `-y` switch. It will be up to the user to
refresh the catalog and upgrade the system _explicitly_. The other
approach would be to have both the `-y` _and_ `-u` switches, but that
would mean that installing a package through Puppet would implicitly
upgrade the whole of the system - I don't think that would be desirable.
=> (PUP-10152) Prevent Pacman package provider doing partial upgrades

lib/puppet/functions/call.rb
Note that Deferred has been supported since Puppet 6.0
=> (DOCS) (DOCUMENT-1084) fix Deferred value note

acceptance/tests/provider/package/yum_semantic_versioning.rb, lib/puppet/provider/package/rpm.rb, lib/puppet/provider/package/yum.rb, lib/puppet/util/package/version/rpm.rb, lib/puppet/util/rpm_compare.rb, spec/unit/provider/package/yum_spec.rb, spec/unit/util/package/version/rpm_spec.rb
This PR adds version range support for yum provider
example manifest will install the highest available version that is
above or equal 1.7.0
package { 'tree':
ensure => ('>=1.7.0'),
provider => 'yum',
}
=> (PUP-10298) Yum version range support

acceptance/tests/windows/PUP-9719_windows_system_first_pa_run.rb
Because this test was renabled in CI, tests are failing on 2008r2
because the task scheduler cannot find puppet in its PATH.
This commit  changes the test to explicitly specify the
full path for the scheduled task.
=> (PUP-10376) specify the full path for the schtask

lib/puppet/environments.rb, spec/unit/environments_spec.rb
This commit ensures that we return an empty array, rather than `nil`, when
validating environment directories. Previously, if you didn't have an
`@environment_dir`, an `undefined method` error would be thrown when trying to
query environments:
```
$ curl https://localhost:8140/puppet/v3/environments -H "Content-type: application/json" -k
{"message":"Server Error: undefined method `collect' for nil:NilClass","issue_kind":"RUNTIME_ERROR"}%
```
=> (PUP-10405) Fix `undefined method` error when querying environments

lib/puppet/provider/package/pip3.rb
In certain environments, the methods and variables in ’puppet/provider/package/pip.rb’ were being initialized twice. First and only consequences of this issue appeared when constant variables were added to this file and warnings regarding double initialisation/definition were shown to the user at every puppet run.
This happened only when puppet’s autoloader from ‘puppet/util/autoload.rb’ parsed and loaded ’puppet/provider/package/pip3.rb’ first and after it did the same with ’puppet/provider/package/pip.rb’, even though ’puppet/provider/package/pip3.rb’ required ‘puppet/provider/package/pip.rb’ already. The loading order is important for producing this issue. It can be affected by factors such as operating system, modules installed and decisional mechanisms used (like the 'specificity' …
=> (PUP-10401) Pip package provider outputs warning on puppet run

lib/puppet/network/http/base_pool.rb
MRI's SSLSocket#cipher returns an array, while JRuby returns a string[1]. We
don't typically run our client http code under JRuby, but ensure we don't crash
when trying to print debug info.
[1] https://github.com/jruby/jruby/issues/2436
=> (maint) JRuby SSLSocket#cipher returns a string unlike MRI

lib/puppet/node/environment.rb, spec/integration/node/environment_spec.rb, spec/unit/node/environment_spec.rb
If the keyword `bolt_project` is defined, the Bolt project should be
loaded at the head of the `Puppet::Node::Environment#modules` list of
modules. Bolt sets a temporary environment when running which it uses to
load modules on it's modulepath. We want to maintain this behavior and
also load the Bolt project directory configure by the user as a
standalone module. This ensures that any modules with the same name as
the Bolt project aren't loaded, so that the Bolt project can safely
shadow existing modules only when specified in Bolt. Additionally this
ensures that only the Bolt project is loaded as a module, not any
sibling directories. The keyword should only ever be set in Bolt
contexts and should not impact Puppet environments.
=> (PUP-10379) Load bolt project into environment module list

lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/puppet_gem.rb
In certain environments, the methods and variables in ’puppet/provider/package/gem.rb’ were being initialized twice. First and only consequences of this issue appeared when constant variables were added to this file and warnings regarding double initialisation/definition were shown to the user at every puppet run.
This happened only when puppet’s autoloader from ‘puppet/util/autoload.rb’ parsed and loaded ’puppet/provider/package/puppet_gem.rb’ first and after it did the same with ’puppet/provider/package/gem.rb’, even though ’puppet/provider/package/puppet_gem.rb’ required ‘puppet/provider/package/gem.rb’ already. The loading order is important for producing this issue. It can be affected by factors such as operating system, modules installed and decisional mechanisms used (like the …
=> (PUP-10390) Ruby file gets loaded twice

lib/puppet/util/pidlock.rb, lib/puppet/util/windows/process.rb, lib/puppet/util/windows/security.rb, spec/unit/util/pidlock_spec.rb
Prior to this commit, if puppet is running in the background as a service, and the user runs `puppet agent -t` in the foreground, the foreground process may not have permission to open the process token for the background process running as `LocalSystem`, causing puppet to raise with an ambiguous error message.
To fix this, we open the process token with the `SeDebugPrivilege`, which allows access to any process.
=> (PUP-10248) Windows pidlock can raise access denied

lib/puppet/provider/package/pkgdmg.rb, spec/unit/provider/package/pkgdmg_spec.rb
This pull request supersedes #8072. 
The pkgdmg package provider uses the '-noidme' flag with hdiutil, which was deprecated in macOS 10.15. See man hdiutil for more information. In macOS 10.15 the '-noidme' flag causes hdiutil to output a deprecation warning, which then causes pkgdmg to fail to parse the plist xml that hdiutil generates, which then causes the package installation to fail in puppet.
This change removes the '-noidme' flag from pkgdmg in order to prevent the deprecation warning from hdiutil, and restore functionality to pkgdmg in macOS 10.15 and above. Additonally, after reviewing the man page for hdiutil in macOS 10.14, it seems the '-noidme' flag is unnecessary for older versions of macOS as hdiutil appears to not perform idme actions by default. This change also removes …
=> (PUP-10408) Remove deprecated '-noidme' flag from pkgdmg package provider

lib/puppet/pal/pal_impl.rb, spec/unit/puppet_pal_2pec.rb
This updates the scope for a `ScriptCompiler` to not contain any
`$facts`, `$trusted`, or `$server_facts`.
This work is to enable the use of the `lookup` function in Bolt plans
outside of apply blocks. Since the concept of `facts`, etc. do not make
sense in the scope of running a plan, these fields should not be
available. Removing these fields from the scope disables the use of
interpolations outside of apply blocks.
Relates to puppetlabs/bolt#1403
=> (PUP-10397) Remove facts and vars from ScriptCompiler scope

lib/puppet/http/resolver.rb, lib/puppet/http/resolver/server_list.rb, lib/puppet/http/resolver/settings.rb, lib/puppet/http/resolver/srv.rb, lib/puppet/http/session.rb, spec/unit/http/session_spec.rb
Previously, resolver exceptions were collected in the session, and were only
cleared the next time `route_to` was called. To ensure the exceptions have the
same lifetime as the call to `route_to` and no more, pass an error_handler
callback to the `route_to` method. The callback will be called once per
exception that occurs during the resolution process.
=> (maint) Use callback to report on resolver exceptions

lib/puppet/util/pidlock.rb, spec/unit/util/pidlock_spec.rb
(maint) Simplify pidlock detection when we already own the lock
If the pidlock file contains our process id, then we by definition own the lock,
and can short-circuit the `clear_if_stale` logic.
It's possible pid was recycled, but that means whatever process created the
pidlock no longer exists, and we've "inherited" the pidlock.
This commit updates `clear_if_stale` to call `lock_pid` only once, as each call
reads the pidlock from disk.
As a result of this change, we only attempt to lookup the process name and args
in the case where the lockfile contains a pid that isn't us and the pid is still
active. As a result, some of the stubbing logic was removed from the spec test.
This also means calling `locked?` in `rake parallel:spec` no longer clears the
lock. A new test wasn't added for that …
=> (maint) Don't clear "stale" pid when running parallel:spec

lib/puppet/util/pidlock.rb, spec/unit/util/pidlock_spec.rb
* upstream/5.5.x:
(maint) Simplify pidlock detection when we already own the lock
Conflicts:
lib/puppet/util/pidlock.rb
spec/unit/util/pidlock_spec.rb
There was conflict due to no longer calling `lock_pid` multiple times while
clearing and the begin/rescue when failing to lookup the procname. The tests
also had to change because we only resolve the pid to a process name if the
process is still active.
=> (maint) Merge 5.5.x to master

lib/puppet/provider/package/gem.rb, spec/unit/provider/package/gem_spec.rb
When figuring out whether an installed gem version satisfies the manifest requirements, Puppet would run the requested version through `Gem::Dependency.new`.
Initializing `Gem::Dependency` with composed requirements (i.e. ">=1.2, <2") would trigger a parse error when parsing in `Gem::Requirement`. Since `Gem::Dependency` supports arrays of requirements, we fix this by splitting our requested version on comma.
On strings that do not have commas and are not valid Puppet version ranges (like "~> 1.0"), the split will be a noop (with the exception of it turning into array, which has no side effects on `Gem::Dependency.new`).
=> (PUP-10395) Fix insync for gem version ranges

lib/puppet/agent.rb, spec/unit/agent_spec.rb
Before this commit, `run_in_fork` is calling `exit` with value
returned by block without any check. If a block returns `nil`,
puppet run will fail and raise `TypeError` exception.
With this correction, in case a block returns `nil` puppet will
call `exit(1)` an run will fail.
=> (PUP-10366) defense to `exit` calls

lib/puppet/agent.rb
as `return` is returning from method defining the block and not
from the block only, undo returned value changes as they
unexpectedly change puppet behavior (and pxp-agent acceptance fails)
=> (maint) partially revert a2d41de

lib/puppet/application/agent.rb, lib/puppet/configurer.rb, lib/puppet/transaction/report.rb, lib/puppet/util/at_fork.rb, lib/puppet/util/platform.rb, spec/unit/application/agent_spec.rb, spec/unit/configurer_spec.rb, spec/unit/transaction/report_spec.rb, spec/unit/util/at_fork_spec.rb
Prior to this commit, Puppet started metrics calculation somewhat late during runtime (at [`Configurer#run`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/configurer.rb#L202)). This commit adds a new `startup_time` metric that includes the duration between startup and report initialization.
This is especially visible if the user has lots of external/custom facts, as Facter will evaluate all of them the first time `Facter.value` is called in Puppet, so facts are being loaded twice due to them being used in Puppet.
This is just a proof of concept as I'm not sure this is the way we should take. I also commented the Facter use in `atForkHandler` since it gets executed very early in the Puppet run and with that in place we don't get to `Application#run` until after the first run …
=> (PUP-10371) Add metric for total agent runtime

lib/puppet/agent.rb
due to bad understanding of code removed in 5ea240ac30, we expected
that `exit(-1)` will set `exitstatus` to `-1` and `raise SystemExit`,
while what happened  was that `exitstatus` was interpreted as `unsigned char`
and had value of `255`, hence `run_in_fork` will always just return `exitstatus`
=> (maint) do not explicitly call `exit` in `run_in_fork`

lib/puppet/provider/service/systemd.rb, spec/fixtures/unit/provider/service/systemd/list_unit_files_services, spec/unit/provider/service/systemd_spec.rb
Fixes inconsistency in puppet behaviour: services marked as `bad` by `systemctl` were omitted when listing all available services (via `puppet resource service`) but when querying individually the same services (via `puppet resource service <service_name>`) they actually appeared to be
enabled and running.
This weird behaviour has been discovered on Ubuntu 18.04 with pe_postgresql service where systemctl seemed to simply not like at all symlink chaining of unit conf files. Full details available in the comments section of the [ticket](https://tickets.puppetlabs.com/browse/PUP-10378).
=> (PUP-10378) 'puppet resource service' omitting services on Ubuntu

lib/puppet/ssl/state_machine.rb, spec/unit/ssl/state_machine_spec.rb
When bootstrapping the agent's ssl subsystem, release the ssl lockfile prior
to sleeping (when the cert hasn't been issued yet), and reacquire the lockfile
after. If we fail to reacquire, raise an error as another puppet instance
acquired it.
=> (PUP-10228) Release ssl lockfile while sleeping

ext/windows/service/daemon.rb
Replace deprecated usage of `puppet --configprint` with `puppet config print`.
=> (PUP-10414) Replace deprecated calls to `--configprint`

lib/puppet/http/client.rb, lib/puppet/http/external_client.rb, lib/puppet/http/service/ca.rb, lib/puppet/http/service/compiler.rb, lib/puppet/http/service/report.rb, lib/puppet/reports/http.rb, spec/integration/http/client_spec.rb, spec/unit/http/client_spec.rb, spec/unit/http/external_client_spec.rb, spec/unit/reports/http_spec.rb
Pass the body of a PUT or POST request as an argument instead of contained in
the options hash.
=> (maint) Pass put/post body as an argument

lib/puppet/provider/package/yum.rb, spec/fixtures/unit/provider/package/yum/yum-check-update-subscription-manager.txt, spec/unit/provider/package/yum_spec.rb
RedHat RHBA-2020:1028 changed the output of `yum check-update`
when subscription manager is enabled(adding extra blank lines) breaking
the `check_updates` method of `yum provider`.
This commit changes how we parse the output of `yum check-update`
in order not to depend on the first blank line occurred but rather
split by blank lines, and check on each chunk to see
if we can extract package information.
=> (PUP-10432) Fix yum provider check_updates.

lib/puppet/provider/package/pip.rb, lib/puppet/util/package/version/pip.rb, spec/unit/provider/package/pip_spec.rb, spec/unit/util/package/version/pip_spec.rb
Sorting and comparison mechanism fixed when deciding the latest version available for a python package. Mechanism will fall through old implementation when unexpected version patterns appear as input.
=> (PUP-10375) Latest package version for pip provider fixed

lib/puppet/http/client.rb, lib/puppet/network/http/pool.rb, spec/integration/network/http_pool_spec.rb, spec/unit/http/client_spec.rb, spec/unit/network/http/pool_spec.rb
The http client didn't construct the connection pool the same way that the legacy networking code did. As a result, connections made with the client did not observe the http_keepalive_timeout, so it couldn't be disabled or tuned.
=> (PUP-10434) Observe http_keepalive_timeout setting

lib/puppet/provider/package/aix.rb, spec/unit/provider/package/aix_spec.rb
Previously, when installing packages on AIX systems, Puppet would only check the package name and version to ensure presence.
If a package is in a broken or inconsistent state, Puppet would not report any error, causing false positives concerning installed packages.
Extend the package query regular expression to also take into account the package state, which can be one of the following:
```
A – Applied.
B – Broken.
C – Committed.
E – EFIX Locked.
O – Obsolete. (partially migrated to newer version)
? – Inconsistent State...Run lppchk -v.
```
If the package we are installing gets into a broken (B) or inconsistent (?) state, we abort the installation. We also treat packages marked with these codes as absent when querying installed packages.
~Open point: should we log broken and inconsistent …
=> (PUP-8937) Check AIX package state after install

lib/puppet/provider/service/systemd.rb, spec/fixtures/unit/provider/service/systemd/list_unit_files_services, spec/unit/provider/service/systemd_spec.rb
Even though, services that are in the `static` state can not be enabled due to missing information in the `[Install]` unit file section (puppet actually shows them always as enabled but a debug log is printed every time there is an enabling/disabling attempt and no changes are done),
they can be started/stopped (and status can be checked), so puppet is able to show information about them. Before this commit, puppet already presented information about these services but only when asked about a particular service by name (`puppet resource service <static_service_name>`).  When listing information about all available services (`puppet resource service`), `static` services were omitted, causing inconsistency in puppet's behaviour.
=> (PUP-10437) systemd provider listing static services fix

acceptance/tests/resource/user/should_create_with_expiry_absent.rb, lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
When a user is created, useradd will execute 'useradd -e -M test'.
Useradd -e on SLES requires a number of days parameter that is optional on other
platforms. Without the parameter, useradd -e on SLES will create an
expired user with expiration date on 1970-01-01.
The newly added -1 means the account will never expire
=> (PUP-7663) -1 instead if '' when expiry = :absent

lib/puppet/provider/service/systemd.rb, lib/puppet/type/service.rb, spec/unit/provider/service/systemd_spec.rb, spec/unit/type/service_spec.rb
Services that are in the `indirect` state should not be enabled or disabled by puppet. The `systemctl` call with the `is-enabled` argument will continue to report the service to be in a `indirect` state even after attempting enable/disable it, causing puppet to retry at every run if the manifest requests so. Before this commit it reported false changes each time also.
A debug log will be shown each time there is an attempt to enable/disable an `indirect` service and no changes will be done.
=> (PUP-7163) systemd provider 'indirect' service fix

lib/puppet/forge/repository.rb, lib/puppet/http/client.rb, lib/puppet/http/external_client.rb, lib/puppet/reports/http.rb, spec/unit/http/client_spec.rb, spec/unit/http/external_client_spec.rb
The old API accepts credenials as options[:basic_auth] which contains a
hash with username and password. The new API had flattened these so that
username was options[:user] and password was options[:password]. This
commit reverts back to the old way so that credentials are namespaced
and passed in as options[:basic_auth][:user] and
options[:basic_auth][:password]
=> (PUP-10470) Pass credentials in basic_auth

spec/unit/provider/service/systemd_spec.rb
Aligns usage of `provider_class` instead of `described_class` in `systemd_spec.rb`.
=> (maint) Merge up 5c8f9a to master fix

lib/puppet/provider/package/portage.rb, spec/unit/provider/package/portage_spec.rb
The original confine against operatingsystem makes the portage provider unusable on other Gentoo-based distributions, if they have a proper operatingsystem name.
Switching it to confine against osfamily instead will let it be used for all Gentoo-based distributions, regardless of their name.
=> (PUP-10469) Fix portage package provider confine

lib/puppet/indirector/file_content/http.rb
Puppet no longer uses the 'http' terminus to retrieve file content, so deprecate
it in preparation for puppet 7. Puppet **does** use the 'http' terminus for file
metadata, so that one is unchanged.
There are no tests for the terminus, so the warning is only printed if you
explicitly call a method on the indirection:
irb(main):008:0> Puppet::FileServing::Content.indirection.terminus_class = 'http'
=> "http"
irb(main):009:0> Puppet::FileServing::Content.indirection.find('https://foo.com')
Warning: Puppet::Indirector::FileContent::Http is deprecated. Use Puppet::HTTP::Client instead.
(location: /Users/josh/work/puppet/lib/puppet/indirector/file_content/http.rb:15:in `initialize')
=> (PUP-10444) Deprecate http file content terminus

spec/integration/util/windows/adsi_spec.rb
Previously the test created a user without a password which sometimes
fails in appveyor due to password complexity requirements. Set a
password that includes lower, upper, numerics and punctuation.
=> (maint) Avoid transient error due to empty password

lib/puppet.rb, lib/puppet/application/device.rb, lib/puppet/application/ssl.rb, lib/puppet/configurer.rb, lib/puppet/face/facts.rb, lib/puppet/face/plugin.rb, lib/puppet/forge/repository.rb, lib/puppet/reports/http.rb, lib/puppet/runtime.rb, lib/puppet/ssl/state_machine.rb, lib/puppet/test/test_helper.rb, lib/puppet/type/file/source.rb, spec/unit/network/http_pool_spec.rb, spec/unit/puppet_spec.rb, spec/unit/reports/http_spec.rb, spec/unit/ssl/state_machine_spec.rb
Use symbols for names of runtime implementations, so that callers don't need to
allocate a string (puppet doesn't enforce frozen string literals yet).
=> (PUP-10471) Use symbols for implementation names

lib/puppet/agent.rb, spec/unit/agent_spec.rb
When agent run is done in a forked process and an error is raised,
having an explicitly return in a block ends up in hitting a
LocalJumpError.
```
-- Logs begin at Thu 2020-04-30 10:08:03 UTC, end at Thu 2020-04-30 10:09:20 UTC. --
Apr 30 10:08:12 formative-child systemd[1]: Started Puppet agent.
Apr 30 10:08:12 formative-child systemd[1]: Starting Puppet agent...
Apr 30 10:08:17 formative-child puppet-agent[874]: Starting Puppet client version 6.15.0
Apr 30 10:08:17 formative-child puppet-agent[1265]: Could not run Puppet configuration client: undefined local variable or method `a' for #<Puppet::Agent:0x0000000002c8aad0>
Apr 30 10:08:17 formative-child puppet[874]: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:98:in `fork': unexpected return
```
=> (PUP-10477) remove non-local return from agent.rb

lib/puppet/indirector/rest.rb, spec/unit/indirector/rest_spec.rb
Deprecate the find, search, etc methods on the base rest terminus. Subclasses
of the rest terminus should use the HTTP client.
=> (PUP-10445) Deprecate base rest methods

lib/puppet/indirector/file_metadata/http.rb, spec/integration/application/agent_spec.rb, spec/integration/http/client_spec.rb, spec/lib/puppet_spec/https.rb, spec/unit/indirector/file_metadata/http_spec.rb, spec/unit/indirector/file_metadata/rest_spec.rb
Use our HTTP client when making HEAD requests to retrieve file metadata from http(s) sources. Continue to trust the system cert store and puppet CA when making https connections.
We now use persistent connections when making HEAD requests. Previously we made one non-persistent connection per file resource with an http(s) source.
Also update the rest terminus tests so we call `find`, etc on the model `Puppet::FileServing::Metadata` and not on the terminus. The former takes the URL, while the latter takes a request.
=> (PUP-10482) Use http client for http file metadata

lib/puppet/face/module/search.rb, spec/unit/face/module/search_spec.rb
Rather than using `puppet module` to search for modules, users should
go to the Puppet Forge to search modules.
=> (PUP-10480) Deprecate 'puppet module search'

lib/puppet/file_serving/http_metadata.rb, spec/unit/indirector/file_metadata/http_spec.rb
Previously, we parsed the Content-MD5 header strictly (RFC 4648), but some
webservers don't include padding, so parse the header leniently (RFC 2045).
Blocked on https://github.com/puppetlabs/puppet/pull/8131
=> (PUP-10164) Parse Content-MD5 leniently

lib/puppet/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
This PR updates the global option "--no-gpg-check" to "--no-gpg-checks". "--no-gpg-checks" is the correct flag from the zypper documentation:  https://en.opensuse.org/SDB:Zypper_manual_(plain)
"--no-gpg-check" works because zypper supports unique name abbreviations for flags:
https://github.com/openSUSE/zypper/blob/master/src/utils/flags/zyppflags.cc#L378 but this causes confusion when using this flag in a Puppet manifest.
Zypper also accepts multiple options of the same type, so:
```
/usr/bin/zypper --no-gpg-check --no-gpg-checks install --auto-agree-with-licenses --no-confirm apache 
```
does the same thing as:
```
/usr/bin/zypper --no-gpg-checks install --auto-agree-with-licenses --no-confirm apache 
```
=> (PUP-10433) Add --no-gpg-checks as global option

acceptance/tests/resource/service/systemd_resource_shows_correct_output.rb, lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
When a systemd service is managed with `puppet resource`,
inconsistencies could be encountered depending on the properties
managed.
`Puppet::Type.to_resource` checks the status of each parameter,
ultimately calling the `enabled?` method in the systemd provider. If
`statuscmd` was previously called, it would have overwritten the
contents of `$CHILD_STATUS`, which is used by the `enabled?` method as
the exit code of `systemctl is-enabled`.
This could happen when passing both `ensure=stopped` and
`enabled=true` to a service, causing `systemctl is-active` to exit
with 3. When `enabled?` is called again, `$CHILD_STATUS` refers to the
context of the `is-active` call, which is not relevant anymore.
To fix this, we update the method calling `is-enabled` to also return
the exit code.
=> (PUP-10479) systemd wrongly reports enabled state

acceptance/tests/resource/service/systemd_resource_shows_correct_output.rb
Not all services are available on the required platforms. We should be
able to use the puppet service itself as we only want to enable it, so
it shouldn't interfere with the tests.
Caused by https://github.com/puppetlabs/puppet/pull/8126.
=> (maint) Fix systemd acceptance test

lib/puppet/pal/catalog_compiler.rb, lib/puppet/pal/pal_impl.rb, lib/puppet/parser/compiler.rb, spec/unit/puppet_pal_catalog_spec.rb
This commit makes two changes to PAL to support more features within puppet during a catalog compile:
1. When variables are passed to `.with_catalog_compiler` they are now deserialized if they are serialized pcore types
2. A new function was added to the compiler class within `.with_catalog_compiler` so that a process calling PAL functions can evaluate ast with node definitions.
=> (PUP-10476) PAL additions to support more use cases from bolt

lib/puppet.rb, lib/puppet/util/autoload.rb, spec/unit/puppet_spec.rb, spec/unit/util/autoload_spec.rb
Move $LOAD_PATH modification earlier so that it happens when Puppet is
single threaded. This moves the vendor module inclusion to a settings hook,
and libdir to app default initialization.
=> (PUP-10483) Modify $LOAD_PATH when settings are initialized

lib/puppet/file_system/uniquefile.rb, spec/unit/file_system/uniquefile_spec.rb
Ruby emits a useless error message if the mkdir fails because the parent
directory doesn't exist. This often shows up when
puppet tries to create a lockfile, such as when managing a file resource
whose parent doesn't exist, because it's not managed.
=> (PUP-4442) Improve Uniquefile mkdir error message
