puppetlabs/puppet

acceptance/tests/resource/service/systemd_resource_shows_correct_output.rb, lib/puppet/file_system/uniquefile.rb, lib/puppet/provider/package/zypper.rb, lib/puppet/provider/service/systemd.rb, spec/unit/file_system/uniquefile_spec.rb, spec/unit/provider/package/zypper_spec.rb, spec/unit/provider/service/systemd_spec.rb
* pl/5.5.x:
(PUP-4442) Improve Uniquefile mkdir error message
(maint) Fix systemd test
(PUP-10433) Add --no-gpg-checks as global option
(PUP-10479) systemd wrongly reports enabled state
Conflicts:
spec/unit/provider/service/systemd_spec.rb
Conflict were solved by keeping provider initialization from master
`provider = provider_class.new(...)` and updating `provider.execute` mock
from 5.5.x
=>  (maint) Merge 5.5.x to master

lib/puppet/agent.rb, lib/puppet/daemon.rb, spec/unit/daemon_spec.rb
Before this change, puppet agent could get in a repeatedly `restart_requested` state. 
This happens due to two agent runs taking place at about the same time where the second one needs to reload the puppet service(or simply receives a HUP signal) and can't restart because the first run is still in progress.
=> (PUP-10351) Puppet Agent fails to self-restart

CODEOWNERS
There are no longer any members of the puppetlabs/language team. All of
their work has fallen to the puppetlabs/puppetserver-maintainers team
who is already a co-owner of the entire repository.
However, Bolt is the primary consumer of PAL and will own it.
=> (maint) Update language ownership

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
Quoting is required if the path to the pip command contains spaces.
Required for execpipe() but not execute(), and quoting with execute() causes an error.
=> (PUP-10485) quote pip path when it has spaces

acceptance/tests/provider/package/dnfmodule_ensure_versionable.rb, lib/puppet/provider/package/dnfmodule.rb, lib/puppet/type/package.rb, spec/fixtures/unit/provider/package/dnfmodule/dnf-module-list.txt, spec/unit/provider/package/dnfmodule_spec.rb
This PR adds the ability disable a dnf module.
It was done by creating a new value for
ensure field, only available for dnf module.
Ex:
"package { 'package_name':
ensure => 'disabled',
provider => 'dnfmodule'
}"
=> (PUP-10419) disable for dnf module

lib/puppet/application/plugin.rb, spec/integration/application/plugin_spec.rb
When running `puppet plugin download` on a host that isn't the master, the
environment directory likely doesn't exist, so configure the environment mode
to not require it in the same way we do for `puppet agent`.
=> (PUP-10307) Don't require the environment to exist locally

lib/puppet/application/agent.rb, lib/puppet/daemon.rb, spec/unit/application/agent_spec.rb, spec/unit/daemon_spec.rb
Starting server as a daemon has been deprecated in 5.5.x and is now removed.
This commit cleans up the unused code left behind these changes.
Before merging:
=> (maint) Server as daemon cleanup

lib/puppet/agent.rb, lib/puppet/defaults.rb, spec/integration/application/agent_spec.rb, spec/unit/agent_spec.rb
Before this commit, an agent run would immediately exit if there was an already ongoing instance. There was no possibility of making it wait and retry before doing so. The only workaround was to manually retry multiple times until the agent lockfile was released.
Two CLI arguments/puppet configuration settings were added in aid of this issue.
Description for `waitforlock`:
> How frequently puppet agent should try running when there is an
> already ongoing puppet agent instance.
> This argument is by default disabled (value set to 0). In this case puppet agent will
> immediatly exit if it cannot run at that moment. When a value other than 0 is set, this
> can also be used in combination with the `maxwaitforlock` argument.
Description for `maxwaitforlock`: 
> The maximum amount of time the …
=> (PUP-8051) waitforlock and maxwaitforlock setting

lib/puppet/face/help.rb, tasks/manpages.rake
The `puppet man` application is deprecated and will be deleted. Generate ronn output using `puppet help <app> --ronn` in the same way that `puppet man <app>` does.
Eliminate reference to `sbin` directory as that was deleted in 3.0.
Remove commented out code
=> (PUP-10502) Generate ronn output using puppet help

lib/puppet/context/trusted_information.rb, spec/unit/context/trusted_information_spec.rb
Trusted external command may be expensive to run, so we only want to run it if we actually want/use the trusted external data. Previously, this command was invoked on pretty much every call, including file metadata requests, of which there can be hundreds during some Puppet runs.
After this commit, the trusted external command should typically only be invoked twice per Puppet run - once when the agent requests a Node, for environment, to start Pluginsync, and once when the agent requests a catalog.
=> (PUP-10292) Evaluate trusted-external lazily

lib/puppet/http/client.rb, lib/puppet/indirector/rest.rb, lib/puppet/network/http/connection_adapter.rb, lib/puppet/network/http_pool.rb, lib/puppet/runtime.rb, lib/puppet/ssl/verifier_adapter.rb, spec/unit/network/http/connection_spec.rb, spec/unit/network/http_pool_spec.rb
Calls to `Puppet::Network::HttpPool.http_instance` and friends are routed through the HTTP client while preserving the return value and exceptions. As result `Puppet::Network::HTTP::Connection` is never used in puppet and any extension (like puppetdb terminus) calling the method will not notice the change.
=> (PUP-10289) Route HttpPool requests to the HTTP client

lib/puppet/util/log/destinations.rb, spec/unit/util/log/destinations_spec.rb
The puppet master process used to drop privileges to the Puppet[:user] and
Puppet[:group], and then reopen its log destinations, so it was necessary that
its log file destination be owned by those accounts.
In puppet 4, the puppet-agent package no longer creates the `puppet` user and
group, only the pouppetserver package does that. As a result, running puppet
agent as root on a host that wasn't the puppetserver would always log a `Unable
to set ownership` error message.
This commit removes the `chown` logic as it's not needed for puppet agents. Also
confine the test based on Puppet::Util::Platform and not features. The latter
requires the features subsystem and is overkill for what's needed here.
=> (PUP-10407) Don't chown log file destination

lib/puppet/type/user.rb, spec/unit/type/user_spec.rb
Previously, if `purge_ssh_keys` was set on a user resource similar to:
```puppet
user { 'testuser':
purge_ssh_keys => true
}
```
Application would fail since the `purge_ssh_keys` parameter requires the home directory to also be managed by Puppet.
This commit adds a fallback to `Dir.home(username)` for resources that do not specify the `home` parameter.
=> (PUP-10506) Fix `purge_ssh_keys` requiring homedir

.gemspec
Facter 4 currently breaks puppet tests. Confine to less than 4 until we
can get that sorted.
=> (maint) Confine to facter < 4

lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/pip.rb, lib/puppet/provider/package/yum.rb, lib/puppet/provider/package/zypper.rb, lib/puppet/util/package/version/range.rb, lib/puppet/util/package/version/range/eq.rb, spec/unit/provider/package/yum_spec.rb, spec/unit/util/package/version/range_spec.rb
Fix parsing version range for simple version string like '1.2.3'.
**Puppet Version:** 6.11.0
**Puppet Server Version**: 6.11.0
**OS Name/Version:** Debian 9
**Steps:**
`puppet resource package prometheus-client ensure='0.7.1' provider='pip3' --debug`
**Actual Behavior:**
Debug log contains strange string:
> Debug: Cannot parse 0.7.1 as a pip version range, falling through.
=> (PUP-10496) Fix parsing version range for regular version

lib/puppet.rb
Since we may not have control over everywhere that manipulates
$LOAD_PATH in a threaded context, just try to synchronize it whenever
running on JRuby.
=> (PUP-10483) Synchronize $LOAD_PATH

lib/puppet/network/http/connection_adapter.rb, spec/integration/network/http_pool_spec.rb, spec/unit/network/http/connection_spec.rb
The Connection class accepts a URL as the request path, and sends it in
"absolute-form" in the request line[1]:
GET https://puppet:8140/ HTTP/1.1\r\n
Client's are only supposed to send absolute-form when CONNECT-ing to a proxy so
that the proxy knows which upstream server to forward the request to. However,
HTTP 1.1 servers are required to accept absolute-form, so things happen to work.
This commit allows the ConnectionAdapter to accept a URL like the Connection
class does, and passes a new URL to the client consisting of the current scheme,
server, port and path from the URL argument. The resulting request will be
made using "origin-form" as it should have been all along:
GET / HTTP/1.1\r\n
There shouldn't be any compatibility issues as servers prefer "origin-form".
This commit also …
=> (PUP-10289) Allow caller to pass a URL string when they meant a path

lib/puppet/type/service.rb
Adds a note to the service type to clarify enable parameter behavior. (see DOC-4016)
=> (docs) add note to clarify enable param

lib/puppet/daemon.rb
Commit 7d8b0d37664e1bdf274bfa04ccf7ef5e5ab425eb caused the scheduled agent run to be disabled, as a result the daemonized service would never run. Since the daemon always has an `agent`, just delete the line.
=> (maint) Run the scheduled agent job

.gemspec, spec/unit/indirector/catalog/compiler_spec.rb, spec/unit/provider/service/init_spec.rb, spec/unit/provider/service/openbsd_spec.rb, spec/unit/provider/service/openwrt_spec.rb, spec/unit/provider/service/redhat_spec.rb, spec/unit/provider/service/systemd_spec.rb
=> (PUP-10524) Address spec failures when running with facter 4

spec/integration/application/agent_spec.rb
Depending in how fast the pid file is created, we can
end-up in a situation where puppet agent run
is started before maxwaitforlock is exceeded resulting
in a call to the puppet server which is not started,
and the test will fail with `Failed to open TCP connection`
This commit adds an sleep of `maxwaitforlock` value
before starting the next agent run, to make sure that
timeout is honoured.
=> (maint) Fix maxwaitforlock integration test

lib/puppet/agent.rb, lib/puppet/ssl/state_machine.rb, spec/integration/application/agent_spec.rb
Previously the "exits if maxwaitforlock is exceeded" test sometimes failed
because it started a background thread to lock the lockfile and slept for 2
seconds before exiting. Meanwhile the main thread ran the `agent` application
which can take some time to execute. The 0.5 maxwaitforlock setting also forced
the main thread to always retry the lock once, and that incurred a 1 second
penalty based on `waitforlock`. So if the background thread exited (which
releases the lock) before the main thread retried, then the main thread would
acquire the lock and never output the expected "Exiting now..." message.
This commits sets the maxwaitforlock setting to 0 and changes the inequality to
'>=' to ensure we don't retry the lock when the setting is 0. We also memoize
Time.now, so that we don't …
=> (maint) Don't wait when deadline is 0

lib/puppet/defaults.rb, lib/puppet/ssl/ssl_provider.rb, spec/integration/application/agent_spec.rb, spec/unit/ssl/ssl_provider_spec.rb
If `Puppet[:ssl_trust_store]` is not nil and refers to a non-empty file, then
puppet will add that as a trusted CA store when making HTTPS requests to
non-puppet infrastructure, in addition to the puppet CA(s) and CA certs in the
puppet-agent CA cert bundle.
The setting will be ignored if the path refers to an empty file. A warning will
be emitted if the path refers to a directory, etc.
=> (PUP-7814) Add ssl_trust_store setting to load trusted CA certs

lib/puppet/agent.rb
Commit c5a8687ffee intended to switch the comparison to >= so that if the
deadline is the same as now (in integer seconds since the epoch) then we
shouldn't retry the lock. If the values were equal then the test would sometimes
fail on slow systems (windows appveyor) because the background thread exited and
released the lock before the retry occurred, so it didn't exit with the expected
message.
=> (maint) Don't retry the lock if the deadline is now

lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/openbsd_spec.rb, spec/unit/provider/user/useradd_spec.rb
I did some digging on how `shadow-utils` and `libuser` implemented the
`-M` flag, and on the assumptions that Puppet made regarding this
flag.
First, the `shadow` library implemented the `-M` flag (also known as
`--no-create-home`) back in 2008, in this commit[1]. For reference,
the first tag containing this commit was 4.1.3, which was released on
April 15th 2009.
Second, RedHat has been maintaining their own patched version of
`shadow` called `shadow-utils`. What they do is get the upstream
`shadow` source, *extensively* patch it, then vendor it as
`shadow-utils`, which is present on every RedHat-based OS starting
with at least EL 5. Among the patches that RedHat applies is one that
adds the same `-M` functionality as the upstream project did. However,
RedHat has been doing this long …
=> (PUP-8897) Fix `managehome` property for `useradd`

acceptance/tests/ssl/trusted_external_facts.rb, lib/puppet/defaults.rb, lib/puppet/trusted_external.rb, spec/unit/context/trusted_information_spec.rb
If a directory is specified, then trusted['external'] will contain a
hash of `<basename> => <data>` for each executable file in the directory.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (PUP-10528) Extend trusted_external_command to support a directory

lib/puppet/network/http/api/master/v3/environment.rb, lib/puppet/parser/compiler/catalog_validator/env_relationship_validator.rb, lib/puppet/parser/compiler/catalog_validator/site_validator.rb, lib/puppet/parser/environment_compiler.rb, lib/puppet/pops/issues.rb, lib/puppet/pops/resource/resource_type_impl.rb, lib/puppet/pops/validation/checker4_0.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, lib/puppet/resource/type.rb, lib/puppet/type.rb, spec/unit/parser/environment_compiler_spec.rb
Deprecate language keywords `site`, `application`, `produces`, `consumes`
Deprecate environment catalog and validators
Deprecate `export` and `consume` metaparameters
Deprecate `environment` REST API
=> (PUP-9251) Deprecate application orchestration

lib/puppet/parser/resource.rb, lib/puppet/parser/resource/param.rb, spec/integration/parser/compiler_spec.rb
In case of resource arrays, the parameters are shared between resources
```
test_mod::service { ["ServiceA","ServiceB"]:
password => Sensitive("password")
}
```
This leads to trouble for Sensitive parameters as puppet will unwrap the
value for first resource and will validate it against Sensitive type for
the second resource.
With this change, the parameter and it's value are duplicated when
resource is created.
=> (PUP-10511) fix resource array with sensitive parameters

lib/puppet/defaults.rb
This commit updates de default permisions for
state.yaml and transactionstore.yaml in order
to remove group write access.
=> (PUP-8922) update permision for state files

lib/puppet/defaults.rb, lib/puppet/network/http/api/master/v3/environment.rb, lib/puppet/parser/compiler/catalog_validator/env_relationship_validator.rb, lib/puppet/parser/compiler/catalog_validator/site_validator.rb, lib/puppet/parser/environment_compiler.rb, lib/puppet/parser/resource.rb, lib/puppet/parser/resource/param.rb, lib/puppet/pops/issues.rb, lib/puppet/pops/resource/resource_type_impl.rb, lib/puppet/pops/validation/checker4_0.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, lib/puppet/resource/type.rb, lib/puppet/type.rb, lib/puppet/util/windows/api_types.rb, lib/puppet/util/windows/registry.rb, spec/integration/parser/compiler_spec.rb, spec/integration/util/windows/registry_spec.rb, spec/unit/parser/environment_compiler_spec.rb, spec/unit/util/windows/api_types_spec.rb
* upstream/5.5.x:
(PUP-10511) fix resource array with sensitive parameters
(PUP-9251) Deprecate export & consume metaparameters
(PUP-9251) Deprecate `environment` REST API
(PUP-9251) Deprecate apporch environment catalog
(PUP-10536) strip after wide terminator
(PUP-8922) update permision for state files
(PUP-9251) Update app orchestration link
(PUP-9251) Deprecate application orchestration constructs
* Conflicts:
lib/puppet/pops/validation/validator_factory_4_0.rb (mismatch in
whitespace)
=> (maint) Merge up 5.5.x to master

lib/puppet/http/redirector.rb, lib/puppet/http/response.rb, lib/puppet/indirector/file_metadata/http.rb, spec/unit/http/client_spec.rb, spec/unit/http/response_spec.rb, spec/unit/indirector/file_metadata/http_spec.rb
Allows puppet to retrieve file content from github releases and Amazon S3 buckets using the http(s) source parameter. Amazon strictly verifies presigned URLs, which exposed some issues with puppet's HTTP redirection handling:
* Preserve query parameters from the `Location` header
* Resolve relative URLs in `Location` header relative to the base URL
* Rewrite `Host` header based on new host/port
* If HEAD request for file metadata fails due to access denied or method not allowed, then fallback to a partial GET request.
=> (PUP-6380) Fallback to partial GET if HEAD is not supported

lib/puppet/type.rb, spec/unit/type_spec.rb
This came up when investigating why sshkeys_core 2.0.0 does not purge
keys. To add support for multiple SSH key types per name, composite
namevars had to be implemented. However, the functionality only worked
one-way (when ensuring resources as opposed to querying existing
resources).
Ensuring a resource of type:
```puppet
sshkey { 'testuser@ssh-dss':
ensure => 'present',
...
}
```
would correctly evaluate to the following Puppet resource:
```puppet
Sshkey[testuser@ssh-rsa]{:name=>"testuser", :type=>"ssh-rsa", :key=>"..."}
```
Purging sshkeys would create different resources:
```puppet
Sshkey[testuser]{:name=>"testuser", :key=>"..."}
```
Meaning that multiple key types with the same name would not get
parsed correctly.
This happens due to `Puppet::Type.instances` not taking multiple …
=> (PUP-10510) Set correct title when collecting resources

acceptance/tests/resource/service/puppet_service_runs_puppet.rb
This commit adds an acceptance test to ensure that starting the puppet
service on agents runs puppet.  This validation was missing from the
`puppet_service_management.rb` test.  Due to the comprehensive nature of
the existing test, this test is added independently to reduce execution
time.  The existing test takes about 4m to execute while this specific
case takes about 30s.
=> (PUP-10527) Test puppet service runs puppet

lib/puppet/file_serving/terminus_selector.rb, spec/unit/file_serving/terminus_selector_spec.rb
Previously, if an indirector request's key was a URL, but the URL path started
with a double slash, then puppet thought it was a local absolute path. This
occurred because the indirector request strips the leading slash off the URL
path when setting its key, but the second slash remained, and that appeared to
be an absolute posix path.
This commit eliminates the premature optimization. Select the terminus based on
the request protocol. If no protocol is given and the request key is an absolute
path, then use the local :file terminus. Otherwise select the :file_server
terminus, which knows how to convert a mount path to a path on disk, such as
"modules/my_module/my_file".
=> (PUP-10544) Request protocol should take precedence over path

lib/puppet/file_serving/http_metadata.rb, lib/puppet/type/file.rb, lib/puppet/type/file/checksum.rb, lib/puppet/util/checksums.rb, spec/unit/file_serving/http_metadata_spec.rb, spec/unit/util/checksums_spec.rb
Artifactory generates X-Checksum-{Md5,Sha1,Sha256} headers, so parse them from
the HTTP response, if present, when determining the remote checksum.
There is a draft RFC for Want-Digest and Digest headers, but it's not
finalized yet: https://tools.ietf.org/html/draft-ietf-httpbis-digest-headers
This commit also sets the header fields on the response instead of stubbing
methods.
This is based on PR #5707 originally authored by Dylan Cochran <heliocentric@gmail.com>
and committed by Peter Souter <peter.souter+GIT@puppet.com>
Blocked on PR #8197
=> (PUP-5707) Support X-Checksum-* headers

lib/puppet/indirector/file_metadata/http.rb, spec/unit/indirector/file_metadata/http_spec.rb
HEAD requests to puppetserver will fail for default routes like
`/puppet-ca/v1/certificate/ca`, because puppetserver only allows GET requests in
its default tk-auth. Requests to custom mount points can also fail if the user
forgets to explicitly allow HEAD.
Since there are multiple ways HEAD can fail, fallback to a partial GET
request.
=> (PUP-10543) Fallback to partial GET if HEAD request to puppetserver fails

lib/puppet/forge/repository.rb, lib/puppet/http/client.rb, lib/puppet/indirector/file_metadata/http.rb, lib/puppet/reports/http.rb, spec/unit/http/client_spec.rb, spec/unit/indirector/file_metadata/http_spec.rb
Puppet's http client supports passing basic authentication explicitly as
an option, as is done with the `http` report processor. This commit
makes it possible to pass a URL containing userinfo and have puppet use
those credentials. If both are passed, then the explicit `basic_auth`
parameter takes precedence.
Blocked on https://github.com/puppetlabs/puppet/pull/8199
=> (PUP-6916) Allow userinfo to be passed in the URL

lib/puppet/pops/evaluator/evaluator_impl.rb, spec/unit/pops/evaluator/evaluating_parser_spec.rb
Previously we would generate a BlockExpression for apply blocks with
multiple statements, and assumed if an apply block had less than 2
statements that it had 1 statement and we would return that statement.
This meant that for apply blocks with 0 statements the AST would
be `nil`, which caused issues when we assumed it was a proper AST. This
now generates a BlockExpression for every case except when the block has
1 statement, in which case it returns the statement.
=> (PUP-10542) Generate AST for apply blocks with 0 statements

lib/puppet/network/http/api/indirected_routes.rb, spec/unit/network/http/api/indirected_routes_spec.rb
Print the list of format names that are unacceptable, not the
Puppet::Network::Format objects.
=> (PUP-10549) Print unacceptable format names not objects

lib/puppet/defaults.rb
Commit f40cc71e8 updated the description for the color setting, but that part
was lost along the way, likely when the file was reformatted in bf9ac399bd539
and conflicts resolved.
=> (maint) Update console color setting for Windows

lib/puppet/application/agent.rb, lib/puppet/configurer.rb, spec/integration/application/agent_spec.rb
Puppet failed to load cached catalogs containing rich data, because the
Configurer hadn't yet created the loaders necessary to deserialize the catalog
using pcore. This affected rich data types like Binary and Deferred, but not
Sensitive, since it predates pcore and is serialized differently.
This commit moves the creation of the loaders to the `agent` application similar
to how the `apply` and `device` applications already handle it. See commits
b9878fd0258 and b30ecfcc429.
If the environment changes based on the node response, then update the current
environment like we did before. Note there is a separate ticket to update the
current environment if the environment changes due to catalog convergence, see
PUP-10308.
This commit also preserves creation of the loaders if it hasn't been …
=> (PUP-10572) Create loaders in the agent application

lib/puppet/network/http/connection_adapter.rb, spec/integration/network/http_pool_spec.rb, spec/unit/network/http/connection_spec.rb
Puppet's connection adapter class URL encoded the request path and query parameters, whereas the old connection class did not. This restores the behavior that existed in 6.15.0.
Also include the query component when calling the connection adapter with the entire URL as a string, instead of just the path and query.
=> (PUP-10580) Don't double encode path and query

lib/puppet/type/file.rb, spec/unit/type/file_spec.rb
Previously puppet computed a checksum when it wrote files, then computed a checksum for the written file, and verified they matched. Later the `checksum_value` property was added which allows puppet to determine insync-ness without having to make a metadata request, which is especially important for http(s) file sources that often don't support checksums in HTTP headers. However, puppet didn't verify that the file content that it wrote matched the desired checksum value.
If a desired checksum type and value are specified, then always verify the file contents we wrote match. If a `source` is specified, try to fallback to the checksum in the source's metadata, if any. If a `content` is specified, then fallback to the checksum computed from the content (binary) string. In cases where neither …
=> (PUP-10368) Validate checksum values

acceptance/lib/puppet/acceptance/service_utils.rb, acceptance/tests/resource/service/windows.rb, lib/puppet/provider/service/windows.rb, lib/puppet/type/service.rb, lib/puppet/util/windows/service.rb, lib/puppet/util/windows/user.rb, spec/integration/util/windows/user_spec.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/type/service_spec.rb, spec/unit/util/windows/service_spec.rb
This feature allows puppet users to gain more control over their Windows services by now being able to manage the logon credentials for any of them as desired.
This commit adds the `logonaccount` property and the optional `logonpassword` parameter (not needed when the user specified in the `logonaccount` field has no password). These can be managed alone or in combination with the `ensure` property.
In the first case, the credentials will be checked for validity and then set but will not be used by the service until it is restarted. This respects the Windows GUI behaviour from `services.msc` where after changing the logon credentials, it prompts the user with the alert message `The new logon name will not take effect until you stop and restart the service.`.
When also managing `ensure` …
=> (PUP-1289) Manage service logon credentials on Windows

lib/puppet/file_serving/mount/locales.rb, lib/puppet/file_serving/mount/pluginfacts.rb, lib/puppet/file_serving/mount/plugins.rb, spec/unit/file_serving/mount/locales_spec.rb, spec/unit/file_serving/mount/pluginfacts_spec.rb, spec/unit/file_serving/mount/plugins_spec.rb
Previously the agent printed an ugly warning if it tried to pluginsync, but the
server did not have any top-level module directories. The puppetserver packages
create several default module directories like `/etc/puppetlabs/code/modules`
so this doesn't often occur, though it used to occur with a newly installed
webrick puppet master in 4.x, and can occur if the directories are deleted.
The motivation for this change is because the server's file metadata response
should differentiate between the set of file metadata is empty versus missing.
The agent should fail in the latter case, but not the former.
This commit changes the `search` method for plugins,pluginfacts,locales mount
points to return the default path Puppet[:codedir] so that the file server
returns FileMetadata for that …
=> (PUP-2608) Return default file metadatas for builtin mounts

lib/puppet/util.rb
Commit 94df3c1 broke rspec-puppet. Revert the commit, including how the current platform is detected so as to not break rspec-puppet in a Z release.
=> (PUP-10586) Revert "(PUP-10254) Make default environment constant"

lib/puppet/transaction/persistence.rb, spec/unit/transaction/persistence_spec.rb
Commit 0b6563eea09 allowed Puppet::Util::Storage to load Symbol and Time from
yaml, but only added Symbol to Puppet::Transaction::Persistence. As a result,
puppet would fail to load the transactionstore if it had stored a Time in the
prior run, issue a error and prevent puppet from reporting on corrective change.
Add Time to the allowed list of classes and add a test like the "should load
Time and Symbols" test in storage_spec.
=> (PUP-10585) Allow transaction store to YAML load Time

lib/puppet/defaults.rb
Remove the --no-client option from runinterval setting on configuration page, as the option has been removed. See DOC-4588.
=> (docs) remove runinterval --no-client option

lib/puppet/indirector/hiera.rb, lib/puppet/test/test_helper.rb, spec/integration/data_binding_spec.rb, spec/unit/configurer_spec.rb, spec/unit/ssl/host_spec.rb
Preserve the `@termini` hash before running each test so that it is restored at
the end. We have to duplicate the hash so that the saved copy isn't modified
during the test. The hash maps registered termini names (eg :processor) to
objects for each indirection (eg :report).
Prior to this, tests could reuse a terminus created and registered during an
earlier test. If the terminus' initialize method had side effects, like creating
a settings catalog, then those side effects could be skipped, causing the test
to fail, but not when run in isolation.
=> (maint) Clear registered termini instances after each test

lib/puppet/provider/package/apt.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/aptitude_spec.rb
A very naive attempt at adding apt-mark support
@adrienthebo i saw an offer to help with this functionality on #5216 and wondered if would be able to comment on this change also, Its not quite working but i feel its getting close.  however If i am miles away  please say.  thanks
=> (PUP-6631): attempted to support apt-mark

lib/puppet/type/file.rb
https://tickets.puppetlabs.com/browse/DOC-4619
This commit should fix the following formatting error:
https://puppet.com/docs/puppet/6.17/type.html#file-attribute-backup
=> (DOCS) Fix formatting error

lib/puppet/parser/functions/create_resources.rb
We've gotten questions from users about why we don't more fully document create_resources. As I understand it, it's because it's a bit of magic, hard to read, and hard to troubleshoot. This note adds some of that context to the generated docs, assuming I've made the fix in the right place. Based on a conversation with @binford2k .
I'm not sure I've made the fix in the right place. If not, or if my note is inaccurate in any way, happy to fix, obviously.
=> (docs) caution for create_resources

lib/puppet/util/windows/eventlog.rb, lib/puppet/util/windows/string.rb, spec/unit/util/windows/string_spec.rb
Ruby < 2.1 did not correctly handle multibyte terminators when allocating and
resizing wide strings, causing data to be read past the end of the buffer. It
was fixed in ruby 2.1.0[1], which we no longer support.
Ruby < 2.4 did not correct handle multibyte terminators when transcoding
strings, such as when calling `String#force_encoding('UTF-16')` and converting
the binary string with a single null terminator to a wide string with a wide
terminator. That was fixed in 2.4.0[2] and backported to 2.3 in [3], which is
the minimum version we support.
[1] https://github.com/ruby/ruby/commit/1549894a0699abdfab1fbba0e468afd3f2f990b3
[2] https://github.com/ruby/ruby/commit/f2ee22371b15411e818b23199161d1658ba08622
[3] https://github.com/ruby/ruby/commit/6f122a4f10512bb60795faa0021e498800a7f1b8
=> (PUP-3970) Remove wide string terminator workaround

lib/puppet/application/apply.rb, lib/puppet/pops/loader/runtime3_type_loader.rb, lib/puppet/pops/loaders.rb, spec/fixtures/integration/application/apply/environments/spec/.resource_types/applytest.pp, spec/fixtures/integration/application/apply/environments/spec/modules/amod/lib/puppet/provider/applytest/applytest.rb, spec/fixtures/integration/application/apply/environments/spec/modules/amod/lib/puppet/type/applytest.rb, spec/integration/application/apply_spec.rb, spec/unit/pops/loaders/loaders_spec.rb
Previously, `puppet apply` failed if the manifest referenced a resource default,
and there existed pcore resource types for that resource in
`<env>/.resource_types/<type>.pp`. The resulting error was:
Could not autoload puppet/type/applytest: Attempt to redefine entity
During compilation the Runtime3TypeLoader delegated to the pcore loader to load
the resource type from the <type>.pp file, and cached the resulting
PResourceType object in the Runtime3TypeLoader's cache.
Later during catalog compilation, the `Catalog#to_ral` method called the
metatype manager to autoload the resource type and register it with the
Runtime3TypeLoader. However, due to the already registered PResourceType object,
the above error was raised.
To fix this issue we could include the pcore loader during compilation, …
=> (PUP-9602) Ignore pcore resource loader for puppet apply

Gemfile, lib/puppet/configurer/downloader.rb, lib/puppet/defaults.rb, spec/integration/faces/plugin_spec.rb, spec/unit/configurer/downloader_spec.rb, spec/unit/configurer_spec.rb
If an error occurs during pluginsync and `Puppet[:ignore_plugin_errors]` is
false, then stop the run, otherwise facts needed to compile the catalog and
types/providers needed to apply the catalog will be missing. The lack of facts
can cause compilation to fail, and the lack of type & providers can cause
application to fail, or worse data corruption due to mismatched versions of old
plugins and new catalogs or vice versa. To ensure backwards compatibility, the
setting defaults to true, so there is no change in current behavior, though the
default value will be changed to false in Puppet 7.
Part of the reason for the old behavior is that 4.x and earlier webrick-based
puppet master replied with HTTP 404 if it didn't have any modules installed with
at least one `lib` directory OR if the …
=> (PUP-1763) Stop agent run if pluginsync fails

lib/puppet/confine.rb, lib/puppet/confine/any.rb, lib/puppet/feature/base.rb, lib/puppet/file_system/file_impl.rb, lib/puppet/gettext/config.rb, lib/puppet/gettext/module_translations.rb, lib/puppet/indirector/exec.rb, lib/puppet/indirector/facts/facter.rb, lib/puppet/indirector/indirection.rb, lib/puppet/indirector/report/processor.rb, lib/puppet/module.rb, lib/puppet/network/format_support.rb, lib/puppet/network/http/route.rb, lib/puppet/node/environment.rb, lib/puppet/parameter.rb, lib/puppet/parser/type_loader.rb, lib/puppet/pops/lookup/context.rb, lib/puppet/provider/file/windows.rb, lib/puppet/settings.rb, lib/puppet/ssl/validator/default_validator.rb, lib/puppet/transaction.rb, lib/puppet/trusted_external.rb, lib/puppet/type.rb, lib/puppet/util/character_encoding.rb, lib/puppet/util/execution.rb, lib/puppet/util/windows/api_types.rb, lib/puppet/util/windows/security.rb, spec/unit/confine_spec.rb, spec/unit/network/format_support_spec.rb, spec/unit/util/character_encoding_spec.rb
Prefer the block form of `Puppet.debug` when passing an interpolated message, so
that the interpolation can be avoided when running in non-debug. This is similar
to commit 2d0d7333b, but includes server-side puppet code that is called on
every request, such as features, confines, gettext, network formats and route
matching. It also updates file system and Windows code paths that are triggered
for every file resource.
=> (maint) Use block form of Puppet.debug

.gemspec, ext/project_data.yaml
We ended up not using the httpclient gem, drop it for now.
=> (PUP-10490) Drop httpclient gem dependency

lib/puppet/application/lookup.rb, lib/puppet/util.rb, spec/integration/application/lookup_spec.rb
Some puppet default settings required facter to retrieve the data which
caused facter to load all external facts that are not used. This can
slow down puppet if external facts are slow.
To disable loading of external facts, Facter.load_external(false) must be 
called before Facter starts resolving facts.
Puppet::Util.skip_external_facts should set Facter.load_external(false) 
before executing the block of code, and after that it sets Facter.load_external(true).
=> (PUP-10599) skip local external facts on lookup

acceptance/tests/resource/service/windows.rb, acceptance/tests/resource/user/should_manage_roles_on_windows.rb, lib/puppet/provider/user/aix.rb, lib/puppet/provider/user/user_role_add.rb, lib/puppet/provider/user/windows_adsi.rb, lib/puppet/type/service.rb, lib/puppet/type/user.rb, lib/puppet/util/windows/api_types.rb, lib/puppet/util/windows/user.rb, spec/integration/util/windows/user_spec.rb, spec/unit/provider/user/windows_adsi_spec.rb, spec/unit/type/service_spec.rb, spec/unit/type/user_spec.rb
This feature allows puppet to manage the rights and privileges of Windows users through the existing `roles` property. The accepted values are, as described in Microsoft documentation, certain constant names (https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment) which can be passed in an array or as a string when it is just one.
This property comes in pair with the `role_membership` parameter which offers better control over the desired state through the two supported values: `minimum` (default) and `inclusive`. When this parameter is set to `minimum`, the given roles are appended to the existing ones. When it is set to `inclusive`, managed user remains only with the given roles.  The `roles` property set to an empty array in …
=> (PUP-10547) Manage user rights on Windows

lib/puppet/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
When a version without release is set, zypper
should rely on the rpm comparision, same as yum.
=> (PUP-10609) Fix zypper ensure version

lib/puppet/transaction/report.rb
This updates the reader's docs to mention that it also includes noop
corrective changes.
Signed-off-by: Enis Inan <enis.inan@puppet.com>
=> (maint) Update corrective_change reader's docs in the report object

acceptance/lib/puppet/acceptance/service_utils.rb, acceptance/tests/resource/service/launchd_provider.rb, acceptance/tests/resource/service/smf_basic_tests.rb, acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
This came up when runnning all acceptance tests for Ruby 2.7. We have additional spaces in the `puppet resource` output due to a param with a longer name, so update the assertions to match that.
=> (maint) Fix service assertions in acceptance

ext/project_data.yaml
This commit updates `project_data.yaml` to align with the win32-process
gem removal.
Depends on #8204
=> (PUP-10590) Remove win32-process gem dependency

ext/project_data.yaml
This commit updates project_data.yaml to align with the win32-service
gem removal.
Depends on #8194
=> (PUP-7446) Remove win32-service gem dependency

lib/puppet/application/ssl.rb, lib/puppet/defaults.rb, spec/unit/application/ssl_spec.rb
The default value did not reflect where puppet saves its CSR while waiting for
the CA to issue a certificate. Update the default value to match reality.
=> (PUP-9346) Change default hostcsr setting

lib/puppet/functions/reverse_each.rb, lib/puppet/functions/step.rb, lib/puppet/pops/types/iterable.rb
commit message from 4a137aa8e1902f10fe999659dd079272d444b538:
In Puppet's functions involving iteration we call
`Iterable.asserted_iterable()` to ensure whatever we are given is
properly coerced into an iterator. However, we also do a recursive type
inference on any elements of an Array, or keys and values if passed a
Hash. This is unnecessary for nearly every workflow and can be
prohibitively costly when working with large collections.
The one usage that could use an Iterator with typed elements is if a
user called `step` or `reverse_each` and attempted to save that
value or pass it into a 4x Puppet function defined w/in a .pp file. In
those cases a user _could_ assert that they received an
Iterator[SomeElementType].
To account for this we add a new optional parameter to …
=> (maint) Iterable performance improvements

lib/puppet/node/environment.rb
It was surprising that this wasn't a constant time operation.
=> (maint) Look up module by name

acceptance/lib/puppet/acceptance/windows_utils.rb, ext/project_data.yaml, ext/windows/service/daemon.rb, install.rb, lib/puppet/util/windows.rb, lib/puppet/util/windows/api_types.rb, lib/puppet/util/windows/file.rb, lib/puppet/util/windows/monkey_patches/dir.rb, spec/integration/util/windows/monkey_patches/dir_spec.rb
Defined missing functions, constants and structs in `puppet/util/windows/file`, and a private `wstrip` function in our Dir monkey-patch. The original gem monkey-patches the String class to define the method, but since we only use it in one place, we add it to Dir.
Also fixed some Ruby 2.7 warnings, and removed a stale require to Win32API which we don't use anymore.
Replaced win32-dir usage in install.rb with environment variables, and also removed the win32-security gem from project_data.yaml.
After this PR is merged we should no longer have dependencies on external win32 gems.
=> (PUP-6184) Remove win32/dir usage

lib/puppet/pal/pal_impl.rb, spec/unit/puppet_pal_2pec.rb
This reverts the changes made in #8063, which
removed facts and vars from PAL's ScriptCompiler scope. This
resulted in a breaking change that affected downstream projects
that rely on PAL's public API.
It also adds a new `:disable_facts` flag to `#with_script_compiler`,
which will prevent facts from being set for the compiler scope. The
default value for the flag is `false` to preserve the old behavior of
the script compiler, while allowing other tools (namely Bolt) the
ability to control the facts variables being set.
=> (PUP-10615) Add facts and vars back to ScriptCompiler scope

lib/puppet/defaults.rb, lib/puppet/node.rb, spec/integration/parser/node_spec.rb, spec/unit/node_spec.rb
Deprecated in 6.x because of security concerns, defaults changed to the implementation this pr uses. Modern site.pps can do all of the things that these enabled in more explicit way for those that want to opt-in to this kind of behavior.
=> (PUP-10436) Remove strict_hostname_checking & node_name setting/usage

lib/puppet/util/windows.rb, lib/puppet/util/windows/monkey_patches/dir.rb, spec/integration/util/windows/monkey_patches/dir_spec.rb
Before this commit, attempts of installing or running puppet on Windows via AWS Session Manager failed constantly with a `<class:Dir>': uninitialized constant Dir::PERSONAL (Name Error)` error. This behaviour was identified on EC2 Windows Server 2019 instances.
The issue is found in the `win32-dir` gem which at some point tries to assign the `Dir::PERSONAL` constant to `Dir::MYDOCUMENTS` without checking if it is initialized/defined first, resulting in the `Name Error` error above. The unlikely scenario where this happens is as follows:
The AWS Session Manager communicates with a `SSM Agent` installed on the desired instance. A user called `ssm-user` is created, either manually or automatically by the `SSM Agent` installer (only versions older than 2.3.612.0), to facilitate the connection …
=> (PUP-10600) Undefined constant on Windows via AWS Session Manager

lib/puppet/node/environment.rb, spec/integration/node/environment_spec.rb, spec/unit/node/environment_spec.rb
Previously, Bolt would only set the `bolt_project` Puppet setting if the
project was loadable, in this case if it had a name. However Bolt always
has a project, it just may not get loaded as a module. This presented
issues when we needed to know where the Bolt project was located in
Bolt's custom Puppet functions, but the Bolt project wasn't named. The
interim solution for this was to set a new Puppet setting
`bolt_project_data` to read from the custom Puppet functions. This
introduces a more robust solution, which is to only load the project if
a method `load_as_module?` returns true. This lets us always set the
`bolt_project` Puppet setting for access throughout the Bolt lifecycle,
while only loading the project as a module when valid.
See https://github.com/puppetlabs/bolt/issues/2051 …
=> (PUP-10618) Use load_as_module? to load Bolt project

lib/puppet/indirector/file_metadata/http.rb, lib/puppet/type/file/source.rb, spec/integration/application/apply_spec.rb
Prior to 6.16, puppet assumed http file sources in manifests were already URL
encoded. So to reference a URL path with a space, you had to specify:
source => 'http://example.com/b%20c'
Similarly, if the query contained a character that wasn't a URL code point[1],
such as 'b[c', then it had to be URL encoded in the manifest:
source => 'http://example.com?q=b%5Bc'
Commit 11eee4e886d changed the http content request so it called the `uri`
reader method instead of calling `URI(metadata.source)`. The former encodes the
source using `Puppet::Util.uri_encode` before parsing it, which could result in
double encoded source URLs. It also meant the http content used different levels
of encoding than the previous http metadata request.
The `uri_encode` method also incorrectly assumes `=` characters …
=> (PUP-10603) Consistently encode metadata and content for http URLs

lib/puppet.rb
Settings are registered by calling Puppet::Settings#define_settings, so remove
the deprecated Puppet.define_settings method.
=> (PUP-10472) Remove Puppet.define_settings

lib/puppet/resource.rb, lib/puppet/resource/type.rb, spec/unit/resource_spec.rb
* Puppet::Resource.set_default_parameters
* Puppet::Resource.validate_complete
* Puppet::Resource::Type.assign_parameter_values
=> (PUP-10474) Remove deprecated Puppet::Resource methods

lib/puppet/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
On Debian-based platforms, puppet will always report changes if `mark` is set to `none` on a resource. This commit updates the provider to properly parse packages that are not held.
Found in https://github.com/puppetlabs/puppet/pull/8267#issuecomment-675418735
=> (PUP-10643) Fix `mark => none` not being idempotent with dpkg provider

acceptance/tests/resource/exec/should_run_command_as_user.rb, acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_home.rb, acceptance/tests/resource/user/osx_10.4_should_fail_when_modify_uid.rb, acceptance/tests/resource/user/should_modify_home.rb, acceptance/tests/resource/user/should_modify_uid.rb
Commit 4f30d93c3eec899ebaca4d7b8eb89aaae89c746f removed the wrappers for `Beaker::Host#user_present` and `user_absent`.
This commit changes the code to also use the Beaker methods.
=> (PUP-10623) Use Beaker::Host#user_* methods

lib/puppet/http.rb, lib/puppet/http/resolver/server_list.rb, lib/puppet/http/service.rb, lib/puppet/http/service/puppetserver.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/service/puppetserver_spec.rb
Previously puppet related HTTP headers like `X-Puppet-Version` and those specified in `Puppet[:http_extra_headers]` were not sent in the simple status request, because the ServerList resolver made a "raw" HTTPS request. This commit adds a `puppetserver` service endpoint for REST APIs implemented in puppetserver/clojure and modifies the ServerList resolver to use that.
=> (PUP-10617) Resolve server_list using puppetserver service

acceptance/tests/ticket_1334_clientbucket_corrupted.rb, acceptance/tests/ticket_6541_invalid_filebucket_files.rb, lib/puppet/type/file.rb, spec/unit/type/file/content_spec.rb, spec/unit/type/file_spec.rb, spec/unit/util/backups_spec.rb
Previously puppet stored a copy of any file it overwrote or deleted in
its local filebucket. However, the local filebucket grows unbounded over
time and a cron job or tidy resource must be used to free old files.
Change the `backup` parameter's default value to false. The old behavior
can be reenabled by adding a resource default:
File { backup => 'puppet' }
=> (PUP-9407) Disable filebuckets by default

lib/puppet/transaction.rb, spec/unit/transaction_spec.rb
Previously, if prefetch raised `LoadError` or `Puppet::MissingCommand`, then it never marked the resources associated with the providers' type as failed. Similarly, if prefetch raised `StandardError`, then it never marked the resources as failed when `Puppet[:future_features]` was false (default). As a result, the overall transaction status would be "failure", but there wouldn't be any resource status events in the report for what the failure was.
Now we consistently mark resources as failed if `LoadError` or `StandardError` are raised. As a result of this change, if a provider's prefetch raises `LoadError` or `Puppet::MissingCommand`, then the provider will not be called later to create resources, since those exceptions indicate a provider dependency is missing, so there's no point in …
=> (PUP-9405) Mark resources as failed if prefetch fails

benchmarks/hiera_env_lookup/benchmarker.rb, benchmarks/hiera_global_lookup/benchmarker.rb, lib/puppet/pops/types/p_type_set_type.rb
Update `hiera_env_lookup` and `hiera_global_lookup` benchmarks to hiera 5, add a nested hash to the hiera data with 100 elements. Dig into the innermost hash 100 times.
Short-circuit TypeSetType reference to avoid performing type inference on the entire hash.
This doesn't solve the issue where type inference is performed on each level of the hash, so if there are N levels, then type inference is performed N times.
The global lookup benchmark for each commit:
```
$ git rebase -i 8032ed3031 --exec 'git rev-parse HEAD && bundle exec rake benchmark:hiera_global_lookup ITERATIONS=5'
Executing: git rev-parse HEAD && bundle exec rake benchmark:hiera_global_lookup ITERATIONS=5
898804a373b77486517fa421332fc359feedb682
mkdir -p /var/folders/8m/d6146zxd6bv_3h8y4ykvvxh40000gn/T/hiera_global_lookup2020 …
```
=> (PUP-10628) Short circuit TypeSetType inference

lib/puppet/http/resolver/server_list.rb, lib/puppet/http/service/puppetserver.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/service/puppetserver_spec.rb
Commit 01f72c395cd1 modified the resolver so it no longer passed the SSLContext
through to the HTTP client. This was ok if the client had completed SSL
initialization previously. But if called during `puppet ssl bootstrap`, then
the client would attempt to load the default SSLContext and fail, since the CA
cert hadn't been retrieved yet.
=> (PUP-10617) Thread ssl_context through when resolving server list

lib/puppet/defaults.rb, spec/unit/configurer/downloader_spec.rb, spec/unit/configurer_spec.rb
If `ignore_plugin_errors` is true(default value before this commit),
puppet agents can fail to pluginsync and will be missing facts/types/providers
that may be needed to request and apply the catalog.
For example, missing custom/external facts can change which classes are
included in the catalog or cause compilation failures if the manifests
references the missing fact
=> (PUP-10598) Change default value of ignore_plugin_errors to false

lib/puppet/pops/types/p_meta_type.rb, lib/puppet/pops/types/p_type_set_type.rb, spec/shared_contexts/types_setup.rb
Check that the object passed to `PTypeSetType#instance?` is an instance of
`PTypeSetType` or subclass, instead of a `Hash` with a pcore_uri key. This
redoes the change from commit 786e8b366.
The `PTypeType#instance?` method already checks for specific classes, so doesn't
cause full type inference of a Hash.
Add the `PTypeType` and `PTypeSetType` to the list of rich data compatible
classes, so they are tested in the type calculator specs. Those classes
correspond to the `Type` and `TypeSet` in the `RichData` alias.
=> (PUP-10628) Check for an instance of PTypeSetType

acceptance/tests/agent/last_run_summary_report.rb, acceptance/tests/windows/PUP-9719_windows_system_first_pa_run.rb, install.rb, lib/puppet/defaults.rb, lib/puppet/reference/configuration.rb, lib/puppet/settings.rb, lib/puppet/test/test_helper.rb, lib/puppet/util/run_mode.rb, spec/lib/puppet_spec/settings.rb, spec/spec_helper.rb, spec/unit/util/run_mode_spec.rb
Before this commit, the `last_run_summary.yaml` report file (automatically generated after an agent run) was located in `/opt/puppetlabs/puppet/cache/state` on Linux and `C:\ProgramData\PuppetLabs\puppet\cache\state` on Microsoft Windows which isn't accessible by any user since it can sometimes contain other files with sensitive data in them. The `last_run_summary.yaml` does not contain such information.
This commit adds the `public` folder (full path being `/opt/puppetlabs/puppet/public` on Linux and `C:\ProgramData\PuppetLabs\puppet\public` on Microsoft Windows) with `0755`(rwxr-xr-x) permissions and changes the `last_run_summary.yaml` file default path inside it for public access. Similar files can easily be moved here in the future. The folder's existence is ensured after installation …
=> (PUP-10627) Makes last_run_summary.yaml readable for regular users

acceptance/tests/provider/package/puppetserver_gem.rb, lib/puppet/provider/package/puppetserver_gem.rb, spec/fixtures/unit/provider/package/puppetserver_gem/gem-list-local-packages, spec/unit/provider/package/openbsd_spec.rb, spec/unit/provider/package/puppetserver_gem_spec.rb
The puppetserver_gem package provider is currently available through the
puppetlabs-puppetserver_gem module.[1]
Pull the provider into core puppet, as decided in the ticket.
In addition to this, fix some Lint/AssignmentInCondition rubocop offsenses and
make the `self.execute_rubygems_list_command` private.
Add spec and acceptance tests.
[1] https://forge.puppet.com/puppetlabs/puppetserver_gem
=> (PUP-10604) Include puppetserver_gem in core puppet

acceptance/tests/agent/last_run_summary_report.rb
The `last_run_summary_report.rb` acceptance test needs to be skipped on Windows machines in Japanese due to malformed output.
Error found:
`Expected /None:\(R\)/ to match "...PC-NAME\\Ȃ:(R)\n..."`
=> (maint) Skip 'last_run_summary_report.rb' test on Japanese Windows

lib/puppet/provider/package/pip2.rb, spec/unit/provider/package/pip2_spec.rb
Fresh pull request for master branch per comment https://github.com/puppetlabs/puppet/pull/8300#issuecomment-686322452
=> (PUP-7526) Adds pip2 provider

lib/puppet/provider/package/puppetserver_gem.rb
Puppetserver still loads all types and providers during catalog compilation,
and JRuby with FIPS enabled cannot require rubygems. So guard the require
statement like we do in puppet/ssl/openssl_loader.
The `/opt/puppetlabs/bin/puppetserver gem install` command will fail
when running with JRuby with FIPS, so confine the provider when
`fips_enabled` is false. That way trying to manage a puppetserver gem
will print:
Error: /Stage[main]/Main/Package[uuid]: Provider puppetserver_gem is not functional on this host
instead of:
Error: Execution of '/opt/puppetlabs/bin/puppetserver gem install --no-document <gem>' returned 1:
ERROR:  Loading command: install (NameError)
cannot load (ext) (org.jruby.ext.openssl.OpenSSL)
=> (PUP-10604) Guard against JRuby FIPS

lib/puppet/defaults.rb, spec/unit/configurer/downloader_spec.rb, spec/unit/configurer_spec.rb
This reverts commit 2ec586ee80466f04273a8d4972387a5cdeaead7d, reversing
changes made to 8427686c0fd6c0f994e202a378263a0d5f565e96.
The following tests are failing in puppetserver CI, because the agent no longer falls back to its cached catalog if pluginsync fails:
```
$ export GEM_SOURCE=https://artifactory.delivery.puppetlabs.net/artifactory/api/gems/rubygems/
$ bx rake ci:test:aio TESTS=tests/environment/environment_scenario-bad.rb SHA=05976d1e8992c60316ced4290b9f919a0b933938 SERVER_VERSION=7.0.0.SNAPSHOT.2020.09.08T1653 TEST_TARGET=redhat7-64a OPTIONS='--preserve-hosts=always'
...
$ bx beaker exec tests/report/cached_catalog_status_in_report.rb
...
```
I went ahead and reverted this as we'll need to fix PUP-1763 in 5.5.x and then switch the default value in 7, and didn't want to block …
=> Revert "Merge pull request #8305 from ciprianbadescu/PUP-10598/ignore_plugin_errors

acceptance/tests/parser_functions/no_exception_in_reduce_with_bignum.rb, lib/puppet/http/factory.rb, lib/puppet/pops/model/model_label_provider.rb, lib/puppet/util/monkey_patches.rb, lib/puppet/util/retry_action.rb, lib/puppet/util/windows/eventlog.rb, spec/unit/file_bucket/file_spec.rb, spec/unit/functions/camelcase_spec.rb, spec/unit/functions/capitalize_spec.rb, spec/unit/functions/downcase_spec.rb, spec/unit/functions/upcase_spec.rb, spec/unit/http/factory_spec.rb, spec/unit/pops/evaluator/evaluating_parser_spec.rb, spec/unit/pops/serialization/to_from_hr_spec.rb, spec/unit/pops/types/type_calculator_spec.rb, spec/unit/pops/types/type_factory_spec.rb, spec/unit/pops/visitor_spec.rb, spec/unit/settings/http_extra_headers_spec.rb, spec/unit/type/file/ensure_spec.rb, spec/unit/type/file/mode_spec.rb, spec/unit/util/monkey_patches_spec.rb, spec/unit/util/run_mode_spec.rb, spec/unit/util_spec.rb
Drop distinction between Bignum and Fixnum (they were unified as Integer in 2.4), remove some monkey patches and conditional spec logic.
=> (PUP-10509) Drop support for Ruby < 2.5

lib/puppet/pops/evaluator/evaluator_impl.rb, lib/puppet/pops/model/ast.pp, lib/puppet/pops/model/ast.rb, lib/puppet/pops/model/factory.rb, lib/puppet/pops/model/model_tree_dumper.rb, lib/puppet/pops/model/pn_transformer.rb, lib/puppet/pops/types/type_parser.rb
Commit caced6b59 changed how location information within a heredoc string was
calculated. As a result, the SubLocatedExpression AST class is no longer used.
This commit removes the class.
=> (PUP-9309) Remove SubLocatedExpression

acceptance/tests/resource/file/content_attribute.rb, lib/puppet/application/filebucket.rb, lib/puppet/defaults.rb, lib/puppet/file_serving/http_metadata.rb, lib/puppet/http/service/compiler.rb, lib/puppet/http/service/file_server.rb, lib/puppet/type/file/checksum.rb, spec/integration/application/agent_spec.rb, spec/integration/application/apply_spec.rb, spec/integration/application/filebucket_spec.rb, spec/integration/type/file_spec.rb, spec/unit/application/filebucket_spec.rb, spec/unit/configurer_spec.rb, spec/unit/defaults_spec.rb, spec/unit/http/service/file_server_spec.rb, spec/unit/indirector/file_bucket_file/file_spec.rb, spec/unit/transaction/resource_harness_spec.rb, spec/unit/type/file/checksum_spec.rb, spec/unit/type/file_spec.rb
Puppet's `digest_algorithm` setting defaults to `md5`, which is outdated. This commit switches it to to `sha256`.
Update spec tests accordingly.
=> (PUP-10583) Change default digest_algorithm to SHA256

spec/unit/file_serving/configuration/parser_spec.rb
The file server's config parser should successfully parse the mounts while
ignoring the allow and deny rules.
=> (PUP-10473) Expect fileserver config parser to return mounts

lib/puppet/functions/new.rb
Casting between Puppet Data Types, such as `Integer("9")`, will cause
Puppet Server to retain `Puppet::Parser::Catalog` objects in memory
after requests finish.
This is caused by two issues in the `new_function_for_type` method:
- The cache is a Hash instance with a lambda function that creates
constructor functions as they are requested. This lambda closes over
the Compiler scope value passed the first time `new()` is called, which
keeps that scope in memory.
- The Compiler `scope` value passed the first time new() is called is
further passed into the constructor function when it is created. The
function then stores it as a local variable.[1]
Refactor the `new_function_for_type` method to pass `nil` instead of
`scope` when creating the constructor function. The functions will fall
back …
=> (PUP-10659) Fix Data Type casting causing memory leaks in Puppet Server

lib/puppet/indirector/rest.rb, spec/unit/indirector/rest_spec.rb
If the `Content-Type` response header is missing or is not PSON/JSON, then
return the response body instead of calling the non-existent method
`uncompress_body`, which was removed in commit ca36093. The HTTP client is
responsible for decompressing the response instead of the caller having to do
that.
=> (PUP-10661) Don't call nonexistent uncompress_body method

lib/puppet/http/resolver.rb, lib/puppet/http/resolver/server_list.rb, lib/puppet/http/resolver/settings.rb, lib/puppet/http/resolver/srv.rb, lib/puppet/http/session.rb, spec/integration/application/agent_spec.rb, spec/unit/configurer_spec.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/session_spec.rb
Previously, the server list resolver collected exceptions that occurred during
resolution. Now we log the exceptions at error level as they occur, which
eliminates the need for the `error_handler`.
The server list resolver also used to raise an error if the list was exhausted,
but that prevented the collected exceptions above from being logged at error
level. Now the server list resolver uses the `canceled_handler` to cancel
resolution (instead of raising) and its resolve method returns nil like other
resolvers.
The integration test relied on enabling debug for server_list tests. When that
is removed, it causes puppet to print the error to stderr instead of stdout.
=> (PUP-10664) Log server_list exceptions as they occur

lib/puppet/pops/evaluator/collectors/abstract_collector.rb, lib/puppet/resource/type.rb
Use of a resource collector with an override block will cause Puppet
Server to retain `Puppet::Parser::Catalog` objects in memory after
requests finish.
The leak is caused by Resource Collector overriding the `child_of`
methods on the resources it operates on to always return `true`. This
forces the collector overrides to be merged in later by short-circuiting
the logic in `Puppet::Parser::Resource` that only accepts overrides from a
parent scope.[1][2]
Using `meta_def` to override a method results in the creation of a Ruby
"eigenclass" to hold the new method definition. The body of the method,
which accepts `klass` and always returns `true`, is provided by a Ruby
block. This block is an instance of a `Proc`, which means that it closes
over all variables that happen to be in scope. One of …
=> (PUP-10657) Fix resource collector override leak

lib/puppet/configurer.rb, spec/integration/configurer_spec.rb, spec/unit/configurer_spec.rb
In case pluginsync fails and `ignore_plugin_errors` is `false`, puppet should
apply cached catalog if `usecacheonfailure` is `true`
=> (PUP-10667) consider `usecacheonfailure` when pluginsync fails

lib/puppet/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
Before this commit, there's no indication of the current package
version when package resource is configured with latest, even
when running puppet agent with the debug flag,
After this commit a debug message with current version will be shown
if no upgrade upgrade is available.
```
Debug: Package[rsync](provider=yum): Yum didn't find updates, current version(3.1.2-10.el7) is the latest.
```
=> (PUP-7791) add debug message when using latest packages

api/schemas/report.json, lib/puppet/configurer.rb, lib/puppet/transaction/report.rb
Schema was incremented because new value was added for the `cached_catalog_status` report field:
`on_pluginsync_failure` to be used when a cached catalog was used because the usecacheonfailure setting was set and the pluginsync failed while having ignore_plugin_errors set to false
=> (Maint) fix rubocop and update report schema

acceptance/tests/lookup/lookup.rb
Test adaptation was needed following site resource removal from
https://github.com/puppetlabs/puppet/pull/8316
=> (PUP-10680) update lookup test following site resource removal

lib/puppet/defaults.rb, spec/unit/configurer/downloader_spec.rb, spec/unit/configurer_spec.rb
If `ignore_plugin_errors` is true(default value before this commit),
puppet agents can fail to pluginsync and will be missing facts/types/providers
that may be needed to request and apply the catalog.
For example, missing custom/external facts can change which classes are
included in the catalog or cause compilation failures if the manifests
references the missing fact
=> (PUP-10598) Change default value of `ignore_plugin_errors` to false

spec/integration/util/windows/adsi_spec.rb, spec/unit/file_system_spec.rb, spec/unit/provider/exec_spec.rb
the following tests have been updated
- spec/integration/util/windows/adsi_spec.rb:34
Was making the assumption that `Administrator` user
is present. Changed to `Guest` since `Administrator`
is not available in all setups.
- spec/unit/file_system_spec.rb:870
`Puppet::FileSystem.expand_path` expands relative
to the drive that Puppet is executed from. The
expect here was making the assumption that Puppet
tests are run form `SystemDrive` which is not always
the case. Updated the test to match that the expanded path
starts with a drive letter.
- spec/unit/provider/exec_spec.rb
ENV['PATH'] is not correctly handled by Ruby. Use
Pathname.cleanpath no normalize the path that is
used in the `exec` resource
=> (PUP-10640) make tests more reliable

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml
I cherrypicked commit https://github.com/puppetlabs/puppet/pull/8352/commits/9c60d3e232cf61fb9d6578b1912ad1664d80cbae and resolved conflicts. It's a bit clearer that 2.3/2.4 are removed, 2.7 is added on windows, and the branch names changed.
=> (PUP-10640) setup github actions for main branch

lib/puppet/face/facts.rb, lib/puppet/indirector/facts/facter.rb, spec/unit/face/facts_spec.rb, spec/unit/indirector/facts/facter_spec.rb
This PR adds a new action for puppet facts _(puppet facts show)_. This action is more configurable (supports all the arguments that facter does, and can be called to retrieve only a fact or a list of facts).
Depends on: [FACT-2774](https://github.com/puppetlabs/facter/pull/2054)
=> (PUP-10644) Add show action for puppet facts

lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/puppet_gem.rb, spec/unit/provider/package/gem_spec.rb, spec/unit/provider/package/puppet_gem_spec.rb
Because `INSTALL_DIR/puppet/bin` is prepended to PATH,
gem provider always uses Puppet's Ruby.
This commit changes the gem provider to execute commands
in a specific environment that has a PATH which does not
contain `puppet/bin`.
It also updates the puppet_gem provider to use
the full path for the Puppet's gem executable
=> (PUP-10677) gem provider uses system ruby

lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/integration/parser/catalog_spec.rb, spec/unit/parser/functions/create_resources_spec.rb, spec/unit/pops/validator/validator_spec.rb
Previously puppet would warn or error if it encountered a virtual
class (indicated by `@class`) or an exported class (indicated by `@@class`)
based on the `Puppet[:strict]` setting. By default, puppet would warn, yet
include resources from the virtual class in the catalog. So the resources in the
virtual class weren't virtual! Also note, it wasn't possible to turn off the
warning.
This commit makes puppet always error on virtual and exported classes. The
validator_factory_4_0.rb validates static resource expressions, while
runtime3_support validates `create_resources` calls, which can be used to create
resources at runtime, so we need to prevent things like:
create_resources('@class', {})
The integration tests are removed since we already test for validation errors in
unit tests.
=> (PUP-7582) Error on virtual and exported classes

acceptance/tests/language/exported_resources.rb, lib/puppet/application/doc.rb, lib/puppet/application/lookup.rb, lib/puppet/face/catalog.rb, lib/puppet/face/node.rb, lib/puppet/face/node/clean.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/indirector/facts/yaml.rb, lib/puppet/indirector/json.rb, lib/puppet/indirector/msgpack.rb, lib/puppet/indirector/yaml.rb, lib/puppet/pops/evaluator/runtime3_converter.rb, lib/puppet/settings.rb, lib/puppet/util/run_mode.rb, spec/unit/application/doc_spec.rb, spec/unit/application_spec.rb, spec/unit/face/node_spec.rb, spec/unit/indirector/catalog/json_spec.rb, spec/unit/indirector/json_spec.rb, spec/unit/indirector/msgpack_spec.rb, spec/unit/indirector/yaml_spec.rb, spec/unit/settings_spec.rb, spec/unit/util/run_mode_spec.rb
Add "server" run mode that behaves like "master"
It should be possible to set the run mode (eg in an external application) using the "server" or "master" run mode.
Update applications in puppet to use the "server" run mode as needed, such as "puppet lookup".
=> (PUP-10671) Add `server` run mode and alias

api/schemas/report.json, lib/puppet/configurer.rb, lib/puppet/transaction/report.rb, spec/integration/configurer_spec.rb, spec/unit/configurer_spec.rb
While fixing `ignore_plugin_errors`/`usecacheonfailure` interaction
a new specific value was added for cached_catalog_status. This new
value does not bring enough benefit vs complexity, reverting to
using generic `on_failure` value
=> (maint) revert schema increment and new value added to cached_catalog_status

api/schemas/report.json, lib/puppet/configurer.rb, lib/puppet/transaction/report.rb, spec/integration/configurer_spec.rb, spec/unit/configurer_spec.rb
While fixing `ignore_plugin_errors`/`usecacheonfailure` interaction
a new specific value was added for cached_catalog_status. This new
value does not bring enough benefit vs complexity, reverting to
using generic `on_failure` value
5.5.x PR: https://github.com/puppetlabs/puppet/pull/8362
=> (maint) revert schema increment and new value added to cached_catalog_status (cherry-pick from 5.5.x)

acceptance/tests/environment/environment_scenario-bad.rb
Prior to PUP-10598, puppet would ignore the pluginsync errors due to the
non-existent environment on the server and would fail when trying to request a
catalog.
As of PUP-10598, puppet will fail on the first pluginsync error, so the error
message is different. The overall behavior is similar though. The cached catalog
is ignored since `puppet agent --test` implies `--no-usecacheonfailure`.
=> (PUP-10598) Update expectation when puppet agent fails

lib/puppet/defaults.rb, lib/puppet/settings.rb, spec/unit/settings_spec.rb
This commit adds a new setting `settings_catalog`
which defaults to `true`. This settings can is used
to configuer if Puppet will compile and apply the
settings catalog when `Puppet.settings.use(*sections)`
is used.
=> (PUP-8682) Allow disabling of settings catalog

lib/puppet/node/facts.rb, spec/unit/application/facts_spec.rb
**Description of the problem:** `puppet facts --render-as yaml` outputs mac addresses unquoted.
If your mac address doesn't contain any chars A-F this is a problem as other tools parsing the resulted yaml will interpret the value as a sexagesimal (base 60) integer.
**Description of the fix:** use Psych to double quote any string that contains the `:` character (this affects macaddress, any date/time and ipv6 style values).
=> (PUP-9505) Quote facts that contain special string

lib/puppet/settings.rb, spec/unit/settings_spec.rb
Puppet adds a section to its searchpath based on the run mode. This is what enables puppetserver running in `:master` run mode to load settings from the `[master]` section. As a result of the switch to `:server` run
mode, then applications running in server run mode, like `puppet lookup`, will no longer read settings from `[master]`.
If our run mode is `:server` or `:master`, add sections for both, in that order, so that `:server` takes precedence over `:master`.
Add `server` as an allowed section name to be able to test this change, and update the remaining `master` run mode tests to use `server`.
=> (PUP-10671) Update setting section search path

lib/puppet/defaults.rb, lib/puppet/environments.rb, lib/puppet/network/http/api/master/v3/environments.rb, spec/unit/environments_spec.rb, spec/unit/network/http/api/master/v3/environments_spec.rb
This adds a new puppet setting `Puppet[:environment_ttl]` which is similar to the deprecated `Puppet[:environment_timeout]` except the former computes the expiration time as N seconds since the environment was last accessed, while the latter computes it relative to when the environment was created. This way heavily used environments will be cached, but onetime "dev" environments will not.
The `Puppet[:environment_ttl]` setting is global and cannot be set in `environment.conf`. Puppet will use the `Puppet[:environment_ttl]` setting if it is explicitly configured, otherwise it will fallback to using `Puppet[:timeout]`.
If `Puppet[:environment_ttl]` is set, then environments can still be evicted using the [environment-cache REST API](https://puppet.com/docs/puppetserver/5.3/admin-api/v1/envir …
=> (PUP-8014) Cache actively used environments

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
In case no server from `server_list` is available and `usecacheonfailure`
is set to `true`, skip pluginsync and use cached catalog
=> (PUP-10648) consider usecacheonfailure when using server_list

lib/puppet/network/authorization.rb, lib/puppet/network/http/api/master/v3.rb, spec/unit/network/http/api/indirected_routes_spec.rb, spec/unit/network/http/api/master/v3_spec.rb, spec/unit/network/http/api_spec.rb, spec/unit/network/http/handler_spec.rb
Verify puppetserver registered its authconfigloader class, which indicates it
will authorize REST requests. If it fails to do so, either due to
misconfiguration or bug, then return HTTP Unauthorized (401) for all v3 REST
endpoints so we fail securely.
Note when legacy routes was enabled (in 6.x) indirected routes performed the
authorization check within its `indirection2uri` method. But here we do the
check before the route is called, since we just need to know the request method
and path to format the error message.
=> (PUP-10473) Verify puppetserver registers its authconfigloader

lib/puppet/defaults.rb, lib/puppet/environments.rb, lib/puppet/network/http/api/master/v3/environments.rb, spec/unit/environments_spec.rb, spec/unit/network/http/api/master/v3/environments_spec.rb
The `environment_ttl` setting was added to replace `environment_timeout`, but
having two settings complicates the upgrade process for the common case where
the timeout is set to 'unlimited'. If we naively upgrade, then puppet server
will switch from always cache to never cache, due to the default value of
`environment_ttl=0`.
This commit preserves the existing behavior of `environment_timeout` when the
value is `0` or `unlimited`.
Otherwise, the `environment_timeout` value is the time to live relative to when
the environment was created or last used. The `environment_timeout_mode` setting
defaults to `from_created`, but can be set to `from_last_used`.
=> (PUP-8014) Add environment_timeout_mode

lib/puppet/http/service/puppetserver.rb, spec/integration/application/agent_spec.rb, spec/lib/puppet_spec/puppetserver.rb, spec/unit/application/filebucket_spec.rb, spec/unit/configurer_spec.rb, spec/unit/http/resolver_spec.rb, spec/unit/http/service/puppetserver_spec.rb, spec/unit/http/session_spec.rb
This commit updates the path of simple server status
to `/status/v1/simple/server`. If this returns 404
it calls `/status/v1/simple/server` to ensure
backwards compatibility.
=> (PUP-10673) Call simple server status endpoint

spec/unit/configurer_spec.rb
Commit 139b5e93a2b added a test that stubbed the old API, but the configurer was
modified in 8112327d45 to call the simple server service instead. Update the
test to match the code.
=> (maint) Update test to stub /status/v1/simple/server

acceptance/tests/direct_puppet/static_catalog_env_control.rb, acceptance/tests/environment/use_enc_environment_for_files.rb, acceptance/tests/environment/variables_refreshed_each_compilation.rb, acceptance/tests/lookup/lookup.rb, lib/puppet/defaults.rb, lib/puppet/environments.rb, spec/unit/environments_spec.rb
Remove `environment_timeout_mode` setting and change default behavior to `from_last_used`.
There is no change in behavior if `environment_timeout` is `0` or `unlimited`.
Otherwise, evict environments if not used within the last `environment_timeout` seconds. Also remove deprecation warning, since the setting now works as expected.
=> (PUP-10619) Evict environments based on last used time

.github/workflows/rspec_tests.yaml
Due to having all GitHub Actions jobs marked as required in the repository's GitHub Branch settings, we always had pull requests with stuck jobs waiting to be run when there were no code changes (no changes at all in cases like merge ups or only in `**.md` or `docs/*` or `examples/*` or `ext/*` or `benchmarks/*` files). Workaround for this was to have someone with enough rights on the repository to forcefully merge the pull request.
Example of stuck pull request: https://github.com/puppetlabs/puppet/pull/8392
This seemed the most detailed discussion regarding this topic in the GitHub Community: https://github.community/t/status-check-with-path-filter/18049
This commit makes all the jobs run always even if the files added/modified in the pull request can't impact the code in any way. …
=> (maint) Remove ignored paths from GitHub Actions

lib/puppet/indirector/facts/facter.rb, spec/unit/indirector/facts/facter_spec.rb
When using `puppet facts show` puppet appends local facts to result. This is not desirable, `puppet facts show` supports custom user queries, for example `puppet facts show os` should only show `os` fact, but because of the append, it will show the local facts as well.
The PR excludes local facts when `puppet facts show` is called.
=> (PUP-10717) Puppet should not append facts to facter results

lib/puppet/util/rubygems.rb, spec/unit/util/rubygems_spec.rb
Puppet calls `Puppet::Util::RubyGems::Source#directories` to get a list of
candidate paths for the autoloader, so that we can load types, features, etc
from gems, see commit 2a12fdd5c. However, `Gem::Specification.latest_specs`
parses the full gemspec, returning `Gem::Specification` objects.
The `Gem::Specification.stubs` method only parses the "stub line" in the
gemspec, for example:
And returns `Gem::StubSpecification` objects. Calling the `stubs` method is
about 6.7 times faster than `latest_specs` when running from packages, i.e. not
bundler.
The `stubs` method also preserves the behavior of returning pre-release gems, as
the pre-release filtering happens when converting stubs to full specs.
Doing so also fixes a strange puppet/rubygems bug whereby `Kernel.require` can
fail to load a …
=> (PUP-10719) Collect gem directories from Gem::StubSpecifications

acceptance/tests/reports/failover_master.rb
As part of our harmful terminology removal, we are replacing the use of
`master` with `server`. This commit updates our acceptance test to
accomodate that change.
=> (maint) Fix logged error match

lib/puppet/settings.rb, spec/unit/settings_spec.rb
PUP-10670 introduced the `serverport` alias for `masterport` and changed Puppet to use it internally instead of `masterport`.
This introduced the following change in behaviour:
- when setting `masterport` in any section different than `main`(eg. agent), this is ignored and the default `serverport` value is used.
- users that have `masterport` set in their configuration, in a different section than `main`(eg. agent), are also affected as Puppet
will not pick up the value set for `masterport` and it will use the default `serverport` value.
This is due to the setting hooks not being called when they are set in sections other than `main`.
In addition to the setting hooks, check and set masterport and serverport when `initialize_app_defaults` is called, if required.
=> (PUP-10722) Fix masterport not honored

lib/puppet/defaults.rb, lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/unit/pops/loaders/loaders_spec.rb
Remove func3x_check setting which made it possible to disable 3x function
checking and stray single quote in the exception message.
Preserve the "illegal function is loaded" test to show the behavior when an
invalid 3x function is loaded.
=> (PUP-9469) Remove func3x_check setting

lib/puppet/settings.rb, spec/unit/settings_spec.rb
* 6.19.1_release:
(PUP-10722) Fix masterport not honored
(packaging) Bump to version '6.19.1' [no-promote]
Conflicts (pick master version):
.gemspec
lib/puppet/version.rb
=> Merge 6.19.1_release to master

lib/puppet/http/client.rb
The `execute_request` method always ensures the response body is drained so it's
not necessary to call `response.body` in cases where we're not streaming the
response. It also avoids confusion as to whether `execute_request` returns the
response body or the request.
=> (maint) Refactor response body reading

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
The setting will be removed in puppet 7, so deprecate setting it to false in 6.x
=> (PUP-10724) Issue a deprecation warning if func3x_check is disabled

lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb
**Description of the problem:** when `puppet facts show` action is called without indicating the render, the default render is `json` which is not pretty printed.
**Description of the fix:** The default render should be `console` (the default for `find` action) and in order to display the facts as a pretty json a new method (when_rendering :console) was implemented.
=> (PUP-10716) Fix show action output formatting

lib/puppet/face/epp.rb, lib/puppet/functions/epp.rb, lib/puppet/functions/inline_epp.rb, lib/puppet/pops/evaluator/evaluator_impl.rb, spec/unit/functions/inline_epp_spec.rb
If an EPP template contains a Sensitive data type, then join the unwrapped
value, but wrap the entire result as Sensitive. This way the underlying
sensitive value is preserved, and the caller can access it by unwrapping the
entire result. Previously, the result was always a string and contained the
generic 'Sensitive [redacted]' message, so the underlying sensitive value was
lost.
Update the `epp` and `inline_epp` function signatures, since they can both
return either String or Sensitive[String].
Update the `epp` application to unwrap sensitive values produced by the above
functions.
=> (PUP-8969) Preserve sensitiveness of epp templates

lib/puppet/indirector/fact_search.rb, lib/puppet/indirector/facts/json.rb, lib/puppet/indirector/facts/yaml.rb, lib/puppet/indirector/json.rb, spec/unit/indirector/facts/json_spec.rb
We have a YAML terminus for facts, however YAML can problematic for hexidecimal numbers (see PUP-9505).
Additionally, JSON is generally a better serialization format for machines to understand, is a smaller spec than YAML, has a relatively mature ecosystem in Java around parsing/serializing, and is backwards compatible with YAML for recent YAML parsers (YAML has become a superset of JSON).
For these reasons we should implement a JSON terminus for facts (there already exists one for catalogs) and users should be encouraged to use it instead of the YAML terminus.
Original PR: #8287 
node and report json terminus added in #8398
=> (PUP-10656) Provide a JSON fact terminus

Gemfile
There is a regression with keyword args[1], exclude that version.
https://github.com/rspec/rspec-expectations/issues/1221
=> (maint) Exclude rspec-expectations 3.9.3

Gemfile, lib/puppet/face/epp.rb, lib/puppet/functions/epp.rb, lib/puppet/functions/inline_epp.rb, lib/puppet/pops/evaluator/evaluator_impl.rb, lib/puppet/settings.rb, spec/unit/defaults_spec.rb, spec/unit/functions/inline_epp_spec.rb, spec/unit/settings_spec.rb
* upstream/master:
(PUP-10724) Issue a deprecation warning if func3x_check is disabled
(PUP-10722) Fix masterport not honored
(packaging) Bump to version '6.19.1' [no-promote]
(PUP-8969) Preserve sensitiveness of epp templates
Conflicts:
lib/puppet/defaults.rb
spec/unit/defaults_spec.rb
facterng and func3x_check settings were removed in main. Keep test from master
which asserts settings don't raise deprecation warnings by default.
=> (maint) Merge master to main

lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb
Make `show` action the default action for `puppet facts` application. Previously, the default one was the `find` action.
=> (PUP-10715) Show action default for puppet facts

lib/puppet/defaults.rb, lib/puppet/settings/base_setting.rb, spec/integration/environments/setting_hooks_spec.rb, spec/lib/puppet_spec/settings.rb, spec/unit/settings_spec.rb
If a setting is set or overridden in a section other than `main` and the section matches the application's run_mode, then puppet will use the value, but only call the setting's hook if it's of type `:on_initialize_and_write`. This explains why specifying a `certname` containing uppercase letters in the `main` section wasn't rejected as expected. This changes the `certname` setting's hook to `:on_initialize_and_write` and adds tests.
=> (PUP-9481) Validate certname in sections other than main

lib/puppet/pops/validation/checker4_0.rb, spec/unit/pops/validator/validator_spec.rb
The checker class validates the AST produced by the puppet parser, but was
missing some type names. As a result of this change, a class or defined type in
top scope can no longer be named 'init', 'object', etc. Classes or defined types
in other scopes will still work, e.g. `mymodule::object`.
=> (PUP-7843) Reserve missing type names

lib/puppet/defaults.rb, lib/puppet/indirector/report/json.rb, lib/puppet/indirector/report/yaml.rb, spec/unit/indirector/report/json_spec.rb, spec/unit/indirector/report/yaml_spec.rb
The implementation in https://github.com/puppetlabs/puppet/pull/8398
used Puppet::Util.replace_file which is an old implementation to the new
Puppet::FileSystem.replace_file
Replaced Puppet::Util.replace_file with Puppet::FileSystem.replace_file
and updated the specs.
=> (PUP-10712) Json terminus for node and report fix

lib/puppet/defaults.rb, lib/puppet/settings.rb, lib/puppet/settings/integer_setting.rb, lib/puppet/settings/port_setting.rb, spec/integration/defaults_spec.rb, spec/unit/settings/integer_setting_spec.rb, spec/unit/settings/port_setting_spec.rb
This is just a POC. As some setting types were quite specific I decided to implement a `PortSetting` type instead of `IntegerSetting`. On second thought, it would also make sense to have both, and have `PortSetting` inherit from `IntegerSetting`, as there might be cases in the future where we just want to ensure a setting is a valid integer.
Note that we also have the `:ca_port` and `:report_port` settings initialized the same way, which I have not yet changed, but I think they should be the same for consistency.
Thoughts? This change can also be considered breaking in a way, as the setting is now an integer (internally at least, the user can still set it to a string in puppet.conf if they want).
=> (PUP-10711) Add `:port` and `:integer` setting types and update defaults

lib/puppet/http.rb, lib/puppet/http/client.rb, lib/puppet/http/external_client.rb, lib/puppet/http/response.rb, lib/puppet/http/response_converter.rb, lib/puppet/http/response_net_http.rb, lib/puppet/indirector/catalog/rest.rb, lib/puppet/indirector/facts/rest.rb, lib/puppet/indirector/file_bucket_file/rest.rb, lib/puppet/indirector/file_content/rest.rb, lib/puppet/indirector/file_metadata/rest.rb, lib/puppet/indirector/node/rest.rb, lib/puppet/indirector/report/rest.rb, lib/puppet/indirector/rest.rb, lib/puppet/network/http/connection.rb, lib/puppet/type/file/source.rb, spec/unit/http/client_spec.rb, spec/unit/http/external_client_spec.rb, spec/unit/http/session_spec.rb, spec/unit/indirector/report/rest_spec.rb, spec/unit/indirector/rest_spec.rb
Previously puppet's legacy connection adapter assumed the http client implementation returned instances of `Puppet::HTTP::Response` that wrapped `Net::HTTPResponse`. But that isn't true when running in puppetserver.
Now the legacy connection adapter converts `Puppet::HTTP::Response` instances (returned by the new http client implementation) to `Net::HTTPResponse`. This makes it possible for report processors, rest termini and server functions that call the legacy http API to continue working in puppetserver 7.
=> (PUP-10730) Convert puppet http responses to net/http responses

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
The settings hook is called twice in one run when trying to set/unset the `facterng` flag which makes `Facter` module to not be present and puppet to raise an error.
=> (maint) Fix setting of facterng flag

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
This change updates the cadir default to warn users to run the
puppetserver ca tool to migrate the ca directory from under a
`puppet/ssl/` to the new default `puppetserver/ca` location.
=> (PUP-10720) Update cadir setting for migration warnings

lib/puppet/network/formats.rb, spec/unit/http/service/compiler_spec.rb, spec/unit/http/service_spec.rb
Previously the agent always advertised that it accepted the rich data msgpack
format (application/vnd.puppet.rich+msgpack) even if the agent didn't have the
msgpack gem installed locally. If the msgpack gem was installed on the server,
and the server selected the rich data msgpack format, then the agent would fail
to deserialize the catalog.
Now we call the `suitable?` method in the superclass so the msgpack feature
constrain is taken into account. Calling the super `supported?` method triggers
a bunch of other logic around whether or not the format implements required
methods, so avoid that.
Note the "raw" msgpack format didn't have this issue because it didn't override
the "supported?" method.
=> (PUP-10772) Only accept msgpack if gem is installed

acceptance/tests/agent/last_run_summary_report.rb, lib/puppet/defaults.rb
Due to security concerns, this commit downgrades file permissions for `last_run_summary.yaml` from `644` to `640`. This allows access only to file owner and its group (by default).
See https://github.com/puppetlabs/puppet/pull/8277 and ticket comments for more information.
=> (PUP-10627) Add default file permissions 640 for last_run_summary.yaml

lib/puppet/parser/templatewrapper.rb, spec/unit/parser/templatewrapper_spec.rb
The Scope#tags method was removed in 02576c98fa5, but the test didn't catch it
because we don't verify partial doubles. Since it's public API, keep the method
but raise an exception so it's clear what the issue is.
=> (PUP-10779) Raise not implemented error if TemplateWrapper#tags is called

lib/puppet/environments.rb, spec/unit/environments_spec.rb
The environment cache has two methods to clear a cached environment (`clear_all` and `clear(name)`) and two methods to clear expired environment(s) (`clear_all_expired` and `clear_if_expired(name)`). An environment can become expired if the environment timeout is exceeded or if it is marked as expired through the puppetserver [environment-cache REST endpoint](https://puppet.com/docs/puppetserver/5.3/admin-api/v1/environment-cache.html#delete-puppet-admin-apiv1environment-cache).
When an environment is cleared, we need to delete the environment from memory (which contains the AST for parsed puppet code), notify the cache expiration service, delete the environment-specific text domain and environment-specific settings. Prior to this PR, we didn't clear environment consistently. To remedy …
=> (PUP-10713) Ensure environment cache is consistent when entries are cleared

lib/puppet/provider/user/aix.rb, spec/fixtures/unit/provider/user/aix/aix_passwd_file.out, spec/unit/provider/user/aix_spec.rb
Prior to this commit, the aix user resource only allowed for a static
pattern when parsing the passwd file for passwords. This would cause the
resource to be continually applied if the password line had spacing that
did not align with the pattern. This commit changes the parsing to allow
for abitrary spacing in the password line.
=> (Pup-10778)  Allow whitespace in regex for AIX user password parsing

Gemfile, lib/puppet/face/node/clean.rb, spec/unit/face/node_spec.rb
Previously, the puppet node clean action called the PuppetServer CA CLI
as a library to clean certs. To do so it implemented a bridge between
the CA library's logger and Puppet's logger. That implementation only
included those methods used by the CA's clean action. However, in the
most recent version of the CA it will now also `warn` if the cadir is in
the legacy location (like Puppet proper does).
This patch implements the remaining API for the CA's logger (debug
and warn). It also filters out the warning from the CA library for a
cadir nested w/in the ssldir, as Puppet should have already warned about
that if needed.
=> (PUP-10786) Update puppet node clean for ca-cli 2

lib/puppet/util/posix.rb, spec/unit/util/posix_spec.rb
`get_posix_value` method checks if the user/group
that is added in the manifest corresponds with the
user/group retrieved from system. If they differ,
a full query is executed to retrieve all the
users/groups and match them with the required value.
This commit adds an extra check, for the case when
multiple users/groups have a same identifier(uid/gid)
In this case a full query is not needed, and the found
identifier is returned.
=> (PUP-10774) Do not query all groups/users

Gemfile, lib/puppet/ffi/posix.rb, lib/puppet/ffi/posix/constants.rb, lib/puppet/ffi/posix/functions.rb, lib/puppet/util/posix.rb, spec/unit/provider/user/pw_spec.rb, spec/unit/provider/user/useradd_spec.rb, spec/unit/util/posix_spec.rb
Due to performance issues on systems with big number of user groups, this commit adds ffi method `getgrouplist` as primary method of listing the groups of a user resource on posix. On systems without ffi, the `groups_of` method falls back to previous implementation with `Etc.groups` (which is very inefficient because it's checking all available groups for given user membership).
Gemfile now also contains `ffi` for testing purposes.
Before merging this we should have:
After completing above, we can also merge #8444 and leave a comment on internal ticket regarding this.
=> (PUP-10774) Add faster user groups query on posix

.gemspec, Gemfile, ext/project_data.yaml
Previously, puppet had a dependency on the ruby `scanf` gem when running
puppet from source, but not when running as a gem. To ensure transitive
dependencies are resolved correctly, like when running puppetlabs-puppetdb
specs against puppet as a gem, move the `scanf` dependency to
`project_data.yaml`.
Note the runtime dependency is only needed when running ruby 2.7 or up. If
running on 2.5 or 2.6, then the `scanf` gem will be ignored, so there's no
harm in including it.
=> (PUP-10797) Add runtime dependency on scanf

lib/puppet/defaults.rb, lib/puppet/face/node/clean.rb, spec/unit/defaults_spec.rb
This change stops puppet from emitting CA dir deprecation warnings,
but it still keeps the cadir defaulted to the puppetserver dir
unless it already exists within the puppet/ssl dir.
=> (PUP-10812) Remove chatty CA dir deprecation

lib/puppet/type/user.rb
Ruby 2.7 introduced a warning for checking invalid objects (such as `Integer` in our case) against a regular expression. The check in this case always returns nil even though a valid String would respect the given regular expression, resulting in the possibility of unwanted behaviour.
This commit replaces the check accordingly in the user type and keeps previous logic. Example of the removed warning:
> /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type/user.rb:468: warning: deprecated Object#=~ is called on Integer; it always returns nil
=> (PUP-10790) Fix regex warnings introduced in Ruby 2.7

.github/workflows/rspec_tests.yaml, spec/unit/util/storage_spec.rb
Running the `parallel:spec` rake task on **Windows** with **Ruby v2.5** recently started to surface a constant issue in our tests: passing with **0 failures** but always completing with **exit code 1**. Overall checks in our investigation:
- managed to reproduce the issue on Windows GitHub Actions runners (on both versions available at the moment: `windows-2016` and `windows-2019`) as well as on our own virtual machines, thus eliminating the possibility of _changes in the GitHub Actions environment_ as a root cause
- compared the version of installed gems in a failing run against a passing one from previous GitHub Actions runs but we didn't find any difference
- while using `git bisect` we didn't find any **good** commit; using a random 5 months old commit (even though the issue was first …
=> (maint) Fix parallel:spec finishing with  0 failures but exit code 1

.github/workflows/rspec_tests.yaml, lib/puppet/application_support.rb, lib/puppet/util/posix.rb, spec/unit/application_spec.rb, spec/unit/ssl/ssl_provider_spec.rb, spec/unit/util/posix_spec.rb, spec/unit/util/storage_spec.rb
This pull request backports a couple of changes from main:
- (PUP-10774) Do not query all groups/users e15685f
- (maint) Fix parallel:spec, 0 failures but exit code 1 cf16ce4
- (maint) Lock bundler version in GitHub Actions a898ffe
- (maint) Skip SSL spec when openssl >= 1.1.1h  f7b30f1eac702c7e8c6dc22b943666832e26918f
- (PUP-10773) Reroute master settings to server dee7247e90280491d42886320a1ad8589bdc3736
It also adds:
- (PUP-10821) Avoid unwanted nil id for posix user/group 1b82e79
This commit has been cherry-picked from #8451 
Changes done in #8444 caused a Puppet::DevError to be raised (in the get_posix_value method when calling the get_posix_field method) and silently catched without returning any value. Unit test failures on puppetlabs-sshkeys_core were seen due to receiving nil id …
=> (maint) Backport latest changes from main

spec/unit/ssl/ssl_provider_spec.rb
The regression[1] introduced in openssl 1.1.1h was fixed[2] upstream, so only skip the test if we're on the affected version of openssl.
OpenSSL 1.1.1i no longer exhibits this issue.
[1] https://github.com/openssl/openssl/commit/42bb51e59308b3ebc5cc1c35ff4822fba6b52d79
[2] https://github.com/openssl/openssl/pull/13585
=> (maint) Skip SSL spec only when running with openssl 1.1.1h

lib/puppet/reference/configuration.rb, spec/unit/ssl/ssl_provider_spec.rb
* commit 'de32c1e053621dee5ad3e822b8779849de7485da':
(maint) Trigger on PRs and pushes to 6.x
(DOCS) Update PE defaults note in configuration.rb
(maint) Skip SSL spec only when running with openssl 1.1.1h
Conflicts (keep ours):
.github/workflows/checks.yaml
.github/workflows/rspec_tests.yaml
=> (maint) Merge 6.x to main

.github/workflows/rspec_tests.yaml
This reverts commit a898ffe934460bce0930205e0430bdf2693ff619 since the bundler regression was recently fixed[1].
[1] https://github.com/rubygems/rubygems/commit/6a8791c6000f6a20982e37db302432ddaa3fb916
=> Revert "(maint) Lock bundler version in GitHub Actions"

lib/puppet/configurer.rb, spec/fixtures/integration/application/agent/cached_deferred_catalog.json, spec/integration/application/agent_spec.rb
Merge commit a17761d60b introduced a semantic conflict between the environment
convergence changes in 5.5.x and the deferred function support in 6.x. As a
result puppet evaluated deferred functions before caching the result. This
regression was first introduced in 6.12.0. As a result, if the agent ran
from a cached catalog, it would use the result from last time, instead of
re-evaluating the deferred function.
This commit switches the order of those operations and adds a test. We have
to use `binary_file` because `file` is a 3x function and there are issues
with 3x functions and deferred values.
=> (PUP-10818) Cache the deferred function, not its result

lib/puppet/util/autoload.rb, spec/unit/util/autoload_spec.rb
Pathname#cleanpath correctly replaces all backslashes to forward slashes
on Windows, so remove our workaround. The workaround is required in 5.5.x
because we "support" 1.9.3.
[1] https://bugs.ruby-lang.org/issues/9618
=> (PUP-10840) Remove cleanpath workaround

lib/puppet/parser/ast/leaf.rb, lib/puppet/pops/model/ast_transformer.rb
Puppet emitted a deprecation warning when parsing a `node` definition containing
a hostname, because it passed a hash to `Puppet::Parser::AST::HostName.new`, but
the initialize method expected keyword arguments. The error is only reproducible
using ruby 2.7.1, but not 2.7.2. The error doesn't happen with `AST::Regex`,
because its `initialize` method accepted a hash.
This commit double splats the hash prior to calling `klass.new` and it updates
`AST::Regex` to expect keyword arguments like `AST::HostName`. Note the
superclass `AST::Leaf` already expects keyword arguments.
=> (PUP-10845) Eliminate keyword parameter warning

lib/puppet/defaults.rb, lib/puppet/settings.rb, lib/puppet/settings/alias_setting.rb, spec/integration/defaults_spec.rb, spec/unit/settings_spec.rb
Added a new settings type, alias, and updates :serverport to be an alias for :masterport
=> (PUP-10725) add aliasing mechanism for settings

lib/puppet/module_tool/applications/installer.rb, lib/puppet/module_tool/errors/shared.rb, spec/unit/module_tool/applications/installer_spec.rb
Depends on puppetlabs/semantic_puppet#34.
The changes are backwards compatible so they shouldn't break users with
older versions of semantic_puppet.
Fixed a bug where we wouldn't print the version of the module we're
installing when raising this specific error.
Also, when installing a module without specifying its version, the error
message will show the best candidate instead of `(???)`.
Before (assuming puppetlabs-concat 6.4.0 is installed prior to this):
```
Error: Could not install module 'trepasi-debnet' (???)
No version of 'trepasi-debnet' can satisfy all dependencies
Use `puppet module install --ignore-dependencies` to install only this module
```
After:
```
Error: Could not install module 'trepasi-debnet' (v1.5.2)
The requested version cannot satisfy the following dependency: …
```
=> (PUP-9176) List failed module install dependencies

lib/puppet/face/facts.rb, lib/puppet/indirector/facts/facter.rb, spec/unit/indirector/facts/facter_spec.rb
By default, `puppet facts show` application displays all facts, including legacy facts. This PR adds an option, `--no-legacy` to disable legacy facts when querying for all facts.
=> (PUP-10850)Add --no-legacy option for puppet facts

lib/puppet/face/facts.rb
This option has no effect and is needed for backwards compatibility.
=> (maint) Add show legacy option for puppet facts

lib/puppet/module_tool/applications/installer.rb, lib/puppet/module_tool/errors/shared.rb, spec/unit/module_tool/applications/installer_spec.rb
In 9822a26bf we only handled the case where a module that is to be installed cannot satisfy one or more of its dependencies.
Spec tests uncovered a case that we missed, where the module satisfies all of its constraints, but an existing installed module would become unsatisfied after the installation.
I think this has a low chance of occuring in practice. To reproduce this, one has to:
1. Install a module with fixed upper dependencies:
`> puppet module install --target-dir tmpdir trepasi-debnet -v 1.5.1`
This version has puppetlabs-stdlib bound to `>= 3.2.0 < 5.0.0`
2. Forcibly remove the `stdlib` module
`> rm -rf tmpdir/stdlib`
3. Attempt to install a version of stdlib that breaks the above-stated dependency
`> puppet module install --target-dir tmpdir puppetlabs-stdlib -v "> 5"`
Without …
=> (PUP-9176) Requested module breaks existing module dependency

lib/puppet/face/facts.rb, lib/puppet/network/formats.rb, spec/unit/network/formats_spec.rb
**Description of the problem:** The output format is different between Facter and `puppet facts` when a query for a single fact is provided:
`~~ puppet facts facterversion`
`{
"facterversion": "4.0.47"
}`
vs
`~~ facter facterversion`
`4.0.47`
**Description of the fix:**
**Added `--value-only` command argument:**
When there is a single query, only display the value of the fact without it's name:
`~~ puppet facts facterversion --value-only`
`"4.0.47"`
Also this generates a warning message if the argument is used with multiple queries or with no query at all:
`puppet facts show facterversion  os --value-only`
`Warning: Incorect use of --value-only argument! The argument must be used when quering for a single fact!`
**Added `flat` render format:**
When there is a query for a simple fact: …
=> (PUP-10847) Add flat output format

lib/puppet/face/facts.rb, lib/puppet/indirector/facts/facter.rb, spec/unit/indirector/facts/facter_spec.rb
**Description of the problem:** Legacy facts were displayed by default without a mechanism to opt-out. An opt-out mechanism was introduced in  https://github.com/puppetlabs/puppet/pull/8475 but this also introduced some breaking changes.
**Description of the fix:** Implemented a mechanism to opt-in for legacy facts and the `--show-legacy` option was fixed.
=> (PUP-10850)Fix show_legacy option for puppet facts

lib/puppet/application/apply.rb, lib/puppet/configurer.rb, lib/puppet/pops/evaluator/deferred_resolver.rb, spec/integration/application/agent_spec.rb, spec/integration/application/apply_spec.rb
Previously, puppet apply could call deferred 3x functions, but puppet agent
could not, resulting in:
Function <name> not defined despite being loaded!
This was due to `puppet agent` calling `Puppet::Parser::Functions.environment_module`
with different `Puppet::Node::Environment` objects, but the same name. As a
result, 3x functions were defined on one Module instance[1], but a different
Module instance was mixed into the scope[2]. As a result, calling
`Scope#function_<name>` would trigger `method_missing`.
The reason this affected `puppet agent` is because it creates a
`Puppet::Node::Environment.remote` environment_instance when deserializing the
catalog[3], which is a different instance than the current environment pushed onto
the context.
This commit passes the current environment to …
=> (PUP-10819) Define and call 3x functions using the same Module object

lib/puppet/file_serving/configuration/parser.rb, spec/unit/file_serving/configuration/parser_spec.rb
Legacy auth was removed in 7, so if we parse an authz rule in fileserver.conf,
then we want to alert the user that it will be ignored by puppet. However,
`allow *` rules are harmless and match puppet's current behavior, so ignore
those, but continue logging an error for other allow/deny rules.
=> (PUP-10851) Omit error when parsing 'allow *' in fileserver.conf

lib/puppet/configurer.rb, spec/integration/application/agent_spec.rb
Commit 408bf4e0f9 cached the resource catalog before resolving deferred
functions and converting the resource catalog to a RAL catalog. This way the
deferred function is cached, not the function's result. However, that caused
a regression as we cached the resource catalog before type/provider validation,
which occurs during `Catalog#to_ral`. For example, when using a non-absolute
path as the `command` in an `exec` resource.
Due to PUP-9323, we have to resolve deferred values, which mutates the resource
catalog, before converting to RAL and provider validation, and we need to do
that before caching. So make a copy of the original resource catalog, and cache
that if validation succeeds.
=> (PUP-10818) Validate catalog before caching it

lib/puppet/application/apply.rb, lib/puppet/configurer.rb, lib/puppet/pops/evaluator/deferred_resolver.rb, spec/integration/application/agent_spec.rb, spec/integration/application/apply_spec.rb
* Commits:
(PUP-10815) Add `puppet facts diff` command
(PUP-10819) Define and call 3x functions using the same Module object
(PUP-10815) Added Facter diff util
* Conflicts:
lib/puppet/face/facts.rb - the `diff` action has no purpose in Puppet 7
* Removed:
lib/puppet/util/fact_dif.rb
acceptance/tests/face/facts_face_diff.rb
Only changes from `(PUP-10819) Define and call 3x functions using the same Module object` (#8477) get merged up.
=> (maint) Merge up 6.x into main

lib/puppet/pops/evaluator/deferred_resolver.rb, spec/unit/pops/evaluator/deferred_resolver_spec.rb
Commit 321f04b2d0 added a mandatory environment parameter to the
DeferredResolver.resolve_and_replace method, but apparently that is a public API
called by bolt[1] and pxp-agent's apply module[2]. So make the environment
parameter optional and default to the catalog's environment, like it did before.
[1] https://github.com/puppetlabs/bolt/blob/2.40.2/libexec/apply_catalog.rb#L99
[2] https://github.com/puppetlabs/pxp-agent/blob/1.15.9/lib/src/modules/apply.cc#L164
=> (PUP-10819) Preserve deferred evaluator API compatibility

acceptance/tests/environment/should_find_existing_production_environment.rb, lib/puppet/settings.rb
Before this commit puppet expected the default `production` environment folder to always be in the first path of the `environmentpath` setting and was being automatically created if not found there.
This commit adds a check to make sure it was not already created in any of the other environment paths given before automatically creating a new one. This can happen if a new path is inserted at the beginning of the `environmentpath` setting after the `production` folder was already created. This change aligns with custom environment behaviour where it searches in the given environment paths and uses the first one it matches, from left to right, the environment name given.
=> (PUP-10842) Fix production environment folder creation

ext/build_defaults.yaml
More of a formality, but also for clarity: remove the reference to the
old GPG signing key.
This is normally overridden by the key in the build-data repo.
=> (RE-13432) Remove reference to old GPG key

lib/puppet/face/facts.rb, lib/puppet/indirector/facts/facter.rb, spec/unit/indirector/facts/facter_spec.rb
This will print information for all the facts used(time is printed by facter), not only the queried ones:
```
❯ bx puppet facts show timezone --timing
fact 'operatingsystem', took: (0.022100) seconds
fact 'osfamily', took: (0.000022) seconds
fact 'operatingsystem', took: (0.000018) seconds
fact 'osfamily', took: (0.000012) seconds
fact 'operatingsystem', took: (0.000013) seconds
fact 'operatingsystem', took: (0.000009) seconds
fact 'timezone', took: (0.000052) seconds
{
"timezone": "EET"
}
```
=> (PUP-10858) Add `--timing` to puppet facts show

spec/unit/ssl/certificate_request_spec.rb
We set the keylength setting to 512 during tests to reduce the amount of time
spent generating RSA private keys. However, the CSR signing tests fail with the
following error when using a 512-bit RSA key and digests SHA384 and 512:
OpenSSL::X509::RequestError:
EVP lib
So use 2048-bit keys for those tests.
=> (PUP-8110) Increase size of private key in CSR tests

lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/aptitude.rb, lib/puppet/type/package.rb, spec/unit/provider/package/apt_spec.rb
Before puppet-18.0, using an absolute path as package name allowed
users to install local packages using apt. While this was working,
the functionality was unintended and incomplete(eg. puppet will execute
package install command each run and will report changes).
This commit enables the usage of `source` parameter with `apt` provider
and now a user can install a local package using a manifest like bellow:
```
package { 'helloworld':
source => '/tmp/helloworld_1.0-1.deb'
ensure => installed,
}
```
=> (PUP-10854) allow apt to install local packages

lib/puppet/provider/package/apt.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/aptitude_spec.rb
This improves the performance of apt package provider by skipping the `apt-mark` calls when removing resources that does not exist.
=> (PUP-10856) avoid unnecessary calls to aptmark

api/docs/pson.md
Describe how pson forked from json and was modified to allow arbitrary
binary content. Make it clearer how pson differs from json.
=> (maint) Update PSON doc

lib/puppet/property/list.rb, lib/puppet/provider/group/groupadd.rb, lib/puppet/provider/user/useradd.rb, spec/unit/provider/group/groupadd_spec.rb, spec/unit/provider/user/useradd_spec.rb
Before this commit, `forcelocal` had no effect on the `groups` field from the `useradd` provider. This change allows to get groups from `/etc/groups` when `forcelocal` is set to `true`.
This PR also adds `forcelocal` option effect on user gid from the `useradd` provider and fixes the retrieval of arrays from the property list.
=> (PUP-10857) Find groups locally with useradd provider

lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb
The `puppet facts show --value-only` option prints just the value for a single
fact. Previously, the value was pretty printed using JSON.dump, which emitted a
quoted string. Now just print the string, so that the value can be parsed via
automation, like export OSFAMILY=`puppet facts show os.family --value-only`
Also add a test for multiple fact names as the `--value-only` option.
=> (PUP-10861) Don't JSON.dump single fact values

acceptance/tests/resource/user/should_manage_groups.rb, lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
In a previous commit we mistakenly called the wrong method to get the
groups of an user, as `get` retrieves information from an user's passwd
structure, and the groups of an user are not present in that structure.
To fix this, call the superclass method, which should call
`Puppet::Util::POSIX.groups_of`.
Also reenable the `should_manage_groups` acceptance test.
=> (PUP-10857) Correctly retrieve the groups of an user

lib/puppet/provider/service/debian.rb
When we deliver both systemd and systemv init scripts, sometimes
puppet decides to use debian provider on `puppet resource service puppet`
commands, even when system is running with systemd.
The change confines debian provider to systems where `systemd` is not
running with PID 1 and is complementary to the confine from systemd provider
=> (maint) disable debian service provider if systemd is running with PID 1 

acceptance/tests/resource/user/should_modify_gid.rb, acceptance/tests/resource/user/should_modify_gid_forcelocal.rb, lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
This is a regression of #8501 which made `forcelocal` act different when
setting the `gid` parameter.
Since we were returning the GID of an user as a string, Puppet made the
assumption that the GID wasn't a number. This caused issues when setting
gid to a string value (like `gid => 'abc'`), which is allowed in Puppet.
To fix this, ensure we return the GID as integer after searching
`/etc/passwd`. If for some reason it cannot be converted, it is returned
as is (highly unlikely as non-numeric GIDs are not allowed in
`/etc/passwd`).
=> (PUP-10896) Fix gid idempotency on user resource

lib/puppet/face/facts.rb, lib/puppet/indirector/facts/facter.rb, lib/puppet/network/formats.rb, spec/unit/application/facts_spec.rb, spec/unit/face/facts_spec.rb, spec/unit/indirector/facts/facter_spec.rb, spec/unit/network/formats_spec.rb
This is mostly a cherry-pick of the following commits
that added `puppet facts show` on main:
- 88fbc32
- eafff42
- c9dfabb
- cac4677
- fdbcce0
- 3a8626f
- 0de8cfc
The changes that were made after the cherry-pick:
- find is set back to default action, instead of show
- the macaddress for tests was changed to work on ruby 2.3/2.4
=> (PUP-10844) Add puppet facts show on 6.x

lib/puppet/util/windows/principal.rb, spec/integration/util/windows/principal_spec.rb
This commit adds a sanitization step at the beginning of the `lookup_account_name` method (from `Puppet::Util::Windows::SID::Principal`) for the given account names. This now allows looking up users from `APPLICATION PACKAGE AUTHORITY` when they are given as fully qualified names.
Before this commit, the only workarounds were to either use their SID values or their unqualified names (`ALL RESTRICTED APPLICATION PACKAGES` instead of `APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION
PACKAGES`). With these in mind, issues still appeared when managing files/folders with this user already set in the rights or ownership properties (Puppet was, and still is, getting the fully qualified name and then was failing during account name information retrieval due to this known issue).
See …
=> (PUP-10899) Add Windows account name sanitization for lookup

lib/puppet/file_system/windows.rb, lib/puppet/util/windows/adsi.rb, lib/puppet/util/windows/sid.rb, spec/integration/util/windows/adsi_spec.rb, spec/unit/file_system_spec.rb, spec/unit/util/windows/sid_spec.rb
This pull request adds a fallback to retrieving the current Windows user name SID by retrying with the fully qualified user name when said SID returns as `nil` the first try. This is done via the `GetUserNameExW` function.
A debug message is also added where errors (in the `Puppet::Util::Windows::SID::name_to_principal` method) were caught silently and increased debugging difficulty (`Puppet::Util::Windows::SID::Principal::lookup_account_name` in particular).
=> (PUP-10898) Get fully qualified current user name as fallback

.gemspec
to make it accessible via e.g. rubygems.org and usable by
compliance tooling
Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>
=> gemspec: add license metadata

lib/puppet/application/ssl.rb, lib/puppet/file_system/windows.rb, lib/puppet/util/windows/adsi.rb, lib/puppet/util/windows/sid.rb, spec/integration/util/windows/adsi_spec.rb, spec/unit/application/ssl_spec.rb, spec/unit/file_system_spec.rb, spec/unit/util/windows/sid_spec.rb
* 6.x:
(PUP-10940) use `puppet facts show` command to compare facts
(PUP-10898) Get fully qualified current user name as fallback
(PUP-10888) Added puppet ssl show action
(maint) Add debug messages for silently catched errors
(PUP-10940) puppet facts diff facter-ng reload  On facts diff command we run both facter 3 and facter 4 in the same run
=> (maint) Merge branch 6.x into main

lib/puppet/defaults.rb, lib/puppet/network/http/factory.rb, lib/puppet/util/monkey_patches.rb, spec/integration/application/plugin_spec.rb, spec/integration/http/client_spec.rb, spec/unit/network/http/factory_spec.rb
Previously puppet's ciphersuite depended on the ruby+openssl version in use.
This commit makes it explicit by adding a `ciphers` setting and defaulting to
Mozilla's "backward compatibility" option. All of the ciphers supported in
puppet-agent 6.x (with ruby 2.5.8 and openssl 1.1.1i) are still supported:
> old_ciphers = OpenSSL::SSL::SSLContext.new.ciphers
> ctx = OpenSSL::SSL::SSLContext.new
> ctx.ciphers = Puppet[:ciphers]
> pp ctx.ciphers - old_ciphers
[]
> pp ctx.ciphers
[["TLS_AES_256_GCM_SHA384", "TLSv1.3", 256, 256],
["TLS_CHACHA20_POLY1305_SHA256", "TLSv1.3", 256, 256],
["TLS_AES_128_GCM_SHA256", "TLSv1.3", 128, 128],
["ECDHE-ECDSA-AES128-GCM-SHA256", "TLSv1.2", 128, 128],
["ECDHE-RSA-AES128-GCM-SHA256", "TLSv1.2", 128, 128],
["ECDHE-ECDSA-AES256-GCM-SHA384", "TLSv1.2", 256, 256], …
=> (PUP-10889) Explicitly set ciphersuite and allow it to be configurable

lib/puppet/util/windows/api_types.rb, spec/integration/util/windows/registry_spec.rb
On Windows, it is possible to have a registry that contains corrupted
data after the WCHAR_NULL characters, that can break puppet when reading
the registy.
Part of the fix was done in PUP-10536, but when the WCHAR_NULL from the
registry is \u0000 instead of \u0000\u0000, the split did not work.
Now WCHAR_NULL is forced encoded to UTF-16LE, meaning `\u000` so puppet
will now stop at the WCHAR_NULL char.
The initial issue can be reproduced by importing file.reg using
`reg import  .\file.reg`
----file.reg----
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PUP105360000]
"DisplayName"="PUP105"
"DisplayVersion"=hex(2):32,0,0,0,f3,23,8a,bc,fa,7f,0,0,10,65,74,b9,fa,7f,0,0,90,d8,55,6f,59
=> (PUP-10943) Puppet read registry until WCHAR_NULL

lib/puppet/pops/validation/checker4_0.rb, spec/integration/parser/collection_spec.rb
Commit 8bdaaecdce removed the `when CapabilityMapping` statement, but didn't
remove the corresponding issue. I was thinking of Java switch/case, where
multiple cases fall through. This makes it possible to use the splat operator to
override attributes for collected resources.
=> (PUP-10951) Allow splat operator inside overridden resource collectors

lib/puppet/face/facts.rb, lib/puppet/util/fact_dif.rb
This commit updates the exclude list for `puppet facts diff` by removing non-volatile facts and adding missed ones that were discovered while running the command on all of our available platforms.
Results from above tests were taken and processed as follows:
- The initial exclude list was (49 in total): `facterversion`, `swapfree_mb`, `swapsize_mb`, `load_averages\.*`, `memory\.swap\.available_bytes`, `memory\.swap\.capacity`, `memory\.swap\.total_bytes`, `memory\.swap\.used_bytes`, `memory\.swap\.available`, `memory\.system\.available`, `memory\.system\.available_bytes`, `memory\.system\.capacity`, `memory\.swap\.used`, `memory\.system\.total_bytes`, `memory\.system\.used`, `memory\.system\.used_bytes`, `memoryfree`, `memoryfree_mb`, `memorysize_mb`, `mountpoints\..*`, `mtu_.*`, …
=> (PUP-10947) Modify the exclude list for `puppet facts diff`

acceptance/tests/resource/package/common_package_name_in_different_providers.rb, acceptance/tests/ticket_1334_clientbucket_corrupted.rb
- common_package_name_in_different_providers
Not really sure why the error message changed between 6.x and 7.x, but apart from this the functionality appears to be the same.
- ticket_1334_clientbucket_corrupted.rb
This failed due to PUP-10583 which changed the default digest algorithm to SHA256 for Puppet 7
=> (PUP-10923) Fix acceptance tests on main branch

spec/spec_helper.rb
We added an Azure Metadata fact in Facter 4.0.52,
and GH Actions VMs are running on Azure, so there's
an additional http call being made which needs to
be stubbed.
=> (maint) stub Facter requests to external services

acceptance/tests/resource/service/AIX_service_provider.rb, acceptance/tests/resource/service/puppet_service_runs_puppet.rb
An unwanted change from the following commit https://github.com/puppetlabs/puppet/commit/2dd43150b3596b872e82141a6b1be515dd805809#diff-8605333114f5da06990288c0de42387d8b1e0e694eb670498efa0fa5fc0597e3R63-R68 got in main, which breaks the AIX service tests as the call to `run_nonexistent_service_tests` was changed, but the method signature was not changed.
To fix this, revert to the 6.x version of the AIX test.
=> (PUP-10923) Fix aix acceptance test

lib/puppet/functions/partition.rb
The `|` (pipe character) in the examples given in `lib/puppet/functions.rb` are currently rendered in https://puppet.com/docs/puppet/latest/function.html#partition as _table_ _cell_ _dividers_, but it’s supposed to be Puppet source code.
=> (docs) mark documentation examples in lib/puppet/functions.rb as source code

lib/puppet/face/facts.rb, spec/integration/http/client_spec.rb
This commit adds missing characters from the `EXCLUDE_LIST` array of regular expressions used for filtering the `puppet facts diff` output of volatile facts.
=> (maint) Fix exclude_list for `puppet facts diff`

.rubocop.yml, lib/puppet/defaults.rb, lib/puppet/node/environment.rb
This commit removes the on-write hook from the rich data setting,
instead updating environments to read the current value from settings
directly when queried, if not overwritten in the environment conf. The
env conf is read once and its rich_data setting (or lack thereof) is
cached, so we don't read the file over and over.
------
Thanks for your contribution! Note that all community contributors will be required to sign our Contributor License Agreement, unless you fall under the [Trivial Patch Exemption Policy](https://puppet.com/community/trivial-patch-exemption-policy). If you believe it applies to your pull request, please comment explaining why you do not need to sign the CLA. Directions for signing will be attached to your pull request shortly.
Please note that all contributions may …
=> (PUP-10952) Respect `rich_data` setting without rereading env conf

lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
This is to update useradd provider to ignore empty lines in /etc/group
```
/etc/passwd:24:testuser:x:1001:1001:testuser:/home/testuser:/bin/bash
/etc/group:41:centos:x:1000:testuser
/etc/group:42:testuser:x:1001:
/etc/group:43:
Notice: Compiled catalog for [redacted] in environment production in 0.02 seconds
Notice: Applied catalog in 0.02 seconds
```
Confirmed no changes/still working as expected if /etc/group does not contain empty lines, and if adding user:
```
/etc/passwd:24:testuser:x:1001:1001:testuser:/home/testuser:/bin/bash
/etc/group:41:centos:x:1000:testuser
/etc/group:42:testuser:x:1001:
Notice: Compiled catalog for [redacted] in environment production in 0.02 seconds
Notice: Applied catalog in 0.02 seconds
Notice: Compiled catalog for [redacted] in environment production in …
```
=> (PUP-10997) ignore empty lines in /etc/group

lib/puppet/defaults.rb
There is a race condition that can cause parallel or rapid puppet agent runs to truncate the `agent_disabled_lockfile` this is similiar to a very old issue with the puppetdlockfile #1158.
This changes the `agent_disabled_lockfile` setting type to string to ensure that a file resource is not added to the catalog.
=> (PUP-11000) Change agent_disabled_lockfile setting type to string

lib/puppet/module.rb, spec/unit/module_spec.rb
This adds a new subdirectory to the `Module` class `scripts/` which
automatically generates the functions `scripts?()`, `scripts()`, and
`script()` on the class for retrieving available scripts. This is part
of the [scripts
milestone](https://github.com/puppetlabs/bolt/issues?q=is%3Aopen+is%3Aissue+milestone%3AScripts)
for Bolt, which aims to eventually standardize on more specific file
loading from either the `files/` directory or `scripts/` directory in a
module. This doesn't need a file serving endpoint (at least for now) as
we don't plan to support this in Puppetserver - users who want to use
scripts with file resources should use the files directory rather than
scripts.
=> (PUP-10996) Enabled loading scripts from a `scripts` directory

lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb
This commit allows the `diff` action (from `face/facts.rb`) to output results in a friendly and human readable format by default. The previous one-liner output can still be achieved by using the `--render-as json` option.
Output from Ubuntu 20.04 ARM (without fix):
```sh-session
➜ puppet facts diff
{"mountpoints./.device":{"new_value":"/dev/nvme0n1p1","old_value":"PARTUUID=4ef7520f-474e-4d3e-a298-fe71ee0e99c5"}}
➜ puppet facts diff --render-as yaml
---
mountpoints./.device:
:new_value: "/dev/nvme0n1p1"
:old_value: PARTUUID=4ef7520f-474e-4d3e-a298-fe71ee0e99c5
➜ puppet facts diff --render-as json
{"mountpoints./.device":{"new_value":"/dev/nvme0n1p1","old_value":"PARTUUID=4ef7520f-474e-4d3e-a298-fe71ee0e99c5"}}
```
Output from Ubuntu 20.04 ARM (with fix applied):
```sh-session
➜ puppet …
```
=> (PUP-10973) Default `puppet facts diff` output to pretty JSON

lib/puppet/provider/package/puppet_gem.rb, spec/unit/provider/package/puppet_gem_spec.rb
When puppet is used as a library, environment.bat
is not sourced and this leads to `PUPPET_DIR` to
not be set. Because `puppet_gem` is relying on that
to build the `gem.bat` path, it will end-up using
a non-existing path, making this provider not suitable.
This has been noticed when using the `puppet_gem`
with the package task in PE.
This commit updates the `puppet_gem` provider to
use `Gem.default_bindir` to determine the location
of the execatables. To avoid accidental usage of
`puppet_gem` provider with system ruby, a confine to
the existence of `aio_agent_version` facts has been added.
Manually tested that `package` task works in PE.
If `puppet_gem` is run from puppet as a gem, it will report that the provider is not functional.
=> (PUP-10964) fix puppet_gem command on Windows

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
This commit adds logic to the default CA dir calculation to make it
return the new CA dir location `/etc/puppetlabs/puppetserver/ca` if the
new location has CA content, since in this case, we understand that
the CA has been migrated, and we want to be using the new location. When
the new location does not exist, we return the old default, since we
want to use the old location for new installs.
=> (PUP-11004) Return new CA location as default if it exists

lib/puppet/functions.rb, lib/puppet/loaders.rb, lib/puppet/pops/loader/base_loader.rb, lib/puppet/pops/loader/dependency_loader.rb, lib/puppet/pops/loader/loader.rb, lib/puppet/pops/loader/module_loaders.rb, lib/puppet/pops/loader/predefined_loader.rb, lib/puppet/pops/loader/runtime3_type_loader.rb, lib/puppet/pops/loader/static_loader.rb, lib/puppet/pops/loaders.rb, lib/puppet/pops/types/p_type_set_type.rb, lib/puppet/settings.rb, spec/unit/pops/loaders/dependency_loader_spec.rb, spec/unit/pops/types/type_parser_spec.rb
This makes loaders aware of the environment they are loading for and then attempts to lock with the environment instead of synchronizing each loader instance on itself.
=> (PUP-10959) Lock loader hierarchy instead of individual loaders

lib/puppet/face/facts.rb, lib/puppet/util/fact_dif.rb, spec/unit/application/facts_spec.rb
This commit aims to improve the `puppet facts diff` CLI command by:
- showing all differences between Facter 3 and Facter 4 (including facts available only in Facter 4)
- sorting output results in alphabetical order for better human readability
- allowing users to remove certain facts from output (via the `--exclude <regex>` CLI option)
- including a CLI option to see results in a fully structured form
- adding various code improvements
---
Before:
```sh-session
➜ puppet facts diff
{
"hypervisors.vmware.version": {
"new_value": "ESXi 6.7",
"old_value": ""
}
}
➜ puppet facts diff --render-as yaml
---
hypervisors.vmware.version:
:new_value: ESXi 6.7
:old_value: ''
➜ puppet facts diff --render-as json
{"hypervisors.vmware.version":{"new_value":"ESXi 6.7","old_value":""}}
```
---
After: …
=> (PUP-10985) Output facts existing only in Facter 4 via `diff` action

lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb
Previously, when executing `puppet facts show` for creating the result of `puppet facts diff`, we could end up with warnings besides the needed output  which was breaking our JSON parsing. This commit ensures that we retrieve stdout only and discard stderr.
Example of error:
```sh-session
➜  puppet facts diff
Error: 765: unexpected token at 'Warning: Facter: timeout option is not supported for custom facts and will be ignored.
{"aio_agent_version":"6.21.1.48", ...
```
=> (maint) Retrieve only stdout for `puppet facts diff`

lib/puppet/provider/package/dnfmodule.rb, spec/unit/provider/package/dnfmodule_spec.rb
When trying to install a module without default profile, newer
`dnf` versions (eg. 4.2.23) show a different error message.
This commit adapts the `dnf` error message expected in dnfmodule provider.
=> (PUP-11024) enable dnfmodule with no default profile on newer dnf (cherry-pick)(6.x)

lib/puppet/provider/package/dnfmodule.rb, spec/unit/provider/package/dnfmodule_spec.rb
When trying to install a module without default profile, newer
`dnf` versions (eg. 4.2.23) show a different error message.
This commit adapts the `dnf` error message expected in dnfmodule provider.
=> (PUP-11024) enable dnfmodule with no default profile on newer dnf(main)

spec/unit/gettext/config_spec.rb, spec/unit/provider/service/init_spec.rb, spec/unit/provider/service/openwrt_spec.rb, spec/unit/transaction/additional_resource_generator_spec.rb, spec/unit/transaction_spec.rb, spec/unit/util/selinux_spec.rb
This resolves order dependent test failures seen when running:
```shell
$ bundle exec rspec spec/integration/application/plugin_spec.rb spec/unit/gettext/config_spec.rb
$ bundle exec rspec spec/integration/application/plugin_spec.rb spec/unit/provider/service/init_spec.rb
$ bundle exec rspec spec/unit/util/selinux_spec.rb spec/unit/transaction_spec.rb
$ bundle exec rspec spec/unit/transaction/additional_resource_generator_spec.rb spec/unit/transaction_spec.rb
```
There will be merge conflicts when merging to main, I'll take care of that after this passes CI
=> (PUP-11022) Resolve order dependent test failures

lib/puppet/http/service/compiler.rb, spec/unit/http/service/compiler_spec.rb
This commit adds a method to the `Puppet::HTTP::Service::Compiler` class to expose the v4 catalog enpoint in puppetserver.
=> (PUP-11002) Expose v4 Catalog endpoint in compiler service

acceptance/tests/resource/file/ticket_8740_should_not_enumerate_root_directory.rb, acceptance/tests/resource/user/should_allow_password_salt_iterations_osx.rb, acceptance/tests/resource/user/should_modify_home.rb, acceptance/tests/resource/user/should_modify_uid.rb, lib/puppet/http/service/compiler.rb, spec/unit/http/service/compiler_spec.rb
(PUP-11002) Expose v4 Catalog endpoint in compiler service
(PUP-11025) Skip failing acceptance tests for Big Sur
(packaging) Bump to version '6.23.0' [no-promote]
Conflicts:
.gemspec
lib/puppet/http/service/compiler.rb
lib/puppet/version.rb
man/man5/puppet.conf.5
man/man8/puppet.8
Conflict diff:
```diff
diff --cc .gemspec
index 63fa8a9438,96c7e3ec63..0000000000
--- a/.gemspec
+++ b/.gemspec
@@@ -13,7 -13,7 +13,11 @@@
Gem::Specification.new do |s|
s.name = "puppet"
++<<<<<<< HEAD
+  version = "7.7.0"
++=======
+   version = "6.23.0"
++>>>>>>> upstream/6.x
mdata = version.match(/(\d+\.\d+\.\d+)/)
s.version = mdata ? mdata[1] : version
diff --cc lib/puppet/http/service/compiler.rb
index 54e855859e,00149462f2..0000000000
--- …
```
=> (maint) Merge up 6.x into main 

.github/workflows/rspec_tests.yaml, Gemfile, ext/project_data.yaml, spec/unit/resource/catalog_spec.rb
Allow bundler to install win32-dir 0.7.2 that contains the ASLR fix.
This change affects bundler and the runtime dependencies for the win32
specific versions of the puppet gem. It is important to continue accepting
win32-dir 0.4.9, because that is what we ship in the puppet-runtime.
Since win32-dir 0.7.2 only supports ruby 2.4 and up, this change drops the ruby
2.3 and windows rspec combination. Ruby 2.3 went EOL March 28, 2018.
The change to ruby-prof was due to bundler pulling in a a version that wasn't
compatible with older ruby versions. So restrict that to ruby >= 2.5. It's only
needed when running the memory related benchmarks.
=> (maint) Relax win32-dir

lib/puppet/type/file/selcontext.rb, lib/puppet/util/selinux.rb, spec/unit/type/file/selinux_spec.rb, spec/unit/util/selinux_spec.rb
See #8537 for details. This supersedes that PR and targets 6.x.
Note https://github.com/puppetlabs/puppet/blob/67ad21b64237eb4f808844bdaa3c2b0e4cdef95c/lib/puppet/util/filetype.rb#L131 is unchanged because in that case we've already written the file prior to retrieving its selinux context.
=> (PUP-7559) Pass correct mode when lookup SELinux default context

spec/unit/http/service/compiler_spec.rb
Ruby 3 removed support for passing a hash as the last parameter and having it
auto convert to keyword parameters. Use double splat so it's clear we're passing
keyword arguments.
=> (maint) Splat hash explicitly

lib/puppet/parser/functions/fqdn_rand.rb, spec/unit/parser/functions/fqdn_rand_spec.rb
Adds an optional argument to the `fqdn_rand` function so that the `fqdn` fact is
downcased when computing the seed. This way the function always produces the
same value if the fqdn fact only differs by case, but all of the `fqdn_rand`
arguments are the same. Note the downcase argument must be passed after the SEED
argument:
fqdn_rand(100, 'expensive job 1', true)
The SEED argument defaults to nil, so this is also possible:
fqdn_rand(100, nil, true)
=> (PUP-10922) Add optional argument to downcase fqdn

lib/puppet/file_serving/fileset.rb, lib/puppet/http/service/file_server.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/indirector/file_metadata/rest.rb, lib/puppet/type/file.rb, lib/puppet/type/tidy.rb, spec/unit/file_serving/fileset_spec.rb, spec/unit/indirector/catalog/compiler_spec.rb, spec/unit/type/tidy_spec.rb
Adds a new parameter, `max-files`, to limit the number of resources
that may be created by types supporting recursion(file, tidy).
In case the number of resources is greater than `max-files`, an
ArgumentError is raised.
=> (PUP-10946) add max-files for file and tidy resources

install.rb, spec/integration/type/file_spec.rb, spec/lib/puppet_spec/files.rb, spec/unit/file_bucket/dipper_spec.rb, spec/unit/pops/lookup/context_spec.rb
This is the correct way to pass additional arguments in Ruby 3 and also works in Ruby 2.4.
Note that I'm not sure this is the only one where an opts hash is no longer accepted. This PR is just for FileUtils.
=> (PUP-11050) Use keyword arguments for FileUtils

lib/puppet/configurer/downloader.rb, lib/puppet/file_serving/fileset.rb, lib/puppet/type/file.rb, spec/unit/configurer/downloader_spec.rb, spec/unit/file_serving/fileset_spec.rb
* Update the file type to accept -1 `max_files` which will disable warnings
* Update pluginsync to pass `max_files => -1`
=> (PUP-10946) Ignore max file warnings during pluginsync

lib/puppet/ssl/verifier.rb, lib/puppet/util/monkey_patches.rb
Previously, puppet on ruby 3 raised a generic CertVerifyError if the hostname
was mismatched rather than the more specific CertMismatchError. This is because
Ruby 3 changed the StoreContext#error from V_ERR_OK to V_ERR_HOSTNAME_MISMATCH.
This was fixed in ruby-openssl#2.2.0 first released in ruby 3.
[1] https://github.com/ruby/openssl/commit/035a04ece237105ba3c91a8db8f81dc81d2dc452
=> (PUP-11045) Ruby 3 returns V_ERR_HOSTNAME_MISMATCH

lib/puppet/util.rb
URI.escape/unescape was removed in Ruby 3, because it implements RFC 2396
escape/unescape with updates for RFCs 2732 and 2373, and those have been
superseded by RFC 3986.
To maintain 100% compatibility while supporting Ruby 3, implement the
escape/unescape methods in puppet[1]. In the future we can look at using
Addressable or using the newer URI parser in ruby.
[1] https://github.com/ruby/ruby/blob/v2_7_3/lib/uri/rfc2396_parser.rb#L24-L46
=> (PUP-11046) Implement RFC2396 style escape/unescape

lib/puppet/file_serving/fileset.rb, spec/unit/file_serving/fileset_spec.rb
Since the http handler is transforming only posive values to numbers,
we need to accomodate the max_files value of `-1` value as string.
=> (PUP-10946) Allow `-1` value of max_files as string

lib/puppet/provider/service/debian.rb, lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/debian_spec.rb, spec/unit/provider/service/systemd_spec.rb
Commit 2f14ddd26 changed the debian and systemd service providers from calling
`Kernel.system` to `Puppet::Provider.execute`, but the methods don't take
arguments in the same way, resulting in:
wrong number of arguments (given 5, expected 1..2)
This code path only seems to occur when ensuring a non-existent service isn't
enabled such as:
Prior to 2f14ddd26 we did not use a shell when calling Kernel.system:
..
[pid  1631] [00007fe41e5d1e37] execve("/bin/ls", ["ls", "*"], 0x55c1d97b3c50 /* 20 vars */) = 0
So we preserve that behavior when calling Puppet::Provider#execute:
"require 'puppet'; Puppet::Util::Execution.execute(['ls', '*'])"
..
[pid  1613] [00007f1231b57e37] execve("/bin/ls", ["ls", "*"], 0x5615349c44d0 /* 18 vars */) = 0
We also have to pass `failonfail => false` to prevent …
=> (PUP-11048) Correct changes from system to execute

lib/puppet/defaults.rb, lib/puppet/functions/all.rb, lib/puppet/functions/capitalize.rb, lib/puppet/functions/downcase.rb, lib/puppet/functions/get.rb, lib/puppet/functions/group_by.rb, lib/puppet/functions/lest.rb, lib/puppet/functions/new.rb, lib/puppet/functions/partition.rb, lib/puppet/functions/require.rb, lib/puppet/functions/sort.rb, lib/puppet/functions/tree_each.rb, lib/puppet/functions/type.rb, lib/puppet/functions/upcase.rb, lib/puppet/reference/configuration.rb
Related to #8596
Wraps more code examples in backticks. The main aim is to avoid issues
in the generated docs caused by unescaped `[]` samples. While I was
in these files, I tried to add missing backticks to other code samples
that I found.
Also adds backticks to the defaults field in the configuration
reference generator.
Please merge up to 7.
=> (Docs)(maint) Fix more strings formatting issues

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
Closes https://tickets.puppetlabs.com/browse/PUP-11034
Previously the `service` provider for `systemd` threw a debug message and prevented `static` services from being `enable => 'mask'`. Turns out this is a valid configuration (corner case) and the `systemctl` commands work just fine.
Specifically this happens on CentOS/RHEL 8 when trying to disable core dumps by masking the `systemd-coredump.socket` service using the following resource declaration:
```puppet
service { 'systemd-coredump.socket':
ensure => 'stopped',
enable => 'mask',
}
```
Now, we provide an extra case when checking the enabled value to allow `static` services to be `masked`, but not allow them to be `enabled` or `disabled` via `true` and `false`.
=> (PUP-11034) Allow systemd static services to be masked

lib/puppet/defaults.rb
Prior to this, the configuration reference page of the docs didn't mention how to disable reporting with the reports setting.
The docs page on reporting mentions it: https://puppet.com/docs/puppet/7.6/reporting_about.html
But not the config reference page: https://puppet.com/docs/puppet/7.6/configuration.html
This change aligns those docs by updating `defaults.rb` with info on disabling reporting.
=> (docs) Document that 'reports = none' disables reporting

lib/puppet/type/service.rb, spec/unit/type/service_spec.rb
Before, validation on values from the `enable` property was overwritten with a custom one which omitted checking required features for values such as :mask. This resulted in a not very useful error message instead of the intended:
`Provider x must have features y to set z`.
8d6c5ba92076babba07a42d8f82c9e6f86f8ef8b re-enables check for required features on enable service values before the custom validation.
9b9e7489839b8e55d3c18790278aff01a2adce0b adds required feature for `delayed` value on enable service property.
16181a58b125aaed17e84eab882e326bccadcb53 adds required feature for `manual` value on enable service property and removes custom validation since it is completely replaced by above changes of adding required features.
=> (PUP-11062) Add required feature for delayed service setting

CONTRIBUTING.md
https://cla.puppet.com/ does not work.
=> (docs) CONTRIBUTING.md: update link to CLA

Gemfile, spec/unit/functions4_spec.rb
- Add webrick to test group for ruby >= 3
- Update rake
- Pass binding's source location to eval
The sorted set issue will be handled in https://github.com/puppetlabs/puppet/pull/8613
=> (PUP-11047) Ruby 3 language and gem updates

lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/yum.rb, lib/puppet/provider/package/zypper.rb
Ruby 3 has removed sorted_set from the core and
exposes it as an external gem.
In puppet, we use it to store the versions of a package.
This can be safely replaced by an Array.
=> (PUP-11076) remove sorted_set usage

acceptance/tests/resource/user/should_manage_purge_ssh_keys_for_new_user.rb, lib/puppet/type/user.rb, spec/unit/type/user_spec.rb
Before this commit, running the following manifest would result in error:
```puppet
user { 'Luchi':
purge_ssh_keys => true
}
```
Error:
```
Parameter purge_ssh_keys failed on User[Luchi]: Munging failed for value true in class purge_ssh_keys: user Luchi doesn't exist
```
This commit better guards against missing or invalid homedir of a user when the `purge_ssh_keys` parameter is managed. It also prioritizes the `ensure` field (when it is set to `present`) instead of `purge_ssh_keys`.
=> (PUP-11067) Prioritize user type `ensure` before `purge_ssh_keys`

lib/puppet/provider/service/freebsd.rb, spec/unit/provider/service/freebsd_spec.rb
Previously, we did not truncate the script when updating a variable. Since the module only support setting variables to "YES" and "NO", the only consequence was that when switching from "YES" to "NO" the last character of the file was kept and we ended up with a blank line:
sshd_enable="YES"\n  -> sshd_enable="NO"\n\n
With the introduction of the support of more variables for the freebsd provider, this result however in more breakage so we have to fix it.
Discovered while working on #8607
=> (maint) Fix rc-scripts edition on FreeBSD when managing services

acceptance/tests/allow_arbitrary_node_name_fact_for_agent.rb, acceptance/tests/allow_arbitrary_node_name_for_agent.rb
For tests that modify auth.conf, make sure we reload the puppetserver service after copying back the old auth.conf, otherwise subsequent tests may fail.
For example, running `tests/agent/agent_parses_json_catalog.rb` after `allow_arbitrary_node_name_for_agent.rb` will fail without this change.
=> (maint) Reload puppetserver service on tests teardown

ext/osx/puppet.plist
By default, launchd plists do not provide access to user keychains (i.e. having the daemon run `security list-keychains` as a different user will not list the user's keychains).
There isn't really any reason why we shouldn't allow this in the puppet plist especially since having `puppet agent -t` run the same command works, it's just runs from the daemon that are affected.
Apple documentation for `SessionCreate` states the following:
> SessionCreate <boolean>
> This key specifies that the job should be spawned into a new security
> audit session rather than the default session for the context is belongs
> to. See auditon(2) for details.
Relevant SO answer: https://stackoverflow.com/a/9482707/1074558
=> (PUP-11081) Allow access to user keychains from macOS daemon

lib/puppet/provider/package/nim.rb, spec/unit/provider/package/nim_spec.rb
20f2499 adapts the regular expression used in the `nim` package provider to allow packages with `S` (security update) in their header to be installed instead of throwing the error:
`Unable to parse output from nimclient showres: line does not match expected package header format`
2c9bb7e adapts the regular expression from the `nim` package provider used for parsing RPM package versions to allow installation of RPM packages that have letters in their version instead of throwing the error:
`Unable to parse output from nimclient showres: package string does not match expected rpm package string format`
=> (PUP-3631) Fix regular expressions in the `nim` package provider

lib/puppet/pops/types/p_sem_ver_type.rb, spec/unit/pops/types/p_sem_ver_type_spec.rb
Passing SemVer prerelease or build components as a list of arguments or a hash
added dots between each character due to confusion between Strings vs Arrays.
For example, SemVer(1, 0, 0, "rc0") resulted in prerelease "r.c.0". This isn't
an issue when passing the entire version as a string, eg "1.0.0-rc0".
Automatically wrapping the prerelease or build components in an array isn't a
breaking change, because it wasn't possible to do it previously. That's because
the function signature is defined to accept a `SemVerQualifier` which `Array` is
not:
$ bx puppet apply -e 'notice(SemVer(1, 2, 3, ["rc4"], ["5"]))'
Error: Evaluation Error: Error while evaluating a Function Call...
rejected: parameter 'prerelease' expects a match for SemVerQualifier
=> (PUP-11077) Pass SemVer prerelease and build as an array

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
CIS controls may require services to be masked, even if they don't exist. So
check if the service exists using `systemctl cat -- <name>` before trying to
disable it.
=> (PUP-10974) Allow masking of nonexistent systemd services

lib/puppet/util/monkey_patches.rb, lib/puppet/x509/cert_provider.rb
Since puppet#main requires ruby 2.5 or greater, we can drop some patches for older ruby/openssl issues.
=> (maint) Drop ruby monkey patches

lib/puppet/forge/cache.rb, lib/puppet/module_tool/tar/mini.rb, spec/unit/module_tool/applications/installer_spec.rb
On Windows the default forge cache base directory is created from Dir.mktmpdir
and contains forward slashes: "C:/Users/josh/AppData/Local/Temp/...".
When unpacking a tarball we check that the entry to be unpacked has the
same prefix. The prefix is the result of File.expand_path, which also
returns a path with forward slashes. When the cache base directory is
changed to a Windows native path, e.g. C:\Temp, to work around long file
path issues, the check will fail.
This commit cleans the base_dir and the tar entry, so that the comparison
is always done using forward slashes.
=> (PUP-4884) Accept native windows module_working_dir path

lib/puppet/indirector/resource/ral.rb, spec/unit/indirector/resource/ral_spec.rb
Commit ef1217338a969f2346a4408c191988a40842c657 renamed the `Puppet::Resource#to_resource` method, which broke the `ral` terminus, but it went unnoticed due to overstubbing in the test. This cleans up the tests and makes it possible to once again filter resources either using the key `Puppet::Resource.indirection.search('user/root')` or using options `Puppet::Resource.indirection.search('user', name: 'root')`
=> (PUP-7799) Allow searching for resources

lib/puppet/forge.rb, spec/integration/application/module_spec.rb
The module_repository may include a path prefix which wasn't included in error
messages due to the way it joined the host and relative uri.
Since we switched over the http client, the request URL is available from the
response object, so just use that.
=> (PUP-8650) Include module_repository in PMT error message

lib/puppet/type/file/mode.rb, lib/puppet/util/symbolic_file_mode.rb, spec/unit/type/file/source_spec.rb
When creating an event for a mode property change, the `desired_value` in the
report is obtained from the `Property#should` method, which calls `unmunge` to
convert the internal representation to its external form. The desired mode
may be an octal string without leading 0's or symbolic form (u+a). Ensure the
latter is padded with 0's so the `desired_value` matches the `previous_value`.
=> (PUP-7493) Record desired mode with leading zeros in the report

lib/puppet/provider/parsedfile.rb, spec/unit/provider/parsedfile_spec.rb
Custom providers like Nagios subclass the `parse` method and may return nil,
causing `retrieve` to return nil. Previously that caused a hard to debug error
trying to call `each` on nil. Now we raise an error with the `target` and name
of the provider. Note the same check is made again after prefetch_hooks are
called.
=> (PUP-9369) Raise if parsedfile providers returns nil

lib/puppet/settings.rb, spec/unit/settings_spec.rb
If user/group providers were not suitable and puppet tried to manage its
internal file-related settings, then puppet printed a cryptic error:
Could not create resources for managing Puppet's files and directories in
sections [:main, :agent, :ssl]: undefined method `exists?' for nil:NilClass
Now we raise if the user or group provider is not functional. It's not a
breaking change, since we raised previously too.
=> (PUP-9825) Raise if the user or group provider is not suitable

lib/puppet/pops/types/type_mismatch_describer.rb, spec/unit/functions/assert_type_spec.rb, spec/unit/functions4_spec.rb
Make the error message clearer if a function is called with arguments that
don't match any of its signatures.
=> (PUP-7792) Improve error message when function arguments don't match

lib/puppet/application/filebucket.rb, spec/integration/application/filebucket_spec.rb
The filebucket predates environments (all files are available from all
environments), yet running filebucket commands would fail if the configured
environment doesn't exist. Set the environment mode for the filebucket
application so it's not required, similar to how it's done for plugins, config,
help, etc.
=> (PUP-10796) Don't require environment to exist for filebucket CLI

lib/puppet/face/help/action.erb, lib/puppet/face/help/face.erb, lib/puppet/interface/documentation.rb
The CLI for face applications accept an `--extra` option, but it doesn't work,
because the string is passed to Puppet::Indirector::Request#initialize, which
expects a Hash[1]. Since this has never worked and we've never specified the
string format, hide the option.
[1] https://github.com/puppetlabs/puppet/blob/7.8.0/lib/puppet/indirector/request.rb#L69
=> (PUP-8700) Hide extra face option

lib/puppet/type/tidy.rb, spec/unit/type/tidy_spec.rb
Tidy resource documentation for the age parameter states that files whose age is equal or greater than the specified time will be removed, and that setting age to 0 will remove all files.[1]
The actual implementation only removes the file if the age is greater, not equal, so fix the comparison.
Note that the size parameter is documented similarly, and the implementation is correct there.
[1] https://puppet.com/docs/puppet/7.7/types/tidy.html#tidy-attribute-age
=> (PUP-11079) Tidy files with age equal or greater

lib/puppet/settings/config_file.rb, lib/puppet/settings/value_translator.rb, spec/integration/defaults_spec.rb, spec/unit/settings/config_file_spec.rb, spec/unit/settings/value_translator_spec.rb, spec/unit/settings_spec.rb
It was not possible to set a setting to a string consisting of all digits such
as `certname=000000000180`. This occurred, because the ConfigFile class
prematurely converted any value that matched /\d+/ to an integer and Ruby will
raise when given `Integer('000000000180')`. Similar problems were reported with
the `environment` setting.
The problem is that the conversion is done before we know the setting's type.
The conversion is also only done when parsing puppet.conf or CLI arguments. So
the value as stored in memory could be a string (if that was the default value),
or it could be an integer (if set in puppet.conf).
This change means settings must explicitly convert to an integer in their
"munge" method which is called during interpolation. This is already done for
autosign, duration, …
=> (PUP-7785) Don't prematurely convert setting values

lib/puppet/file_system/file_impl.rb, lib/puppet/file_system/windows.rb, spec/unit/file_system_spec.rb, spec/unit/parser/templatewrapper_spec.rb
Previously, if a template contained a BOM, then it was preserved by the `template` function, and would end up in the resulting file or powershell command. Now we pass the `bom` option when reading the file, which strips the BOM as it is read.
For example, given a template with a leading BOM:
```shell
$ cat test.ps1.erb
﻿<%= 42 %>
$ od -t x1 test.ps1.erb
0000000 ef bb bf 3c 25 3d 20 34 32 20 25 3e
```
Puppet used to include the BOM in the rendered output:
```
C:\Users\josh\projects\puppet>bundle exec puppet apply -e "notify { 'thing': message => template('C:\Users\josh\projects\puppet\test.ps1.erb') }"
...
Notice: /Stage[main]/Main/Notify[thing]/message: defined 'message' as '﻿ 42'
```
Note the unprintable character before 42 above:
With this change:
``` …
```
=> (PUP-8243) Strip leading BOM from ERB templates

install.rb
fbd859fd02d176137cc9102854be50c04f2912a2 deprecated this parameter back in 2012. That's a long enough deprecation period for packagers to migrate and can be safely removed by now.
=> (maint) remove deprecated --[no-]tests install option

lib/puppet/defaults.rb
A recent change to the way numerical settings are munged made it
necessary to specify the type of a setting that should be converted to a
number, rather than automatically converting all strings that look like
numbers. This commit adds the `integer` type to the `keylength` setting,
to ensure it is converted to an int and not passed as a string.
=> (PUP-7785) Ensure `keylength` setting is treated as an int

lib/puppet/util/windows/sid.rb, spec/unit/util/windows/sid_spec.rb
This commit simply restricts the `Could not retrieve raw SID bytes from` debug log to when an actual SID is passed to `ConvertStringSidToSidW`. The order in which the `Puppet::Util::Windows::SID.name_to_principal` method checks and tries to convert the input (be it an account name, domain qualified account name or SID) to a `Puppet::Util::Windows::SID::Principal` object made it print error messages to debug when it was actually succeeding in the end. Since every Puppet Agent run needs information about at least the currently logged on user, this was creating unnecessary noise in the debug logs.
Before fix:
```sh-session
➜ bundle exec puppet resource user 'Luchi' --debug
...
Debug: Facter: fact "operatingsystem" has resolved to: windows
...
Debug: Could not retrieve raw SID bytes from …
```
=> (PUP-10967) Debug logs clean up when resolving account SID on Windows

lib/puppet/functions/unwrap.rb, spec/unit/functions/unwrap_spec.rb
- as there is no Function `unwrap_if_necessary()` we make the Function `unwrap()`
more tolerant and let it return a non-sensitive Value just like it is
=> (PUP-11123) make Function unwrap more tolerant

lib/puppet/module_tool/applications/installer.rb, lib/puppet/module_tool/errors/shared.rb, spec/unit/module_tool/applications/installer_spec.rb
The 'puppet module install' command requires a fully qualified module name in
the form 'author-module' or 'author/module' or an absolute or relative path to a
tarball. If it's not a tarball, provide a helpful error if author is missing.
=> (PUP-10641) Provide useful error message if module name is invalid

lib/puppet/defaults.rb, spec/unit/util/ldap/connection_spec.rb, spec/unit/util/ldap/manager_spec.rb
The change in eeb61d1c6 allowed settings to be strings containing digits
and to remain strings (helpful for numeric certnames for example).
However, several settings depended on the automatic conversion of
strings that contain digits to Integer. This adds type specification
to any defaults that match / \d+,/ in the defaults.rb.
All are given the type `:integer` unless the setting contains the word
"port" in which case they gain the type `:port`.
A notable exception being the ldapport setting, which depends on being a
string and now is explicitly a string in the defaults.
Additional searches for ttl & priority didn't reveal any defaults that
needed changing. Nor did a search for strings containing wholy digits.
=> (maint) Provide types for possible integer settings defaults

lib/puppet.rb, lib/puppet/settings.rb, spec/integration/environments/settings_interpolation_spec.rb, spec/integration/indirector/facts/facter_spec.rb, spec/lib/puppet_spec/settings.rb, spec/unit/settings_spec.rb
When running `facter -p`, if the environment is set in the agent section of puppet.conf, it would not be reported in the agent_specified_environment fact due to Puppet running in the user run mode.
Now an additional check is made to see if the setting is explicitly set in the agent section, and the fact prioritizes the agent section over other sections.
=> (PUP-6801) Honor agent section for agent_specified_environment fact

lib/puppet/application/resource.rb, spec/integration/application/resource_spec.rb
Previously, attempting to run the puppet resource subcommand with an invalid environment would fail fast.
This commit makes puppet resource default to the production environment if the specified one does not exist.
=> (PUP-6554) Make puppet resource default to production environment

lib/puppet/environments.rb, spec/unit/environments_spec.rb, spec/unit/functions/logging_spec.rb
The `Puppet::Environments::Cached.get` method says it accepts Strings or Symbols. This commit normalizes the environment name before caching and getting the environment to avoid duplicated environments in cache (as String and as Symbol).
```ruby
require 'puppet'
Puppet.initialize_settings
Puppet[:log_level] = 'debug'
Puppet::Util::Log.newdestination(:console)
Puppet::ApplicationSupport.push_application_context(Puppet::Util::RunMode[:user])
envs = Puppet.lookup(:environments)
pp envs.instance_variable_get(:@cache).keys
envs.get!('production')
pp envs.instance_variable_get(:@cache).keys
envs.get!(:production)
pp envs.instance_variable_get(:@cache).keys
```
```sh-session
➜ bundle exec ruby script.rb
Debug: Caching environment 'production' (ttl = 1 sec)
["production"]
Debug: Found in cache …
```
=> (PUP-10955) Normalize environment name to symbol before caching

acceptance/tests/resource/exec/accept_array_commands.rb, lib/puppet/provider/exec/posix.rb, lib/puppet/type/exec.rb, spec/integration/type/exec_spec.rb, spec/unit/type/exec_spec.rb
This change updates the exec resource to accept arrays as command. 
The new behavior is enabled for the following parameters: `:comand`, `:onlyif`, `:unless`, `:refresh`.
```
Changing the command to accept an array:
command: "/bin/echo *"         # executes through shell
command: ["/bin/echo *"]       # non-existing command "bin/echo *"
command: ["/bin/echo *", "*"]  # non-existing command "bin/echo *"
command: ["/bin/echo", "*"]    # executes directly
onlyif/unless: '/bin/echo *'                                  # executes one command through shell
onlyif/unless: ['/bin/echo', '*']            				  # this is handled as two separated commands: '/bin/echo'(1), '*'(2)
onlyif/unless: ['/bin/echo *', '/bin/echo $SHELL']            # executes two commands through shell
onlyif/unless: …
```
=> (PUP-5704) allow array commands in exec resource

lib/puppet/resource/type_collection.rb, spec/unit/parser/compiler_spec.rb, spec/unit/resource/type_collection_spec.rb, spec/unit/resource/type_spec.rb
Node and class scopes are both added to the topscope, so given a manifest like:
node 'abc' { include abc }
We will add the node scope, but not the class scope, because we think it's
already been added. As a result the class is ignored, making it difficult to
debug. This also occurs when using hiera lookup/include:
node 'abc' { lookup('classes').include }
This adds dup checks when adding a node or hostclass to the type collection,
similar to our existing checks. As a result, we will now fail compilation and
the error message will indicate where the node or hostclass was first defined
and where the redefinition was attempted.
Error: Class 'mynode' is already defined (file: manifest.pp, line: 1); \
cannot redefine as a node (file: manifest.pp, line: 2) on node mynode
It also adds tests that …
=> (PUP-3995) Raise if a node and hostclass name conflict

spec/integration/indirector/facts/facter_spec.rb, spec/unit/settings_spec.rb
Prior to eeb61d1c64, puppet automatically coerced settings whose values were all
digits to an integer. Puppet no longer does that, instead it stores the value
that was set, and converts the value when it is looked up, based on the
settings' type, e.g. :integer, :enum, etc.
The facter_spec change is because `serverport` is a `:port` setting so trying to
set it to "baz" is invalid. It's not a breaking change, because running `puppet
agent -t --serverport baz` would never have worked.
The setting_spec change is because we no longer coerce the string to an integer.
Also 6.x doesn't have this issue, because the `integer` and `port` type were added in 7.0
=> (maint) Update tests to match more strict settings behavior

spec/integration/indirector/facts/facter_spec.rb
Spec test should have set `environment` not `serverport`.
=> (maint) Fix typo in environment spec - 6.x

spec/integration/indirector/facts/facter_spec.rb
Spec test should have set `environment` not `serverport`.
=> (maint) Fix typo in environment spec - main

lib/puppet/type/user.rb
this makes an explicitly configured "purge_ssh_keys: false" in type
"user" bypass the whole purging mechanism as expected
=> (PUP-11131) Honor explicitly configured "purge_ssh_keys: false"

lib/puppet/configurer.rb, lib/puppet/transaction/report.rb, spec/fixtures/unit/configurer/last_run_report.yaml, spec/integration/application/agent_spec.rb, spec/unit/configurer_spec.rb
Previously, when Puppet failed to get its node definition, it would try to pluginsync against the agent-configured environment (usually 'production'). This is inappropriate, as it first deletes all of its plugins, and then has to re-sync them fresh from the correct environment after it switches over.
The environment is now written in the lastrunfile, which Puppet attempts to read if it fails to fetch the node definition. Environment values set with `--environment` or in puppet.conf are still prioritized over the last used environment.
=> (PUP-10216) Use last environment instead of requesting the node's environment

lib/puppet/environments.rb, spec/unit/environments_spec.rb
Previously, the cached environment list could
return environments that were no longer accessible.
This commit updates the code to remove from
cache environments that are no longer on disk.
=> (PUP-11129) remove deleted environments from cache

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
Starting with version `20.3b1`, `pip` removed available versions of a package from output when trying to install a wrong or unavailable version. Puppet is using this output to gather all available versions of a package and determine the latest one. Even though this regression got fixed in `21.1` version of `pip`, this commit adds the `--use-deprecated=legacy-resolver` argument when querying available versions of the managed package and also using any of the affected versions of `pip`.
```sh-session
➜ puppet resource package ‘colorize’ ensure=latest provider=pip3
Error: Could not get latest version: [nil, nil, nil, nil]
Error: /Package[colorize]/ensure: change from ‘1.1.0’ to ‘latest’ failed: Could not get latest version: [nil, nil, nil, nil]
package { ‘colorize’:
ensure   => ‘1.1.0’, …
```
=> (PUP-11029) Fix pip package provider to query available versions

lib/puppet/provider/package/windows.rb, lib/puppet/provider/package/windows/exe_package.rb, lib/puppet/provider/package/windows/package.rb, spec/unit/provider/package/windows/exe_package_spec.rb
Windows exe packages can now be install from a URL source.
It downloads the package locally, and runs the file with the command
options.
=> (PUP-3317) Windows exe packages can be sourced from URL

acceptance/tests/resource/user/should_create_modify_with_password.rb, lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
When managing passwords with useradd provider, the password hash appears
for a quick time when listing running processes (ps, top, strace)
Now the password is set via the chpasswd command that uses stdin to
receive the password from a temporary file. This way it won't appear on
the process list.
=> (PUP-3634) User resource password run with chpasswd

lib/puppet/face/node/clean.rb
This PR is about the fix for the bug found within `clean.rb` when the Logger is called and received a `:debug` message.  The fix is to create a debug function within the `LoggerIO` class in the file `clean.rb`.
=> (maint) Logger bug fix

lib/puppet/face/node/clean.rb
This bug arose from adding the option to use debug logging to the puppetserver-ca gem.  The error happened when the test for Puppet's 'clean' face in 6.x is ran.  The reason behind the error is because we did not have a 'debug' option in our 'LoggerIO' class in 'clean' face.  Thus, the solution to the bug is to include the 'debug' option in our logger by adding a debug function in the LoggerIO class.  Furthermore, we decided to include the 'warn' option for the logger similar to Puppet's 'clean' face in 7.x so that it's less of a hassle when merging and having a uniform code base.
=> (maint) Fix a bug with the logger in clean.rb

acceptance/tests/resource/package/ips/should_be_updateable_and_unholdable_at_same_time.rb, lib/puppet/provider/package/pkg.rb, spec/unit/provider/package/pkg_spec.rb
Before this commit, the `pkg` provider was unable to handle manifests where a package was updated and marked as unhold at the same time. This fix ensures the package is first unhold and then updated when trying to install certain versions.
=> (PUP-10956) Allow pkg provider to update and unhold package in same run

lib/puppet/defaults.rb, lib/puppet/network/http/api/indirected_routes.rb, spec/unit/network/http/api/indirected_routes_spec.rb
When an agent runs with a environment that does not exist on the server,
puppet will fail with
```
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Find /puppet/v3/node/steep-ribcage.delivery.puppetlabs.net resulted in 404 with the message: {"message":"Not Found: Could not find environment 'qwe'","issue_kind":"RUNTIME_ERROR"}
Info: Retrieving pluginfacts
Error: /File[/opt/puppetlabs/puppet/cache/facts.d]: Could not evaluate: Could not retrieve information from environment qwe source(s) puppet:///pluginfacts
Info: Retrieving plugin
Error: /File[/opt/puppetlabs/puppet/cache/lib]: Could not evaluate: Could not retrieve information from environment qwe source(s) puppet:///plugins
Info: Retrieving locales
Error: /File[/opt/puppetlabs/puppet/cache/locales]: …
```
=> (PUP-6802) Fallback to default environment when given is missing 

lib/puppet/module.rb, spec/unit/module_spec.rb
This adds a new subdirectory to the `Module` class `scripts/` which
automatically generates the functions `scripts?()`, `scripts()`, and 
`script()` on the class for retrieving available scripts. This is part
of the [scripts milestone](https://github.com/puppetlabs/bolt/issues?q=is%3Aopen+is%3Aissue+milestone%3AScripts)
for Bolt, which aims to eventually standardize on more specific file
loading from either the `files/` directory or `scripts/` directory in a
module.
This doesn't include serving from the `scripts/` directory in Puppetserver, which is a separate ticket https://github.com/puppetlabs/bolt/issues/2919
=> (PUP-11165) Backport scripts loading from a `scripts` directory

lib/puppet/node/environment.rb
Commit fecf5d69 called `Dir.chdir` followed by `Dir.glob('*')`. Commit 6d499bde
switched to `Dir.entries`, but didn't remove the `Dir.chdir`.
=> (PUP-11166) Remove unnecessary Dir.chdir

lib/puppet/environments.rb, lib/puppet/indirector/catalog/compiler.rb, spec/unit/indirector/catalog/compiler_spec.rb
Previous to this change, the `environmentpath` was set using the
internal Puppet::FileSystem.expand_path, which had the side effect
of stripping the value's trailing slash. This broke the regex used
for determining if a file met the criteria for
`inlineable_metadata?` and stopped catalogs from getting any
metadata values for files.
This change moves the trailing slash into the regex, so that the
`environmentpath` is not required to contain the slash to match. It
also ensures that the object returned by `real_path` is a Pathname,
as that is a requirement for the `get_content_uri` method.
=> (PUP-11169) Fix missing trailing `/` for versioned dirs static catalogs

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
The systemd provider should be the default since RHEL7 and going
forward. With CentOS Stream 9 coming out shortly, it should continue to
function like CentOS 8 by using the systemd provider by default.
Signed-off-by: Alex Schultz <aschultz@redhat.com>
=> (PUP-11168) Fix RHEL9 support for service provider

lib/puppet/provider/service/launchd.rb, spec/unit/provider/service/launchd_spec.rb
If a malformed but still parsable file is encountered in
`/Library/Launch{Agents,Daemons}`, ensure the parsed data is a `Hash` before
attempting to check for the `Label` key.
=> (PUP-11164) Handle a parsable but malformed plist

lib/puppet/environments.rb, lib/puppet/gettext/text_domain_service.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/node/environment.rb, spec/unit/environments_spec.rb, spec/unit/gettext/text_domain_service_spec.rb
The compiler terminus loads a text domain at the start of compilation. If `Cached#get_conf` is called it will try to clear expired environments. This doesn't
happen due to the environment cache containing strings, while `get_conf` is called with the environment's name as a symbol.
These commits add a `TextDomainService` which is called when an environment is added or cleared from the cache (similar to the expiration service). This ensures the text domain and module translations have the same lifetime as the environment.
It also adds a guard to prevent an environment from being evicted during compilation. That matches the old behavior, but it's done explicitly rather than relying on a bug.
Altogether it means the default environment_timeout=0 won't reload the environment multiple times …
=> (PUP-11158) Guard against environment expiration during compilation

spec/integration/application/filebucket_spec.rb, spec/spec_helper.rb, spec/unit/pops/parser/parse_containers_spec.rb
Reduces debug output when running tests via `bundle exec rspec spec/integration/application/filebucket_spec.rb`. The issue was partially masked when running `parallel:spec`.
Remove filtering of tests using the `:broken` filter. Just use `pending`.
=> (maint) reduce debug output clutter and remove 'broken' test filtering

spec/shared_behaviours/documentation_on_faces.rb, spec/unit/indirector/store_configs_spec.rb, spec/unit/interface/action_spec.rb, spec/unit/network/authstore_spec.rb, spec/unit/ssl/certificate_request_spec.rb
Deletes pending tests that are useless, tested elsewhere or deleted in 7.
Cherrypicks commit to fix pending CSR tests.
There is one pending test left (which is included 5 times, once for each checksum type). I think it's related to PUP-10122, when collecting file metadata for a link, so I kept it.
=> (maint) Cleanup pending specs

lib/puppet/environments.rb, spec/unit/environments_spec.rb
Trying to compile a catalog using a DirectoryLoader failed because it doesn't
implement the guard/unguard methods. Add them to the base EnvironmentLoader
module that is mixed into various environment loaders, and overriden in the
Cached loader.
=> (PUP-11158) Implement guard methods in base loader module

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
At the start of the configurer run, puppet pushes
its configured environment or the server-specified
environment onto the context.
If pluginsync causes environment to change,
then the agent switches to the new environment but
the new environment is not pushed onto the context,
leaving the old environment set.
This commit updates the `lib/puppet/configurer.rb`
to push the new environment after the convergence
is done.
=> (PUP-10308) Fix Puppet.lookup(:current_environment)

lib/puppet/pops/serialization/to_data_converter.rb, lib/puppet/transaction/persistence.rb, spec/unit/pops/serialization/to_from_hr_spec.rb
Binary, Sensitive, etc deferred results can corrupt the transaction
store if not converted with Puppet::Pops::Serialization::ToDataConverter
before saving to the file.
=> (PUP-10820) Convert data before saving to transactionstorefile

lib/puppet/environments.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/node/environment.rb, spec/unit/environments_spec.rb, spec/unit/indirector/catalog/compiler_spec.rb
This PR is similar to what was attempted in PR #8673 except:
1. It preserves the existing way of managing text domains via compilation using `node.environment.with_text_domain`
2. It defines noop guard/unguard methods on the base EnvironmentLoader module.
3. Environments are not expired when guard/unguard are called
4. An environment won't be evicted if it is guarded but marked as expired by the cache expiration service (puppetserver)
=> (PUP-11158) Guard environment from reloading

lib/puppet/file_serving/configuration.rb, lib/puppet/file_serving/configuration/parser.rb, lib/puppet/file_serving/mount/scripts.rb, spec/unit/file_serving/configuration/parser_spec.rb, spec/unit/file_serving/configuration_spec.rb, spec/unit/file_serving/mount/scripts_spec.rb
This adds a file serving mount "scripts" that loads scripts from the
`scripts/` directory of the specified module that is one of the default mounts. This is for use by
Puppetserver to serve file content and metadata for scripts through a
`scripts` mount_point.
=> (PUP-11187) Add `scripts` file serving mount

acceptance/tests/direct_puppet/cached_catalog_remediate_local_drift.rb, acceptance/tests/direct_puppet/static_catalog_env_control.rb, acceptance/tests/environment/custom_type_provider_from_same_environment.rb, acceptance/tests/environment/variables_refreshed_each_compilation.rb, acceptance/tests/face/parser_validate.rb, acceptance/tests/i18n/modules/puppet_agent.rb, acceptance/tests/i18n/modules/puppet_agent_cached_catalog.rb, acceptance/tests/i18n/modules/puppet_agent_with_multiple_environments.rb, acceptance/tests/language/binary_data_type.rb, acceptance/tests/language/exported_resources.rb, acceptance/tests/language/functions_in_puppet_language.rb, acceptance/tests/language/pcore_generate_env_isolation.rb, acceptance/tests/language/sensitive_data_type.rb, acceptance/tests/language/server_set_facts.rb, acceptance/tests/loader/autoload_from_resource_type_decl.rb, acceptance/tests/loader/resource_triggers_autoload.rb, acceptance/tests/lookup/config3_interpolation.rb, acceptance/tests/lookup/config5_interpolation.rb, acceptance/tests/lookup/hiera3_custom_backend.rb, acceptance/tests/lookup/lookup.rb, acceptance/tests/lookup/lookup_rich_values.rb, acceptance/tests/lookup/merge_strategies.rb, acceptance/tests/lookup/v3_config_and_data.rb, acceptance/tests/lookup/v4_hieradata_with_v5_configs.rb, acceptance/tests/pluginsync/feature/pluginsync_should_sync_features.rb, acceptance/tests/reports/corrective_change_new_resource.rb, acceptance/tests/reports/corrective_change_outside_puppet.rb, acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb
Recent work allowed the agent to skip node requests by inspecting a
lastrunfile if it exists and start the agent check-in process with the
environment listed there. However, the acceptance tests often create
dummy enviroments and do not clean up the lastrunfile.
A first pass updated many tests to remove the lastrunfile on all agents
if they used a temporary environment. However, several were missed as
the agent testing will only test a subset of the server tests. In an
attempt to quickly rectify the situation this patch audits all
acceptance tests that use, or mention that they should use,
`mk_tmp_environment_with_teardown` and extends their teardowns to use
the existing pattern for removing the lastrunfile.
=> (maint) Teardown remaining lastrunfile after using tmp env

spec/fixtures/integration/l10n/envs/prod/modules/demo/Gemfile, spec/fixtures/integration/l10n/envs/prod/modules/demo/Rakefile, spec/fixtures/integration/l10n/envs/prod/modules/demo/lib/puppet/functions/l10n.rb, spec/fixtures/integration/l10n/envs/prod/modules/demo/locales/config.yaml, spec/fixtures/integration/l10n/envs/prod/modules/demo/locales/ja/puppet-l10n.po, spec/fixtures/integration/l10n/envs/prod/modules/demo/locales/puppet-l10n.pot, spec/fixtures/integration/l10n/envs/prod/modules/demo/metadata.json, spec/integration/l10n/compiler_spec.rb, spec/shared_contexts/l10n.rb
While working on PUP-11158 I found that module translations were not present if the environment was reloaded during compilation. This adds an integration test to ensure a function in a module can generate a localized message using translations from the module's `locale` directory. There are beaker tests, but the feedback cycle is long.
Also note translations are disabled in spec tests, see https://github.com/puppetlabs/puppet/blob/846e5e41d50d363e738658588c497313a59900a5/spec/spec_helper.rb#L18-L21 so this provides a way for integration tests to selectively enable localizations using a shared context.
=> (maint) Add l10n integration test

acceptance/tests/environment/environment_scenario-bad.rb, lib/puppet/configurer.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/indirector/terminus.rb, lib/puppet/network/http/api/indirected_routes.rb, spec/integration/configurer_spec.rb, spec/lib/puppet_spec/puppetserver.rb, spec/unit/configurer_spec.rb
Previous to this PR, when an agent agent starts a run with an environment not
available on the server, it will also try to pluginsync with the unexistent
environment.
Now, a request is sent to the server checking if there is anything to
pluginsync, or if the environment even exists.
=> (PUP-6802) Skip pluginsync if node request fails with 404 error

spec/integration/application/agent_spec.rb
Tests sometimes failed on Windows because it was possible for the thread to exit
before the agent started up. If the thread didn't exist, then the agent could
forcibly acquire the stale lock and continue the run, failing to connect to a
non-existent server.
This extends the maximum amount of time the worker thread hold onto the lock.
=> (maint) Increase wait time

lib/puppet/configurer.rb, lib/puppet/defaults.rb, spec/unit/configurer_spec.rb
Puppet doesn't warn the user when the facts exceed certain limits. This pull request 
adds checks that compare the current sizes and lengths of the facts with a series of limits.
Options for the user to change the values for these limits were also added.
The limits implemented so far are the following:
1. `fact_name_length_soft_limit` - The soft limit for the length of a fact name
2. `fact_value_length_soft_limit` - The soft limit for the length of a fact value
3. `top_level_facts_soft_limit` - The soft limit for the number of top level facts
4. `number_of_facts_soft_limit` - The soft limit for the total number of facts.
5. `payload_soft_limit` - The soft limit for the size of the fact hash after its encoded
Brief explanation on how we check each limit:
1. To check the length of the …
=> (PUP-11088) Warn if fact limits are exceeded

lib/puppet/configurer.rb, lib/puppet/http/service/compiler.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/indirector/catalog/rest.rb, spec/fixtures/integration/application/agent/lib/facter/agent_spec_role.rb, spec/integration/application/agent_spec.rb, spec/lib/puppet_spec/puppetserver.rb, spec/unit/configurer_spec.rb, spec/unit/http/service/compiler_spec.rb, spec/unit/indirector/catalog/compiler_spec.rb, spec/unit/indirector/catalog/rest_spec.rb
The agent now sends a `check_environment` query parameter when requesting its catalog via the v3 endpoint. The server-side indirector code converts the query parameter to an indirector request option and passes that to the compiler catalog terminus. If the option is `true`, then the server will check if the agent's current environment, that it last pluginsynced in, matches the server-specified environment, as determined by the node terminus, such as an ENC or PE Classifier. If the environments are mismatched, then the terminus short-circuits catalog compilation, returning an empty catalog with the server-specified environment. The agent will detect the mismatch, switch its current environment, and retry its convergence loop.
Prior to this change, if manifests in the server-specified …
=> (PUP-9570) Short-circuit compilation if the agent's current env doesn't match the server specified env

lib/puppet/type/exec.rb
Make it more explicit that the `onlyif` and `unless` commands of an `exec` resource have to run during noop Puppet runs.
=> (PUP-11199) Improve exec noop documentation

lib/puppet/module/plan.rb, lib/puppet/module/task.rb, spec/lib/puppet_spec/modules.rb, spec/unit/module_spec.rb
This adds the `scripts` mount point to the list of valid mount point to
load files specified under a Tasks `files` metadata from.
=> (PUP-11200) Allow loading Task files from scripts mount

acceptance/tests/environment/feature_branch_configured_environment.rb, acceptance/tests/environment/use_last_server_specified_environment.rb, lib/puppet/configurer.rb, lib/puppet/transaction/report.rb, spec/unit/configurer_spec.rb
With the recent changes in PUP-10216, the agent stores the last used environment in `last_run_summary.yaml`. If the next run does not specify an environment on the CLI, then the last used environment always takes precedence over the environment specified in puppet.conf.
This change makes an exception for the agent-specified case so that the second run only uses the environment from the previous run if it was server-specified. Otherwise, the agent should start in its configured environment (from puppet.conf) or default to "production".
=> (PUP-11201) Refine when the last used environment is used

acceptance/tests/resource/user/should_destroy_with_managehome.rb, lib/puppet/provider/aix_object.rb, lib/puppet/provider/user/aix.rb, spec/unit/provider/user/aix_spec.rb
Before this commit, when a manifest that deletes an AIX user is applied, with `managehome` parameter set to true, puppet would not delete the home directory for that user because it was using `rmuser`, and it has no flag to delete home directories.
This commit adds a simple folder removal of user home directory (when `managehome` is enabled) as `userdel` also removes the user from
`/etc/security/passwd`, and `rmuser` does not. Puppet will not remove user home directory if this is relative, '/', symlink or contains home directories of other users.
=> (PUP-11170) User => absent deletes homedir on AIX (when managehome=true)

lib/puppet/provider/user/aix.rb, spec/unit/provider/user/aix_spec.rb
This pull requests adds the `-p` flag to the `rmuser` command, to ensure that the user's password was deleted.
=> (PUP-11190) Fix user resource not removing password on AIX agents

lib/puppet/configurer.rb, lib/puppet/indirector/indirection.rb, spec/integration/application/agent_spec.rb, spec/integration/configurer_spec.rb, spec/integration/transaction/report_spec.rb, spec/unit/configurer_spec.rb, spec/unit/indirector/indirection_spec.rb
Always cache the last run report, even if the REST request to the report server fails.
=> (PUP-6708) Ensure last run report is always saved

lib/puppet/pops/lookup/lookup_adapter.rb, spec/unit/functions/lookup_spec.rb
If module lookup_options are empty, then lookup failed with:
NoMethodError: undefined method `each_pair' for nil:NilClass
Now module lookup_options are ignored in the same way they would be if they were not there.
Also adds some tests to assert environment and module lookup_options reject invalid `LookupKey` data types.
=> (PUP-10890) Gracefully ignore empty module lookup_options

lib/puppet/file_system/file_impl.rb, spec/unit/file_system_spec.rb
Since ASCII characters are single bytes, there is no need for a BOM to detect byte ordering (LSB/MSB). Before this commit, `Puppet::FileSystem.read_preserve_line_endings` method was always adding this and causing the following warning:
```
BOM with non-UTF encoding US-ASCII is nonsense
```
=> (PUP-11196) Remove BOM warning when using US-ASCII encoding

spec/unit/configurer_spec.rb
CI was failing due to a fact of size 410 not matching the regex [1-9]*. Use \d
to match digits.
=> (maint) Accept 0 digit

Gemfile
Puppet does not depend on the ronn or gettext-setup gems, though they
are used in CI to automate man page generation and updating the pot
file, respectively. So change the group to be optional. To include the
gems use `bundle install --with documentation`.
=> (maint) Make documentation group optional

lib/puppet/facter_impl.rb, lib/puppet/runtime.rb, spec/unit/facter_impl_spec.rb, spec/unit/puppet_spec.rb
Add support for multiple facter implementations and
provide default FacterImpl that is used to delegate
all methods to Facter.
Any client can register its own Facter implementation:
```
Puppet.initialize_settings([], true, true, facter: facter_impl)
```
=> (PUP-11216) Add support for multiple facter impl

lib/puppet/settings/file_setting.rb, spec/unit/settings/file_setting_spec.rb
File-based settings used to support a `create` option, but that was removed
awhile ago. Remove the unused accessor. Directories on the other hand are always
created/managed, since they are often the parent of a file-based setting.
=> (PUP-3817) Remove unused create_files

lib/puppet/test/test_helper.rb, spec/unit/network/http/connection_spec.rb, spec/unit/network/http_pool_spec.rb
https://github.com/puppetlabs/puppet/pull/8749/files#diff-91bcbee7bf547ed6ab2546124a1a87c5e34d8189ef781252293b65725ea40bddR145 introduced a change
on how we load runtime services, setting them
upfront before running any tests. This breaks the
ability to mock the implementations and enforces
specific implementations to be injected when Puppet
is initialized. To avoid breaking other projects,
do not load the HttpClient for now, but let it be
lazy initailized as it was before #8749.
=> (PUP-11217) do not eager load Puppet's HttpClient

lib/puppet/test/test_helper.rb, spec/unit/network/http/connection_spec.rb, spec/unit/network/http_pool_spec.rb
https://github.com/puppetlabs/puppet/pull/8749/files#diff-91bcbee7bf547ed6ab2546124a1a87c5e34d8189ef781252293b65725ea40bddR145 introduced a change
on how we load runtime services, setting them
upfront before running any tests. This breaks the
ability to mock the implementations, and enforces
specific implementations to be injected when Puppet
is initialized. To avoid breaking other projects,
do not load the HttpClient for now, but let it be
lazy initailized as it was before #8749.
=> (PUP-11217) do not eager load http_client

lib/puppet/util/json.rb, spec/unit/network/formats_spec.rb
If the `MultiJson` gem was absent, then `Puppet::Util::Json.dump` failed if
given an array or hash containing an indirected object. The issue occurred because the
json library will call the object's `to_json` method (since it's not a primitive
type) passing an instance of `JSON::State` as the `options` argument. The
`to_json` method for indirected objects is implemented in
`Puppet::Network::FormatSupport`, and that calls `Puppet::Util::Json.dump`
recursively.
Now we detect if the `options` is a `JSON::State` object, similar to how the
JSON library detects if it's being called recursively[1].
https://github.com/ruby/ruby/blob/v2_7_3/ext/json/generator/generator.c#L1071-L1088
=> (PUP-11237) Detect recursive json generation

lib/puppet/type/service.rb, spec/unit/type/service_spec.rb
ab3870c allows provider to be asked for default `timeout` value for syncing service properties when it has one instead of always defaulting to `10`. This was causing issues on Windows when services were taking more than 10 seconds to change state or sync properties instead of waiting for 30 seconds as the provider was set to.
https://github.com/puppetlabs/puppet/commit/ba93e860e725a2faef084fe820dae2aa90028dbb allows the `timeout` parameter of service to be String and munges it to Integer to be further used. This seemed like a common problem when trying to manage a service from cli and specifying a timeout such as:
```sh-session
puppet resource service puppet ensure=running timeout=20
```
Before this commit, above command was raising:
```sh-session
Error: Could not run: Parameter timeout …
```
=> (PUP-10925) Fix service timeout parameter default value for syncing properties

lib/puppet/provider/user/useradd.rb, spec/unit/provider/user/useradd_spec.rb
Prior to this, when managing a `user` resource with `forcelocal => true`, directory services (i.e. LDAP) enabled on the host, and a duplicate username in LDAP and locally, the `shell` and `home` attributes of the user would be checked against their values from LDAP, not from `/etc/passwd`.
This caused Puppet runs to always show that the `shell` and `home` attributes were changing on each run if LDAP had different values for the user than the Puppet code did. Puppet would correctly set the values for those attributes in `/etc/passwd`, but they'd appear to change on each run.  The `user` resource was no longer idempotent.
After this, the values for `shell` and `home` will be checked against the local `/etc/passwd` file when `forcelocal => true` is set on a `user` resource.
Fixes …
=> (PUP-11241) Check against a user's local 'home' and 'shell' when forcelocal is true

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
Previously, if the agent run decided to use the last server environment, it would not push the current environment and loaders onto the context.
Metadata requests that don't specify an environment will cause the indirector to fall back to the environment stored in the [context](https://github.com/puppetlabs/puppet/blob/3828aabe8d32368faa5cdc1a428189d0cb117e52/lib/puppet/indirector/request.rb#L33), which in our case is [the environment the agent started in](https://github.com/puppetlabs/puppet/blob/3828aabe8d32368faa5cdc1a428189d0cb117e52/lib/puppet/application/agent.rb#L389-L401) instead of the converged one.
Push the current environment and loaders if we're using the last server environment, and extract the logic to a separate method.
=> (PUP-11265) Push last used environment and loaders onto the context

spec/unit/provider/package/pkg_spec.rb
The package tests in main don't rely on CHILD_STATUS anymore, so adapt
the test to return ProcessOutput explicitly.
=> (maint) Return ProcessOutput instead of using CHILD_STATUS

lib/puppet/file_system.rb, lib/puppet/util/autoload.rb, spec/unit/util/autoload_spec.rb
Previously, puppet failed to load if the current working directory was a short
Windows path. This was due to trying to require `Puppet::Util::Uniquefile` using
its long and short path. This regression was introduced with the move to
require_relative.
The `Autoload.files_in_dir` method is expected to return relative paths that are
contained within the `dir` argument. For example, returning an array containing
`puppet/provider/exec/posix`.
However, if the `dir` argument contained a short Windows path and the short path
wasn't the last directory component, then the `files_in_dir` method returned a
relative path of the form, because `Dir.glob` always returns long paths:
../../../../../../../Program Files/Puppet Labs/Puppet/puppet/lib/ruby/vendor_ruby/puppet/provider/exec/posix
Later the …
=> (PUP-11184) Expand to long paths

benchmarks/many_modules/benchmarker.rb, benchmarks/many_modules/module/init.pp.erb, benchmarks/many_modules/module/role.pp.erb, lib/puppet/util/monkey_patches.rb
The unoptimized version makes N+1 substrings where N is the number of
path components:
/a/b/c
/a/b
/a
''
It's worse on Windows due to the long install path. The optimization was
released in Ruby 3, so make it conditional.
The `many_modules` benchmark is reduced by ~1MB due to 21K fewer Pathname allocations
```
< Total allocated: 182369970 bytes (2324118 objects)
> Total allocated: 181314432 bytes (2303673 objects)
allocated memory by gem
-----------------------------------
<  28202981  pathname
>  27147491  pathname
allocated objects by gem
-----------------------------------
<    445128  pathname
>    424684  pathname
```
=> (PUP-11311) Monkey patch Pathname for Ruby < 3

lib/puppet/functions/versioncmp.rb, lib/puppet/util/package.rb, spec/unit/functions/versioncmp_spec.rb
Before 356a602994a6d757aa48045fcbfb0043aa307b5b, `Puppet::Util::Package.versioncmp()` thought `11.0` is greater than `11`. Now it can trim trailing zeroes and dots from version before comparing, by setting the new argument `ignore_trailing_zeroes` to true. By default it is kept to `false` for backwards compatibility reasons.
04d94f23af5590c2ad60cfff113e81fc83407cce updates the `Puppet::Util::Package.versioncmp()` method to use more recent Ruby practices and removes unnecessary checks.
=> (PUP-11235) versioncmp() strip redundant numbers

spec/shared_contexts/l10n.rb
Previously, if a test set `Puppet[:disable_i18n] = true`, then the l10n
integration test would fail, because the `gettext_disabled` instance variable
was still true. This can be reproduced in 6.x via:
$ bundle exec rspec spec/unit/node/environment_spec.rb \
spec/integration/l10n/compiler_spec.rb
..
expected: "それは楽しい時間です"
got: "IT'S HAPPY FUN TIME"
Similarly, running these in order would fail, because the default text domain
was deleted but never readded:
$ bundle exec rspec spec/unit/gettext/config_spec.rb \
spec/integration/l10n/compiler_spec.rb
..
FastGettext::Storage::NoTextDomainConfigured:
Current textdomain (nil) was not added, use FastGettext.add_text_domain !
This updates the l10n shared context to more completely restore l10n support.
=> (maint) Fix order dependent spec failures

benchmarks/many_modules/benchmarker.rb
Use j not i when naming the manifest, so the name matches the class.
=> (maint) Ensure benchmark's manifest matches class name

lib/puppet/concurrent/thread_local_singleton.rb
Thread#thread_variable? sometimes returns false[1] on MRI, which causes the
ThreadLocalSingleton to not behave like a singleton. Instead call `thread_variable_get`
to see it's set. This means the singleton value can't be `nil`, but we
never do that in practice.
Kudos to @mikaelsmith for finding the ruby bug!
[1] https://bugs.ruby-lang.org/issues/16906
This reduces the many_modules benchmark (updated in https://github.com/puppetlabs/puppet/pull/8792) by about 37MB on MRI:
```
Total allocated: 184825386 bytes (2331704 objects)
allocated memory by file
-----------------------------------
36832308  /home/josh/work/puppet/lib/puppet/pops/parser/lexer2.rb
```
```
Total allocated: 147626146 bytes (1993015 objects)
allocated memory by file
-----------------------------------
5847972 …
```
=> (PUP-11236) Work around Thread#thread_variable? bug

lib/puppet/graph/simple_graph.rb
I noticed a couple of misleading comments while skimming the code:
- The comment for `#dependencies` is wrong - it describes *dependents*, not *dependencies*.
- `#walk` implements depth-first search, not breadth-first.
=> (docs) Fix incorrect comments in simple_graph.rb

lib/puppet/concurrent/thread_local_singleton.rb, lib/puppet/provider/service/init.rb, lib/puppet/util/windows.rb, lib/puppet/util/windows/service.rb, spec/unit/provider/service/gentoo_spec.rb, spec/unit/provider/service/init_spec.rb, spec/unit/provider/service/openwrt_spec.rb, spec/unit/provider/service/redhat_spec.rb
* Commits:
- (PUP-11236) Work around Thread#thread_variable? bug
- (PUP-11319) Move `DEFAULT_TIMEOUT` constant for Windows services
- (maint) Rewrite openwrt_spec.rb to avoid overstubbing
- (maint) Update init provider to use Puppet::FileSystem
- (PUP-11313) Prevent puppet from executing directories
* Conflicts:
- lib/puppet/util/windows/service.rb - due to constants and structs
still existing in the file on 6.x but not on main (when moving the
DEFAULT_TIMEOUT constant in 44eb687)
=> (maint) Merge 6.x into main

benchmarks/many_modules/benchmarker.rb, benchmarks/many_modules/module/init.pp.erb, benchmarks/many_modules/module/role.pp.erb, lib/puppet/pops/parser/code_merger.rb
Commit af560639d0 flattened the code produced by the code merger to avoid
a deeply nested tree, but it used += to concatenate the children.
Commit f2ae1b0404 switched to `+` which eliminated the Lint/UselessAssignment
rubocop warning, but still created a new Array containing a copy of the memo and
the parsed class' code. This meant every iteration copied the memo and the memo
increased in size each time.
This commit uses `flat_map`, which correctly appends a single element or an
array of elements to the `children` array and has the same memory profile as
calling concat (for arrays) or << (for an element).
The many_modules benchmark shows a reduction in allocated memory by 3.2MB, all of which comes from memory allocated by Arrays.
Before
```
Total allocated: 157407598 bytes (2131019 …
```
=> (PUP-11318) Use flat_map not +

lib/puppet/application/lookup.rb, spec/integration/application/lookup_spec.rb
5cde767dc1e67afc729b4ff6cdf5d603e02228ae added the ability to use facts
from a fact file, but those facts were added after the classification
happened, meaning that any facts used as rules for classification
couldn't be overridden with the facts from the fact file.
This commit fixes this issue by querying pdb to get the target node's
facts, and merge the facts provided from the fact file, before the
classification happens.
=> (PUP-10435) Facts provided in a file can't be used for classification

acceptance/tests/parser_functions/puppet_lookup_cmd.rb, lib/puppet/application/lookup.rb, spec/integration/application/lookup_spec.rb, spec/unit/application/lookup_spec.rb
Previously, puppet lookup would return incorrect results for any target node that had no facts cached.
For example when using the `Per-node data` hierarchy, with the path to the data fail being the value of `$trusted[certname]`, a node that had the said fact cached would return the correct data from its data file, but a node which didn't have any facts cached, would default to a common configuration file, outputting the data from there.
This is misleading since it doesn't error out, giving the impression that the run went well, when in actuality it failed to fetch the correct data.
This commit fixes this issue by failing the run the moment we are able to see that the target node has no cached facts.
TODO:
=> (PUP-7362) Fail fast if there are no facts for a node

.gemspec, acceptance/tests/face/loadable_from_modules.rb, acceptance/tests/modules/changes/missing_checksums_json.rb, spec/fixtures/unit/forge/bacula.json, spec/unit/forge/module_release_spec.rb
This updates test fixtures for puppet module metadata to use https instead of
git. Note `.git` extension is removed, because that's a redirect to a URL that
doesn't have the extension.
=> (maint) Remove references to git scheme

.gemspec, Gemfile, acceptance/Gemfile, acceptance/tests/face/loadable_from_modules.rb, acceptance/tests/modules/changes/missing_checksums_json.rb, acceptance/tests/parser_functions/puppet_lookup_cmd.rb, lib/puppet/application/lookup.rb, spec/fixtures/unit/forge/bacula.json, spec/integration/application/lookup_spec.rb, spec/unit/application/lookup_spec.rb, spec/unit/forge/module_release_spec.rb
* commit 'fd0a86e23afa3c504d5645d117d2290da07f849b':
(maint) update Gemfile locate_for
(maint) Remove references to git scheme
(PUP-7362) Fail fast if there are no facts for a node
(PUP-10435) Facts provided in a file can't be used for classification
=> (maint) Merge up fd0a86e to main

acceptance/tests/agent/agent_fails_with_unknown_resource.rb, api/schemas/catalog.json, benchmarks/serialization/catalog.json, lib/puppet/defaults.rb, lib/puppet/http/client.rb, lib/puppet/http/redirector.rb, lib/puppet/parser/resource.rb, lib/puppet/pops/evaluator/runtime3_resource_support.rb, lib/puppet/resource.rb, lib/puppet/resource/catalog.rb, spec/fixtures/integration/application/agent/cached_deferred_catalog.json, spec/integration/parser/pcore_resource_spec.rb, spec/unit/configurer_spec.rb, spec/unit/http/client_spec.rb, spec/unit/resource/catalog_spec.rb, spec/unit/resource_spec.rb
(PUP-11328) Get the environment's name without loading the environment
(PUP-11328) Fallback to node request in configurer
(PUP-11319) Move `DEFAULT_TIMEOUT` constant for Windows services
(PUP-9561) Optimize parameter validation for blocks
(PUP-11209) Puppet agent silently skips unknown resources.
(PUP-11188) Do not add auth and cookie header when redirecting
=> (maint) Merge 6.25.1 release to 6.x 

lib/puppet/application/lookup.rb, spec/unit/application/lookup_spec.rb
When using puppet lookup with --facts, if the facts file overrides any of
hostname, domain, fqdn, clientcert, then it must override all of them.
=> (PUP-8220) puppet lookup based on factfile restriction

lib/puppet/file_system.rb, lib/puppet/file_system/file_impl.rb, lib/puppet/file_system/jruby.rb, lib/puppet/file_system/windows.rb, spec/unit/file_system_spec.rb
Raise ArgumentError if passed an invalid path as is done for other Puppet::FileSystem methods.
Eliminate some Pathname copying when calling `Puppet::FileSystem.replace_file`
=> (PUP-11345) Assert path in Puppet::FileSystem.chmod

lib/puppet/type/file/group.rb, lib/puppet/type/file/owner.rb, spec/unit/type/file/group_spec.rb, spec/unit/type/file/owner_spec.rb
If the file owner or group can't be resolved and we're running in noop, then
return false, so puppet knows the properties' current and desired states don't
match.
=> (PUP-3907) Don't require the file owner/group to exist in noop

lib/puppet/resource.rb
Remove constant redefinition warnings introduced in automerge f8ceb05064
=> (maint) Remove duplicate constants

acceptance/tests/resource/file/handle_fifo_files.rb, lib/puppet/type/file/data_sync.rb
This commit makes the `retrieve_checksum` method from `lib/puppet/type/file/data_sync.rb` to skip FIFO and socket files since their contents can't be retrieved to generate a checksum and causes puppet to hang indefinitely.
=> (PUP-1460) Skip retrieving checksum for FIFO and socket files

acceptance/tests/parser_functions/puppet_lookup_cmd.rb, lib/puppet/application/lookup.rb
This commit changes the priority of the `--environment` option by
skipping the classification whenever the flag is specified. This allows
the user to bypass the ENC enforced environment with the cli option.
=> (PUP-7479) Prioritize `--environment` flag over ENC for lookup

lib/puppet/file_system/path_pattern.rb, lib/puppet/pops/validation/checker4_0.rb
`PathPattern` now caches its `Pathname#to_s` eliminating 4 copies during validation.
It also no longer uses `Pathname#each_filename` to check for `..`, as that method is implemented using `Pathname#chop_basename` and is slow.
Memory allocation for the `many_modules` benchmark is reduced by 2.3MB due to fewer calls to `Pathname#to_s`
Before
```
Total allocated: 118278927 bytes (1750119 objects)
Total retained:  7348796 bytes (103634 objects)
allocated memory by gem
-----------------------------------
91126921  puppet/lib
21367896  pathname
...
allocated memory by file
-----------------------------------
21367896  /home/josh/.rbenv/versions/2.7.3/lib/ruby/2.7.0/pathname.rb
...
1024342  /home/josh/work/puppet/lib/puppet/file_system/path_pattern.rb
...
allocated memory by location …
```
=> (PUP-11312) Reduce Pathname allocation

lib/puppet/file_system/uniquefile.rb, spec/unit/file_system/uniquefile_spec.rb
Uniquefile is based on Ruby's Tempfile and it was already fixed in Ruby[1]
[1] https://github.com/ruby/ruby/commit/6f8bce9eff15b527c87e1b13312db2fbf0b504f4
=> (PUP-5800) Don't file expand uniquefile's prefix

lib/puppet/ssl/verifier.rb, lib/puppet/util/monkey_patches.rb
Ruby now correctly sets the store_context.error when the cert is mismatched[1], [2]. So
in that case raise the expected CertMismatchError.
We also have to monkey patch the ruby constant, which was only recently added to
match openssl 1.1[3].
[1] https://github.com/ruby/openssl/issues/244
[2] https://github.com/ruby/openssl/commit/74ef8c0cc56b840b772240f2ee2b0fc0aafa2743
[3] https://github.com/ruby/openssl/commit/65ea09c403cc216d8e14d966b78fbc1bea16810d
=> (maint) ruby-openssl now sets store_context.error

lib/puppet/pops/serialization/to_data_converter.rb, lib/puppet/transaction/persistence.rb, spec/unit/pops/serialization/to_from_hr_spec.rb, spec/unit/transaction/persistence_spec.rb
Revert changes introduced for PUP-10820 and fix binary values in the persistence store a different way
=> (PUP-11321) Allow loading of safe classes from the persistence store

.github/workflows/rspec_tests.yaml
Update Windows environment from windows-2106 to windows-2019
https://github.com/actions/virtual-environments/issues/4312
=> (maint) update github actions windows environment

.github/workflows/rspec_tests.yaml, lib/puppet/pops/serialization/to_data_converter.rb, lib/puppet/ssl/verifier.rb, lib/puppet/transaction/persistence.rb, lib/puppet/util/monkey_patches.rb, spec/unit/pops/serialization/to_from_hr_spec.rb, spec/unit/transaction/persistence_spec.rb
- commit 'a13074652077766c8dfd535d6f6765d6b6005a21':
- (packaging) Updating manpage file for 6.x
- (PUP-11321) Allow loading of safe classes from the persistence store
- Revert "Merge pull request (PUP-10820) Convert data before saving to transactionstorefile #8699 from Dorin-Pleava/PUP-10820"
- (maint) ruby-openssl now sets store_context.error
=> (maint) Manual mergeup

lib/puppet/application/lookup.rb, spec/integration/application/lookup_spec.rb
d48d683 added the ability to classify nodes based on trusted facts (certname, fqdn, domain). However, this didn't apply to custom extensions.
Register Puppet OIDs inside the lookup application, then parse the certificate and create a trusted information object to get the correct list of custom extensions.
If a value for `certname` is provided in a fact file for the lookup application, use it when creating the trusted information object. This makes it possible to override `trusted.certname` for classification.
=> (PUP-8094) Make lookup aware of certificate extensions

acceptance/tests/resource/user/should_correctly_ensure_depending_resources.rb, lib/puppet/type/user.rb, spec/unit/transaction/additional_resource_generator_spec.rb
This commit moves the moment when `ssh_authorized_key` resources are created from the beginning of the user type evaluation, to the end of it to avoid order dependency issues.
PUP-11067 fixed the case where a user gets created and at the same time any ssh keys associated are removed in the same manifest. To achieve this, the ensure property gained priority over generating the ssh key removal resources as these depend on the user home location.
PUP-11320 allows once again natural priority of the user properties and parameters but moves the `ssh_authorized_key` resources creation at the end of the user type flow, after all user properties and parameters were resolved.
=> (PUP-11320) Move `ssh_authorized_key` resources creation at the end

acceptance/tests/resource/file/handle_fifo_files_when_recursing.rb, lib/puppet/file_serving/metadata.rb
This commit allows retrieval of attributes for fifo and socket files when recursing over given path from a `file` resource. This avoids below error:
```sh-session
Error: /Stage[main]/Main/File[/given_folder_path]: Failed to generate additional resources using ‘eval_generate’: Cannot manage files of type fifo
```
When applying:
```puppet
file { "/given_folder_path":
ensure  => present,
recurse => true,
owner   => Luchi
}
```
Same behaviour and fix applies to `socket` files.
=> (PUP-4045) Allow retrieval of attributes for fifo and socket files

api/docs/http_report.md
The current report format is version 12. It also changes the grammar.
=> (maint) Update report format version in HTTP report doc

lib/puppet/face/generate.rb, lib/puppet/generate/type.rb, spec/unit/face/generate_spec.rb
Previously, puppet generate would return an exit code with the value of
0 even when failing to generate a new custom type.
```
> puppet generate types
Notice: Generating Puppet resource types.
Error: <envpath>/modules/my_module/lib/puppet/type/my_module.rb: title patterns that use procs are not supported.
> echo $?
0
```
This commit fixes this issue by creating a new Puppet::Generate method
that checks whether a type has raised an error or not. Since we want to
continue checking inputs even if one has failed, this comes in handy
since we can exit at the end of the run, keeping the functionality the
same.
=> (PUP-11078) Puppet generate should return non-zero when failing

lib/puppet/type/user.rb
* commit '2a7b3ad1e2ef20b19b910029994cfe1f78d39839':
(PUP-11380) Ignore authorized key purging if home doesn't exist yet
Revert "(PUP-11067) Prioritize user type `ensure` before `purge_ssh_keys`"
Revert "(PUP-11320) Move `ssh_authorized_key` resources creation at the end"
* Conflicts:
lib/puppet/type/user.rb
=> (maint) Merge up 6.x to main

acceptance/tests/resource/service/init_on_systemd.rb
Red Hat 9 does not ship with /etc/init.d, causing this test to fail. We have excluded it as a platform for this particular test.
See also: PA-4121
=> (maint) Excludes RHEL9 from init_on_systemd test

Gemfile, lib/puppet/util/yaml.rb
The non-keyword argument variant was deprecated in Psych 3.1.0 and has been
removed in 4.0.0 (https://github.com/ruby/psych/commit/0767227051dbddf1f949eef512c174deabf22891).
Encountered this in a downstream custom Debian packaging of Puppet server with Psych 4.0.3 and manifested as an error regarding too many arguments (1 vs 5) during global `lookup_options` lookup resulting in catalog compilation failure.
=> (PUP-11405) Replace deprecated/changed Psych YAML methods, pin rdoc

acceptance/tests/parser_functions/puppet_lookup_cmd.rb, lib/puppet/application/lookup.rb, spec/integration/application/lookup_spec.rb
This commit moves the entire trusted information logic in the case where
we have the `compile` option enabled and we are not a `plain` terminus,
since any other case does not need the said `trusted_information`
context.
=> (PUP-11402) Puppet lookup fails when used locally

lib/puppet/configurer.rb, lib/puppet/node.rb, spec/unit/node_spec.rb
Previosuly, if an environment instance is set on a node, then the
`Node#environment_name` returns nil, but `Node#environment` returns the
instance whose name is the expected symbolic value.
This commit fixes this inconsistency, by removing the
`instance_variable_defined?` check, when setting the environment.
=> (PUP-11330) Puppet::Node#environment_name may return the wrong value

lib/puppet/configurer.rb, lib/puppet/defaults.rb, spec/unit/configurer_spec.rb
This commit adds a new setting that allows to choose between using the
environment data from the `last_run_summary.yaml` file or just do the node
request and ignore all the other environment data.
TO DO before merging:
=> (PUP-11379) Agent no longer calls local enc script

acceptance/tests/server_returns_pson_when_preferred_serialization_set.rb
Previously, we would output the full content of an agent run using
http_debug when checking serialization formats. We require checking
the stdout of the http_debug command to validate the content-type
header was set correctly.
However, outputting the raw bytes from the http requests to the logs
can be problematic because in CI we will take each test's output and
place them into xml files for Jenkins to display. These raw bytes may
contain invalid xml content that causes the post-run CI actions to fail
the build.
This sets the command which uses http_debug to "silent" so that its
content will not be sent to stdout.
=> (maint) Do not output raw serialization in acceptance

lib/puppet/functions/next.rb
Pretty self-explanatory. We don't have a good example for using this in the docs, and I want to link to it from other pages. 
(Please merge this up to main)
=> (docs) Add example for next()

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml
This commit updates rubygems to latest version to avoid the following
error: ``` Your RubyGems version (2.5.2.3)) has a bug that prevents
`required_ruby_version` from working for Bundler. Any scripts that use
`gem install bundler` will break as soon as Bundler drops support for
your Ruby version. Please upgrade RubyGems...  ```
This commit also removes an unnecessary step that installed `bundler` a
second time since the `ruby/setup-ruby@v1` action now also installs
bundler.
(cherry picked from commit 8f9992704fc353d5639108bd63761b1736d4d3d2)
=> (maint) Update rubygems and remove unnecessary step

lib/puppet/type/exec.rb
The shown `grep(1)` example is missing begin‑of‑line/end‑of‑line anchors.
=> (docs) lib/puppet/type/exec.rb `unless` `grep(1)` anchors

spec/unit/confiner_spec.rb
Previously the test failed on ruby 3.0.3 and rspec 3.10.3 due to expecting a
method to be called with keyword arguments, but getting called with a hash.
The issue is described in [1], but the problem stems from using a "double" since
rspec has no way of knowing whether the "real" object accepts keyword args or a
hash. This commit avoids the issue entirely by using a real object.
[1] https://github.com/rspec/rspec-mocks/issues/1460
=> (PUP-11456) Avoid ruby kwarg and hash confusion with doubles

spec/integration/application/resource_spec.rb
Previously the test was creating a Puppet::Type 'test', and not removing the type at the end of the spec.
That created a possibility where 
This PR cleans up the name of the type, and removes it at the end of spec.
=> (maint) Fix resource_spec.rb test

lib/puppet/http/client.rb
This is an option that must be set in the `options:` hash, not passed directly to `#get`.
=> (maint) Fix documentation for include_system_store

spec/integration/application/resource_spec.rb
A recent change broke specs for older versions of Ruby, this fixes it.
=> (maint) Fix resources_spec for Ruby versions < 2.5

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
Previously if you were running the puppet agent with strict enviroment mode
and the given enviroment was not found, puppet would then default to the production
environment.
This can produce unexpected results, so now we are going to fail early when
the environment is not found and strict environment mode is on.
=> (PUP-11440) If no env found, and strict env mode cancel puppet run

acceptance/tests/parser_functions/puppet_lookup_cmd.rb, lib/puppet/application/lookup.rb, spec/integration/application/lookup_spec.rb
Topscope variables were not being resolved on lookup when an environment was supplied. This PR fixes that.
=> (PUP-11437) Fix bug on lookup when environment is supplied

lib/puppet/util.rb, lib/puppet/util/monkey_patches.rb, spec/unit/util/windows_spec.rb
Previously, 'puppet/util/windows.rb' was loaded on Windows due to requiring
'puppet/file_system/uniquefile'[1]. The second require[2] was actually a noop,
since the file had already been required. And on non-Windows, the file was never
loaded.
Now we explicitly require 'puppet/util/windows' on all platforms. It must be
done after 'puppet/util/platform' so we can detect if we're actually on Windows.
We also remove the misleading requires that didn't do anything.
[1] https://github.com/puppetlabs/puppet/blob/6.26.0/lib/puppet/util.rb#L11
[2] https://github.com/puppetlabs/puppet/blob/6.26.0/lib/puppet/util.rb#L25
=> (PUP-11459) Always load Puppet::Util::Windows

lib/puppet.rb, lib/puppet/agent.rb, lib/puppet/application/agent.rb, lib/puppet/http/client.rb, lib/puppet/ssl/ssl_provider.rb, lib/puppet/ssl/state_machine.rb, spec/integration/application/agent_spec.rb, spec/lib/puppet_spec/puppetserver.rb, spec/unit/agent_spec.rb, spec/unit/application/agent_spec.rb, spec/unit/daemon_spec.rb, spec/unit/http/client_spec.rb, spec/unit/ssl/state_machine_spec.rb, tasks/generate_cert_fixtures.rake
* Agents never reloaded their ssl state, which prevented `crl_refresh_interval` from working as intended when `Puppet[:onetime]` was false. Now we reload ssl state prior to each run.
* Clear `default_*_ssl_context` for each run.
* Print CRL information at debug level along with CA and client certs.
* Daemonized agents never logged that they were exiting if they failed to get a cert.
* Added integration tests for bootstrapping SSL.
=> (PUP-11428) Reload ssl context for each agent run

lib/puppet/provider/package/puppetserver_gem.rb, spec/unit/provider/package/puppetserver_gem_spec.rb
Prior to this PR, the puppetserver_gem listed local packages using
the GEM command line, which resulted in innacurate results if a gem was
already loaded. This PR switches the listing of puppetserver gems to
use the shell command.
=> (PUP-11452) Shell out to list packages in puppetserver_gem

acceptance/tests/resource/user/should_allow_managed_macos_users_to_login.rb, lib/puppet/provider/user/directoryservice.rb, lib/puppet/type/user.rb
macOS 10.15+ require the salt to be 32 bytes
=> (PUP-11454) Enforce salt requirements for macOS versions 10.15+

lib/puppet/provider/package/windows.rb, lib/puppet/provider/package/windows/exe_package.rb, lib/puppet/provider/package/windows/package.rb, spec/unit/provider/package/windows/exe_package_spec.rb
Windows exe packages can now be install from a URL source.
It downloads the package locally, and runs the file with the command
options.
(cherry picked form commit 159b06614b52fd32a58f3f2a6d3eed64a9a0cd9b)
=> (PUP-11502) Windows exe packages can be sourced from URL

lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, spec/unit/pops/loaders/loaders_spec.rb
Prior to the commit the illegal error message only included the method
name and line number, but this makes finding the source file difficult.
After this commit the source file name is included in the error message.
=> (PUP-11472) Add source_ref to legacy function error

lib/puppet/http/client.rb, lib/puppet/ssl/ssl_provider.rb, spec/integration/http/client_spec.rb, spec/lib/puppet_spec/https.rb, spec/unit/ssl/ssl_provider_spec.rb
Previously, the http client could trust additional CAs or include a client cert, but not both. However, when integrating with Vault, it's common for the Vault server to require a client cert to retrieve a token and for the Vault server's cert to be issued by an external CA. To make this simple, the following is now possible:
```ruby
client = Puppet.runtime[:http]
client.get(URI("https://server.example.com:8888"), options: {include_system_store: true})
```
If the client cert exists and the server requests mutual TLS (mTLS), then the cert will be used in the call above. If the client cert doesn't exist/yet, such as `puppet apply` prior to any certs being issued, then the call above will ignore the non-existent client cert, but fail to connect if the server requests mTLS. If the client cert …
=> (PUP-11522) Support mutual TLS when using an external CA

lib/puppet/module/task.rb, spec/unit/task_spec.rb
When a module has sub-directories in its `tasks` directory, these directory names are returned as available task names when listing tasks through the corresponding API endpoint of the Puppet Server (`/puppet/v3/tasks?environment=production`).  Using the API to query the task metadata with this invalid task name leads to an exception:
```
Failed to request task metadata: 500: Internal Server Error: java.io.FileNotFoundException: /etc/puppetlabs/code/environments/production/site-modules/profile/tasks/foo (Is a directory) (RuntimeError)
```
When listing the tasks of a module, explicitly check for the type of the found files and reject directories to avoid reporting them.
=> (PUP-11539) Ignore directories when listing tasks

acceptance/tests/agent/agent_fails_with_unknown_resource.rb, acceptance/tests/modulepath.rb, acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb, acceptance/tests/resource/file/ticket_7680-follow-symlinks.rb, acceptance/tests/resource/service/windows_mixed_utf8.rb, acceptance/tests/resource/user/should_modify_when_not_managing_home.rb, acceptance/tests/utf8/utf8-in-catalog.rb, acceptance/tests/utf8/utf8-recursive-copy.rb
https://github.com/voxpupuli/beaker/pull/1744, https://github.com/voxpupuli/beaker/pull/1745 must be merged first in order to test Windows 11.
Added `pending_test` for tests that fail on Windows 11. Also dropped 2003 logic
in the symlink test since we don't support it anymore.
Filed https://tickets.puppetlabs.com/browse/PUP-11582 so that we investigate why these failure are occurring.
=> (maint) Mark some tests as pending for Windows 11

lib/puppet/info_service/task_information_service.rb, spec/unit/info_service_spec.rb
Updates the task_info_service implementation to return all task metadata
for each task when tasks_for_environment is called. This requires
reading metadata json files for each task.
Testing was done to ensure the additional file reads for metadata json
files would not impact performance of puppetserver. In tests with an
environment with > 3000 tasks, the difference in total time to process
all task data was only any increase of 0.5 - 1 second..
=> (PUP-11540) Update task_info_service to return private/description

acceptance/tests/agent/agent_fails_with_unknown_resource.rb, acceptance/tests/modulepath.rb, acceptance/tests/resource/exec/should_run_bad_command.rb, acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb, acceptance/tests/resource/file/ticket_7680-follow-symlinks.rb, acceptance/tests/resource/service/windows_mixed_utf8.rb, acceptance/tests/resource/user/should_modify_when_not_managing_home.rb, acceptance/tests/resource/user/should_modify_while_managing_home.rb, acceptance/tests/utf8/utf8-in-catalog.rb, acceptance/tests/utf8/utf8-recursive-copy.rb
Reverts two previous commits, as we don't need to skip those tests on Windows 11 anymore.
Remove the 2003 logic from the symlink test.
Update test to not rely on cygwin 2 behavior
=> (maint) Revert pending tests

acceptance/tests/resource/group/should_query_all.rb
Our new macos 12 arm64 hardware has something a bit off with the configuration
that causes this test to fail. Rather then holding up the release of the puppet
release we are going to skip the test and fix the hardware issue at a later point.
=> (maint) Skip should_query_all.rb test for macos-12-arm64

lib/puppet/util.rb, spec/unit/util_spec.rb
If `/proc/self` is not a directory, `safe_posix_fork` will raise an unhandled
`Errno::ENOTDIR`, which will cause all puppet executions to fail.
This adds `Errno::ENOTDIR` to the `rescue`, to handle this case.
=> (PUP-11594) Handle misconfigured /proc filesystems in safe_posix_fork

lib/puppet/face/help.rb, lib/puppet/generate/type.rb, lib/puppet/parser/templatewrapper.rb, lib/puppet/util.rb, lib/puppet/util/resource_template.rb, spec/unit/util/resource_template_spec.rb
On Ruby 3.1 passing the arguments as positional arguments raises warnings:
```
warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```
However, on Ruby < 2.7 passing as keyword arguments is not allowed. This is why a conditional with RUBY_VERSION is used.
I must admit I have not tested my changes yet and am relying on CI to tell me now.
=> (PUP-11552) Pass ERB arguments as keywords

ext/systemd/puppet.service
The addition of [this field](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Documentation=) allows calling [systemctl help](https://freedesktop.org/software/systemd/man/systemctl.html#help%20PATTERN%E2%80%A6%7CPID%E2%80%A6) puppet to display documentation for the service unit.
=> (PUP-11586) Add Documentation field to systemd unit

lib/puppet/util/selinux.rb, spec/unit/util/selinux_spec.rb
Since OpenZFS 0.6.3, ZFS can handle SELinux labels. We should therefore allow Puppet to set labels for files on ZFS filesystems.
Adding the test here is probably excessive, and whilst I did consider adding a check to make sure the version of ZFS in use was recent enough, I couldn't see a way to do so without linking this package to `zfs_core`. Additionally, Puppet 7 only supports back to CentOS 6, which has OpenZFS 0.8.5 builds in the official repos.
=> (PUP-110603) Mark ZFS as an SELinux-Capable Filesystem

lib/puppet/util/json.rb
This disables the conversion of floats to BigDecimal when the Oj MultiJson adapter is being used, as is done currently with JrJackson.
The original bug report is at the following URL: https://bugs.debian.org/923976
This patch has been carried for some time in the Debian Puppet package, without issue.
=> (PUP-11620) Avoid sending malformed PuppetDB reports with Oj

lib/puppet/reference/configuration.rb
In line with other values, this commit sets a default value for
`srv_domain` for consistency.
See also: 5b954fdf12ef3ae9e4276269a1eab9097ea489de
=> (maint) Update doc generation with default domain

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml
GitHub is deprecating Ubuntu 18.04 runners on April 1, 2023. This commit switches all Ubuntu 18.04 used in GitHub Actions to `ubuntu-latest` (currently Ubuntu 20.04).
=> (PUP-11626) Update Ubuntu GitHub Action runners

lib/puppet/module/task.rb, spec/unit/task_spec.rb
An empty string is valid JSON per the IETF standard, but MultiJSON raises an error when passed one. This commit updates our JSON load method to check for  empty strings and return nil, as the built-in JSON gem does.
=> (PUP-11629) Accept empty string with MultiJSON

spec/unit/http/service/compiler_spec.rb, spec/unit/network/formats_spec.rb, spec/unit/reports/store_spec.rb, spec/unit/util/storage_spec.rb, spec/unit/x509/cert_provider_spec.rb
Currently, puppet rspec tests fail when run with ruby 3.1.2 and openssl@1.1.1. These failures are primarily due to a change in behavior with the YAML.load function, Ruby 3.1 no longer accepting certain Time strings as input, and some error messages being changed.
=> (PUP-11406) Update puppet rspec tests for Ruby 3.1.

spec/unit/agent_spec.rb, spec/unit/confiner_spec.rb, spec/unit/indirector/indirection_spec.rb, spec/unit/module_tool/tar/mini_spec.rb, spec/unit/provider/ldap_spec.rb, spec/unit/provider/package/dpkg_spec.rb, spec/unit/provider/package/pkgutil_spec.rb, spec/unit/provider/parsedfile_spec.rb, spec/unit/transaction/event_manager_spec.rb, spec/unit/transaction_spec.rb, spec/unit/type/file_spec.rb, spec/unit/type/filebucket_spec.rb, spec/unit/type/tidy_spec.rb, spec/unit/util/execution_spec.rb, spec/unit/util/network_device_spec.rb
Puppet verifies partial doubles so arguments are checked against the original method and to ensure methods that don't exist can't be stubbed. RSpec 3.11.2 changes how keyword arguments are verified[1].
So previously you could write `expect(:m).with(a: true)` and it would pass if the method was called with a hash or keyword arguments. But now the expectation must expect a hash, not keyword arguments.
[1] https://github.com/rspec/rspec-mocks/commit/bc1a68725d57e167c885763e7f3edc236f92b7b5
=> (maint) Expect `with` hash arguments instead of kwargs

lib/puppet/defaults.rb, lib/puppet/indirector/facts/facter.rb, spec/integration/application/agent_spec.rb, spec/unit/indirector/facts/facter_spec.rb
Adds a puppet setting `include_legacy_facts`. If set to false, then legacy facts will not be sent to puppetserver and will not be available during `puppet apply` compilation.
This commit doesn't cause legacy facts to be blocked, so they are still available via `Facter.value(:osfamily)` for example. This is important to maintain compatibility with `defaultfor`, `confine`, etc statements used to select the most suitable provider.
=> (PUP-11662) Allow legacy facts to be excluded

lib/puppet/type.rb, lib/puppet/type/resources.rb, lib/puppet/type/user.rb, spec/unit/type/resources_spec.rb
Some types (e.g. resources, user) generate child resources from parent resources and need to copy all metaparameters, except for :alias, to the newly-generated child resource.
This commit adds a new method, copy_metaparams, that enables types to do this.
=> (PUP-11631) Adds copy_metaparams method

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml, .github/workflows/snyk_monitor.yaml
This work is for [PA-4700](https://tickets.puppetlabs.com/browse/PA-4700)
Puppet 6.x will be end of life on February 28, 2023 and Puppet 7.x will become the long term support (LTS) branch. In preparation for this, a new Puppet 7.x branch will be created and Puppet's GitHub Actions & protection rules must be updated. This PR updates Puppet's GitHub Actions to account for 7.x being the new LTS branch.
=> (maint) Update github actions to account for 7.x branch

lib/puppet/type.rb, lib/puppet/type/tidy.rb, spec/unit/type/tidy_spec.rb
This PR allows tidy to properly pass on its metaparameters to generated child file resources.
While working on this ticket, we also discovered a bug in `copy_metaparams` that has been addressed.
=> (PUP-10688) Allow tidy to pass on metaparameters

.github/workflows/rspec_tests.yaml, spec/unit/file_system_spec.rb
The setup action is failing to install 9.2.17.0, so update to the latest in the 9.2 series.
=> (maint) Bump to jruby 9.2.21.0

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml
The promotion from 7.x overwrote our changes. Revert back to main. This change will ensure the file conflicts in any future merge.
=> (maint) Update github action branches for main

.gemspec, Gemfile
fast_gettext < 2.1 calls Object#taint (removed in Ruby 3.2) which prevented puppet from loading. Bump our runtime dependency for fast_gettext. Also bump gettext-setup to 1.x, as it has a transitive dependency on fast_gettext.
=> (PUP-11634) bump fast_gettext due to removed Object#taint method

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml
The latest version of rubygems-update does not support ruby 2.5. This breaks spec testing on the 6.x so we're going to pin to the last supported version of that gem.
=> (maint) For ruby 2.5, pin to older version of rubygems-update

lib/puppet/defaults.rb, spec/unit/ssl/state_machine_spec.rb
This commit changes the crl_refresh_interval from defaulting to "never" to 1 day.
=> (PUP-11602) Defaults crl_refresh_interval to 1 day

lib/puppet/type.rb
The method has been dead for a long time, ever since the resource harness was created to call "insync?" on either `Puppet::Property::Ensure` (create) or each `Puppet::Property` (modify).
=> (maint) Remove dead Puppet::Type.insync? method

spec/integration/application/apply_spec.rb, spec/integration/http/client_spec.rb, spec/integration/network/http_pool_spec.rb
Between OpenSSL 1.1 and 3, errors about self-signed certificates changed from "self signed" (no hyphen) to "self-signed" (with a hyphen). This change caused regex for these errors in our spec tests to fail.
This commit relaxes the regex so it matches both OpenSSL 1.1 and 3 errors.
=> (maint) Updates OpenSSL errors in spec

Gemfile
Specs generated a warning due to an issue with vcr < 6.1 on Ruby 3.1+. See https://github.com/vcr/vcr/commit/98cc00b57369dfd671c227be6aa3f03d7475cb6c
```
/usr/local/bin/bundle: warning: Exception in finalizer #<Proc:0x00007f8c2990fbe8 /usr/local/lib/ruby/gems/3.2.0/gems/vcr-5.1.0/lib/vcr/library_hooks/webmock.rb:36 (lambda)>
/usr/local/lib/ruby/gems/3.2.0/gems/vcr-5.1.0/lib/vcr/library_hooks/webmock.rb:36:in `block in global_hook_disabled_requests': wrong number of arguments (given 1, expected 0) (ArgumentError)
```
=> (maint) Require vcr 6.1 - 6.x

lib/puppet/defaults.rb, spec/integration/application/agent_spec.rb, spec/integration/application/apply_spec.rb
This commit changes the default value of preprocess_deferred setting from true to false. This change will ensure deferred functions are not preprocessed by default and are instead evaluated during catalog application. Additionally, some tests were updated to accommodate this change.
This work is a follow up to [PUP-9323](https://tickets.puppetlabs.com/browse/PUP-9323).
=> (PUP-11526) Evaluate deferred functions lazily by default

.github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml, .github/workflows/snyk_monitor.yaml
This commit updates the Checkout GitHub Action from 2 to 3, as version 2 is deprecated because it uses Node.js 12. See:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> (maint) Update Checkout GitHub Action

lib/puppet/defaults.rb, spec/unit/transaction/report_spec.rb
In PUP-11654, we gave the option to exclude unchanged resources from reports.
In this commit, we make that option the default behavior.
=> (PUP-11684) Default to exclude unchanged resources

.github/workflows/rspec_tests.yaml, lib/puppet/ssl/certificate_request.rb, spec/unit/ssl/certificate_request_spec.rb, spec/unit/ssl/ssl_provider_spec.rb, spec/unit/x509/cert_provider_spec.rb
* Update tests to work with openssl 3 native library
* Update code to work with ruby-openssl 3 bindings
* Add ubuntu 22.04, ruby 3.2. 0 and openssl 3 to CI
=> (PUP-11699) Run tests against Ruby 3.2 and OpenSSL 3

.gemspec, .github/workflows/checks.yaml, .github/workflows/rspec_tests.yaml, ext/project_data.yaml, lib/puppet.rb
We still have to support JRuby 9.2, which implements the MRI 2.5.x language feature set. See 065e2ef1544c7c38095a46afb147107703a528f7 for details.
=> (PUP-11649) Drop MRI < 2.7

lib/puppet/indirector/facts/facter.rb, spec/unit/indirector/facts/facter_spec.rb
Facter.resolve v4 returns a Facter::FactCollection Hash subclass unlilke Facter v3. This causes functions like `dig` to fail, since the function only accepts a Collection type, not a Runtime type:
dig($facts, "ruby", "version")
Protect against this by calling `to_h`. If the object is a Hash, it will return `self`. If the object is derived from Hash, it will return a new Hash containing the contents of the object.
=> (PUP-11717) Protect against facter returning a Hash subclass

lib/puppet/indirector/facts/facter.rb, spec/integration/node/facts_spec.rb, spec/unit/indirector/facts/facter_spec.rb
Manually merging up due to CI issues.
The test failed in main, because we changed the default for `ignore_legacy_facts` (so `Facter.resolve` is called, not `Facter.to_hash`)
=> (maint) Merge 7.x to main

acceptance/tests/agent/agent_fails_with_unknown_resource.rb
The test sets the vendormoduledir so that compilation succeeds and expects the agent to fail, since the customtype was never pluginsynced. Override vendormoduledir on the agent so the test works in either case.
Verified this passes using single and multi host configs:
```
bx rake ci:test:setup SHA=fa212183fac8cfb125d5bf4bdf89d23e0793b161 HOSTS=redhat7-64a-redhat7-64m
bx rake ci:test:setup SHA=fa212183fac8cfb125d5bf4bdf89d23e0793b161 HOSTS=redhat7-64ma           
```
=> (maint) Handle case where agent and server are on the same host

acceptance/tests/catalog_with_binary_data.rb, acceptance/tests/direct_puppet/supports_utf8.rb, acceptance/tests/parser_functions/hiera_in_templates.rb, acceptance/tests/reports/corrective_change_new_resource.rb, acceptance/tests/reports/corrective_change_outside_puppet.rb, acceptance/tests/reports/corrective_change_via_puppet.rb, acceptance/tests/resource/file/ticket_6448_file_with_utf8_source.rb
Update manifests and hiera config to use structure facts.
Passed on base linux: https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_pr/2405/
=> (PUP-11713) Update beaker tests to use structured facts

.gemspec, ext/project_data.yaml
concurrent 1.2 deleted Concurrent::RubyThreadLocalVar, so pin for now.
We have to update two places, because .gemspec is used when running puppet from source using bundler and ext/project_data.yaml is used when building the puppet gem.
=> (PUP-11722) Pin ruby concurrent to 1.1.x

lib/puppet/defaults.rb, spec/integration/application/agent_spec.rb, spec/integration/parser/compiler_spec.rb, spec/integration/parser/conditionals_spec.rb, spec/integration/parser/scope_spec.rb, spec/unit/application/lookup_spec.rb, spec/unit/functions/epp_spec.rb, spec/unit/functions/inline_epp_spec.rb, spec/unit/functions/return_spec.rb, spec/unit/indirector/catalog/compiler_spec.rb
This commit sets `strict_variables` to `true` and modifies any tests that fail due to this change. To completely enable strict mode by default, [strict](url) will also  need to be set to `error` instead of `warning`. This work will be done in [PUP-11725](https://tickets.puppetlabs.com/browse/PUP-11725).
=> (PUP-11689) Set strict_variables to true to enable strict mode by default

lib/puppet/parser/functions/fqdn_rand.rb, spec/unit/parser/functions/fqdn_rand_spec.rb
The `fqdn_rand` function rely on the `fqdn` legacy fact to operate. When running Puppet with `--no-include_legacy_facts`, the behavior is changed:
```sh-session
romain@zappy ~/Projects/puppetlabs/puppet % bundle exec puppet apply -e 'warning(fqdn_rand(100))' --include_legacy_facts
Warning: Scope(Class[main]): 4
Notice: Compiled catalog for zappy.blogreen.org in environment
production in 0.01 seconds
Notice: Applied catalog in 0.01 seconds
romain@zappy ~/Projects/puppetlabs/puppet % bundle exec puppet apply -e 'warning(fqdn_rand(100))' --no-include_legacy_facts
Warning: Undefined variable '::fqdn';
(file & line not available)
Warning: Scope(Class[main]): 79
Notice: Compiled catalog for zappy.blogreen.org in environment
production in 0.01 seconds
Notice: Applied catalog in 0.01 seconds
``` …
=> (PUP-11752) Fix usage of legacy fact in fqdn_rand

acceptance/tests/lookup/hiera3_custom_backend.rb
The hiera gem is no longer bundled in puppet-agent, so install it during the hiera3_custom_backend test.
This is a follow up to the change in PA-4646
I manually verified this passes the following tests:
```
$ bundle exec rake ci:test:setup SHA=ed3ec05c794d111add2126cc4d3008b0adf64ab3 HOSTS=redhat7-64ma SERVER_VERSION=7.9.5.SNAPSHOT.2023.01.31T1920
...
$ bundle exec beaker exec tests/parser_functions/,tests/lookup,tests/utf8/utf8-in-function-args.rb,tests/ticket_5592_hiera_lookup_when_param_undef.rb
```
where the list of tests came from:
```
$ git grep -l hiera tests/
tests/lookup/config3_interpolation.rb
tests/lookup/config5_interpolation.rb
tests/lookup/hiera3_custom_backend.rb
tests/lookup/lookup.rb
tests/lookup/lookup_rich_values.rb
tests/lookup/merge_strategies.rb …
```
=> (maint) Install hiera v3 gem during beaker test

lib/puppet/defaults.rb, spec/integration/application/apply_spec.rb, spec/integration/parser/compiler_spec.rb, spec/integration/parser/conditionals_spec.rb, spec/integration/parser/scope_spec.rb, spec/unit/application/lookup_spec.rb, spec/unit/application/resource_spec.rb, spec/unit/data_providers/hiera_data_provider_spec.rb, spec/unit/functions/epp_spec.rb, spec/unit/functions/inline_epp_spec.rb, spec/unit/functions/lookup_spec.rb, spec/unit/functions/return_spec.rb, spec/unit/hiera/scope_spec.rb, spec/unit/module_spec.rb, spec/unit/parser/scope_spec.rb, spec/unit/pops/evaluator/arithmetic_ops_spec.rb, spec/unit/pops/evaluator/evaluating_parser_spec.rb, spec/unit/pops/loaders/loaders_spec.rb, spec/unit/pops/serialization/to_from_hr_spec.rb, spec/unit/pops/validator/validator_spec.rb, spec/unit/resource/catalog_spec.rb
To start moving towards enabling strict mode by default, in [PUP-11689](https://tickets.puppetlabs.com/browse/PUP-11689) strict_variables was turned on. This commit continues that by setting strict to default to error instead of warning. 
Additionally, rspec tests that failed after the change were updated. I came across some unexpected behavior after setting strict to error so I set those tests to pending and created a ticket, [PUP-11751](https://tickets.puppetlabs.com/browse/PUP-11751), so those could be looked into later.
=> (PUP-11725) Turn on strict mode by default

.rubocop.yml, lib/puppet/pops/evaluator/relationship_operator.rb
JRuby 9.4 will warn that this will be interpreted as a method's argument list not a destructuring. That is the desired behavior but we do not want the warning.
=> (maint) Remove spurious space between method name & args

.gemspec, Gemfile, ext/project_data.yaml
With the release of facter 4.3.0 we no longer need to point to facter's github repo.
=> (PUP-11756) Update facter dependency

lib/puppet/defaults.rb, man/man5/puppet.conf.5, spec/integration/application/agent_spec.rb, spec/integration/application/apply_spec.rb
This fixes several misspellings of the word "satisfied", which is written "satified", where an `s` is missing.
This misspelling was flagged by the Debian [Lintian tool](https://wiki.debian.org/Lintian).
=> (maint) fix multiple misspellings of "satisfied"

lib/puppet/functions/each.rb, lib/puppet/functions/filter.rb, lib/puppet/functions/map.rb, lib/puppet/pops/lookup/context.rb
The each/filter/map functions, for some dispatches, use patterns that
are slow and/or buggy when run on jruby.
The correct pattern for enumeration is
```
object.each do |value|
yield(value)
end
```
Two alternatives in use are
```
enum = object.each
object.size.times do
yield(enum.next)
end
enum = object.each
begin
loop do
yield(enum.next)
end
rescue StopIteration
end
```
The first pattern is incorrect because it never triggers StopIteration
on the enumerator (by attempting to call `next` one last time). On MRI
this is apparently harmless, but on JRuby it leaves the Fiber associated with the
Enumerator around. Since Fibers are implemented via native threads on
JRuby, that leaves around a native thread. That can deplete the
available threads and interferes with garbage collection, as every …
=> (PUP-11755) Avoid slow, buggy pattern for enum functions

lib/puppet/type/file/ctime.rb, lib/puppet/type/file/mtime.rb, spec/unit/type/file/ctime_spec.rb, spec/unit/type/file/mtime_spec.rb
Prior to this commit, Puppet's file type returned a file's ctime and mtime (created and modified times) as Time objects. This commit converts those to Strings instead to alleviate issues when those values needed to be used in formats that don't understand Time objects (e.g. YAML).
=> (PUP-11763) Converts ctime/mtime to string

acceptance/tests/modules/changes/module_with_modified_file.rb, acceptance/tests/modules/changes/module_with_removed_file.rb, acceptance/tests/modules/changes/unmodified_module.rb, acceptance/tests/modules/list/with_environment.rb
Currently, the test forge instance's SSL cert is expired. Due to this Puppet CI is blocked. This commit skips all tests that use a test forge instance.
=> (maint) Skip tests that use test forge instance

lib/puppet/provider/package/pacman.rb
Add Artix to the list of Arch-based distros. This will greatly simplify the process of packaging Puppet for Artix.
=> (packaging) Add Artix to pacman.rb

lib/puppet/module.rb, lib/puppet/module/task.rb, spec/unit/pops/loaders/loaders_spec.rb
This commit has Puppet::Util::Json.load check if an empty string is passed in and returns nil if an empty string is passed in. More work may be necessary to ensure Puppet::Util::Json.load behaves as expected.
=> (PUP-11754) Empty metadata files should be treated as though they don't exist

ext/project_data.yaml
Prior to this commit, Puppet's runtime dependency on Facter was '> 4.3.0', '< 5'. The most recent release of Facter is 4.3.0, so nightly gems of Puppet 8 could not satisfy their runtime dependencies.
This commit updates the lower bound of Puppet's Facter runtime dependency to '>= 4.3.0'.
=> (maint) Update Facter dependency

.gemspec, Gemfile, ext/project_data.yaml
Puppet's gemspec and the project_data.yaml file used by our packaging utility had gotten out of sync in terms of Puppet's gem dependencies.
This commit syncs up the dependencies in both the gemspec and project_data.yaml, which includes changing our dependency on fast_gettext to >= 2.1 < 3, which allows us to use fast_gettext that's compatible with Ruby > 3.2 (i.e., does not include removed Object#taint methods).
=> (maint) Sync gemspec and packaging file

acceptance/tests/lookup/config5_interpolation.rb, lib/puppet/parser/scope.rb, lib/puppet/pops/lookup/hiera_config.rb, spec/unit/functions/lookup_spec.rb
With Puppet[:strict], hiera interpolation errors prevented compilations because variables were not yet initialized. With this change, the hiera_config class adds a context for the Puppet::Parser::Scope to consider when raising errors.
=> (PUP-11751) Handle interpolation errors from hiera_config

lib/puppet/face/help/action.erb, lib/puppet/face/help/face.erb, lib/puppet/indirector/face.rb, lib/puppet/interface/documentation.rb, spec/unit/indirector/face_spec.rb
The "extra" CLI option has been a part of Puppet since 2011, but has never worked properly and was hidden in 2021.
This commit entirely removes the "extra" CLI option.
=> (PUP-11119) Removes "extra" CLI option

.gemspec, lib/puppet.rb
This reverts commit a4d7b3ff3ab6f0e2e5d7eaae1b3607bd6651dcc5.
=> (PUP-11716) Revert ruby version changes to .gemspec and lib/puppet.rb

acceptance/tests/catalog_with_binary_data.rb
The `file` function returns a `String`, not `Binary`, so if the string contains data that is not valid UTF-8, then puppetserver will fail to serialize the catalog as `rich_data_json`. However as described in PUP-10928, puppet will fallback to either `rich_data_msgpack` (if msgpack is installed as a puppetserver gem) or fallback to `pson`.
Rich data support was added to agents in Puppet 6, so just use the `binary_file` function instead of relying on the fallback behavior.
I tested this using:
```
bundle exec rake ci:test:setup SHA=7eac0d839a56c765074bfc14df65768f3f00ecdf HOSTS=redhat7-64m-redhat7-64a
bundle exec beaker exec tests/catalog_with_binary_data.rb
```
=> (PUP-9648) Use binary_file instead of file

lib/puppet/functions/max.rb, lib/puppet/functions/min.rb, spec/unit/functions/max_spec.rb, spec/unit/functions/min_spec.rb
Prior to this commit, the max and min core functions would compare SemVer, Timespan, and Timestamp types as Strings, which would lead to often incorrect results (e.g. max would state that a SemVer of 2.0.0 was greater than 10.0.0).
This commit updates max and min to recognize SemVer, Timespan, and Timestamp types properly.
=> (PUP-11663) Enable more types in max/min functions

lib/puppet/pops/lookup/interpolation.rb, spec/unit/pops/lookup/interpolation_spec.rb
The previous logic did not handle values set to nil; this brings back the `nil_in_scope?` method to preserve the previous logic.
=> (PUP-11751) Handle possible nil values in interpolation

lib/puppet/network/http/api/indirected_routes.rb, spec/unit/network/http/api/indirected_routes_spec.rb
If puppetserver falls back to PSON when serializing a catalog, then conversion of rich data will be lossy, but the problem won't be noticed until the catalog is applied on the agent.
This converts the debug message to a warning to assist troubleshooting. This affects both `find` and `search` operations for all indirected types.
=> (PUP-11787) Warn if we fail to serialize and fallback

acceptance/tests/environment/enc_nonexistent_directory_environment.rb, acceptance/tests/resource/package/yum.rb
In Beaker, the assert_not_match method was removed in commit voxpupuli/beaker@6282311 in favor of MiniTest::Assertions#refute_match. This change was released in Beaker 5.0.0.
This commit updates all instances of the assert_not_match with refute_match in preparation for a future switch to Beaker 5.
=> (maint) Update assert_not_match to refute_match

lib/puppet/defaults.rb, lib/puppet/indirector/catalog/json.rb, lib/puppet/network/http/api/indirected_routes.rb, spec/unit/network/http/api/indirected_routes_spec.rb
Currently, Puppet will fall back to PSON when unable to serialize to JSON. This
can cause issues since rich data types cannot be serialized via PSON. Due to
this, PSON will eventually be depreceated and removed in future releases. This
commit adds a setting, :allow_pson_serialization, which defaults to false in
Puppet 7 and will default to true in Puppet 8. When set to false, a warning
will be raised when falling back to PSON and when set to true, an error will be
raised instead. This option affects both puppetserver's configuration management
service responses and when the agent saves its cached catalog.
=> (PUP-10928) Add allow_pson_serialization setting

spec/unit/network/http/api/indirected_routes_spec.rb
Unlike puppet#7.x (where the `:allow_pson_serialization` setting was first
added), by default in puppet#main, pson is not a supported format so the rspec
tests for `:allow_pson_serialization` were not able to test the desired behavior.
This commit stubs out `Puppet.features.pson?` in those tests to stimulate that 
the `puppet-pson` library is present so pson is a supported format returned by
`accepted_response_formatters`.
=> (PUP-10928) Fix indirected_routes_spec.rb

lib/puppet/defaults.rb, spec/unit/network/http/api/indirected_routes_spec.rb
Rich data is enabled by default and when attempting to serialize rich data to PSON, there will be data loss since rich data cannot be serialized via PSON. Due to this, this commit sets the default value for :allow_pson_serialization to false for Puppet 8. This means an error will be raised when falling back to PSON.
=> (PUP-11785) Don't fallback to PSON if catalog rendering fails

lib/puppet/defaults.rb, lib/puppet/file_system/uniquefile.rb, lib/puppet/node/environment.rb, lib/puppet/provider/exec/windows.rb, lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/puppet_gem.rb, lib/puppet/test/test_helper.rb, lib/puppet/util.rb, lib/puppet/util/execution.rb, spec/integration/defaults_spec.rb, spec/integration/util_spec.rb, spec/unit/provider/package/gem_spec.rb, spec/unit/provider/package/puppet_gem_spec.rb, spec/unit/test/test_helper_spec.rb, spec/unit/util/run_mode_spec.rb, spec/unit/util_spec.rb
Ruby 3 no longer uses the current code page when getting and setting environment variables. Instead it always calls wide functions like [`GetEnvironmentVariableW`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getenvironmentvariablew) and transcodes the value from `UTF-16LE` to `UTF-8`. And it does the reverse when setting environment variables. As a result, we don't need our Windows specific code for accessing environment variables.
* Deprecates `Puppet::Util.{get_env,get_environment,clear_environment,set_env,merge_environment}`
* Call `ENV` related methods directly
* Add more boundary cases for valid env keys and values
Tested Windows (x86, x64 and Japanese) in https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppe …
=> (PUP-11348) Use ENV directly on Windows

CODEOWNERS
This commit transfers ownership of certain parts of the codebase from the PDK GitHub team to the larger, more current Modules GitHub team.
=> (maint) Update CODEOWNERS with modules team

.gemspec, ext/project_data.yaml, lib/puppet/thread_local.rb
Prior to this commit, Puppet relied on the
Concurrent::RubyThreadLocalVar private class in concurrent-ruby.
This private class was removed in concurrent-ruby v1.2.0: https://github.com/ruby-concurrency/concurrent-ruby/commit/30465396
This commit updates Puppet::ThreadLocal to use
Concurrent::ThreadLocalVar instead of Concurrent::RubyThreadLocalVar and updates Puppet's dependency on concurrent-ruby to remove the pin to < v1.2.0.
=> (PUP-11723) Remove concurrent-ruby private class

lib/puppet/defaults.rb, lib/puppet/http/service/ca.rb, lib/puppet/ssl/state_machine.rb, lib/puppet/x509/cert_provider.rb, spec/integration/application/agent_spec.rb, spec/unit/application/lookup_spec.rb, spec/unit/http/service/ca_spec.rb, spec/unit/ssl/state_machine_spec.rb, spec/unit/x509/cert_provider_spec.rb
By default, puppet agents will now attempt to **refresh** their CA bundle once per day. If new certs are successfully downloaded, then those will be used for subsequent TLS connections. The agent will also automatically attempt to refresh its CRL bundle, since if a new CA was retrieved, then we will need its corresponding CRL to verify the full cert chain.
If there are no changes to the CA bundle or if the agent is unable to retrieve them, then it will continue using its existing CA certs and try again later (after another day).
```
$ bundle exec puppet agent -t --ca_refresh_interval=1s --crl_refresh_interval=1s
Info: Refreshing CA certificate
Info: Refreshed CA certificate: 44:B4:4F:8B:B4:D4:C5:9F:66:7F:46:BB:CF:CF:1C:EB:F6:C5:81:15:7B:E6:74:0F:04:31:FA:EC:F4:F4:E5:1A
Info: Refreshing …
```
=> (PUP-10639) Periodically refresh our CA bundle

lib/puppet/node/environment.rb, spec/unit/file_system/path_pattern_spec.rb
JRuby does not properly match both directory and file wildcards when using Dir.glob (e.g. Dir.glob('**/*.pp'), which can lead to incorrect matches. Because of this, if a manifest name contains ".pp" in its filename (e.g. foo.pp.pp), Puppet does not recognize it as a manifest file when importing and parsing manifests.
This commit updates the perform_initial_import method to no longer rely on that wildcard Dir.glob behavior to recursively traverse a directory and instead uses only the directory wildcard and uses Array.select to identify files ending in ".pp" from there.
=> (PUP-11788) Account for JRuby behavior in Dir.glob

lib/puppet/defaults.rb, spec/unit/defaults_spec.rb
bb86ff6 added a conditional to Puppet's default settings to account for unique behavior for diff on AIX 5.3, which has long been end-of-life and is no longer supported by Puppet or Puppet Enterprise.
This commit updates Puppet's default settings for diff and associated spec tests to remove that AIX 5.3-specific conditional.
=> (maint) Removes AIX 5.3-specific setting

lib/puppet/defaults.rb
This commit adds a setting to Puppet to set an interval at which to automatically renew a node's host/client certificate. This setting is set to a default of 30 days initially.
=> (PUP-11855) Add hostcert renewal setting

lib/puppet/http/service/ca.rb, spec/unit/http/service/ca_spec.rb
This commit adds a method,
Puppet::HTTP::Services::CA.post_certificate_renewal, to allow a node to send a POST request to renew its certificate.
=> (PUP-11854) Add method to renew certificate

lib/puppet/ssl/ssl_provider.rb, spec/unit/ssl/ssl_provider_spec.rb
String#chomp! returns nil if the string is not modified, but String#chomp doesn't. So just use that.
=> (PUP-11849) Always print the CRL authorityKeyIdentifier

lib/puppet/ssl/oids.rb
This commit adds the pp_cli_auth OID, which is a certificate extension that allows the puppetserver CA CLI tool to submit requests to the puppet-CA API that change the status of certificates. The OID was created in SERVER-2287 but was never added to Puppet.
=> (PUP-9964) Add Puppetserver CA CLI Authoriziation OID to Puppet

lib/puppet/ssl/oids.rb, lib/puppet/x509/cert_provider.rb, spec/unit/ssl/state_machine_spec.rb, spec/unit/x509/cert_provider_spec.rb
This commit adds an auto-renew attribute to the CSR when it is generated if the agent supports auto-renewal of certificates. Agents that either do not have the hostcert_renewal_interval setting or have it set to 0 do not support auto-renewal.
Originally, this was added as an auto-renew extension to the CSR (see #9076). However, in its default (FOSS) configuration,  puppetserver rejects extensions so the auto-renew will be implemented as an attribute instead.
=> (PUP-11896) Send auto-renew attribute in CSR

lib/puppet/ssl/oids.rb
This commit adds the pp_cli_auth OID, which is a certificate extension that allows the puppetserver CA CLI tool to submit requests to the puppet-CA API that change the status of certificates. The OID was created in SERVER-2287 but was never added to Puppet.
Originally this was added to Puppet 8.x in #9077 but I forgot to also add it to 7.x
=> (PUP-9964) Add Puppetserver CA CLI Authoriziation OID to Puppet 7.x

lib/puppet/pops/evaluator/deferred_resolver.rb, spec/integration/application/apply_spec.rb
Prior to this commit, evaluating a deferred resource that includes a Sensitive value would fail during munging.  This commit marks these resources as sensitive and unwraps them during catalog application.
=> (PUP-11846) Handle unprocessed, deferred sensitive

lib/puppet/ssl/state_machine.rb
Use "renew" to describe client cert updates to avoid confusion with CA/CRL "refresh".
=> (maint) Print that client cert was renewed

lib/puppet/http/client.rb, spec/integration/http/client_spec.rb
Before this commit, puppet would attempt to `finish` a connection in the block passed to an `http.request` function. This will not work because `finish` sets the `@socket` to nil, and the net/http request assumes that the `@socket` is set for the duration of that function. With this change, we mark some state during the request function that indicates the connection should be closed after the completion of the `http.request`.
=> (PUP-11853) Wait for request completion before closing

acceptance/tests/resource/group/should_query_all.rb
In CI, automatic mergeup from 7.x to main failed with this:
```
14:24:26 fatal: Exiting because of an unresolved conflict.
14:24:26 U	acceptance/tests/resource/group/should_query_all.rb
14:24:27 + echo 'Couldn'\''t automatically resolve conflicts while merging 5baa68a4c22c0fa16d98696072cca38690611033 into main; Merge-up must be done manually.'
```
This was due to a newline existing in `should_query_all.rb` in 7.x, but not main.
=> (maint) Manual mergeup July 31 2023

acceptance/Gemfile
This commit updates beaker-hostgenerator to ~> 2 to enable compatibility with newer platforms, such as macOS 13.
=> (maint) Update beaker-hostgenerator

lib/puppet/info_service/task_information_service.rb, spec/unit/info_service_spec.rb
Currently, when a task is omitted due to a failure, Puppet Server logs an exception with a generic error message and provides no details on how to resolve the error: `ERROR [qtp1527520408-905] [puppetserver] Puppet Failed to validate task`
This commit removes the generic message that overrides the original error message in the rescued error. Instead, the rescued error message is logged.
=> (PUP-11928) Give more specific error messages for /puppet/v3/tasks API

lib/puppet/application/ssl.rb, lib/puppet/x509/cert_provider.rb, spec/unit/application/ssl_spec.rb
Adds a command `puppet ssl generate_request` to generate a CSR but not submit it. This is useful when boostrapping an offline agent.
=> (PUP-10589) Add a generate_request option to puppet ssl

.github/workflows/rspec_tests.yaml, spec/unit/ssl/certificate_signer_spec.rb, spec/unit/ssl/ssl_provider_spec.rb
Puppetserver upgraded from the JRuby 9.2.y.z series to JRuby 9.3.y.z as part of SERVER-3133. This commit updates the JRuby version used in Rspec tests to match the most recent JRuby version used in the Puppetserver 7.x series.
=> (PUP-11935) Update JRuby in tests to 9.3.y.z

lib/puppet/parser/files.rb
Testing confirms that the `find_file()` function may indeed be used to verify the existence of a file specified by absolute path, with the caveat that this check appears to be performed prior to any resource changes made by the same code.
The following code-snippet accurately reports the existence or non-existence of a test file *before* deleting that file.
```
$testpath = '/tmp/testfile'
file { $testpath: ensure => absent }
if find_file($testpath) {
notify { "$testpath exists.": }
} else {
notify { "$testpath does not exist.": }
}
```
=> Correct inaccurate comment in find_file() function.

lib/puppet/application/ssl.rb, spec/unit/application/ssl_spec.rb
If a user attempts to get rid of some certs and confuses `puppetserver ca clean` with `puppet ssl clean`, there is a chance it will wipe out keys/certs that were not intended. This commit adds some safeguards to the ssl clean subcommand to try to avoid that scenario.
=> (PUP-11895) ssl application's clean shouldn't allow extra args

Gemfile, ext/project_data.yaml
FFI >= 1.16.0 breaks FFI modules in Facter, which is a dependency of Puppet. While the latest release of Facter (4.5.0) pins FFI to 1.15.5, Puppet's gemspec adds a Windows-specific runtime dependency on FFI set to > 1.9.24 < 2, which currently resolves to the latest version of FFI (1.16.2).
This commit pins FFI to 1.15.5 to address the incompatibility between Facter and FFI >=1.16.0.
=> (PUP-11947) Pin FFI to 1.15.5

lib/puppet/application.rb
Log the openssl version and whether FIPS is enabled. The version contains spaces, so quote it. This is omitted on JRuby, because we don't require openssl, see puppet/ssl/openssl_loader.rb for details.
Debug: Runtime environment: puppet_version=8.1.0 ... \
openssl_version='OpenSSL 1.1.1f  31 Mar 2020', openssl_fips=false
=> (PUP-11930) log openssl version

lib/puppet/util/monkey_patches.rb, spec/unit/util/monkey_patches_spec.rb
We should handle cases where the deprecated exists? methods are called for File or Dir, and give a warning but still allow things to proceed.
=> (PUP-11945) Add patches for File and Dir exists? methods

lib/puppet/defaults.rb
Currently, the documentation of the setting implies that the certificate will be refreshed every N days (N = specified duration). However, it actually only renews the client cert if the cert expires within N days from now.
This commit updates the documentation for hostcert_renewal_interval in defaults.rb to more closely reflect how the setting behaves.
=> (PUP-11944) Update `hostcert_renewal_interval` puppet setting docs

lib/puppet/type/filebucket.rb
Default digest_algorithm changed in Puppet 7.0.0; update filebucket documentation to reflect no longer md5 by default.
The algorithm used is specified by the digest_algorithm setting; md5 was the default for Puppet6 and earlier; from Puppet 7.0.0 onwards the default was changed to sha256 - ref: https://www.puppet.com/docs/puppet/7/release_notes_puppet.html#enhancements_puppet_7-0-0-pup-10583
=> (docs) update filebucket doc to reflect cryptographic checksum instead of md5

docs/http.md
The evolution of that part of the code has seen multiple iterations, and
the doc does not reflect the current usage so fix it.
While here, also fix the wrong variable name typo.
=> Fix `Puppet::HTTP::Client` example with system store

lib/puppet/functions/split.rb, spec/unit/functions/split_spec.rb
[PUP-11429](https://tickets.puppetlabs.com/browse/PUP-11429)
=> (PUP-11429) Make split() sensitive-aware

lib/puppet/util/windows/adsi.rb, lib/puppet/util/windows/sid.rb, spec/unit/util/windows/adsi_spec.rb
This commit introduces two new errors, ERROR_TRUSTED_DOMAIN_FAILURE and ERROR_TRUSTED_RELATIONSHIP_FAILURE. Those two errors can occur when looking up a SID and the a host fails a trust call with the AD. We can still recover and should attept to.
=> (PUP-11938) Handle more errors around Windows SID and ASID

lib/puppet/util/monkey_patches.rb, spec/unit/util/monkey_patches_spec.rb
1341b92 added monkey patches for File.exists? and Dir.exists? and used Puppet's warning method to indicated that the methods are deprecated.
This commit updates those monkey patches to instead use the less verbose Kernel#warn.
=> (PUP-11974) Use Ruby warn for deprecation

lib/puppet/util/monkey_patches.rb, spec/lib/puppet_spec/verbose.rb, spec/unit/agent_spec.rb, spec/unit/daemon_spec.rb, spec/unit/type/exec_spec.rb, spec/unit/util/monkey_patches_spec.rb
In ruby 2.7.x, the rb_file_exists_p and rb_dir_exists_p methods call rb_warning to log that the methods are deprecated[1][2] However, the rb_warning method is a noop if $VERBOSE is nil or false[3] To preserve the same behavior, only warn when $VERBOSE is truthy. Also include the class name and path in the warning so we can identify and fix the issue.
[1] https://github.com/ruby/ruby/blob/1f4d4558484b370999954f3ede7e3aa3a3a01ef3/file.c#L1819
[2] https://github.com/ruby/ruby/blob/1f4d4558484b370999954f3ede7e3aa3a3a01ef3/dir.c#L3301
[3] https://github.com/ruby/ruby/blob/1f4d4558484b370999954f3ede7e3aa3a3a01ef3/error.c#L336-L338
=> (PUP-11974) Only warn when Ruby's verbose is enabled

.github/workflows/rspec_tests.yaml
For PE-36375 puppetserver 8 bumped its JRuby version from 9.4.2.0 to 9.4.3.0.
This commit mirrors that change in the rspec test matrix.
=> (maint) Bump JRuby in tests

lib/puppet/indirector/catalog/rest.rb, spec/unit/indirector/catalog/rest_spec.rb
When a catalog is requested, log which server is attempted to be used and if an IP address is resolvable display that.
=> (PUP-11899) Log which server we request a catalog from

lib/puppet/type/resources.rb
The resources type is useful on both hosts and devices and is compatible as is in both modes.
=> (PUP-11666) Mark resources type as valid for hosts and devices

.github/workflows/checks.yaml, .github/workflows/jira.yml, .github/workflows/rspec_tests.yaml
This PR:
- Adds a friendly name to the GitHub Actions workflow that exports GitHub Issues to Jira.
- Removes a pin to a Ruby-2.5-compatible version of Rubygems in our GitHub Actions workflows that is no longer needed.
=> (PA-5932) Add name to Jira workflow

.github/workflows/checks.yaml, Rakefile
Now that GH issues are the source of truth, we can drop the commits check.
=> Drop commits check

lib/puppet/http/service/compiler.rb, spec/integration/application/agent_spec.rb, spec/lib/puppet_spec/puppetserver.rb
This change will emit a notice when http traffic from a puppetserver sends the `X-Puppet-Compiler-Name` header; this should help for debugging purposes when troubleshooting compilation issues and several compilers are behind a load balancer.
=> (PUP-11900) Notify when `X-Puppet-Compiler-Name` header found

lib/puppet/provider/service/init.rb
This is the same PR as https://github.com/puppetlabs/puppet/pull/9082 but applied to the 7.x branch. In 7.x the code uses legacy facts, while main uses modern facts (`osfamily` vs `os.family`).
=> [7.x] Avoid downcasing facts in service provider

lib/puppet/provider/service/init.rb
If the os.name or os.family fact is missing this will result in nil.downcase. In practice that's unlikely, but in some test scenarios it can happen. By using the properly cased values it removes the need to downcase, which is also slightly faster.
=> Avoid downcasing facts in service provider

lib/puppet/indirector/catalog/compiler.rb, spec/unit/indirector/catalog/compiler_spec.rb
During catalog compilation, after loading the requested environment we load the node and server specified environment. Previously, We would then compare the Environment objects to determine if the requested environment matched the server specified environment. However, if the environment cache is flushed between those two environments being loaded they could be different object instances representing the same desired environment.
To resolve this race condition we now check the environment names (Environment#name canoncalizes to symbols to avoid symbol/string mismatch).
=> (maint) Compare Environment#name in compiler

lib/puppet/provider/package/dnfmodule.rb, spec/unit/provider/package/dnfmodule_spec.rb
the old code would work correctly for ensure => present, but not for ensure => 'some_stream', as dnf does include the whole module spec in the error message and the old regex didn't match anymore.
```
Error: Problems in request:
broken groups or modules: 389-ds
Error: Problems in request:
broken groups or modules: 389-ds:1.4
```
=> (PUP-11985) correctly enable module:stream without default profile with dnfmodule

lib/puppet/ssl/ssl_context.rb
Ruby 2.5 added the `keyword_init: true` option to Struct.new to enable keyword arguments.
This commit updates the Puppet::SSL::SSLContext to take advantage of this language feature and removes a workaround needed for older versions of Ruby.
Additionally, Ruby 3.2 addeed the ability to initialize a Struct with keyword arguments without the `keyword_init: true` option. This commit adds a comment noting that, so it can be removed in the future when Puppet drops support for Ruby < 3.2.
=> (maint) Simplifies SSLContext intialization

lib/puppet/type/exec.rb, spec/unit/type/exec_spec.rb
If an exec's 'command' parameter is deferred and lazily evaluated, then we can't autorequire the file that the command will execute. This is because we won't know what the command is until the exec is evaluated. But that means it's already too late to add a relationship from the file resource to the exec resource. In this situation and explicit relationship is required to ensure the file resource is evaluated before the exec. The same is true for the 'onlyif' and 'unless' exec parameters.
=> (PUP-11937) Skip autorequire if exec's param is deferred and lazily evaluated

lib/puppet/http/service/compiler.rb, spec/integration/application/agent_spec.rb, spec/lib/puppet_spec/puppetserver.rb
This change will emit a notice when http traffic from a puppetserver sends the X-Puppet-Compiler-Name header; this should help for debugging purposes when troubleshooting compilation issues and several compilers
are behind a load balancer.
=> (PUP-11900) Notify when X-Puppet-Compiler-Name header found

lib/puppet/configurer.rb
Puppet calculates the total number of facts on an agent node to warn the user if it will cause performance issues with PuppetDB. PuppetDB performance can be impacted when the leaf count of a factset is too high.
Prior to this commit, Puppet inconsistently calculated facts when generating a warning. This did not count individual array elements; for example, the processor.models fact with a fact per processor core would only be counted once. Additionally, hash keys were incorrectly each counted as individual facts when they would not represent separate leaf counts in PuppetDB.
These behaviors lead to a slight discrepancy between what Puppet would report to the user and what the total fact count ended up being in PuppetDB.
This commit updates Puppet to more accurately count facts to reflect …
=> (PUP-11685) Update total fact count

acceptance/tests/resource/group/should_query_all.rb
In 8e9f9cb, we disabled macOS 12 and 13 ARM from running the test to query all groups due to an issue with those images in Puppet's CI system.
This issue was resolved in ITHELP-70197 and the test can be re-enabled for these platforms.
=> (maint) Restore macOS group test

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
Systemd is available on Gentoo since a long time (although Gentoo supports multiple init systems). This change marks the provider as default for Gentoo.
=> (PUP-11593) Gentoo: Fix systemd service provider

.github/workflows/jira.yml
Confusingly, the permission 'pull-requests' is plural and has dashes.
=> Use singular pull_request event type

acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb
This commit adds a mapping for a package for Amazon Linux to use for the systemd masked services test.
=> (PUP-11986) Add Amazon Linux package mapping

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
Systemd is available on Gentoo since a long time (although Gentoo supports multiple init systems). This change marks the provider as default for Gentoo.
Cherrypicked from main. Original PR: https://github.com/puppetlabs/puppet/pull/8919
=> (PUP-11593) Gentoo: Set systemd as default provider

lib/puppet/settings.rb
Not locking the default initialization can lead to race-conditions.
I don't think we can switch to Concurrent::Map, and it's compute_if_absent
method, because insertion order won't be maintained. So synchronize the long
way.
ref: ruby-concurrency/concurrent-ruby#970
Co-authored-by: Maciej Mensfeld <maciej@mensfeld.pl>
resolves #8951
=> Make cache and values fully thread-safe

.github/workflows/jira.yml
From github, secrets and variables for actions "are not passed to workflows that are triggered by a pull request from a fork". As a result, we cannot trigger the jira workflow in the same way as GH issues, so revert those changes.
=> Revert labeling pull requests

.rubocop_todo.yml, examples/enc/regexp_nodes/regexp_nodes.rb, lib/puppet/file_system/file_impl.rb, lib/puppet/file_system/posix.rb, lib/puppet/interface/action.rb, lib/puppet/interface/action_builder.rb, lib/puppet/pops/loader/ruby_data_type_instantiator.rb, lib/puppet/pops/loader/ruby_function_instantiator.rb, lib/puppet/pops/loader/ruby_legacy_function_instantiator.rb, lib/puppet/provider/package/appdmg.rb, lib/puppet/provider/package/windows/package.rb, lib/puppet/util/command_line/trollop.rb, lib/puppet/util/execution.rb, spec/unit/provider/package/appdmg_spec.rb
=> (PUP-1172) Resolve Security cops 7.x

acceptance/tests/resource/service/ticket_5024_systemd_enabling_masked_service.rb, lib/puppet/settings.rb
There was a conflict due to gentoo and legacy vs structured facts. This resolves the systemd beaker test on amazon2023.
=> Merge 7.x to main

README.md
This commit updates the README's references to Jira to use GitHub issues instead. I have also updated references to Puppet versions in the README to more current versions.
=> Update issues URL

lib/puppet/application/resource.rb, lib/puppet/provider/service/systemd.rb, lib/puppet/provider/service/windows.rb, lib/puppet/type/service.rb, spec/unit/application/resource_spec.rb, spec/unit/provider/service/systemd_spec.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/type/service_spec.rb
Previously when Windows or SystemD attempted to managed a non-existant resource Puppet would just return that the service was stopped. This could be a bit confusing since if the service doesn't exist, that should be made explicit and we should do more then just returning that the service is in a 'stopped' state.
This change will cause Puppet to return an error message if a Windows/Systemd service is not found while trying to manage said service.
=> SystemD and Windows resources when not resource found will now return error

lib/puppet/application/resource.rb, lib/puppet/provider/service/systemd.rb, lib/puppet/provider/service/windows.rb, lib/puppet/type/service.rb, spec/unit/application/resource_spec.rb, spec/unit/provider/service/systemd_spec.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/type/service_spec.rb
Reverts puppetlabs/puppet#9175
This is failing in a few places with beaker-puppet in our pre-suites. We should make sure that is patched before we introduce this change.
Example failure looks like trying to force the service `iptables` to stop, even when it isn't running.
=> Revert "SystemD and Windows resources when not resource found will now return error"

lib/puppet/provider/service/redhat.rb, lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/redhat_spec.rb
Since CentOS7/RHEL7, systemd is used to manage services. This change changes the default provider in CentOS/RHEL from the old redhat provider based on init, to the systemd provider, so that we no longer need to update the provider code when adding support for a new version of CentOS/RHEL.
The old redhat provider is still used for CentOS/RHEL<7 which are using init to manage services.
=> (PUP-11433) Use systemd by default in CentOS/RHEL

lib/puppet/pops/evaluator/literal_evaluator.rb, lib/puppet/pops/validation/checker4_0.rb, spec/unit/info_service_spec.rb
=> (PUP-11981) Add test for non-literal class params in ClassInfoService spec

lib/puppet/provider/service/redhat.rb, lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/redhat_spec.rb
SystemD has been the default init system for Red Hat Enterprise Linux and its derivatives since RHEL 7 was released in 2014. In 928cf67, we attempted to reflect this in Puppet's service providers.
However, this change did not have the desired effect as the RedHat service provider was still specified as the default for systems with the os.family fact of "redhat." Tests relating to services started failing after 928cf67.
I do not believe that this change will have any undesired effects on Red Hat derivatives like Alma or Rocky because those distributions also use SystemD as their init system and use the same versioning scheme as upstream.
=> Correct Red Hat service providers

spec/unit/provider/service/systemd_spec.rb
This PR:
- Updates array in SystemD tests to use consistent styles and use string-array and symbol-array literals for brevity.
- Mocks the `os.family` fact in the SystemD nonexistent services tests to allow the test to run the Debian-specific code path, regardless of which platform the test is run on.
=> Clean up SystemD tests

lib/puppet/pops/evaluator/literal_evaluator.rb, lib/puppet/pops/issues.rb, lib/puppet/pops/validation/checker4_0.rb, spec/unit/info_service_spec.rb, spec/unit/pops/evaluator/literal_evaluator_spec.rb
Backport of #9190 and #9210 to 7.x
=> [Backport] (PUP-11981) Syntactically incorrect types cause nil types in Puppet::InfoService::ClassInformationService

.rubocop.yml, .rubocop_todo.yml, Gemfile
This PR enables the performance, Rake, and RSpec Rubocop extensions and configures them in the Rubocop configuration and todo files. This does not involve any code changes.
Note that I have pinned all of these gems at the last version that supported Ruby 2.5, matching with where we have Rubocop itself pinned and the version of Ruby we target in the Rubocop configuration file. We will update this in a future PR.
=> Enable Additional Rubocop Extensions

acceptance/config/aio/options.rb, acceptance/teardown/common/099_Archive_Logs.rb
=> (PA-4154) Add post-suite step to archive logs

lib/puppet/util/windows/registry.rb
RegQueryValueExW doesn't guarantee the returned buffer for the `lpData`
parameter is null terminated, so ensure that it is.
When retrieving a registry value of type REG_SZ or REG_EXPAND_SZ extend the
buffer by 1 wchar (2 bytes) so we can always write a wchar null terminator that
is guaranteed not to overwrite user data.
The resulting wchar array is then guaranteed to be properly wchar null
terminated:
\u0041
\u0042
\u0000
which when UTF-16LE encoded will result in the byte array:
\x41 \x00
\x42 \x00
\x00 \x00
If Windows does null terminate, then we will add an additional wchar null
terminator, which won't hurt anything.
The same applies to REG_MULTI_SZ, except it is supposed to have two wchar null
terminators, for a total of 4 bytes. One terminator is for the last string in
the array, and …
=> (PUP-11122) Ensure reg values are null terminated

.github/workflows/rspec_tests.yaml
A recent update to the Ruby GitHub Action added Ruby 3.2.3 for Windows: https://github.com/ruby/setup-ruby/pull/566/commits/591bd21fa67511786e99952dc1381fbd56353efe
That version of Ruby for Windows bundles OpenSSL 3.2. We bundle OpenSSL 3.0 in puppet-agent and the discrepancy between the two versions of
OpenSSL is causing some SSL tests to fail.
This commit pins the Ruby version for GitHub runners used in spec tests to 3.2.2.
=> Pin Windows Ruby to 3.2.2

lib/puppet/parameter/value.rb, lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/pops/parser/lexer2.rb, lib/puppet/pops/serialization/abstract_writer.rb, lib/puppet/pops/validation.rb, lib/puppet/provider/nameservice/directoryservice.rb, lib/puppet/provider/package/apt.rb, lib/puppet/provider/package/dnfmodule.rb, lib/puppet/provider/package/yum.rb, lib/puppet/provider/user/aix.rb, lib/puppet/util/checksums.rb, lib/puppet/util/logging.rb, lib/puppet/util/provider_features.rb
This PR comprises fixes to Rubocop layout cop violations to support updating Rubocop and its extensions in https://github.com/puppetlabs/puppet/pull/9222
=> Fix layout cops

lib/puppet/environments.rb, lib/puppet/external/dot.rb, lib/puppet/face/module/list.rb, lib/puppet/module_tool.rb, lib/puppet/module_tool/applications/upgrader.rb, lib/puppet/module_tool/shared_behaviors.rb, lib/puppet/network/format_handler.rb, lib/puppet/network/http/handler.rb, lib/puppet/node/environment.rb, lib/puppet/parser/functions/create_resources.rb, lib/puppet/pops/loader/module_loaders.rb, lib/puppet/provider/nameservice/directoryservice.rb, lib/puppet/provider/package/aptrpm.rb, lib/puppet/provider/package/pkgdmg.rb, lib/puppet/provider/user/directoryservice.rb, lib/puppet/resource/catalog.rb, lib/puppet/settings.rb, lib/puppet/type.rb, lib/puppet/type/user.rb, lib/puppet/util/command_line/trollop.rb
This PR comprises fixes to Rubocop performance cop violations to support updating Rubocop and its extensions in https://github.com/puppetlabs/puppet/pull/9222
=> Fix performance cops

acceptance/tests/resource/exec/should_run_command_in_cwd.rb, acceptance/tests/utf8/utf8-in-function-args.rb
en_US.UTF-8 support is not setup on the test image and session linger support is enabled by default
revert when the test images are rebuilt
needs backport
=> (PUP-12020) Skip tests on debian-12-amd64

acceptance/tests/resource/package/common_package_name_in_different_providers.rb, acceptance/tests/resource/package/yum.rb
Beaker's singular `agent` method can either return a single host or an array of hosts, depending on how many hosts have the agent role in your beaker config. For example, when running with `redhat7-64m-ubuntu2004-64a`, then it will return a single host. If running with `redhat7-64ma-ubuntu2004-64a`, then it will return an array of hosts[1].
The beaker `agent` method should never be used as it can cause tests to pass in agent CI, but fail in puppetserver CI, since they test the agent running on the server host.
Instead reference the `agents` method, which is guaranteed to exist and return an array, possible empty.
Also use the `fact_on` helper which parses the facter output as JSON and avoids having to chomp newlines in the output.
[1] …
=> Use agents beaker DSL method

ext/project_data.yaml
Previously our key and cert test fixtures were shipped in the gem, which
triggered security scanners. This deletes the `spec` directory from each
platform specific gem and reduces the size of each gem by about 1MB when
using the `bundle exec rake package:gem` task:
Before:
```
$ ls -la pkg/puppet-8.4.0.178.gem
-rw-rw-r-- 1 josh 1.5M Feb  9 11:21 pkg/puppet-8.4.0.178.gem
```
After:
```
$ ls -la pkg/puppet-8.4.0.177.gem
-rw-rw-r-- 1 josh 2.8M Feb  9 11:21 pkg/puppet-8.4.0.177.gem
```
For reasons described in PA-5400 we don't currently use `gem build .gemspec`
to build puppet gems.
No changes are needed to the .gemspec or Gemfile, because they both
include the content from project_data.yaml.
=> Drop specs when building gem

ext/project_data.yaml
Previously our key and cert test fixtures were shipped in the gem, which triggered security scanners. This deletes the `spec` directory from each platform specific gem and reduces the size of each gem by about 1MB when using the `bundle exec rake package:gem` task:
Before:
```
$ ls -la pkg/puppet-8.4.0.178.gem
-rw-rw-r-- 1 josh 1.5M Feb  9 11:21 pkg/puppet-8.4.0.178.gem
```
After:
```
$ ls -la pkg/puppet-8.4.0.177.gem
-rw-rw-r-- 1 josh 2.8M Feb  9 11:21 pkg/puppet-8.4.0.177.gem
```
For reasons described in PA-5400 we don't currently use `gem build .gemspec` to build puppet gems.
No changes are needed to the .gemspec or Gemfile, because they both include the content from project_data.yaml.
(cherry picked from commit 107a8e572450c1a178b309e0e38c0d30796a068d)
=> [Backport 7.x] Drop specs when building gem

acceptance/lib/puppet/acceptance/environment_utils.rb, acceptance/lib/puppet/acceptance/module_utils.rb, acceptance/lib/puppet/acceptance/service_utils.rb, acceptance/tests/agent/agent_disable_lockfile.rb, acceptance/tests/environment/can_enumerate_environments.rb, acceptance/tests/environment/directory_environment_production_created_master.rb, acceptance/tests/pluginsync/7316_faces_with_app_stubs_should_be_available_via_pluginsync.rb, acceptance/tests/resource/service/should_query_all.rb, acceptance/tests/ticket_13948_lib_dir_hook_should_be_called_on_initialization.rb
Previously in Beaker, you could use standalone stdout and stderr methods to access output from remote machines.
These methods were deprecated in 2013 with voxpupuli/beaker@28b2510 and dropped entirely in voxpupuli/beaker@73a31c7.
This commit updates any methods that were initially missed in the first pass of this work in commit 9f5f8e5.
=> Update Beaker result proxies on host object

acceptance/tests/resource/service/init_on_systemd.rb
Commit 9f5f8e5a eliminated the global `stdout`, but changed the block to return whatever the `on` method returned (which was a Beaker::Result object). Since the object is truthy, RHEL6 wasn't excluded.
This needs to be backported to 7.x
=> Return boolean instead of Beaker::Result

.gemspec, lib/puppet/version.rb
db7c196 accidentally bumped Puppet's version to "8.5.0x" instead of "8.6.0". This commit updates Puppet's version, both in the version file and gemspec, to 8.6.0.
=> (packaging) Bump to version '8.6.0' [no-promote]

lib/puppet/http/redirector.rb, spec/unit/http/client_spec.rb
Prior to this commit, Puppet would copy all request headers in an HTTP redirect, including Accept-Encoding. In some cases when HTTP compression was enabled, the response would fail to get decompressed, then would fail to get parsed and trigger a vague error.
This commit strips the Accept-Encoding headers on redirect, allowing Ruby's built-in Net::HTTP to both compress and decompress the traffic.
Resolves https://github.com/puppetlabs/puppet/issues/9143
=> Remove Accept-Encoding header on redirect

lib/puppet/application/resource.rb, lib/puppet/provider/service/systemd.rb, lib/puppet/provider/service/windows.rb, lib/puppet/type/service.rb, spec/unit/application/resource_spec.rb, spec/unit/provider/service/systemd_spec.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/type/service_spec.rb
When running `puppet resource service`, and the service does not exist, the application will return a 0 exit code and display that the service is not running.
This PR introduces a new option for the `puppet resource service` application, `--fail`, if the service is not found and the option is used, the application will return with a non-zero exit code, and display an error message.
Example of use:
```
[root@potent-image ~]# puppet resource service made_up_service ensure=running --fail
Error: Systemd start for made_up_service failed!
journalctl log for made_up_service:
-- No entries --
Error: /Service[made_up_service]/ensure: change from 'absent' to 'running' failed: Systemd start for made_up_service failed!
journalctl log for made_up_service:
-- No entries --
Error: Could not run: Failed …
```
=> Add options for failing resource check on command line

lib/puppet/pops/evaluator/literal_evaluator.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/unit/pops/evaluator/literal_evaluator_spec.rb, spec/unit/pops/validator/validator_spec.rb
Previously, class parameters of the form `Integer[-1] $param` would fail
compilation, because the value `-1` was lexed as a UnaryMinusExpression
containing a LiteralInteger. And since the LiteralEvaluator didn't implement the
`literal_UnaryMinusExpression` method, the visitor called `literal_XXX` for each
ancestor class, until reaching `literal_Object`, which always raises.
This adds the `literal_UnaryMinusExpression` method and returns -1 times
the expression it wraps. This is similar to how the TypeParser interprets
UnaryMinusExpressions[1].
If strict is off, the issue will be ignored. If strict is warning, then a
warning will be reported, but compilation will continue:
Warning: The parameter '$i' must be a literal type, not a Puppet::Pops::Model::AccessExpression
If strict is error, …
=> Accept UnaryMinusExpression as class parameter type

acceptance/tests/environment/should_find_existing_production_environment.rb, acceptance/tests/i18n/modules/puppet_agent.rb
The 'should_find_existing_production_environment' test is useful and will be re-enabled later using a module fixture.
```
❯ git grep -zl audit:high acceptance/tests | xargs -0 grep -l install_i18n
❯ 
```
This should be backported to 7.x
=> Stop installing i18n module from the forge during beaker tests

lib/puppet/pops/evaluator/literal_evaluator.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/unit/pops/evaluator/literal_evaluator_spec.rb, spec/unit/pops/validator/validator_spec.rb
https://github.com/puppetlabs/puppet/pull/9269
=> Backport #9269 to 8.5.1

lib/puppet/provider/package/pacman.rb, spec/unit/provider/package/pacman_spec.rb
This small patch adds an option to the pacman provider to purge config files.
From the manpage:
```console
$ pacman -R -h | head -n6
usage:  pacman {-R --remove} [options] <package(s)>
options:
-b, --dbpath <path>  set an alternate database location
-c, --cascade        remove packages and all packages that depend on them
-d, --nodeps         skip dependency version checks (-dd to skip all checks)
-n, --nosave         remove configuration files
```
=> package: pacman provider: Add purgeable feature

lib/puppet/defaults.rb, lib/puppet/indirector/catalog/rest.rb
Add's a new Puppet setting, skip_logging_catalog_request_destination, which defaults to false and if set to true when the catalog is compiled Puppet will not output which server supplied the used catalog.
=> (PUP-12023) Add option for disabling catalog messages

lib/puppet/reference/indirection.rb, lib/puppet/reference/metaparameter.rb, lib/puppet/reference/providers.rb, lib/puppet/reference/type.rb, spec/integration/application/doc_spec.rb
Some of the `puppet doc --reference <name>` commands failed after the switch to frozen literal strings. This dups strings in the same way we did in fb20023e1e2 and adds missing tests.
Also ignore the validator terminus for the resource model when generating docs.
=> Dup frozen strings

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
`pip freeze` (https://pip.pypa.io/en/stable/cli/pip_freeze/) "outputs installed packages in requirements format"
(https://pip.pypa.io/en/stable/reference/requirement-specifiers/). As of pip 19.1, pip also supports specifying a requirement as a URL, and, for packages that were installed using URL format, `pip freeze` will output package requirements in URL format.
However, Puppet's `pip freeze` parser doesn't support URL format, so it doesn't realize that a package is installed if it uses URL format, causing every `puppet agent` run to attempt to reinstall the package.
This PR adds support for parsing `pip freeze` URL format.
```console
$ pip3 install git+https://github.com/bootlin/pdf-link-checker.git
$ pip3 freeze --all | grep pdf
pdf-link-checker @ …
```
=> Support pip freeze URL format

lib/puppet/application/resource.rb, spec/unit/application/resource_spec.rb
See discussion in issue #9292.
What this PR adds is the ability for on the command line if --fail is passed then the `puppet resource` command will exit with a non zero return code.
=> (#9292) New command line flag for puppet resource, fail

lib/puppet/info_service/class_information_service.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/lib/puppet_spec/matchers.rb, spec/unit/info_service_spec.rb, spec/unit/pops/evaluator/literal_evaluator_spec.rb, spec/unit/pops/validator/validator_spec.rb
Previously, the ILLEGAL_NONLITERAL_PARAMETER_TYPE issue was under control of the `strict` setting. Since `strict` defaults to `error`, `puppet parser validate` logged an error message and exited non-zero for non-literal types such as `Integer[0, 60*24]`
In order to gradually phase out non-literal parameter types, this commit changes the issue to be a deprecation. When parsing and validating puppet code a warning is now logged, regardless of `strict`, and it exits with 0:
Warning: The parameter '$i' must be a literal type, not a ...
(file: /etc/puppetlabs/code/environments/production/manifests/site.pp,
line: 2, column: 19)
As a result of this change, the ClassInfoService error does not include locator information in the error hash:
{"error":"The parmeter '$i' is invalid: The expression …
=> (PUP-12026) Change non-literal type check to deprecation warning

lib/puppet/info_service/class_information_service.rb, lib/puppet/pops/validation/validator_factory_4_0.rb, spec/lib/puppet_spec/matchers.rb, spec/unit/info_service_spec.rb, spec/unit/pops/evaluator/literal_evaluator_spec.rb, spec/unit/pops/validator/validator_spec.rb
Previously, the ILLEGAL_NONLITERAL_PARAMETER_TYPE issue was under control of the `strict` setting. Since `strict` defaults to `error`, `puppet parser validate` logged an error message and exited non-zero for non-literal types such as `Integer[0, 60*24]`
In order to gradually phase out non-literal parameter types, this commit changes the issue to be a deprecation. When parsing and validating puppet code a warning is now logged, regardless of `strict`, and it exits with 0:
Warning: The parameter '$i' must be a literal type, not a ...
(file: /etc/puppetlabs/code/environments/production/manifests/site.pp,
line: 2, column: 19)
As a result of this change, the ClassInfoService error does not include locator information in the error hash:
{"error":"The parmeter '$i' is invalid: The expression …
=> [Backport] (PUP-12026) Change non-literal type check to deprecation warning

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
`pip freeze` (https://pip.pypa.io/en/stable/cli/pip_freeze/) "outputs installed packages in requirements format"
(https://pip.pypa.io/en/stable/reference/requirement-specifiers/). As of pip 19.1, pip also supports specifying a requirement as a URL, and, for packages that were installed using URL format, `pip freeze` will output package requirements in URL format.
However, Puppet's `pip freeze` parser doesn't support URL format, so it doesn't realize that a package is installed if it uses URL format, causing every `puppet agent` run to attempt to reinstall the package.
This PR adds support for parsing `pip freeze` URL format.
(cherry picked from commit 207a7dc7f271c9d97be400d0d2ebb80a5cda6cd2)
Backport: https://github.com/puppetlabs/puppet/pull/9280
=> [Backport 7.x] Support pip freeze URL format

ext/project_data.yaml
CFPropertyList up until 3.0.6 used the File.exists? method, which was deprecated in Ruby 2.7 and removed entirely in Ruby 3.2.
Because puppet-agent 8 vendors Ruby 3.2, this commit bumps CFPropertyList's dependency from ~> 2.2 to >= 3.0.6.
See also: https://github.com/puppetlabs/puppet-runtime/commit/0977603530285ce5af113a5378d7a75fb4c8d624
=> Bump CFPropertyList to >= 3.0.6

lib/puppet/type/exec.rb
This is probably not what most people would expect...
=> Document passing an array to exec creates

lib/puppet/util/rpm_compare.rb, spec/shared_examples/rhel_package_provider.rb, spec/unit/util/rpm_compare_spec.rb
Commit 3a548510ee detected cases where the "architecture was in the title of a package and moves it to the end of the version string" such as ".86_64" But the noarch regex matched any occurrence "noarch", including "-noarch". That bug was fixed in commit ca36fc66ae. This commit adds some missing tests and refactors the regex.
=> Add tests for -noarch

lib/puppet/util/command_line/trollop.rb, spec/unit/util/command_line_utils/puppet_option_parser_spec.rb
This commit modifies how partial matches are handled when parsing global command line options. Before, Puppet would accept and do nothing with options global options that use '-' instead of '_'. For example, it would accept '--show-diff' and do nothing when the correct name is '--show_diff'.
With this change, while handling any global options given in the command line options, if the command line option does not match existing global options, it will convert '-' to '_' and vice versa. Then, check if that matches a valid global option. Additionally, if the command line option needs to convert '-' to '_' or vice versa, Puppet will also warn to let the user know a partial match was detected and this behavior will be deprecated in Puppet 9.
=> (PUP-11693) Global OptionParser ignores partially matched invalid params

lib/puppet/util/command_line/trollop.rb, spec/unit/util/command_line_utils/puppet_option_parser_spec.rb
This commit updates the Global OptionParser (Trollop) to only warn when the passed in argument partially matches a valid global option. Additionally, the warning is more descriptive now and includes the argument given and the correct global option.
=> (PUP-11693) Update behavior when partial argument match detected

Gemfile, puppet.gemspec
ffi 1.16.0 - 1.16.2 had a bug when defining a layout in an FFI::Struct and it was fixed in 1.16.3.
See https://github.com/puppetlabs/facter/pull/2707
=> Accept ffi >= 1.16.3, < 1.17.0

lib/puppet/pops/lookup/module_data_provider.rb, spec/unit/functions/lookup_fixture_spec.rb
Puppet::Pops::Lookup::ModuleDataProvider#validate_data_hash is a method that is supposed to prune a data hash of any keys that are not prefixed with a given module's name. However prior to this commit it incorrectly took the data hash, cloned it, operated on the clone, then returned the unchanged original hash.
This commit updates validate_data_hash to instead return the modified hash, and updates the warning message generated when a key is pruned to include the key.
=> Update validate_data_hash to return modified hash

lib/puppet/provider/group/groupadd.rb, spec/unit/provider/group/groupadd_spec.rb
- Starting from version 40, Fedora does not have the lgroup* commands available due to deprecation of libuser: https://fedoraproject.org/wiki/Changes/LibuserDeprecation.
- groupadd relies on libuser to add/purge members to/from groups.
- Add manages_members feature to Fedora 40 and above since groupmod can add members to groups now. Historically, it was unable to do so that's why puppet used lgroupmod for it.
- Handle flags for lgroupmod (-M) and groupmod (-aU) commands properly.
- Only use lgroup* commands if libuser is supported.
- When libuser is not supported, members should be purged using the usermod command. Since usermod does not support comma separated list of users they should be removed one by one.
=> (PUP-12041) Handle libuser's unavailability in Fedora 40

.github/workflows/rspec_tests.yaml, lib/puppet/node/environment.rb, spec/unit/file_system/path_pattern_spec.rb
This commit updates JRuby to 9.3.14.0 in tests. This version of JRuby addresses a bug with Dir.glob (see jruby/jruby@5b06409) that we had previously worked around in both code and tests (see 663062a). Because the Dir.glob bug has now been addressed, this commit also removes the workarounds we had added.
=> Bump to JRuby 9.3.14.0, reenable test

lib/puppet/provider/aix_object.rb
The cop is unsafe and changing it breaks test, so disable it
=> Disable Style/SymbolProc in aix object

Rakefile, puppet.gemspec
Adds `pl_ci:nightly_gem_build` The only difference from `gem_build` is that the nightly version uses the extended dot version as the version string in the gemspec (and therefore resulting filename). Based on https://github.com/puppetlabs/facter/pull/2726
=> (PA-6427) Add rake tasks for building nightly gem 

.github/workflows/rspec_tests.yaml, spec/integration/directory_environments_spec.rb, spec/integration/node/environment_spec.rb, spec/unit/file_system_spec.rb, spec/unit/util/autoload_spec.rb
Tests started failing with a new GH Windows Server runner 20240526.1.1. The
previous version worked 20240514.1.0. Mark as pending until we can determine the
cause.
As noted in https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
> When you create a long file name, Windows may also create a short 8.3 form of the name, called the 8.3 alias or short name, and store it on disk also. This 8.3 aliasing can be disabled for performance reasons either system-wide or for a specified volume, depending on the particular file system.
> On many file systems, a file name will contain a tilde (~) within each component of the name that is too long to comply with 8.3 naming rules. ... Not all file systems follow the tilde substitution convention, and systems can be configured to disable 8.3 …
=> Mark some failing 8.3 Windows tests as pending

.github/workflows/rspec_tests.yaml, spec/integration/directory_environments_spec.rb, spec/integration/node/environment_spec.rb, spec/unit/file_system_spec.rb, spec/unit/util/autoload_spec.rb
Backport https://github.com/puppetlabs/puppet/pull/9368
Since this modifies the `.github/workflows` directory it must be manually backported
=> [Backport 7.x] Mark some failing 8.3 Windows tests as pending

Rakefile, puppet.gemspec
Backport https://github.com/puppetlabs/puppet/pull/9364
```
$ bx rake pl_ci:gem_build
Successfully built RubyGem
Name: puppet
Version: 7.31.0
File: puppet-7.31.0-x86-mingw32.gem
Successfully built RubyGem
Name: puppet
Version: 7.31.0
File: puppet-7.31.0-x64-mingw32.gem
Successfully built RubyGem
Name: puppet
Version: 7.31.0
File: puppet-7.31.0-universal-darwin.gem
Successfully built RubyGem
Name: puppet
Version: 7.31.0
File: puppet-7.31.0.gem
$ bx rake pl_ci:nightly_gem_build
Successfully built RubyGem
Name: puppet
Version: 7.30.0.18.g08f61e6
File: puppet-7.30.0.18.g08f61e6-x86-mingw32.gem
Successfully built RubyGem
Name: puppet
Version: 7.30.0.18.g08f61e6
File: puppet-7.30.0.18.g08f61e6-x64-mingw32.gem
Successfully built RubyGem
Name: puppet
Version: 7.30.0.18.g08f61e6
File: …
```
=> [Backport 7.x] Add rake tasks for building nightly gem

lib/puppet/provider/package/xbps.rb, spec/unit/provider/package/xbps_spec.rb
I wanted to use puppet on void-linux, so this PR adds the package provider for xbps.
Let me know if any changes has to be made :)
=> (maint) Add xbps used by voidlinux as a package provider

lib/puppet/daemon.rb, lib/puppet/scheduler/splay_job.rb, spec/unit/daemon_spec.rb
Prior to this commit, updates to splay settings in the Puppet configuration file (puppet.conf) would not get picked up in a daemonized Puppet run.
This commit updates the daemon class to call a new public method in the splay job class to update the splaylimit.
=> Update splaylimit during daemon run

puppet.gemspec
fast_gettext 3 was released yesterday and it basically dropped support for Ruby 2.7. Pulling in version 3 is fine because puppet 8 already requires Ruby 3.1 or newer.
=> fast_gettext: Allow 3.x

acceptance/tests/windows/service_manager_integration.rb, lib/puppet/util/windows/daemon.rb
=> [Backport 7.x] Stop using FFI threads and use ruby threads for the windows puppet daemon

lib/puppet/util/execution.rb, spec/unit/util/execution_spec.rb
On Windows, if squelch was false and Uniquefile.new raised, then we attempted to
close a nil stdout. This scenario can occur if TEMP or similar environment
variable is defined but refers to a non-existent directory.
So check for nil before closing. We don't have this issue on posix, because
it uses an IO pipe instead of Uniquefile.
Fixes https://github.com/puppetlabs/puppet/issues/9385
=> Check for nil before closing Uniquefile

lib/puppet/application/lookup.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/node/server_facts.rb, spec/fixtures/unit/application/environments/production/data/common.yaml, spec/unit/application/lookup_spec.rb
During normal catalog compilation, server facts are added by the `compiler`
terminus prior to calling `Puppet::Parser::Compiler.compile`[1]. However, the
lookup application directly calls `Compiler.compile`, bypassing the `compiler`
terminus[2]. Therefore, server facts weren't being added when running the lookup
command.
Ideally, catalog compilation and the lookup command would compile the catalog in
the same way, but changing that is risky. For that to work, we would need to
pass the already resolved node and facts to the `compiler` terminus and the
terminus would need to add server facts to the node. However, the terminus
doesn't add server facts if the node is passed in. It only does that if it
resolves the node using the indirector[3].
Rather than mess with the terminus and break …
=> Add server facts when looking up values

lib/puppet/functions/regsubst.rb
As far as I can tell, Regexp.compile has never accepted a third parameter to Regexp.compile until Ruby 3.2. There it actually is a timeout parameter. In older versions it was discarded as an invalid input. It's unclear to me if this parameter ever worked in the first place.
This PR attemps to still make it work as it was originally intended, but it's unclear what the original goal even was. Perhaps it's better to make an incompatible change to drop the third parameter and instead enhance the flags parameter to support `N` as a value.
=> Respect Regexp.compile method signature

lib/puppet/application/lookup.rb, lib/puppet/indirector/catalog/compiler.rb, lib/puppet/node/server_facts.rb, spec/fixtures/unit/application/environments/production/data/common.yaml, spec/unit/application/lookup_spec.rb
Manual backport of #9392 due to legacy facts in puppet 7
=> [Backport 7.x] Add server facts when looking up values

ext/windows/service/daemon.rb
Previously when Puppet parsed a runinterval of 0 on Windows, it would set the runinterval to 1800 seconds, Puppet's default runinterval value. This was incorrect behavior, as on other platforms and in the documentation, a runinterval of 0 indicates that Puppet should run continuously.
This commit updates the Windows daemon to set the runinterval to 1800 seconds when it receives an empty string and cast to integer in all other cases.
=> (PUP-1881) Correct Windows runinterval behavior

.github/workflows/rspec_tests.yaml
The setup-ruby action makes it trivial to bundle install gems from a cache and update the cache when the run completes.
When using `bundler-cache`, we can't use `bundle config` commands, but we can achieve the same effect specifying BUNDLE_SET as an env variable.
See https://github.com/ruby/setup-ruby for details
On Ubuntu 22.04:
```
> bundle install
/opt/hostedtoolcache/Ruby/3.2.4/x64/bin/bundle config --local path /home/runner/work/puppet/puppet/vendor/bundle
/opt/hostedtoolcache/Ruby/3.2.4/x64/bin/bundle lock
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Writing lockfile to /home/runner/work/puppet/puppet/Gemfile.lock
Cache key: setup-ruby-bundler-cache-v6-ubuntu-22.04-x64-ruby-3.2.4-wd-/home/runner/work/puppet/puppet-with--without--only--Gemfile.lo …
```
=> Use bundler-cache to bundle install and cache gems

.github/workflows/rspec_tests.yaml
The setup-ruby action makes it trivial to bundle install gems from a cache and update the cache when the run completes.
When using `bundler-cache`, we can't use `bundle config` commands, but we can achieve the same effect specifying BUNDLE_SET as an env variable.
See https://github.com/ruby/setup-ruby for details
(cherry picked from commit 86820eee25e428f7e667bf9529b97c32e6575d9b)
=> [Backport 7.x] Use bundler-cache to bundle install and cache gems

Gemfile, puppet.gemspec, spec/unit/interface_spec.rb
Running puppet with Ruby 3.3.0 prints:
$ bundle exec puppet --version
/home/josh/work/puppet/lib/puppet/settings.rb:4: warning: getoptlong was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add getoptlong to your Gemfile or gemspec.
/home/josh/work/puppet/lib/puppet/util/feature.rb:116: warning: syslog was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add syslog to your Gemfile or gemspec.
Since getoptlong is necessary to parse the command line and is a pure ruby gem,
it's safe to add it as a runtime dependency in puppet.gemspec.
Since syslog is a feature and requires native extensions, add it to the features
group in the Gemfile. It will also need to be added to the runtime on …
=> (PUP-12029) Prepare for Ruby 3.3

lib/puppet/defaults.rb, lib/puppet/provider/package/gem.rb, lib/puppet/provider/package/puppet_gem.rb, lib/puppet/util/run_mode.rb, spec/unit/provider/package/puppet_gem_spec.rb, spec/unit/provider/package/puppetserver_gem_spec.rb, spec/unit/util/run_mode_spec.rb
The run mode already determines the platform. Moving all platform specific paths into RunMode makes it easier to get a complete overview and change things where needed.
@ekohl originally filed this #8938. I've retargeted his commit for `main` and updated some spec failures.
=> (PUP-11655) Use run_mode for better platform independence

lib/puppet/file_serving/http_metadata.rb
This commit adds logic in `http_metadata.rb` to skip MD5 related checksums when FIPS is enabled since MD5 is not supported on FIPS enabled systems. This PR addresses https://github.com/puppetlabs/puppet/issues/9375.
=> (PUP-12047) Add logic to skip MD5 checksum method on a FIPS system

lib/puppet/application/doc.rb, lib/puppet/module_tool/tar/gnu.rb, lib/puppet/parser/functions/generate.rb, lib/puppet/type/file/target.rb, lib/puppet/util/reference.rb, spec/unit/module_tool/tar/gnu_spec.rb, spec/unit/parser/functions/generate_spec.rb
Dir.chdir is problematic because it affects all threads in the current process
and if puppet is started with a current working directory it doesn't have
traverse/execute permission to, then it won't be able to restore the cwd at the
end of the Dir.chdir block.
Puppet supports two execution implementations (posix and windows), both of which
already support the `cwd` option. Puppetserver also injects its external
implementation using the execution_stub. Its execution implementation now
supports the `cwd` option, see SERVER-3051.
Also pass the directory in which to extract modules to the `tar` command.
This should not be backported to 7.x
=> (PUP-9997) Avoid Dir.chdir

spec/unit/file_serving/http_metadata_spec.rb
This commit adds a test to http_metadata_spec.rb that checks that the MD5 checksum type is skipped in the collect method on FIPS enabled platforms.
=> (PUP-12047) Add test to ensure MD5 checksum is skipped for FIPS

lib/puppet/pops/evaluator/runtime3_resource_support.rb, lib/puppet/pops/evaluator/runtime3_support.rb, lib/puppet/provider/package/pkgutil.rb
rubocop 1.65.0 fixed false negatives for Lint/Void, which highlighted some bugs where the guard clauses weren't doing anything.
Commit 01db61e241 moved code from runtime3_support to runtime3_resource_support:
* Runtime3Support is modified to use Runtime3ResourceSupport instead of
directly containing the methods for resource search and creation.
But the `resource_to_ptype` method was copied instead of moved. So delete it from Runtime3Support.
This should not be backported to 7.x, since we're constrained to an older version: https://github.com/puppetlabs/puppet/blob/46e88b416de67c85ee32b42395a6464ee9397342/Gemfile#L55
=> Add missing return

lib/puppet/pops/evaluator/deferred_resolver.rb, spec/integration/application/apply_spec.rb, spec/unit/pops/evaluator/deferred_resolver_spec.rb
Previously, a manifest containing nested Deferred values did not mark the corresponding parameter as sensitive, resulting in the following:
$ cat manifest.pp
$vars = {'token' => Deferred('new', [Sensitive, "password"])}
file { '/tmp/a.sh':
ensure  => file,
content => Deferred('inline_epp', ['<%= $token %>', $vars])
}
$ truncate --size 0 /tmp/a.sh
$ puppet apply --show_diff manifest.pp
Notice: Compiled catalog for localhost in environment production in 0.01 seconds
Notice: /Stage[main]/Main/File[/tmp/a.sh]/content:
--- /tmp/a.sh	2024-07-03 17:30:37.024543314 -0700
+++ /tmp/puppet-file20240703-1784698-2cu5s9	2024-07-03 17:30:41.880572413 -0700
@@ -0,0 +1 @@
+password
\ No newline at end of file
The issue occurred because we were only checking if the outermost DeferredValue contained any …
=> (PUP-12050) Check for nested Sensitive arguments

lib/puppet/pops/evaluator/deferred_resolver.rb, spec/integration/application/apply_spec.rb, spec/unit/pops/evaluator/deferred_resolver_spec.rb
Backport https://github.com/puppetlabs/puppet/pull/9410 to 7.x
=> [Backport 7.x] (PUP-12050) Check for nested Sensitive arguments

install.rb
I was trying to figure out how to do the install parts for https://github.com/puppetlabs/puppet/pull/8636 and trying to make sense of the install script. In doing so I found some things that have been unused for ages. Things get easier to understand if there's less stuff, so this helps a bit.
=> Remove deprecated DESTDIR and unused things from install.rb

lib/puppet/functions/hiera.rb, lib/puppet/functions/yaml_data.rb
Added a newline between the require statement and start of documentation to work around https://github.com/puppetlabs/puppet-strings/issues/296
To verify, run:
echo 'gem "puppet-strings"' >> Gemfile.local
bundle update
bundle exec puppet strings generate --format json --out /tmp/strings.json
jq -r '.puppet_functions[] | select(.name == "yaml_data").docstring.text ' /tmp/strings.json | head
This should be backported to 7.x
=> Workaround strings bug when generating function docs

puppet.gemspec
This reconciles both the version.rb and gemspec to the same version number (7.33.0).
=> (packaging) Bump to version '7.33.0' [no-promote]

puppet.gemspec
This reconciles both the version.rb and gemspec to the same version number (8.9.0).
=> (packaging) Bump to version '8.9.0' [no-promote]

lib/puppet/resource/type.rb, spec/integration/parser/node_spec.rb
Before this commit, two nodes could collide due to the lookaround Regex pattern. This issue arose because the regex was converted to a regular string by ignoring characters other than a-z, 0-9, _, and -.
For example, /(?<!a)sync/ was converted to "__node_regexp__async," and /async/ was also converted to "__node_regexp__async," causing an error that the node was already defined.
To prevent such duplication, this commit normalize the lookarround pattern from the regex, ensuring a unique string in case of lookarround pattern conflict.
For example, /(?<!a)sync/ will converted to "__node_regexp__LPQULTEXaRPsync" replacing (?<!a) to "LPQULTEXaRP" while converting to the string.
=> (PUP-11515) Negative Lookbehind Regex Causes Duplicate Node

lib/puppet/provider/package/pacman.rb, spec/unit/provider/package/pacman_spec.rb
This is a regression from https://github.com/puppetlabs/puppet/commit/d23d6dbfd2e578016441ab292d934b4d74ab436f
During some cleanup, the command
```
pacman pacman --noconfirm --noprogressbar -Sy
```
got modified to:
```
pacman pacman --noconfirm --noprogressbar -S
```
But this isn't a valid command anymore:
```
root@bastelfreak-nb ~ # pacman --noconfirm --noprogressbar -S
error: no targets specified (use -h for help)
root@bastelfreak-nb ~ #
```
The idea was to prevent partial system upgrades while installing new packages. To do this, the `sync` option was removed from the installation routine. The correct fix is to remove the command completely.
=> Remove broken pacman command for installing packages 

lib/puppet/application/apply.rb, lib/puppet/application/ssl.rb, lib/puppet/defaults.rb, lib/puppet/functions/capitalize.rb, lib/puppet/functions/find_file.rb, lib/puppet/functions/index.rb, lib/puppet/functions/lookup.rb, lib/puppet/functions/new.rb, lib/puppet/functions/regsubst.rb, lib/puppet/functions/unique.rb, lib/puppet/type/exec.rb, lib/puppet/type/file/checksum.rb, lib/puppet/type/file/ctime.rb, lib/puppet/type/file/mtime.rb, lib/puppet/type/file/selcontext.rb, lib/puppet/type/package.rb, lib/puppet/type/user.rb, lib/puppet/util/checksums.rb
Pull in changes that were made in osp-docs
puppetlabs/osp-docs@f24d9b3c066ebd9624ebc0a0d163dd47b330469c
puppetlabs/osp-docs@c3fec1488fc74a9e349cef8c9725b4b5927d8b65
puppetlabs/osp-docs@27fa002f08432040cff0020689834ae5be5f85e8
puppetlabs/osp-docs@27fa002f08432040cff0020689834ae5be5f85e8
puppetlabs/osp-docs@f8fc805d1b18df6141ab8e45947f9fa1307a4ee2
puppetlabs/osp-docs@4a448c8bcc4d1851f570459c46c9ccaa88f1f4f3
puppetlabs/osp-docs@1914d58d5fc57ac997e25367272160c4cf28b8a7
puppetlabs/osp-docs@e1b7ffa9ffe2fd51adb2c6ab8fdf10bb9610eaca
Also includes changes requested in https://github.com/puppetlabs/osp-docs/pull/347
=> (PUP-12063) Merge osp-docs changes back to puppet

lib/puppet/type/file/selcontext.rb, lib/puppet/util/selinux.rb, spec/unit/type/file/selinux_spec.rb, spec/unit/util/selinux_spec.rb
Fixes https://github.com/puppetlabs/puppet/issues/9431
Supersedes https://github.com/puppetlabs/puppet/pull/9437
This PR reproduces much of the mode-related functionality of the now-deprecated matchpathcon codepath. This is important because without this, Puppet determines an incorrect SELinux label to apply to files -- i.e. it does not match what restorecon would do -- which is important because correct SELinux labelling is a necessity in order to ensure that policy is applied correctly.
=> Add file mode-awareness to selabel_lookup

spec/integration/parser/collection_spec.rb
rspec-expectations recently released v3.13.2, which includes a change to the include matcher (see rspec/rspec-expectations@bd5d306).
This change breaks using the splat operator on an array into the include matcher.
This commit updates the matcher to iterate over the array instead of using the splat operator.
=> Fix include matcher behavior

ext/project_data.yaml
Previously, Puppet relied on the in-house Packaging library to build all artifacts related to Puppet. Puppet moved away from using Packaging to build gems in 867ce9c, which also removed the files key used to build tarballs.
This commit re-adds the files key (as a list instead of a string, as recommended by Packaging) to enable the packaging:tar Rake task, which builds source tarballs of Puppet.
=> Add files to include in tarball

lib/puppet/application/filebucket.rb, lib/puppet/face/catalog.rb
Updates based on feedback:
1. Avoid making promises about future releases ... (so) avoid the word "yet."
2. We assume that users are reading the documentation while they use the product, so we write in the present tense.
3. Avoid the "Note" label because it doesn't tell users anything about the content of the note. Users can't tell whether the note will present crucial information or be just a tip. In this case, we could use the "Important" or "Restriction" label instead.
=> Documentation updates

lib/puppet/settings.rb, rakelib/generate_references.rake, rakelib/references/configuration.erb, references/configuration.md
bundle exec rake references:configuration
It runs `puppet doc -r configuration` to generate references/configuration.md.
In order for the output to not be dependent on the hostname/domain facts, allow them to be overridden as an environment variable. This can't be done using FACTER_*, because structured facts like `networking.hostname` can't be overridden by an env variable.
To determine if any meaningful changes have been made, you can run:
git diff  -I built_from_commit -I 'This page was generated from the Puppet source code' references/
=> (PUP-12065) Add task to generate configuration reference

lib/puppet/face/help.rb, lib/puppet/reference/configuration.rb, man/man5/puppet.conf.5, man/man8/puppet.8, rakelib/man/puppet.erb, rakelib/manpages.rake
Previously, the man/man8/puppet.8 man page wasn't formatted correctly
with each subcommand and summary on a new line. This was because
`puppet --help` doesn't output ronn format, just raw text. So generate
`puppet.8.ronn` in valid ronn format so that it can be converted to
roff. Use `man --local-file man/man8/puppet.8` to verify the results.
Also don't blindly run `<bin>/<app> --help` for every app. That's left
over from when puppet had multiple bin stubs.
Since ronn shells out to groff, abort if the latter is not installed.
Hardcode the http_user_agent value so it's not sensitive to the puppet
version or the ruby version/architecture the user is running.
=> (PUP-12075) Render puppet man page correctly

rakelib/manpages.rake
If groff is not installed, ronn will warn, but continue along, so don't require it.
=> Don't require groff

Gemfile, rakelib/generate_references.rake, rakelib/manpages.rake, rakelib/references/function.erb, rakelib/references/functions_template.erb, references/function.md
bundle exec rake references:function
This task uses puppet strings to generate references/function.md.
The task requires the puppet-strings gems, so add it to the documentation
bundler group. Since the group is optional, check to see if the gem is present
before trying to load it, similar to how we handle ronn.
If there are both 3.x and 4.x functions with the same name, we ignore the 3.x
version and document the 4.x version.
This code is adapted from puppet-docs. The old code had a bug as it used to
replace /####\s/ with '###\s' resulting in a literal '\s' in the header for
some functions.
If `puppet-strings` gem is installed, then the man page generation will include
strings as a new application type. Since we don't actually ship strings
in puppet, hide it from man page generation.
=> (PUP-12064) Add task to generate function reference

lib/puppet/reference/configuration.rb, lib/puppet/settings.rb, rakelib/generate_references.rake
Rather than introducing new environment variables, just hard code the default value in the config reference like we do for others.
See also c5c7fc8412497647aa1a591e39067f1440e51a2b
=> Hardcode hostname and domain

lib/puppet/provider/service/systemd.rb, spec/unit/provider/service/systemd_spec.rb
Select systemd as the default service provider
Author: James Evans <54334+jaevans@users.noreply.github.com>
Supersedes https://github.com/puppetlabs/puppet/pull/9170
=> (PUP-11949) Set systemd as default for Raspbian 12

.github/workflows/references.yaml
When a commit is pushed to main, build all of the references, including man pages. If the only changes are due to SHA and dates, then do nothing. Otherwise, commit all of the references and man pages.
The action is only triggered when a commit is pushed to main, but not on pull requests so that we don't have to worry about untrusted inputs.
The action is only triggered when the repo owner is puppetlabs, so it won't trigger on forks.
The action uses full SHAs for the pandoc and add-and-commit actions.
If changes are detected, the action creates a commit whose author is GitHub Actions <actions@github.com> with message:
Update references [no-promote]
And pushes the commit to the main branch. It uses the repository's GITHUB_TOKEN to accomplish this. We don't need to worry about recursive …
=> (PUP-12055) Build references on commit to main

lib/puppet/provider/package/pip.rb, spec/unit/provider/package/pip_spec.rb
When searching for versions of a Pip module a regex we depend on needs to be updated to work with Pip version 24.
=> (maint) Update pip provider regex

.github/workflows/references.yaml
This commit updates the GitHub Aciton used to generate reference documentation to use the token of the puppet-release-bot GitHub user to check out code. This should enable the action to push to the protected main branch, which it was unable to before.
=> Use token to check out reference action

lib/puppet.rb, lib/puppet/application/resource.rb, lib/puppet/resource.rb, spec/integration/application/apply_spec.rb, spec/unit/application/resource_spec.rb, spec/unit/resource/catalog_spec.rb, spec/unit/resource_spec.rb
Since Puppet 6.0 "datafication" has inspected the context for the value
of rich_data. However, in only some code paths does the value in the
context get overridden with a value taken from the settings. This means
in some cases the rich_data value will always be true or always be
false, regardless of how the user has configured the rich_data setting.
And, in the case the simply calling `to_data_hash` on a resource the
rich_data value will always be false.
This updates the base_context to set rich_data to the settings value,
ensuring that the default value for rich_data in the context is the
value users have set.
Additional changes are primarily where tests still assumed the default
value of rich_data was false, with one exception - YAML serialization in
the resource application will break …
=> (PUP-12077) Respect rich_data setting in base context

lib/puppet/defaults.rb
This commit increases default value of `number_of_facts_soft_limit` from 2048 to 2048 * 5 = 10240.
2048 is too small for `number_of_facts_soft_limit` because:
- The `_package_inventory_1` fact in PE will report packages present by multiple providers which results in a package being reported up to 3 times and `_package_inventory_1` to be have many more fact values than expected
- A default PE install reports 5019 fact values which already exceeds the previous limit, 2048.
Taking into account the issues above and the feedback from Vox Pupuli in the Puppet Community Slack about their fact count, 10240 is a more suitable limit.
=> (PUP-12071) Increase default value for number_of_facts_soft_limit

ext/windows/service/daemon.rb
This line is not sane for the setting of the log_level default (because specifying `--log_level` on the command line always takes precedence over what's specified in puppet.conf)
loglevel = %x{ #{puppet_path} config --section agent --log_level notice print log_level }.chomp
It sets log_level to notice, and then return the output of the log_level setting
loglevel = "notice"
is the same thing with fewer steps
Author: Marty Ewings <martyewings@gmail.com>
Supersedes PR #8958
=> (maint) Remove needless check in setting  default

acceptance/tests/ssl/certificate_extensions.rb
We are encountering an issue with tests running on AIX due to incorrect system time. While we are waiting on a permanent fix in ITHELP-99479, this temporary workaround sets the timesync property on the Beaker host object to "true" if the host is AIX.
=> (PA-7090) Correct system time on AIX

Gemfile, puppet.gemspec
The syslog gem moves from default gems to a normal gem in Ruby 3.4. It raises the following warning on Ruby 3.3.5:
```
lib/puppet/util/command_line.rb:14: warning: syslog was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add syslog to your Gemfile or gemspec to silence this warning.
```
The ostruct gem moves from default gems to a normal gem in Ruby 3.5. It raises the following warning on Ruby 3.3.5:
```
lib/puppet/util/command_line.rb:14: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```
=> Add syslog & ostruct as runtime dependencies

lib/puppet/functions/regsubst.rb, spec/unit/functions/regsubst_spec.rb
[PUP-11326](https://tickets.puppetlabs.com/browse/PUP-11326)
Possible Use-Case [out of Real-Life](https://github.com/Icinga/puppet-icinga2/blob/master/manifests/feature/gelf.pp#L100):  
```
$_ssl_key = $::facts['os']['family'] ? {                           
'windows' => regsubst($ssl_key, '\n', "\r\n", 'EMG'),            
default   => $ssl_key,                                           
}
```
=> (PUP-11326) Make regsubst() sensitive-aware

.github/workflows/rspec_tests.yaml, .rubocop_todo.yml
Temporarily pin Windows Ruby 3.2 rspec check test to Ruby 3.2.5 to resolve the OpenSSL errors that popped up when using Ruby 3.2.6. This should be reverted once PA-7108 is resolved.
=> (PA-7108) Temporarily pin Windows Ruby 3.2 rspec check to Ruby 3.2.5

lib/puppet/configurer.rb, spec/unit/configurer_spec.rb
This commit updates the soft limit warning for fact value length to include
the fact name and updates the soft limit warning for fact name length to
include the length that was used to evaluate if the length exceeds the limit.
=> (PUP-12083) Update soft limit warning for fact value length and fact name length

acceptance/lib/puppet/acceptance/rpm_util.rb
This PR addresses an issue with an older version of OpenSSH in our Red Hat 9 images with a temporary workaround.
=> Fix tests on Red Hat 9

lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb, spec/unit/provider/package/puppetserver_gem_spec.rb
A new JSON gem release (2.8.0) changed how empty arrays and hashes are pretty printed. This PR updates Puppet to maintain past behavior and adds a test for empty hashes.
Ruby also released a new URI gem (1.0.0) this month that adds a space to their error messages. This PR updates our test to reflect that.
=> JSON and URI updates

.rubocop_todo.yml, lib/puppet/face/facts.rb, spec/unit/application/facts_spec.rb, spec/unit/provider/package/puppetserver_gem_spec.rb
This PR comprises several fixes for tests and checks including:
- Updating a test to handle the URI version used in newer Rubies (> 3.0)
- Handle the change in behavior in newer JSON versions for empty arrays and hashes
- Exclude files for Style/AccessModifierDeclarations cop
=> Check fixes
